### ISSUE TITLE
[TBD] DecoratorNode tied to React

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1014]
Is it correct that DecoratorNode is tied to React? AFAIK Outline should be library agnostic and/or provide a mechanism for other libraries to integrate just fine with it. Can we have `decorate(): any` instead of `decorator(): React$Node` to offer a more generic mechanism?

**Comment by CRIMSON-CORP** [comment]
Hello, Please how can i work with the ImageNode on Vanilla js? ive tried returning an image element in the decorate method, but it doesnt work


  decorate() {
      const image = document.createElement("img");
      image.alt = this.__altText;
    image.src = this.__src;
    image.width = this.__width;
    image.height = this.__height;
    image.style.maxWidth = this.maxWidth;
    return image;
  }
  
  Pls assist

**Comment by acemtp** [comment]
same for me, i tried basic DOM in a DecoratorNode and it's not working. 
They say it's agnostic but it doesn't seem to be agnostic at all but React only.

**Comment by etrepum** [comment]
See HorizontalRuleNode for an example of a decorator that does not depend on React. 
https://github.com/facebook/lexical/blob/main/packages/lexical-extension/src/HorizontalRuleExtension.ts
