### ISSUE TITLE
Adjust the playground CSS to support RTL

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1021]
Some pieces are a bit off, especially the TreeView

<img width="1439" alt="Screen Shot 2021-12-15 at 5 58 05 pm" src="https://user-images.githubusercontent.com/193447/146240009-e540d3f0-ae3d-470a-b249-3b6fe34863ae.png">

**Comment by thegreatercurve** [comment]
Yeah, I guess we don't really need to do this if we don't surface internationalisation options in the UI
