### ISSUE TITLE
Add auto date/time formatting

### ISSUE THREAD

**Issue by trueadm** [facebook/lexical#1102]
When adding a date/time it would be great if this could be auto formatted as a plugin. The functionality should work like it does in Quip.

**Comment by armelpingault** [comment]
I guess you are talking about this feature?

When you type for example `06/30`, you see a popover below suggesting to turn it into a date if you click on it:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/6302123/176757027-e3f30d5c-b1f9-4271-9ba8-beba17c54e3c.png">

Once you click on the popover, the text turns into a Date Picker:
<img width="294" alt="image" src="https://user-images.githubusercontent.com/6302123/176757071-083fa72b-a633-4ead-b1e9-d5e399bab78f.png">

When you mouseover the Date Picker, you see the full date:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/6302123/176757181-5b2ed0c1-5f5b-4d41-87dc-fcb8b4382a6c.png">

When you click on it, you can select another date:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/6302123/176757228-082391ef-edaf-4d67-86ea-84ab6c726282.png">

**Comment by thegreatercurve** [comment]
Closing as this adds a lot of complexity to the playground.
