### ISSUE TITLE
Add inline slides feature

### ISSUE THREAD

**Issue by trueadm** [facebook/lexical#1105]
It would be great to have an inline slideshow/carousel feature. Each slide could have the option to customize the background, add text/images/bullets inside each slide. I'd imagine each slide to be a separate editor instance.

**Comment by rimildeyjsr** [comment]
Can I work on this?

**Comment by acywatson** [comment]
> 

Yes - assigning to you!

**Comment by thegreatercurve** [comment]
Closing as this as it doesn't necessarily demonstrate any unique features of Lexical within the playground.
