### ISSUE TITLE
Pasting any paragraph style like H1 should carry over consistently to blank lines.

### ISSUE THREAD

**Issue by kraisler** [facebook/lexical#1118]
Note the 2 sub-cases in the video.

This should work regardless of H1 vs H2 vs Block Quote Vs. Code Block. The rule is the same:
When pasting on blank line, the copy source paragraph style should transfer over.
If the line is not blank but the selection to replace will result in a blank line prior to the paste, then the same rule applies. Please see video.

https://user-images.githubusercontent.com/1952520/150235240-778d6d41-70f0-419b-b574-aa3a5bca39d7.mov

**Comment by thegreatercurve** [comment]
Validated that this works correctly.
