### ISSUE TITLE
Paragraph selection can be inconsistent

### ISSUE THREAD

**Issue by kraisler** [facebook/lexical#1119]
Paragraph selection can be inconsistent resulting in different behaviors esp around copy and paste.
https://user-images.githubusercontent.com/1952520/150236285-d8558660-c7c5-43c3-b11e-bec869b8995e.mov

**Comment by LuciNyan** [comment]
I can't reproduce this bug anymore, I want to know if you can still reproduce this bug in 👀

**Comment by thegreatercurve** [comment]
I finally got a chance to take a look at this issue. I can replicate it but I think it's expected browser behaviour we probably shouldn't override.

When you do the selection dragging down and then going back up, your cursor is still just below the first paragraph, which places the `focusNode` of the selection at the start of the new line. Copying and pasting therefore makes sense to include the start of the new line as well. 

If you drag down and then drag back up though, but put your cursor is at the end of the first paragraph, so the `focusNode` of the selection is at the end of the first paragraph, the new line is not included in the copy and paste.

https://user-images.githubusercontent.com/7748470/188322708-acd7c3bb-3819-4dc5-8d08-91322e39d111.mov
