### ISSUE TITLE
Setting list item to Normal wrongly adds new paragraph

### ISSUE THREAD

**Issue by kraisler** [facebook/lexical#1128]
https://user-images.githubusercontent.com/1952520/150411458-bc692eb4-7d55-4364-aa6d-ed95a61003bf.mov

**Comment by sidverma32** [comment]
hey @trueadm  , can I take up this issue?

**Comment by acywatson** [comment]
@sidverma32 I'm sorry, I stumbled onto the (potential) fix for this (#1802) while investigating another issue.

I have another very similar one I am happy for you to take a look at though :) #1803 

Let me know if you're interested, or just self-assign

**Comment by sidverma32** [comment]
Sure @acywatson . I'm interested , will look into it.
