### ISSUE TITLE
Lexical github:Links: Link Popup Requirements/Spec

### ISSUE THREAD

**Issue by kraisler** [facebook/lexical#1150]
The below wording might be tedious.  The attached movie should offer up some audio/video assistance.

**If one more more links exist and are selected PARTIALLY:**
The link button should always invoke the link popup and not clear the current link.
The link button should select the first link in the series of partially selected links (showing the selection) then invoke the popup.
The link popup should have a Clear Link option along with an Edit Link option.
This last UX design concept eliminates the confusion brought on by the very first issue above ("not clear the current link").

**If 2 or more links exist and are selected WHOLLY:**
If more than one link are FULLY selected by the selection, then the link popup should show up with the Clear Link as the only enabled option.

**If have only a blinking caret:**
The link button should invoke the link button and put it immediately into EDIT MODE.

**If we have non-link text selected that is not crossing a paragraph boundary**
The link button should appear and be in EDIT MODE if the link itself is not fully formed. If the selected text begins with www as in www.mytext.com then the link displayed ought to be "www.mytext.com".  If the text is plain text, then its current functionality of "http://" is just fine, however it should be placed in EDIT MODE.

**Other Details**
The link popup should have an OK button and a Cancel button. Or at least have a Cancel button besides Esc.

If the selected text spans more than one paragraph, the Link Button on the toolbar should be disabled.

https://user-images.githubusercontent.com/1952520/150443773-12d2f24e-b803-4c92-be24-26501b8fe5f8.mov

**Comment by zurfyx** [comment]
Closing in favor of #1795 that already has some discussion
