### ISSUE TITLE
Regression: bad code break: Delete empty line should move next line up, but also changes styling 

### ISSUE THREAD

**Issue by kraisler** [facebook/lexical#1158]
Deleting empty line where next line is H1 wrongly removes H1 styling.
https://user-images.githubusercontent.com/1952520/150588773-bd0feaee-fe56-4831-bd77-7b65e2306710.mov

**Comment by yuzhouu** [comment]
another similar bug

Uploading 150588773-bd0feaee-fe56-4831-bd77-7b65e2306710.mov…
