### ISSUE TITLE
Add/audit keyboard shortcuts for converting to and from markdown

### ISSUE THREAD

**Issue by kraisler** [facebook/lexical#1182]
Some examples:
Ctrl-Shift-C | Copy selected Markdown text as HTML to Clipboard
Ctrl-Shift-V | Paste HTML from Clipboard as Markdown text

Ctrl-L | Create List from multiple lines of text
Ctrl-Q | Quote selected text
Ctrl-K | Insert or create link from selected text
Alt-C | Format selected text as code block

**Comment by g4rry420** [comment]
Hi @zurfyx , Can I work on this issue ?

**Comment by thegreatercurve** [comment]
Closing this as I don't think we should include these shortcuts as part of core in case they override the key for host, browser or OS shortcuts. They can be added at the developer's discretion, but I think we should include them by default.
