### ISSUE TITLE
Add support for "anchor" links

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#1184]
Users can use a simple LinkNode for this, but we may need to expose a way to grab a DOM selector from a node. We probably also want to serialize it with the editor so it can be stored.

**Comment by thegreatercurve** [comment]
I realized that this was added in by @karam-qaoud during his internship as part of #2634 to add the table of contents mini map. Heading nodes are transformed to add relevant classes and IDs.

**Comment by cbratschi** [comment]
Is this still supported? I could not find any TOC component in the playground and entering #test as a link target is rejected.

**Comment by ivailop7** [comment]
> Is this still supported? I could not find any TOC component in the playground and entering #test as a link target is rejected.

it's in the settings button at the bottom left to enable 'table of contents' flag

**Comment by cbratschi** [comment]
> > Is this still supported? I could not find any TOC component in the playground and entering #test as a link target is rejected.
> 
> it's in the settings button at the bottom left to enable 'table of contents' flag

Thanks, the TOC works. But it just displays all headings, still looking for a feature to set IDs or named anchors and use them in links.

**Comment by vect-sderory2** [comment]
Same issue here I want to have the possibility to add an id on an heading node so that I can use it in a link

**Comment by cccccroge** [comment]
Please support this !!! 😭
