### ISSUE TITLE
Code Block: move to start/move to end bugs

### ISSUE THREAD

**Issue by trueadm** [facebook/lexical#1185]
When pressing CMD + Left, CMD + Right, the cursor should go to the start of the code, not the whitespace.

**Comment by ChakshuGautam** [comment]
I was looking into the list of commands to dispatch [here](https://github.com/facebook/lexical/blob/main/packages/lexical/Lexical.d.ts#L17-L56) but wasn't able to find a `JUMP_TO_START` command. Is there something that already does this or this would be a new command?

**Comment by ChakshuGautam** [comment]
Hey, let me know if this approach is fine, I will refactor, start writing tests and create a PR.

**Comment by thegreatercurve** [comment]
Verified that this has been fixed.
