### ISSUE TITLE
Is it correct that children ElementNode are joined with \n\n?

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1214]
Currently two children ElementNodes are returned with a \n\n in between. This makes sense for ParagraphNodes in Rich Text, but should this be the norm?

![nn](https://user-images.githubusercontent.com/193447/152182438-a34102ee-9e8f-4e3a-b79d-036368a48874.png)

**Comment by thegreatercurve** [comment]
Validated that this is fixed.
