### ISSUE TITLE
Links are not consolidated when selection is backwards

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1240]
Notice that there's 3 links instead of 1

https://user-images.githubusercontent.com/193447/152996898-2914e1e0-9345-4d82-b815-8d82aab05b93.mov

**Comment by HarrySIV** [comment]
Hi @zurfyx, I tested this and it no longer seems to be an issue.

**Comment by thegreatercurve** [comment]
Confirmed this is no longer an issue on the playground.
