### ISSUE TITLE
Migrate the codebase from flow to typescript

### ISSUE THREAD

**Issue by justinhaaheim** [facebook/lexical#1242]
@justinhaaheim is tracking plans and progress in separate documents. If you have questions or want to get involved reach out to him.

**Comment by ivan-ngchakming** [comment]
Hi, I'd like to help with this. Is there any updates on this and how can I get involve?

**Comment by maasencioh** [comment]
### Packages
- [x] lexical-clipboard
- [x] lexical-code
- [x] lexical-dragon
- [x] lexical-file
- [x] lexical-hashtag
- [x] lexical-headless
- [x] lexical-history
- [ ] lexical-link
- [ ] lexical-list
- [x] lexical-mark
- [ ] lexical-markdown
- [ ] lexical-offset
- [ ] lexical-overflow
- [x] lexical-plain-text
- [x] lexical-playground
- [ ] lexical-react
- [x] lexical-rich-text
- [ ] lexical-selection
- [ ] lexical-table
- [ ] lexical-text
- [ ] lexical-utils

### Special Packages
- [ ] lexical
- [ ] shared
- [ ] lexical-yjs

**Comment by FezVrasta** [comment]
Can you share anything on the reason behind the migration?
