### ISSUE TITLE
Feature: Add PrettierPlugin for code block formatting

### ISSUE THREAD

**Issue by trueadm** [facebook/lexical#1282]
We probably need the API to detect nodes being removed/added before we can do this, but it would great to have a plugin that adds an auto format button to code blocks so we can format the content. This was an internally requested feature too.

**Comment by LuciNyan** [comment]
We now have a code block that supports many languages, I wonder if we need to introduce a prettier parser for each language when we implement this feature. If we support more languages later, do we need to add the corresponding parser as well?
