### ISSUE TITLE
Remove "root" listener API

### ISSUE THREAD

**Issue by trueadm** [facebook/lexical#1311]
I don't think we need the root listener API now that we have commands. I might be wrong, and maybe we should first do an audit internally to see the usage, but it would be good to remove code that we no longer need where possible.

**Comment by acywatson** [comment]
I think there are plenty of valid uses cases for root listeners. We document a pattern leveraging them here: https://lexical.dev/docs/concepts/dom-events. I guess we can remove the API and allow people to do this more directly - maybe lighten up the core.

**Comment by acywatson** [comment]
Let's not worry about this right now. Lots of usages internally and it's an established and documented pattern,
