### ISSUE TITLE
E2E flakiness - Can type characters, and select and replace a part?

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1320]
This test seems to be flaky sometimes on the CI. Race condition or something?

`Can type characters, and select and replace a part?`

<img width="860" alt="Screen Shot 2022-02-17 at 4 11 36 pm" src="https://user-images.githubusercontent.com/193447/154522542-0c912412-0619-4e0b-8f3d-9932eb01be2f.png">

**Comment by thegreatercurve** [comment]
Closed as we know about test flakiness. We have a general task for tracking this issue.
