### ISSUE TITLE
Text nodes with \r\n cause issues with text cursor

### ISSUE THREAD

**Issue by gdelmas** [facebook/lexical#1341]
When a text node has been programatically created with CR+LF
```
$createTextNode('Hello\r\nWorld')
```
and a user ads an additional line break, the text curser can no longer be moved upwards with the arrow keys. Left and right allows to move through the text though. When moving the cursor downwards into the `\r` line, the text cursor becomes invisible.

https://user-images.githubusercontent.com/2949816/155035533-708e86b2-aa43-473b-bbc2-1bf52cced470.mov

The carriage return `\r` also does not show up in the debug tree view, although it somehow appears to cause issues.

As user edits insert line break nodes, I am wondering if TextNodes with line break or carriage return characters are supposed to exist.

**Comment by trueadm** [comment]
You can use `selection.insertRawText` and it should get rid of the pesky characters for you and insert line breaks.
