### ISSUE TITLE
Fast Refresh compatibility

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1405]
On Fast Refresh nodes are recreated building new node references which causes trouble with node registration and equality (that we currently do based on prototype)

**Comment by thegreatercurve** [comment]
Still a problem even after moving to Vite

**Comment by trueadm** [comment]
Fast Refresh won't work well with Lexical anyway, as Lexical has its own mutable state which won't play well with Fast Refresh from experience.
