### ISSUE TITLE
Enhance markdown the ``` shortcut for code block

### ISSUE THREAD

**Issue by kraisler** [facebook/lexical#1456]
Currently, pressing "\`\`\` " converts paragraph to a code block (unless it is already a code block).
It also supports "\`\`\`js " for a code block with language = 'js'.

We'd like this to be "\`\`\`" + return where the return makes the conversion to code block. Current functionality should be retained:
  i. undo should restore "\`\`\`" and the return key.
  ii. the "\`\`\` " with the space should continue to work.
  iii. the "\`\`\`" should only appear at the start of the non-code block paragraph and not in the middle of it.

When inside a code block paragraph, markdown is typically disabled.
However, when the user types "\`\`\`" followed by a return, the code block should toggle off.  We could also trigger this with a space.  In either case the new paragraph should be converted to normal. 

As a stretch, the user might also type the 3 ticks + return in the middle of a code block paragraph. In this case, the next paragraph should be made normal and the 3 ticks removed. 

The following is prescriptive but suggestion only. The engineer should treat below as advisory only:

So, to implement this, we need to expand the current trigger. Currently, the trigger is a " " and defined as TRIGGER in the code.
We should alter this to be an enumeration of types:
type AutoFormatTriggers = whitespaceTrigger | newlineTrigger | codeBlockOffTrigger | codeBlockOffTrigger.

**Comment by jgonera** [comment]
@zurfyx Is this resolved? I tried `lexical` and `@lexical/markdown` 0.7.6 and a code block is only created when I use a space after "```", not when I use a return.

See https://codesandbox.io/s/zealous-thunder-9zceu2 (I checked on latest Chrome and Firefox on macOS).

**Comment by jgonera** [comment]
@kraisler ?

**Comment by yakkomajuri** [comment]
I'd be keen on this as well but seems default behavior has remained the same

**Comment by etrepum** [comment]
Not sure why this was closed (it has been years) but if you want to see this feature then file a new issue for the enhancement if there isn't already an open one. Note that you may have to submit a PR to implement it yourself if you want the feature sooner than later. Commenting on closed issues is one of the least effective ways to communicate for this project.

**Comment by dmitryshostak** [comment]
Why is this issue closed without any resolution or an example of the correct approach implementing such a behaviour?

**Comment by etrepum** [comment]
See previous comment
