### ISSUE TITLE
Bug: Safari line break anchor offset

### ISSUE THREAD

**Issue by fantactuka** [facebook/lexical#1473]
Safari (unlike Chorme/Firefox) updates anchorOffset/focusOffset when inserting line breaks. 

Scenario:
Use plain text mode and insert newlines (hit enter multiple times). During selection reconciliation we check whether anchor/focus and corresponding offsets has been changed ([here](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalReconciler.js#L839-L844)) and if it's the same as before - skip scrolling into view. 

In this case Chorme/Firefox do not update anchorOffset of DOMselection when inserting line break, hence if we compare `DOMselection.anchorOffset` with `pendingState.selection.anchorOffset` it will be different and will cause scrolling recalculation.

Safari does update DOMselection.anchorOffset so it will be exactly the same as in pending state selection and won't trigger scrolling.

JSFiddle with example, focus into content editable box and start hitting enter. FF/Chrome will maintain anchorOffset, while Safari will keep updating it

https://jsfiddle.net/wqb35pLj/

**Comment by etrepum** [comment]
Since this is old and it's not really clear what the impact on the Lexical side is, I'm going to close it. Pressing return repeatedly in a plaintext editor scrolls the caret into view for me in safari and chrome.
