### ISSUE TITLE
Skip E2E tests before navigation

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#1495]
Our E2E tests currently launch the browser and navigate to the playground and wait for it to load regardless of whether or not the test will ultimately be skipped. This was the case before the test harness refactor, but the refactor made it obvious.

If we can skip before navigation and page load, this will probably speed up some test suites and reduce overall flakiness. Currently, navigation happens for every test in the beforeEach hook (in the initialize function). I order to skip before navigation, we need to either move the navigation out to individual tests or separate the tests into suites with different beforeEach hooks based on when they are skipped, or find some other clever way.

**Comment by thegreatercurve** [comment]
I believe this is fixed now.
