### ISSUE TITLE
Improve React Getting Started Documentation

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#1516]
https://lexical-website-new.vercel.app/docs/getting-started/react

We should improve this to be a more step-by-step guide that highlights how easy it is to get started with React and links out to or embeds CodeSandboxes where possible.

**Comment by knownasnaffy** [comment]
While at this topic, the page for react documentation at https://lexical.dev/docs/react/ has a next button pointed at it's own url. Anyone working on this, please fix that.

**Comment by etrepum** [comment]
Since we do have a getting started guide that does link out to stackblitz I think this can be closed
