### ISSUE TITLE
Concept Docs: Editor State

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#1531]
https://lexical-website-new.vercel.app/docs/concepts/editor-state

Write some documentation about what editor state is, how it works, and how it should (and perhaps should not) be used.

**Comment by pspeter3** [comment]
I think a relevant question too is should you store the editor state in your database and if so, how do you serialize the editor state to HTML for rendering?

**Comment by trueadm** [comment]
@pspeter3 Do you need to serialize the HTML state for rendering? You can just deserialize the state and pass it to a Lexical editor instance in read only mode. That way it will render the same, and none of the content will be editable.

**Comment by acywatson** [comment]
> @pspeter3 Do you need to serialize the HTML state for rendering? You can just deserialize the state and pass it to a Lexical editor instance in read only mode. That way it will render the same, and none of the content will be editable.

What if you want to, for example, send an email?  :)

**Comment by pspeter3** [comment]
@trueadm I do need to serialize the HTML state for rendering. Can I instantiate the editor on the server side in Node (etc...) or does it rely on the DOM to be present?

**Comment by trueadm** [comment]
Lexical relies on the DOM being present. We're exploring ways of how you might export HTML, which is definitely simpler on the client then on the server (because of styling). Watch this space! :)

**Comment by acywatson** [comment]
This was added here: https://lexical.dev/docs/concepts/editor-state

We can create further issues with more specific requests
