### ISSUE TITLE
Flatten the testing matrix

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#1536]
We're running into concurrency limits on macOS in the CI and it's also just wasting compute. We should flatten the testing matrix and run the various tests suites serially instead of in parallel on separate machines. This will save the cost of repeatedly doing all the npm setup.

**Comment by harish-sethuraman** [comment]
I tried to do so but seems like it also takes quite a lot of time. Most of the time spent is on running the e2e test and not on doing npm setup since we already have cached deps. You can take a look at #1858 in case that is what you mean in this issue

**Comment by acywatson** [comment]
Thanks for the time you put into this - I think, rather than overall time, what we were going for here was fewer separate machines used to keep us away from the concurrency limits. If it's going to take a lot longe to execute them, we might want to just keep doing it the way we're doing it. As you said, everything is cached, so the setup overhead is relatively low.

Let's just abandon this for now. Thanks again for the effort!
