### ISSUE TITLE
Image caption is not populated on parseEditorState

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1537]
Save an EditorState with an image caption, try populating it again (i.e. by uploading a file). It doesn't show up

**Comment by thegreatercurve** [comment]
Closing as this seems to have been fixed with the recent changes to nested editors.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/7748470/189069874-0e227819-b25f-4c73-9853-d8df01283eca.png">
