### ISSUE TITLE
Code highlighting alternative

### ISSUE THREAD

**Issue by fantactuka** [facebook/lexical#1567]
See if we can leverage https://webreflection.github.io/highlighted-code/test/demo.html (`<pre>` with highlighted code and `pointer-event: none; user-select: none` over `<code>` (`LexicalCodeNode`) with plain-text)

More details TBD

- highlighting will be outside of editor state (state will hold only plain text for CodeNode)
- positioning `<pre>` over CodeNode should be pixel perfect which might not be trivial

**Comment by trueadm** [comment]
I think this is cool but ultimately apart of the larger span of work to rewrite the code editor to be more like CodeMirror.
