### ISSUE TITLE
Bug: Converting multiple paragraphs into Code Block creates separate blocks

### ISSUE THREAD

**Issue by a-xin** [facebook/lexical#1572]
Enter multiple lines of text, select all, switch to code block

## The current behavior
Each line becomes a separate code block

https://user-images.githubusercontent.com/1154924/160666844-7cdbc88d-2e93-4390-ad54-e8c06a8267f5.mov

## The expected behavior
A single code block with multi-line content should get created

**Comment by fantactuka** [comment]
This one is fixed @ Lexical playground, will migrate sync to WWW playground
