### ISSUE TITLE
Bug: Copy & paste from website causes linebreaks to be added and behaves inconsistently

### ISSUE THREAD

**Issue by a-xin** [facebook/lexical#1573]
This might be separate issues:
- Copy & pasting text from a website into Lexical playground appends additional linebreak
- Selecting a paragraph on a website using triple-click and then copy & pasting it into Lexical merges inline styles (see video, everything becomes bold)
-  Selecting a paragraph by using mouse-down on the start of it and mouse-up on the end of it, and then copy & pasting into Lexical playground correctly preserves the inline styles but also adds a linebreak at the end

Copied paragraph from here: https://www.grammarly.com/blog/how-long-is-a-paragraph/

https://user-images.githubusercontent.com/1154924/160668451-a8f0f943-2372-43dd-9aaf-a10f5a31abc5.mov

**Comment by thegreatercurve** [comment]
This is consistent with other text editors such as ProseMirror. We don't necessarily want to strip out line breaks if they exist at the end of a copied piece of text.
