### ISSUE TITLE
Can't edit formula when inside a table cell

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1597]
I can type at the end but it's impossible for me to place the cursor in the middle using my mouse

https://user-images.githubusercontent.com/193447/161524494-769a3662-66e2-4250-a505-56b9d54dfc89.mov

**Comment by DavieReid** [comment]
I think this is a symptom of a more general issue.

If a cell has any content, when you click into that cell the cursor is moved to the start of the content.   

You can try this out in the playground by adding an empty table, typing in a couple of cells, and then click on the cells you have typed in as though you wanted to edit the text.  You will see the cursor briefly appear at the end of the text and then jump to the beginning.

My expectation would be that the cursor would appear at the end of the text.
