### ISSUE TITLE
[Discussion] Improve the experience around merging editor states

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#1601]
I ended up writing this to solve the problem I posed earlier of merging a saved editor state into an active editor. The use case is very similar to insertDataTransferForRichText, but the saved state doesn't have a range like the shape that we put on the clipboard.  Here, I basically create a range, to get it into the correct shape so I can pass it to $generateNodes.

I'm almost sort of relying on an implementation detail here, even though the shape passed to $generateNodes is a public interface.  I think we can add something like this to core or re-work the shape of these stringified states to be cross-compatible.

I don't fully understand the concept of a "range" in the context of the JSON we put on the clipboard when we copy, but maybe one idea is to just add such a range to the editor state when we stringify it.

```
function $insertEditorStateString(
  editorState: string,
  selection: RangeSelection | GridSelection | NodeSelection | null,
) {
  const parsed = JSON.parse(editorState);
  const nodeMap = parsed._nodeMap;
  const range = [];
  // recreate the range using the same strategy Lexical $cloneContents does.
  nodeMap.forEach(node => {
    if (node[1].__parent === 'root') {
      range.push(node[0]);
    }
  });
  // This is all borrowed from $generateNodes
  const parsedNodeMap: ParsedNodeMap = new Map(nodeMap);
  const nodes = [];
  for (let i = 0; i < range.length; i++) {
    const key = range[i];
    const parsedNode = parsedNodeMap.get(key);
    if (parsedNode !== undefined) {
      const node = $createNodeFromParse(parsedNode, parsedNodeMap);
      nodes.push(node);
    }
  }
  if ($isRangeSelection(selection)) {
    selection.insertNodes(nodes);
  } else {
    $getRoot().append(...nodes);
  }
}
```

**Comment by trueadm** [comment]
I'm closing for now as this topic hasn't really been that prevalent and some of the complexities around this should probably just exist in user-land implementations rather than in core.
