### ISSUE TITLE
Handle invalid html for paste

### ISSUE THREAD

**Issue by fantactuka** [facebook/lexical#1615]
Pasting invalid html might crash editor, e.g. lists or tables. Current API has hooks for child nodes post processing, but not for the node itself, so there's no way to adjust generated lexical's tree if we get invalid structure.

As a specific example: copying html with `<li>` tags not being wrapped into `<ul>` crashes editor, as `ListItemNode` expects its parent to be `ListNode`.

**Comment by tylerjbainbridge** [comment]
I might be able to take this, I'm pretty familiar with Copy + Paste after the table work and I have some ideas around enforcing Parent-Child relationship on paste.

**Comment by acywatson** [comment]
@tylerjbainbridge happy to let you take a look at this :)
