### ISSUE TITLE
Bug: Enter will split a link and move the second part to next paragraph 

### ISSUE THREAD

**Issue by ocavue** [facebook/lexical#1678]
Lexical version: The latest version on https://lexical-playground.vercel.app/

## Steps To Reproduce

Check the video below. 

Link to code example: N/A

## The current behavior

https://user-images.githubusercontent.com/24715727/163252913-bd0594f7-3408-490a-b6b8-9a5ab6944471.mp4

## The expected behavior

This is what I expected when I press Enter:
![image](https://user-images.githubusercontent.com/24715727/163252963-3e527ebe-009c-4b70-b7eb-ddf1662c3669.png)

**Comment by acywatson** [comment]
Looks like we need to insert a LineBreakNode instead of a new ParagraphNode in this case.

https://github.com/facebook/lexical/blob/4e57eb8d7e0ca00fe998f02b9dd3efaaef858a2e/packages/lexical-rich-text/src/index.js#L598

Possibly for all inline elements?
