### ISSUE TITLE
Bug: Unexpected cursor jumping with iOS Auto-Correct

### ISSUE THREAD

**Issue by tshddx** [facebook/lexical#1680]
Lexical version: Version in use on the Lexical Playground at time of posting this issue.

## Steps To Reproduce

Note: When I use the editor normally on iPhone Safari, I encounter other instances of strange behavior. This is the first instance I have been able to reliably reproduce:

1. Visit the [Lexical Playground](https://lexical-playground.vercel.app/) on an iPhone using Safari.
2. Tap to place the cursor immediately before the letter "T" at the beginning of the second sentence "Try writing in some text...".
3. Type the letters "hrllo". Above the keyboard you should see an Auto-Correction suggestion for "Hello". (This likely varies based on system language, Auto-Correction settings, etc.)
4. Tap the "Hello" suggestion.
5. Observe the editor text says "HelloTry writing in some text..." and the cursor has jumped to the end of that paragraph.

Screen recording:

https://user-images.githubusercontent.com/307393/163254125-c0e00bb4-b176-4eaa-ab04-1b6cf3ef493a.mp4

## The current behavior

The cursor jumps unpredictably when tapping iOS Auto-Correct suggestions.

## The expected behavior

The cursor should behave predictably, as it does with native text inputs and textareas in iOS Safari.

**Comment by trueadm** [comment]
Thanks for flagging. I'll take a deep dive into this tomorrow! :)
