### ISSUE TITLE
Bug: Confirm button is overflowing InsertEquationDialog

### ISSUE THREAD

**Issue by diegonvs** [facebook/lexical#1694]
Lexical version: 0.2.0

## Steps To Reproduce

1. Open Lexical Playground
2. Click on Insert and insert an equation
3. Type something like `x` inside the input
4. You will notice the Confirm button wrongly positioned overflowing the Modal component

See:

![image](https://user-images.githubusercontent.com/7663513/163287836-60ccd166-30cb-49fa-bc9f-3bd56af995ce.png)

## The current behavior

Confirm button overflowing the Modal region

## The expected behavior

We can have 2 possibilities here:

1. Confirm button can be fixed at the bottom of the Modal by increasing the size of the Modal
2. Maybe reducing the space(width in this case) of the equation area inside the Modal

Do we have tests or samples for what we consider long equations? It can be good for testing and detecting these kind of bugs :)

**Comment by trueadm** [comment]
What browser is this?

**Comment by diegonvs** [comment]
Sorry, I'm on Version 102.0.4972.0 (Official Build) dev (64-bit)

![image](https://user-images.githubusercontent.com/7663513/163289524-f37145f6-4d0b-4192-ad9b-3b3335f3e869.png)

I can take a look on Chrome stable if you want :)

**Comment by diegonvs** [comment]
On Chrome stable(Version 100.0.4896.88 (Official Build) (64-bit)):

![image](https://user-images.githubusercontent.com/7663513/163289711-5af022c5-9044-478f-a838-2fae379ffdab.png)


![image](https://user-images.githubusercontent.com/7663513/163289685-9d86ead5-f986-4dea-8bdb-287d3ff787e4.png)

**Comment by trueadm** [comment]
This should fix the issue :) https://github.com/facebook/lexical/pull/1697

**Comment by diegonvs** [comment]
![noice](https://c.tenor.com/pEtOxcxh_xUAAAAC/noice-michael-rosen.gif)

Thank you!

**Comment by diegonvs** [comment]
When taking a look on preview:

![image](https://user-images.githubusercontent.com/7663513/163291314-768f1bee-a4be-4850-ad4f-6b3285686027.png)

It's looking nice :)
