### ISSUE TITLE
Bug: can't type Chinese in Chrome ios

### ISSUE THREAD

**Issue by chenqing** [facebook/lexical#1695]
![747FD1E9-F18B-4E8E-A8CC-74ED48E3D8BD](https://user-images.githubusercontent.com/3064613/163288642-98cfb569-108d-4451-b48e-2ed7908a485c.gif)

https://lexical-playground.vercel.app/

**Comment by trueadm** [comment]
This doesn't happen for me in other IME languages. What version of iOS do you have and what Chinese keyboard is it exactly? Thanks!

**Comment by chenqing** [comment]
iOS：15.4.1
iPhone 13 pro max 
Chrome version ：100.0.4896.77

**Comment by trueadm** [comment]
@chenqing Good to hear it works on Safari. Which means it's likely a Chrome iOS bug. What keyboard are you using? Chinese Traditional/Simplified, Zhuyin/Pinyin/Sucheng/Cangjie?

**Comment by chenqing** [comment]
> 

Chinese Simplified Pinyin

**Comment by trueadm** [comment]
Thanks, I can reproduce. I'll look into this.
