### ISSUE TITLE
Bug: samsung keyboard swipe typing missing spaces between words in firefox mobile

### ISSUE THREAD

**Issue by jakehamilton** [facebook/lexical#1699]
Lexical version: latest on playground as of writing

Device: Samsung Galaxy S21 Ultra & Tab S7+
OS: Android 12, One UI 4.1
Samsung Keyboard Version: 5.4.70.24
Browser: Firefox 99.2.0 (Build #2015874211), 3fbd94a59+

## Steps To Reproduce

1. Open the playground in Firefox mobile
2. Tap the text area to open the Samsung keyboard
3. Type using swipe gestures

Link to code example: https://lexical-playground.vercel.app/

## The current behavior

When using swipe typing, spaces are not added between words.

https://user-images.githubusercontent.com/7005773/163301765-9b0592f1-5f44-49d3-a5d9-4cbe32c3e10a.mp4

## The expected behavior

The text area should support normal swipe typing like other text fields such that spaces are inserted between words.

---

Note: After testing in Chrome, it would seem this occurs only in Firefox mobile for me. Additionally, the issue does not occur in Firefox when using GBoard. Only the combination of Firefox + Samsung Keyboard seems to cause a problem.

**Comment by trueadm** [comment]
Can you take another look at the Playground and see if it's still happening? We landed some Android fixes today that might have helped. This is a tricky one, as debugging Firefox on Android is a PITA.

**Comment by jakehamilton** [comment]
Took another look and spaces are being added!

However now words don't show up until the next word is entered. Not quite sure why that would be.

https://user-images.githubusercontent.com/7005773/163493699-b6c24a7e-52c0-4892-ad36-27f437e411f0.mp4

> This is a tricky one, as debugging Firefox on Android is a PITA.

Agreed. Not quite sure what is causing this interaction, but I appreciate the work to try and resolve it!

**Comment by trueadm** [comment]
This is so strange. Does the same issue happen on Chrome? Maybe we can put this down to a Firefox bug, as I can't see anything obvious that would cause this (there was something suspect before).

**Comment by jakehamilton** [comment]
Yeah, this seems to be a *very* specific interaction between Firefox and the Samsung keyboard. Here's what I've tested:

Firefox + Samsung Keyboard = broken
Firefox + GBoard = works
Chrome + Samsung Keyboard = works
Chrome + GBoard = works

I'm fine closing this as a "probably browser or keyboard related issue", but just in case I find some time to try and debug locally, where would be a good place to start in the code to check for input events firing/failing? I may try and poke around a little bit and see if I can find anything.

**Comment by trueadm** [comment]
@jakehamilton The best place to look is in `LexicalEvents` where most of the logic around composition is handled.

**Comment by jakehamilton** [comment]
Great, shall I close this ticket for now and reopen if I manage to find anything?

**Comment by trueadm** [comment]
We can keep this open for now, I don't see any harm :)

**Comment by jakehamilton** [comment]
Sounds good, thanks for the help so far. Really appreciate the work being done on this project 😁

**Comment by trueadm** [comment]
I think we can close this now as this doesn't really seem like a Lexical issue.
