### ISSUE TITLE
Bug: Playground popup positioning does not handle various edge cases

### ISSUE THREAD

**Issue by atomiks** [facebook/lexical#1704]
Lexical version: Latest

## Steps To Reproduce

Continues from https://github.com/facebook/lexical/issues/1677

### Overflows viewport edges

<img width="1099" alt="Screen Shot 2022-04-14 at 4 24 38 pm" src="https://user-images.githubusercontent.com/22450188/163326237-b65f071b-5b1d-4e6c-b55a-e3ee9744ceb8.png">

### Does not align to a `ClientRect`

<img width="916" alt="Screen Shot 2022-04-14 at 4 25 28 pm" src="https://user-images.githubusercontent.com/22450188/163326356-74214cff-00ef-4e4f-a413-19181afa7ebc.png">

### Does not reposition on window resize

<img width="1054" alt="Screen Shot 2022-04-14 at 4 26 19 pm" src="https://user-images.githubusercontent.com/22450188/163326498-47f0516a-0e84-402e-b8d5-3de718bb7cd6.png">

## The expected behavior

It adapts to all of these requirements. That's why I made [Floating UI](https://floating-ui.com) 😋 

- "Overflows viewport edges" is solved by https://floating-ui.com/docs/shift
- "Does not align to a ClientRect" is solved by https://floating-ui.com/docs/inline
- "Does not position on window resize" is solved by https://floating-ui.com/docs/autoUpdate

**Comment by mihrab34** [comment]
#1712

**Comment by mihrab34** [comment]
Fix PlaygroundPopupPositioning For Various Edge Cases top and left position #1712
