### ISSUE TITLE
Feature: It would be nice to have an ESM version 

### ISSUE THREAD

**Issue by pshihn** [facebook/lexical#1707]
It would be nice to have an ES6 modules version so it could be easily used in the browser directly. 
Thanks.

**Comment by yuzuquats** [comment]
I put together an initial version for bundling lexical into an ES6 module - i'm fairly new to using npm/node but thought this might be interesting: 
- https://github.com/facebook/lexical/issues/2119#issue-1230182471
- https://github.com/yuzuquats/lexical-web-component/blob/master/dist/lexical.bundle.min.js

**Comment by Alex-ray** [comment]
I agree, this causes a lot of issues with libraries such as Yjs that require a single import. If you are trying to use Lexical collaboration plugin with Yjs in an es module the Lexical library loads the cjs version of Yjs which conflicts with the es module loaded version of Yjs. This leads to major issues like this https://github.com/yjs/yjs/issues/438 and this https://github.com/facebook/lexical/issues/2153


Realistically this shouldn't be too hard to implement either.  Simply expose both ejs and cjs versions of the Lexical packages and let the consuming apps decide which ones to load.

**Comment by Alex-ray** [comment]
I agree, this causes a lot of issues with libraries such as Yjs that require a single import. If you are trying to use Lexical collaboration plugin with Yjs in an es module the Lexical library loads the cjs version of Yjs which conflicts with the es module loaded version of Yjs. This leads to major issues like this https://github.com/yjs/yjs/issues/438 and this https://github.com/facebook/lexical/issues/2153


Realistically this shouldn't be too hard to implement either.  Simply expose both ejs and cjs versions of the Lexical packages and let the consuming apps decide which ones to load.

**Comment by benjaminsehl** [comment]
I'm down to help on this — but am admittedly quite a newb when it comes to this stuff. 

Are we expecting something like this?

```
lexical-package/
├── dist/
│   ├── cjs/
│   │   ├── LexicalModule.js
│   │   └── ...
│   ├── esm/
│   │   ├── LexicalModule.js
│   │   └── ...
└── src/
    └── ...
```

**Comment by kaikun213** [comment]
Fully agree on the above. Yjs is an absolute pain when packages use different versions of it, easily causing hours of weird debug issues. Common websocket backend implementations like [hocuspocus](https://github.com/ueberdosis/hocuspocus) do support the esm version.

Any change this is on the roadmap?

**Comment by mkilpatrick** [comment]
Bump on this. Using this library with the latest version of Vite causes problems.

**Comment by CanRau** [comment]
> Bump on this. Using this library with the latest version of Vite causes problems.

Same here, have to do this

```tsx
import lexicalComposerContext from "@lexical/react/LexicalComposerContext";
const [editor] = lexicalComposerContext.useLexicalComposerContext();
```

for all `@lexical` packages, so it won't crash 😵‍💫

**Comment by marbemac** [comment]
> Same here, have to do this for all @lexical packages, so it won't crash

Yeah, and then depending on setup the TS typings stop working 🤦‍♂️.

**Comment by umaranis** [comment]
I maintain [svelte-lexical](https://github.com/umaranis/svelte-lexical/) which is the port of lexical to svelte. Sveltekit 2 requires Vite 5 and as mentioned above, lexical packages are not working properly with Vite 5. According to Vite, it is not a Vite5 issue, rather [a NodeJS compatibility issue](https://github.com/vitejs/vite/issues/14332). The solution seems to be `lexical` supporting the ESM module system. This is becoming a bit urgent as CJS is getting deprecated.

I would request the maintainers to prioritize this issue. Thanks.

**Comment by CanRau** [comment]
Good to know haven't yet upgraded to Vite 5 but now def gonna wait or if I give it a shot watch out how our editor behaves

**Comment by kcoet** [comment]
is there any progress on this?

**Comment by lukasholzer** [comment]
Bump on that lexical is kinda unusable with yjs in an ESM workspace due to the issue of importing yjs both in commonjs and ESM.

There are great build tools out there that help to build ESM/CJS compatible packages that support both versions. 

Especially as this package is not any CJS specific language features like `__dirname` that cannot be converted to ESM it is just about the import and module syntax that can be easily exported in both versions.

If you are willing to do so I could offer my help and expertise in building either ESM only packages for both versions.

TBH I think dropping commonjs just makes sense as mostly this package is used inside the web where commonjs is not tree shakeable and resulting in larger bundle sizes.

**Comment by ivailop7** [comment]
We are interested in going ESM. Feel free to tackle the conversion.

**Comment by ktecho** [comment]
Upvoting, as we need this to have a proper working package for Svelte.
