### ISSUE TITLE
Bug: npm install fails

### ISSUE THREAD

**Issue by pshihn** [facebook/lexical#1708]
Fetch the latest repo, and run `npm install`
Get the following error:
`No matching version found for playwright@1.16.0-next-alpha-trueadm-fork.`

**Comment by trueadm** [comment]
What are your system specs?

**Comment by harish-sethuraman** [comment]
The same happens for me I'm using `Mac mini (M1, 2020)`

**Comment by trueadm** [comment]
I also use an M1. For me I have to do run my terminal in Rosetta compatibility mode.

**Comment by pshihn** [comment]
Macbook Pro 2017 
MacOD Mojave 10.14.6

**Comment by sukechris** [comment]
I failed several times to install using `npm`, but, `yarn` is fine

**Comment by harish-sethuraman** [comment]
What version of `npm` are you using? can you try running `npm --version`?

**Comment by caleboleary** [comment]
Upgrading npm from `6.14.13` to `8.7.0` with 
```
npm install -g npm@latest
