### ISSUE TITLE
Bug: Block conversion issues (crash)

### ISSUE THREAD

**Issue by austensatterlee** [facebook/lexical#1709]
Lexical version:

## Steps To Reproduce

_This is on Firefox 99.0 (64-bit)_

1. Create some text and convert it into a code block
2. Convert that code block into a quote block
3. Undo (hit ctrl+z)

## The current behavior

Screenshot of result of following the steps above:

![image](https://user-images.githubusercontent.com/3756179/163341005-61124005-082f-43c1-8eda-1889ff2c5aae.png)

## The expected behavior

Being able to undo converting one block type into another 🙃

Note that even typing in some characters, selecting the format dropdown and hitting "code block" will cause a `"key" is read-only` error to appear (if you first select the text, then convert it, things work correctly). It seems like there's a general issue with format conversion.

**Comment by trueadm** [comment]
I believe we fixed this already, we just need to do an npm release.

**Comment by trueadm** [comment]
@austensatterlee would you mind trying again please? We just released 0.2.1.

**Comment by austensatterlee** [comment]
Just tried again, seems to work now 👍
