### ISSUE TITLE
Bug: npm install error caused by install chromium

### ISSUE THREAD

**Issue by Junezm** [facebook/lexical#1711]
Lexical version: 0.2.0

## Steps To Reproduce

1. git clone repo
2. npm install

Link to code example:

## The current behavior
 Command: node install.js
Arguments: 
Directory: /Users/frontend/editor/lexical/node_modules/puppeteer
Output:
The chromium binary is not available for arm64.
If you are on Ubuntu, you can install with: 

 sudo apt install chromium

 sudo apt install chromium-browser

/Users/frontend/editor/lexical/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115
                    throw new Error();
## The expected behavior
the package link-preview-generator unused, so I remove it, then I can install successful

**Comment by trueadm** [comment]
Try running your terminal with compatibility mode if you're using an M1 machine. That's what I have to do. Then everything works great :)

**Comment by shijie-todd** [comment]
> 

How to run terminal with compatibility mode ?

**Comment by kevinansfield** [comment]
If anyone else runs into this, note that you can install chromium manually via homebrew and set some env vars to stop point puppeteer at the right place. The instructions here work well https://linguinecode.com/post/how-to-fix-m1-mac-puppeteer-chromium-arm64-bug

**Comment by Timebutt** [comment]
I ran into the same problem this morning and dropped a [PR](https://github.com/facebook/lexical/pull/3114) to resolve the problem.
