### ISSUE TITLE
Bug: Copying 1100 lines of code into it crashes the page and nothing gets pasted in, then typing a newline doesn't work.

### ISSUE THREAD

**Issue by mlzzen** [facebook/lexical#1714]
Lexical version: https://lexical-playground.vercel.app/

## Steps To Reproduce

1. open https://lexical-playground.vercel.app/
2. paste code of https://github.com/vuejs/core/blob/main/packages/compiler-core/src/parse.ts to playground

Link to code example:

## The current behavior
crashes, and noting gets pasted in, and typing newline doesn't work

## The expected behavior
1100 line code can be paste in

**Comment by trueadm** [comment]
Thanks for reporting this. This looks to be an issue with our code block parsing logic. After debugging part of it Chrome dev tools, looks like we're spending a huge amount of time parsing it was regular expressions from Prism. I wonder if we should switch to a better code highlighting library @fantactuka

**Comment by fantactuka** [comment]
Fixed with #1727
