### ISSUE TITLE
Bug: Android + Mobile Chromium + GBoard adds white-space on selection.

### ISSUE THREAD

**Issue by RaulPROP** [facebook/lexical#1716]
Lexical version: 0.2.0

## Steps To Reproduce

1. Open a mobile chromium browser in android.
2. Go to the playground [(https://lexical-playground.vercel.app/)](https://lexical-playground.vercel.app/).
3. Tap any word to set the caret at that position.

Link to code example: (https://lexical-playground.vercel.app)[https://lexical-playground.vercel.app]

## The current behavior
It adds a white-space where the caret should be placed.

## The expected behavior
The caret is set normally.

## Things to consider
- This only happens when using GBoard.
- This works properly on Mobile Firefox.
- This works properly on iOS.

## Video

https://user-images.githubusercontent.com/15218519/163381419-bcd4fbe0-203d-4bef-b18c-d993c9fb3a50.mp4

**Comment by X7md** [comment]
Same here

**Comment by trueadm** [comment]
This is the strangest issue. I'm unable to repro it on my Samsung + Android Chrome? Maybe I need to switch to the Google keyboard, but I'm not sure how to do that on this device… let me dig deeper.

**Comment by RaulPROP** [comment]
This is a fairly common bug regarding js text-editor libraries.

i.e.: the [slate](https://github.com/ianstormtaylor/slate)'s Angular wrapper library [slate-angular](https://github.com/worktile/slate-angular/) also has a [very similar bug](https://github.com/worktile/slate-angular/issues/194) (but the regular slate library doesn't).

**Comment by orange4glace** [comment]
Samsung + Android 11 + Chrome + GBoard. Cannot reproduce either.

**Comment by RaulPROP** [comment]
I can reproduce it with:
- One plus 6T (Android 11)
- Xiaomi Mi 10T (Android 11)
- Xiaomi Mi 8T (Android 11)
- Huawei P30 Lite (Android 10)

**Comment by socarlosb** [comment]
Same issue here with:
- Samsung A50
- Android v11
- Gboard with two languages (EN+ PT) and 31 Jan 2022 update

**Comment by orange4glace** [comment]
> Samsung + Android 11 + Chrome + GBoard. Cannot reproduce either.

Oh, now I can do it.

**Comment by orange4glace** [comment]
This is because GBoard fires `compositionstart` event even selection is changed in English keyboard.

**Comment by trueadm** [comment]
I've put up https://github.com/facebook/lexical/pull/1732, which should hopefully fix this (and other) issues.
