### ISSUE TITLE
Feature: Add descriptive element titles for better accessibility

### ISSUE THREAD

**Issue by WeaverOfTheWeb** [facebook/lexical#1726]
Icons aren't always the best for describing a feature/function so it would be helpful to have titles added to each interactive element describing it's functionality.

![Screenshot 2022-04-14 145749](https://user-images.githubusercontent.com/1872377/163406637-dea9db71-7cac-407e-97c8-18777513ae59.png)

**Comment by acywatson** [comment]
I agree with this, in principle, but there are some accessibility gotchas with using just the title attribute. I think we might need to go a bit deeper, as described here (linked from MDN docs where I was refreshing on title attr):

https://inclusive-components.design/tooltips-toggletips/

In any case, even just the title attribute would probably be an improvement over what's there now.

**Comment by furstenberg** [comment]
Yes, as already mentioned there are issues with using the title attribute. 

MDN page for title attribute has some [accessibility concerns](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#accessibility_concerns) listed. 

The title attribute is also mentioned in the [A11Y Project checklist](https://www.a11yproject.com/checklist/):

> The title attribute has numerous issues, and should not be used if the information provided is important for all people to access. An acceptable use for the title attribute would be labeling an iframe element to indicate what content it contains.

**Comment by thegreatercurve** [comment]
Fixed by #1932
