### ISSUE TITLE
Tables Bug: Plain text representation of tables on keyboard should be tabular.

### ISSUE THREAD

**Issue by tylerjbainbridge** [facebook/lexical#1742]
What it looks like now
<img width="256" alt="image" src="https://user-images.githubusercontent.com/13852400/163459184-6f6bc89f-2952-4585-9e19-28987f1f82fa.png">

What it should look like
<img width="189" alt="image" src="https://user-images.githubusercontent.com/13852400/163459117-f4ad6182-96de-46a1-b3fe-aa623d519507.png">

**Comment by armelpingault** [comment]
Hi @tylerjbainbridge and @zurfyx I could have a look at this bug, but could you explain a little bit more how to reproduce it? Thanks
