### ISSUE TITLE
Feature: prevent disallowed usage of `$getRoot` and `$getSelection`

### ISSUE THREAD

**Issue by tomhicks** [facebook/lexical#1757]
Instead of specifying rules like "only use `$getRoot` and `$getSelection` inside these functions", why not simply supply those as parameters to the callbacks? Like this:

```
editor.update(({getRoot, getSelection}) => {...})
```

I'm sure this was considered already, and maybe it has something to do with not having to wire this through to subsequent nested callbacks for library authors, but surely this would be a better experience than having to remember there are certain places you can and can't use a function?

**Comment by trueadm** [comment]
This is actually how it originally worked, however there are three downsides:

- Like you mention, you have to wire this through everything, which we found was just adding to the complexity in many cases.
- In the future when we ship ESM modules, you should be able to tree-shake the $ functions you don't use out of your bundle.
- Destructuring lots of these (they are many) from the argument adds significant bytes to your bundle when it can be completely avoided.

**Comment by tomhicks** [comment]
Thanks for the response.

I'm talking from a position of not having tried lexical yet (I've got three different RTE-dependent projects and I'm looking at replacing them all with Lexical)... but ...

Do/can the dollar functions check their execution context in dev mode to determine if they are indeed allowed to execute? (one horrendous way of doing this would be to check for specific function names in the call stack)

Maybe this isn't a problem when using it for real, though?

**Comment by trueadm** [comment]
> Do/can the dollar functions check their execution context in dev mode to determine if they are indeed allowed to execute? (one horrendous way of doing this would be to check for specific function names in the call stack)

Calling them today in the wrong location will trigger a runtime error.

> Maybe this isn't a problem when using it for real, though?

I honestly think you'll get to grips with this when using Lexical very quickly. Using TS, these will autocomplete from the `lexical` package as you type them anyway!

**Comment by tomhicks** [comment]
Lovely stuff. Might as well close this then.

Although I do still prefer the injected style of dependency resolution for things like testing, I do understand the decision.
