### ISSUE TITLE
Bug: Device detect about native Webkit and cursor position for CJK characters.

### ISSUE THREAD

**Issue by sukechris** [facebook/lexical#1787]
Hi, Thank you for your great work! I want to use `lexical`(current version is 0.2.1) with native Webkit for my desktop app, and my operate system is MacOS Big Sur. I encountered two problems.
1. the expected device is not matched by `navigator.userAgent` when IME composing
2. the cursor position is slightly offset when I use `Chinese Simplified Pinyin` keyboard, and I guess it might be related to the CJK characters. Also, I find this issue #1695 has same problem.

https://user-images.githubusercontent.com/36565253/163677253-491a7509-2028-4a2c-a9c9-37f5d2b4ddbc.mov

**Comment by trueadm** [comment]
The big issue here is how we detect you're using webkit if there's no `navigator.userAgent`. Any ideas?

**Comment by sukechris** [comment]
@trueadm yeah, you are right, maybe I should custom `userAgent` when I'm using webkit, custom Safari userAgent for Mac `Webkit`, custom Edge userAgent for Windows `Webview2`

**Comment by sukechris** [comment]
@trueadm I use for Tauri for build my app, and I submit a issue https://github.com/tauri-apps/tauri/issues/3904

**Comment by thegreatercurve** [comment]
Closing this as the issue does not seem to be Lexical specific. The offset when using the `Chinese Simplified Pinyin` keyboard is no longer present.
