### ISSUE TITLE
Revisit UX around link edit

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1795]
_Feedback from Hotgeart @ Reddit_

When I click on a link, I should be able to edit it, to open the standard isn't CTRL+LMB ?

(Maybe take some Quip inspiration - they do link edit when you're on the same paragraph but otherwise link takes to link)

**Comment by acywatson** [comment]
We should already have the logic for this internally, but it does rely on the EditorContext at the moment, which we're trying to remove.

**Comment by trueadm** [comment]
@acywatson I think the best way to do this is by using three things:

- In the LinkPlugin, have a Map for `<Element, string>` where string is the link itself.
- Add a mutation listener for LinkNode. It sets the entry in the map on `created` and removes it on `destroyed`.
- Add a CLICK_COMMAND handler in the LinkPlugin. In the handler, check the `event.target` agains the Map and open up a new window with the link.

**Comment by acywatson** [comment]
I think what you need here is a way to update a specific LinkNode’s url property when it’s clicked on. The ask here is to show the edit menu on click and to open the link on Ctrl+Click, AFAICT.  I don’t think this totally solves for the first case, as we need to reference the node on click, rather then the DOM element

**Comment by fantactuka** [comment]
We have `ClickableLink` plugin which allows opening link with cmd/meta key only (right now there's no filter callback hence it opens regardless of cmd/meta key):

```
<ClickableLinkPlugin filter={(e) => e.ctrlKey || e.metaKey} />
```

It also [includes logic](https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/ClickableLinkPlugin.js#L51-L71) to get link node out of event (getting <a> tag, then nearest lexical node out of it). 

Combining clickableLinkPlugin + adjustments link editor logic would address both points from original suggestion, the only question is about UX:

I've played a bit with it and one thing not sure yet: should we open link editor when clicking on link or when moving cursor (via keyboard) into link as well

**Comment by trueadm** [comment]
Improvements made to links internally. It's more of a playground issue too.
