### ISSUE TITLE
Disable clear button when the editor is blank

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1801]
There's no need to have a clear button with a clear confirmation when the editor is blank (it's redundant)

Programmatically wise we can probably check whether the EditorState has only one Paragraph and this one has no children

**Comment by harish-sethuraman** [comment]
I can take up this issue. I need one small help. 
Are we doing same sort of thing somewhere else in the repo for other option? (reading EditorState and blocking any option?)

**Comment by harish-sethuraman** [comment]
We can close this issue since it is fixed
