### ISSUE TITLE
Bug: Changing format to Normal in an indented list with more than one list item breaks list heuristics.

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#1803]
Lexical version: 0.2.1

## Steps To Reproduce

1. Insert a list with three items
2. Indent the bottom two items one level
3. With the last item selected, select "Normal" from the format dropdown in the playground
4. Hit Enter to go to the next line
5. type "- " to create a markdown list item
6.  Hit backspace to delete what you created in 5.

```
 root
  └ (5) list 
    ├ (4) listitem 
    | └ (6) text "one"
    └ (26) listitem 
      ├ (27) list 
      | └ (7) listitem 
      |   └ (8) text "two"
      ├ (42) paragraph 
      | └ (41) text "three"
      └ (46) list 
        └ (45) listitem 
```

https://user-images.githubusercontent.com/14864325/163697433-1ab34236-d150-4aec-8ee2-549f01b37bfd.mov

## The current behavior

Currently, deleting the list item deletes everything in between (see the video).

## The expected behavior

We don't support having Paragraphs in ListItems, so the root issue here probably goes back to how we select the insertion target in [$wrapLeafNodesInElements](https://github.com/facebook/lexical/blob/3f36d8d6234731d89928b1e11c780a9debafc87a/packages/lexical-selection/src/index.js#L519). When the user selects "Normal" we should probably be appending the new Element to the Root.

An alternative way to address this would be to change the deletion behavior here and just support having paragraphs inside nested ListItems. This might break other things, though.

**Comment by thegreatercurve** [comment]
Validated that this appears to have been fixed.
