### ISSUE TITLE
Excalidraw - ESC key should close/discard the current drawing

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1812]
_Feedback from [flibben](https://www.reddit.com/user/flibben/) @ Reddit_

You can potentially use the ESC command provided by Lexical. Make sure the it runs after Excalidraw's. For example, if I'm editing a text inside Excalidraw the first ESC key press should cancel the text edit inside Excalidraw, second should discard the drawing

**Comment by rimildeyjsr** [comment]
@zurfyx - can i work on this?
