### ISSUE TITLE
Excalidraw - Make the SVG result resizable

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1813]
_Feedback from [flibben](https://www.reddit.com/user/flibben/) @ Reddit_

We can improve Excalidraw's UX by making it resizable so that the user can easily pick their final size. Given Excalidraw provides a SVG for us this makes this issue a lot easier/doable

Whoever takes this issue may want to get some inspiration from the ImagePlugin/Node implementation

**Comment by 100paperkite** [comment]
Can I work on this?
