### ISSUE TITLE
GIPHY plugin

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1820]
GIFs are pretty popular, let's build a GIPHY plugin or similar. I'd probably place it underneath Image.

The UI is pretty much up to the person building the feature but I believe we're looking at something like this:
<img width="1027" alt="Screen Shot 2022-04-17 at 12 14 08 pm" src="https://user-images.githubusercontent.com/193447/163712011-6bf38b46-a595-4879-b434-899f0071b808.png">

SDK key: gslE624Ax1m7LThTdDztLGZpci6XhfIL

Happy to discuss the whole UX further or even whether GIPHY is the best GIF service

**Comment by rimildeyjsr** [comment]
@zurfyx - i would love to work on this! What all would this entail?

**Comment by zurfyx** [comment]
That's awesome! You can build as much as you feel comfortable with. It's a multi-step plugin so here's how I would approach it:

First PR: Check whether ImageNode works for you or you need a special GIHPY node - try with a simple hardcoded button that prints a sample GIHPY - like the flower sample image
Second (and maybe) third PR. When you're confident that you've got all the Lexical pieces aligned, build a sort of Image-like modal that has an input and a grid of GIPHY images while using the GIHPY. You will have scan through their dev API to find which method to calls and how to pass the API key

**Comment by rimildeyjsr** [comment]
That's a good strategy, thank you for elaborating! I will start work on the first PR!

**Comment by rimildeyjsr** [comment]
@zurfyx - Hey, I was working on the second PR and used a library called `react-giphy-searchbox` to achieve the layout. Everything was working as expected, but when I tried to commit, the pre-commit hook started failing with the error - "Module not found - react-giphy-searchbox".

I wanted to ask if there is any restriction on adding new libraries to the codebase, or if I am doing something wrong here?

**Comment by thegreatercurve** [comment]
From closed PR: 
> On reflection, I think we should close the related issue as well. Since it was created, we've added a lot of additional functionality to the playground, and I'm concern that the UX is becoming unwieldy and overwhelming for newcomers. Adding in Giphy doesn't necessarily show how to do anything new that isn't in another rich text media example, like image, Excalidraw, YoutTube or Twitter nodes.
