### ISSUE TITLE
Notion-like Toggle Plugin

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1841]
### Discussed in https://github.com/facebook/lexical/discussions/1835

<div type='discussions-op-text'>

<sup>Originally posted by **gutenye** April 18, 2022</sup>
Like below. Would love to see an example made into Playground. Thanks

https://user-images.githubusercontent.com/377544/163746866-7f479034-e675-42d9-98ab-6f20b0c9a3b9.mp4

</div>

---

That's an interesting one! The implementation is really attached to its requirements. For example, can it have siblings? How should text deletion work?

In the case of Notion it seems like it it behaves very similarly to ListNode so I can see two approaches:

ElementNode
The most accessible and cross-front-end framework approach is to write your own ElementNode that displays the arrow, has some padding and some TextNode inside it.

The ElementNode afterInsert will render these hidden item nodes, and the arrow click handler will change their visibility (rather than create-delete that would not show in the EditorState and would be bad for export and collab)

DecoratorNode
DecoratorNode is not necessarily a bad approach is there's lots of custom CSS involved. In the case the DecoratorNode would handle the handle the first line and the arrow and would render another editor inside it.

**Comment by gutenye** [comment]
@zurfyx I've created an example code using `ElementNode`. Can you please take a look?

1. Does the code have anything to improve or is there a better way? (As I'm new to Lexical)
2. How to prevent the backspace key to delete the arrow icon? (I don't want the ToggleNode to be deleted)
3. Is [this](https://codesandbox.io/s/lexical-togglenode-0ct1mm?file=/src/ToggleNode/ToggleIconNode.tsx:905-1041) the correct way to pass a `LexicalNode` to a `Component`?

Thanks

https://codesandbox.io/s/lexical-togglenode-0ct1mm
