### ISSUE TITLE
Feature: Capitalize first letter after return in mobile Safari

### ISSUE THREAD

**Issue by jclem** [facebook/lexical#1846]
In most text inputs on iOS, including in mobile Safari, after the user hits the return key to insert a new line, the next letter is auto-capitalized. This does not appear to be the case with Lexical.

I believe ProseMirror is the only editor toolkit that is able to preserve this behavior (albeit in a way that's occasionally buggy), so it's possible this is not fixable without some new APIs being introduced in Safari.

I've filed this as a feature request, because almost no other editor toolkits preserve this behavior; it didn't feel right to file it as a bug.

**Expected behavior:**

https://user-images.githubusercontent.com/412282/163811330-02f4b7ee-304a-4d28-9315-f429319a1116.mp4

**Observed behavior:**

https://user-images.githubusercontent.com/412282/163811128-3be0f33b-b8e8-4a6c-b820-4791b2f6275d.mp4

**Comment by trueadm** [comment]
Do you know how ProseMirror is making this work? We could likely do something similar.

**Comment by jclem** [comment]
Amazing @trueadm—thanks! Faster to fix than for me to answer your question 😄
