### ISSUE TITLE
Bug: Text replacement not working after newline in mobile Safari

### ISSUE THREAD

**Issue by jclem** [facebook/lexical#1849]
When typing a text replacement abbreviation directly after a newline, the text of the previous line is included what Safari sees as the current text, and therefore the replacement does not happen.

Lexical version: Whatever is on playground.lexical.dev as of Apr. 18, 2022 9:27AM ET.

## Steps To Reproduce

1. Type some text, like "Hello" on a line
2. Hit the return key to enter a new line
3. Type a text replacement abbreviation

Link to code example: n/a

## The current behavior

The replacement is not triggered, because if the previous line is "hello", and the abbreviation is "omw", Safari thinks the current text is "helloomw".

https://user-images.githubusercontent.com/412282/163815350-cac5bdc9-7068-490a-a3eb-ab96bc21b866.mp4

## The expected behavior

The expected behavior is that the first line contains the text that was typed, and on the second line, text replacement occurs. In this case, the "omw" abbreviation should be replaced with "On my way!"

https://user-images.githubusercontent.com/412282/163815598-fb0daf3a-7a02-47f2-8ba2-18384195b5fe.mp4

**Comment by trueadm** [comment]
I know what is causing this. I’ll look into it tomorrow when I’m back at work.

**Comment by trueadm** [comment]
I have a fix up: https://github.com/facebook/lexical/pull/1869. This should also fix the other issue too.
