### ISSUE TITLE
Bug: @lexical/code/LexicalCode.d.ts is not a module.

### ISSUE THREAD

**Issue by mass2527** [facebook/lexical#1850]
Lexical version: 0.2.1

## Steps To Reproduce

1. yarn add @lexical/code
2. import {registerCodeHighlighting} from '@lexical/code';

I'm currently trying to follow [Lexical](https://lexical.dev/) document's [Powerful Features](https://codesandbox.io/s/lexical-rich-text-example-5tncvy?from-embed) with typescript.
`import {registerCodeHighlighting} from '@lexical/code'` can't be done **since `LexicalCode.d.ts` is not defined**.

## The current behavior
can't import {something} from '@lexical/code'

## The expected behavior
can import {something} from '@lexical/code'

**Comment by acywatson** [comment]
@zurfyx is this fixed in 0.2.2?

**Comment by zurfyx** [comment]
Yes! File types were missing - https://github.com/facebook/lexical/pull/1818
