### ISSUE TITLE
Copy-paste or cut-paste image

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1853]
Clicking on image and Copy-paste or cut-paste image doesn't work (because of the DecoratorNode)

**Comment by acywatson** [comment]
DecorateNodes should be able to define an exportHtml, like other nodes, I guess?

**Comment by Proful** [comment]
May not be same, but one related feature may be "Copy Image" from any other website and ability to paste in lexical would be great help. I am not sure how it works, I don't think "Copy Image" converts to base64 encoded & stores in clipboard. But it does works in figma.

**Comment by thegreatercurve** [comment]
Re-tested and this appears to have been fixed by #2517
