### ISSUE TITLE
Bug: Collaboration remote cursors go away when the remote editor blurs

### ISSUE THREAD

**Issue by zwily** [facebook/lexical#1857]
When using collaboration, a cursor showing where remote users are in the document. When a remote user clicks to a different window, then that cursor goes away (including the selection). This is not how Google Docs works and is probably not what people expect to happen. The fix looks easy - there's a `useYjsFocusTracking` that sets local state to `null` on every `blur` of the editor, and removing that hook would prevent this from happening. 

The `useYjsFocusTracking` hook may mean this is intended behavior, but if it is, it should probably be configurable so people can imitate the Google Docs behavior if desired.

An alternative may be to update local state on blur, but update it to an "inactive" status, and show that on the remote end maybe in a lighter color, name italicized, or something. That could be kinda cool.

Lexical version: 0.2.2

## Steps To Reproduce

1. Using collaboration, open two editors
2. Select something in the first editor. Notice it appears selected in the second editor.
3. Click away from the browser in the first window. Notice the selection goes away in the second editor, even though it's still selected in the first editor (though grayed out because it's not active.)

Link to code example:

N/A

## The expected behavior

As described above.

**Comment by trueadm** [comment]
This was intentional, as I've also found how Google Docs does it to be broken/wonky. This isn't how Quip does it, for example. Happy to take another visit at this though. Another thing to consider is nested editors – right now the blur logic means that a cursor properly gets removed from the non-active editors (when there are more than 1 editor active on the page).

**Comment by zwily** [comment]
There is a slight difference between multiple editors (where I agree you definitely want this to happen) and the window - with multiple editors, if you select some text in one and then click to another editor, the selection goes away from the first editor, and when you click back to the first editor it is still gone. 

However, if you select some text and then click to another window completely, the text stays selected but goes to the inactive color (usually gray), and when the window is reactivated the selection remains. So to the local person they see selected text (but gray), and to the remote person they don't see a selection.

I agree that with multiple editors you do want the blur to remove the selection state from yjs. It would be nice to trigger it on `SELECTION_CHANGE_COMMAND` but it looks like the selection doesn't ever get set to null when the editor loses focus. 

This whole thing is pretty minor and the existing behavior is reasonable so I'll close it for now. Once I get further down the road with building my editor I may revisit it. :)

**Comment by trueadm** [comment]
I completely agree with you that we can improve this. I wonder if we could invoke a `SELECTION_ACTIVITY_COMMAND` or something similar with a payload of `true` or `false` that gives signal as to when a user does this? Then we can better tune the selection logic in collaboration?

**Comment by zwily** [comment]
Yeah, as long as it gets triggered when the editor blurs, which `SELECTION_CHANGE_COMMAND` does not do. I was curious why it doesn't, and found the code in https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalEvents.js#L159. So it does appears intentional.

A new command with some additional context on why the selection changed would be sufficient to have more flexible behavior in collaboration.

**Comment by trueadm** [comment]
Interestingly, as we found out when speaking to Mozilla and Apple folks – the Selection and Focus systems are meant to be independent. So if you have selection on a contentEditable and blur it, selection shouldn't change (Chrome does though, but that's not spec compliant AFAIK). We assumed earlier in the project that this should be the case. Changing tab likely doesn't cause a selectionchange for the same reason, so having an independent event should help.
