### ISSUE TITLE
Bug: Inserting line break between two text nodes does not break a line correctly

### ISSUE THREAD

**Issue by shaoshing** [facebook/lexical#1861]
Inserting line break between two text nodes currently insert a new line/paragraph without breaking the line from the text caret. It works as expected if your caret is within a text node though. Please see video below for repro steps.

Lexical version: 0.2.2

## Steps To Reproduce

https://user-images.githubusercontent.com/118264/163897483-61fbd625-2063-4a48-8eff-f6e37c3ec8a4.mp4

Link to code example:

**Comment by acywatson** [comment]
This is probably related to the changes I made to insertParagraph earlier this week:


https://github.com/facebook/lexical/pull/1748
