### ISSUE TITLE
Move Excalidraw to its own @lexical/excalidraw package

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1872]
It's starting to be a pretty popular one. Let's move it to its own package just like @lexical/list etc.

**Comment by zurfyx** [comment]
cc @rulikrulit if that's something you'd be interested in

**Comment by always-maap** [comment]
should be similar to #1301 and #1239. where should react components go? `lexical/react`? or inside `lexical/excalidraw` itself?

https://github.com/facebook/lexical/tree/main/packages/lexical-playground/src/nodes/ExcalidrawNode

**Comment by Anifahb** [comment]
Hi @always-maap @zurfyx - first timer here 👋 . Can i be pick this up?

**Comment by zurfyx** [comment]
Sorry for the late reply, I completed missed the first comment. @rulikrulit seems to have already picked this up yesterday and has a branch in good shape - https://github.com/facebook/lexical/compare/feature/excalidraw-package

Do you mind grabbing some other good first time @Anifahb?

**Comment by n2o** [comment]
I'd love to see this feature merged and implemented as own package. The Excalidraw integration is great :-)

**Comment by ShaswatPrabhat** [comment]
HI, is this still open and seeking contributions ?

**Comment by thegreatercurve** [comment]
Closing this as this we had a PR open for it but it introduced a lot of cross-package dependencies we are keen to avoid.

**Comment by EgonBolton** [comment]
I can't see the in-progress branch that was abandoned. I would like to see what those dependencies are, is it possible? @thegreatercurve

**Comment by thegreatercurve** [comment]
> I can't see the in-progress branch that was abandoned. I would like to see what those dependencies are, is it possible? @thegreatercurve

@EgonBolton This was the PR we ended up closing: #2131

**Comment by EgonBolton** [comment]
> @EgonBolton This was the PR we ended up closing: #2131

Can we reopen this one? In the conversation the rest of the team has agreed that the ui could be copied or the methods exposed. It seems fine to me too.
