### ISSUE TITLE
Bug: Typescript Error for theme

### ISSUE THREAD

**Issue by Proful** [facebook/lexical#1885]
Lexical version: 0.2.3

## Steps To Reproduce

1. packages/lexical-playground/src/themes/PlaygroundEditorTheme.js

## The current behavior
Above theme file in typescript complaining with below error

```
Property 'list' is incompatible with index signature.
  Type '{ listitem: string; nested: { listitem: string; }; olDepth: string[]; ul: string; }' is not assignable to type 'string | Record<string, string>'.
    Types of property 'nested' are incompatible.
      Type '{ listitem: string; }' is not assignable to type 'string'.ts(2530)
```

**Comment by zurfyx** [comment]
I believe it's just a problem with the Lexical.d.ts types? Want to submit a quick PR?
