### ISSUE TITLE
Feature: support for subscript and superscript

### ISSUE THREAD

**Issue by animeshk874** [facebook/lexical#1887]
Hi! I have to add a button for subscript in the editor toolbar. But turns out, the subscript and superscript functionalities aren't fully implemented. I did see a few variables (`IS_SUBSCRIPT`, `IS_SUPERSCRIPT`) in the source code, but I didn't see them being used anywhere. I also went through the doc, but wasn't able to find anything of much relevance. So I just wanted to know the state of this feature. Also, please let me know if I am missing something. Thanks :)

**Comment by Proful** [comment]
It is available as part of https://github.com/facebook/lexical/blob/ec7c75afe6c2db15d5bc1e9bb35df4d649e25d93/packages/lexical/Lexical.d.ts#L552

Like `strikethrough` implementation you have to implement for   'subscript' or 'superscript'

1. You have to add class name here https://github.com/facebook/lexical/blob/f8fac3a011f406106266b5c74611a2cd5a266a1e/packages/lexical-playground/src/themes/PlaygroundEditorTheme.js#L80
2. Provide CSS style here https://github.com/facebook/lexical/blob/f8fac3a011f406106266b5c74611a2cd5a266a1e/packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
3. `editor.dispatchCommand(FORMAT_TEXT_COMMAND, 'superscript')`

**Comment by animeshk874** [comment]
thanks @Proful. Any clue why are we using CSS tag to implement this rather than using `<sup>` and `<sub>` tags?

**Comment by Proful** [comment]
Not sure the reasoning behind it, except bold (strong) & italic (em), span tag is generated for rest text nodes.

Ref [LexicalTextNode.js](https://github.com/facebook/lexical/blob/main/packages/lexical/src/nodes/LexicalTextNode.js#L74)

**Comment by animeshk874** [comment]
got it, thanks 👍

**Comment by acywatson** [comment]
> thanks @Proful. Any clue why are we using CSS to implement this rather than using `<sup>` and `<sub>` tags?

Maybe we should be? We can look into it. I guess the classes might be more flexible than relying on browser styling, but now I'm thinking about the semantics of not having the tags.

**Comment by trueadm** [comment]
Addressed in https://github.com/facebook/lexical/pull/1903.
