### ISSUE TITLE
Bug: Cursor position is incorrect under the Chinese IME in Safari

### ISSUE THREAD

**Issue by realme0213** [facebook/lexical#1898]
Lexical version: 0.2.3

## Steps To Reproduce

1. Open [Lexcical Playground](https://playground.lexical.dev) in Safari
2. Type Chinese with `Chinese Simplified Pinyin` keyboard

## The current behavior

https://user-images.githubusercontent.com/104089673/164278375-a3caa31d-a25e-4f9d-b283-f5e6fb50823b.mov

**Comment by trueadm** [comment]
Can you also provide a video of what the correct result should be please? It's hard to know without knowing these languages :/

**Comment by realme0213** [comment]
Sorry for the incomplete information I provided, the expected behavior in Chrome is fine @trueadm 

https://user-images.githubusercontent.com/104089673/164281010-8cd788ac-10fc-40cb-a4d0-b79f8d4f6faa.mov

The keyboard I'm using:
<img width="308" alt="截屏2022-04-21 00 37 34" src="https://user-images.githubusercontent.com/104089673/164281141-91125f27-71b4-4553-915d-136058f32ae1.png">

**Comment by trueadm** [comment]
Is the issue that the selection cursor is offset slightly? As the input and composition completion look the same in both – unless I'm missing something?

**Comment by realme0213** [comment]
@trueadm yeah, just selection cursor is offset slightly when IME composing

**Comment by LuciNyan** [comment]
> @trueadm yeah, just selection cursor is offset slightly when IME composing

I opened https://playground.lexical.dev in Safari to try to reproduce the problem, but it seems to be fine, and I was wondering if the problem still exists in your case?

https://user-images.githubusercontent.com/22126563/170183973-f667eb14-bc89-4ca1-96f6-6fd5c56e0e6d.mov

**Comment by realme0213** [comment]
@LuciNyan I tried it and found no problem, it seems to work perfectly, awesome!! thank you🤝
