### ISSUE TITLE
Bug: Lexical selection is saying wrongly that some nodes belong to the selection

### ISSUE THREAD

**Issue by Fetz** [facebook/lexical#1904]
Lexical version: 0.2.3

## Steps To Reproduce

1. create 3 words separated by multiple spaces
2. make part of those words (I think this is optional) with inline styles (bold, italic)
3. make the left and right words link
4. make the center word a link
5. if steps are follow correctly the anchorNode and focusNodes will be the textNodes outside and will not belong to the selection
6. But if you check the lexical selection it will say that that the anchor nodes and focus nodes are selected.

https://user-images.githubusercontent.com/1071113/164434689-0bd7b2c5-4ee7-4527-894d-87e3c12d7f4a.mov

## The current behavior
Lexical Selection and DOM Selection have the same anchorNode and focusNode but Lexical says wrongly that these nodes are selected but they are not.

## The expected behavior
Either:
- Lexical selection will return different anchorNode and focusNode then the browser that belongs to always to selection
- or it should use the same DOM Selection anchorNode and focusNode but should detect correctly if these nodes are in the selection or not.

**Comment by trueadm** [comment]
Lexical normalizes DOM selection under-the-hood to reflect consistent values at an abstract level – so you shouldn't expect them to match up. Forcing them match up is what causes so many issues, because different browsers have very different ideas as to what should be selected. Stick with using Lexical's selection model if you can. :)

**Comment by Fetz** [comment]
@trueadm but in this scenario that I highlighted in the video anchorNode and focusNode both in lexical and the browser are the same (I extracted the text content to double check I got the same content) but that anchorNode or focusNode either shouldn't be returning selected or Lexical should instead set the anchorNode/focusNode the nodes inside the selection.

**Comment by trueadm** [comment]
Ah, sorry. I just realized I was looking at the wrong thing above. The logic is working correctly, it's just you're reading the selection of an editor state in the past. If you want to get the latest selection, you need to do `$getSelection` inside `editor.update()`. Doing it in a read will only get the selection of the editor state when it was created.

**Comment by trueadm** [comment]
This is what I mean by normalization. The DOM selection is at the very end of the whitespace text node (you can see this in your debug view) and also at the start of the other whitespace text node (also in your debug view). If you're at the boundary of two text nodes, you're technically selecting the interception of both of them. Given in this case it's an element – a link node, you're selecting the link node.

**Comment by Fetz** [comment]
Sadly is not what is happening in that specific example that I created.
A - Left whitespace
B - Link that is selected
C - Right whitespace

In Dom Selection in Chrome, Dom is saying that:
- A is focusNode and is not selected since the offset says that the selection starts/ends in the next sibling
- C is the anchorNode and is not selected since the offsets says that the selections starts/ends in the previous sibling
- B is the content inside the selection

In Lexical Selection, the lexical is saying that:
- A is focusNode and is (wrongly) selected
- C is the anchorNode and is (wrongly) selected

I confirmed that in lexical the focusNode and anchorNode are A and C by:
- checking that the node text content (see video attached) is empty spaces
- I check that the focusNode & anchorNode are not the same


https://user-images.githubusercontent.com/1071113/164502108-cef1934b-0b83-4b6d-a604-a21460dd6dd2.mov

In my example the link in the middle is written with the following format: normal**bold**_italic_
