### ISSUE TITLE
Pressing enter at the end of line skips new line created via linebreak

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1910]
1. Write some text
2. Shift + Enter
3. Write some more text
4. Move to the end of the first line
5. Press enter

https://user-images.githubusercontent.com/193447/164508418-16cf4848-017a-44b2-8f88-373c8aaf07f2.mov

**Comment by trueadm** [comment]
Odd, but this doesn't occur for me locally?

**Comment by zurfyx** [comment]
My bad, was in an old commits. Already fixed by some recent commit
