### ISSUE TITLE
Shouldn't be able to click outside the Modal (i.e. Excalidraw)

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1927]
Maybe we should close the modal when this happens and offer a method to handle modal discard

Additionally, you should not be able to tab outside the modal

**Comment by siva-kannan3** [comment]
@zurfyx I would like to work on this issue. Can I be assigned?

**Comment by siva-kannan3** [comment]
@zurfyx I would love to work on this issue. Can I be assigned?

**Comment by siva-kannan3** [comment]
would it be nice to add click outside support for other modals too like table, poll?

**Comment by PAkerstrand** [comment]
This issue was closed by #1999, correct?
