### ISSUE TITLE
Bug: When long text occupies more than one line, the ordinal number is misplaced

### ISSUE THREAD

**Issue by murukal** [facebook/lexical#1946]
When long text occupies more than one line, the ordinal number is misplaced

## before:
![1650811347812](https://user-images.githubusercontent.com/42456766/164981940-83e6312b-64ce-4cf0-914f-3440e21e8b2a.jpg)

## after:
![1650810907919](https://user-images.githubusercontent.com/42456766/164981656-2e0220b9-fe74-45cf-885d-c32da70cef59.jpg)

i use (element.offsetHeight / lineHeight) to infer rows

```
if (i) {
    const element = editor.getElementByKey(children[i - 1].getKey());
    const offsetHeight = element.offsetHeight;
    const lineHeight = parseFloat(getComputedStyle(element).lineHeight);
    const lineCount = Math.ceil(offsetHeight / lineHeight);
    
    for (let index = 1; index < lineCount; index++) {
        gutter += '\n';
    }
}
```

**Comment by trueadm** [comment]
This is a known issue right now. We plan on removing text wrapping, but haven't had the time to do so.
