### ISSUE TITLE
Enhancement: We shouldn't be initializing skipped tests.

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#1953]
Currently, we run the initialize util, which navigates to the local playground, in a beforeEach. The logic for skipping tests is inside the test itself. We need to to reorganize this somehow such that if we know a test will be skipped, we don't pay the cost of actually initializing.

There are several ways to think about this, the most straightforward probably being just moving the initialize inside the tests themselves and checking the skip condition before. For suites that are all skipped, we can probably move the skip to the beforeEach.

Example: https://github.com/facebook/lexical/blob/3b70199ea4a83e809ac3f57d8c62067b5b15a34c/packages/lexical-playground/__tests__/e2e/File.spec.mjs#L28

**Comment by trueadm** [comment]
I don't believe we do this anymore! :)
