### ISSUE TITLE
Bug: Improve Lexical <-> Lexical Copy & Paste For Text Selections

### ISSUE THREAD

**Issue by tylerjbainbridge** [facebook/lexical#1957]
As of now `Lexical <-> Lexical` copy + paste clones the entire structure from the top level all the way to the way down to the selected nodes, which is inconsistent with how we build the tree for external (HTML) copy & paste.

Take the following example, if you copy text within a Header you get the following two cases:
`Lexical<->Lexical`: includes the parent header element
`External (HTML)`: only the selected text

https://user-images.githubusercontent.com/13852400/165001643-3d324170-aa07-4d7e-9b0e-b190b8ab4fa2.mov

This is _fine_ for paragraphs, headers, etc, but for deeply nested element trees such as Tables and Lists this is very problematic. Selecting any text within a Table or List will include the the entire tree from the top level all the way down to the text node. 

E.g. A RangeSelection within a TableCell or ListItem will include the following nodes `table -> table row -> table cell -> paragraph -> text`, which essentially is a tiny slice of the table and not expected behavior (see the video below).

https://user-images.githubusercontent.com/13852400/165001783-47a5167f-5542-4fb2-9d27-6411d329ec40.mov

This is what is causing #1916. 

[You can see the source code for `Lexical<->Lexical` copy + paste here](https://github.com/facebook/lexical/blob/3349ffbaf4f6902f8ccb71494b1535129f16d1d4/packages/lexical-selection/src/index.js#L163).

**Comment by tylerjbainbridge** [comment]
I propose that we improve [`$cloneContents`](https://github.com/facebook/lexical/blob/3349ffbaf4f6902f8ccb71494b1535129f16d1d4/packages/lexical-selection/src/index.js#L163) by only including nodes that are "selected" in the editor, rather than building a clone from the bottom all the way up. This will make it's behavior consistent with [`$convertSelectedLexicalContentToHtml`](https://github.com/facebook/lexical/blob/f9ee530c9012b9de3ff7469a11ffb548861cdb25/packages/lexical-clipboard/src/clipboard.js#L117) and more predictable overall.

If we DO want to include the parent `ElementNode` with a `RangeSelection` isolated in the same parent, I propose that we introduce a new method on `ElementNode` that signals it's coupled with its `TextNode` children. This might be useful for Paragraphs, Headers, etc.

Open to suggestions for the new behaviors, but I think we should start by only copying selected content internally (i.e. the text itself in this case) until we have a more consistent & predictable solution in mind.

**Comment by trueadm** [comment]
I think the reason we do this, is to match how copying DOM HTML works in general. We should align with that, as changing the structure won’t help us if everything else works that way
