### ISSUE TITLE
Pressing shift+enter on an ElementNode shouldn't create a new line

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#1964]
Should be treated as a new paragraph (like the `insertAfter` behavior)

![Screen Shot 2022-04-25 at 12 20 34 pm](https://user-images.githubusercontent.com/193447/165079402-b05e6312-fc33-4872-a8dd-444efcd51d2b.png)

**Comment by trueadm** [comment]
Are you saying it shouldn't add a linebreak in?

**Comment by zurfyx** [comment]
Actually, that's probably OK
