### ISSUE TITLE
Bug: Lexical debugger selection is showing in wrong place

### ISSUE THREAD

**Issue by Fetz** [facebook/lexical#1970]
Lexical version:

## Steps To Reproduce

1. Go to https://playground.lexical.dev/
2. Copy a lorem ipsum paragraph
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam venenatis risus ac cursus efficitur. Cras efficitur magna odio, lacinia posuere mauris placerat in. Etiam eu congue nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla vulputate justo id eros convallis, vel pellentesque orci hendrerit. Pellentesque accumsan molestie eros, vitae tempor nisl semper sit amet. Sed vulputate leo dolor, et bibendum quam feugiat eget. Praesent vestibulum libero sed enim ornare, in consequat dui posuere. Maecenas ornare vestibulum felis, non elementum urna imperdiet sit amet.
3. Paste and make it a list item
4. Paste and make a normal paragraph
5. Do a selection in both the paragraph & in the list item
    - Both scenarios the browser selection indicator and lexical debugger selection will not match

https://user-images.githubusercontent.com/1071113/165095016-57b79a21-e500-4b30-9083-e4b042a98d3a.mov
> Ignore the pasting issue, is reported by this issue: #1966

## The current behavior
- Debugger Lexical selection is not matching what is selected by the selection indicator.

## The expected behavior
- Debugger Lexical selection should match what is selected by the selection indicator.

**Comment by trueadm** [comment]
This is a complex one to solve. Ideally we should invest time in rewriting the debugging tree. For now this is out of scope of the existing debugging plugin though.
