### ISSUE TITLE
Feature: Make the ImageResizer handles more intuitive

### ISSUE THREAD

**Issue by BjoernRave** [facebook/lexical#1974]
I would like to be able to drag and resize, for example an SVG, on only one axis, as known from other Vector graphic software or photoshop.

Origin of issue: https://github.com/facebook/lexical/pull/1851#issuecomment-1108310710

**Comment by 100paperkite** [comment]
Can I also work on this if this issue will be labeled as 'good first issue' or 'help wanted'?

**Comment by zurfyx** [comment]
Sure, thanks!

**Comment by danillymkin** [comment]
Hi, did I understand correctly that you just need to add new buttons? Will the image change also taking into account the proportions?

<img width="357" alt="image" src="https://user-images.githubusercontent.com/61794941/165290890-4f0aea35-fafe-4d02-aa48-03b310a06fda.png">
