### ISSUE TITLE
Expose the useLexicalDecorators hooks

### ISSUE THREAD

**Issue by martinc2907** [facebook/lexical#2013]
I am making my own plugin instead of using the plaintext/richtext plugins, and many of my nodes are extending the DecoratorNode. To render these nodes, I need access to the useLexicalDecorators hook. Would it be possible to remove it from being deprecated? Thank you.

https://github.com/facebook/lexical/blob/main/packages/lexical-react/src/DEPRECATED_useLexicalDecorators.js

**Comment by trueadm** [comment]
I'd like to know more what your own plain/rich text plugin is doing as to why you need a custom version? For now we have no intentions of re-exposing them as they're more of an implementation detail that might change in the future.
