### ISSUE TITLE
Bug: broken floating menu positioning when several paragraphs are selected

### ISSUE THREAD

**Issue by Zombobot1** [facebook/lexical#2017]
Lexical version: playground

## Steps To Reproduce

1. Select several lines of text

![image](https://user-images.githubusercontent.com/48030070/165728882-a6b38b14-478e-46d7-8766-79b7d23c6587.png)

## The current behavior
Menu is positioned on the editor's edge

## The expected behavior
Menu is positioned near selection

**Comment by Zombobot1** [comment]
Probably it can be fixed if positioning is changed from right to top or bottom

Screenshot of this discussion on discord

<img width="907" alt="image" src="https://user-images.githubusercontent.com/48030070/165730631-9799d8d9-b502-49ec-aa36-a6404fe48b17.png">

**Comment by trueadm** [comment]
I have a fix in my upcoming PR.

**Comment by Zombobot1** [comment]
The bug still occurs inside lists

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/48030070/166008271-b49af79d-96ec-4e5f-b3a8-f00c5136fd11.png">
