### ISSUE TITLE
Bug: Formatting of Inline code elements is lost when content is copied from external web page

### ISSUE THREAD

**Issue by reads21** [facebook/lexical#2049]
Formatting of Inline code elements is lost when content is copied from external web page. In the dom we  see  inline "<code> code</code>" element  missing when pasted in lexical .

Lexical version: 0.25

## Steps To Reproduce

1. navigate to Mozilla mdn website https://developer.mozilla.org/en-US/docs/Web/API/Node/normalize and copy the first paragraph like the one's pasted below. 

 "The normalize() method of the [Node](https://developer.mozilla.org/en-US/docs/Web/API/Node) interface puts the specified node and all of its sub-tree into a normalized form. In a normalized sub-tree, no text nodes in the sub-tree are empty and there are no adjacent text nodes."
 
2.  Paste it into lexical playground to see the "normalize()" text unformatted . 

 
Link to code example:
 
https://playground.lexical.dev/

## The current behavior
Inline code element's formmating is missing when content is from external web page.

## The expected behavior
Inline code elements formatting should be preserved when pasted into lexical.

**Comment by mmarkelov** [comment]
I guess that the `format` keep only one value, so only one style will be applied to pasted text. I can try to take it, and make `format` an array or set maybe

**Comment by fantactuka** [comment]
Fixed by #2607
