### ISSUE TITLE
Feature: expose `parseEditorState` function that accepts already parsed JSON.

### ISSUE THREAD

**Issue by nicksrandall** [facebook/lexical#2052]
My datastore stores JSON natively so it feels funny to have to re-stringify the value just to have it parsed back by `editor.parseEditorState()`. Could we extend `editor.parseEditorState()` to accept an object of same shape? Or just expose the `parseEditorState` utility function that it internally calls?

## Alternative
Just re-stringify the obj before sending to the method.

**Comment by trueadm** [comment]
Maybe the function can also take a raw JSON object or the stringified object

**Comment by nicksrandall** [comment]
This should be be a simple PR. I’ll make one and send it your way.
