### ISSUE TITLE
Feature: Better support Markup/HTML/JSX/TSX code highlighting

### ISSUE THREAD

**Issue by gutenye** [facebook/lexical#2075]
Use the same theme, here's the screenshot and DOM structure of `prism-react-render`

<img width="450" alt="Screen Shot 2022-05-05 at 11 17 10" src="https://user-images.githubusercontent.com/377544/166859060-9e70186b-e55a-42de-8ca6-57cc55bc09e0.png">

<img width="481" alt="Screen Shot 2022-05-05 at 11 15 04" src="https://user-images.githubusercontent.com/377544/166859150-46648ac9-b440-4970-bea2-15fb5999c64e.png">

And this is the result of `Lexical`

<img width="459" alt="Screen Shot 2022-05-05 at 11 16 59" src="https://user-images.githubusercontent.com/377544/166859207-ae5efd7e-b02c-4836-a317-03a8ad05846e.png">

<img width="443" alt="Screen Shot 2022-05-05 at 11 24 27" src="https://user-images.githubusercontent.com/377544/166859501-0a58687c-d93c-4ee0-8ce3-095c89cd7906.png">

Lexical is missing several class names for a better highlighting, like `<span class="token  tag">div</span>` or `<span class="token tag attr-value punctuation attr-equals">=</span>`

The `__highlightType` should be an array of strings.

https://github.com/facebook/lexical/blob/31e3b1889a4ef570a04597c04d75efa4e13aea88/packages/lexical-code/src/index.js#L80

**Comment by trueadm** [comment]
Closing as this is out of scope given our intent to rewrite the code editor.
