### ISSUE TITLE
Bug: caret color changes when paragraph is empty 

### ISSUE THREAD

**Issue by NicolasRoelandt** [facebook/lexical#2079]
I've notice an issue that could be a bit problematic in dark mode. In the screenshot I changed the base text color to red because it was easier to show, but imagine the same with dark background with white text.
Imagine you set your base text color to red. The caret will change color once we type text:
<img width="217" alt="Screenshot 2022-05-05 at 10 17 08" src="https://user-images.githubusercontent.com/8594193/166894998-d2e717cb-a970-418d-a4a4-48c69d576047.png"><img width="201" alt="Screenshot 2022-05-05 at 10 16 23" src="https://user-images.githubusercontent.com/8594193/166894902-bf6ec363-2d8f-4277-bf57-0623717c9ceb.png">

The reason is that the caret color will take the text color, but when your paragraph is empty, there is no text color. 
You can work around it it by applying a caret-color style to your ContentEditable. In my opinion this is not great as you need to specify this color in two different places (one which is not even inside your theme).

I had a small look at this and my first attempt was to apply the text.base style to paragraph node : https://github.com/facebook/lexical/compare/main...caret-color but then I figured out we would have to do this for headings, code, etc, which wouldn't scale well. So I think this might need a deeper discussion.

Lexical version: 0.2.5

## Steps To Reproduce

1. Apply the changes in https://github.com/facebook/lexical/compare/main...caret-issue to make you text color red
2. Notice how the caret color is different once you start typing text

## The current behavior
Caret color does not depend of text color when text is empty

## The expected behavior
They should be in sync

**Comment by trueadm** [comment]
Addressed in https://github.com/facebook/lexical/pull/2080 :)

**Comment by NicolasRoelandt** [comment]
Following the discussion in https://github.com/facebook/lexical/pull/2080, it seems that it will be a won't fix as it's by design. How can I mark it as won't fix?
