### ISSUE TITLE
Bug: Browser tab will freeze on markdown conversion after some time

### ISSUE THREAD

**Issue by lander854** [facebook/lexical#2083]
Lexical version: 0.2.5

## Steps To Reproduce
open sandbox example
type markdown text for around 1 minute

https://codesandbox.io/s/lexical-rich-text-example-forked-6g9ewh?file=/package.json

## The current behavior
freezer browser tab
## The expected behavior
not freeze browser tab

**Comment by lander854** [comment]
also tested with react 18, same issue

**Comment by fantactuka** [comment]
Should be fixed by #2137, feel free to reopen if find another scenario
