### ISSUE TITLE
Rename (and group) update listeners

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#2098]
**Problem:**

1. We have many update listeners and it's not obvious that mutation and textcontent are also update listeners.
2. Mutation and textcontent are missing interesting metadata passed to updateListeners. Hence, when you want to do something that doesn't strictly align with these other alternatives you have to fallback to `registerUpdateListener`

**Solution**

1. Make `updateListener` seemingly less powerful. Rename it to `registerEditorStateUpdateListener`
2. Rename the other two to `registerMutationUpdateListener` and `registerTextContentUpdateListener` since they are part of the same lifecycle.
3. Add the additional update metadata params to the other two
```
registerEditorStateUpdateListener((editorState, updateParams) => {
}

registerMutationUpdateListener(Node, (nodes, updateParams) => {
  const flags = updateParams.flags;
})
```

**Side note**

Having updateParams on nodeMutation would fix an immediate problem on WWW where we need to read flags inside a mutation listener. Currently, it's very hard because the mutation listener is also called before the update listener, so forces the user to introduces a sort of timeout or switch to the update listener.

**Comment by zurfyx** [comment]
> What exactly will go into updateParams?

The immediate use case I have in mind is update flags, which can be used to tell whether it was part of a `history-merge` or `collaboration` update

**Comment by trueadm** [comment]
Sounds good to have the tags passed to all three, maybe as the 2nd argument.

**Comment by trueadm** [comment]
I think the `UpdateListener` should have the following signature

```
editor.registerUpdateListener(
  ({prevEditorState, editorState}), tags) => { … }
)
```

So we'd drop the following being passed to it: `dirtyLeaves`, `dirtyElements` and `normalizedNodes`. Instead we can update the `MutationListener` to handle some of those things.

Right now, the `mutations` Map that is passed to `MutationListener` is great, but it could cover the gap a bit more. We have `CREATED`, `DESTROYED` and `UPDATED`, but like the DOM mutation listener, we don't have any signal for if a node's sub-tree is dirty. So why don't we add `SUBTREE` and `NORMALIZED` to mutation listeners? Maybe these can be opted-in.

**Comment by fantactuka** [comment]
I'm not sure that history plugin will be able to get all needed information about the change happened if we remove dirtyLeaves/Elements from update listener

**Comment by trueadm** [comment]
@fantactuka Couldn't you use both listeners in tandem. You still have prev editor state/next editor state from the update listener + knowledge of dirty nodes/leaves from the mutation listener?
