### ISSUE TITLE
Bug: colSpan is ignored in Table cell node

### ISSUE THREAD

**Issue by reads21** [facebook/lexical#2101]
Colspan and rowspan are not respected when you copy paste a table from external website . 

Lexical version: 0.2.5

## Steps To Reproduce

1. Go to a website like https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_th_colspan
2. Copy paste table to lexical playground 

 
Link to code example:

https://github.com/facebook/lexical/blob/main/packages/lexical-table/src/LexicalTableCellNode.js

1. The createDom method doesnt  attach colspan .
2.  convertTableCellNodeElement doesnt pass colspan
3.  GridCellNode doesnt have rowspan member variable as well . 

## The current behavior
Table's which have row and colspan gets murky when copy pasted

## The expected behavior
WYSWIG

**Comment by tylerjbainbridge** [comment]
Pasting my comment from @mmarkelov's PR here

> I'm pretty sure this is going to break selection and a lot of table operations (insert row/column, delete row/column, apply header state, etc) because they iterate through the table assuming each row has the same amount of columns using basic for-loops. There needs to be some new logic that accounts for colspan & rowspan added here.

> This feature is planned but will require changing a lot of core code within [TableSelection](https://github.com/facebook/lexical/blob/main/packages/lexical-table/src/LexicalTableSelection.js), [GridSelection](https://github.com/facebook/lexical/blob/84948d70fc499f8e638ed7c6e51eda3135c9fff5/packages/lexical/src/LexicalSelection.js#L334), and [TableUtils](https://github.com/facebook/lexical/blob/main/packages/lexical-table/src/LexicalTableUtils.js).

> Happy to approve the PR once support is added in these places & the tests pass, but that's going to be a lot of work.

Basically supporting colspan/rowspan will require a lot of core changes, but we'll be adding support soon.

**Comment by iampava** [comment]
Any updates on this? 👀

**Comment by wanggrplus123** [comment]
Any updates on this? 👀

**Comment by wsyks** [comment]
When will the plan update

**Comment by zurfyx** [comment]
Addressed in https://github.com/facebook/lexical/pull/4046
