### ISSUE TITLE
indent not tracked in getTextContent

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#2106]
I am using latest version
and still see the issue with indent. when we indent the words between lines become 1 word using getTextContent()
after https://github.com/facebook/lexical/pull/1993 work
 I am wondering if you guys are going to work on this near the future

_Originally posted by @yuuminakamura in https://github.com/facebook/lexical/discussions/1980#discussioncomment-2703114_

**Comment by trueadm** [comment]
Is this still a known issue? I'm having difficult reproducing it.

**Comment by thegreatercurve** [comment]
Closing this as I can't repro either.
