### ISSUE TITLE
Feature: Ability to render the editor in an iframe

### ISSUE THREAD

**Issue by cmmartin** [facebook/lexical#2108]
I'm trying to render the editor inside an iframe (via a react portal), but it's not working and I suspect this is due to the fact that it's referencing the global window object for selection state, etc. I'd like to be able to pass a custom window object (the iframe window)

One solution is to provide the window object in a react context. It can be passed in via an optional prop to the `RichTextPlugin` or `PlainTextPlugin` (or maybe even `LexicalComposer`) and would default to `window`. 

Alternatively, [Slate](https://github.com/ianstormtaylor/slate) reads the window from the contentEditable DOM node. So if you have a ref to that DOM node, you can look up it's parent window with something like...

```
contentEditableNode.current.ownerDocument.defaultView
```

We can expose this as a helper and replace all references to the global `window` with the helper like Slate...

https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/plugin/react-editor.ts#L54-L64

**Comment by trueadm** [comment]
I think we can extract it from the contenteditable like Slate does.

**Comment by CarlosBalladares** [comment]
this would be useful

**Comment by trueadm** [comment]
Thanks for reporting this. Fixed in #2918 :)

**Comment by darabun** [comment]
I'm trying to get this working but can't seem to get it to work when it's in the iframe.

I have it reproduced here: https://codesandbox.io/s/aged-frog-iu8ff7

It works when outside of the iframe but not when inside it.
Is there something obvious that I'm doing wrong?

**Comment by cmmartin** [comment]
@trueadm can we reopen this? I'm facing the same issue as @darabun. 

Interestingly, I can almost make it work if I provide an initial editor state with some text content like this: https://codesandbox.io/s/modern-wave-1ehl2o?file=/src/Lexical.js

But you'll notice the Enter/Return character doesn't work in the iframe, but works outside it. It seems like there are some event listeners missing in the iframe.

**Comment by cmmartin** [comment]
@darabun See https://github.com/facebook/lexical/issues/3534

**Comment by trueadm** [comment]
Let me know if this PR helps: https://github.com/facebook/lexical/pull/3573

**Comment by cmmartin** [comment]
Definitely an improvement, but there are still selection issues. It seems like we're getting the proper selection part of the time now. Try inserting a line break in the iframe here...

https://codesandbox.io/s/sweet-fire-e9ry1d

**Comment by trueadm** [comment]
How about https://github.com/facebook/lexical/pull/3578?

**Comment by cmmartin** [comment]
It works! Thanks @trueadm https://codesandbox.io/s/sweet-fire-e9ry1d
