### ISSUE TITLE
Feature: draggable block

### ISSUE THREAD

**Issue by echarles** [facebook/lexical#2115]
It would be great to have draggable blocks ready to be used (in core or as an example), see the notion like experience.

![Untitled5](https://user-images.githubusercontent.com/226720/167362676-73ad647d-12e4-4aa5-8d21-97ff9f99d82c.gif)

**Comment by echarles** [comment]
Work is being done in https://github.com/facebook/lexical/pull/2027 that could help to get the block drag/drop feature alive.

**Comment by oskar-szwajkowski** [comment]
Could you share your opinions about how could it be achieved in lexical?

Up to this point I was using Draft.js, and there I implemented drag & drop by wrapping each block inside draggablewrapper, then saving blockkey on drag event, and when dropping, changing order of blocks array to reflect drag & drop behavior

Should implementing custom drag & drop in lexical works similarly? However I cannot figure out the way to create general 'wrapper' around every non-inline element
(Other use case of that wrapper would be count up amount of open comments in this paragraph/block)

**Comment by DaniGuardiola** [comment]
Bumping this as we also need this feature really badly. What @oskar-szwajkowski shared is quite similar to our thinking. Two main challenges stand out:

- Overriding the nodes to wrap them with a drag and drop handle. Ideally, in a universal way (wrap all block nodes without duplicating too much code) and with the possibility of using react elements. Thinking that https://github.com/facebook/lexical/issues/1262 will be a step forward here.
- Showing drop targets in the right places to visually indicate where the block would land if dropped.

Would really love to learn how to implement something like this.

**Comment by hustlefueled** [comment]
+1 to @DaniGuardiola and @oskar-szwajkowski .

Being able to readjust content blocks will be super helpful. Currently, you need to cut and paste elements to realign and this creates formatting issues. 

Would love to see this come to Lexical.

**Comment by acywatson** [comment]
Acknowledging this thread - thanks for the feedback and thoughts here! Will try to follow up with some ideas on how we might be able to achieve something like this.

**Comment by LuciNyan** [comment]
Hi  @oskar-szwajkowski.

I'm sorry for missing your mention. For this feature, I tried a few different implementations. In my opinion the drag and drop implementation should not be intrusive to any other code. The user is free to choose whether or not to add this plugin, so I think the best implementation would be to add a draggable menu. When dragging happens it's essentially just dragging an icon, and we can customize the content displayed by way of setDragImage.

**Comment by songispm** [comment]
anything new?

**Comment by echarles** [comment]
@songispm A draft PR is being worked out by @LuciNyan. You can try the playground on https://lexical-playground-nzep8plck-fbopensource.vercel.app I find the implemented feature appealing and meeting the requirements.
