### ISSUE TITLE
Feature: Code block improvements

### ISSUE THREAD

**Issue by fantactuka** [facebook/lexical#2118]
- [ ] Add new element node (`CodeLineNode`) for code lines (it using `LineBreakNode` now), update highlighting and diffing accordingly
- [ ] Remove gutter rendering based on `:before` and use newly added CodeLineNode to render line number (Addresses #1946)
- [ ] Add some guards around longer code blocks rendering w/highlighting
    - Debounce highlighting
    - Add optional highlighting threshold (if content is longer then specified threshold then highlighting is disabled)
- [ ] Improve code blocks performance. Explore what we can do it have better code blocks performance on longer code blocks, some examples:
    - Virtualization (as a part of lexical reconciler)
    - Using AST parsing for highlighting instead of prism
    - Offload highlighting and diffing from main thread and move to a web worker
- [ ] Improve documentation for code blocks (#2380)

**Comment by BrianHung** [comment]
>  Improve code blocks performance. Explore what we can do it have better code blocks performance on longer code blocks, some examples:

You can try using incremental parsers like https://tree-sitter.github.io/tree-sitter/ or https://lezer.codemirror.net/. Found it hard to use them for incremental _syntax highlighting_ however, since they mainly targeting code text editors which give current viewport and lines, instead of position offsets in a document.

**Comment by danestves** [comment]
It's even worst right now, I'm testing out the `0.5.1-next.1` version and HTML is not highlighted 😅

<img width="1353" alt="CleanShot 2022-10-23 at 00 58 46@2x" src="https://user-images.githubusercontent.com/31737273/197374717-ddb3aa1c-5459-4ffb-b2dc-ce40c6d3fc11.png">

**Comment by trueadm** [comment]
I think we should invest some time next half to rewrite the code editor to be more like CodeMirror.

**Comment by renato** [comment]
Has any of the tasks mentioned in the OP been addressed at some point?

Especially the ones that would improve Code block performance (move the highlighting work from the main thread, virtualization, etc)?

@trueadm @fantactuka did this rewrite work happen? Are there other issues tracking this effort?

Thank you!
