### ISSUE TITLE
Feature: @ Mentions

### ISSUE THREAD

**Issue by fosple** [facebook/lexical#2121]
Hey lexical devs,

Would be awesome, if you could add a "@-mentions" plug-in to lexical. 

Example from the old draft.js world: https://www.draft-js-plugins.com/plugin/mention

Thanks for your work on lexical! I'm super happy, that after I read that sadly draft.js will be shut down, lexical is now open source 👍

Best
fosple

**Comment by thegreatercurve** [comment]
Hey @fosple! We already have a Mentions plugin in the playground. You should be able to activate the menu by typing "@" and then a couple of characters in the playground: https://playground.lexical.dev.

The code for the specific plugin is in [`packages/lexical-playground/src/plugins/MentionsPlugin.tsx`](https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/MentionsPlugin.tsx).
