### ISSUE TITLE
can't enter CJK characters properly

### ISSUE THREAD

**Issue by arayutw** [facebook/lexical#2123]
When you enter CJK characters from your iOS15 smartphone, the first character will be duplicated.

![IMG_0159](https://user-images.githubusercontent.com/5499895/167518925-b6bd1465-0692-4aa9-b3cb-3d184c65ed86.PNG)
If you enter `おはよう`, `おはおはよう` will be entered.

Can be reproduced here.
https://playground.lexical.dev/

**Comment by trueadm** [comment]
Thanks for reporting this. I'll dig into it when I next get the chance :)
