### ISSUE TITLE
Feature: Developer Tools Web Extension

### ISSUE THREAD

**Issue by thegreatercurve** [facebook/lexical#2127]
- [x] Scaffold a new [cross-browser web extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension) which works with Firefox, Chrome, Edge, and Safari.
- [x] Port the existing inline ASCI Lexical state tree representation to the extension.
- [ ] Create a more interactive representation of the Lexical state tree, akin to the Component view within [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en).
  - [x] Respective tree nodes should be collapsible or expandable.
  - [x] Respective tree nodes should highlight the relevant DOMNode on hover of the Lexical Node.
  - [x] Add slide out panel with all properties on the node.
  - [x] Add a view for the current selection.
  - [ ] Add the ability to time-travel between different editor states.
  - [ ] Add a log of all Lexical commands and their respective payloads.
  - [ ] View should be performant even for larger Lexical state trees.
  - [ ] View should have a suite of unit and E2E tests which test for basic Lexical states.
  - [ ] Add details of editor config.
- [ ] Build a CI pipeline within our Github Actions which handles publishing new extension versions to their respective web extension stores.
- [ ] Add the extension to each of our test browser environments, so we can better debug failing E2E tests.

**Comment by thegreatercurve** [comment]
@noi5e Would you mind adding yourself as an assignee to this Issue? For some reason, I can't add you.

**Comment by noi5e** [comment]
@thegreatercurve Huh, I don't see a button to add myself:
<img width="329" alt="Screen Shot 2022-06-13 at 9 37 34 AM" src="https://user-images.githubusercontent.com/4361605/173402319-8f803a1b-0392-4d11-9da1-21fd8701a8ea.png">

Is it true that only one person can be assigned to an issue at a time? It could be a question of access level too.
