### ISSUE TITLE
Feature: Readonly editor with state updates & listeners

### ISSUE THREAD

**Issue by yudori** [facebook/lexical#2164]
I have a usecase where:
1. I don't want the editor to be editable by the user
2. I want the capability to receive editor updates and subscribe to commands like click, drag, etc.

So far, I haven't been able to find a clean solution that achieves both. Setting the editor to `readonly` in the `initialConfig` 'freezes' the editor thereby achieving (1) but not (2).
It would be nice to have an editor that is non-editable but can still hooked up to the in-built listeners. 
For react, having a prop that can override `isReadOnly` in the [LexicalContentEditable](https://github.com/facebook/lexical/blob/main/packages/lexical-react/src/LexicalContentEditable.jsx#L94) seems to be one way to achieve this.

**Comment by trueadm** [comment]
We should possibly let event commands go through for click and drag. Right now they're guarded on by the readonly state. Editor state updates should work in read only mode though.

**Comment by yudori** [comment]
@trueadm That sounds ideal to me! I would also argue selection change events would fit into that category of events that should be emitted even in read only mode

**Comment by trueadm** [comment]
> @trueadm That sounds ideal to me! I would also argue selection change events would fit into that category of events that should be emitted even in read only mode

I’d need to think about this more as selecting text in a content editable has different DOM heuristics to when you do it on non contenteditables. I’m not even sure it’s possible.

**Comment by pguduguntla** [comment]
Hey, is there any update on this? Is it possible to have a readOnly editor that listens to selection state changes?

**Comment by yudori** [comment]
@pguduguntla The solution I went with is to leave the global lexical editor readonly state as `false` and instead use a custom 'readonly' contenteditable in the text plugin.


Custom ReadOnlyContentEditable.ts

```react
import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext';
import React, { useCallback } from 'react';

export type Props = {
    id?: string,
};

export default function ReadOnlyContentEditable(props: Props): JSX.Element {
    const [editor] = useLexicalComposerContext();
    const ref = useCallback(
        (rootElement: null | HTMLElement) => {
            editor.setRootElement(rootElement);
        },
        [editor]
    );

    return (
        <div
            contentEditable={false}
            id={props.id}
            ref={ref}
        />
    );
}
```

Usage in LexicalPlainTextPlugin

```react
<LexicalPlainTextPlugin
  contentEditable={<ReadOnlyContentEditable />}
  ...
/>
```

**Comment by pguduguntla** [comment]
@yudori  Oh sweet! That works for my use case, thanks so much man!

**Comment by mahmedmushtaq** [comment]
@yudori @zurfyx  it is causing a problem in my condition. When I am trying to add  the new value by setting `contenteditable={stateTrueBool}` then my new data would be lost after setting `conditEditable=false`. Can you please guide me on why is it deleting the new data.

**Comment by 6peterlu** [comment]
@mahmedmushtaq maybe you need to call editor.setEditorState with the new editor state after you change contentEditable flag?
