### ISSUE TITLE
Bug: If `placeholder` exists, the first character entered will be selected.

### ISSUE THREAD

**Issue by kyoya0819** [facebook/lexical#2168]
Lexical version: 0.2.9

## Steps To Reproduce

I do not have a computer with a non-Japanese keyboard, so I am writing about how to reproduce this on a Japanese keyboard.

1. Set `placeholder` to something other than `undefined`.
2. Selects the input area.
3. Change the character input mode to alphanumeric input mode.
4. Changes the character input mode to Kana (Japanese) input mode.
5. Type some characters.

~~This bug can also be seen in [Lexical's Playground](https://lexical-playground.vercel.app/).~~
This bug can also be seen in [the sample embedded on the home page](https://lexical.dev/).

## The current behavior

https://user-images.githubusercontent.com/45027336/168419957-56384162-746a-4261-acd5-91edb65855c6.mov

## The expected behavior

If I set `placeholder` to `undefined`, I will not get this error.
However, I'll get a type definition error.

https://user-images.githubusercontent.com/45027336/168419862-6fd80e0c-6088-4be1-8fd5-9212857b845b.mov

I am not very good at English, so if I am wrong, I would appreciate it if you could let me know.
Thanks for reading! Thanks for the great library!

**Comment by trueadm** [comment]
What browser and operating system are you using?

**Comment by kyoya0819** [comment]
I forgot to post the information. My apologies.

As far as I could confirm, only the combination of macOS and Chrome could confirm this phenomenon.

Here are the respective versions.
macOS: 12.3.1
Chrome: 101.0.4951.64

Also, let me make a correction regarding the first Issue.
The same behavior was observed on the Lexical site, not on the "Playground" but on the sample embedded on the home page.

**Comment by trueadm** [comment]
Hmm, I wonder if this is related to plain text mode. On the playground website, if you click in the bottom left, on the toggle and switch to Plain text mode. Does this issue occur then too?

**Comment by trueadm** [comment]
I'm finding it really hard to reproduce this issue. Every-time I enter a character on either playground, or on the website example (which is a plain text example), it works fine. I'm also on macOS + Chrome.

**Comment by kyoya0819** [comment]
> Hmm, I wonder if this is related to plain text mode. On the playground website, if you click in the bottom left, on the toggle and toggle off "Rich text" mode. Does this issue occur then too?

Both with Rich mode off and on, Playground was unable to reproduce the behavior of the video in this issue.

> I'm finding it really hard to reproduce this issue. Every-time I enter a character on either playground, or on the website example (which is a plain text example), it works fine. I'm also on macOS + Chrome.

Perhaps a Japanese keyboard is needed to reproduce the problem.
I will try to confirm that it is not just my problem by using other devices.
However, this may take a little time to request, etc.

> Let me know if https://github.com/facebook/lexical/pull/2185 helps any.

I have tried Vercel's Preview and nothing seems to change.

**Comment by kyoya0819** [comment]
There are three embedded samples on [the home page](https://lexical.dev/).
Only one of them `Built to Extend` worked correctly, the other two did not.

**Comment by kyoya0819** [comment]
I had a friend of mine confirm this and he seemed to behave the same way as I did.

macOS: 12.3
Chrome: 101.0.4951.64

**Comment by trueadm** [comment]
I've tried to reproduce this with a Japanese keyboard (iOS + macOS) on the playground and I cannot see any issues.

**Comment by zurfyx** [comment]
Closing as inactive, happy to reopen if the issue persists
