### ISSUE TITLE
Question : logic of lexical

### ISSUE THREAD

**Issue by alajillo** [facebook/lexical#2169]
Hi dev team.
this is drawing that i understand lexical logic

![lexical flow (1)](https://user-images.githubusercontent.com/78560569/168424958-cf64c2b9-a839-44a9-a9c7-1d1ab18e7686.png)

logic:
* first we create editorState instance via createEditor api
* attach to rootElement with contenteditable
* update editor state via editor.update()
* new editor state become pending state and compare with current state
* apply diff to root element
* it is also able to update via listeners, commands, nodeTransForms

do i understand right?

**Comment by acywatson** [comment]
Hey @alajillo, yes - this is basically correct. Listeners and commands don't necessarily update the editor, though. Commands are just a pub-sub means of communication between loosely coupled components. They don't necessarily have to trigger and update the editor state, though they frequently do. Listeners are similar - you can listen to various events and update the editor in response, but you don't necessarily have to update the editor.

Transforms are sort of in a slightly different category. They allow you to listen to changes to a specific node type BEFORE the actual update is applied. This means you can intercept changes and alter or even prevent them.

If you have any other questions, feel free to post them here, or join us on Discord :)
