### ISSUE TITLE
Bug: TextNode with inert mode has unexpected behavior

### ISSUE THREAD

**Issue by fosple** [facebook/lexical#2180]
## Issues

When creating a TextNode with "inert" mode (see https://lexical.dev/docs/concepts/nodes#textnode) I discovered the following bugs:

1. Node does not replace "<RichTextPlugin placeholder=" text, when being inserted
2. One cannot enter a TextNode after inert node (put caret behind inert-TextNode)
3. Copy & pasting a inert node does not preserve the content

## Steps to reproduce & current behavior

See video:
https://user-images.githubusercontent.com/4522947/168487590-ea4dc389-e1a1-4f0a-a489-9821f11a3edc.mov

Try it out:
https://codesandbox.io/s/lexical-rich-text-example-forked-geil3d?file=/src/plugins/ToolbarPlugin.js

## The expected behavior

See video (Google Docs is a good example how inert TextNodes should be handled: 
https://user-images.githubusercontent.com/4522947/168487611-4ccc36cb-aec6-4fa8-9461-e4d6a1a3db6f.mov

1. Enter @Dropdown in a Google Docs document to try it out (see video)

**Comment by trueadm** [comment]
Hey, inert text nodes have undocumented special behavior. They are not designed to be used as placeholder text, and rather to be used as auto complete text. The user shouldn't be able to copy, or select the text and nor can they insert text after it (if selection changes, you should remove the inert text from the editor). I'd probably advise against using inert unless you really need to use it.

**Comment by fosple** [comment]
@trueadm Ah ok, thanks for clarifying. You can close the ticket then. I guess for the Google Docs Dropdown use case I should rather use a Decorator node. Is there the option to provide a "alt" text to a decorator node (like for images)? So when you copy the contents of the lexical editor to another plain-text-editor I can provide what text to be pasted for the decorator node when it needs to be converted to plain text?

**Comment by trueadm** [comment]
You can add `getTextContent()` to your Decorator Node and that should hopefully do the trick!

**Comment by fosple** [comment]
@trueadm Thanks a lot! That worked like a charm :)
