### ISSUE TITLE
Bug: PlainTextPlugin initialEditorState string throws error

### ISSUE THREAD

**Issue by always-maap** [facebook/lexical#2186]
lexical PlainTextPlugin initialEditorState doesn't accept string

![2022-05-16-183914_1920x1080_scrot](https://user-images.githubusercontent.com/58308349/168611896-ea8742d2-3d7a-4c16-bba8-65f0994f2f58.png)

Lexical version:0.2.9

## Steps To Reproduce

use PlainTextPlugin with initialEditorState set to a string 

## The current behavior
Unexpected token e in JSON at position 1

## The expected behavior
either support converting string to lexical data structure or removing the type

**Comment by always-maap** [comment]
I can work on the pr. please decide the direction

**Comment by trueadm** [comment]
It does accept a string. It’s likely that your input is incorrect? Can you paste it in the issue?

**Comment by always-maap** [comment]
> How are you getting the JSON?

you mean editorState.toJSON().editorState ?

**Comment by trueadm** [comment]
You just need to do `JSON.stringify(editorState).`

**Comment by always-maap** [comment]
> You just need to do `JSON.stringify(editorState)`.

yeah I know but it was the recommended way in doc 
https://lexical.dev/docs/concepts/editor-state

**Comment by trueadm** [comment]
We should fix that!

**Comment by always-maap** [comment]
> You don’t need to serialize this to your database. You can easily traverse through and define your own format. We do this internally at Meta - we basically construct a single string and mark the ranges for the basic cases.

I learned how facebook converts lexical internal representation. something like this
```
"message":{
  "ranges":[{"entity":{"id":"149980285694976"},"length":11,"offset":13}],
  "text":"lexical test Always MAAP this is\npretty cool"
}
```

but still, we need to convert it back to lexical representation for editing. is there any easy internal way of doing it or just creating the object with ranges and messages?

**Comment by acywatson** [comment]
@fantactuka might have insight

**Comment by fantactuka** [comment]
> @fantactuka might have insight 

> "message":{
>   "ranges":[{"entity":{"id":"149980285694976"},"length":11,"offset":13}],
>   "text":"lexical test Always MAAP this is\npretty cool"
> }

Dominic pretty much answered that: it seem reasonable to serialize to a single string + entity ranges for plain text given it's expected to be very simple. And it'll be a different story if you use lexical for rich text, then ranges for entities and styles would become more complex to convert to/from so might want to stick to something more tree-like

**Comment by acywatson** [comment]
@always-maap let's continue discussion in #2197 and close this one out. That way we can get more discovery/input from the community.
