### ISSUE TITLE
Feature: Add a "Clear formatting" button to the Playground

### ISSUE THREAD

**Issue by thegreatercurve** [facebook/lexical#2190]
Add a "Clear formatting" to the Playground which will restore all text content to an unstyled paragraph.

**Comment by acywatson** [comment]
Should selecting "Normal" from the dropdown do this?

**Comment by thegreatercurve** [comment]
> Should selecting "Normal" from the dropdown do this?

That should just change the font size. Clearing all formatting, should change the font size, font style, mode, BIU formatting, and change any Element and Decorator nodes which contain text to just Text nodes.

**Comment by im-adithya** [comment]
I would like to work on this!

**Comment by thegreatercurve** [comment]
> I would like to work on this!

@im-adithya Go for it! Feel free to assign yourself to the issue.

**Comment by im-adithya** [comment]
@thegreatercurve Please review :D
