### ISSUE TITLE
Bug: createNodeFromParse: type "link" + type "list" not found

### ISSUE THREAD

**Issue by yuuminakamura** [facebook/lexical#2192]
cannot display content includes link and list.

Lexical version: latest

Error: 
**createNodeFromParse: type "link" + not found**

**createNodeFromParse: type "list" + not found**

I saved editor state in BE and wanted to display it in some page.
the content with bold, italic, alignment and indent were worked perfect.
![Screen Shot 2022-05-16 at 5 47 33 PM](https://user-images.githubusercontent.com/46723838/168705001-f3dc85fc-7f0a-434c-95b8-5738300adc57.png)

However, when I use link and list. I am getting errors 

code
```
                    <LexicalComposer
                        initialConfig={{
                            onError(error) {
                                throw error;
                            },
                            readOnly: true,
                            nodes: [],
                        }}
                    >
                        <PlainTextPlugin
                            placeholder={null}
                            contentEditable={<ContentEditable />}
                            initialEditorState={editorState}
                        />
                    </LexicalComposer>
```

I just want to display the plain content.

when I submit editorState to save in BE I use JSON.stringify(value)
so the value I save looks like this

`value: "{\"_nodeMap\":[[\"root\",{\"__children\":[\"49\"],\"__dir\":\"ltr\",\"__format\":0,\"__indent\":0,\"__key\":\"root\",\"__parent\":null,\"__type\":\"root\"}],[\"49\",{\"__type\":\"paragraph\",\"__parent\":\"root\",\"__key\":\"49\",\"__children\":[\"71\"],\"__format\":0,\"__indent\":0,\"__dir\":\"ltr\"}],[\"71\",{\"__type\":\"text\",\"__parent\":\"49\",\"__key\":\"71\",\"__text\":\"hello\",\"__format\":0,\"__style\":\"\",\"__mode\":0,\"__detail\":0,\"__marks\":null}]],\"_selection\":{\"anchor\":{\"key\":\"71\",\"offset\":0,\"type\":\"text\"},\"focus\":{\"key\":\"71\",\"offset\":5,\"type\":\"text\"},\"type\":\"range\"}}"`

using this value as an initial value to display with Editor works perfect.

```
                <LexicalComposer initialConfig={editorConfig}>
                    <div className={classes.editorContainer}>
                        <ToolbarPlugin />
                        <div className="editor-inner">
                            <RichTextPlugin
                                contentEditable={
                                    <ContentEditable
                                        className={classes.editorInput}
                                    />
                                }
                                initialEditorState={
                                    initialValue ? initialValue : null
                                }
                                placeholder={null}
                            />
                            <OnChangePlugin onChange={onChange} />
                            <AutoFocusPlugin />
                            <ListPlugin />
                            <LinkPlugin />
                        </div>
                    </div>
                </LexicalComposer>
```

but not with PlainTextPlugin.
I am wondering if it is not a bug and I am missing something.

**Comment by acywatson** [comment]
In your editorConfig, you need to include ListNode and LinkNode in the list in the nodes property:

```
                    <LexicalComposer
                        initialConfig={{
                            onError(error) {
                                throw error;
                            },
                            readOnly: true,
                            nodes: [LinkNode, ListNode, ListItemNode],
                        }}
                    >
                        <PlainTextPlugin
                            placeholder={null}
                            contentEditable={<ContentEditable />}
                            initialEditorState={editorState}
                        />
                    </LexicalComposer>
```

**Comment by acywatson** [comment]
This should help - 

https://github.com/facebook/lexical/pull/2196

You should have seen an error for LinkNode though - looks like our runtime check is already in place there.

**Comment by yuuminakamura** [comment]
@acywatson thank you for finding my mistakes.
it is working now✨
