### ISSUE TITLE
Bug: Custom Decorator nodes not rendered after editor state is restored from local storage

### ISSUE THREAD

**Issue by vineetdigit** [facebook/lexical#2195]
When the editor state containing custom decorator nodes is stored in the local storage, and later retrieved, parsed and passed down to the RichTextPlugin, then the custom decorator nodes are **not** rendered. However, paragraph/text nodes are rendered just fine. The expected behavior is that all nodes are rendered. This problem is at least reproducible in the codesandbox below.

Lexical version: 0.2.9

## Steps To Reproduce

I have created a custom decorator node named Excalidraw which currently renders just a div. 

The codesandbox has instructions on the app screen to reproduce the issue.

https://codesandbox.io/s/frosty-aryabhata-e4pkke-e4pkke

## The current behavior
Only paragraph/text nodes are rendered.

## The expected behavior
paragraph/text, as well as custom decorator node, must render

**Comment by trueadm** [comment]
I'm hoping that https://github.com/facebook/lexical/pull/2200 fixes this issue due to lifecycle sequencing.
