### ISSUE TITLE
Feature: DraftJS Migration Documentation Utils

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#2197]
We should add documentation around how to move to Lexical from DraftJS and perhaps even conversion utilities to help with the process.

Discussion moved from: https://github.com/facebook/lexical/issues/2186

**Comment by zurfyx** [comment]
Duplicate of #1641

**Comment by dragogargo** [comment]
built a tool for this: https://github.com/dragogargo/draft-to-lexical

Converts RawDraftContentState → SerializedEditorState. Supports standard blocks, inline styles, and entities (links, images). You can also plug in custom entity handlers.

npm install draft-to-lexical

Works as a library or CLI.
