### ISSUE TITLE
Bug: Superscript and Subscript are not interpreted while using clipboard.

### ISSUE THREAD

**Issue by sameer1612** [facebook/lexical#2202]
Lexical version:

## Steps To Reproduce

1. Use lexical playground.
2. Copy and paste some page content containing sub and sup elements from elsewhere.
3. Observe behaviour for superscript and subscript elements.

Content copied:
-----------
<img width="361" alt="image" src="https://user-images.githubusercontent.com/39580073/168963386-eaa3b96b-4e14-47fd-bca1-b1c5573bf4f3.png">

HTML code for above content: 
-----------
```
<p class="plain-text"><sup>a</sup>RND and JLM contributed equally to this paper.</p>
<p class="plain-text"><sub>b</sub>JLG and JS contributed equally to this paper.</p>
```

## The current behavior
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/39580073/168962907-9ae91e1e-cb34-4a14-86ab-6d15b92c16a6.png">

## The expected behavior
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/39580073/168962964-49f72f3f-2d83-45fd-9658-d5d8011dedef.png">

**Comment by acywatson** [comment]
This was fixed here for Google docs here: #2571 

Looks like we're still not supporting the semantic HTML import
