### ISSUE TITLE
Bug: Paste strikethrough and italic from Google Docs

### ISSUE THREAD

**Issue by hanford** [facebook/lexical#2216]
Some formatting (strikethrough and italic) are lost when pasting from Google docs. This is likely because Google docs doesn't use semantic HTML and instead uses inline styles. In the past, I've needed to detect when a paste is coming from Google docs and then look at inline styles. I've done this by seeing if the paste payload includes `docs-internal-guid` and then looking at nodes `font-style` (for italic) and `text-decoration` for strikethrough.

Lexical version: 0.2.9 (Latest at time of issue creation)

## Steps To Reproduce

1. Go here: https://docs.google.com/document/d/1qLjUKNWU-VK_TQsUY18qqyA_gtIpJOsNAMFh4et21Fw/edit?usp=sharing
2. Copy contents
3. Paste into sandbox

Link to code example:
https://codesandbox.io/s/lexical-rich-text-example-forked-mxx7z8?file=/src/Editor.js

## The current behavior
Formatting is lost

## The expected behavior
Formatting should be retained

**Comment by acywatson** [comment]
Thanks for the detailed report - I think we do something similar already for bold text pasted from google docs already.

**Comment by hanford** [comment]
I'll open a PR this morning

**Comment by hanford** [comment]
Just opened https://github.com/facebook/lexical/pull/2220, happy to make any modifications if needed!
