### ISSUE TITLE
Bug: MentionsPlugin click interactions fail to insert correct mention

### ISSUE THREAD

**Issue by dylanhusted** [facebook/lexical#2217]
Live on the playground, if you trigger the mentions typeahead and then select an option with your mouse, you'll find that the first option is selected instead of your choice. You'll also notice two hover/focus highlights happening, even though you've used your mouse to hover on a specific option.

![Screen Shot 2022-05-18 at 10 49 40 PM](https://user-images.githubusercontent.com/7398726/169219895-f3e91e84-f87a-44a2-8e3b-2e9051101c87.jpg)

^^ I clicked Admiral Dodd Rancit here

![Screen Shot 2022-05-18 at 10 49 45 PM](https://user-images.githubusercontent.com/7398726/169219908-95c0e49b-9774-42ac-82c7-512e8b066512.jpg)

^^ And Aayla Secura was inserted

Lexical version: 0.2.9

## Steps To Reproduce

1. Type @a in the playground
2. Use your mouse to hover on any option except the first
3. Click on that option
4. See first option inserted instead of your choice

Link to code example:

The problem is here
https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/MentionsPlugin.tsx#L786

There is both an `isSelected` and `isHovered` state. `isSelected` determines which item gets inserted, but it isn't set `onMouseEnter`. I think this differentiation is unnecessary, and there could just be one focused state. This gets rid of multiple highlights and this bug.

I have a branch locally with this fixed but don't have push writes to get a PR up for review. Happy to push up if helpful!

**Comment by acywatson** [comment]
> I have a branch locally with this fixed but don't have push writes to get a PR up for review. Happy to push up if helpful!

Thanks for reporting! Would love to have a look a the PR. The contribution workflow is typically to create a fork of lexical, then create a pull request from that fork into the main repo. If you're up for doing that, I'd be happy to take a look at the PR.

https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow

**Comment by dylanhusted** [comment]
> Thanks for reporting! Would love to have a look a the PR. 

@acywatson Sounds good! PR ready for you here: https://github.com/facebook/lexical/pull/2224

**Comment by acywatson** [comment]
@dylanhusted Awesome. Thanks so much for doing this.

Closing as fixed by #2224
