### ISSUE TITLE
Feature: INSERT_CHARACTER_COMMAND

### ISSUE THREAD

**Issue by robwegbr** [facebook/lexical#2219]
Following closure of [#2163](https://github.com/facebook/lexical/issues/2163) I'm looking for a way to detect any new character that is being added to the editor such that it can be inserted as a custom text node, rather than a regular text node.

Currently the INSERT_TEXT_COMMAND seems to run only under certain conditions inside the function "onBeforeInput".

In DraftJS the equivalent I was using was [handleBeforeInput](https://draftjs.org/docs/api-reference-editor/#handlebeforeinput) which gives you access to the to be inserted "chars" and the "editorState".

Not sure if I'm missing an alternate way of implementing this use-case but having looked at the various approaches I don't see how we can make this work without significant performance overhead (looked at INSERT_TEXT_COMMAND, Mutation listener, TextContent listener, Node transforms). This also considering the content we're working with will be large and heavily edited.

Thanks for your looking into this!

**Comment by trueadm** [comment]
There’s no consistent way to do this. Text insertion can come from things that we get events for, but also it could come from other things (extensions, spellcheck, IME, execCommand etc). Plus, mutation listeners might mutate the event thereafter. The best way to track text changes is by diffing the editor states before and after.

**Comment by robwegbr** [comment]
hmm got it, and would you recommend tracking through a mutation listener and then comparing against a (stored) prevEditorState? Or is there a better way to approach this

**Comment by trueadm** [comment]
You can use an update listener, it gives you the `prevEditorState` which helps for custom diffing. You can just get the text content of the prev editor state vs next and then do a lightweight diff on the text to see what was changed. See https://github.com/facebook/lexical/blob/main/packages/shared/src/simpleDiffWithCursor.js for an example of the diff algorithm.

**Comment by robwegbr** [comment]
Thanks for your help - I'll look into this approach! Closing this one
