### ISSUE TITLE
Feature: maxLength

### ISSUE THREAD

**Issue by jack-guy** [facebook/lexical#2230]
Setting a maxlength for an editor was something that was [quite complicated](https://stackoverflow.com/a/46071494/1008741) using Draft.js. It's also a common need - particularly for developers relying on an editor primarily for plaintext functionality (as a replacement for `<textarea />`).

I see that there's some WIP work being done on [LexicalCharacterLimitPlugin](https://github.com/facebook/lexical/blob/main/packages/lexical-react/src/LexicalCharacterLimitPlugin.tsx) but testing this feature out in the playground seems to show a different behavior than I expected - rather than limiting input it simply highlights input that's outside the character limit - 
![image](https://user-images.githubusercontent.com/957238/169620937-1a17b89e-b367-4ad4-8bd9-a840a89e2b32.png)

I also tried to poke around the source code for how I might implement this myself. My current, very naive implementation:
```
const LexicalMaxLengthPlugin = ({ maxLength }) => {
    const [editor] = useLexicalComposerContext();

    useEffect(() => {
        editor.registerTextContentListener(textContent => {
            if (textContent.length > maxLength) {
                editor.update(
                    () => {
                        $getSelection().deleteCharacter(true);
                    },
                    {
                        tag: 'history-merge',
                    },
                );
            }
        });
    }, [editor]);

    return null;
};
```
this has many problems (I wasn't really expecting it to work)
- very slow to delete excessive characters
- using a bad update pattern
- even with the `history-merge` tag, the history stack is broken. A keypress to enter a character beyond the maxlength is still added to the stack.

I'm curious if functionality to mimic the behavior of `<textarea maxlength=""` can be accomplished using Lexical as it exists today, or if there will need to be some new APIs implemented. In particular without some pretty tedious and potentially slow node manipulation it's not clear to me how one could truncate excess characters in a single update.

My team is trying to be an early adopter of Lexical - we're in the process of migrating our application to React 18 and draft.js is partially blocking that. Thanks!

**Comment by trueadm** [comment]
> I'm curious if functionality to mimic the behavior of <textarea maxlength="" can be accomplished using Lexical as it exists today, or if there will need to be some new APIs implemented. In particular without some pretty tedious and potentially slow node manipulation it's not clear to me how one could truncate excess characters in a single update.

It should definitely be possible to do this. I might take a stab at hacking something together here!

**Comment by trueadm** [comment]
Check out https://github.com/facebook/lexical/pull/2254!

**Comment by trueadm** [comment]
Thank you for the awesome feedback. I addressed them in https://github.com/facebook/lexical/pull/2258. :)

**Comment by jack-guy** [comment]
@trueadm thanks again for the quick fixes. From my tests the history works almost perfectly on the latest playground revision. There's only one case I found that is other than what I expected. If I copy text that's at the max length and attempt to paste it with the cursor at the start it seems to continue to add to the history (and appears to be moving the anchor and focus forward):

![image](https://user-images.githubusercontent.com/957238/170140383-f0535873-6fe5-49ba-a90c-bdaa13c7c029.png)

after a paste:

![image](https://user-images.githubusercontent.com/957238/170140414-f888eb70-8bc6-454c-a910-24c7b79a4dd4.png)

Oddly this does not apply to typing or any other strings I attempt to paste in the same manner.  So very much an edge case, not sure users would ever actually run into this one. 

I'm still seeing strange behavior with editor state inconsistency however.

1. `"what happens if this is trunca"`
![image](https://user-images.githubusercontent.com/957238/170139044-1f0b2dd0-3298-4dd2-b38b-56706825a2bb.png)
2. insert `enter` after `"if"`. Text is truncated at the end.
![image](https://user-images.githubusercontent.com/957238/170139115-a796885f-a6fc-47f4-b2af-4c948fa33a7f.png)
3. press `enter` a second time. Now try to backspace - will not work, instead will highlight text one character at a time:
![image](https://user-images.githubusercontent.com/957238/170139378-e2b6ae5a-5cd7-4146-8d96-a33740b290fb.png)
4. insert characters in the middle - editor state and content editable are inconsistent 
![image](https://user-images.githubusercontent.com/957238/170139411-3ef6776a-8232-42fb-b86d-cac0917c50d8.png)
 
This is in Chrome `101.0.4951.64` if that's at all helpful.

Again want to say I appreciate the time you've put into this - this seems like a particularly tricky feature request so no worries at all if this has to be set aside for the time being :)

**Comment by trueadm** [comment]
Thanks yet again for finding that issue. It was obvious on reflection: https://github.com/facebook/lexical/pull/2265

**Comment by jack-guy** [comment]
Thanks @trueadm, that seems to have addressed the weird highlighting + editor state inconsistency!

However, pressing enter in the middle of text still truncates the end of the string. Original text:
![image](https://user-images.githubusercontent.com/957238/170352423-f6690d99-1011-449d-ba60-fd1c04c1a672.png)
after 6 returns:
![image](https://user-images.githubusercontent.com/957238/170352501-94eab067-89df-4e47-9f16-c6bbb6972f92.png)

**Comment by trueadm** [comment]
That's intentional. An element has text content `\n\n`.

**Comment by jack-guy** [comment]
Sure yeah, makes sense. Just treating `<textarea maxLength` as reference I wouldn't except a return to be treated any differently from other keyboard input :)

This is a great start for my team though and your help has been invaluable. Thanks again Dominic! Hope as I familiarize myself with Lexical and the documentation gets refined I'll be able to pitch in here sometime soon too :)

**Comment by trueadm** [comment]
No problem. Actually, I came up with a neat heuristic that handles this in the simple case: https://github.com/facebook/lexical/pull/2273

**Comment by jack-guy** [comment]
After the latest revision, `MaxLengthPlugin` seems to be working perfectly in the playground. Looking forward to getting this all set up in production here when the latest Lexical is released!

**Comment by granmoe** [comment]
Where is this exposed in the public API? Is it in a package or anything?

**Comment by granmoe** [comment]
I'm just copying the source for now as a workaround

**Comment by AntonOfTheWoods** [comment]
For anyone else looking, the project maintainers seem to not have been given the bandwidth to document properly. A LOT of actually useful functionality is available in the playground code including [a `MaxLengthPlugin`](https://github.com/facebook/lexical/tree/main/packages/lexical-playground/src/plugins/MaxLengthPlugin)

**Comment by bartoszhernas** [comment]
This is nice for frontend but how do we use it on the backend? I can now send longer data to my backend, and it's not limited at all. I tried reusing the plugin code but I understand that it depends on currently selected TextNode. 

The solution for that problem is probably more complicated? Take all the text nodes and start cutting them from the back until we reach proper content size. 

Probably better to just error out if the content is too big (so someone plays tricks with your frontend and sends custom requests)
