### ISSUE TITLE
Feature: background color of the text, automatically apply the black and white text color.

### ISSUE THREAD

**Issue by arayutw** [facebook/lexical#2232]
When applying the background color of the text, it may be useful to be able to automatically apply the black and white text color as an option.
For many people, choosing a background color while considering the text color can be a hassle.

```
function blackOrWhite ( hexcolor ) {
	var r = parseInt( hexcolor.substr( 1, 2 ), 16 ) ;
	var g = parseInt( hexcolor.substr( 3, 2 ), 16 ) ;
	var b = parseInt( hexcolor.substr( 5, 2 ), 16 ) ;

	return ( ( ( (r * 299) + (g * 587) + (b * 114) ) / 1000 ) < 128 ) ? "white" : "black" ;
}
```

https://www.w3.org/TR/AERT/#color-contrast

**Comment by thegreatercurve** [comment]
I like the idea of this but I think the UX might be somewhat unpredictable or unexpected, especially if the user has already made an explicit choice within the highlight and text color pickers.

**Comment by ArabCrew786** [comment]
> When applying the background color of the text, it may be useful to be able to automatically apply the black and white text color as an option. For many people, choosing a background color while considering the text color can be a hassle.
> 
> ```
> function blackOrWhite ( hexcolor ) {
> 	var r = parseInt( hexcolor.substr( 1, 2 ), 16 ) ;
> 	var g = parseInt( hexcolor.substr( 3, 2 ), 16 ) ;
> 	var b = parseInt( hexcolor.substr( 5, 2 ), 16 ) ;
> 
> 	return ( ( ( (r * 299) + (g * 587) + (b * 114) ) / 1000 ) < 128 ) ? "white" : "black" ;
> }
> ```
> 
> https://www.w3.org/TR/AERT/#color-contrast


Hey man so where do i add the TEXT ?

**Comment by ArabCrew786** [comment]
`#00FF00`Okay

**Comment by ArabCrew786** [comment]
`HELLO THIS IS GREEN #00FF00`

**Comment by ArabCrew786** [comment]
`#000000`where to add the test lol for coloring the whole sentence.`#000000`

`where to add the test lol for coloring the whole sentence.#000000where to add the test lol for coloring the whole sentence.`

**Comment by ArabCrew786** [comment]
where to add the TEXT`#00FF00`
/ for coloring the whole sentence.

**Comment by ArabCrew786** [comment]
[https://t.me/imakeconfigs](![Telegram-Symbol](https://github.com/ArabCrew786/FortniteDeviceAuthGenerator/assets/136216042/cba988e9-7cbd-4df6-a766-795b681edf3f))

**Comment by ArabCrew786** [comment]
![Telegram-Symbol](https://github.com/facebook/lexical/assets/136216042/13ee11f2-f049-4f32-8cd8-df499660c61d)[Telegram](https://t.me/imakeconfigs)
