### ISSUE TITLE
Feature: Checklist is inconvenient for touch devices

### ISSUE THREAD

**Issue by ghost** [facebook/lexical#2233]
With a touch device, it is very difficult to check and uncheck the checkbox, and it is not possible to operate naturally.
I would like follow-up such as not focusing when checking and taking a large click range.

**Comment by im-adithya** [comment]
We can take inspiration from Google Keep:
<img src="https://user-images.githubusercontent.com/64399555/171399594-67e7a4e9-ce3e-4193-aab4-36e45c58780f.jpg" width="400" />

**Comment by thegreatercurve** [comment]
I like @im-adithya's suggestion of increasing the touchable area around the check box. 

Closing this as I don't think there are any underlying bugs with core. The padding of the check box, and any additional pseudo elements to increase the touchable surface, can be controlled via the developer's own styling choices.
