### ISSUE TITLE
Bug: setReadOnly in plugin doesn't change editor

### ISSUE THREAD

**Issue by fameoflight** [facebook/lexical#2234]
```javascript 

import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext'
import React, { useEffect } from 'react'

interface IFormPlugin {
  value: string;
  readOnly?: boolean;
}

export default function FormPlugin({ value, readOnly }: IFormPlugin): React.ReactElement {
  const [editor] = useLexicalComposerContext()

  useEffect(() => {

    if (value && editor && readOnly) {
      const initialEditorState = editor.parseEditorState(value)
      editor.setEditorState(initialEditorState)

      editor.setReadOnly(readOnly)
    }
  }, [value, editor, readOnly])

  return <div />
}

```

when using this plugin when I change readonly I expect editor to change readonly state, but that's not the case. Maybe I am missing something here.

**Comment by trueadm** [comment]
Where are you supplying your content editable? Are you using `<LexicalContentEditable />`?

**Comment by fameoflight** [comment]
Here are sample of my code. I removed this plugin for now. 

But I expected the abstraction to work as expect. 

https://github.com/facebook/lexical/issues/1834#issuecomment-1134021296

**Comment by trueadm** [comment]
I just tried this out on the playground app locally and it seems to be working fine. Have you checked the HTML of the content editable and made sure it's showing `contenteditable="false"`?

**Comment by fameoflight** [comment]
my code it goes into some kind of infinite loop. Unable to debug as my browser just hangs. For now I am unblocked we can close this.
