### ISSUE TITLE
Bug: Quote markdown export missing newline

### ISSUE THREAD

**Issue by hanford** [facebook/lexical#2247]
When markdown exporting editor content quotes only have one line when two are needed. In markdown, blockquote content followed by a single line is treated as a continuation of the blockquote content.

Lexical version: 0.2.9

## Steps To Reproduce

1. Erase playground content
2. type `> foo` hit [enter], type `bar`
3. Note that bar is _outside_ the blockquote
4. toggle markdown view
5. Take output and put into a markdown preview
6. See that `bar` is inside the blockquote content

See commonmark: https://spec.commonmark.org/dingus/?text=%3E%20foo%0Abar%0Abaz%0A%0Aasdf%0A
See marked: https://marked.js.org/demo/?outputType=html&text=%3E%20foo%0Abar%0Abaz%0A%0Abar&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master

## The current behavior
Content following text is treated as blockquote

## The expected behavior
Content in editor text following a quote node should not formatted as blockquote

**Comment by hanford** [comment]
https://github.com/facebook/lexical/pull/1998#discussion_r861085636

**Comment by thegreatercurve** [comment]
Closed by #1998

**Comment by hanford** [comment]
@thegreatercurve this has not been closed and is still a bug

For block quotes to be escaped in markdown, there must be two new lines, not one.

This input:
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/2148168/173862424-56232ef5-bdfa-4c6e-9c3c-3a04b1c6e802.png">


Creates this markdown:
<img width="938" alt="image" src="https://user-images.githubusercontent.com/2148168/173862490-f54d1073-a6f5-4d13-9a35-20d9f0f1c030.png">

Which in any markdown renderer, renders this way:
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/2148168/173862604-1af7554d-6c4e-4660-8cbc-ea3920479894.png">

**Comment by fantactuka** [comment]
Partially addressed in #2519, although it uses hard line breaks (similar to what github does)

**Comment by digitalgopnik** [comment]
Seems fixed now in current playground-version :)

**Comment by hanford** [comment]
It does seem fixed in the playground now! @fantactuka is this good to close out?
