### ISSUE TITLE
Add Tests for MaxLength functionality

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#2255]
#2254 introduced a MaxLength plugin to the playground:

https://github.com/facebook/lexical/blob/90aad493addf837f05af86cd2a28871083e6e73e/packages/lexical-playground/src/plugins/MaxLengthPlugin.tsx#L14

as well as a helper function that contains most of the logic for enforcing the max length:

https://github.com/facebook/lexical/blob/90aad493addf837f05af86cd2a28871083e6e73e/packages/lexical-selection/src/index.ts#L904

It would be great to have an e2e test for the MaxLength plugin, as well as a suite of unit tests for the new helper function in lexical/selection.

**Comment by im-adithya** [comment]
@acywatson please review :)

**Comment by thegreatercurve** [comment]
Fixed in #2296
