### ISSUE TITLE
Bug: Unexpected language change for Code Block

### ISSUE THREAD

**Issue by mmarkelov** [facebook/lexical#2271]
Lexical version: latest

## Steps To Reproduce

1. Select new Code Block
2. Change the language to Python for example
3. Insert copied text

## The current behavior
The language changed to default JavaScript

## The expected behavior
Should keep Python

https://user-images.githubusercontent.com/22371328/170352258-e9ed6ab3-5c17-4a01-a401-9cb6dcb23a4d.mov

**Comment by trueadm** [comment]
We plan on rewriting the code block in the future and this should be fixed by that work.
