### ISSUE TITLE
Bug: Deserializing HTML causes tags to apply to entire rest of text 

### ISSUE THREAD

**Issue by rempelj** [facebook/lexical#2274]
There is a bug where HTML tags seem to not deserialize correctly which causes tags to apply to the entire rest of the text. I am experiencing this issue both with @lexical/clipboard and with the next @lexical/html package.

---

Lexical version: 0.2.9

## Steps To Reproduce

```
const [editor] = useLexicalComposerContext();
editor.update(() => {
  const html = '<p>a<strong>b</strong>c</p>'
  const parser = new DOMParser();
  const dom = parser.parseFromString(html, 'text/html');
  const nodes = $generateNodesFromDOM(editor, dom);
  const root = $getRoot();
  root.clear();
  root.append(...nodes);
})
```

Also noticed when using `$insertDataTransferForRichText(fakeDataTransfer, selection, editor);` (from [here](https://github.com/facebook/lexical/issues/1834#issuecomment-1105341834))

## Live example
https://codesandbox.io/s/lexical-rich-text-example-forked-65hsq1?file=/src/Editor.js

Look for `<SetInitialHtmlValue value="<p>a<strong>b</strong>c</p>" />`
See the rich text has more bold characters than the initial html.

## The current behavior
The `<strong>` tag applies to all the remaining characters:
```
<p dir="ltr"><span data-lexical-text="true">a</span><strong data-lexical-text="true">bc</strong></p>
```

## The expected behavior
The `<strong>` tag should only apply to the middle character.
```
<p dir="ltr"><span data-lexical-text="true">a</span><strong data-lexical-text="true">b</strong><span data-lexical-text="true">c</span></p>
```

**Comment by trueadm** [comment]
Thanks for the report! https://github.com/facebook/lexical/pull/2275 should fix this issue :)

**Comment by rempelj** [comment]
Wow, that was so fast. Thanks a lot!
