### ISSUE TITLE
Bug: AutoFocusPlugin doesn't work with many editors

### ISSUE THREAD

**Issue by hanford** [facebook/lexical#2280]
When having many editors, using `AutoFocusPlugin` to control which editor receives focus doesn't seem to work

Lexical version: 0.2.9

## Steps To Reproduce

1. Have 2+ editors with and create a boolean autoFocus prop that conditionally renders the `AutoFocusPlugin`
2. conditionally active autoFocus on one of the editors
3. See that it doesn't have focus

Link to code example: https://codesandbox.io/s/many-lexical-autofocus-ype4po

## The current behavior
No editor, or sometimes the last one, receives focus

## The expected behavior
The editor with `autoFocus={true}` should receive focus

**Comment by trueadm** [comment]
Should be fixed with https://github.com/facebook/lexical/pull/2282.

**Comment by hanford** [comment]
@trueadm 🔥

**Comment by hanford** [comment]
@trueadm actually does this work in the above sandbox? (focus'ing the first of three editors)

**Comment by trueadm** [comment]
Works for me? https://codesandbox.io/s/many-lexical-autofocus-forked-lcog4q

**Comment by hanford** [comment]
@trueadm Hmmmm... probably something on my side then. Sorry about that, will keep digging and open another issue if I can repro
