### ISSUE TITLE
Bug: caret not visible between two DecoratorNode

### ISSUE THREAD

**Issue by azvoncov-smartling** [facebook/lexical#2285]
If we have two DecoratorNode entities side by side, because we add contenteditable="false", the browser does not render caret between them, although we can add text between them

Lexical version: 0.2.9

## Steps To Reproduce
1. Create two Nodes side by side inherited from DecoratorNode
2. Put the cursor between them

https://user-images.githubusercontent.com/87305102/170682093-e5e796bf-a9e0-43ee-ab15-96edd3946fb4.mov

As a solution, we can add empty text fields between the DecoratorNode's, like SlateJS does for example.

Link to code example:
https://codesandbox.io/s/stupefied-perlman-tmv9p6?file=/src/App.tsx

## The current behavior
caret not visible

## The expected behavior
caret visible

**Comment by trueadm** [comment]
Slate doesn't put empty text nodes in, it actually puts in text nodes with zero width characters. Lexical used to do this a long time ago, but it actually causes far more problems than it solves. It causes issues on Android and iOS when attempting to type into the place (iOS tries to autocapitialize), screen readers like JAWS/NVDA/VoiceOver read out "Zero width space" and also it causes problems with offsets. I believe another alternative approach is to use inline imgs, like ProseMirror does.

**Comment by trueadm** [comment]
After digging into this more, it's a widespread issue with contenteditable. It's definitely not a Lexical specific problem. We have played around with zero width character hacks, as have ProseMirror and other editors – but it's not a solution. It causes far too many problems, especially with things like composition, spellcheck etc.

I think the best solution is to go back to the browser vendors and ask them to look into this problem again and get them to fix it.

**Comment by trueadm** [comment]
Closing this for now. We're aware of the issue internally and we're looking to best tackle this – given it's not really a Lexical bug.
