### ISSUE TITLE
Bug: `@lexical/html` not found in npm

### ISSUE THREAD

**Issue by harish-sethuraman** [facebook/lexical#2299]
## Steps To Reproduce
<img width="961" alt="Screenshot 2022-05-31 at 3 11 10 PM" src="https://user-images.githubusercontent.com/32865581/171144045-b2bc0ef3-b1f8-4ad8-a54c-f0e9628fb3ef.png">

1. Tried to install the above package `@lexical/html` and resulted in `An unexpected error occurred: "https://registry.yarnpkg.com/@lexical%2fhtml: Not found".`
2. Checked the NPM registry and found that there was no package in that name

document link: https://lexical.dev/docs/concepts/serialization#html---lexical
## The expected behavior

The package should have been published? If it is publish in progress feel free to close this issue :)

**Comment by obask** [comment]
This version hasn't been released yet. I'm trying to set a dependency on the github, but it would be nice if is has been published.

**Comment by harish-sethuraman** [comment]
"dependencies" : {
  "name1" : "git://github.com/user/project.git#commit-ish",
  "name2" : "git://github.com/user/project.git#commit-ish"
}

You can use the github repo url link like this and install packages.

**Comment by harish-sethuraman** [comment]
The package is now officially available! Closing this issue. 


https://www.npmjs.com/package/@lexical/html
