### ISSUE TITLE
Feature: Mermaid.js support 

### ISSUE THREAD

**Issue by jagill** [facebook/lexical#2302]
[Mermaid.js](https://mermaid-js.github.io/mermaid/#/) is a markup language to produce flowcharts and graphs.  For the feature set it supports, it allows a very quick and simple method to author graphs.  Furthermore, this markup can be handled well by source control.

If Lexical could parse and display mermaid markup, this would really improve the experience for people wanting to display a graph.  The alternative is creating a graph in Powerpoint/Excalidraw/etc, saving it as an image, and including it.

**Comment by thegreatercurve** [comment]
Closing as I don't think this should necessarily be a part of our core set of packages, but it could be created and hosted by an OSS contributor.
