### ISSUE TITLE
Bug: Combining bold italic strikethrough can generate invalid markdown

### ISSUE THREAD

**Issue by hanford** [facebook/lexical#2303]
Combining Bold, Italic and strikethrough formats can generate invalid markdown

Lexical version: 0.2.9

## Steps To Reproduce

1. Enable Bold, type (`Bold `)
2. Enable Italic, type (`Italic `)
3. Enable strike through, type (`bold italic strikethrough`)
4. View generated markdown

Note that the generated markdown is:
```
**bold *italic ~~strikethrough***~~
```

Which escapes strikethrough incorrectly, it _should_ be

```
**bold *italic ~~strikethrough~~***
```

## The current behavior
Invalid markdown is generated

## The expected behavior
Proper markdown should be generated

Current _bad_ state
<img width="700" alt="Screen Shot 2022-05-31 at 12 42 06 PM" src="https://user-images.githubusercontent.com/2148168/171271576-0b4ac128-ecf6-47b0-a280-d1f926a40abc.png">

<img width="700" alt="Screen Shot 2022-05-31 at 12 36 29 PM" src="https://user-images.githubusercontent.com/2148168/171270617-021756bb-5526-4500-9361-8e4c9906c78c.png">

Fixed state with open PR:
<img width="700" alt="Screen Shot 2022-05-31 at 12 42 33 PM" src="https://user-images.githubusercontent.com/2148168/171271647-0a6fd717-5829-4a05-9b36-83a55c44455d.png">
<img width="700" alt="Screen Shot 2022-05-31 at 12 36 55 PM" src="https://user-images.githubusercontent.com/2148168/171270688-39e9596e-8077-47bd-87fe-d22fc7c83a95.png">

**Comment by digitalgopnik** [comment]
:+1:

**Comment by Slapbox** [comment]
It appears there was a PR for this in #2304? Does anyone know why it wasn't committed?

**Comment by etrepum** [comment]
Should be fixed by https://github.com/facebook/lexical/pull/5758
