### ISSUE TITLE
Bug: Root node is undefined

### ISSUE THREAD

**Issue by fameoflight** [facebook/lexical#2312]
```typescript
import { $createParagraphNode, RootNode } from "lexical";

export function prepopulatedEmptyRichText() {

  console.log('root', RootNode);

  // const root = new RootNode();
  // root.append($createParagraphNode());

  // console.log(root);

}

export default {}
```

## The current behavior
console log is `root undefined`
## The expected behavior
expected this to be rootnode type

**Comment by trueadm** [comment]
You need to have an editor to create nodes, and you need to do it in `editor.update`. There is no other way, as doing `new SomeNode` will fail unless you're in an `update`.

**Comment by fameoflight** [comment]
Thanks

**Comment by fameoflight** [comment]
Hopefully you can see my point here, all of this just to ensure to show placeholder when state is empty (also not have copy paste fail)

**Comment by fameoflight** [comment]
It doesn't. I pass null to editor and then past html and it fails with error I described here 

https://github.com/facebook/lexical/issues/2308

**Comment by fameoflight** [comment]
interesting I guess I will pass undefined if it's null. Thank you so much you are best :)
