### ISSUE TITLE
Question: Does it really work without react?

### ISSUE THREAD

**Issue by digitalgopnik** [facebook/lexical#2313]
Hello there,

thanks for this nice editor-library. I came across some issues during implementing lexical with plain vanilla js app. The code can be found here: https://codesandbox.io/s/lexical-vanilla-js-i05utt

As you can see, the editor does not take the pressed key as an input.
If you add: 
```

editor.update(() => {
  const root = $getRoot();
  const paraNode = $createParagraphNode();
  const textNode = $createTextNode('Hello World');
  paraNode.append(textNode);
  root.append(paraNode);

```
there will be text inside the editor, but its neither possible to use the backspace (no chars will be deleted) nor to use enter (to add a new paragraph).

Did i something wrong? Or is there a bug with using lexical in a vanilla js-environment?

Best regards

**Comment by trueadm** [comment]
You'll need to wire up the various commands that occur from input (Lexical dispatches them) to APIs in selection. See https://github.com/facebook/lexical/blob/main/packages/lexical-rich-text/src/index.ts#L418-L784

**Comment by digitalgopnik** [comment]
@trueadm Thanks for your ultra quick response :) 

Could be maybe helpful for lexical newcomers who come across the same issue to have an example with vanilla js. If you don't mind i would extend my sandbox and create a pull request which a link inside the readme to have an example in plain javascript?

**Comment by trueadm** [comment]
Sure, if you'd like to contribute to the docs then that would be awesome :)

**Comment by digitalgopnik** [comment]
@trueadm Thanks for the clarification :+1:! :)

**Comment by lyove** [comment]
> registerRichText(editor, initialEditorState);

This is simple example https://github.com/lyove/lexical-vanilla
