### ISSUE TITLE
Bug: RichTextPlugin#initialEditorState breaks AutoFocusPlugin

### ISSUE THREAD

**Issue by hanford** [facebook/lexical#2328]
When using both `RichTextPlugin` combined with the `initialEditorState` prop, AutoFocusPlugin stops working

Lexical version: 0.3.0

## Steps To Reproduce

1. Have a `RichTextPlugin#initialEditorState` function and see AutoFocusPlugin stop auto focusing.

Link to code example: 

In the below sandbox you can toggle / untoggle the prop and notice when clicking "refresh" in the web view, autofocus will either work or not

https://codesandbox.io/s/many-lexical-autofocus-forked-q74c9w?file=/src/Editor.js:2847-2960

## The current behavior
The presence of initialEditorState, prevents `AutoFocusPlugin` from properly auto focusing

## The expected behavior
Autofocus should work regardless of whether or not `initialEditorState` is used

refs #2280 #2282

**Comment by hanford** [comment]
@trueadm Sandbox is updated!

**Comment by trueadm** [comment]
The reason it doesn't work, is because there is nothing to select. You've provided a custom function to generate the initial state, but it doesn't generate anything, leaving you with an empty editor state. You can't focus or select an empty editor – obviously, as there's nothing to select. You must have at least a block element like a `ParagraphNode` or something as content (it doesn't need any children).

**Comment by hanford** [comment]
@trueadm in my private repo, my function looks like this:

```
// Replace newlines & break tags that are added from OnChangeMarkdown
let str = (value || '').replace(/\n\n<br>\n/g, '\n');

// If we still have br tags, we're coming from Slate, apply
// Slate list collapse and remove remaining br tags
// https://github.com/facebook/lexical/issues/2208
if (str.match(/<br>/g)) {
  str = str.replace(/^(\n)(?=\s*[-+\d.])/gm, '').replace(/<br>/g, '');
}

str = str
  // Unescape HTML characters
  .replace(/&quot;/g, '"')
  .replace(/&amp;/g, '&')
  .replace(/&#39;/g, "'")
  .replace(/&lt;/g, '<')
  .replace(/&gt;/g, '>');

$convertFromMarkdownString(str, transformers || TRANSFORMERS);
```

And the bug still occurs

**Comment by hanford** [comment]
Modifying the above function with the below snippet worked!

```
if (!str) {
  return $createParagraphNode();
}
```
