### ISSUE TITLE
Feature: Markdown shortcut

### ISSUE THREAD

**Issue by ghost** [facebook/lexical#2330]
Thank you for developing a great project. There is a request.
When entering markdown, for example <code>,

1. `
2. a
3. a
4. `

If you enter in the order of, it will be <code>,

1. `
2. `
3. Move the cursor back one
4. a
5. a

If you enter in the order of, it will not be <code>.

I have a habit of inputting the latter, and I am very happy that the latter is also recognized.

**Comment by thegreatercurve** [comment]
@ghost Any chance you could take a look at Maksim's comment above and maybe update the bug description? It's proving a little difficult to debug currently.

**Comment by thegreatercurve** [comment]
Closing this as its difficult to repro.
