### ISSUE TITLE
Bug: `libdefs/` and `utility-types` missing in generated .d.ts files.

### ISSUE THREAD

**Issue by aearly** [facebook/lexical#2339]
Lexical version: 0.3.1

## Steps To Reproduce

1. Import `lexical` in a TS environment (e.g. VS Code).
2. View type definition for `lexical` library (`Lexical.d.ts`)
3. See missing types.

![Screenshot from 2022-06-03 15-09-53](https://user-images.githubusercontent.com/558190/171965827-f52d91d5-b54b-493a-9e5f-8911f15b6d0b.png)

I ran into this playing with the new `SerializedLexicalNode` types.  A missing `Spread` type in the definition led to the compiler complaining about missing `text` or `children` properties on `SerializedTextNode` and `SerializedElementNode`.

**Comment by kof** [comment]
Seems like I have the same issue, even though I am on 0.3.5 and I can see utility-types is in dev dependencies. Shouldn't it also be in peer dependencies?

**Comment by kof** [comment]
I also have this one, so I am not sure whats going on:

```
node_modules/lexical/LexicalUtils.d.ts:14:28 - error TS2307: Cannot find module 'shared/types' or its corresponding type declarations.

14 import type { Klass } from 'shared/types';
                              ~~~~~~~~~~~~~~
                              ```

**Comment by kof** [comment]
How is a private package "shared" supposed to be used when lexical is installed as a dependency?
