### ISSUE TITLE
Question: $getSelection re-render?

### ISSUE THREAD

**Issue by itschip** [facebook/lexical#2340]
Hi, I came across something when writing a small Image plugin. Each time I try to add a image node, it seems as it re-renders and adds two images, instead of one.

Let me explain with code :)

I have this simple function to find a very specific string, and then create a imageNode, which is a div > img
```tsx
function findAndTransformImage(node: TextNode): null | DecoratorNode<JSX.Element> {
  const text = node.getTextContent();

  if (text === 'https://i.imgur.com/Dw6jrsz.png') {
    const selection = $getPreviousSelection();
    console.log("selection", selection)
    if ($isRangeSelection(selection)) {
      const imageNode = $createImageNode(text);
      selection.insertNodes([imageNode]);

      return imageNode;
    }
    return null;
  }
}
```
Now, the outcome of this (if copy-paste the link I am checking for) is two images, instead of one.
![brave_iW6FMfqDrq](https://user-images.githubusercontent.com/59088889/172018070-1f1829c4-0b3c-4ba1-83e5-b24f38c86ff3.png)

Is this a place where one would use a listener instead? Or is it obvious what I might be missing?

**Comment by trueadm** [comment]
You might want to also check what type of node you're dealing with here. i.e. you're missing a `!$isImageNode(node)`. Decorators also have text content, so you might be just repeating your existing node.

**Comment by itschip** [comment]
> You might want to also check what type of node you're dealing with here. i.e. you're missing a `!$isImageNode(node)`. Decorators also have text content, so you might be just repeating your existing node.

Not sure if this the best practice, but doing the following works.

```tsx
function findAndTransformImage(node: DecoratorNode): null | DecoratorNode<JSX.Element> {
  const text = node.getTextContent()

  if (text === 'https://i.imgur.com/ygLc7K0.png') {
    const selection = $getPreviousSelection();
    console.log('selection', selection);
    if ($isRangeSelection(selection)) {
      const imageNode = $createImageNode(text);
      
      node.replace(imageNode)
      return imageNode;
    }
    return null;
  }
}
```

**Comment by trueadm** [comment]
Yeah, that will work, as you're replacing the existing node. You should still check if it's already the node you want though. Otherwise you might be replacing the right node that has already been made, with another copy!

**Comment by itschip** [comment]
Will do, thanks! 👍🏻
