### ISSUE TITLE
Bug: `CTRL+X`, `CTRL+C` don't work for `PlainTextPlugin`

### ISSUE THREAD

**Issue by yeahga** [facebook/lexical#2341]
Lexical version: 0.3.1
Chrome version: 102.0.5005.63
Firefox version: 101.0

## Steps To Reproduce

1. Enter text into the editor
2. Select any text and press `CTRL+X`

Link to example:
https://codesandbox.io/s/g932e

## The current behavior
Selected text cut but not copied to clipboard

## The expected behavior
Selected text cut and copied to clipboard

**Comment by yeahga** [comment]
CTRL+C doesn't copy text either

**Comment by trueadm** [comment]
Thanks for flagging this, this was a recent regression.

**Comment by yeahga** [comment]
@trueadm, thank you for your great work!
