### ISSUE TITLE
Bug: Mentions Typeahead Positioning (iOS Safari)

### ISSUE THREAD

**Issue by dylanhusted** [facebook/lexical#2354]
Currently live on [the playground](https://playground.lexical.dev/). If you open the mentions typeahead from iOS safari, you'll see it render over your text, rather than below it. This doesn't appear to be happening on Android, so it may be safari-specific.

![IMG_67580A5118D0-1](https://user-images.githubusercontent.com/7398726/172224061-ef99ca57-e94b-4373-aa5a-cff0cee72599.jpg)

Lexical version: 0.3.2

## Steps To Reproduce

1. Open the playground from iOS safari
2. Type '@' followed by search text
3. See mentions results overflow over your text

Link to code example: 

playground code will do!

## The current behavior
Mentions typeahead covers your search text
## The expected behavior
Mentions typeahead positions itself below your search text

**Comment by thegreatercurve** [comment]
I've tried a few different ways to try to replicate this and break iOS Safari, but without much luck. I think this may have inadvertently been fixed since been reported.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/7748470/180659514-e3307181-e354-4b9f-ab81-e4f7e949e19f.png">

**Comment by dylanhusted** [comment]
> I've tried a few different ways to try to replicate this and break iOS Safari, but without much luck. I think this may have inadvertently been fixed since been reported.
> 
> <img alt="image" width="452" src="https://user-images.githubusercontent.com/7748470/180659514-e3307181-e354-4b9f-ab81-e4f7e949e19f.png">

Yes looks like you're right. Thanks @thegreatercurve !
