### ISSUE TITLE
Bug: Pasting emoji at the end clears editor (MaxLength)

### ISSUE THREAD

**Issue by im-adithya** [facebook/lexical#2357]
https://github.com/facebook/lexical/pull/2296#issuecomment-1141938595

https://user-images.githubusercontent.com/64399555/171148508-4f4dc82d-baeb-4b42-a75a-1bbc2bb20b73.mp4

Lexical version: Latest

## Steps To Reproduce

1. Type any random 30 characters
2. Copy this emoji 💏 or any other emoji of length 2 (occupying a length of 2, otherwise this emoji is actually of length 11 as shown by `'💏'.length` which also can be an error if lexical is supposed to treat this as an 11-length emoji, but `a....a💏` (28 `a`s) works fine in MaxLength)
3. Remove a character and paste the emoji at the end (and ONLY at the end, otherwise the behavior is proper)

## The current behavior
The entire editor gets cleared and the Block Format dropdown disappears! (I've found out that it is because the `blockType` of editor gets changed to root after being cleared)

## The expected behavior
It shouldn't allow the emoji

## Note
I would like to work on this after getting to know a bit more about emoji guidelines as that would help in a better understanding of the functionality!

**Comment by trueadm** [comment]
Fixed in https://github.com/facebook/lexical/pull/2428.
