### ISSUE TITLE
Feature: Customise decorator nodes block type behaviour

### ISSUE THREAD

**Issue by thegreatercurve** [facebook/lexical#2369]
At the moment, certain decorator nodes, such as `YouTubeNode` and `TweetNode`, are block-style top-level nodes, which are only insertable and editable at the level just below the root. `TextNodes`, or any other type of node, are not allowed to flow around these nodes.

However, other decorator nodes though, such as `ImageNode`, are inlined in `ParagraphNodes` and the text is allowed to flow around the decorator.

We should allow users to be able to select how a decorator node behaves. On hover of a decorator node a small menu will appear which defines a few options: 
 - `break text`: forces the current decorator node to split any text node and become a top-level node, wrapped in `DecoratorBlockNode`
 - `inline`: adds the any top-level decorator node to the previous sibling nodes end-most leaf node so that it flows with the text.

**Comment by thegreatercurve** [comment]
Closing this as I think this is a nice bit of UX, but since we opened it, we've taken more of an opinion that the playground should be kept fairly simply when possible to allow users to grep the code easier.

**Comment by brendon** [comment]
Beyond the playground. Are inline images a possibility with the Lexical editor core (with an extension I presume)? Or is it something that fundamentally won't work? :)

**Comment by etrepum** [comment]
Sure, but that code isn’t written for you.

**Comment by brendon** [comment]
All good. Just wanted to check that is wasn't some prohibited by the document modelling.
