### ISSUE TITLE
Feature: Documentation around @lexical/code

### ISSUE THREAD

**Issue by rememberlenny** [facebook/lexical#2380]
Would it be possible to have more documentation around @lexical/code? I'm very interested to understand how this is designed to be used, and I'm inferring usage based on the code at the moment.

**Comment by fantactuka** [comment]
Hi @rememberlenny,

As of now that package exports `registerCodeHighlighting` that can be used to mount its features to the editor. If you're using react, then [here's an example](https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/CodeHighlightPlugin.ts#L1) from our playground on how to call it from plugin. There's some ongoing work to split `registerCodeHighlighting` into code highlighting and code typing enhancements (#2382), after that we'll update docs to reflect new structure

**Comment by acywatson** [comment]
Covered here: https://github.com/facebook/lexical/issues/2845
