### ISSUE TITLE
Bug: Incorrect imports in documentations

### ISSUE THREAD

**Issue by mariusrak** [facebook/lexical#2389]
A lot of examples in readme or in docs are written with incorrect variables. For example:

```js
import { TRANSFORMERS } from '@lexical/markdown';
import {MarkdownShortcutPlugin} from '@lexical/react/LexicalMarkdownShortcutPlugin';

<LexicalComposer>
  <LexicalMarkdownShortcutPlugin transformers={TRANSFORMERS} />
</LexicalComposer>
```

Imported is `MarkdownShortcutPlugin` but referenced is `LexicalMarkdownShortcutPlugin`.
So, many examples incorrectly prepends `Lexical` in front of variables.

It's confusing and, of course, the copied code is not working then.

**Comment by trueadm** [comment]
Sorry about that. If you get a chance and want to help, please do put up a PR and help us fix the bad references :)
