### ISSUE TITLE
Bug: blocktype highlight seems to be improper

### ISSUE THREAD

**Issue by im-adithya** [facebook/lexical#2401]
How do we wish to highlight the selected blockType?

We currently seem to use a span of class active when selected, but this causes the UI to look improper on hovering over other block types as shown below

```
{blockType === 'paragraph' && <span className="active" />}
```

(Observe the background-color size)
<p>
<img src="https://user-images.githubusercontent.com/64399555/173417562-ba6e7940-ad11-4933-88d1-591ea6d59225.png"/>
<img src="https://user-images.githubusercontent.com/64399555/173417565-1678fcd0-62b2-4325-9e0b-021c88b194e5.png"/>
</p>

Lexical version: Latest

## The expected behavior

Please let me know the expected behavior, did we miss adding a tick icon in the active span element or is this the desired behavior itself?

## Note
I would like to work on this!

**Comment by fantactuka** [comment]
It could be like bold/italic/underline buttons ([blue-ish background](https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/index.css#L448))
