### ISSUE TITLE
Bug: Strange backspace behavior on Android Chrome across rich text formatting boundaries

### ISSUE THREAD

**Issue by aearly** [facebook/lexical#2403]
Lexical version: 0.3.3

## Steps To Reproduce

1. Visit https://playground.lexical.com
2. Clear text
3. Type "Hello"
4. Enable bold
5. Type "world". Text reads "Hello **world**"
7. Hit backspace 5 times. Text reads "Hello "
9. Hit backspace one more time.  Text reads "Hello**Hello**"
11. Hit backspace 5 times.  Text reads "Hello"
12. Hit backspace.  Text reads "Hell**Hell**"

**Comment by trueadm** [comment]
I fixed this but it must have regressed. I'll take another look into it tomorrow.
