### ISSUE TITLE
[Discussion] Rename CharacterStylesPopupPlugin to FloatingToolbar?

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#2446]
It always takes me 30 ages to find this plugin, I wonder if we should rename it

**Comment by harish-sethuraman** [comment]
may be `FloatingFormatter`?

**Comment by thegreatercurve** [comment]
We have other floating toolbars some maybe something more specific like `TextFormatFloatingToolbar`?

**Comment by harish-sethuraman** [comment]
TextFormatFloatingToolbar -> `FloatingTextFormatToolbar` may be? It would be easy to grasp if floating was at the start?

**Comment by thegreatercurve** [comment]
Closed by #2456
