### ISSUE TITLE
initialEditorState not working on LexicalComposer

### ISSUE THREAD

**Issue by barbalex** [facebook/lexical#2461]
Lexical version: 0.3.5, react.

With recent updates from 0.3.3 to 0.3.5 I now get this warning in the console:
```
initialEditorState on RichTextPlugin is deprecated and will be removed soon. Use LexicalComposer initialEditorState instead
```
So I went to github and the documentation website, searching for information on initialEditorState.
But found nothing.

So I thought: Well, let's just try doing what the warning says.

I moved 
```
initialEditorState={value ? JSON.stringify(value) : undefined}
```
from `RichTextPlugin` to `LexicalComposer`.

Now the warning disappears, as expected. But initial state is not set. Which is unexpected.

The value I am passing in was created with `state.current?.toJSON()` from state updated with the `newState` returned by the onChange of the `OnChangePlugin`. This works fine in the `RichTextPlugin`.

Please help me find the documentation, so I can try to solve this. Or could it be a bug?

The only thing I found was the [pull-request](https://github.com/facebook/lexical/pull/2425). From what I can tell in the code, simply moving the initialEditorState declaration should work.

**Comment by thegreatercurve** [comment]
CC @zurfyx

**Comment by n2o** [comment]
I am experiencing the same bug, which is why I keep the `initialEditorState` at the `RichTextEditor`, and now we have to live with the deprecation warning. I am quite confident, that this is a bug. We are experiencing this in a ClojureScript project:

```clojure
;; Works, but keeps deprecation warning
[:> LexicalComposer {:initialConfig initial-config}
 [:> RichTextPlugin {:initialEditorState (initialize-editor-state)}]]

;; Warning disappears, but there is no initial state
[:> LexicalComposer {:initialConfig initial-config
                     :initialEditorState (initialize-editor-state)}
 [:> RichTextPlugin ,,,]]
```

**Comment by Decamark** [comment]
Maybe they've moved that option into initialConfig?

https://github.com/facebook/lexical/blob/60e06fd11608c2935d1e57063a646befbd7a8405/packages/lexical-react/src/LexicalComposer.tsx#L51-L59

This worked for me.

```js
const initialConfig = {
  theme,
  editorState,
};

<LexicalComposer initialConfig={initialConfig}>
...
</LexicalComposer>
```
