### ISSUE TITLE
Bug: Link not copied if only the link selected

### ISSUE THREAD

**Issue by nextend** [facebook/lexical#2464]
Lexical version:

## Steps To Reproduce

1. Open https://codesandbox.io/s/lexical-rich-text-example-5tncvy
2. Type Hello World
3. Select: ell
4. Add a link to the selection
5. Select: ell
6. Ctrl+C -> copy
7. Move the caret somewhere else then ctrl+V -> paste

## The current behavior
The pasted "ell" does not have the link on it.

## The expected behavior
"ell" should be a link

https://youtu.be/zx9JiVKk4gw

**Comment by fantactuka** [comment]
Fixed in #2474
