### ISSUE TITLE
Feature: Emoji picker

### ISSUE THREAD

**Issue by always-maap** [facebook/lexical#2468]
I think it would be nice to add an emoji picker to the playground since it's a common thing like what Facebook or Twitter uses.

![2022-06-18-010652_1920x1080_scrot](https://user-images.githubusercontent.com/58308349/174397981-85b1d7d5-b480-4612-91fd-82ed11ac9420.png)

We either can use emoji components like [emoji mart](https://github.com/missive/emoji-mart) or use a native emoji list like what we did in Zoomit. The advantage of using a list like this is we can support inline-emoji like what GitHub or telegram offers(:emojiTag)

![2022-06-18-010933_1920x1080_scrot](https://user-images.githubusercontent.com/58308349/174398262-ed3784ea-eda8-4817-a6b9-1f9b2e5f1f03.png)

![2022-06-18-011142_1920x1080_scrot](https://user-images.githubusercontent.com/58308349/174398473-b700623a-e402-4909-b554-99f547c6313e.png)

That shouldn't be a hard plugin to implement with a little help. I would like to work on it if you are agreeing

**Comment by thegreatercurve** [comment]
Hey @always-maap! Thanks for the idea and te really comprehensive issue report.

I wouldn't have any issues with this being implemented. My only concern would be how this fits with some of the existing functionality we have in the playground for the `EmojiNode` and `EmojiPlugin`. 

This plugin transforms text which represents an emoji into an actual emoji node (i.e.`:)` becomes 🙂). We'd definitely want to keep this logic as it's a useful illustration of how node transforms work. 

I guess you could probably still implement the drop down though, which activates any time something like a `:` is typed, or have "Emoji" under the "Insert" menu in the toolbar, which opens up a modal with one of the third party picker components you mentioned.

**Comment by thegreatercurve** [comment]
I'm going to close this for the moment. I think there are potential features here, but I'm not sure about how much value they would necessarily add to the playground compared to some of the existing emoji logic.

**Comment by sakhmedbayev** [comment]
thumb-up for this enhancement 👍

**Comment by Moumene** [comment]
thumb-up for this enhancement 👍

I used `emoji-mart` for this purpose, I m facing an issue whenever I try to add an emoji it's always inserted at the end of the text with this code 
``` typescript
const addEmoji = React.useCallback(
   (emoji: string) => {
     editor.update(() => {
       $insertNodes([$createTextNode(emoji)]);
     });
   },
  [editor],
 );
```

```jsx
<Picker data={data} onEmojiSelect={addEmoji} onClickOutside={onClose} theme="light" />
```
Couldn't make it to insert the emoji in the last position of the caret.

**Comment by wadood42** [comment]
Create a plugin and get the selection and then add the emoji at the selection.
`
const ADD_EMOJI_COMMAND: LexicalCommand<any> = createCommand();
export default function EmojiPlugin() {
	const [editor] = useLexicalComposerContext();

	React.useEffect(() => {
		return editor.registerCommand(
			ADD_EMOJI_COMMAND,
			(payload) => {
				const selection = $getSelection();
				if ($isRangeSelection(selection)) {
					selection.insertNodes([$createTextNode(payload)]);
				}
				return true;
			},
			1
		);
	}, [editor]);
	return (
		<Picker
			data={data}
			theme='light'
			onEmojiSelect={(d) => {
				editor.dispatchCommand(ADD_EMOJI_COMMAND, d.native);
			}}
		/>
	);
}
`

**Comment by miquelcdp** [comment]
Hi!

Here it is a working solution, I hope this helps someone:

`import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext';
import {
  $createTextNode,
  $insertNodes,
  TextNode,
  TextPointCaret,
  $getSelection,
  $getPreviousSelection,
  PointCaret,
  $isRangeSelection,
  $caretFromPoint,
  $getSiblingCaret,
  $getChildCaret,
  $getRoot,
  $createParagraphNode,
  $getCollapsedCaretRange,
  $setSelectionFromCaretRange,
} from 'lexical';

function $insertTextToCurrentOrLastCaret(text: string) {
  const selection = $getSelection() || $getPreviousSelection();
  let initialCaret: undefined | PointCaret<'next'>;
  if ($isRangeSelection(selection)) {
    initialCaret = $caretFromPoint(selection.focus, 'next');
  } else {
    if (selection != null) {
      const nodes = selection.getNodes();
      const lastNode = nodes[nodes.length - 1];
      if (lastNode) {
        initialCaret = $getSiblingCaret(lastNode, 'next');
      }
    }
    initialCaret =
      initialCaret ||
      $getChildCaret($getRoot(), 'previous')
        .getFlipped()
        .insert($createParagraphNode());
  }

  const caretNode = initialCaret.origin;
  const caretNodeType = caretNode.getType();
  $setSelectionFromCaretRange($getCollapsedCaretRange(initialCaret));

  if (caretNodeType === 'text') {
    const caretNodeAsTextNode = caretNode as TextNode;
    const initialCaretAsTextCaret = initialCaret as TextPointCaret<
      TextNode,
      'next'
    >;

    const offset = initialCaretAsTextCaret.offset;

    if (typeof offset === 'number') {
      caretNodeAsTextNode.spliceText(offset, 0, text, true);
    }
  } else {
    const newTextNode = $createTextNode('');
    $insertNodes([newTextNode]);
    newTextNode.spliceText(0, 0, text, true);
  }
}

export const EmojisPlugin = () => {
  const [editor] = useLexicalComposerContext();

  const handleEmojiSelect = (emoji: string) => {
    editor.update(() => {
      $insertTextToCurrentOrLastCaret(emoji);
    });
  };

  return (
    <EmojiPicker onEmojiSelect={handleEmojiSelect} icon="face" hideOnSelect />
  );
};
`

**Comment by miquelcdp** [comment]
Here it is a working example, you are welcome :)

```

import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext';
import {
  $createTextNode,
  $insertNodes,
  TextNode,
  TextPointCaret,
  $getSelection,
  $getPreviousSelection,
  PointCaret,
  $isRangeSelection,
  $caretFromPoint,
  $getSiblingCaret,
  $getChildCaret,
  $getRoot,
  $createParagraphNode,
  $getCollapsedCaretRange,
  $setSelectionFromCaretRange,
} from 'lexical';

function $insertTextToCurrentOrLastCaret(text: string) {
  const selection = $getSelection() || $getPreviousSelection();
  let initialCaret: undefined | PointCaret<'next'>;
  if ($isRangeSelection(selection)) {
    initialCaret = $caretFromPoint(selection.focus, 'next');
  } else {
    if (selection != null) {
      const nodes = selection.getNodes();
      const lastNode = nodes[nodes.length - 1];
      if (lastNode) {
        initialCaret = $getSiblingCaret(lastNode, 'next');
      }
    }
    initialCaret =
      initialCaret ||
      $getChildCaret($getRoot(), 'previous')
        .getFlipped()
        .insert($createParagraphNode());
  }

  const initialCaretNode = initialCaret?.origin;

  if (!initialCaretNode) {
    return;
  }

  const initialCaretNodeType = initialCaretNode.getType();
  $setSelectionFromCaretRange($getCollapsedCaretRange(initialCaret));

  if (initialCaretNodeType === 'text') {
    const initialCaretNodeAsTextNode = initialCaretNode as TextNode;
    const initialCaretAsTextCaret = initialCaret as TextPointCaret<
      TextNode,
      'next'
    >;

    const offset = initialCaretAsTextCaret.offset;

    if (typeof offset === 'number') {
      initialCaretNodeAsTextNode.spliceText(offset, 0, text, true);
    }
  } else {
    const newTextNode = $createTextNode('');
    $insertNodes([newTextNode]);
    newTextNode.spliceText(0, 0, text, true);
  }
}

export const EmojisPlugin = () => {
  const [editor] = useLexicalComposerContext();

  const handleEmojiSelect = (emoji: string) => {
    editor.update(() => {
      $insertTextToCurrentOrLastCaret(emoji);
    });
  };

  return (
    <EmojiPicker onEmojiSelect={handleEmojiSelect} icon="face" hideOnSelect />
  );
};

```
