### ISSUE TITLE
Bug: Cursor position is incorrect  in Safari

### ISSUE THREAD

**Issue by poycc** [facebook/lexical#2471]
Lexical version:

## Steps To Reproduce

1. Open [Lexcical Playground](https://playground.lexical.dev/) in Safari
2. insert a gif

## The current behavior

![Jun-19-2022 13-53-28](https://user-images.githubusercontent.com/24654957/174467892-4f783408-6402-468d-9db7-66c327e97589.gif)

**cursor in front of the picture**

## The expected behavior

![Jun-19-2022 14-01-39](https://user-images.githubusercontent.com/24654957/174468005-fbd9909f-72b9-471c-9b2b-d25abfc750ac.gif)

**cursor behind the picture**

**Comment by thegreatercurve** [comment]
This should now be fixed with our recent work on adding in forcing cursor state.
