### ISSUE TITLE
Bug: move some packages into peerDependencies

### ISSUE THREAD

**Issue by LvChengbin** [facebook/lexical#2473]
Lexical version: 0.3.5

## Steps To Reproduce

1. Using yarn berry as package manager under PNP mode.

Link to code example:

Just run the demo of "Powerful Features" on official home page of lexical.dev.

https://codesandbox.io/s/serene-wiles-1w0s5h?file=/src/Editor.js

## The current behavior

![image](https://user-images.githubusercontent.com/963223/174489670-33f60cf9-978e-4c6e-9de9-8408fd3691aa.png)

## The expected behavior

yarn berry uses different virtual packages while trying to import from different packages, it makes the two `HeadingNode`s are not same.

**Comment by thegreatercurve** [comment]
Correct me if I'm wrong, but this seems like more of an issue with that particular CodeSandbox and running it with Yarn Berry, instead of NPM which we use at the moment. I'm unable to reproduce the error with our current Package Manager.
