### ISSUE TITLE
Bug: HistoryPlugin incorrectly undo to the word I typed during IME mode

### ISSUE THREAD

**Issue by Fonger** [facebook/lexical#2479]
Lexical version: currently latest 5802651c24d88b2f7d27253749f55cb8ffa3b12b

## Steps To Reproduce

1. type in IME mode in chinese `ㄓㄨˋㄧㄣ ㄈㄨˋㄩㄢˊ` and press `Enter` to leave IME mode to get `注音復原` (just an arbitary example, the word itself is not related to this bug)
2. press command+z to undo. press again and again...

Link to code example:

https://user-images.githubusercontent.com/5862369/174654885-538282f7-e414-4109-bd02-fcf7eeb63bcb.mov

## The current behavior
When I hit undo, it becomes `注音復ㄩㄢ`. press again `注音復ㄩ` again `注音復` again `注音ㄈ` again `注音` again `注ㄧㄣ`...

## The expected behavior
When I hit undo, it should completely remove `注音復原` instead of going back to the one I type in IME mode.

**Comment by trueadm** [comment]
The fix is to ensure the History plugin merges changes during when `editor.isComposing()` is true.
