### ISSUE TITLE
Multiple editors and accessing editors by id through context provider

### ISSUE THREAD

**Issue by adri1wald** [facebook/lexical#2480]
We are building a webapp with multiple editors that can be updated through interactions with other parts of the UI. For example, we have a PDF viewer from which you can add the selection to the last active editor.

We are currently using slate, but testing out Lexical on recommendation of an expert. With slate we have a context provider which stores in state a map from `editorId` to `Editor`.  We can then dynamically add and remove editors by id, as well as get an editor by id from any child of that provider.

I'm wondering how to do this with Lexical? It seems that creation and initialization is now an implementation detail of `<LexicalComposer />`, so I'm wondering how to "get the editor out" of that subtree. Best I've though of so far (untested):

```
import { useEffect } from 'react'
import { LexicalComposer } from '@lexical/react/LexicalComposer'

function Editor(props) {
  // hook to access editor context
  const editors = useEditors()
  useEffect(() => () => editors.deleteEditor(props.editorId), [])
  return (
    <LexicalComposer
      initialConfig={{
        namespace: props.editorId,
        editorState(editor) {
          editors.createEditor(props.editorId, editor)
        },
        ...
      }}
    >
      ...
    </LexicalComposer>
  )
}
```

**Comment by thegreatercurve** [comment]
Closing as we chatted about this in the Discord. The agreed upon answer was to pass editor instances up to a parent context using a custom plugin via `useEffect`.
