### ISSUE TITLE
Bug: Playground open links on click

### ISSUE THREAD

**Issue by nextend** [facebook/lexical#2483]
## Steps To Reproduce

1. Open https://playground.lexical.dev/
2. Click on Lexical website link in the bulleted list

## The current behavior
Opens the link on new tab

## The expected behavior
Place the caret at that position.

**Comment by hanford** [comment]
This is not a bug, it's functionality that's added via this plugin: https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/ClickableLinkPlugin.ts
