### ISSUE TITLE
Prefix functions within a command callback with $ 

### ISSUE THREAD

**Issue by thegreatercurve** [facebook/lexical#2485]
Under certain conditions, we trigger the command listeners [within an `editor.update` block](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalUpdates.ts#L640-L642), so we should probably think about renaming any of the callbacks in the default command listener callbacks to add a `$` prefix. 

This would make the implementation consistent with some of our [own guidance and docs on the $ prefix](https://lexical.dev/docs/faq#why-does-lexical-use-the--prefix-in-the-name-of-many-of-the-functions).

**Comment by PAkerstrand** [comment]
https://discord.com/channels/953974421008293909/988746933248073769

**Comment by thegreatercurve** [comment]
Closing this as I no longer think this is possible without introducing several breaking changes. I think the editor.update that exists in the command listeners is possibly more of an implementation detail than anything else.
