### ISSUE TITLE
Feature: Text Node format and detail setters should accept a string

### ISSUE THREAD

**Issue by thegreatercurve** [facebook/lexical#2491]
`setFormat` and `setDetail` both accept numbers for format and detail type, but `toggleFormat` accepts a `TextFormatType` corresponding to the format type. 

We can still store the formats as numbers for the sake of saving space during serialization, but these should all accept a `TextFormatType` for developer experience.

**Comment by im-adithya** [comment]
Would like to work on this!
I've never come across `setDetail` yet, what is it used for?

**Comment by im-adithya** [comment]
After looking through the code, I think it's more like `setFormat` is something internal for TextNode unlike ElementNode as TextNode format can have multiple things (bold, italic, underline etc.) at once and is using binary flags to know if more than one is being applied... (while the ElementNode uses format for alignment purpose)

Isn't it that only `toggleFormat` is to be used by developers, as marking flags as per 7 different formats [0010110 for ex] and then applying it in decimal a bit complex and is already being done by us under the hood?
