### ISSUE TITLE
Bug: Deleting first comment in a thread makes the next reply the new thread starter

### ISSUE THREAD

**Issue by adamkona** [facebook/lexical#2494]
Lexical version:

Playground

## Steps To Reproduce
1. create a new quote comment referencing some element in the editor
2.  reply to that comment
3.  delete the top level quote comment

The quote comment is removed from the thread, but the first reply is then made the quote comment.

This could be problematic because a reply should reference a specific comment. If that comment is then made the quote comment, it appears as if this person started this thread which is inaccurate.

Link to code example:

## Example

This is an example of creating a comment which quotes an area of the document and then two replies to that comment. 
<img width="995" alt="example of quoted area with two replies" src="https://user-images.githubusercontent.com/20659452/175034927-59e36c1e-d5f3-490b-9bcb-7b1f73fc3eb2.png">

This is the result of deleting the comment which started the thread.
<img width="1000" alt="result after deleting thread starter" src="https://user-images.githubusercontent.com/20659452/175034973-80f5b5d7-14af-42d8-9efa-8cf22e63e707.png">

## The current behavior
- Replies to a thread are made the quote comment when the original quote comment is deleted.
- The highlight in the document which shows where the thread started is also removed, but it is still shown in the comment thread.

## The expected behavior
I think that better behaviour would be to remove the content of a comment and replace it with "deleted comment" and maintain the current tree structure.

**Comment by im-adithya** [comment]
I guess they avoided this to not make the comments box lengthy.

One solution can be to modify delete for the comment as suggested above (showing "[deleted comment]" in grayer text) with an additional option to delete a thread as a whole (to avoid the length issue).

Let's wait for the core team to check on this.

(Would like to work on this btw!)

**Comment by thegreatercurve** [comment]
@im-adithya I'd be happy for you to work on this. 

I think this was just a basic oversight when we were making the comments plugin. Ideally, if you delete the top comment in a thread, we could either mark it as _Deleted_, as you suggest, or we could just delete the whole thread altogether. Either seems like reasonable UX.

The length issue isn't a major concern as this is intended to be a basic demo, but I'll leave it up to you. 

This is the code you'd need to update: https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/commenting/index.ts#L165-L190
