### ISSUE TITLE
Feature: Export `createEmptyEditorState` and other LexicalEditorState functions

### ISSUE THREAD

**Issue by nc** [facebook/lexical#2500]
By default EditorState manipulation functions like `createEmptyEditorState` are not exported. It'd be great to have these also exported by default so it's easier to create and manage EditorState.

**Comment by trueadm** [comment]
We don’t want people manually constructing EditorStates as it won’t work properly outside an update cycle and it won’t work with the reconciler properly. So it’s unlikely we’ll ever expose this function as it’s an implementation detail.

**Comment by ProofOfKeags** [comment]
@trueadm how are we supposed to supply the `initialEditorState` argument to `LexicalComposer` if there is no way to construct an editor state...?
