### ISSUE TITLE
Bug: Pasting nested lists doesn't work

### ISSUE THREAD

**Issue by hanford** [facebook/lexical#2503]
One of the things I've seen in the wild (Lexical exceptions from our users) seems to occur when pasting a nested list(s). This can pretty easily repro'd following the below steps...  happy to provide more details/information if needed

Lexical version: 0.3.3

## Steps To Reproduce

1. Copy the `Preview` portion from the [commonmark dingus](https://spec.commonmark.org/dingus/?text=-%20foo%0A%20%20-%20bar%0A%20%20%20%20-%20baz%0A%20%20-%20foo%0A-%20bar)
2. Paste into [playground.lexical.dev](https://playground.lexical.dev/)

Notice that the first half the list nesting doesn't have the correct styles (more importantly, is very wonky to work with). Lexical will also then generate invalid Markdown for the nested list (as you can see in the 2nd video)

The initial jump was caused by be "de-indenting" (shift + tab), however most interactions can be very unexpected.

This video shows off some weird behavior, shortcuts not working as expected, styling is off, etc

https://user-images.githubusercontent.com/2148168/175352299-f49f9ee0-bd8d-4bcf-9df4-1929a92749eb.mov

This video shows off the markdown generation breaking

https://user-images.githubusercontent.com/2148168/175354635-4f71a213-4627-4b38-8b69-202a6aa2e00c.mov

## The current behavior
Lists are pasted in a shape that Lexical doesn't seem to properly handle

The paste payload is as follows:
```
<meta charset='utf-8'><ul data-sourcepos="1:1-5:5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li data-sourcepos="1:1-4:7" style="box-sizing: border-box;">foo<ul data-sourcepos="2:3-4:7" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;"><li data-sourcepos="2:3-3:9" style="box-sizing: border-box;">bar<ul data-sourcepos="3:5-3:9" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;"><li data-sourcepos="3:5-3:9" style="box-sizing: border-box;">baz</li></ul></li><li data-sourcepos="4:3-4:7" style="box-sizing: border-box;">foo</li></ul></li><li data-sourcepos="5:1-5:5" class="selected" style="box-sizing: border-box; background-color: rgb(238, 238, 238);">bar</li></ul>
```

## The expected behavior
`Lexical(/list | /clipboard | /markdown)` Should either normalize the list payload into what it expects, or should work with both structures.

Possibly related to: #2208

**Comment by hanford** [comment]
I created a `.patch` file with the changes from #2509 over [here](https://gist.github.com/hanford/767a154ec7cd822b07b310e7c13ea761) so I can begin using these changes now

**Comment by acywatson** [comment]
> I created a `.patch` file with the changes from #2509 over [here](https://gist.github.com/hanford/767a154ec7cd822b07b310e7c13ea761) so I can begin using these changes now

Now that the CI is fixed I'll look at getting this into the next release cycle. Thanks again for reporting!
