### ISSUE TITLE
Bug: Line numbers disappear when a large block of code is pasted

### ISSUE THREAD

**Issue by zignis** [facebook/lexical#2525]
Lexical version: 0.3.5

## Steps To Reproduce

1. Visit playground and create a new code block
2. Paste a large block of code (ex. from https://raw.githubusercontent.com/facebook/lexical/main/packages/lexical-playground/src/themes/PlaygroundEditorTheme.css)

## The current behavior

The line numbers disappear at the end of the block

## The expected behavior

The line number should be present over the entire node

![Screenshot (48)](https://user-images.githubusercontent.com/77036902/175940795-f9c06516-71e7-4975-b11a-0033f06d76df.png)

**Comment by digitalgopnik** [comment]
This is still in Lexical version: 0.5.0 (which is currently deployed on [playground](https://playground.lexical.dev)

![lexical_code_lines](https://user-images.githubusercontent.com/2630316/195594711-9311ba84-b3ed-406c-9632-81f849190bc5.gif)

The gutter-numbers have the same length as the children of the ```CodeNode```. But if the line is very long (without a linebreak), a single ```CodeHighlightNode``` can take 2 lines in view.

Any ideas how to fix this? :)

**Comment by trueadm** [comment]
We plan on rewriting the code node in the future. So closing this for now.
