### ISSUE TITLE
Bug: Deleting partial selection with link turns the following text into link

### ISSUE THREAD

**Issue by nextend** [facebook/lexical#2538]
Lexical version: 0.3.5

## Steps To Reproduce

1. Open https://playground.lexical.dev/
2. Enter: An extensible italic text editor framework
3. Select "extensible italic text" -> create a link
4. Select "italic" -> turn into italic
5. Select "ible italic text editor" and hit backspace or delete

Link to code example:

## The current behavior
The link wraps "extens framework"

## The expected behavior
The link wraps "extens"

https://www.youtube.com/watch?v=HRRvrgheBM8

**Comment by etrepum** [comment]
Can't reproduce
