### ISSUE TITLE
Bug: Pasting markdown table creates a duplicate code node

### ISSUE THREAD

**Issue by HexM7** [facebook/lexical#2541]
Lexical version:

## Steps To Reproduce

1. Visit the playground and create a new code block
2. Paste the following markdown content:

```md
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```

![Screenshot (49)](https://user-images.githubusercontent.com/77036902/176114737-6ba9ca35-cde6-4b25-9b73-de3462d1334a.png)

**Comment by fantactuka** [comment]
Hi @HexM7, tried to reproduce but no luck, could you check if I missed anything:


https://user-images.githubusercontent.com/132642/178986460-64c611bc-09fb-47c3-ba2d-5353fefa57ae.mov

**Comment by HexM7** [comment]
This is no longer reproducible.
