### ISSUE TITLE
Bug: dot when pressing space key

### ISSUE THREAD

**Issue by GuillotJessica** [facebook/lexical#2542]
When pressing a key followed by space key(twice or more) there is a dot added after the key

Lexical version: sandbox

https://user-images.githubusercontent.com/21151517/176124394-fc72e26b-5888-42d4-9850-0dcf20206ff1.mov

## Steps To Reproduce

1. Watch the video
2. Go to the sand box, press f followed by space key.(twice or more)

## The current behavior
Add a dot when space key is pressed
## The expected behavior
User should only have desired pressed keys printed

**Comment by thegreatercurve** [comment]
@GuillotJessica What browser and OS are you using? I'm struggling to reproduce this error.

**Comment by thegreatercurve** [comment]
Closing this for the moment as the above seems like issue. We've been unable to repro otherwise.
