### ISSUE TITLE
Bug: Text with 'underline' format is stripped out on paste

### ISSUE THREAD

**Issue by Piliuta** [facebook/lexical#2552]
Pasting rich text from other editors which support styling (e.g. Google Docs, Apple Notes and etc) removes the 'underline' style.

Lexical version: `0.3.5`

## Steps To Reproduce

1. Copy a rich text with 'underline' style from any other rich text editor
2. Paste it into the lexical playground editor

https://user-images.githubusercontent.com/1575198/176225987-f3a0188b-2323-4a77-92e5-47c320f8d93b.mov

**Note:** this is not just the playground issue. I am seeing the same issue while testing in my env. 

## The current behavior
Rich text is pasted without 'underline' style.

## The expected behavior
'underline' style should be preserved as other styles (e.g. bold or italic) do.

**Comment by caskEqui** [comment]
The underline is still not working in playground, if you click markdown, and go back to editor, the underline is gone. Its the same withe align. Is there something in markdown missing?

**Comment by raRaRa** [comment]
It seems like Lexical markdow plugin doesn't support underline
