### ISSUE TITLE
Feature: Improve $wrapLeafNodesInElements's input parameter `createElement`

### ISSUE THREAD

**Issue by aquarius-wing** [facebook/lexical#2557]
I need `createElement` parameter turn to `(targetNode: LexicalNode) => ElementNode`

Because I have some node with custom properties just like a paragraph with `pinOnMap`, when I want it turn to heading, the `pinOnMap` property is lost.

I need targetNode in createElement function's input parameters list, so I can read it and set to new node.

**Comment by thegreatercurve** [comment]
Nice idea @aquarius-wing! Would you be interested in creating this in a PR?

**Comment by zurfyx** [comment]
Closing as this function is now obsolete

**Comment by GermaVinsmoke** [comment]
@zurfyx Can you please let us know what was it replaced with?
