### ISSUE TITLE
Feature: Improve serialization flexibility of built-in nodes.

### ISSUE THREAD

**Issue by StormVanDerPol** [facebook/lexical#2559]
Currently `exportDOM` handles the way nodes serialize to html, which makes sense in the context of the editor DOM, but it's possible a user would want the output html obtained from `$generateHtmlFromNodes` to have a different shape. So I think  It would help for a user to somehow be able to change how the built-in nodes serialize to html.

Example case: `TextNode` currently serializes to either a `strong`, `span` or `em` tag with the CSS classes you find in the theme for formatting. It's possible a user would rather serialize `TextNode` to an actual text node, wrapped in `u`, `em` and `strong` tags for formatting, hypothetically because all their existing html is already structured like this.

**Comment by thegreatercurve** [comment]
This should have been solved with the introduction of replaceable base nodes in #3367
