### ISSUE TITLE
Feature: Dark Mode for Lexical Playground

### ISSUE THREAD

**Issue by im-adithya** [facebook/lexical#2563]
### Description
Having a dark mode option can help improve the UX of the playground similar to Google Docs (in mobile)!

<p>
<img width="40%" src="https://user-images.githubusercontent.com/64399555/176472888-ea74f84f-336a-44e5-ae0d-c98507a6a78f.jpg"/>
</p>

### Additional Context
I would like to work on this if core team approves!

**Comment by thegreatercurve** [comment]
Sounds good to me @im-adithya! I think this would probably mainly be CSS changes that detect your system preferences and applies different styles via `prefers-color-scheme`: https://css-tricks.com/dark-modes-with-css.

Looking into the Google Docs example, 2 things that are quite interesting that you could possible incorporate:
 - When you open the text color color picker, it will put you back into light mode.
 - There is a toggle switch for manually switching back and forth from light to dark mode.

**Comment by im-adithya** [comment]
> When you open the text color color picker, it will put you back into light mode.

Sounds interesting!

**Comment by thegreatercurve** [comment]
Close this issue for the moment as most of this functionality can be handled by the custom theming. This would be a nice addition to the playground, but not essential enough to leave the issue open.
