### ISSUE TITLE
Bug: Markdown code node importing is hardcoded

### ISSUE THREAD

**Issue by fantactuka** [facebook/lexical#2564]
Markdown functionality relies on passed transformers list, which allows passing built-in ones as well as custom nodes trasnfomers. But the code block is an exception - MarkdownImport always processes code blocks regardless of transformers list:

https://github.com/facebook/lexical/blob/2abc8244d5754860b96bfc6f875bdcbf23d4e390/packages/lexical-markdown/src/v2/MarkdownImport.ts#L54-L74

Which means even if we don't pass code blocks (or if we pass custom code node) the built-in version will be used.

**Comment by mattrhysgregory** [comment]
Hey @fantactuka I've been experimenting with a solution for multi line transformers, how about a new type of transformer "multiline-transformer" that takes in a RegExp for start and a RegExp for end? the resulting lines are joined and passed into the replace function for the transformer to parse / create node from?

```typescript
for (const {startRegExp, endRegExp, replace} of transformers) {
    // check if the block could be opening
    const openMatch = lines[startLineIndex].match(startRegExp);
    if (openMatch) {
      let endLineIndex = startLineIndex;
      const linesLength = lines.length;

      while (++endLineIndex < linesLength) {
        const closeMatch = lines[endLineIndex].match(endRegExp);

        if (closeMatch) {
          const matchingLines = lines.slice(startLineIndex, endLineIndex);
          const match = matchingLines.join('\n');

          const textNode = $createTextNode(match);
          const elementNode = $createParagraphNode();
          elementNode.append(textNode);
          rootNode.append(elementNode);

          replace(elementNode, [textNode], match, true);
          return [elementNode, endLineIndex];
        }
      }
    }
}
```

**Comment by mattrhysgregory** [comment]
I like it, will give it a go when I get some time 👍

**Comment by yj-ang** [comment]
This issue seems to be inactive for a while, not sure if the proposed changes still in consideration.

For my case, I need to convert the Excalidraw code block (See the example below) to a [ExcalidrawNode](https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx). So I created a custom markdown transformer for the ` ```excalidraw` pattern but it never work due to the hardcoded code block transformer. 

```markdown
```excalidraw
{
...
}
\```
```

For temporary workaround, I copied the entire `lexical-markdown` directory to my project and modify the `importCodeBlock` logic. I'm looking forward to get rid of this hacky workaround. :(

**Comment by milaabl** [comment]
@mattrhysgregory , please have a look at it, it really is a blocker

**Comment by cesar-ibr** [comment]
Hey guys, any updates on this? I'd like to work out a solution if no one is already doing it

**Comment by fforres** [comment]
Feels this would unblock some very powerful caes.

@cesar-ibr did you ended up taking a look?

**Comment by mayneyao** [comment]
> This issue seems to be inactive for a while, not sure if the proposed changes still in consideration.
> 
> For my case, I need to convert the Excalidraw code block (See the example below) to a [ExcalidrawNode](https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx). So I created a custom markdown transformer for the `` ```excalidraw `` pattern but it never work due to the hardcoded code block transformer.
> 
> ```
> ```excalidraw
> {
> ...
> }
> \```
> ```
> 
> For temporary workaround, I copied the entire `lexical-markdown` directory to my project and modify the `importCodeBlock` logic. I'm looking forward to get rid of this hacky workaround. :(


same issue, I want to transform code into into mermaid node.  here is my solution

```ts
// after call $convertFromMarkdownString()
for (const code of $nodesOfType(CodeNode)) {
  const lang = code.getLanguage()
  if (lang ==='mermaid')     
    code.replace($createMermaidNode(code.getTextContent()))
  }
}
```

**Comment by GitHdu** [comment]
> > This issue seems to be inactive for a while, not sure if the proposed changes still in consideration.
> > For my case, I need to convert the Excalidraw code block (See the example below) to a [ExcalidrawNode](https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx). So I created a custom markdown transformer for the `` ```excalidraw `` pattern but it never work due to the hardcoded code block transformer.
> > ```
> > ```excalidraw
> > {
> > ...
> > }
> > \```
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For temporary workaround, I copied the entire `lexical-markdown` directory to my project and modify the `importCodeBlock` logic. I'm looking forward to get rid of this hacky workaround. :(
> 
> same issue, I want to transform code into into mermaid node. here is my solution
> 
> // after calling $convertFromMarkdownString()
> for (const code of $nodesOfType(CodeNode)) {
>   const lang = code.getLanguage()
>   if (lang ==='mermaid')     
>     code.replace($createMermaidNode(code.getTextContent()))
>   }
> }

is there a mermaid demo

**Comment by mayneyao** [comment]
> > > This issue seems to be inactive for a while, not sure if the proposed changes still in consideration.
> > > For my case, I need to convert the Excalidraw code block (See the example below) to a [ExcalidrawNode](https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawComponent.tsx). So I created a custom markdown transformer for the `` ```excalidraw `` pattern but it never work due to the hardcoded code block transformer.
> > > ```
> > > ```excalidraw
> > > {
> > > ...
> > > }
> > > \```
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > For temporary workaround, I copied the entire `lexical-markdown` directory to my project and modify the `importCodeBlock` logic. I'm looking forward to get rid of this hacky workaround. :(
> > 
> > 
> > same issue, I want to transform code into into mermaid node. here is my solution
> > // after calling $convertFromMarkdownString()
> > for (const code of $nodesOfType(CodeNode)) {
> > const lang = code.getLanguage()
> > if (lang ==='mermaid')
> > code.replace($createMermaidNode(code.getTextContent()))
> > }
> > }
> 
> is there a mermaid demo

https://staging.eidos.space

**Comment by etrepum** [comment]
Commenting on closed issues and PRs is not a very effective method of communication, only the maintainers and people who interacted with the issue will see it.

Consider creating a discussion on github or [discord](https://discord.gg/KmG4wQnnD9), these are the best channels for discussing topics that are not an open issue or PR.
