### ISSUE TITLE
Feature: Has register command MOVE_TO* in rich text module

### ISSUE THREAD

**Issue by aquarius-wing** [facebook/lexical#2568]
I need a easy way to control caret.
1. register `MOVE_TO_START` and `MOVE_TO_END` in rich text module.
2. `INSERT_PARAGRAPH_COMMAND` has parameter to switch splitting the line or appending the line and inserting line before.

Here is my situation.I got a slash keyword to show a dropdown manu, just like [notion.so](notion.so), I input a '/' char, select the menu by pressing enter key to change the element node (from paragraph to heading for example).

The problem is when I input a '/' char in middle of paragraph node, what I want is create a paragraph node after this node.
But
1. the `INSERT_PARAGRAPH_COMMAND` will split the paragraph node.If it has a parameter to switch split the line or append the line and insert line before, it would be better.
2. While the `INSERT_PARAGRAPH_COMMAND` only split the paragraph node, so I need control caret `MOVE_TO_END`, and then run the `INSERT_PARAGRAPH_COMMAND`.

# Pleasure to contribute code
If my needs can be accepted, I would love to contribute code.

**Comment by im-adithya** [comment]
The slash command is in the works :rocket: #2534

**Comment by thegreatercurve** [comment]
You should be able to just call `selectStart` or `selectEnd` on the root node to achieve the above without adding in custom commands.
