### ISSUE TITLE
Bug: Selection gets wrong after link created

### ISSUE THREAD

**Issue by nextend** [facebook/lexical#2569]
Lexical version: 0.3.5

## Steps To Reproduce

1. Open https://playground.lexical.dev/
2. Delete everything, only the paragraph should stay
3. Enter "Hello World"
4. Enter an inline breakline at the end -> HTML interpretation: "Hello World[br]"
5. Select "World[br]" -> "Hello |World[br]|"
6. Click on Insert link

## The current behavior
After inserting the link "Hello " gets selected

## The expected behavior
"World[br]" should be selected

https://www.youtube.com/watch?v=U_aRmFNnYAw

**Comment by ozanyurtsever** [comment]
I couldn't reproduce this bug in my end. How do you select the text **"World"**, by just double clicking on it?

Here is my screen recording;

![CPT2206301051-1400x455](https://user-images.githubusercontent.com/36413633/176623517-b02f569c-58ff-400a-aed1-f9873a3b4294.gif)

**Comment by LuciNyan** [comment]
> I have several ways:
> 
> 1. Pointerdown before char W and move pointer into/under the line break's row and then pointerup.
> 2. Position the caret after the line break, hold shift and then hit arrow left multiple times
> 3. Position the caret before char W, hold shift and then hit arrow right multiple times until the selection->focus type turns into element

As you said, I reproduced the problem.

**Comment by etrepum** [comment]
Interestingly it looks like the element offset exceeds the size of the parent, so maybe somewhere we are converting a text point to an element point without changing the offset correctly
