### ISSUE TITLE
Bug: In an editable EditorState after Parsed, typing will create a new TextNode instead of continuing with the last TextNode

### ISSUE THREAD

**Issue by ProvidenceXz** [facebook/lexical#2575]
Lexical version: 0.3.6

### With `TextNode`
1. Refresh browser in code sandbox link
2. Editor should AutoFocus
3. type anything, see in TreeView that a new `TextNode` was created
![Screen Shot 2022-06-30 at 11 40 06 AM](https://user-images.githubusercontent.com/9211198/176753764-cc4c558e-80ae-46f3-8613-3b4881f4a44f.png) 

### With `AutoLinkNode`
1. Uncomment `SerializedAutoLinkNode` json in `state`
2. Refresh browser in code sandbox link
3. Editor should AutoFocus
4. type `m` to complete the link, see in TreeView that a new TextNode with `m` was created, and `AutoLinkNode` was destructed
![Screen Shot 2022-06-30 at 11 44 31 AM](https://user-images.githubusercontent.com/9211198/176754348-2e0835b4-ac8f-42a1-a255-48c21ee13b09.png)

Link to code example:

https://codesandbox.io/s/lexical-plain-text-example-forked-t3cgjf?file=/src/Editor.js

## The current behavior

- On fresh parsing, editor won't consider the last `TextNode`, will blindly create a new `TextNode` and won't merge it with its predecessor

## The expected behavior

- The last `TextNode` should be open for edit, new input should be considered part of that TextNode
- `AutoLinkNode` shouldn't collapse, it should take new input as part of its child `TextNode`

**Comment by fantactuka** [comment]
Thanks for the sandbox example, it helped a lot!

Serialized state missing format/detail/styles fields for text nodes (even tho they have default values). Fixed sandbox:
https://codesandbox.io/s/lexical-plain-text-example-forked-3nuxbu?file=/src/Editor.js

That should fix the issue, but feel free to reopen if it's something else

**Comment by ProvidenceXz** [comment]
@fantactuka Wow. I would never know, in my case, I don't need format/detail/style so I don't persist them.

Is this an implementation detail thing? Like, when I input, since format/detail/style doesn't match, the editor then creates a new `TextNode`? If so, why is the existing node not assigned default values when first parsed?

I haven't tested but I think this will fix my issue. But I'm curious about the above question.

**Comment by fantactuka** [comment]
> Is this an implementation detail thing? Like, when I input, since format/detail/style doesn't match, the editor then creates a new `TextNode`? If so, why is the existing node not assigned default values when first parsed?

The rule of thumb here is to persist Lexical's serialized state regardless of fields usage on backend since serialization/deserialization are tied together. I guess we can use default values if they are not set in serialized json, will see if there any downsides

**Comment by ProvidenceXz** [comment]
@fantactuka just to give you a better idea of where I come to this.

I persist the whole editor tree structure (representing nodes as DTOs) instead of JSON string. As part of the limitation of GraphQL I need to use a single input type for all nodes, but there's a conflict with `TextNode` and `ElementNode`'s serialized `format` type (one is bitmap as number for performance reasons, the other is just string). Since I don't use `format` at all (the default one works), I simply omitted them.

I'm interested to know whether default values can be set when parsing incomplete serialized nodes. That'd help with my code cleanliness. In the meantime, I'll do the fix you did in my sandbox. Thanks again :)
