### ISSUE TITLE
Bug: Windows Chrome 50 keyboard input text node not work

### ISSUE THREAD

**Issue by gauseen** [facebook/lexical#2577]
Lexical version: 0.3.6

## Steps To Reproduce

1. window Chrome 50 keyboard input text node not work

```tsx
<LexicalComposer initialConfig={initialConfig}>
  <PlainTextPlugin
    contentEditable={<ContentEditable className="content-editable-root" />}
    placeholder={<Placeholder>{placeholder}</Placeholder>}
  />
  <AutoFocusPlugin />
</LexicalComposer>
```

https://user-images.githubusercontent.com/22701565/176819760-72e151c7-4537-4158-b82a-847dbcd8b099.mp4

Link to code example:

**Comment by thegreatercurve** [comment]
@gauseen Are you still experiencing this issue? I know we fixed a load of bugs with international composition a while ago.

**Comment by thegreatercurve** [comment]
Closing this as I wasn't able to replicate the bug on a Window laptop.
