### ISSUE TITLE
Feature: Add toHTML on EditorState object

### ISSUE THREAD

**Issue by trueadm** [facebook/lexical#2586]
Today, using `$generateHtmlFromNodes` requires jumping through a bunch of hoops and also requires doing calling the helper `editor.update`. Maybe we can simplify this and move it into core by just providing a `toHTML` method on the `EditorState` itself, similar to how we have `toJSON`.

**Comment by trueadm** [comment]
Closing this issue. Thinking about it more, it's not possible to do this as we need to have knowledge of the `editor` object, unlike the `toJSON` workflow – as we invoke the `createDOM` methods on nodes, and thus need the `EditorConfig`.

**Comment by guotie** [comment]
I think `toHTML` is possible for editorState, tiptap do provide this method.
