### ISSUE TITLE
Bug: Pasting text which cause NodeTransform might result in error

### ISSUE THREAD

**Issue by nextend** [facebook/lexical#2589]
Lexical version: 0.3.5

## Steps To Reproduce

1. Open https://codesandbox.io/s/elastic-chihiro-9w484f
2. Select "Copy me!" (Make sure that only the link selected and no whitespace before/after on the clipboard)
3. CTRL+C or copy
4. Click into the editor area and paste CTRL+V

Link to code example:

## The current behavior
Error: updateEditor: selection has been lost because the previously selected nodes have been removed and selection wasn't moved to another node. Ensure selection changes after removing/replacing a selected node.

## The expected behavior
There should not be an error and TextNode gets added to the content

This problem is related to the fact that LinkNode gets NodeTransform-ed into TextNode:
```
editor.registerNodeTransform(LinkNode, (node) => {
    node.replace(new TextNode(node.getTextContent()));
});
```

https://www.youtube.com/watch?v=buJLVaoyNJw

**Comment by thegreatercurve** [comment]
@nextend Sorry for the delay in looking at this bug. I think this just got lost in all of the issues. 

Thank you for the detailed but minimalistic bug report though! It's really appreciated as it makes everything easy to debug.

In this case, the error message is correct. You need to select the new node after the transform. The below solves the issue: 
```js
editor.registerNodeTransform(LinkNode, (node) => {
    const textNode = new TextNode(node.getTextContent());
    node.replace(textNode);
    textNode.select();
});
```

**Comment by nextend** [comment]
@thegreatercurve Thank you for the solution. I changed a little bit to check whether the replaced node was selected or not. I hope it will work as expected :)

```
editor.registerNodeTransform(LinkNode, node => {
	const selection = lexical.$getSelection();
	const textNode = new TextNode(node.getTextContent());

	node.replace(textNode);

	if (lexical.$isRangeSelection(selection) && (selection.anchor.getNode() === node || selection.focus.getNode() === node)) {
		textNode.select();
	}
});
```

**Comment by sonlichao** [comment]
When I selected all items in my lexical editor and pasted a html, my lexical editor crashed.
When I do the same actions in https://playground.lexical.dev/, it crashed as well. 

<img width="690" alt="スクリーンショット 2023-12-14 16 17 10" src="https://github.com/facebook/lexical/assets/8370453/1a0f09ef-d292-4110-8b88-b3303cdab25f">
