### ISSUE TITLE
Bug: $restoreEditorState inside a NodeTransform causes error if passed state has additional empty nodes

### ISSUE THREAD

**Issue by aarku** [facebook/lexical#2593]
Calling `$restoreEditorState()` in a `RootNode` `NodeTransform` with a state that has more nodes than the previous state causes a TypeError during reconciliation.

Context: I'm trying to make a plugin to enforce a certain hierarchy of nodes, i.e. a template. This is a contrived example based on the MaxLengthPlugin from the playground.

Is `$restoreEditorState` even the right approach for templates? Otherwise it looks like I'd have to make a handler to every command that could potentially mess with node hierarchy.

Lexical version:
0.3.6

## Steps To Reproduce

1. Open up this sandbox forked from lexical-rich-text-example: https://codesandbox.io/s/recursing-turing-gd8uy4?file=/src/Editor.js
2. In the running app with the editor focused, press `Enter` followed by `Backspace`.
3. An exception is thrown during update.

Link to code example: https://codesandbox.io/s/recursing-turing-gd8uy4?file=/src/Editor.js

## The current behavior
An exception is thrown.
## The expected behavior
The AllowAppendOnlyPlugin plugin should block the delete attempt.

Thanks! I love lexical's architecture, I'm excited to use it more.

**Comment by aarku** [comment]
I'm going to switch my approach to adding nodes in the transformer if they don't exist, instead of trying to block them from leaving. I think it's still a bug, but this other approach seems to be going better.

**Comment by thegreatercurve** [comment]
We are aware of some bugs in `$restoreEditorState`, notably how it restores the editor node map.
