### ISSUE TITLE
Bug: <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'lexical'

### ISSUE THREAD

**Issue by akichim21** [facebook/lexical#2601]
I get an error sometimes. Rebuilding the container several times, fix it.
It may not have anything to do with lexical, but I'll report it.

next: 12.1.5
lexical: 0.3.6
yarn: 1.22.19
node: v16.15.1
Dockerfile: node:16-alpine

when next dev
```
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'lexical' in '/'
<w> while resolving 'lexical' in / to a directory
```

when access editor page
```
Module not found: Can't resolve '@lexical/react/LexicalComposer'
```

**Comment by fantactuka** [comment]
Have you tried deleting package-lock.json and re-generating it? I suppose restarting container does not do it

https://stackoverflow.com/questions/67082806/when-updating-next-js-v10-1-13-to-webpack5-getting-warnings-cant-resolve-fsev

I'll close it for now, as does not seem related, but feel free to reopen

**Comment by Eloyts97** [comment]
I get this error /@lexical/clipboard/LexicalClipboard.dev.js
Module not found: Can't resolve 'lexical' in '/node_modules/@lexical/clipboard'

With this imports:
import { $getRoot, $getSelection } from 'lexical';

// import Lexical components
import { LexicalComposer } from '@lexical/react/LexicalComposer';
import { PlainTextPlugin } from '@lexical/react/LexicalPlainTextPlugin';
import { ContentEditable } from '@lexical/react/LexicalContentEditable';
import { HistoryPlugin } from '@lexical/react/LexicalHistoryPlugin';
import { OnChangePlugin } from '@lexical/react/LexicalOnChangePlugin';
import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext';
import LexicalErrorBoundary from '@lexical/react/LexicalErrorBoundary';
