### ISSUE TITLE
Bug: Setting a pending format at end of text before beginning a (Japanese) composition in Safari errors with "Lexical node does not exist in active editor state"

### ISSUE THREAD

**Issue by birtles** [facebook/lexical#2613]
Lexical version:

## Steps To Reproduce

1. Open the lexical playground in Safari (desktop)
2. Select all the text and delete it
3. Switch to Japanese input
4. Press <kbd>a</kbd> followed by <kbd>Enter</kbd> to commit あ
5. Press <kbd>⌘</kbd>+<kbd>B</kbd> to set bold on the collapsed selection
6. Press <kbd>a</kbd> to begin a new composition

## The current behavior

An error is produced and the candidate window shows up with an "a" and no candidate text in the editor.

In the current version of the playground which uses the production version of Lexical, the error is:

```
Error: Minified Lexical error #69...
```

![image](https://user-images.githubusercontent.com/1232595/177925579-c4618e45-9bc4-4af2-a579-38f3cbd5d7b5.png)

Using a similar setup with a dev build of Lexical, the error is:

```
Error: Lexical node does not exist in active editor state. Avoid using the same node references between nested closures from editor.read/editor.update.
```

![image](https://user-images.githubusercontent.com/1232595/177925643-9466aafd-724f-450f-a988-b45aa88e97fa.png)

## The expected behavior

It should not error. 

This appears to come about from this block:

https://github.com/facebook/lexical/blob/82bb692f221b813d9702b3c8a83aebff0788f92a/packages/lexical/src/LexicalEvents.ts#L391-L419

It looks like the reference to `node` used inside the `setTimeout` is now stale.

**Comment by LuciNyan** [comment]
This doesn't seem to be a safari-only bug, it can also be reproduced in chrome.

**Comment by birtles** [comment]
Thanks @LuciNyan!

**Comment by milaabl** [comment]
I have the same problem with my English-language-based CustomNode in a RichTextEditor plugin format #3938 Error: Lexical node does not exist in active editor state. Avoid using the same node references between nested closures from editorState.read/editor.update.

**Comment by volodymyrl** [comment]
I get the same error when I try to use **MaxLengthPlugin** https://github.com/facebook/lexical/blob/d4b192289d3714b34614b411d40e513d1f86f413/packages/lexical-playground/src/plugins/MaxLengthPlugin/index.tsx#L43.  

_Uncaught Error: Lexical node does not exist in active editor state. Avoid using the same node references between nested closures from editorState.read/editor.update._

**Comment by MAK-Denis** [comment]
@vlysytsia Did you figure out the solution yet?
I'm seeing the exact same issue on my end too.
