### ISSUE TITLE
Bug: Link toggle doesn't work when it is in the end of a paragraph

### ISSUE THREAD

**Issue by Piliuta** [facebook/lexical#2614]
Lexical version: 0.3.7

## Steps To Reproduce

1. Open the playground page https://playground.lexical.dev/
2. Add any link at the end of a paragraph
3. Set the caret to the end of the link (note: the link will be recognized in the toolbar)
4. Press the link button in the toolbar to unlink

https://user-images.githubusercontent.com/1575198/177985346-7365bc5f-de3e-4819-b13c-d901daaefdb8.mov

## The current behavior
Link is not removed when the caret is set at the end of a link located at the end of a paragraph

## The expected behavior
Whenever the link is recognized (i.e. the toolbar indicates it is a link), click on the button should unlink the link.

**Comment by trueadm** [comment]
The bug here is that the toolbar thinks it’s a link. If your caret is at the end, it’s not actually on the link, it’s after the link due to how link semantics work on the web

**Comment by Piliuta** [comment]
The selection state has the focus set to the end of the link in this case. Is the expected behavior that the selection has a different state?

**Comment by Piliuta** [comment]
> The bug here is that the toolbar thinks it’s a link. If your caret is at the end, it’s not actually on the link, it’s after the link due to how link semantics work on the web

The selection state has the focus set to the end of the link in this case. Is the expected behavior that the selection has a different state?

**Comment by trueadm** [comment]
Actually, I mistook the video and thought there was a text node after. The selection should be at the end of the link in this case as there is no next sibling. Looks like a bug in the link toggling logic.

**Comment by Piliuta** [comment]
Yeah, the key note is that there is nothing after the link. Can I expect this to be fixed then? 🙏🏻 

Without too many details, when I was looking into the code, I noticed that the toggle command uses `$getSelection.extract()` and it returns null (even though `$getSelection.getNodes()` returns a list with the link node). Not sure what's the difference between these two, but perhaps it gives you a clue.

**Comment by acywatson** [comment]
Now I'm wondering why we have both Selection.extract and Selection.getNodes. The semantics are similar.

**Comment by acywatson** [comment]
Oh, I see - it's about extracting out partially selected text.
