### ISSUE TITLE
Bug: Selecting text ending in bold and then typing produces one character without bold and the remainder in bold

### ISSUE THREAD

**Issue by birtles** [facebook/lexical#2626]
Lexical version: Playground version (0.3.7?)

Testing with Firefox Nightly (104) and Safari desktop.

## Steps To Reproduce

1. Open [lexical playground](https://playground.lexical.dev/)
2. Select all the text and delete it
3. Type "Hello there"
4. Select "there" and make it bold, e.g. by pressing <kbd>Ctrl</kbd> + <kbd>B</kbd>
5. Select the whole string, "Hello there", from left to right
6. Type something, like "Hi again"

## The current behavior

"H**i again**" is produced with "H" not in bold, and "i again" in bold.

## The expected behavior

I guess none of it should be bold. That would match Word's behavior.

If that's difficult, at least making all of the typed text would be more consistent.

## Screen shots

With the text selected:

![image](https://user-images.githubusercontent.com/1232595/178173884-89a57a10-b65e-4b67-9238-f844ba00364a.png)

After typing "H" (notice we have the text node for "H" with _no_ format but the selection has `{ format: bold }`).

![image](https://user-images.githubusercontent.com/1232595/178173915-d729ddd3-a5da-46fd-a789-1bc5f1d1c84e.png)

After typing "i again" (notice the selection format has been applied to the remaining text

![image](https://user-images.githubusercontent.com/1232595/178173980-c2347502-489c-40c8-9ced-439f8c00a5b6.png)

I suppose we need to detect that text is being replaced and reset the selection's format to the format of the anchor node?

**Comment by tomashco** [comment]
I tried to understand better the behaviour here, I think there is a misalignment when RangeSelection "is" method is called (see packages/lexical/src/LexicalSelection.ts) 

Looking at this.format and selection.format, the latter (selection.format) gets updated a character after "this" is updated. I think if "selection" would be in sync with "this" there wouldn't be this behaviour (but I couldn't be able to fix it).

Anyone else has any hint on how to address this bug?
