### ISSUE TITLE
Bug: editor draws focus when setting initial state to empty markdown string

### ISSUE THREAD

**Issue by horvdan** [facebook/lexical#2636]
Creating an editor with `editorState: () => $convertFromMarkdownString("")` causes the editor to receive focus.

This only happens if there was something focused previously, so it won't happen on initial render, but always happens after adding new editors with a button click for example.

Lexical version: 0.3.7

## Steps To Reproduce

1. Load example, note that the editor doesn't have focus
2. Add a new editor without a default value - it receives focus
3. Write something in the default value textbox and add another editor - this time it doesn't receive focus

Link to code example:
https://codesandbox.io/s/xenodochial-breeze-3bh4mn

## The current behavior
The editor draws browser focus.

## The expected behavior
The editor state is initialized with an empty paragraph node and selection set at start (same behavior as currently), but it  doesn't draw browser focus.

**Comment by fantactuka** [comment]
Try adding `$setSelection(null)` after `$convertFromMarkdownString` to avoid re-focusing

**Comment by horvdan** [comment]
That works indeed, thank you!

Is there maybe a way to keep the initialized selection state while preventing focus?

I understand that the default editorState has `selection: null` set, but that makes that toolbar unusable without focusing the editor first. Do we have to check for null selections and calling `$getRoot().selectEnd()` if none before every text format/block type change/insert command coming from the toolbar, or am I missing some obvious solution here?

(The playground's toolbar would have the same issue without the initial content/autofocus)

**Comment by hanford** [comment]
I believe I ran into this too: https://github.com/facebook/lexical/issues/2328

**Comment by fantactuka** [comment]
> Do we have to check for null selections and calling $getRoot().selectEnd() if none before every text format/block type change/insert command coming from the toolbar, or am I missing some obvious solution here?

Sounds right to me, otherwise toolbar would seem broken
