### ISSUE TITLE
Bug: Quote: Conversion between paragraph and quotes with links creates extra elements

### ISSUE THREAD

**Issue by Piliuta** [facebook/lexical#2647]
Lexical version: 0.3.7

## Steps To Reproduce

1. Open the playground page https://playground.lexical.dev/
2. Create any paragraph with links in it
3. Select all text of the paragraph (Note: should a range selection, i.e. not collapsed)
4. Apply "Quote" format - (1 + x links) quotes created
5. Select text on the Quote and turn it into Normal text - 

https://user-images.githubusercontent.com/1575198/179219061-7fdfbc96-4b00-4e87-a6c4-cbfb3f0427d0.mov

## The current behavior
The paragraph is converted to Quote with extra Quotes above it. _Every link creates an extra Quote_
The Quote is converted into multiple paragraphs

## The expected behavior
The paragraph is converted to a single Quote. The quote is converted to one paragraph.

Notes: Looks like the problem is caused by the `$wrapLeafNodesInElements` method [somewhere here](https://github.com/facebook/lexical/blob/645227ebd0f61942d48897b03b0701a4da884508/packages/lexical-selection/src/index.ts#L667-L698) that generates extra elements.

**Comment by acywatson** [comment]
Related to #2648

**Comment by Piliuta** [comment]
I was able to find where the problem comes from:

When we have a text selection like `text [link](google.com)` and wrap it using the `$wrapLeafNodesInElements` function:
- it loops through all children elements (including nested ones), in the examples the list of nodes is
```
[
  { type: 'text', text: 'text ' },
  { type: 'link', url: 'google.com ' },
  { type: 'text', text: 'link ' },
]
```
- [1st loop] it gets children from the parent of the first node, appends them to the wrapped element and changes parent relations on them to the new node
https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L688-L689
- [2nd loop] does not do anything because the link node is not considered a leaf (I think this is a bug too, but this is not the source of the problem)
https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L677
or otherwise, it would be ignored because this is a first-level leaf (because already wrapped)
https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L678
- [3rd loop] the text node is not a first-level leaf, so it is not in the `movedLeafNodes` set, so it passes this condition
https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L678
it also passes the condition that checks if the parent was already moved (since this is a child of the link node that already has a new parent and the new parent key is not in the map)
https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L682
so now it creates a new wrapping element
https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L683-L685


**Problem:** The general problem is that the function attempt to loop through all children including nested, however it doesn't memorize if the nested children were already moved or not.

**Proposed solutions:**
### First
Add all children **including nested ones** to the moved leaves when their parent is wrapped with the new node
https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L690

### Second
Check if a parent at any level up in the tree is already wrapped while looping through the nodes:
I did something like this, but this considers only one level-up
```javascript
    if (
      movedLeafNodes.has(node.getKey())
      || (node.getParent() && movedLeafNodes.has(node.getParent().getKey()))
    ) {
      continue;
    }
```

### Third
Loop through first-level leaves only while moving them to the wrapping node.
https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L664-L667


@acywatson is this something that can be prioritized to be fixed?

**Comment by acywatson** [comment]
> I was able to find where the problem comes from:
> 
> When we have a text selection like `text [link](google.com)` and wrap it using the `$wrapLeafNodesInElements` function:
> 
> * it loops through all children elements (including nested ones), in the examples the list of nodes is
> 
> ```
> [
>   { type: 'text', text: 'text ' },
>   { type: 'link', url: 'google.com ' },
>   { type: 'text', text: 'link ' },
> ]
> ```
> 
> * [1st loop] it gets children from the parent of the first node, appends them to the wrapped element and changes parent relations on them to the new node
>   https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L688-L689
> * [2nd loop] does not do anything because the link node is not considered a leaf (I think this is a bug too, but this is not the source of the problem)
>   https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L677
>   
>   or otherwise, it would be ignored because this is a first-level leaf (because already wrapped)
>   https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L678
> * [3rd loop] the text node is not a first-level leaf, so it is not in the `movedLeafNodes` set, so it passes this condition
>   https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L678
>   
>   it also passes the condition that checks if the parent was already moved (since this is a child of the link node that already has a new parent and the new parent key is not in the map)
>   https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L682
>   
>   so now it creates a new wrapping element
>   https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L683-L685
> 
> **Problem:** The general problem is that the function attempt to loop through all children including nested, however it doesn't memorize if the nested children were already moved or not.
> 
> **Proposed solutions:**
> 
> ### First
> Add all children **including nested ones** to the moved leaves when their parent is wrapped with the new node
> 
> https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L690
> 
> ### Second
> Check if a parent at any level up in the tree is already wrapped while looping through the nodes: I did something like this, but this considers only one level-up
> 
> ```js
>     if (
>       movedLeafNodes.has(node.getKey())
>       || (node.getParent() && movedLeafNodes.has(node.getParent().getKey()))
>     ) {
>       continue;
>     }
> ```
> 
> ### Third
> Loop through first-level leaves only while moving them to the wrapping node.
> 
> https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-selection/src/index.ts#L664-L667
> 
> @acywatson is this something that can be prioritized to be fixed?

Thanks for your work on debugging this!

Would you be interested in making a PR to apply your findings?

One note here:

> [2nd loop] does not do anything because the link node is not considered a leaf (I think this is a bug too, but this is not the source of the problem)

As you pointed out, likely not the source of the problem, but conceptually a LinkNode is an "inline ElementNode" and it wouldn't be a leaf.

This function has always been a pretty naive approach to comprehensively handling the formatting case and it breaks in a lot of weird ways. I'm open to the improvement you're suggesting, though, but I can't promise a timeline on a fix from the core team. If you make a PR, we will certainly do our best to review and get that merged in a timely manner.
