### ISSUE TITLE
Bug: Block selection from start to end affects next block when converted to other blocks

### ISSUE THREAD

**Issue by Piliuta** [facebook/lexical#2648]
Lexical version: 0.3.7

## Steps To Reproduce

1. Open the playground page https://playground.lexical.dev/
2. Create two paragraphs
3. Select the first one (from the very end, e.g. use double-click)
4. Apply any block format (e.g. heading or quote)

https://user-images.githubusercontent.com/1575198/181064038-183b3c2c-ddf3-4b4c-93b0-8af03805e567.mov

## The current behavior
The selected paragraph and the paragraph next to it are converted into the new format.

## The expected behavior
Only the selected paragraph is converted into the format. The paragraph next to it remains as is.

**Comment by acywatson** [comment]
This is interesting - there's actually only one paragraph in the editor state - it looks like a new one is actually inserted before the existing one when you apply the QuoteNode formatting.

This is probably an issue with $wrapLeafNodesInElements, which has always been a bit buggy, especially around inline elements.

**Comment by Piliuta** [comment]
@acywatson I just realized that I attached the wrong video to this issue (already updated). This issue is different from what I posted here https://github.com/facebook/lexical/issues/2647 and _I feel like they might actually be different bugs_. Could you take another look?

**Comment by zeeyang** [comment]
Triple click block selection includes the line break node, which puts selection range end at the beginning of next paragraph. $wrapLeafNodesInElements just needs to be smarter about not including the next paragraph if selection range is at the beginning.

**Comment by Piliuta** [comment]
@acywatson I am thinking to make a fix for this issue. I can see at least two different approaches here:
1. Fix the function that wraps nodes to be smarter as @zeeyang [proposed](https://github.com/facebook/lexical/issues/2648#issuecomment-1211028229). 
2. Change how lexical handles selection via triple-click overriding default behavior to select only the block from start to end. 

I see different editors handle it differently, so not sure what's the preferable solution here.

Any preferences or concerns here?

**Comment by Piliuta** [comment]
> After triple click I would expect the carriage return to be selected. i.e. delete after triple click should completely remove the paragraph including carriage return. I tested on several editors and this seems to be the universal expectation. I think option 2 goes against this expected behavior.

Tested in JIRA, Google Docs, Coda, Discord products, and Slate framework - neither of these remove the carriage return 🤷🏻‍♂️

**Comment by zeeyang** [comment]
Did a quick test on Google Docs, Slack, MS Word, Apple Pages, Apple Notes - all behaved the same with carriage return moved. The only one didn't was Coda, but it was doing something very custom there.

![Kapture 2022-11-01 at 10 57 55](https://user-images.githubusercontent.com/2062827/199305710-1e4f9310-d293-4a3d-9b57-4d6196b8b364.gif)

![Kapture 2022-11-01 at 10 58 36](https://user-images.githubusercontent.com/2062827/199305731-cee70832-d231-4586-b1e1-553562ee52d7.gif)

![Kapture 2022-11-01 at 11 01 22](https://user-images.githubusercontent.com/2062827/199305759-10718d09-39a7-491e-b02d-c898dae5ef39.gif)

**Comment by Piliuta** [comment]
> Did a quick test on Google Docs, Slack, MS Word, Apple Pages, Apple Notes - all behaved the same with carriage return moved. The only one didn't was Coda, but it was doing something very custom there.

See, it is different.

_I found Google Docs inconsistent though. I did see the same behavior as you recorded, but now I am not able to reproduce it, it always keeps the carriage. Seems like it has some complicated rules around it_ 

Either behavior makes sense to me. It is something that should probably be customizable per product.

I am going to propose a fix for the wrapper function as the first step.

**Comment by EgonBolton** [comment]
I think I solved this in [the PR I started and didn't finish](https://github.com/facebook/lexical/pull/3234), where $wrapnodes is much simplified.
The only thing I need is to fix the $isBlock function, so that it doesn't import nodes. It shouldn't be too hard, but I've been really busy lately.

**Comment by Piliuta** [comment]
> I think I solved this in [the PR I started and didn't finish](https://github.com/facebook/lexical/pull/3234), where $wrapnodes is much simplified. The only thing I need is to fix the $isBlock function, so that it doesn't import nodes. It shouldn't be too hard, but I've been really busy lately.

I pulled your branch and still do see the problem. Thanks for pointing out the PR, I'll check if there is anything that potentially can be used to fix it.

**Comment by mattslight** [comment]
Issue is still present in 0.7.5 and 0.7.6. Oddly enough when beforming bold, italic etc the functionality works. So I think looking at that code for FORMAT_TEXT_COMMAND [selection.formatTextI()] would be the place to start and then mirroring into $setBlockType_experimental https://github.com/facebook/lexical/pull/3234

https://github.com/facebook/lexical/blob/a18e04c349039bbf10bc54f0aaa908c415d28d08/packages/lexical/src/LexicalSelection.ts#L1077

**Comment by Piliuta** [comment]
JFYI: I managed to handle this issue in my implementation by calling a custom trimming function before `$wrapNodes`. The function looks like this:

```js
export function $trimBoundaries(selection) {
  const selectionEnd = selection.isBackward()
    ? selection.anchor
    : selection.focus;
  if (
    $isRangeSelection(selection) &&
    !selection.isCollapsed() &&
    selectionEnd.offset === 0
  ) {
    let trailingNode = selectionEnd.getNode();
    while (trailingNode !== null) {
      const parentOffset = trailingNode.getIndexWithinParent();
      trailingNode = trailingNode.getParentOrThrow();

      if ($isRootNode(trailingNode)) {
        if (selection.isBackward()) {
          const collapsedEndSelection = selection.clone();
          collapsedEndSelection.modify('move', false, 'character');
          collapsedEndSelection.modify('move', true, 'character');
          selection.anchor = collapsedEndSelection.anchor;
        } else {
          $moveCharacter(selection, true, true);
        }
        break;
      }

      if (parentOffset !== 0) {
        break;
      }
    }
  }
}
```

This ensures it moves the caret to the trailing position of the previous line if it is right at the leading edge. This works regardless of selection directions.

**Comment by mattslight** [comment]
Great, thank you so much for sharing - I will try to reuse this code and
see if I can reproduce a fix on my side.
