### ISSUE TITLE
Question: how to get the instance ?

### ISSUE THREAD

**Issue by HZZformGD** [facebook/lexical#2656]
Hi, I am a newbie.  I had read the doc several times ,  but could not find how to get the instance. I try to use useRef to get the editor instance but fail.  so is there any sample code to show me.  Extra question , How to set a default text ? useState or other methods? I wish i can get the sample code.

```code
@lexical/react: 0.3.7
lexical: 0.3.7
```

what i want is following code
```javascript
function App (){
      const toggleReadOnly = () => {
        instance.setReadOnly(false)
      }
      const [defaultValue] = useState('Dude, typing something on here.')

     return <>
            <LexicalComposer  initialConfig={{
                      ...editorConfig,
                      readOnly: true,
                    }}
             />
                       <PlainTextPlugin
                              initialEditorState={defaultValue}
                              contentEditable={<ContentEditable className="editor-input" />}
                           />
            </LexicalComposer>
             <button onClick={toggleReadOnly}></button>
     </>
}
```

**Comment by Piliuta** [comment]
You can get access to the editor instance using the `useLexicalComposerContext` custom hook from `'@lexical/react/LexicalComposerContext'`. The first value of the returned list is the editor instance, so to get it you would do:

`const [editor] = useLexicalComposerContext();`

and then the toggle read-only state method would look like this:

```
const toggleReadOnly = () => {
  editor.setReadOnly(false)
}
```

**Comment by HZZformGD** [comment]
> You can get access to the editor instance using the `useLexicalComposerContext` custom hook from `'@lexical/react/LexicalComposerContext'`. The first value of the returned list is the editor instance, so to get it you would do:
> 
> `const [editor] = useLexicalComposerContext();`
> 
> and then the toggle read-only state method would look like this:
> 
> ```
> const toggleReadOnly = () => {
>   editor.setReadOnly(false)
> }
> ```
> 
> There is an example on this page https://lexical.dev/docs/getting-started/react.

Thanks for your reply. But emmm i  got an error in your way.  
```code
LexicalComposerContext.useLexicalComposerContext: cannot find a LexicalComposerContext
```
I use useLexicalComposerContext hook  outside LexicalComposer Component (I don't want a plugin way). like 
```javascript
function App (){
      const toggleReadOnly = () => {
        instance.setReadOnly(false)
      }
      const [editor] = useLexicalComposerContext();


      const [defaultValue] = useState('Dude, typing something on here.')

     return <>
            <LexicalComposer  initialConfig={{
                      ...editorConfig,
                      readOnly: true,
                    }}
             />
                       <PlainTextPlugin
                              initialEditorState={defaultValue}
                              contentEditable={<ContentEditable className="editor-input" />}
                           />
            </LexicalComposer>
             <button onClick={toggleReadOnly}></button>
     </>
}
```

**Comment by HZZformGD** [comment]
> You can get access to the editor instance using the `useLexicalComposerContext` custom hook from `'@lexical/react/LexicalComposerContext'`. The first value of the returned list is the editor instance, so to get it you would do:
> 
> `const [editor] = useLexicalComposerContext();`
> 
> and then the toggle read-only state method would look like this:
> 
> ```
> const toggleReadOnly = () => {
>   editor.setReadOnly(false)
> }
> ```
> 
> There is an example on this page https://lexical.dev/docs/getting-started/react.

Hey, @Piliuta . i found a solution.  I don't know if this is good or not. Seeing the code

```javascript
function App (){
      const ref = useRef(null)

      const toggleReadOnly = () => {
        ref?.current?.setReadOnly(false)
      }
      const [editor] = useLexicalComposerContext();


      const [defaultValue] = useState('Dude, typing something on here.')

     return <>
            <LexicalComposer  initialConfig={{
                      ...editorConfig,
                      readOnly: true,
                      editorState: (instance) => ref.current = instance
                    }}
             />
                       <PlainTextPlugin
                              initialEditorState={defaultValue}
                              contentEditable={<ContentEditable className="editor-input" />}
                           />
            </LexicalComposer>
             <button onClick={toggleReadOnly}></button>
     </>
}
```
And...another  extra question (sorry I'm still a novice), how to place cursor to last position ?




```

**Comment by thegreatercurve** [comment]
@HZZformGD Move everything within the context of `LexicalComposer`:
```
<LexicalComposer  initialConfig={{...editorConfig, readOnly: true }} >
    <CustomEditor />
</LexicalComposer>
```
You can set an editor as `readOnly` without needing to reset the `initialConfig` prop of the `LexicalComposer` component. Call `editor.setReadOnly` within your `toggleReadOnly` function instead.

**Comment by HZZformGD** [comment]
> @HZZformGD Move everything within the context of `LexicalComposer`:
> 
> ```
> <LexicalComposer  initialConfig={{...editorConfig, readOnly: true }} >
>     <CustomEditor />
> </LexicalComposer>
> ```
> 
> You can set an editor as `readOnly` without needing to reset the `initialConfig` prop of the `LexicalComposer` component. Call `editor.setReadOnly` within your `toggleReadOnly` function instead.

Oh!!!!! Thx. I get it.
