### ISSUE TITLE
Feature: Multiple class names in theme to use e.g. TailwindCSS seamlessly

### ISSUE THREAD

**Issue by CanRau** [facebook/lexical#2666]
I tried to use TailwindCSS utility classes in my theme like so

```js
underlineStrikethrough: "underline line-through",
```

and just in case also tried `underlineStrikethrough: "underline.line-through"` which is the Emmet style.

Though that's just toggling or something and doesn't work as expected.

I think it would be fantastic to be able to use utility classes, space (or dot separated).

My workaround at least for the `underlineStrikethrough` case is

```js
underlineStrikethrough: "[text-decoration:underline_line-through]"
```

Which works thanks to the "new" JIT mode and being able to define [arbitrary properties](https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties).

Anotherone would be to use [plugins](https://tailwindcss.com/docs/plugins) and then define styles using `addUtilities()` or `addComponents()`.

Or maybe there's some limitation I don't (yet) understand 🤷🏻‍♂️

Anyway, thanks a lot for Lexical, so far it's the best RTE experience I've had so far 🥳❤️

**Comment by maltesa** [comment]
Using multiple classes works for me without any problems (with `"lexical": "0.3.7",`):

![image](https://user-images.githubusercontent.com/4067078/180156388-f5e14ecd-59b4-4b21-a475-4a33b5439904.png)

```js
// https://lexical.dev/docs/getting-started/theming
export const theme = {
  placeholder: 'richtext rt-placeholder text-gray-500',
  paragraph: 'richtext rt-paragraph text-gray-700 leading-normal my-2',
  link: 'richtext rt-link text-primary-500 underline',
  quote: 'richtext rt-quote border-l-4 pl-2 text-gray my-2',
  code: 'richtext rt-code rounded p-3 bg-gray-700 my-2 font-mono text-white block overflow-auto',
  text: {
    bold: 'richtext rt-bold font-bold',
    code: 'richtext rt-code font-mono text-gray-700 bg-gray-300 rounded text-base p-1',
    italic: 'richtext rt-italic italic',
    strikethrough: 'richtext rt-strikethrough line-through',
    underline: 'richtext rt-underline underline',
    underlineStrikethrough:
      'richtext rt-underlineStrikethrough line-through border-b-2 border-black',
  },
  heading: {
    h1: 'richtext rt-h1 pt-4 font-extra text-3xl text-primary leading-tight tracking-tighter',
    h2: 'richtext rt-h2 pt-3 font-bold text-2xl text-gray-600 leading-tight tracking-tight',
    h3: 'richtext rt-h3 pt-2 font-bold text-xl text-gray-500 leading-tight tracking-tight',
  },
  list: {
    // listitem: 'richtext rt-listitem ',
    ul: 'richtext rt-ul list-disc ml-5 marker:text-gray-600 marker:text-lg',
    ol: 'richtext rt-ol list-decimal ml-5 marker:text-gray-600',
    nested: { listitem: 'richtext rt-listitem list-none' },
  },
}
```

**Comment by thegreatercurve** [comment]
Yeah, or maybe use a pseudo element on the class to create the underline or strikethrough. 

(Closing this as it seems like a styling clash with Tailwind.)

**Comment by CanRau** [comment]
Uh interesting, you're right, I was expecting for it to show both classes, but because in the `underlineStrikethrough: "underline line-through",` case it doesn't I thought it's not working.
It surprises me that it's only in this case not applying both classes and then not working as you pointed out because only one would actually work.

Anyways, glad it's working and also thanks for the alternative option to `[text-decoration:underline_line-through]`.
