### ISSUE TITLE
Bug: Copy and paste includes background & text color

### ISSUE THREAD

**Issue by yuuminakamura** [facebook/lexical#2668]
When copy and paste from the website has color, it will copy & paste to the editor
![Screen Shot 2022-07-20 at 4 22 02 PM](https://user-images.githubusercontent.com/46723838/180098998-b4c29a47-1cf4-46b4-ae7f-cc5ecd912fec.png)

Lexical version

"@lexical/react": "^0.3.7",
  "lexical": "^0.3.7",

## Steps To Reproduce

1. copy contents from the website where has background & text color
2. paste in editor https://codesandbox.io/s/stoic-pike-wl21b0?file=/src/index.js
3. Text color and background color is copied from the website even though toolbar doesn't have this option

**Video**
https://user-images.githubusercontent.com/46723838/180098549-1aceb64b-54b0-4c85-8215-0de715139e57.mov

**Note:** playground Editor does not have this problem but I have very similar code to the rich text editor example and having the same issue.

## The expected behavior
text and background color should not be able to paste in the Editor if it doesn't allow those option. and paste as a plain text like playground editor

**Comment by acywatson** [comment]
Thanks for the thorough report - I just merged a PR for this. Will try to get this released ASAP.

Fixed by #2663 

Just waiting on a release.
