### ISSUE TITLE
Bug: Set unique id for each node

### ISSUE THREAD

**Issue by alirezahmz** [facebook/lexical#2684]
I am stuck in using your package, please help me   
How can I set a unique ID for each of the nodes in Lexical? The link below is an example of this work in Tiptop   
https://tiptap.dev/api/extensions/unique-id

**Comment by thegreatercurve** [comment]
We already create and store a unique `key` on each node instance, and each node class has to define a unique `type`. You should be able to access the keys with `node.getKey()`.

**Comment by tommy-taken** [comment]
![image](https://user-images.githubusercontent.com/130306508/232114883-f0cfc666-fa38-4af2-84b5-4e51994a0614.png)

This screenshot belongs to lexical file node tree which is downloaded from playground.lexical.dev. Nodes are not saved with their unique ids. 

How can we make that all nodes are saved with their unique ids?

**Comment by knsg16** [comment]
@thegreatercurve 
I have a same question, how can I set key for  text node ?
For example, using `createParagraphNode` .

**Comment by evskorobogatij** [comment]
I need function "Copy link" for block. Soon I need  id attribute in html and id attribute in json. 
How add id in json and html for all nodes?
