### ISSUE TITLE
Bug: lexical with Typescript components

### ISSUE THREAD

**Issue by alirezahmz** [facebook/lexical#2695]
When I try to create lexical components with ts I get these errors which I have uploaded in the image below.   
Point: When I change the file from tsx to js, I don't have these problems anymore.      
how can I fix this errors?    

  
![editor2](https://user-images.githubusercontent.com/64639961/180595289-cc8ca6ec-f3e4-4378-bcea-a90af9d87292.PNG)
![editor1](https://user-images.githubusercontent.com/64639961/180595293-175c35d2-18fc-47da-b9a7-6488e9338cc6.PNG)

**Comment by thegreatercurve** [comment]
You usually get these errors when using default instead of named imports. If you have something like the below: 
```
import RichTextPlugin from '@lexical/rich-text'
```
Change it to the below: 
```
import { RichTextPlugin } from '@lexical/rich-text'
```

**Comment by alirezahmz** [comment]
thanks.
