### ISSUE TITLE
Bug: Link selection in TextFormatFloatingToolbar [Playground]

### ISSUE THREAD

**Issue by andrewchmr** [facebook/lexical#2707]
Lexical version: 0.3.8

## Steps To Reproduce

1. Select text from link from right to left

Link to code example: https://playground.lexical.dev/

https://user-images.githubusercontent.com/43907473/180993481-dd000b55-d2e0-45b3-9111-b74fc9943d34.mov

## The current behavior
TextFormatFloatingToolbar is not shown

## The expected behavior
TextFormatFloatingToolbar should be shown the same way as when user selects text from left to right

**Comment by thegreatercurve** [comment]
Validated that this now appears to have been fixed.
