### ISSUE TITLE
Feature: Collapsible Headings

### ISSUE THREAD

**Issue by echarles** [facebook/lexical#2718]
It would be great to have collapsible headings (could be disabled by default), see for example the features showcased on https://bangle.dev/docs/examples/collapsible

![Untitled5](https://user-images.githubusercontent.com/226720/181210957-d9e7e9ad-0cae-48fc-a5b6-cc178b389d09.gif)

**Comment by echarles** [comment]
https://github.com/facebook/lexical/issues/1841 and recently merged https://github.com/facebook/lexical/pull/2592 may be related.

**Comment by fantactuka** [comment]
Since it's already listed I'll close
This as a duplicate to keep single issue open for discussions (#1841)

**Comment by echarles** [comment]
@fantactuka https://github.com/facebook/lexical/issues/1841 is just a toogle and any place of the document. This issue is about collabopsible heading (h1, h2,...).

It is not the same thing.

Could we reopen this?

**Comment by echarles** [comment]
@fantactuka This is still closed. I think a collapsible heading can build on a collapsible node, but the feature is different. The goal of this issue to to automatically show the heading in collapse mode (or not if disabled). Any question you have to reopen this?
