### ISSUE TITLE
Bug: Sometimes the cursor is in the wrong place.

### ISSUE THREAD

**Issue by flex-kwoncheol** [facebook/lexical#2726]
Lexical version: 0.3.8
Chrome version:  103.0.5060.114(Official build) (x86_64)

## Steps To Reproduce

1. Visit [demo page](https://codesandbox.io/s/lexical-plain-text-example-forked-kckvss) in a browser built on top of Chromium.
2. Choose a font from 'Pretendard', or 'Noto Sans KR'
<img width="419" alt="screenshot 2022-07-28 오후 4 47 07" src="https://user-images.githubusercontent.com/92355790/181450675-f2268382-8ab1-417a-8b4d-df873d68014c.png">

3. Type something into the editor. You must type in a language that supports word composition. (i.e. [cjk character](https://en.wikipedia.org/wiki/CJK_characters))

Link to code example: [codesandbox](https://codesandbox.io/s/lexical-plain-text-example-forked-kckvss)

## The current behavior

- If some fonts are loaded in a dynamic subset method and entered in a composition-based language(i.e. cjk character), the cursor is in the wrong place.
  - It doesn't happen in browsers built with engines other than Chromium.
  - It doesn't happen unless you're using a font that's split into subsets.
  - Occurs only when there is a word in compositing mode.

https://user-images.githubusercontent.com/92355790/181450860-cccda978-c1aa-4835-b909-746a94950e55.mov

## The expected behavior

- The cursor is always in the right place.

**Comment by tylerjbainbridge** [comment]
Closing for now as I was unable to repro. Please reopen if you're still encountering this.
