### ISSUE TITLE
Bug: Placeholder still present with 'inert' TextNodes, cursor will behave weird

### ISSUE THREAD

**Issue by dvmoritzschoefl** [facebook/lexical#2730]
Lexical version: 0.3.8

## Steps To Reproduce

1. Create 2 TextNodes inside a paragraph, append them to the root node
2. Set the mode of the nodes to 'inert'

Link to code example:

https://codesandbox.io/s/xenodochial-bas-2df8of?file=/package.json

![image](https://user-images.githubusercontent.com/77104411/181727647-22d9a6bf-7bb5-4b80-828c-18c68c73b114.png)

## The current behavior

- Wrong cursor position (on the most right position)
- Placeholder is still present

## The expected behavior
- Placeholder should not be present when there are TextNodes inside the root paragraph
- Cursor should behave predictable (between the textnodes?)

**Comment by thegreatercurve** [comment]
We are removing inert nodes completely as part of 0.4.0 so this should be fixed when this PR gets merged: https://github.com/facebook/lexical/pull/2421
