### ISSUE TITLE
Bug: Comments in isCollab=true doesn't appear to the correct thread

### ISSUE THREAD

**Issue by joypicar** [facebook/lexical#2740]
![image](https://user-images.githubusercontent.com/15082669/182027585-cc42099e-ceb8-4ea8-9a4f-8ae914368aaf.png)

## Steps To Reproduce

1. Go to: [https://playground.lexical.dev/?isCollab=true&collabEndpoint=wss://yjsdemo.fly.dev] and open it on separate browser
2. Create a comment from highlighted word. Create another one
3. Comment on the first thread
4. Refresh the page

## The current behavior
"this should be a reply to Squid" --> appears under the last thread

## The expected behavior
"this should be a reply to Squid" --> this comment should be under the 1st thread

**Comment by thegreatercurve** [comment]
Validated that this now appears to have been fixed.
<img width="333" alt="image" src="https://user-images.githubusercontent.com/7748470/204151405-4fb29e03-253f-424e-b0dd-0b6638fe93b4.png">
