### ISSUE TITLE
Bug: Cypress command `{selectall}` is not captured by Lexical

### ISSUE THREAD

**Issue by andrewchmr** [facebook/lexical#2748]
Lexical version: 0.3.8

## Steps To Reproduce

1. Write any cypress test that types text and then select it using `.type('{selectall}')`

Example: `cy.get('myText').type('It should be selected').type('{selectall}');`

## The current behavior

`$getSelection` would be `null`, but `window.getSelection()` would have proper data

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/43907473/182600664-d91a2b36-9430-4345-a9c8-167167ee9b4c.png">

## The expected behavior

Lexical should capture `selectall` command and update selection

**Comment by fantactuka** [comment]
It seems to work fine in cypress v10, and `selectall` command itself is also handled properly


https://user-images.githubusercontent.com/132642/183543568-4e34b0ee-00f5-45cb-9a32-f2e33bb1b579.mov

https://user-images.githubusercontent.com/132642/183543598-ae22093f-3415-44f7-bc06-4f2c50d2c41a.mov

**Comment by fantactuka** [comment]
Will close for now, feel free to reopen if have steps to reproduce
