### ISSUE TITLE
Bug: Cannot place cursor outside table

### ISSUE THREAD

**Issue by alinamusuroi** [facebook/lexical#2752]
When inserting a table if you delete everything after and before the table, the cursor remains inside the table and you can’t add anything else after or before. To exit the table, you need to move the cursor inside a cell and press the down arrow to move below the table — see video attached.

https://user-images.githubusercontent.com/44519061/182714077-2a9dd636-80bf-4f12-a86c-2ee11bfbd829.mov

## Steps To Reproduce

1. Insert a table
2. Delete everything after and before the table
3. Click outside the table

**Comment by tylerjbainbridge** [comment]
You can click to the right of the table, unfortunately this is a limitation with the current selection model and we are hoping to improve it soon.
