### ISSUE TITLE
More precise $insertBlockNode

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#2756]
Currently adding a block element like TweetNode or YouTube node will need the next best insertion point. While this is OK we can do better.

We can split the tree nodes to add the block immediately at that position (probably based on  https://github.com/facebook/lexical/pull/2322)

Caveat: We can't split table cells!

---

Follow up: you paste a, supposedly, top-level node like TweetNode, the HTML maps to it at least. The node is supposed to be top-level but is inserted at an arbitrary place in the tree. We should automatically fix/prevent this.

**Comment by gdelmas** [comment]
other things to consider:
- current insertion ignores (range) selection
  - usually pre selected text gets removed when inserting something new over it 
- for table cells, etc. insertation nearest possible would be great
  - ex. walk to next possible split point and insert there

**Comment by thegreatercurve** [comment]
@zurfyx Is this still an issue we want to consider?
