### ISSUE TITLE
Rectangular selection

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#2757]
Support/no support? Reuse NodeSelection? 

Do more research on: how to handle updates after selection takes place (i.e. collab)

https://user-images.githubusercontent.com/193447/182870039-7a8725a9-a0b8-45ca-9696-d0862d01f77a.mp4

Original suggestion by @gdelmas

**Comment by thegreatercurve** [comment]
@zurfyx Isn't this just GridSelection?

**Comment by thegreatercurve** [comment]
@zurfyx Can we close this if we're actively trying to reduce the number of selection states within the editor? No other editor I've seen includes this kind of selection.

**Comment by thegreatercurve** [comment]
Closing this as this is unsupported in other text editors.
