### ISSUE TITLE
Bug(playground): Escape key doesn't close the link editor

### ISSUE THREAD

**Issue by ahhshm** [facebook/lexical#2758]
Pressing the escape key doesn't close the link editor in the playground. The logic actually exists ([link](https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx#L324)) but it doesn't work, at least in Chromium 104.0.5112.79. It's probably a bug or even the intentional behavior of chromium because I don't have the same problem in Firefox.

**Comment by Shannon26** [comment]
Hello @ahhshm, I tried this on Microsoft Edge which runs on Chromium. But this seems to work for me. Pressing Esc keep close the link editor.

**Comment by nikmish1** [comment]
<img width="1164" alt="Screenshot 2022-09-12 at 2 49 15 PM" src="https://user-images.githubusercontent.com/30014840/189618177-4215ecc0-1b80-4772-ab32-e80076ed8da1.png">
The link editor doesn’t close on the press of the ESC button I tried in chrome and firefox.

**Comment by ahhshm** [comment]
> May I pick this issue?

Sure. Thank you.
