### ISSUE TITLE
Bug: CTRL+K to delete a line forward is behaving unexpectedly in Chromium

### ISSUE THREAD

**Issue by thegreatercurve** [facebook/lexical#2769]
Originally reported by @sophiebits in #2751

> I noticed that Ctrl-K (also an emacs keybinding) seems to behave incorrectly in Lexical as well. It should delete to (but not including) the nearest \n (or end of string), or delete one \n if you're right before one. In Lexical it seems to be also deleting the newline and some of the characters from the next line, depending on your cursor position when pressing it.

Lexical version: 0.3.8

## Steps To Reproduce

1. Open Lexical Playground in Chrome.
2. Select the middle of a line of text.
3. Press CTRL+K.

## The current behavior

It should delete up until the end of the line.

## The expected behavior

It deletes up more character on th next line, up until the current start offset of the current line.

https://user-images.githubusercontent.com/7748470/183055092-460d1eec-61ea-406a-82ea-9e84291aa4a5.mov

**Comment by thegreatercurve** [comment]
I did some investigation into this bug.

I can only replicate the issue on Chromium. It works as expected on Firefox and Safari. 

It looks like a bug with Chromium, or our framework is doing something that exposes some kind of faulty logic within Chromium.

The `beforeInput` handler fires with the `deleteHardLineForward` event, but when we get the target ranges [here](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalEvents.ts#L334), the `endOffset` is either the same or one less than the `startOffset`. This causes deletion up until the end of the current line, plus the `startOffset` applied to the next line.

![image](https://user-images.githubusercontent.com/7748470/183055562-98880d59-14ad-4705-b0c0-9db3b5645fd8.png)

The target Range should look like this (from Firefox). Note that this fires a different event as well. 

<img width="900" alt="image" src="https://user-images.githubusercontent.com/7748470/183054901-f9eaf1a7-f0b6-495d-9850-01a6b56bff2d.png">

In other editors (Quill, ProseMirror) this works as expected on Chrome, so it suggests there is something wrong with how Chromium parses the HTML that Lexical generates to calculate the ranges.

The problem though is if I copy/paste the HTML into another blank `content-editable`, it again works as expected, so there must an additional factor within Lexical which causes the bug. 

Taking a break from it for the moment, but the search continues...

**Comment by trueadm** [comment]
A year ago, we found a bug in Chromium to do with `getTargetRanges` where the offsets were completely wrong for line selection deletions. I thought the fix we had was landed, but maybe it didn't? We should check to see if the offset and node from `getTargetRanges` in Chromium is still bugged.

**Comment by thegreatercurve** [comment]
@trueadm I did spot that issue last night, and I wondered if it was your report. 

So, this adds the weirdness, but I can't replicate the `deleteHardLineForward` issue in the above example code. It behaves correctly with the correct ranges (ignore all the UI apart from the contenteditable: 

https://user-images.githubusercontent.com/7748470/183069774-96cc1edb-f635-4423-95b9-5c043cd79d25.mov

This goes back to my follow up point: 
> The problem though is if I copy/paste the HTML into another blank contenteditable, it again works as expected, so there must an additional factor within Lexical which causes the bug.

I might see if I can try to reproduce a minimal reproducible example by stripping out various listeners and observers.

**Comment by thegreatercurve** [comment]
Finally got around to testing this a bit more, and this is definitely an issue with Chromium.

It's a false positive in that it works as expected in the browser, but the returned `StaticRanges` are from `getTargetRanges` is incorrect. 

I've [submitted a bug to Chromium here](https://bugs.chromium.org/p/chromium/issues/detail?id=1360253) which should track the issue. 

Closing this issue so we can use the Chromium tracker instead.
