### ISSUE TITLE
Bug: DecoratorNodes content should be collaborative

### ISSUE THREAD

**Issue by echarles** [facebook/lexical#2779]
I am not sure if this is a bug or a feature request, so put it as bug for now as a user.

Lexical version: 0.3.8

## Steps To Reproduce

1. Run the playground in collaborative mode
2. Insert a decorator node, eg an equation or a sticky node
3. Change the content of that node

## The current behavior

The change of the content of the decorator nodes are not collaborative. This is probably logical from a developer perspective based on the current code (nothing is forseen to propagate the changes), but as a user, this is confusing.

## The expected behavior

The user would expect the content change to be collaborative.

![Untitled9](https://user-images.githubusercontent.com/226720/183277782-d58ddf95-7d11-4e66-b3c6-70dc152c0c62.gif)

![Untitled5](https://user-images.githubusercontent.com/226720/183277784-ba7adc83-7bca-407b-a4e7-33a2ebd61006.gif)

**Comment by trueadm** [comment]
This used to work, so it's a recent regression. It's likely to do with changes to nested editors.
