### ISSUE TITLE
Bug: Space between paragraph nodes selected in Safari

### ISSUE THREAD

**Issue by AaronGazzola** [facebook/lexical#2797]
In the Lexical playground in Safari 15.3, the space between paragraph nodes can be selected. The Tree View Plugin indicates that both paragraphs on either side of the highlighted space is selected but text formatting can't be applied.

Lexical version: 0.3.8

## Steps To Reproduce

1. Navigate to the lexical playground in Safari
2. Place the cursor at the beginning of a paragraph node, immediately before the first character.
3. Click and drag the selection to the end of the paragraph node above. 
4. The space between the paragraph nodes should be selected
![image](https://user-images.githubusercontent.com/75453092/183612402-6caf26a3-0158-4848-b0c3-bd187d5ca653.png)

Link to code example: playground.lexical.dev

## The current behavior
Space between paragraph nodes can be selected in Safari

## The expected behavior
Content outside of nodes should not be selected.

**Comment by fantactuka** [comment]
> The Tree View Plugin indicates that both paragraphs on either side of the highlighted space is selected but text formatting can't be applied.

It's TreeView not being clear enough here, if you scroll it down it'll show selection anchor and focus values. The anchor will be the end of first paragraph text, focus with be start of second paragraph text node. Hence nothing can be formatted as no text selected (although the way Safari shows selection is misleading)

**Comment by AaronGazzola** [comment]
> > The Tree View Plugin indicates that both paragraphs on either side of the highlighted space is selected but text formatting can't be applied.
> 
> It's TreeView not being clear enough here, if you scroll it down it'll show selection anchor and focus values. The anchor will be the end of first paragraph text, focus with be start of second paragraph text node. Hence nothing can be formatted as no text selected (although the way Safari shows selection is misleading)

Thanks @fantactuka, I was able to hide the text format floating toolbar when only a line feed character is selected, although I haven't found a solution to disable the user select between nodes in safari without disrupting other selection behavior in the editor.

**Comment by thegreatercurve** [comment]
This appears to be a small issue with how Safari handles range selections between sibling elements. Removing `position: relative` from the paragraphs should fix the issue.

**Comment by AaronGazzola** [comment]
> This appears to be a small issue with how Safari handles range selections between sibling elements. Removing `position: relative` from the paragraphs should fix the issue.

This worked for me! Thanks @thegreatercurve 👍

**Comment by thegreatercurve** [comment]
Related bug report for Safari: https://bugs.webkit.org/show_bug.cgi?id=244780
