### ISSUE TITLE
Bug: Invalid nodes nesting

### ISSUE THREAD

**Issue by fantactuka** [facebook/lexical#2800]
There's an issue with copy-pasting when heading can end up nested into paragraphs. Same applies to all other sorts of invalid nesting (code block inside paragraph or list item, etc). Although we have several places assuming paragraph, heading, quote, code and list are either root-level children or nested into table cell, it's not enforced in any way and you can replicate wrong nesting either by copy-pasting such content or by creating it via nodes api:

```js
// Clipboard
<p><h1>Heading within paragraph</h1></p>
<ul>
  <li><h1>Heading within list</h1></li>
</ul>

...

// Api
$createParagraphNode().append(
  $createHeadingNode('h1').append(
    $createTextNode('Heading within paragraph')
  )
);
```

**Comment by zurfyx** [comment]
Yup, I wonder if we should brainstorm a generic solution. This is the same for many others like copy-pasting links inside links.

**Comment by fantactuka** [comment]
Transformers can help here, but then will it be a plugin or core-defined transformer. Having it as a plugin means it's optional, while some of our code can be broken with this nesting. Add transformer in core sounds better, but then you can easily by-pass it with `update(..., {skipTransformers: true})` and unintentionally break nesting

**Comment by acywatson** [comment]
For copy paste, we probably need a system for sanitizing the incoming tree structure anyway - we have talked about this in the past. We can define invariants and try to apply heuristic remediations when we encounter them. It's still possible, of course, to write code that imperatively creates a structure that will crash the Editor - even in the case of copy+paste once we make it possible to override core node importHTML behavior.

One big issue here is that we don't really articulate a schema or any rules around this. There's no real intrinsic reason why we can't or shouldn't support nesting these elements - we just have some assumptions in our code that make it not work at the moment. If we add something to the core, it makes it so no Editor built on Lexical could handle this. I think we need to see if we can make it possible to handle these cases.

**Comment by DaniGuardiola** [comment]
Regarding the sanitization, what about a [normalization API like slate's](https://docs.slatejs.org/concepts/11-normalizing)? I've been looking for something like this myself, and it seems like it would benefit the core too.

About the problem of limiting functionality when putting this in the core, I guess it ties to the overarching question of how to make it more extendable and customizable. If there was a good system for that in place (I don't know how that would look like), it wouldn't be a big issue, and lexical could have sane defaults while still allowing for users to override and extend those defaults at will.

**Comment by acywatson** [comment]
> Regarding the sanitization, what about a [normalization API like slate's](https://docs.slatejs.org/concepts/11-normalizing)? I've been looking for something like this myself, and it seems like it would benefit the core too.
> 
> About the problem of limiting functionality when putting this in the core, I guess it ties to the overarching question of how to make it more extendable and customizable. If there was a good system for that in place (I don't know how that would look like), it wouldn't be a big issue, and lexical could have sane defaults while still allowing for users to override and extend those defaults at will.

This is really interesting - especially this part:

https://docs.slatejs.org/concepts/11-normalizing#built-in-constraints

 We actually share the majority of these constraints and it would be great to document them. I like the idea of generally being able to declare constraints or invariants and remediations for them through some API like this.

**Comment by GermanJablo** [comment]
Please take a look at my last comment at https://github.com/facebook/lexical/issues/3833#issuecomment-1777942295

Do you think it solves this issue?

**Comment by etrepum** [comment]
I think generally speaking we should have the plugin associated with a node register a transform that enforces any required invariants, e.g. what was done for #6914. It might be worthwhile to write more documentation and provide more utility functions to make this easier, e.g. a declarative "schema" that can be "compiled" to a transform, and possibly something that also compiles to an importDOM after function just to make sure that more of that work happens eagerly. I think more targeted issues for those sorts of things would be better than just having a long-standing issue that's hard to close (except as wontfix, as I'm doing now) and very quickly gets lost in the nth page of issues.
