### ISSUE TITLE
Feature/question: unclear how to customize official plugins

### ISSUE THREAD

**Issue by DaniGuardiola** [facebook/lexical#2801]
## Problem

We're building our editor with Lexical, and we love both the developer experience and the fact that it ships with a nice suite of official plugins.

That said, it's unclear how these plugins are supposed to be customized and extended. There is a very promising thread already discussing how to decouple nodes and plugins, so that devs can extend a node and replace the original ones. Then, plugins will make use of the extended plugin and still work (https://github.com/facebook/lexical/issues/1262), and that's definitely very helpful.

However, there are still questions around how to customize other areas in plugins. Take the rich text plugin for example. We want our editor to support most of the functionality, but we don't want to support some things like headings and text styles like strike-through.

For headings, we're currently just not registering the heading node, and that seems to work for the most part. But there is a possibility that something will break because of that. In fact, when the markdown shortcuts plugin is used, it throws an error when trying to add a heading that way (basically typing `#` and hitting space), because the heading node is not registered.

And we're not sure what to do about strike-through at all.

Of course, a solution is to just fork the plugins and customize them to our taste, but that seems overkill and introduces some complications like having to keep up with the upstream code and so on.

## Potential solution

A solution that I think would work is simply accepting parameters on the official plugins.

These parameters could be classified into two main types: configuration and "hooks".

- Configuration parameters allow devs to specify some options that the plugin will internally take into account. For example, for the rich text plugin, this could be a list of supported block styles, text styles, etc. Other examples could be enabling/disabling/customizing keyboard shortcuts, disabling some behaviors (like indent on tab), etc.
- "Hooks" allow devs to override parts of the plugin logic in a more liberal way, basically replacing what happens when the plugin tries to do X or Y, maybe with access to the original behavior through a callback that the user-provided function can still use in their custom logic.

I think something like this would be an amazing way to offer some customization without forcing users to either fork the plugin or use more "patchy" approaches like registering commands with lower priority that stop other commands on the chain from working (through returning true).

**Comment by echarles** [comment]
> We want our editor to support most of the functionality, but we don't want to support some things like headings and text styles like strike-through.

https://github.com/facebook/lexical/pull/2686 is maybe a step to that, you can read there `This new features flag would allow developers to control the node behavior and would be up to the owner to maintain and support toggling new features.``

https://github.com/facebook/lexical/discussions/2739 discussion may also be related, as discussing the decoupling of Nodes and Plugins, which may be against your proposal (not sure).

I am interested to hear more feedback on your proposal, I am just too new to Lexical to comment on that.

**Comment by fantactuka** [comment]
> For headings, we're currently just not registering the heading node, and that seems to work for the most part. But there is a possibility that something will break because of that. In fact, when the markdown shortcuts plugin is used, it throws an error when trying to add a heading that way (basically typing # and hitting space), because the heading node is not registered.

Depending on a plug-in we can have props to its react wrapper, e.g. 
LexicalMarkdownShortcutsPlugin accepts list of transformers that you can modify to exclude headings or strike through shortcuts (see shortcuts section [here](https://lexical.dev/docs/api/lexical-markdown))

**Comment by DaniGuardiola** [comment]
@fantactuka thanks for your reply! Great to know about the markdown plugin options, we'll use that.

Few questions:

- What would be the right approach to exclude nodes from the rich text plugin? Just not register them?
- How would I exclude styles like strikethrough?
- How do I disable or customize the indenting behavior (on tab)?

And if any of these things aren't possible at the moment, then consider this a feature request for those options :)

I'll update the thread with new use cases as we keep building our editor.

**Comment by acywatson** [comment]
One thing we have been discussing is using the Command system to trigger node insertions instead of using the $create*Node functions directly. If we shifted to this model, you could intercept the hypothetical CREATE_HEADING_NODE command and no-op it.

```
editor.registerCommand(HYPOTHETICAL_CREATE_HEADING_NODE, () => {
  // stop propagation to other command listeners.
  return false;
}, COMMAND_PRIORITY_HIGH)
```

We could probably do something similar with strikethrough - you could intercept FORMAT_TEXT_COMMAND, check for strikethrough, and just not add that format. The current issue is with copy+paste - the logic for importing text formats from HTML is in the core and doesn't use commands, so someone would still be able to paste in a text with strikethrough formatting. We could probably fix that using a transform:

```
editor.registerNodeTransform(TextNode, () => {
    // check format and remove strikethrough if present.
});
```

This is a lot of work to disable a feature, though.

The issue I have with feature flags is that I don't think they scale super well. You end up with a bunch of conditional logic all over the core for enabling and disabling various functionality and it will just keep growing (maybe there's an acceptable upper bound on that, not sure).

**Comment by DaniGuardiola** [comment]
> The issue I have with feature flags is that I don't think they scale super well. You end up with a bunch of conditional logic all over the core for enabling and disabling various functionality and it will just keep growing (maybe there's an acceptable upper bound on that, not sure).

@acywatson that's fair, but I still think the ability to opt in or out to the basic building blocks is important enough to grant feature flags. E.g. at least blocks and text styles. I do see the logic in not going much further past that, and that shouldn't be an issue as long as these high level flags exist, since if you want to *customize* something (rather than just disabling it), then it's as easy as disabling it and re-implementing it yourself.

My biggest gripe with these (otherwise amazing) plugins, especially rich text, is that currently it's all or nothing, and the only way to achieve what you want is to "patch it" by doing what you said (no-oping stuff or undoing with node tranforms), which feels like a big workaround for something that IMO is a very reasonable use-case.

**Comment by fantactuka** [comment]
> My biggest gripe with these (otherwise amazing) plugins, especially rich text, is that currently it's all or nothing, and the only way to achieve what you want is to "patch it" by doing what you said (no-oping stuff or undoing with node tranforms), which feels like a big workaround for something that IMO is a very reasonable use-case.

It's possible to adjust it with relatively low cost:
- mutation listener or transformer to replace created heading nodes with paragraph
`heading.replace($createParagrapNode().append(...heading.getChildren()))`
- transformer to undo strikethrough 
`if (textNode.hasFormat('strikethrough')) textNode.toggleFormat('strikethrough')`
- command listener to prevent indentation
`registerCommandListener(INDENT_CONTENT_COMMAND, () => true, COMMAND_PRIORITY_LOW`

In a very extreme scenario (which very few apps would have) it's possible to construct analog of rich text plugin and listen to a smaller subset of commands. In other cases you can add couple transformers and keep using all built-ins

**Comment by DaniGuardiola** [comment]
Fair enough, thanks for the guidance. I'll experiment with this and see how it goes. Something I'm still worried about with this approach (likely due to ignorance since I'm new to lexical) is that some edge case might be missing that could be the cause of hard-to-debug bugs down the road, especially as more plugins with complex interactions are added. But, fair enough if that's all it takes.

Something that I guess could be helpful is more extensive documentation on the rich text editor plugin, since at the moment devs like me have to look at the plugin code (or ask here as I did) and go semi-deep to understand how to pull this off. I think it'd make me more confident if I could see some documentation on what the plugin offers (e.g. in terms of nodes, registered commands, etc), and it'd be just perfect IMO if it even provided guidance on disabling some behavior with these methods. 

All that said, I think it's awesome that I can nerf the plugin with these simple adjustments, I think it speaks to the great API design of Lexical, keep it up folks :)

**Comment by acywatson** [comment]
> It's possible to adjust it with relatively low cost:
>
>mutation listener or node transformer to replace created heading nodes with paragraph
>heading.replace($createParagrapNode().append(...heading.getChildren()))

@fantactuka - good point.

> Something I'm still worried about with this approach (likely due to ignorance since I'm new to lexical) is that some edge case might be missing that could be the cause of hard-to-debug bugs down the road, especially as more plugins with complex interactions are added

This is also something we are thinking about and is a big part of the reason we haven't yet done this:

>  and it'd be just perfect IMO if it even provided guidance on disabling some behavior with these methods.

The truth is, we tried to design an implement very powerful flexible APIs that can technically cover the majority of use cases, but our point-of-view on exactly how they should be used and how we should recommend that they be used is evolving. We're still figuring out some of this for ourselves - how to keep the API surface simple and comprehensible while still enabling flexibility/extensibility.

I think there's a middle ground though, where we could at least give some hints about where to look for this kind of override functionality in the docs, even if we aren't yet ready to explicitly recommend that everyone do it this way. 

Would be interested in your feedback as you progress here.

**Comment by acywatson** [comment]
Closing this for now, as we have a solution and a ref to the discussion in #1262
