### ISSUE TITLE
Link text editing difficult/frustrating

### ISSUE THREAD

**Issue by gdelmas** [facebook/lexical#2805]
Text editing on links is currently quite difficult, as when selecting the whole link text, it can not be replaced edited

https://user-images.githubusercontent.com/2949816/183913959-f9e468c3-f465-4737-ba3d-93af397ce0b2.mov

I propose to simplify link editing like this:

https://user-images.githubusercontent.com/2949816/183913420-2eb65aa7-0076-46a1-80b1-f0835d300d9f.mov

cc @zurfyx

**Comment by acywatson** [comment]
I like this idea - I think this is the standard.

Bonus point: get rid of that weird behavior in the link edit toolbar where trying to focus the input navigates you to the URL.

**Comment by thegreatercurve** [comment]
Descoping this for the moment as I think the functionality of the Link Nodes in the playground is useful for helping us to debug any related issues. I think for independent surfaces, this could be quite easily added.

**Comment by anilanar** [comment]
Hey @thegreatercurve. Any hints on how one could implement the proposed change in user-land?
