### ISSUE TITLE
Bug: xss vulnerability within links?

### ISSUE THREAD

**Issue by maxhelsel** [facebook/lexical#2806]
Lexical version: lexicon playground 

## Steps To Reproduce

1. type a word
2. highlight word
3. click add link icon
4. type anything in there, something like 'javacript:alert('xss')'

seems you can enter anything inside the link prompt

![Screen Shot 2022-08-10 at 10 47 43 AM](https://user-images.githubusercontent.com/46327674/183936846-04884c29-10e1-4588-8198-6304c0cb0e86.png)

Link to code example: [https://playground.lexical.dev/](https://playground.lexical.dev/)

**Comment by acywatson** [comment]
Yea, we should probably have some basic, but configurable, validation here. Also might be nice to set the rel attribute to head off reverse tabnabbing.

Seems like a good first issue :)

**Comment by heesungjang** [comment]
I would love to work on this issue! Could you please assign this to me if not assigned to anybody yet? thanks!
