### ISSUE TITLE
Bug: Decorator node mutation moves focus to editor under certain circumstances

### ISSUE THREAD

**Issue by adri1wald** [facebook/lexical#2809]
Lexical version: 0.3.8
React version: 17 (interestingly it doesn't happen with 18)

## Steps To Reproduce

1. Clone https://github.com/adri1wald/decorator-mutation-focus-stealing-repro
2. Follow steps in readme

## The current behavior

Some DOM mutations in the decorator node can cause focus to move from the equation input to the editor.

## The expected behavior

No DOM mutations in the decorator node should cause focus to move from the equation input to the editor.

**Comment by thegreatercurve** [comment]
@adri1wald would you mind re-testing to see if this is still an issue? This appears to be fixed when I try to repro in Chrome. 

![image](https://user-images.githubusercontent.com/7748470/203841336-08ddfe25-e9de-47e1-a2de-9a131e26dfef.png)

**Comment by thegreatercurve** [comment]
Closing as this now appears to be fixed.
