### ISSUE TITLE
Bug: parsing markdown loses empty lines

### ISSUE THREAD

**Issue by Santehnikua** [facebook/lexical#2815]
Lexical version: 0.3.8
lexical playground as of 2022-08-11

Test Environment (can reproduce):
- Mozilla Firefox 104.0b8
- Microsoft Edge 104.0.1293.47
- Windows 11 22000.856

## Steps To Reproduce

1. Add two or more empty lines in the middle of text
2. Convert text to markdown using "Convert from markdown" button
3. Convert back using "Convert from markdown" button

Link to code example:
 It looks like the issue is in [$convertFromMarkdownString](https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-markdown/src/index.ts#L68)
https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-markdown/src/index.ts#L68-L74 because using export and import lexical files work well and empty lines remain.

## The current behavior

After converting from markdown, all empty lines disappear.
![ezgif-5-8deddd0449](https://user-images.githubusercontent.com/104627137/184105227-6467e648-5bb7-4fb2-a5dc-7ca1c754b68e.gif)

## The expected behavior
After converting from markdown, all empty lines remain.

**Comment by fantactuka** [comment]
It is a common behavior, e.g. see [commonmark](https://spec.commonmark.org/dingus/?text=%23%23%20Try%20CommonMark%0A%0AYou%20can%20try%20CommonMark%20here.%20%20This%20dingus%20is%20powered%20by%0A%5Bcommonmark.js%5D(https%3A%2F%2Fgithub.com%2Fcommonmark%2Fcommonmark.js)%2C%20the%0AJavaScript%20reference%20implementation.%0A%0A%0A%0A%0AAnother%20paragraph)

We can add support of explicit `<br>` tag, but otherwise empty lines are not preserved

**Comment by Santehnikua** [comment]
Maybe it makes sense to consider two empty lines as a empty paragraph?

**Comment by fantactuka** [comment]
I agree it's useful to keep empty lines (it's how it was in the beginning), but as a default behavior we should try to follow spec

**Comment by Santehnikua** [comment]
Yes, of course, it is necessary to follow the standards.
It seems that the whole point is that the lexical offers much wider possibilities than markdown, due to which losses are obtained with such conversions.
Since this is not a bug after all, i suggest closing the issue, but it would be nice to get some additional options that can be configured to meet the needs of certain projects.
Thank's

**Comment by moughxyz** [comment]
Hmm, this behavior is quite weird indeed.

This text:

```
Hello

World
```

maps to

```
Hello
World
```

I think GHF markdown handles this better and more naturally. Commonmark's handling seems unnatural to me. In any case, here is a transformer that seems to work for me:

```typescript
const NewLineTransformer: TextMatchTransformer = {
  dependencies: [ParagraphNode],
  export: () => {
    return null
  },
  replace: (textNode) => {
    if (!textNode) {
      return
    }

    const p = $createParagraphNode()
    textNode.insertAfter(p)
  },
  importRegExp: undefined as never,
  regExp: undefined as never,
  trigger: '\n',
  type: 'text-match',
}
``` 

However the only way it works is if I force `importRegExp` and `regExp` to undefined, which is undesired. @fantactuka would you happen to know of a regex expression that would work? I've tried a while bunch of them but nothing quite worked (like `^[\n\r]s/`).

**Comment by geisterfurz007** [comment]
I think I might have found a workaround with this:

```ts
const keepNewlines: ElementTransformer = {
  replace: (textNode) => {
    const br = $createLineBreakNode();
    textNode.replace(br);
  },
  regExp: /^$/,
  type: 'element',
  dependencies: [],
  export: () => '',
};
```
Then use that in your `$convertFromMarkdownString` / `$convertToMarkdownString`. I also had to do some pre-processing to make things work, since the export still creates two linebreaks per MD linebreak:

```ts
const newlinePatchedValue = storedValue.replace(/\n\n/g, '\n');

editor.update(() => {
  $convertFromMarkdownString(newlinePatchedValue, [...transformers, keepNewlines, keepIndentLevelExport]);
});
```
`storedValue` is the previous output of `$convertToMarkdownString` that you stored in a database for example.

**Comment by geisterfurz007** [comment]
fwiw, this appears to be planned in #2033
