### ISSUE TITLE
Feature request: Shift-tab on un-nested list-item splits it out of the list

### ISSUE THREAD

**Issue by Awjin** [facebook/lexical#2820]
This would be similar to the current behavior when pressing ENTER on an empty list-item:

https://user-images.githubusercontent.com/3211874/184264686-4d52e9a7-c78f-4dcb-b011-711ee9448b76.mov

<br/>

Proposed shift-tab behavior:

https://user-images.githubusercontent.com/3211874/184264765-873e07bf-5777-465e-a89c-f8dc162d66a1.mov

**Comment by fantactuka** [comment]
You can do it as a plugin with that listens to `OUTDENT_CONTENT_COMMAND`, smth like:

```js
editor.registerCommand(OUTDENT_CONTENT_COMMAND, () => {
  editor.update(() => {
    const selection = $getSelection();
    if ($isRangeSelection(selection) && selection.isCollapsed()) {
      const closestElement = $getNearestBlockElementAncestorOrThrow(selection.anchor.getNode());
      if ($isListItem(closestElement) && closestElement.getIndent() === 0)  {
        $wrapLeafNodesInElements(selection, () => $createParagraphNode());
      }
    }
  });
}, COMMAND_PRIORITY_LOW)
```

**Comment by Awjin** [comment]
Thanks for the example code! I currently have something similar implemented.

However I would like to propose this as default behavior of the List plugin, because it is generally expected UX when tabbing/shift-tabbing a list item. WDYT?

**Comment by thegreatercurve** [comment]
> However I would like to propose this as default behavior of the List plugin, because it is generally expected UX when tabbing/shift-tabbing a list item. WDYT?

@Awjin We're going to remove all of the default tab shortcuts as part of the 0.4.0 release (#2855). We've found that having it in core degrades accessibility when keyboard users need to use TAB and SHIFT+TAB to focus in and out of the editor instead.

**Comment by acywatson** [comment]
Since we're going to actually give users the option to add this behavior back with a plugin when we remove the defaults, I think the logic you're asking for could live there. I suspect most people will add that plugin back in, so the effect would be the same.
