### ISSUE TITLE
Bug: lexical collaborative playground example not working locally

### ISSUE THREAD

**Issue by 6peterlu** [facebook/lexical#2821]
I get the console error
```
WebSocket connection to 'ws://localhost:1234/playground/0/main' failed: WebSocket is closed before the connection is established.
```

when I run `npm run dev` locally on the lexical repo.

Lexical version: git SHA `26a4ed275db9a4258f296fcdc32b281376ab3f40`

## Steps To Reproduce

1. `HOST=localhost PORT=1234 npx y-websocket`
2. Clone repo
3. `npm install`
4. `npm run dev`
5. Use settings to switch collaboration on.

Link to code example:
N/A

## The current behavior
WS connection errors

## The expected behavior
Collaboration example successfully uses local WS server.

I'm sure this is working for most people so would like to understand what to try during debugging. I am running locally on Mac.

**Comment by echarles** [comment]
You have to run `npm run start` (not dev)

**Comment by 6peterlu** [comment]
got it, that works! thanks @echarles
