### ISSUE TITLE
Bug: cjk words are composed in an incorrect way on iOS devices

### ISSUE THREAD

**Issue by flex-kwoncheol** [facebook/lexical#2824]
Lexical version: 0.3.9

## Steps To Reproduce

1. Visit [playground.lexical.dev](https://playground.lexical.dev/) **from iOS device**. 
2. Enter something in Korean or any other [cjk character](https://en.wikipedia.org/wiki/CJK_characters).

 

https://user-images.githubusercontent.com/92355790/184302793-85cfe8a8-bd83-4e77-8eb5-d2238329abed.MP4

Link to code example:

## The current behavior

- It composes a Korean word in an incorrect way.
     - For example, when you type `ㅇ` and then `ㅣ`, it should be `이`, but it becomes `ㅇ이`.
     - In addition, if there is a character following it, the character is deleted. 

## The expected behavior

- It composes a word in a correct way.
- It doesn't delete a character following it.

**Comment by flex-jonghyen** [comment]
I found similar issue (https://github.com/codemirror/view/pull/30) in other project.
On iOS, MutationObserver event give `composing` to `false`.

**Comment by flex-jonghyen** [comment]
I recorded 2 videos at [Compotision Event on MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event).

One was recored on Mac OS 12.3.1, Chrome 104.0.5112.79, Safari 15.4(17613.1.17.1.13).
Another was recored on iOS 15.6, Chrome 104.0.5112.88.

On Mac, composition event occur well. But iOS did not.



https://user-images.githubusercontent.com/97939463/184335328-dab47896-db09-4f62-aef4-14085675331d.mov


https://user-images.githubusercontent.com/97939463/184335354-d51ad14e-4f90-4104-9737-36e65b52724a.MP4

**Comment by flex-kwoncheol** [comment]
> These seem like WebKit iOS issues. Please note that chrome on iOS uses WebKit too.

Does that mean Lexical doesn't address this issue?

**Comment by trueadm** [comment]
Not at all, I'll take a deep dive into this issue when I'm back from parental leave. :)

**Comment by flex-kwoncheol** [comment]
That's sweat! Thank you 😁

**Comment by flex-kwoncheol** [comment]
@trueadm
I'd like to address this issue as our team needs to release a feature that requires Lexical.
It would be very helpful If you could give me some information like where to start 😄

**Comment by trueadm** [comment]
Looking into this more, it actually has nothing to do with composition. It's because we don't handle the `deleteContentBackward` event with data being `null` in Safari. I'll have a fix up later today.
