### ISSUE TITLE
Feature: Standard Element toggling command for all Element Nodes (including custom)

### ISSUE THREAD

**Issue by cobbvanth** [facebook/lexical#2834]
All element nodes should have a standardized way of being toggled via a toolbar, through a single command. This would following the basic outline of the toggleLink() function in the following file:https://github.com/facebook/lexical/blob/7831da750262ffb5a965e2e846f03c92af65158a/packages/lexical-link/src/index.ts#L341

It is extremely cumbersome to write custom logic for toggling element nodes and it would be fantastic on the user facing side if all element nodes had the same, uniform toggle behavior.

**Comment by fantactuka** [comment]
It’s not exactly a command, but can be often used https://github.com/facebook/lexical/blob/7831da750262ffb5a965e2e846f03c92af65158a/packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx#L589

With command is it’s not always same: for heading and paragraph you can just append existing children to a new block. For code block you only need it’s text content but not nested nodes. For lists it’s even more complicated, same for inline elements like links

**Comment by cobbvanth** [comment]
This is definitely a great starting point, an inline version of it would probably cover 90% of use cases, including links

**Comment by thegreatercurve** [comment]
Thanks for the idea! If you want to add a PR to add in this functionality, please feel free. We find `wrapLeafNodesInElements` to be enough for our own needs internally. Closing this just for the moment.
