### ISSUE TITLE
Bug: flow types not exported to TS definitions.

### ISSUE THREAD

**Issue by richburdon** [facebook/lexical#2844]
Lexical version:

```
    "@lexical/react": "~0.3.11",
```

## Steps To Reproduce

This seems to be a regression: TS types are missing.

```
import {
  ProviderAwareness, ProviderFactory, UserState
} from '@lexical/react/LexicalCollaborationPlugin';
```

## The current behavior

`TS2305: Module '"@lexical/react/LexicalCollaborationPlugin"' has no exported member 'UserState'.`

## The expected behavior

Types were previously exported, but currently the types defined in `LexicalCollaborationPlugin.js.flow` are missing from `LexicalCollaborationPlugin.d.ts`

**Comment by thegreatercurve** [comment]
`ProviderAwareness` and `UserState` are now exported from `lexical-yjs`. It's an error for it to still be in Flow.

We removed `ProviderFactory`, but can create your own version of the type using something like the below:

```tsx
import {WebsocketProvider as ProviderFactory} from 'y-websocket';

type ProviderFactory = (
  id: string,
  yjsDocMap: Map<string, Doc>,
) -> WebsocketProvider
```
