### ISSUE TITLE
No getting started with vanilla JS on the README.md

### ISSUE THREAD

**Issue by hkiame** [facebook/lexical#2867]
I can't find getting started with vanilla JS on the README.md. Is it possible to add that?

**Comment by acywatson** [comment]
We can probably add something to the README, but is there some reason why you can't use this guide?

https://lexical.dev/docs/getting-started/quick-start

**Comment by thegreatercurve** [comment]
Closing this for the moment, as I think providing this info on the website is enough.

**Comment by hkiame** [comment]
> We can probably add something to the README, but is there some reason why you can't use this guide?
> 
> https://lexical.dev/docs/getting-started/quick-start

No, there is no reason.  A quick introduction on how to get started with vanilla js on the README might be helpful though.

**Comment by tensiondriven** [comment]
For me, and probably many others, the vanilla getting started guide is *not* enough.  It shows how to set up an editor, but doesn't give an example of registering commands / plugins.

As someone coming into Lexical who wants to use it without React, seeing the claim that "Lexical is framework agnostic", but finding no clear way to get started with Vanilla JS is frustrating.  If the Vanilla Getting Started Guide had just a little more content, where it showed how to register a handful of plugins, much like the React getting started, my concern would be alliviated.

I know that React is more popular and I don't expect vanilla js documentation to take priority, but I would at least like it if the docs for vanilla JS were at parity with the docs for the React bindings.

**Comment by barbalex** [comment]
Personally I managed to set up lexical in react just fine.

Building a new project with qwickjs, I now depend on the vanilla docs.

The vanilla docs only give me a textarea with no ui.

After a few frustrating hours trying to get things set up and working I guess I will give up 😭

Please please please get the vanilla docs on par with the react ones.
