### ISSUE TITLE
Feature: Upload file (pdf, epubs, anything)

### ISSUE THREAD

**Issue by adelin-b** [facebook/lexical#2871]
It would be nice to be able to upload files and download them from lexical (as an classic attachments to a message)

**Comment by thegreatercurve** [comment]
@adelin-b this is definitely possible, but I'm not sure what we could add to the core library to facilitate this functionality, as a lot will depend on your backend architecture. 

We do have an example in the playground which is an image uploader, but that just handles the data on the client. 

Hopefully that can give you some useful ideas.

**Comment by adelin-b** [comment]
I think an configuration that take  "upload, delete, get" functions and just call those when user drop or delete files would make the job.
