### ISSUE TITLE
Bug: Cannot init a list when creating new editor

### ISSUE THREAD

**Issue by ImSingee** [facebook/lexical#2874]
Lexical version: 0.3.11

## Steps To Reproduce

1. Open https://codesandbox.io/s/lexical-rich-text-example-5tncvy (the link is from the repository's README) and create a fork
2. add `editorState: '{"root":{"children":[{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Visit the ","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"listitem","version":1,"value":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Check out the code on our ","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"listitem","version":1,"value":1}],"direction":null,"format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"}],"direction":null,"format":"","indent":0,"type":"root","version":1}}'` in `editorConfig` object
3. An error with the message `Cannot call set() on a frozen Lexical node map` will occur

Link to code example:

https://codesandbox.io/s/intelligent-paper-sd8tcl?file=/src/Editor.js:2032-2044

## The current behavior

An error with the message `Cannot call set() on a frozen Lexical node map` occurred

(BTW, the bug exists only if there is a list in the initial editor config and contains two or more list items)

## The expected behavior

No error(s) occurred

**Comment by fantactuka** [comment]
List state is a bit corrupted: second "value" should be 2 instead of 1. Otherwise list plugin tries to fix it when state is already reconciled and throwing that error. Here's correct state to use:
```json
'{"root":{"children":[{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Visit the ","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"listitem","version":1,"value":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Check out the code on our ","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"listitem","version":1,"value":2}],"direction":null,"format":"","indent":0,"type":"list","version":1,"listType":"bullet","start":1,"tag":"ul"}],"direction":null,"format":"","indent":0,"type":"root","version":1}}'
```
