### ISSUE TITLE
Bug: Pressing tab on list item when selection is covering text and link does nothing

### ISSUE THREAD

**Issue by a-xin** [facebook/lexical#2875]
Repro:
1. Create a list item
2. Put some text followed by a link
3. Select both the text and the link
4. Press tab (or click on `Indent` in the `Align` dropdown)

Result: Nothing happens

Expectation: List item gets indented one level

https://user-images.githubusercontent.com/1154924/186154871-0beaff68-8f98-4dbe-a6e4-55f56318b770.mov

**Comment by thegreatercurve** [comment]
This appears to have been fixed. I'm now able to indent the list item when both the text and link are selected, either together or independently.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/7748470/222455356-c850ec24-ea5f-422e-b414-22eceec37ea5.png">
