### ISSUE TITLE
Inline examples in the documentation 

### ISSUE THREAD

**Issue by thegreatercurve** [facebook/lexical#2886]
> 🚨 PLEASE DO NOT WORK ON THIS ISSUE: This work is earmarked for a Meta intern.

Compared to other rich text editors, our documentation lacks inline/iframe examples of various Lexical concepts and plugins.

As we have opened up Lexical to the OSS community, more and more functionality is being added to the [official playground](https://playground.lexical.dev/).

This creates a kitchen sink example which is confusing to navigate for first time and existing users alike. It also blocks many developers who try to navigate the playground's codebase to simply copy and paste example code. 

To solve this issue, my proposal is to break down the playground into several smaller examples, each one highlighting a different piece of functionality, or different plugin.

These example can then be collated into `iframes` in an "Examples" section within our docs.

Some examples of other inline example pages from other RTEs: 
- [TipTap examples page](https://tiptap.dev/examples/default)
- [ProseMirror examples page](https://prosemirror.net/examples/)
- [SlateJS examples page](https://www.slatejs.org/examples/richtext)
- [QuillJS examples page](https://quilljs.com/playground/)
- [TinyMCE examples page](https://www.tiny.cloud/docs/tinymce/6/basic-example/)

This work will also involve changing some of our E2Es which rely exclusively on the playground.

**Comment by echarles** [comment]
> These example can then be collated into iframes in an "Examples" section within our docs.

Probably the quickest to get something. Another way is to implement lexical as a Docusaurus plugin.

**Comment by thegreatercurve** [comment]
Looks like Docusaurus has recently added some nice functionality for [live code blocks](https://docusaurus.io/docs/markdown-features/code-blocks#interactive-code-editor) in a native plugin.

Depending on the complexity of the example I'm not sure if we'd need to also support having multiple tabs for different files, similar to what you get on TipTap's examples page.

**Comment by echarles** [comment]
There are other examples that allow to show live code and also generate a button to open that code in codesanbox

- https://syncedstore.org/docs/react
- https://plate.udecode.io/docs/plugins/alignment

I have looked at a docusaurus plugin that would allow to embed a codesandbox in a docusaurus webpage but have not found any. Maybe it exists somewhere, or it should not be too difficult to implement. This would allow to directly embed the existing codesanbox plain and rich text.

**Comment by acywatson** [comment]
I remember seeing that React as using this on their new website:

https://sandpack.codesandbox.io/

**Comment by echarles** [comment]
Sandpack has a plugin for docusaurus https://github.com/codesandbox/sandpack/tree/main/plugins/docusaurus

and their docs website on https://sandpack.codesandbox.io/docs/ is built with docusaurus (the introduction page has such a "Live coding environment in minutes").

<img width="956" alt="Screenshot 2022-08-25 at 16 11 07" src="https://user-images.githubusercontent.com/226720/186688121-4bce12b9-d18e-4432-82eb-dbc38b572f8a.png">

**Comment by echarles** [comment]
... a more evolved example on https://github.com/YousefED/SyncedStore/blob/50e4c34ae730f5166dd6f0207638b306c939f4db/docs/src/theme/CodeBlock/index.tsx
