### ISSUE TITLE
Feature: Find and Replace

### ISSUE THREAD

**Issue by Sotatek-TiepLe** [facebook/lexical#2906]
### Search Highlighting and Replace text

Refer: https://ckeditor.com/docs/ckeditor5/latest/features/find-and-replace.html

 - Text with decorations
![image](https://user-images.githubusercontent.com/88995057/187331352-d083d479-56f9-484b-9c89-41283cbcdaad.png)
- Search Highlighting
![image](https://user-images.githubusercontent.com/88995057/187331531-6d88cf61-49dd-49fa-adfb-87518d53f4b6.png)

------
Currently lexical is searching by node
I can't search and select by row
**Hope the helping. Thanks a lot**

**Comment by trueadm** [comment]
I'm not sure that we want to build such a feature, as it's quite particular on your editor workflow. However, why can't someone use the browser built-in search feature? In the case where you can't, you could roll your own plugin and share it with others as I'm sure they'd love to have this too!

**Comment by thegreatercurve** [comment]
I'm going to close this issue as I think it's a cool idea for a feature but it shouldn't be part of core and I'm not sure how much use it would be to include it in the playground.

**Comment by Sotatek-TiepLe** [comment]
Hi @thegreatercurve @trueadm 

Currently Lexical is searching by button
I can't search and select by row like DraftJs

Example DraftJs: https://jsfiddle.net/5nft3yuw/8/

Can you tell me how to handle this case. Thanks a lot!!

**Comment by alexluong** [comment]
> I'm not sure how much use it would be to include it in the playground.

FWIW I'd love to see it in the playground to learn how to handle code highlighting with Lexical. I'm building a similar feature with Lexical right now and it's not easy, to put it lightly 😅

**Comment by Sotatek-TiepLe** [comment]
@alexluong Do you have any ideas? Can we work together? 😀

**Comment by alexluong** [comment]
No ideas from me yet 😅 still exploring this topic (text highlighting), but feel free to ping me on Twitter / email if you want to exchange ideas.

**Comment by mshahzaib101vaionex** [comment]
hello, does any one crack it successfully

**Comment by mshahzaib101** [comment]
Hello, does anyone got the solution for it

**Comment by newproplus** [comment]
Has anyone got the solution for it?

**Comment by newproplus** [comment]
Has anyone got the solution for it?

**Comment by huungoc27** [comment]
Iam trying to create this kind of plugin, but it seems taking time
This is the inprogress image
![image](https://github.com/facebook/lexical/assets/42691242/59a8a71c-7a78-4200-a21a-301d4bbb2040)
