### ISSUE TITLE
Bug: The exported state of list cannot be used to import

### ISSUE THREAD

**Issue by ImSingee** [facebook/lexical#2907]
Lexical version:  0.3.11

> The report is the successor of #2874

## Steps To Reproduce

1. Create a headless editor and insert a list node contains more than one child
2. Use the exported state to create a new editor
3. The same error as #2874 with the message "Cannot call set() on a frozen Lexical node map" will occur 

Link to code example:

https://codesandbox.io/s/peaceful-wiles-uj0elc?file=/src/Editor.js

## The current behavior

The generated editor state cannot be used to import because of the reason pointed out by @fantactuka : "List state is a bit corrupted: second "value" should be 2 instead of 1."

## The expected behavior

No error(s)

**Comment by roeycohen** [comment]
hi @trueadm, how are you?

indeed this issue is fixed, but when one tries to use $generateNodesFromDOM the error returns.

**Comment by roeycohen** [comment]
regarding my last comment, loading the HTML using "editor.update" instead of "initialConfig.editorState(func)" fixed the issue.
using this flow: https://stackoverflow.com/a/75080913/314905

**Comment by DominicSherman** [comment]
@trueadm I am still seeing this issue. If you update the sandbox shared in this issue to use the latest version, you'll see it is still appearing.
