### ISSUE TITLE
Feature: Broadcast focus state

### ISSUE THREAD

**Issue by js-egton** [facebook/lexical#2909]
Hello!

I'm working with Lexical at the moment, and have a fully working editor all set up and working. However, I've had a request from my UX team to show a focus ring around the editor; this currently doesn't seem possible, as the editor does not broadcast focus/blur events.

The best I can manage at the moment is an outline around the editor "inner" using the `:focus-within` CSS selector, but this isn't as clean as we'd like:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/22954865/187416766-bc7a0eb0-cfd0-44a9-bc22-f1c2b812083f.png">

Would something like a focus hook, or an `editor.isFocused` boolean be possible? Anything I could use to add/remove a class based on state would be ideal!

**Comment by trueadm** [comment]
There are BLUR and FOCUS commands you can listen to which should give you what you need?

**Comment by js-egton** [comment]
> There are BLUR and FOCUS commands you can listen to which should give you what you need?

I thought they were commands that would _action_ a blur or focus? i.e "I want to manually focus the editor, so I'll call `editor.focus()`". Have I misunderstood those?

**Comment by js-egton** [comment]
Oh! I see you meant `import { FOCUS_COMMAND, BLUR_COMMAND} from "lexical"` - apologies, I didn't realise which commands you were referring to.

Those have worked a treat, thank you very much for the point in the right direction 👍

**Comment by mattvb91** [comment]
@trueadm the BLUR_COMMAND still triggers even when just using the toolbar options. Is there any way to ignore any toolbar clicks triggering the BLUR_COMMAND?

**Comment by trueadm** [comment]
@mattvb91 If you look at the event `target` or `relatedTarget` and seeing if that gives you any signal to help you?

**Comment by mattvb91** [comment]
> @mattvb91 If you look at the event `target` or `relatedTarget` and seeing if that gives you any signal to help you?

spot on! Thank you, appreciated
