### ISSUE TITLE
Bug: The scroll bar suddenly jumps to the bottom during editing

### ISSUE THREAD

**Issue by tsinglemon** [facebook/lexical#2913]
**Restore the scene**
When a scroll bar appears in the editor and the cursor is at the middle height of the editor, and then press Enter a few times, the scroll automatically jumps to the bottom of the editor's visible area

https://youtu.be/c4gLvtnA3Zg

**try to locate the problem**
I found that when I commented this line of code, there was no problem.
https://github.com/facebook/lexical/blob/bf29e4c0c5e33f28945faea781f7ca99c1c93823/packages/lexical/src/LexicalUtils.ts#L1161
![截屏2022-08-31 04 20 34](https://user-images.githubusercontent.com/23120174/187535513-763b8edd-c774-4f6b-bd0a-2b27163a16cd.png)

**Comment by trueadm** [comment]
Thanks for reporting this. Fixed in #2917 :)
