### ISSUE TITLE
Feature: JSON (Serialize) to HTML without Instance Editor

### ISSUE THREAD

**Issue by kcoet** [facebook/lexical#2933]
Are there any plans to add a feature that will allow us to convert JSON (serialize) to HTML without an Editor instance?

I think that nowadays we need an Editor instance every time we want to convert JSON (serialize) to HTML, so performance might be a problem if we have a site where most of the content is created using an editor, a question and answer site like Quora or Stackoverflow for example.

Related:
- https://github.com/facebook/lexical/issues/2587
- https://lexical.dev/docs/concepts/serialization

**Comment by trueadm** [comment]
I'm not sure this is possible. For a very good reason – what defines the HTML is your nodes, and the only thing aware of them is your editor (you pass it your theme and nodes config on initialization). I don't see how it could ever be possible to do it without these things. You can do this in headless mode on the server `@lexical/headless` if you want to optimize performance without using the client.
