### ISSUE TITLE
Feature: Expose the playground as a single package.

### ISSUE THREAD

**Issue by evolify** [facebook/lexical#2934]
The lexical playground is a nice editor, If it can be expose as a package, everyone can use lexical anywhere quickly.

**Comment by thegreatercurve** [comment]
@evolify I think we've addressed this elsewhere, but the simple reason that we don't export the playground is that we don't have the engineering resources to maintain the framework for building text editors AND a rich text editor as well.

The playground is just meant to be be a more informal scratch pad of ideas. 

That being said, some people are [starting to build fully-featured RTEs around Lexical](https://github.com/ozanyurtsever/verbum) that could fit your use case.
