### ISSUE TITLE
Bug: Android web - Can't backspace delete the last character in a TextNode

### ISSUE THREAD

**Issue by ProvidenceXz** [facebook/lexical#2937]
Lexical version: 0.3.11

## Steps To Reproduce

1. On Android Chrome, go to https://playground.lexical.dev/ and delete all content
2. At the beginning, type a character and backspace. Character not deleted, but cursor moved over
3. If not, repeat with various letters and special characters
4. the only way to delete is through selecting + cut

P.S. I also notice it happening with `token` mode `TextNode`, `LinebreakNode` etc.

Link to code example: https://playground.lexical.dev/

https://user-images.githubusercontent.com/9211198/188241349-dc229aa6-4c41-4424-863c-017080058825.mp4

**Comment by acywatson** [comment]
I can't seem to repro this - just got set up with a new Android phone though, so maybe a versioning thing?

Looks like I'm on Chrome 96.0.4664.104 and Android 12

**Comment by trueadm** [comment]
What android keyboard are you using? Gboard?

**Comment by ProvidenceXz** [comment]
Yes. I'm using Pixel 6 Pro which has GBoard as default.

Chrome ver. 104.0.5112.97
Android 12

Will update to 13 soon and check again.
________________________________
