### ISSUE TITLE
Bug: can't limit nodes/commands that nested editors accept

### ISSUE THREAD

**Issue by jagregory** [facebook/lexical#2952]
Currently it doesn't seem possible to restrict the kind of content that can be placed inside nested editors.

I can work around this by disabling toolbar buttons based on whether the active editor includes a command in it's `_commands` set: `!activeEditor._commands.has(MY_CUSTOM_COMMAND)` but that doesn't seem ideal.

Lexical version: 0.3.11 but also verified against Playground from main (e.g. https://lexical-playground-git-041-fbopensource.vercel.app/)

## Steps To Reproduce

1. Open the [Playground](https://playground.lexical.dev/)
2. Insert a Sticky or a Image with a Caption
3. Within the nested editor, insert an Image, bold some text etc...

## The current behavior

Currently, following the above steps will result in bold text or an image inside in the Sticky, despite the StickyPlugin being configured to accept PlainText:

```
        <LexicalNestedComposer
          initialEditor={caption}
          initialTheme={StickyEditorTheme}>
          {isCollabActive ? (
            <CollaborationPlugin
              id={caption.getKey()}
              providerFactory={createWebsocketProvider}
              shouldBootstrap={true}
            />
          ) : (
            <HistoryPlugin externalHistoryState={historyState} />
          )}
          <PlainTextPlugin
            contentEditable={
              <ContentEditable className="StickyNode__contentEditable" />
            }
            placeholder={
              <Placeholder className="StickyNode__placeholder">
                What's up?
              </Placeholder>
            }
            // TODO Remove after it's inherited from the parent (LexicalComposer)
            initialEditorState={null}
          />
        </LexicalNestedComposer>
```

A similar thing happens with commands. When a command is defined by a plugin that isn't registered on the nested editor, the [triggerCommandListeners function](https://github.com/facebook/lexical/blob/7165f8a13b060c0072e87db6a1271b01de38d18a/packages/lexical/src/LexicalUpdates.ts#L662) iterates the active editors, recognises that there's no listener registered for the command on the nested editor, but then sends the command to the parent editor which just inserts the node within the nested editor anyway.

## The expected behavior

I'd expect:

1. Nested editors to only accept Nodes that are configured on the Nested editor
2. Commands issued to a nested editor that isn't configured to accept them should not result in the command executing and inserting nodes into the nested editor.

**Comment by trueadm** [comment]
This was actually fixes last night https://github.com/facebook/lexical/pull/2947!

**Comment by jagregory** [comment]
Oh awesome! Thanks @trueadm. I had a quick look at the [Preview Playground](https://lexical-playground-drv879wup-fbopensource.vercel.app/) from that PR and it seems to still behave the same as before (e.g. I can insert images in the Sticky). Am I missing something?

**Comment by trueadm** [comment]
@jagregory by default a nested editor inherits its parents nodes unless you specifically define the nodes via <NestedLexicalComposer inititalNodes={…}>

**Comment by jagregory** [comment]
Sounds like a good idea. I'll see what I can do.

**Comment by fantactuka** [comment]
This one seems to be fixed. But feel free to reopen if needed

**Comment by jagregory** [comment]
I've started a PR to update the Playground (#2988), but I'm not sure this issue is fully resolved yet. The nodes aren't being inserted into the nested editor, which is great, but there's still a bit of surprising behaviour with commands:

1. Attempting to insert a node which isn't registered into a nested editor results in a console error in dev mode (more details below)

2. Dispatching a command that isn't registered to a nested editor still results in the command being executed if the parent editor does have the command registered. This results in the behaviour in (1), as a Node is actually instantiated but then fails to be inserted. This is benign for simple insert commands which fail anyway, but may be undesirable for commands that have other side-effects.

I'm not sure what the behaviour should be, but some possible options:

1. Dispatching a command to a nested editor which doesn't have that command registered should just do nothing or raise an error without invoking the command. User's would just see the button do nothing.

2. Have a way to detect whether an editor supports a command, which could be used to disable buttons (tiptap uses their [command dry-run](https://tiptap.dev/api/commands#dry-run-for-commands) for this purpose). It's possible to do this currently by inspecting the editor's `_commands` set, but that feels a bit naughty peeking into private state. Perhaps just exposing a `hasCommand` like `hasNode` would be sufficient?

## More detail

If you test in the [Vercel preview for that PR](https://lexical-playground-git-fork-jagregory-playg-dd5e67-fbopensource.vercel.app/), then create a Sticky and try to insert a Gif inside it: the Gif doesn't get inserted! but an error is logged to the console:

```
Error: Create node: Attempted to create node ImageNode that was not configured to be used on the editor.
    at errorOnTypeKlassMismatch (LexicalNode.ts:797:37)
    at new LexicalNode (LexicalNode.ts:208:9)
    at new DecoratorNode (LexicalDecoratorNode.ts:20:5)
    at new ImageNode (ImageNode.tsx:142:5)
    at $createImageNode (ImageNode.tsx:236:10)
    at Array.<anonymous> (index.ts:62:31)
    at triggerCommandListeners (LexicalUpdates.ts:670:17)
    at LexicalUpdates.ts:649:19
    at beginUpdate (LexicalUpdates.ts:806:5)
    at updateEditor (LexicalUpdates.ts:913:5)
```

Tracing this through this only appears to happen , what seems to be happening is:

1. The Toolbar button dispatches the `INSERT_IMAGE_COMMAND` to the `activeEditor` (which is the nested editor)
4. `dispatchCommand` calls `triggerCommandListeners` which internally gets a list of editors to propagate the command to (in this case: `[nested_editor, root_editor]`)
5. The editor list is iterated, testing to see if the command is in the editor's commands set.
6. The nested editor doesn't have the command registered, so is skipped.
7. The parent editor does have the command registered, so the command is invoked.
8. The command calls `$createImageNode` which in turn instantiates a subclass of `LexicalNode`
9. In the constructor of `LexicalNode` calls `errorOnTypeKlassMismatch`, which retrieves the `activeEditor` again (the nested editor) and checks if the node is registered, which it isn't so an error is thrown.

**Comment by trueadm** [comment]
Commands are expected to propagate. Just like events do on the DOM. This is important, as the patent editor might want to react to certain things inside the nested editor without the nested editor already reacting to them. One thing you can do in your command listener, is validate the target active editor. If it doesn’t match the one used for registering the command then you just skip your logic.

**Comment by jagregory** [comment]
Ok that makes sense.

When `__DEV__` is true the above behaviour occurs, when `__DEV__` is false a slightly different error occurs:

```
Error: registeredNode: Type image not found
    at getRegisteredNodeOrThrow (LexicalUtils.ts:89:37)
    at $applyTransforms (LexicalUpdates.ts:114:26)
    at $applyAllTransforms (LexicalUpdates.ts:215:11)
    at beginUpdate (LexicalUpdates.ts:814:9)
    at updateEditor (LexicalUpdates.ts:913:5)
    at LexicalEditor.update (LexicalEditor.ts:797:5)
    at triggerCommandListeners (LexicalUpdates.ts:648:12)
    at dispatchCommand (LexicalUtils.ts:1110:10)
    at LexicalEditor.dispatchCommand (LexicalEditor.ts:687:12)
    at onClick (index.tsx:245:18)
```

Is that expected behaviour?
