### ISSUE TITLE
Bug: Editor constantly loses focus in React 17

### ISSUE THREAD

**Issue by hanford** [facebook/lexical#2959]
When using `ReactDOM.render` (React 18 & 17), Having many Lexical editors with `key=` attributes, causes editors to lose focus in a way that becomes unusable.

This bug did not occur in Lexical 3.11 and seems to have been introduced with [this commit](https://github.com/facebook/lexical/commit/06c3e6160cac44f1cdbe3113655bd8d00d1e3195).

I have an internal UI that's used to develop lexical that looks like this, as you're typing in the top left editor, I have a few other lexical instances with `key=` attributes that I forcefully re-create to ensure their instantiated with the value of the primary editor. This allows me to verify rendering is consistent across different scenarios

<img width="1734" alt="image" src="https://user-images.githubusercontent.com/2148168/189005457-4a15960a-f16c-49b8-aae6-f0075f8e2341.png">

When trying to upgrade to the latest version, I noticed typing on this page stopped working, after a few hours of debugging, I narrowed it down the ReactDOM method. 🧐

The offending commit doesn't have anything that sticks out to me, but when trying my repro on the commit before it, things worked as expected, and fail afterwards.

Lexical version: 4.0 & 4.1

## Steps To Reproduce

1. Check out [this sandbox](https://codesandbox.io/s/many-lexical-autofocus-forked-us0rff?file=/src/index.js)
2. Type in the top Editor, Notice that it "blurs" as soon as the onChange method is fired (this re-creates the below static editor).
4. Toggle the ReactDOM method that's used in the index.js (enabling `createRoot`, disabling `render`)
5. Notice you're now able to reliably type in the first editor 

Link to code example: https://codesandbox.io/s/many-lexical-autofocus-forked-us0rff?file=/src/index.js

## The current behavior

The editor seems to lose focus almost immediately after interacting with it

## The expected behavior

Focus should remain

**Comment by trueadm** [comment]
Thanks for the detailed repro report. I found the issue and the fix should be in https://github.com/facebook/lexical/pull/2967
