### ISSUE TITLE
Question: Can we remove empty function ?

### ISSUE THREAD

**Issue by Zuckjet** [facebook/lexical#2960]
I found the empty function `selectionTransform`: 
https://github.com/facebook/lexical/blob/d773ead3f1654a9f5fc800b0fcd50faa5f2a3126/packages/lexical/src/nodes/LexicalTextNode.ts#L504-L509

Just out of curiosity why we need this empty function.

**Comment by trueadm** [comment]
It’s used internally on www AFAIK. In that it’s extended

**Comment by thegreatercurve** [comment]
Actually, I see it now. Closing this as we use it in some internal subclasses around mentions.
