### ISSUE TITLE
Bug: Enabling and disabling Markdown removes styles applied to text

### ISSUE THREAD

**Issue by alinamusuroi** [facebook/lexical#2965]
When writing styled text containing whitespaces, enabling and disabling Markdown removes any style applied to the text. The text is also replaced by Markdown.

Lexical version:

## Steps To Reproduce

1. Write any text with whitespaces.
2. Apply styles to the text
3. Convert to Markdown
4. Disable Markdown

https://user-images.githubusercontent.com/44519061/189119324-b11b4556-508f-40ed-a547-2ec048f21072.mov

**Comment by etrepum** [comment]
I can't reproduce this with the current version. I can definitely still see some bugs in how the table support is implemented and how leading or trailing styled whitespace is handled, but this case seems to work ok (ignoring the other table related issues)
