### ISSUE TITLE
Bug: Invalid markdown syntax for table

### ISSUE THREAD

**Issue by mocny** [facebook/lexical#2990]
Markdown syntax for table should look like:

```
| Heading 1 | Heading 2 | Heading 3 |
|---|---|---|
| Content 1 | Content 2 | Content 3 |
```

or with allignments, there should support for:
`|:--- | ---: | :---:|`

At this stage, lexical converts table just like this:
```
| | | |
| | | |
| | | |
```

**Comment by StyleT** [comment]
Fixed now
