### ISSUE TITLE
Bug: Lexical nodes not persisting styles present in original HTML

### ISSUE THREAD

**Issue by manish2612** [facebook/lexical#3010]
Lexical version: 0.4.1

## Steps To Reproduce

1. Generate HTML using Lexical APIs
2. Use generated HTML from step 1 and provide to Lexical editor. use generateNode API provided by Lexical.
3. Resulting content in editor will not have style which it supposed to have

Following HTML was generated by Lexical and saved in DB. We provide it as is to Lexical and generate nodes (https://lexical.dev/docs/concepts/serialization) from it

```
<p class="RMXContentTheme__paragraph"
 data-lexical-node-type="paragraph"
 data-lexical-node-json='{"children":[],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}'
 data-lexical-editor-key="rpoel">
 <span
   data-lexical-node-type="text"
   data-lexical-node-json='{"detail":0,"format":0,"mode":"normal","style":"color: #e00000;background-color: #f8e71c;","text":"manish","type":"text","version":1}'
   data-lexical-editor-key="rpoel"
   style="color: rgb(224, 0, 0); background-color: rgb(248, 231, 28)">
       Hello World
   </span>
</p>
```

## The current behavior

After deserializing HTML content **its NOT PERSISTING style properties** which were present in HTML
```
<p
  class="RMXContentTheme__paragraph"
  data-lexical-node-type="paragraph"
  data-lexical-node-json='{"children":[],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}'
  data-lexical-editor-key="qktmf">
  <span
    data-lexical-node-type="text"
    data-lexical-node-json='{"detail":0,"format":0,"mode":"normal","style":"","text":"manish","type":"text","version":1}'
    data-lexical-editor-key="qktmf">
    Hello World
  </span>
</p>
```

## The expected behavior

After deserializing HTML content **it SHOULD PERSIST style properties** which were present in HTML
```
<p class="RMXContentTheme__paragraph"
 data-lexical-node-type="paragraph"
 data-lexical-node-json='{"children":[],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}'
 data-lexical-editor-key="rpoel">
 <span
   data-lexical-node-type="text"
   data-lexical-node-json='{"detail":0,"format":0,"mode":"normal","style":"color: #e00000;background-color: #f8e71c;","text":"manish","type":"text","version":1}'
   data-lexical-editor-key="rpoel"
   style="color: rgb(224, 0, 0); background-color: rgb(248, 231, 28)">
       Hello World
   </span>
</p>
```

**Comment by zurfyx** [comment]
Fix ready! We were ignoring color/background-color on HTML clipboard paste; see more details on the linked PR

**Comment by Manish2612** [comment]
@zurfyx Thanks! 
I observed similar issue after following same steps for text alignment, strikethrough and underline. It will be great If you can take a look for resolving this.

**Comment by Manish2612** [comment]
After Implementing we are getting text color and background color. When we  use `$getSelectionStyleValueForProperty` for selected text we should get correct colors present in style but LexicalSelection.js is returning null even if styles are present.

```
function $getNodeStyleValueForProperty(node, styleProperty, defaultValue) {
  // Line below is returning string: color: rgb(229, 0, 0);background-color: rgb(248, 231, 28)
  const css = node.getStyle();
  // Line below isreturning null
  const styleObject = getStyleObjectFromCSS(css);

  if (styleObject !== null) {
    return styleObject[styleProperty] || defaultValue;
  }

  return defaultValue;
}
```

**Comment by zurfyx** [comment]
Looks like another bug, thanks for the callout! Just pushed https://github.com/facebook/lexical/pull/3024, see the summary for a detailed explanation

**Comment by Manish2612** [comment]
@zurfyx Thanks for prompt response and fix!
It will be great if you can let us know way to persist text-alignment?

**Comment by zurfyx** [comment]
> @zurfyx Thanks for prompt response and fix! It will be great if you can let us know way to persist text-alignment?

Can you store this on the parent (i.e. ParagraphNode)? `paragraphNode.setFormat('center')`

We also have a command for this -> `.dispatchCommand(FORMAT_ELEMENT_COMMAND, 'center');`

**Comment by Manish2612** [comment]
> > @zurfyx Thanks for prompt response and fix! It will be great if you can let us know way to persist text-alignment?
> 
> Can you store this on the parent (i.e. ParagraphNode)? `paragraphNode.setFormat('center')`
> 
> We also have a command for this -> `.dispatchCommand(FORMAT_ELEMENT_COMMAND, 'center');`

It's already being stored in parent by lexical itself. When we use generated HTML as initial state, aligned text is not rendered by editor even if `data-lexical-json` attributes is present on parent tag.

```
<p
  class="RMXContentTheme__paragraph"
  data-lexical-node-type="paragraph"
  data-lexical-node-json='{"children":[],"direction":"ltr","format":"center","indent":0,"type":"paragraph","version":1}'
  data-lexical-editor-key="tcrre"
>
  <span
    data-lexical-node-type="text"
    data-lexical-node-json='{"detail":0,"format":0,"mode":"normal","style":"","text":"Manish","type":"text","version":1}'
    data-lexical-editor-key="tcrre"
    >This should be aligned center</span
  >
</p>
```
let me know your thoughts on this.

**Comment by ivailop7** [comment]
Can you update to 0.11, all of the alignment issues should be solved, except the individual list item, for the remaining HTML properties, you can refer to https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling

**Comment by manish2612** [comment]
> Can you update to 0.11, all of the alignment issues should be solved, except the individual list item, for the remaining HTML properties, you can refer to https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling

Thanks for an update. I will give it a try.

**Comment by etrepum** [comment]
The way that this works is significantly different now
