### ISSUE TITLE
Bug: TS error on exportJSON / updateDOM when extending AutoLinkNode

### ISSUE THREAD

**Issue by Neewd** [facebook/lexical#3029]
I try to create a custom node who's extending the `AutoLinkNode` in order to add properties to the link (business logic). 
I am not using React so I use it as VanillaJS. 

Lexical version: 0.4.1

## Steps To Reproduce

1. Create classic editor with plain text plugin.
2. Set up the auto link detection like it's made on the AutoLinkNodePLugin for react. 
3. Create a custom node who's extending that AutoLinkNode and add properties to it.
4. An error occurs on importJSON implementation.

Link to code example:

https://codesandbox.io/s/fancy-meadow-evuc55?file=/src/apAutoLink.node.ts

## The current behavior
Class static side 'typeof ApAutoLinkNode' incorrectly extends base class static side 'typeof AutoLinkNode'.
  Types of property 'importJSON' are incompatible.
    Type '(serializedNode: SerializedApAutoLinkNode) => ApAutoLinkNode' is not assignable to type '(serializedNode: SerializedAutoLinkNode) => AutoLinkNode'.
      Types of parameters 'serializedNode' and 'serializedNode' are incompatible.
        Type 'SerializedAutoLinkNode' is not assignable to type 'SerializedApAutoLinkNode'.
          Type 'SerializedAutoLinkNode' is not assignable to type '{ type: "ap-autolink"; customProperty?: string; version: 1; }'.
            Types of property 'type' are incompatible.
              Type '"autolink"' is not assignable to type '"ap-autolink"'.ts(2417)

**Comment by thegreatercurve** [comment]
We are aware of this issue and are looking into a more comprehensive way of dealing with types and node inheritance in Lexical.

**Comment by hyperjump888** [comment]
Here is what I need to fix it, so far it seems to work:

```
class LinkNode... 

export type SerializedLinkNode = Spread<
  {
    type: string;
    url: string;
    version: number;
  },
  Spread<LinkAttributes, SerializedElementNode>
>;

  exportJSON(): SerializedLinkNode {
    return {
      ...super.exportJSON(),
      rel: this.getRel(),
      target: this.getTarget(),
      type: 'link',
      url: this.getURL(),
      version: 1,
    };
  }

class AutoLinkNode extends LinkNode...

  exportJSON(): SerializedAutoLinkNode {
    const baseSerialized = super.exportJSON();
    return {
      ...baseSerialized,
      type: 'autolink',
      version: 1,
    };
  }

```
