### ISSUE TITLE
Bug: `selection.insertNodes` inserts 'top level' nodes inline

### ISSUE THREAD

**Issue by Piliuta** [facebook/lexical#3041]
This is a core issue in the `selection.insertNodes` method. Using this method to insert top-level nodes (`isTopLevel: true`) inserts nodes inline. So if the selection is in a middle of a paragraph, it inserts the node inside the paragraph.

This was discovered in the copy and paste functionality, but really can affect anything that uses this method.

Lexical version: 0.4.1

## Steps To Reproduce

1. Create a selectable top level decorator node. I use `ImageNode` from the lexical library, but made it top level
2. Add an image in the editor
3. Select and copy the image node
4. Paste it in the middle of a text - the image inserted inline

_**Note: There is also a fix for copying image src - not sure if this is a relative path issue or what though.**_ 

```diff
diff --git a/packages/lexical-playground/src/nodes/ImageNode.tsx b/packages/lexical-playground/src/nodes/ImageNode.tsx
index 3adf5b24..a87adc7b 100644
--- a/packages/lexical-playground/src/nodes/ImageNode.tsx
+++ b/packages/lexical-playground/src/nodes/ImageNode.tsx
@@ -42,8 +42,8 @@ export interface ImagePayload {
 
 function convertImageElement(domNode: Node): null | DOMConversionOutput {
   if (domNode instanceof HTMLImageElement) {
-    const {alt: altText, src} = domNode;
-    const node = $createImageNode({altText, src});
+    const {alt: altText, dataset} = domNode;
+    const node = $createImageNode({altText, src: dataset.src});
     return {node};
   }
   return null;
@@ -115,6 +115,7 @@ export class ImageNode extends DecoratorNode<JSX.Element> {
   exportDOM(): DOMExportOutput {
     const element = document.createElement('img');
     element.setAttribute('src', this.__src);
+    element.setAttribute('data-src', this.__src);
     element.setAttribute('alt', this.__altText);
     return {element};
   }
@@ -202,6 +203,14 @@ export class ImageNode extends DecoratorNode<JSX.Element> {
     return this.__altText;
   }
 
+  isTopLevel(): boolean {
+    return true;
+  }
+
+  isInline(): boolean {
+    return false;
+  }
+
   decorate(): JSX.Element {
     return (
       <Suspense fallback={null}>
```

https://user-images.githubusercontent.com/1575198/191313699-8099f2ed-0de9-4e41-80ae-5662550a193a.mov

## The current behavior
Top-level nodes inserted inline.

## The expected behavior
Nodes are inserted at their own blocks as top-level elements.

**Comment by Piliuta** [comment]
**Update:** on lexical v0.5.0 and above `isTopLevel: true` is replaced with `isInline: false`. On the current lexical version (v0.5.1) there are a few non-inline nodes in the playground using which the issue can be reproduced - `LexicalHorizontalRuleNode`, `TweetNode`, `YouTubeNode` and `FigmaNode`. Steps remain the same:


https://user-images.githubusercontent.com/1575198/197481042-8533e841-5505-4e90-9d37-0c59fef5dd93.mov

**Comment by trueadm** [comment]
Is this still a bug?

**Comment by Piliuta** [comment]
> Is this still a bug?

Yes. Here is a fresh example.

https://user-images.githubusercontent.com/1575198/203851417-0bd835ea-416e-42ae-a260-697fabc6df0f.mov

And this PR fixes the problem https://github.com/facebook/lexical/pull/3238 but it is still in review.

**Comment by trueadm** [comment]
Thanks for the update :) I'll track that PR.

**Comment by thegreatercurve** [comment]
Closing as fix PR has been merged
