### ISSUE TITLE
Bug: generateHtmlFromNodes removes alignment styles 

### ISSUE THREAD

**Issue by BanannaLopal** [facebook/lexical#3042]
I have EditorState, after I use the parseEditorState function and then $generateHtmlFromNodes, the alignment styles disappear.

EditorState:
```
{
  "root": {
    "children": [
      {
        "children": [
          {
            "detail": 0,
            "format": 0,
            "mode": "normal",
            "style": "",
            "text": "left",
            "type": "text",
            "version": 1
          }
        ],
        "direction": "ltr",
        "format": "",
        "indent": 0,
        "type": "paragraph",
        "version": 1
      },
      {
        "children": [
          {
            "detail": 0,
            "format": 0,
            "mode": "normal",
            "style": "",
            "text": "center",
            "type": "text",
            "version": 1
          }
        ],
        "direction": "ltr",
        "format": "center",
        "indent": 0,
        "type": "paragraph",
        "version": 1
      },
      {
        "children": [
          {
            "detail": 0,
            "format": 0,
            "mode": "normal",
            "style": "",
            "text": "right",
            "type": "text",
            "version": 1
          }
        ],
        "direction": "ltr",
        "format": "right",
        "indent": 0,
        "type": "paragraph",
        "version": 1
      }
    ],
    "direction": "ltr",
    "format": "",
    "indent": 0,
    "type": "root",
    "version": 1
  }
}
```
Lexical version: 0.4.1

Link to code example: https://codesandbox.io/s/happy-cori-edtjdz?file=/src/App.js

## The current behavior
alignment styles are missing

## The expected behavior
Styles are not lost

**Comment by slavko-chedri** [comment]
I have similar request for _$generateNodesFromDOM_ method.
Inline styles are ignored on transformation from HTML to lexical nodes.
This is example:
HTML:
`<p class="editor-paragraph" dir="ltr" style="text-align: center;"><span>Donec vitae justo id mauris ullamcorper condimentu.</span></p>`

```
const parser = new DOMParser();
const dom = parser.parseFromString(dumpHtml, 'text/html');

// Once you have the DOM instance it's easy to generate LexicalNodes.
const nodes = $generateNodesFromDOM(editor, dom);
```
Output:
```
{
  "root": {
    "children": [
      {
        "children": [
          {
            "detail": 0,
            "format": 0,
            "mode": "normal",
            "style": "",
            "text": " ",
            "type": "text",
            "version": 1
          }
        ],
        "direction": null,
        "format": "",
        "indent": 0,
        "type": "paragraph",
        "version": 1
      },
      {
        "children": [
          {
            "detail": 0,
            "format": 0,
            "mode": "normal",
            "style": "",
            "text": "Donec vitae justo id mauris ullamcorper condimentu.",
            "type": "text",
            "version": 1
          }
        ],
        "direction": "ltr",
        "format": "",
        "indent": 0,
        "type": "paragraph",
        "version": 1
      }
    ],
    "direction": "ltr",
    "format": "",
    "indent": 0,
    "type": "root",
    "version": 1
  }
}
```
I would expect to have "format": "center" at a related element

**Comment by byTimo** [comment]
The paragraph node's alignment is only transferred by the `$generateHtmlFromNodes` correctly because of [this](https://github.com/facebook/lexical/blob/main/packages/lexical/src/nodes/LexicalParagraphNode.ts#L73). I guess the same code should be added to each element node that can be aligned.

For now I have that work around 🙈 :
```typescript
function patchStyleTransformation(LexicalNode: Klass<ElementNode>) {
    const originalExportDOM = LexicalNode.prototype.exportDOM;
    LexicalNode.prototype.exportDOM = function exportDOM(editor) {
        const result = originalExportDOM.apply(this, [editor]);
        const element = result.element;
        if (element) {
            const formatType = this.getFormatType();
            element.style.textAlign = formatType;

            const direction = this.getDirection();
            if (direction) {
                element.dir = direction;
            }
            const indent = this.getIndent();
            if (indent > 0) {
                element.style.textIndent = `${indent * 20}px`;
            }
        }
        return result;
    };
}

patchStyleTransformation(HeadingNode);
patchStyleTransformation(ListNode);
patchStyleTransformation(QuoteNode);
```

**Comment by PrakharRichhariya-314e** [comment]
> The paragraph node's alignment is only transferred by the `$generateHtmlFromNodes` correctly because of [this](https://github.com/facebook/lexical/blob/main/packages/lexical/src/nodes/LexicalParagraphNode.ts#L73). I guess the same code should be added to each element node that can be aligned.
> 
> For now I have that work around 🙈 :
> 
> ```ts
> function patchStyleTransformation(LexicalNode: Klass<ElementNode>) {
>     const originalExportDOM = LexicalNode.prototype.exportDOM;
>     LexicalNode.prototype.exportDOM = function exportDOM(editor) {
>         const result = originalExportDOM.apply(this, [editor]);
>         const element = result.element;
>         if (element) {
>             const formatType = this.getFormatType();
>             element.style.textAlign = formatType;
> 
>             const direction = this.getDirection();
>             if (direction) {
>                 element.dir = direction;
>             }
>             const indent = this.getIndent();
>             if (indent > 0) {
>                 element.style.textIndent = `${indent * 20}px`;
>             }
>         }
>         return result;
>     };
> }
> 
> patchStyleTransformation(HeadingNode);
> patchStyleTransformation(ListNode);
> patchStyleTransformation(QuoteNode);
> ```

But this is giving typeErrors when getting used in editorConfig

**Comment by PrakharRichhariya-314e** [comment]
> The paragraph node's alignment is only transferred by the `$generateHtmlFromNodes` correctly because of [this](https://github.com/facebook/lexical/blob/main/packages/lexical/src/nodes/LexicalParagraphNode.ts#L73). I guess the same code should be added to each element node that can be aligned.
> 
> For now I have that work around 🙈 :
> 
> ```ts
> function patchStyleTransformation(LexicalNode: Klass<ElementNode>) {
>     const originalExportDOM = LexicalNode.prototype.exportDOM;
>     LexicalNode.prototype.exportDOM = function exportDOM(editor) {
>         const result = originalExportDOM.apply(this, [editor]);
>         const element = result.element;
>         if (element) {
>             const formatType = this.getFormatType();
>             element.style.textAlign = formatType;
> 
>             const direction = this.getDirection();
>             if (direction) {
>                 element.dir = direction;
>             }
>             const indent = this.getIndent();
>             if (indent > 0) {
>                 element.style.textIndent = `${indent * 20}px`;
>             }
>         }
>         return result;
>     };
> }
> 
> patchStyleTransformation(HeadingNode);
> patchStyleTransformation(ListNode);
> patchStyleTransformation(QuoteNode);
> ```
Can you please tell me how to use this funcrtion, my editor breaks dow if I try to use it.

**Comment by malavshah9** [comment]
@byTimo  Where should I put above code block?

**Comment by ivailop7** [comment]
I merged yesterday https://github.com/facebook/lexical/pull/4445 so this addresses the Heading and Quote nodes, the List part need a different approach, which is still being discussed.

**Comment by ivailop7** [comment]
Once the next version is released, will mark this as resolved.

**Comment by ivailop7** [comment]
0.11 was released, so your problem is now fixed. If you need more styles serialization, you can refer to overriding a node and the example here: https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling

**Comment by SyedSaqlain** [comment]
I am currently facing this same issue when trying to apply colour styles like(background-color, color)  , any leads for the same : 
on colour selection 
<p class="editor-paragraph ltr" dir="ltr"><span data-lexical-text="true" style="background-color: rgb(139, 87, 42);">helllo </span></p>

after conversion  : 
<p class="editor-paragraph ltr" dir="ltr"><span data-lexical-text="true">helllo </span></p> 

here is my code: 
editor.update(() => {
            const parser = new DOMParser();
            const dom = parser.parseFromString(initialHtml, 'text/html');
            const nodes = $generateNodesFromDOM(editor, dom);
            $insertNodes(nodes);
        });
        
 onChange={(editorState) => {
                editorState.read(() => {
                    onHtmlChanged($generateHtmlFromNodes(editor));
                });
            }}
Just want to know if i'm missing anything here
