### ISSUE TITLE
Bug: Unable to parse Lexical to HTML

### ISSUE THREAD

**Issue by RafaelZasas** [facebook/lexical#3049]
I keep running into the following error when using the $generateHtmlFromNodes function:

`Error: Unable to find an active editor state.
State helpers or node methods can only be
used synchronously during the callback of editor.update() or editorState.read().`

My Editor component takes one prop, the editorRef of type LexicalEditor, which ensures I have access to the editor from the parent, where I would like to handle the serialization and sending of the email.

Lexical version: 4.1

Link to code example: https://stackoverflow.com/questions/73807767/unable-to-parse-lexical-to-html

**Comment by wilbertom** [comment]
Looks like this can be closed since @RafaelZasas found the solution.
