### ISSUE TITLE
question: get markdown string of textContent without updating editor?

### ISSUE THREAD

**Issue by digitalgopnik** [facebook/lexical#3050]
Hi at all,

is it possible to get the markdown string of the editor-content **WITHOUT** updating the editor?

I know there is a way **WITH** (but this will update the editor):
```ts
import {
  $convertFromMarkdownString,
  $convertToMarkdownString,
  TRANSFORMERS,
} from '@lexical/markdown';

editor.update(() => {
  const markdown = $convertToMarkdownString(TRANSFORMERS);
  ...
});

editor.update(() => {
  $convertFromMarkdownString(markdown, TRANSFORMERS);
});
```

Another possible solution would be to iterate through all child-nodes of ```root``` and build the markdown step by step. Maybe there is another one? :)

I would really appreciate proposals, opinions or comments :)

**Comment by trueadm** [comment]
You’ll likely need to use editor.update, but don’t worry - it won’t update anything using this API an will just be a no-op.

**Comment by digitalgopnik** [comment]
> You should be able to call that same function in an editorState.read callback:
> 
> ```
> const editorState = editor.getEditorState();
> editorState.read(() => {
>   const markdown = $convertToMarkdownString(TRANSFORMERS);
> })
> ```

Unfortunately not :(

```
Uncaught Error: Cannot use method in read-only mode.
    at errorOnReadOnly (Lexical.dev.js:5335:13)
    at TextNode.getWritable (Lexical.dev.js:6536:5)
    at TextNode.setTextContent (Lexical.dev.js:8075:31)
    at Object.export (to_markdown.ts:129:12)
    at exportChildren (LexicalMarkdown.dev.js:95:1)
    at exportTopLevelElements (LexicalMarkdown.dev.js:86:1)
    at LexicalMarkdown.dev.js:66:1
    at $convertToMarkdownString (LexicalMarkdown.dev.js:1051:1)
```

**Comment by acywatson** [comment]
> > You should be able to call that same function in an editorState.read callback:
> > ```
> > const editorState = editor.getEditorState();
> > editorState.read(() => {
> >   const markdown = $convertToMarkdownString(TRANSFORMERS);
> > })
> > ```
> 
> Unfortunately not :(
> 
> ```
> Uncaught Error: Cannot use method in read-only mode.
>     at errorOnReadOnly (Lexical.dev.js:5335:13)
>     at TextNode.getWritable (Lexical.dev.js:6536:5)
>     at TextNode.setTextContent (Lexical.dev.js:8075:31)
>     at Object.export (to_markdown.ts:129:12)
>     at exportChildren (LexicalMarkdown.dev.js:95:1)
>     at exportTopLevelElements (LexicalMarkdown.dev.js:86:1)
>     at LexicalMarkdown.dev.js:66:1
>     at $convertToMarkdownString (LexicalMarkdown.dev.js:1051:1)
> ```

Ah, Dominic is right - we have a similar constraint with Lexical -> HTML conversions right now. Unfortunate, but yea the update won't actually mutate the editor state. The semantics are weird though.

**Comment by digitalgopnik** [comment]
@trueadm @acywatson Thanks for help and ultra fast response!

@trueadm Works fine! Thanks for clarification :slightly_smiling_face:

**Comment by digitalgopnik** [comment]
> > > You should be able to call that same function in an editorState.read callback:
> > > ```
> > > const editorState = editor.getEditorState();
> > > editorState.read(() => {
> > >   const markdown = $convertToMarkdownString(TRANSFORMERS);
> > > })
> > > ```
> > 
> > 
> > Unfortunately not :(
> > ```
> > Uncaught Error: Cannot use method in read-only mode.
> >     at errorOnReadOnly (Lexical.dev.js:5335:13)
> >     at TextNode.getWritable (Lexical.dev.js:6536:5)
> >     at TextNode.setTextContent (Lexical.dev.js:8075:31)
> >     at Object.export (to_markdown.ts:129:12)
> >     at exportChildren (LexicalMarkdown.dev.js:95:1)
> >     at exportTopLevelElements (LexicalMarkdown.dev.js:86:1)
> >     at LexicalMarkdown.dev.js:66:1
> >     at $convertToMarkdownString (LexicalMarkdown.dev.js:1051:1)
> > ```
> 
> Ah, Dominic is right - we have a similar constraint with Lexical -> HTML conversions right now. Unfortunate, but yea the update won't actually mutate the editor state. The semantics are weird though.

Definitely a bit misleading. But it's fine :slightly_smiling_face: Thank you!
