### ISSUE TITLE
Bug: Cursor jumping back using registerLexicalTextEntity on combining previous target node with current text node

### ISSUE THREAD

**Issue by vilicvane** [facebook/lexical#3054]
Lexical version: 0.4.1

## Steps To Reproduce

https://codesandbox.io/s/lexical-plain-text-example-forked-1t9vso

In the example above, type "http://lexical.d" and the cursor would jump back before the dot.

A possible fix is to `select()` after `setTextContent()` here:

https://github.com/facebook/lexical/blob/3d6c737624b0167395c2a699df739e09d750bc63/packages/lexical-text/src/index.ts#L196-L210

**Comment by etrepum** [comment]
I don't see this sort of problem with the AutoLinkNode that ships with @lexical/react and this is old enough that the version in this repro doesn't quite work properly with current lexical anymore
