### ISSUE TITLE
Refactor `lexical/selection` into separate files

### ISSUE THREAD

**Issue by thegreatercurve** [facebook/lexical#3060]
All of the logic in `lexical/selection/index.js` is contained in one file. We should instead refactor this file into multiple files instead.

**Comment by abdullahranginwala** [comment]
Hello! First time contributor here. Just to clarify is this -> packages/lexical-selection/src/index.ts the file you are referring to? Secondly, are there any guidelines on how you want to code to be split up in multiple files?

**Comment by abdullahranginwala** [comment]
@thegreatercurve Thank you for reaching out. I looked at the code and realised that each function takes the selection type as a parameter. How can I split the code into multiple files based on the selection type?

**Comment by thegreatercurve** [comment]
@abdullahranginwala Can you just import the relevent classes into your utils file?
