### ISSUE TITLE
Bug: changing text formatting is still allowed in read-only mode

### ISSUE THREAD

**Issue by zeeyang** [facebook/lexical#3065]
Lexical version: 0.5.0 and prior

## Steps To Reproduce

1. in lexical playground, turn on read-only mode
2. in toolbar, change block formatting

![Kapture 2022-09-24 at 09 16 21](https://user-images.githubusercontent.com/2062827/192108233-7be7403c-c1d3-4290-abe7-f0d368afee32.gif)

## The current behavior
Readonly mode (editor.editable = false) blocks cursor input in content editable, but does not prevent toolbar from changing text formatting. 

## The expected behavior
- lexical editor should block updates in readonly mode
- playground toolbar and floating toolbar should be disabled for usability

**Comment by acywatson** [comment]
Good callout, just want to note that the current thinking is that readonly mode shouldn't be a guarantee enforced by the editor. Instead, It just marks contenteditable false on the underlying editor root the user needs to enforce it themselves by checking if editable is true before updating the editor.

We should probably do this check for the plugins we maintain, though.
