### ISSUE TITLE
Add an eslint rule to prevent optional chaining

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#3074]
Add an eslint rule to prevent optional chaining. We don't support it and it will fail the build. Can probably use this, but I don't think we want to depend on this package, necessarily (hasn't been updated in a while and seems to require some additional config that we might not want).

https://github.com/mysticatea/eslint-plugin-es/blob/master/lib/rules/no-optional-chaining.js

**Comment by abdullahranginwala** [comment]
Can I create a custom rule locally based on the package you've mentioned?

**Comment by acywatson** [comment]
> Can I create a custom rule locally based on the package you've mentioned?



Yea that's basically what I was thinking!

**Comment by shanpriyan** [comment]
@acywatson I have created a new plugin with this rule and included the plugin to project locally in #3233 , is that the expected?

**Comment by thorn0** [comment]
What's wrong with optional chaining? Why does it fail the build?
