### ISSUE TITLE
Bug: unable to run $generateHtmlFromNodes with headless editor

### ISSUE THREAD

**Issue by alexluong** [facebook/lexical#3097]
Lexical version: 0.5.0

## Steps To Reproduce

1. Install the necessary dependencies (lexical, @lexical/headless, @lexical/html, etc)
2. In a Node environment, generate HTML string from a lexical editor state JSON string. See reproduction link below.

Link to code example: https://stackblitz.com/edit/node-fsv6np

## The current behavior

With the above reproduction, when running the script this is the log from the terminal:

```
$ node index.js
markdown: hello world
```

## The expected behavior

```
$ node index.js
markdown: hello world
html: <p>hello world</p>
this should be logged
```

**Comment by fantactuka** [comment]
Did you add any dom-like environment to handle dom creation? We [do not provide any built-in replacement](https://github.com/facebook/lexical/blob/main/packages/lexical-html/src/index.ts#L61) for node.js, so you'll need to include [jsDom](https://github.com/jsdom/jsdom) or similar to generate html on server

**Comment by fantactuka** [comment]
To be fair, that document/window check does not work correctly, hence you don't see proper explanation. I've created #3102 to adjust that

**Comment by agustaf9** [comment]
Adding this line worked for me.

`function DocumentFragment() {
  return JSDOM.fragment('')
}`

**Comment by Negan1911** [comment]
@fantactuka It is possible to pass the window / document to headless so we don't check on the global objects?

**Comment by Negan1911** [comment]
Not quite sure if y'all saw it, but on the HTML documentation there's a way to pass the dom as a 2nd parameter: https://github.com/jsdom/jsdom

**Comment by konhi** [comment]
[This implementation ](https://github.com/2wheeh/lexical-nextjs-ssr/blob/6d97581def739cb5763b5a3a2d611f8873a3013e/src/lib/index.ts)solves the issue for Next
