### ISSUE TITLE
Bug: selection changes to null when selecting text after node selection on mobile devices

### ISSUE THREAD

**Issue by IBastawisi** [facebook/lexical#3098]
Lexical version: 0.5.0
<video src="https://user-images.githubusercontent.com/13211445/193463810-8af30292-f54f-455c-9461-56370dc59118.mp4"></video>

**Comment by trueadm** [comment]
This is actually to be expected on touch devices. Moving from node selection to range selection will require an extra touch. Whilst we can force the adjusted behavior, it leads to strange bugs when you try and do things like drag and drop + resizing. So for those reasons, closing for now as I don't see this as too big an issue.

**Comment by IBastawisi** [comment]
> This is actually to be expected on touch devices. Moving from node selection to range selection will require an extra touch. Whilst we can force the adjusted behavior, it leads to strange bugs when you try and do things like drag and drop + resizing. So for those reasons, closing for now as I don't see this as too big an issue.

Hi there!
I was wondering if this could be fixed, it was working as expected before this commit https://github.com/facebook/lexical/commit/382766a
can you review it?
