### ISSUE TITLE
Bug: `DraggableBlockPlugin` uses unexposed apis

### ISSUE THREAD

**Issue by knoopx** [facebook/lexical#3100]
Getting `Failed to resolve import "lexical/LexicalUtils"` when trying to use `DraggableBlockPlugin` from the playground. `getElementByKeyOrThrow` is exported by `lexical/LexicalUtils` but the npm package only contains `Lexical.{dev,prod}.js` and `getElementByKeyOrThrow` is not exported anywhere else.

Lexical version: 0.5

![image](https://user-images.githubusercontent.com/100993/193565004-2eadb351-ca88-4ffe-84bf-56fa4da68913.png)

**Comment by luudv** [comment]
I get same problem, and using https://lexical.dev/docs/api/classes/lexical.LexicalEditor#getelementbykey instead of getElementByKeyOrThrow
