### ISSUE TITLE
Feature: support deeply nested lists

### ISSUE THREAD

**Issue by ssalka** [facebook/lexical#3123]
I'm using the `RichTextPlugin` and trying to make an outline-like document, i.e. a bulleted list that supports deep nesting, like so:

* level1 
  * level2
    * level 3
  * more on level 2
  * ... 

However when I try to do this using just the rich text plugin, it seems to only support shallow lists (going only to level 1).

I noticed this feature _is_ supported in exactly the way I want on the [Lexical Playground](https://playground.lexical.dev/) editor, however I looked at the code and it seems to be doing a lot of custom in-house stuff that is not baked into the provided packages. I would like to get nesting to work without having to do a bunch of manual configuration like how pressing Tab should indent, hitting Enter twice breaks out of the list, etc

I tried to pull in code from the playground repo, which I probably could eventually get working, but this feels like something that should be supported out of the box.

Otherwise, nice work on this editor! I really like the plugin API 😁

**Comment by acywatson** [comment]
You can use ListPlugin from @lexical/react for this:

https://github.com/facebook/lexical/blob/737f8811254ff499755ac5ab5535a736fe9b142a/packages/lexical-playground/src/Editor.tsx#L157

If you’re not using React you can use @lexical/list exports directly.

**Comment by ssalka** [comment]
Awesome, thank you @acywatson! I thought this plugin's behavior was baked in to the rich text plugin.

I did want to call out 1 visual bug, where multiple bullets can be seen on 1 line:

<img width="444" alt="Screen Shot 2022-10-06 at 10 34 40 AM" src="https://user-images.githubusercontent.com/12151879/194380952-452a96fa-6140-4078-8a29-c3903ba13bc2.png">

I doubt this is the intended behavior, but maybe I'm wrong? Anyway, I was able to patch this myself with the following:
```css
[data-lexical-editor] li:has(ul) {
  list-style-type: none;
}
```

Since this CSS tweak suffices for me, I don't feel the need to file a separate issue for this, but if it would help you / the team, I could do so.

**Comment by trueadm** [comment]
> Awesome, thank you @acywatson! I thought this plugin's behavior was baked in to the rich text plugin.
> 
> I did want to call out 1 visual bug, where multiple bullets can be seen on 1 line:
> 
> <img alt="Screen Shot 2022-10-06 at 10 34 40 AM" width="444" src="https://user-images.githubusercontent.com/12151879/194380952-452a96fa-6140-4078-8a29-c3903ba13bc2.png">
> 
> I doubt this is the intended behavior, but maybe I'm wrong? Anyway, I was able to patch this myself with the following:
> 
> ```css
> [data-lexical-editor] li:has(ul) {
>   list-style-type: none;
> }
> ```
> 
> Since this CSS tweak suffices for me, I don't feel the need to file a separate issue for this, but if it would help you / the team, I could do so.

You can use the theme to do this too: https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts#L67
