### ISSUE TITLE
Feature: generateHtmlFromNodes cannot change Iframe tag.

### ISSUE THREAD

**Issue by Heyholder** [facebook/lexical#3127]
generateHtmlFromNodes function cannot change Iframe tag.

`<div class="PlaygroundEditorTheme__embedBlock"><iframe id="ql" width="560" height="315" src="https://www.youtube.com/embed/vfNq4zb-Oow" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" title="YouTube video"></iframe></div> `

```
 editor.getEditorState().read(() => {
    const htmlString = $generateHtmlFromNodes(editor, null);
    console.log(htmlString)}

```
console shows just
`<p class="PlaygroundEditorTheme__paragraph"><br></p><div></div><p class="PlaygroundEditorTheme__paragraph"><br></p><p class="PlaygroundEditorTheme__paragraph"><br></p>
`

**Comment by acywatson** [comment]
exportDOM on the Node class controls how the node is serialized to HTML:

https://lexical.dev/docs/concepts/serialization#lexicalnodeexportdom
