### ISSUE TITLE
Feature: Normalization API

### ISSUE THREAD

**Issue by DaniGuardiola** [facebook/lexical#3141]
## Problem

When building a text editor, it's common to want to enforce some normalizations and constrains, e.g. merging adjacent lists together, disallowing certain heading levels, or establishing a max indentation for some blocks. Currently, in Lexical, some of these constrains can be enforced with techniques like registering node transforms, editor update listeners or commands that undo or modify certain updates before they happen.

However, there are some fundamental problems with this approach that make it a leaky and incomplete solution:

- Registering a command works as long as all plugins use that command for a certain operation (e.g. insert a heading node), but that's not the case. For example, some transforms in the markdown shortcuts plugin don't use these commands, and therefore the updates are allowed.
- Normalization isn't always required only on updates, sometimes you'll want to apply it on the initial state, which AFAIK doesn't fire commands or node transforms.
- Having to take into account these many APIs for each normalization is tedious and prone to bugs, and it's easy to miss some instances.
- In some cases, it's also necessary to enforce these constrains outside of the lifecycle of the editor itself, for example in the server when storing a lexical state in a database. Ideally the headless package could be used to run the normalization server-side.

## Proposal

Implement a proper normalization API like Slate's: https://docs.slatejs.org/concepts/11-normalizing

This could be very useful, even for core plugins and built-in constrains, see related comment: https://github.com/facebook/lexical/issues/2800#issuecomment-1221143560

A highlight of this API is the multi-pass system that makes it easier to write constrains: https://docs.slatejs.org/concepts/11-normalizing#multi-pass-normalizing

**Comment by DaniGuardiola** [comment]
cc @acywatson

**Comment by EgonBolton** [comment]
Related https://github.com/facebook/lexical/issues/1338

**Comment by trueadm** [comment]
Lexical already normalizes basic text nodes. We could expose a way for user controlled normalization too. However, I feel the better approach is to improve the scheme of nodes, in that plugins and core better align with methods that define hierarchy or relationships between types of nodes and their position in the tree.

**Comment by DaniGuardiola** [comment]
@trueadm not sure what that would look like, and what the difference would be with a normalization API?

**Comment by acywatson** [comment]
> @trueadm not sure what that would look like, and what the difference would be with a normalization API?

I think this is sort of the crux of it - there isn't much of a difference, save for whether the logic is centralized in one place or spread across and encapsulated within individual node classes. Historically, we have tended towards the latter, enforcing a sort of proto-schema via methods on the node base classes that define their behavior with respect to each other.

The issue with that setup is that these methods are just called all over the place in different modules and utilities, making it hard to reason about the actual behavior in different scenarios. It can also be hard to debug - I see this come up a lot on discord. The alternative, more "imperative" approach of defining a schema centrally and having it enforced consistently in a single place ameliorates that, but comes with it's own trade-offs, I guess.

**Comment by trueadm** [comment]
We plan on incorporating normalization into schemas. Closing for now.

**Comment by DaniGuardiola** [comment]
@trueadm is there information about schemas anywhere that I could check? Link? :pray:

**Comment by trueadm** [comment]
@DaniGuardiola Not right now. Bear with us, we're still exploring this space before sharing it widely.

**Comment by hoetmaaiers** [comment]
Curious if there is an indication on when this might be availlable. Is this part of a roadmap?
