### ISSUE TITLE
Bug: arrow keys do not move cursor in and out of nested editor wrapped in `contenteditable="false"` in Firefox

### ISSUE THREAD

**Issue by GiacomoRandazzo** [facebook/lexical#3143]
Lexical version: 0.5.0

## Steps To Reproduce

1. Open [Lexical Playground](https://playground.lexical.dev/)
2. Insert sample image
3. Add a caption
4. Try pressing the up or down arrow keys to move the cursor from the caption to the parent editor. This will work in Chrome but not in Firefox

## The expected behavior

We expect the cursor to move in and out of the nested editor as in Chrome.

It is a Firefox limitation, the problem can be reproduced by having:

```html
<div contenteditable="true">
  <div contenteditable="false">
    <div contenteditable="true">1</div>
    <div contenteditable="true">2</div>
  </div>
</div>
```

In Chrome the cursor can be moved freely between the first and second div with the arrow keys. The same is not true for Firefox.
Here's a related Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1289880

**Comment by thegreatercurve** [comment]
Thanks for the report @GiacomoRandazzo! 

I'm going to close this though as I'm not sure what we can within Lexical to fix the issue. We tend to use browser-sniffing logic to fix only critical bugs (e.g. composition and pasteboard issues), and this arrow navigation seems more like an inconsistency than a blocking bug.

The error report on the Firefox side seems to encapsulate the issue well enough, and even though its old, it seems they've increased its importance only a few days ago.

**Comment by GiacomoRandazzo** [comment]
Ok, hopefully they will fix it on the Firefox side!
