### ISSUE TITLE
Feature: editor update listener without selection updates

### ISSUE THREAD

**Issue by DaniGuardiola** [facebook/lexical#3144]
I'm looking for a way to register a listener that is only fired when the editor state changes in any way other than a change in the selection state. The `registerTextContentListener` method gets really close, but I'd like something more generic as listening for text content changes feels hacky and potentially edge-casey for waht I need. I also suspect that `registerTextContentListener` might penalize performant if it needs to compute the text content value on every update, which I assume is not what happens by default.

**Comment by trueadm** [comment]
The text content listener has no performance impacts as we use cached text contents on updates. If you just want to know if something changed other than selection the update listener is still what you want. You get passed arguments with a dirty elements Map which you can use to determine if the change was selection only.

**Comment by DaniGuardiola** [comment]
@trueadm thanks, that covers this use case IMO so closing
