### ISSUE TITLE
Feature: Add react TreeViewPlugin

### ISSUE THREAD

**Issue by wilbertom** [facebook/lexical#3149]
The `@lexical/react` package provides the `TreeView` component but not a `TreeViewPlugin`. The plugin is easy to implement but, it would be nice if it were built into the react package. Right now, it is implemented in the playground so it would mostly be a matter of moving it to the react package.

I added it to my own project and it works OK out of the box:

```ts
function TreeViewPlugin() {
  const [editor] = useLexicalComposerContext();

  return (<TreeView
    viewClassName="tree-view-output"
    timeTravelPanelClassName="debug-timetravel-panel"
    timeTravelButtonClassName="debug-timetravel-button"
    timeTravelPanelSliderClassName="debug-timetravel-panel-slider"
    timeTravelPanelButtonClassName="debug-timetravel-panel-button"
    editor={editor}
  />)
}
```

![Screenshot 2022-10-10 at 03-13-28 Screenshot](https://user-images.githubusercontent.com/2273055/194823523-bbce8516-963b-4fdf-9938-4029775c2fd9.png)

If the feature does get added to react, would it need a `theme` for the class names?

**Comment by acywatson** [comment]
> The `@lexical/react` package provides the `TreeView` component but not a `TreeViewPlugin`. The plugin is easy to implement but, it would be nice if it were built into the react package. Right now, it is implemented in the playground so it would mostly be a matter of moving it to the react package.
> 
> I added it to my own project and it works OK out of the box:
> 
> ```ts
> function TreeViewPlugin() {
>   const [editor] = useLexicalComposerContext();
> 
>   return (<TreeView
>     viewClassName="tree-view-output"
>     timeTravelPanelClassName="debug-timetravel-panel"
>     timeTravelButtonClassName="debug-timetravel-button"
>     timeTravelPanelSliderClassName="debug-timetravel-panel-slider"
>     timeTravelPanelButtonClassName="debug-timetravel-panel-button"
>     editor={editor}
>   />)
> }
> ```
> 
> ![Screenshot 2022-10-10 at 03-13-28 Screenshot](https://user-images.githubusercontent.com/2273055/194823523-bbce8516-963b-4fdf-9938-4029775c2fd9.png)
> 
> If the feature does get added to react, would it need a `theme` for the class names?

I don't have a problem with this - PR welcome. Wonder if the core logic could live in dev-tools package and we could separate out the react bindings.

Theme sounds like a good idea instead of individual class name props.

**Comment by thegreatercurve** [comment]
> I don't have a problem with this - PR welcome. Wonder if the core logic could live in dev-tools package and we could separate out the react bindings.

This is a good point. We can export a plugin version of the tree view for the moment, but in the long run I think we should deprecate both components entirely and instead ask developers to use the browser extension developer tools. 

It currently has the same parity of features as the `TreeView`, but @im-adithya is working with us on significantly upgrading it further over the next couple of months. It should then be ready to publish at some point early next year.

**Comment by thegreatercurve** [comment]
Closing this as this will eventually be replaced by the devtools extension
