### ISSUE TITLE
Revisit generics

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#3152]
Possible improvement to Flow typing of .getChildren()?

The current Flow type of .getChildren() assumes that it gets a generic type argument (https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdAJlrgDbKVxtroAyWAD2C5krAHIRmcAN4BfBs26duqdAFFWWEFgB2MCVMExdjPoOGiDWGXThwA9PbgwAFllTWAYqwgB3ZwCeYO5cJNZEJHD8QiKsAHQAVqhxBD6+tnAA5lgwAMIuwKyMlDoAPAAqAFxR5rFWAHwAFACU1QCCUFDIARX19HbZeQVFJRXtnd2l0Rbiklj1Ta1w5fTyTCzsyuyqcABqogCuWFZwRiZmMZZzMmsEBzr4wBA6cAAkwKj7rEdWjTpz1WmdTmSwARhAIJpkC8AKS4Ny4ADW6GkGUoMAOUBe-ykwB0qBg0NwWAgBD2h2Oc1WCg2HGsKnQAFldDAnjoTmcdKYapdZlI5Aw7g9Wc83h9mXo2b8cVhAbUrswwRCobD4SxkTY7OjMdjrniCUSSWSJSL2VS6GtHM4CugPnBfMQdJkADTWu3aVySODarHoDpdHpfH7XAA+cBNUrm9ToQseouMBIAjH8AXANFoWVYlv7JkHKcx6prvTkdXAZXFBvlCsVdC0MnY4pRGAdiY163Y4I0OFBXfDq804ABeaMd0diz4U359ooDkNh96oCPPKfDRgDgD8cAA2nFd93e6uALpwar79t2LeH53t5rUuhW1x2u0O54ut3oD0uL0+-FwHOBydQ3DFlIwLGN7jjF4ExgAAmFNmGqdNtD0LNxgDUo8waItcGeAk4AAN0A5h0EHbdD36OACGgTscPxeBp0YOBSTLOYKxyKsRlrZoB1RUdgDJRoF0wuZGgY2d53FEDlxEsSePPAiiPcOIwAOVAXFE1db3beQ7B04sMSxBTvnzdw7wfG04GfR030fD8ci-Rifz9CYAOMk4wyXM0wNjU1nHcGAAGZ4NlNNNGQ-QQTQ3NFMLXj9NLctK1XUYgQVeY61HRssGbVt5K7ToD37IcRzHOwhMUjSirncdPJXIrNx3PcCq4I8TxQAr5Mva9Ry0y0nFsyz0BfJ1XQGz9vxLX0-xcjDFLgDypK8+ZwOFNk-IJAAWYLELCzNIum9DhILbDcPgQi3LmEiyIoqioBo06WurJiyUS9jkt0KZ5T5dLuKLOx+M7cqLuYSqZ3miTF0WuqZzk0rzuDYjlNU9SxIo3SMj0n8jIR0yLSAA).
If this type argument is not provided, it returns Array<empty> which can then prevent Flow from type checking how the results of .getChildren() are used.

Here's an example in Flow playground: https://www.internalfb.com/code/www/[35de00ce560c91847885bdcc609825f7c94369f3][history]/html/shared/lexical/Lexical.js.flow?lines=673-674

This isn't strictly speaking an error, but it's pretty hard to figure out that .getChildren() wants the generic type argument which can lead to bugs in the user code.

-- @olegbl

**Comment by zurfyx** [comment]
Agree. This is on the low-hanging fruits of things to revisit. The generics are not only annoying but also a lie. You can potentially handle the wrong values by typing a wrong generic and it won't tell you otherwise.

This, like some others API methods, should return a LexicalNode instead.

**Comment by trueadm** [comment]
Descoping for now.
