### ISSUE TITLE
Bug: Press "Delete" on a paragraph after decorator nodes removes the node

### ISSUE THREAD

**Issue by Piliuta** [facebook/lexical#3155]
When the cursor focus is set on a paragraph next to a decorator node (not inline) pressing the "Delete" ("Backspace") key removes the node.

Lexical version: 0.5.0

## Steps To Reproduce

1. Add any non-inline decorator node to the editor (e.g. Horizontal Rule)
2. Add a paragraph next to this node
3. Press "Delete" key

https://user-images.githubusercontent.com/1575198/195064627-51352f1a-5f50-4aee-ad19-d6b3a571b243.mov

## The current behavior
Pressing "Delete" key before a non-inline decorator node removes the node.

## The expected behavior
Removing an empty paragraph should not remove the decorator node on pressing "Delete" key.
If the paragraph (or the start of whatever non-inline block) is not empty it should remove the node above, i.e. if the merge cannot be resolved into a valid state.

**Comment by thegreatercurve** [comment]
@Piliuta What browser and OS are you using for this bug? is this I'm struggling to replicate this on Chrome.

**Comment by Piliuta** [comment]
> @Piliuta What browser and OS are you using for this bug? is this I'm struggling to replicate this on Chrome.

_I am on Mac OS in Chrome._

I am sorry, I meant to say "that button on the right top corner that I never look at" the "Delete" (or "Backspace" on windows) button 😳. I updated the description.

**Comment by thegreatercurve** [comment]
Just to confirm, if the paragraph node after a decorator node is empty, on hitting "Delete" whilst selection is within the empty paragraph node, you expect the empty paragraph to disappear and the decorator node to become selected? Similar to how it is on ProseMirror.

https://user-images.githubusercontent.com/7748470/195388657-4c7d2374-079b-4a4a-a852-afeb680a0e5e.mov

I can't find the related issue but I think I've seen this mentioned elsewhere. I think the discussion boiled down to it isn't really a bug, it's just a choice we made that if a user hits delete/backspace, the decorator node or character before the carat should be deleted.

Maybe someone else knows different?

**Comment by Piliuta** [comment]
> Just to confirm, if the paragraph node after a decorator node is empty, on hitting "Delete" whilst selection is within the empty paragraph node, you expect the empty paragraph to disappear and the decorator node to become selected? Similar to how it is on ProseMirror.

Yes, exactly. And this is how many other advanced editors behave (or at least they do not remove the content ahead). 

> I can't find the related issue but I think I've seen this mentioned elsewhere. I think the discussion boiled down to it isn't really a bug, it's just a choice we made that if a user hits delete/backspace, the decorator node or character before the carat should be deleted.
> 
> Maybe someone else knows different?

Would be happy to know what was the driver for that decision if that was the case. However, I do not think that's the best decision.

**Comment by Fonger** [comment]
I'm facing the same issue.
If a user insert two block node continously, there's no way for a user to remove the empty paragraph between two block node.

![image](https://user-images.githubusercontent.com/5862369/196070947-ecb73b27-1bb1-45df-a4cc-ad9c940120d0.png)


Two cases shoudl be handled:
- If you hit **backspace** on an empty paragraph after a block node, the block node should not be removed too.
- If you hit **delete** on an empty paragraph before a block node, the block node should not be removed too.

Right now I'm using the following code to achieve this:


```ts
editor.registerCommand<KeyboardEvent>(
  KEY_BACKSPACE_COMMAND,
  event => {
    if (isTargetWithinDecorator(event.target as HTMLElement)) {
      return false;
    }
    const selection = $getSelection();
    if (!$isRangeSelection(selection)) {
      return false;
    }
    event.preventDefault();

    // detect empty node
    const nodes = selection.getNodes();
    if (
      nodes.length === 1 &&
      $isParagraphNode(nodes[0]) &&
      nodes[0].isEmpty()
    ) {
      nodes[0].remove();

      return true;
    }

    return editor.dispatchCommand(DELETE_CHARACTER_COMMAND, true);
  },
```

**Comment by trueadm** [comment]
Should be fixed.
