### ISSUE TITLE
Bug: Impossible to set cursor between decorator nodes using mouse

### ISSUE THREAD

**Issue by Piliuta** [facebook/lexical#3157]
Setting the cursor between two non-inline decorator nodes is not possible to do.

Lexical version: 0.5.0

## Steps To Reproduce

1. Add two non-inline decorator nodes (e.g. tweet node)
2. Ensure there are no other nodes between them (e.g. removing empty space is not possible due to this issue https://github.com/facebook/lexical/issues/3155, use drag actions to stack the nodes)
3. Attempt to set cursor position anywhere between the nodes using the mouse

https://user-images.githubusercontent.com/1575198/195076123-d7c0ff98-d698-42f8-9376-689f2bb4b1ec.mov

## The current behavior
- Click on the decorator node selects, typing in the "selected" does nothing
- Click before or after the decorator node sets the cursor position after the last decorator node

## The expected behavior
_**Proposal**_ clicks on the left or right side of a non-inline decorator node will set the caret before or after the node accordingly.

**Comment by trueadm** [comment]
The way we tackle this is to ensure you can select the nodes, then upon pressing left/right you can move the cursor to in between. Not all decorators have node selection enabled on them, but horizontal rule nodes do and you can see this behavior there.

**Comment by Piliuta** [comment]
> The way we tackle this is to ensure you can select the nodes, then upon pressing left/right you can move the cursor to in between. Not all decorators have node selection enabled on them, but horizontal rule nodes do and you can see this behavior there.

Such behavior is not practical for a few reasons:
- It is not intuitive and not very common. You have to be really a pro user to know it is possible.
- _As you already mentioned_, not all decorators have node selection and thus, setting the caret between such nodes is not possible.
- Node selection can be implemented differently if their content is supposed to act differently to click events and selection is triggered say with some sort of a handler button, in which case that flow to set the caret becomes even more confusing.
- After all, most of the powerful editors allow clicking near _nodes_ to set the caret before or after, so missing such a feature does feel great.

Is this something that can be considered added to the lexical as a core behavior? Do you have any plans for it?

**Comment by trueadm** [comment]
I think this should still be handled as part of the decorator as they’re meant to own and control selection - not the core. So if you wanted localized click handling you could add a click handled to the editor element that tracked +/- 10px of edge and moved range selection upon the click. This could be packages up as a React hook or something so nodes can use them as a one liner

**Comment by zurfyx** [comment]
Closing as emulated cursors should address this.
