### ISSUE TITLE
Bug: Playwright VS Code extension works in other projects but not in Lexical

### ISSUE THREAD

**Issue by EgonBolton** [facebook/lexical#3167]
I can use the command line to run tests.
I can also use the VS Code extension to run tests on an entire file in debug mode.

What I can't is:
- Display and view the individual tests of a file.
- Display the buttons to run tests inside the file.
- Run the tests in headless mode.

Lexical version: 0.5.0

## Steps To Reproduce

1. `git clone https://github.com/facebook/lexical`
2. `cd lexical`
3. `npm install`
4. `npm run dev`
5. Go to the VS Code "Tests" tab, and expand the test tree until you reach the file level, it will not expand further.
Go to a file with tests. Where each test starts there should be a button to run it, but there isn't.

## The current behavior
https://www.loom.com/share/e5077edd617b4ed4bb9ae20493fe847d

## The expected behavior
https://www.loom.com/share/50079aa607d44b1ab8dbffbd6ea90020

**Comment by thegreatercurve** [comment]
This seems more like an environment bug or an issue with the VSCode plugin than Lexical, specifically. Also, I'm able to install VSCode Test Runner plugin myself and run the tests as expected: 

<img width="778" alt="image" src="https://user-images.githubusercontent.com/7748470/195623392-f491d768-4957-4a15-8a38-60cce81ed7cd.png">
