### ISSUE TITLE
Bug: `0.5.0` missing `wrapLeafNodesInElements` in `@lexical/selection`

### ISSUE THREAD

**Issue by ScottAgirs** [facebook/lexical#3179]
`v0.4.1` still had an export `wrapLeafNodesInElements` from `@lexical/selection`, starting with 0.5.0 it appears to be missing. I combed through the changelog, and wasn't able to find any notes on that - perhaps an oversight?

Lexical version: 0.5.0

## Steps To Reproduce

1. https://codesandbox.io/s/bold-brahmagupta-r5c8gu
2. Try creating a Code Block.

Error:
<img width="853" alt="Screen Shot 2022-10-14 at 11 18 26 AM" src="https://user-images.githubusercontent.com/11737572/195798077-92ffa494-c889-4f40-b469-49989b0c91a4.png">

**Comment by thegreatercurve** [comment]
The name of this was changed to just `wrapNodes` in #3020
