### ISSUE TITLE
Bug: stacking bug with grammerly playground demo

### ISSUE THREAD

**Issue by Ne-Ne** [facebook/lexical#3180]
Lexical version: latest

## Steps To Reproduce

1. Load the official playground from the website

Link to code example -> https://playground.lexical.dev/

## The current behaviour

Lexical icons sit on top of Grammarly

<img width="1163" alt="Screenshot 2022-10-14 at 11 46 22" src="https://user-images.githubusercontent.com/2177851/195829885-ed405502-6bbb-4d57-8b22-3818e74e07cf.png">

## The expected behaviour

Not to sit above or let users easily click the UI

**Comment by trueadm** [comment]
Sounds like a grammarly bug? I guess we could have the action buttons hidden and they get shown on pressing some button

**Comment by Ne-Ne** [comment]
I can’t see Grammarly adjusting UI just for this product (although I could be wrong).

I wonder if there is some css positional tweaks which could be done if the UI.

Will take a look in the next few days.

**Comment by acywatson** [comment]
Yea seems like a simple CSS fix - PR welcome. I wonder if Grammarly has configuration options to determine where that icon is positioned.

**Comment by acywatson** [comment]
I looked more at this and I think those buttons used to be outside the editor element. Not sure when that changed.

**Comment by thegreatercurve** [comment]
Validated that this now works.
