### ISSUE TITLE
Feature: EditorState being editable from NodeJS backend

### ISSUE THREAD

**Issue by darinageo** [facebook/lexical#3187]
Hi Lexical Team,

I'd like to start with that I am a huge fan of the Lexical Editor and extremely thankful to the whole team behind it!

I am working on a project where I'd like to expose API so that I can edit the Lexical document from the backend. This is similar to Google Docs API https://developers.google.com/docs/api/how-tos/move-text 

However, I've found out that I cannot programmatically load and edit the lexical state from the backend (NodeJS). I'd like to have the option to load the editor state into the backend service, edit the state there and then serialize and save to db.

I found that if we create a lexical editor and try to load the state in the following way 
```
  const editor = createEditor()
  const state = editor.parseEditorState(loadContent());
  editor.setEditorState(state);
```

it throws exceptions because it requires the `window` browser object . I also tried to import `jsondom` and `window` packages into NodeJS but there are a lot of browser related functions that need to be "mocked" so it doesn't look like a sustainable way.

I hope this can help other Lexcial users too!

Best wishes!

**Comment by acywatson** [comment]
Hey @darinageo! Have you tried running Lexical in Headless Mode?

https://lexical.dev/docs/packages/lexical-headless

That should enable your use case. Please re-open if you still have problems.

**Comment by darinageo** [comment]
Ah! Thank you very much @acywatson!! 

I've tried to use the @lexical/headless following the main example in the docs above :

```
const { createHeadlessEditor } = require('@lexical/headless');

const editor = createHeadlessEditor({
  nodes: [],
  onError: () => {},
});

editor.update(() => {
  $getRoot().append(
    $createParagraphNode().append(
      $createTextNode('Hello world')
    )
  )
});
```
and when trying to access the editor state via `editor.getEditorState().toJSON()` I get an empty array for the root children and wonder why the `'Hello world'` string is not part of the children array. 
```
 {root: Object {children: [], direction: null, format: "", indent: 0, type: "root", version: 1}}
```
If you can please point me in the right direction it will be very much appreciated!

**Comment by Aminoser** [comment]
@darinageo hi. Could you let me know if you found a solution? I have a similar case: I get the text from the database and want to convert it and write it to the same database but after the conversion. I also use @lexical/headless and as a result, I see an empty array for the root children.

Found a [working example](https://codesandbox.io/s/exciting-engelbart-mr2zhg?file=/src/Components/plugins/LoadingHTMLData.ts) (client-side) for finding solutions. And here the same thing - if you use @lexical/headless (editor2) - an empty children array.

**Comment by Aminoser** [comment]
Shortly after writing the question, the solution was found - Lexical updates are async, so simple await solves my problem
