### ISSUE TITLE
Feature: programmatically decrease heading levels within the editor.

### ISSUE THREAD

**Issue by ScottAgirs** [facebook/lexical#3189]
I'm working on re-using Lexical for both - using it for a naive page builder as well as offering users to create their own blog posts.

It would be nice if Lexical had some prop that would control the heading levels (their tags). For example, a prop `decreaseHeadingBy` (or something less verbose) could take in an integer that would then reduce the heading level of the one that user inputs by the provided amount.

Example usage:
```javascript
const initialConfig = {
    editorState: emptyEditor ? undefined : undefined,
    nodes: [...Nodes],
    // ....
    decreaseHeadingBy: 1
  };
```

And the above would result in:
- Heading 2, when user selects Heading 1
- Heading 3, when user selects Heading 2
- etc ...

# Why?
This would be nice for SEO and Lighthouse, since if a platform developer creates layout with Heading as `<h1 />` baked into the design and then user adds another Heading 1 in their article (not perhaps knowing the ins and outs of SEO best practices), the page would result in 2 `<h1 />` headings.

**Comment by acywatson** [comment]
You should be able to achieve this without a configuration option. Can you just prevent the user from inserting H1s in cases where they shouldn't? Alternatively, you could have a [transform](https://lexical.dev/docs/concepts/transforms) that adjusts the level of HeadingNodes. [Mutation listeners](https://lexical.dev/docs/concepts/listeners#registermutationlistener) might also work for this case.

**Comment by ScottAgirs** [comment]
@acywatson thank you for the suggestions, that's awesome. I will look into those options, but - before I do (or after I do, not the point, haha) - I would love to argue that this type of functionality could potentially be easy to add to the core features for folks who are well-versed in the ins and outs of Lexical transformations/mutation listeners, while at the same time it could be quite tedious and time consuming for those who are new to Lexical and Rich Text editors in general.

Additionally, I would argue that this functionality could be quite useful to many, what do you think? All above mere thoughts... :)

**Comment by acywatson** [comment]
It's probably true that it'd be easier for us to do, but we created the plugin system because we wanted to library to be extensible for use cases like this without us having to develop and maintain an API for every imaginable use case. In this instance, a plugin could be as simple as:
```
export function MaxHeadingPlugin(props: { maxHeadingLevel: 1 | 2 | 3 | 4 | 5 }) {
  registerNodeTransform(HeadingNode, (node) => {
   const level = parseInt(node.getTag()[1]);
    if (level > maxHeadingLevel) {
      node.setTag(`h${maxHeadingLevel}`);
    }
  })
}

<LexicalComposer>
  <MaxHeadingPlugin maxHeadingLevel={2}
</LexicalComposer>
```

Not that hard to write, but then when people start using it and asking for small changes to it and asking questions about why it works this way or why it doesn't work that way, it becomes more of a burden.  That's why we encourage people to do these things on their own unless they serve a pretty broad use case.

**Comment by acywatson** [comment]
I'm gonna close this one for now - appreciate the feedback and ideas!

**Comment by ScottAgirs** [comment]
Hey @acywatson sorry missed the reply : )

Thanks so much for clarifying and the snippet, pretty neat! 

The reasoning is quite understandable too and makes sense, thanks again!
