### ISSUE TITLE
Bug: Node transforms are not called when setting editor state

### ISSUE THREAD

**Issue by sebakerckhof** [facebook/lexical#3200]
When setting the editor state using `editor.setEditorState`, node transforms (registered via `registerNodeTransform`) are not executed.

Lexical version: 0.5.0

## Steps To Reproduce

1. Register a node transform, e.g. use the emoticons example: https://github.com/facebook/lexical/blob/main/examples/emoticons.md#insert-emoticonnode

2. Set the editor state to something that includes a part that should be replaced.

## Link to code example:
https://codesandbox.io/s/lexical-plain-text-example-forked-6uqd0o?file=/src/Editor.js

-> When you type `:)` it will transform the emoji
-> When you press `Set editor state` button below the editor, it will not call the transform and instead it just shows `:)`

## The current behavior

Transforms are not called

## The expected behavior

Transforms are called the same way as when typing

**Comment by acywatson** [comment]
https://github.com/facebook/lexical/discussions/3055

**Comment by leandronorcio** [comment]
This bug still exists, maybe this needs to be reopened?
