### ISSUE TITLE
Bug: backspacing into a comment mark deletes the entire mark at once

### ISSUE THREAD

**Issue by knpwrs** [facebook/lexical#3215]
Lexical version: [573a716](https://github.com/facebook/lexical/commit/573a716ef97218927007943689c420a8749107ce)

## Steps To Reproduce

1. Leave an inline comment in the playground
2. With the caret inside the mark you can delete text as you would expect
3. If you have the caret outside the mark (after the end) and then backspace into the mark, as soon as you hit the mark it is deleted all at once.

![markbug](https://user-images.githubusercontent.com/174864/196550153-1ad88a18-eef8-46ab-96f5-5f56a2bac2cf.gif)

Link to code example:

https://github.com/facebook/lexical/tree/573a716ef97218927007943689c420a8749107ce/packages/lexical-playground

## The current behavior

Backspacing into a mark deletes the whole mark. Think this happens because `MentionNode` extends `TextNode`, whereas `MarkNode` extends `ElementNode`. Is there a way to make `ElementNode` behave like `TextNode`, or otherwise make `MarkNode` extend `TextNode` instead of `ElementNode`?

## The expected behavior

Backspacing into a mark should delete the text in the mark character-by-character, like what happens with mentions in normal mode (as opposed to segmented or token modes).

**Comment by trueadm** [comment]
@fantactuka If you get bandwidth, would you mind looking into this issue? Someone reported something similar internally.

**Comment by fantactuka** [comment]
It seems to be working fine now:

https://user-images.githubusercontent.com/132642/216501358-d85641ce-e513-4abe-8bbc-c81d62cfbd28.mov

@knpwrs  feel free to reopen if still have the issue

**Comment by benjick** [comment]
@fantactuka it works because you place the cursor inside the MarkNode, if you move it further to the right and backspace into the MarkNode you will see the behavior

**Comment by etrepum** [comment]
@benjick I can't reproduce it. If you can, please create a new issue with explicit instructions for exactly how to reproduce including a video that shows it happening and a note of which browser you are using.

**Comment by benjick** [comment]
@etrepum I've done some more testing and it seems to be a Firefox only issue. I've created a new issue with video: https://github.com/facebook/lexical/issues/7049
