### ISSUE TITLE
ListNode dangerously executes update logic on createDOM

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#3227]
`createDOM` was designed to render on the DOM. It can happen synchronously and asynchronously but ultimately it translates node data into DOM.

List leverages createDOM to do a last-minute update logic, in particular in `updateChildrenListItemValue`

```
  createDOM(config: EditorConfig): HTMLElement {
    const element = document.createElement('li');
    const parent = this.getParent();

    if ($isListNode(parent)) {
      updateChildrenListItemValue(parent);
      updateListItemChecked(element, this, null, parent);
    }
    element.value = this.__value;
    $setListItemThemeClassNames(element, config.theme, this);

    return element;
  }
```

```
export function updateChildrenListItemValue(
  list: ListNode,
  children?: Array<ListItemNode>,
): void {
  (children || list.getChildren()).forEach((child: ListItemNode) => {
    const prevValue = child.getValue();
    const nextValue = $getListItemValue(child);

    if (prevValue !== nextValue) {
      child.setValue(nextValue);
    }
  });
}
```

This is dangerous because the error-recovery mechanism only applies to the update and transforms, not the reconciliation; and this can translate to a crashed UI and potentially bad collab updates.

**Comment by trueadm** [comment]
I think this has been the cause of some complex collab bugs internally after looking at a recent error report. I think we should prioritise this.

**Comment by acywatson** [comment]
> This is dangerous because the error-recovery mechanism only applies to the update and transforms, not the reconciliation

As discussed offline, I don't think is actually true. We [catch and attempt to recover from errors during reconciliation](https://github.com/facebook/lexical/blob/230903f0f536b8d1a84f2ca43dbb390e9a7f9063/packages/lexical/src/LexicalUpdates.ts#L470), AFAIK. That's not to say this logic is correct - just want to avoid red herrings here.
