### ISSUE TITLE
Bug: selectionTransform is not a function

### ISSUE THREAD

**Issue by strdr4605** [facebook/lexical#3237]
We were penetrating the collab feature with the whole team (~10 users), and we got this error for some users.
Maybe @trueadm has an idea why this may happen.

Lexical version: 0.5.0

## Steps To Reproduce

We don't have clear steps to reproduce (maybe we will understand the steps when our users will report this issue).

## The current behavior

![image](https://user-images.githubusercontent.com/16056918/197202586-0f1787ed-3327-4f69-8c89-ade361160a3e.png)

**Comment by trueadm** [comment]
A hunch would be that the selection objects aren't valid? This is where they're called:

https://github.com/facebook/lexical/blob/d248de02b75f86b540dd14ceb33d9febf40e5f52/packages/lexical/src/LexicalSelection.ts#L2558-L2563

If you could maybe debug what `anchorNode` and `focusNode` are before that method is called, we can maybe see what is happening.

**Comment by strdr4605** [comment]
I will try to find a consistent way to reproduce this issue and debug it

**Comment by thegreatercurve** [comment]
Any update on this issue @strdr4605? Closing this for the moment due to inactivity.
