### ISSUE TITLE
Bug: Virtual keyboard can't be closed in mobile Chrome

### ISSUE THREAD

**Issue by granmoe** [facebook/lexical#3242]
Lexical version: Same as Playground version
Mobile Chrome v106.0.5249.92
iOS 15.6.1

## Steps To Reproduce

1. Go to [Lexical playground](https://playground.lexical.dev/) in mobile Chrome
2. Focus the editor
3. Click the "Done" button in the virtual keyboard

Link to code example:

## The current behavior

Cannot close the virtual keyboard via the "Done" button.

## The expected behavior

Virtual keyboard should close

## Workaround

You can listen to touchstart and touchend and blur the editor in mobile when the user swipes down a certain distance, but this brings some caveats since we don't want to blur on any swipe down movement (e.g. when selecting text for copy/cut, probably other examples).

**Comment by thegreatercurve** [comment]
Thanks for the report @granmoe

This seems like a Chromium specific issue. I can replicate the issue on the ProseMirror home page. Also, the bug didn't exist in an older version of mobile Chromium (~83) which I had on my phone before upgrading.

Submitted a bug report here for Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1378056

Closing so this can be tracked there.
