### ISSUE TITLE
Bug: Unable to convert markdown to editor state in headless mode

### ISSUE THREAD

**Issue by alexluong** [facebook/lexical#3244]
Lexical version: 0.5.0

## Steps To Reproduce

Use `$convertFromMarkdownString` in headless mode.

Link to code example: https://replit.com/@alexluong/RelievedLopsidedConversions#index.ts

## The current behavior

When console.log the editor state after running `$convertFromMarkdownString`, it shows an empty root.

## The expected behavior

Log root with a heading and a paragraph element.

## Use case

My use case is I want to import users' markdown content from other platforms into my application where I'm using Lexical editor.

**Comment by acywatson** [comment]
You can use this: https://github.com/facebook/lexical/blob/d248de02b75f86b540dd14ceb33d9febf40e5f52/packages/lexical/src/LexicalEditor.ts#L60

**Comment by alexluong** [comment]
Thanks for the response, that works perfectly!
