### ISSUE TITLE
Bug: Add HR to the default Markdown transformers

### ISSUE THREAD

**Issue by thegreatercurve** [facebook/lexical#3250]
HRs are valid markdown, so we should expose it through the markdown package.

**Comment by trueadm** [comment]
HRs depend on React right now do they can’t really living without the markdown package depending on React too. Tricky one to decouple.

**Comment by acywatson** [comment]
> HRs depend on React right now do they can’t really living without the markdown package depending on React too. Tricky one to decouple.

Weren't these in the core at one point? I think @thegreatercurve even was the one who added them.

**Comment by thegreatercurve** [comment]
> > HRs depend on React right now do they can’t really living without the markdown package depending on React too. Tricky one to decouple.
> 
> Weren't these in the core at one point? I think @thegreatercurve even was the one who added them.

@acywatson I think @trueadm did some work to add them to the markdown logic after my initial work to add them.

**Comment by trueadm** [comment]
They used to be in core, but it made no sense to have them in core given they were rarely used and never used in plain text. In fact given their special selection mechanics, it made much more sense to have them as decorators.
