### ISSUE TITLE
Bug: Can't set editor state without cursor focus

### ISSUE THREAD

**Issue by 6peterlu** [facebook/lexical#3252]
Lexical version: 0.3.5

## Steps To Reproduce

1. Call editor.setEditorState()
2. Observe cursor focus on that editor

Link to code example:

## The current behavior
editor.setEditorState always sets the cursor focus on that editor.
## The expected behavior
Some sort of configuration that allows setting editor state without also setting cursor focus.

**Comment by 6peterlu** [comment]
Was able to work around it by calling `editor.focus()` in `OnChangePlugin` but would be ideal to have a config in setEditorState

**Comment by trueadm** [comment]
This is intentional, applying an editor state will also re-apply its selection. Your workaround seems fine. Maybe we can have another tag that stops all focusing/selection kind of like the `skip-scroll-into-view` tag which you can already pass to `setEditorState` as the 2nd argument.

**Comment by fantactuka** [comment]
If selection itself is not critical for you, can clone state with null selection that should prevent auto focusing

```
editor.setEditorState(editorState.clone(null))
```
