### ISSUE TITLE
Feature: Allow a custom DOM node for TextNode with an underline format

### ISSUE THREAD

**Issue by jaffemd** [facebook/lexical#3263]
Currently, it seems like the all underline nodes are rendered in a `span` with the theme styles applied. Is there a way to opt in to use a `<u>` DOM node instead of a span?

**Comment by acywatson** [comment]
> Currently, it seems like the all underline nodes are rendered in a `span` with the theme styles applied. Is there a way to opt in to use a `<u>` DOM node instead of a span?

Why do you want to do this?

**Comment by jaffemd** [comment]
As I understand it, the <u> element is a native way for browsers to underline text without any css. I imagine this would make importing and exporting text elements between different text editors more compatible.

**Comment by acywatson** [comment]
> As I understand it, the element is a native way for browsers to underline text without any css. I imagine this would make importing and exporting text elements between different text editors more compatible.

That used to be the case, but this element is not actually supposed to be used for this purpose now (AFAIK):

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u

**Comment by jaffemd** [comment]
That's good to know, thank you!
