### ISSUE TITLE
Bug: Pressing Up/Down with a decorator node selection skips immediate siblings

### ISSUE THREAD

**Issue by kevinansfield** [facebook/lexical#3270]
When a decorator node is selected, pressing <kbd>Arrow Up</kbd>/<kbd>Arrow Down</kbd> moves the cursor off of the decorator node but skips the immediate sibling placing the cursor further away than expected.

Lexical version: 0.5.0

## Steps To Reproduce

1. Open the playground and add a HR node then a couple of paragraphs
2. Select the HR node by using Left/Right arrow keys
3. Press Down arrow key

## The current behavior

https://user-images.githubusercontent.com/415/198145317-5dc1d9d4-6530-410a-9c07-5f6e2b47d755.mp4

## The expected behavior

Cursor is placed on the immediate sibling, same as when pressing <kbd>Arrow Left</kbd>/<kbd>Arrow Right</kbd>

**Comment by trueadm** [comment]
This is intentional, unfortunately handling up/down is tricky and so we leave it to the browser for default behavior. It's tricky as knowing what is visually above means having to calculate the rect of the current selection.

**Comment by thegreatercurve** [comment]
Closing this for the moment as there doesn't seem like an action we can take, but feel free to open otherwise @trueadm.

**Comment by kevinansfield** [comment]
Our use-case was pretty basic, we wanted a consistent behaviour of `<kbd>ArrowUp</kbd>` moving caret to end of previous node and  `<kbd>ArrowDown</kbd>` moving caret to beginning of next node. It was possible to handle this simply via overriding the corresponding key commands - implementation in https://github.com/TryGhost/Koenig/commit/a2a23debc760f6b53d2264895d851d8d28450f7d if anyone else finds this 🙂
