### ISSUE TITLE
Bug: Copy paste doesn't work properly with element nodes

### ISSUE THREAD

**Issue by bigtimecriminal** [facebook/lexical#3316]
Element nodes do not properly support copy-paste

Lexical version: 0.6

## Steps To Reproduce

1. Create an h1 node
2. Copy and paste this text into the middle of it:
- This is the first item.
- And this is the second item.
- And this is the third item.

## The current behavior

Only the first line is h1

https://user-images.githubusercontent.com/6975606/199795946-1e45d4d0-12cc-4a92-bc23-a1f1674c5899.mov

## The expected behavior

All lines are h1

**Comment by acywatson** [comment]
> All lines are h1

I don't know that this is what we want. Is there any other editor where it works this way? Quip and GDocs do it more like us, though Google Docs is pretty borked, generally.
