### ISSUE TITLE
Feature: allow clicking quote on toolbar to insert and `remove` quote

### ISSUE THREAD

**Issue by harish-sethuraman** [facebook/lexical#3318]
Currently there is only inserting quote option. What if the user wants to remove quote just like other formatting? 
Can we somehow get the `selection.hasFormat` for quote to enable and disable quote? 

Or is there any other alternate solution that is already available?

**Comment by acywatson** [comment]
Quote formatting is applied by wrapping the nodes in A QuoteNode. Removing the formatting is a matter for unwrapping them (removing them from the QuoteNode and deleting the QuoteNode).

```
// Add quote format
const quoteNode = $createQuoteNode();
quoteNode.append($createTextNode("this is quoted");

...
// Remove quote format
const children = quoteNode.getChildren();
someOtherNode.append(children);
quoteNode.remove();
```
