### ISSUE TITLE
Bug: ReferenceError: document is not defined with next.js

### ISSUE THREAD

**Issue by shamod** [facebook/lexical#3319]
ReferenceError: document is not defined
    at /Users/hamo/CODE/lexical-test/node_modules/@lexical/react/LexicalComposer.dev.js:95:31
    at beginUpdate (/Users/shamod/CODE/lexical-test/node_modules/lexical/Lexical.dev.js:6141:5)
    at updateEditor (/Users/shamod/CODE/lexical-test/node_modules/lexical/Lexical.dev.js:6232:5)
    at LexicalEditor.update (/Users/shamod/CODE/lexical-test/node_modules/lexical/Lexical.dev.js:9259:5)
    at initializeEditor (/Users/shamod/CODE/lexical-test/node_modules/@lexical/react/LexicalComposer.dev.js:89:12)
    at /Users/shamod/CODE/lexical-test/node_modules/@lexical/react/LexicalComposer.dev.js:66:7
    at Object.useMemo (/Users/shamod/CODE/lexical-test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5124:19)
    at Object.useMemo (/Users/shamod/CODE/lexical-test/node_modules/react/cjs/react.development.js:1650:21)
    at LexicalComposer (/Users/shamod/CODE/lexical-test/node_modules/@lexical/react/LexicalComposer.dev.js:46:33)
    at renderWithHooks (/Users/shamod/CODE/lexical-test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)

Lexical version:

## Steps To Reproduce

1. create a next.js project
2. install lexical
3. yarn dev

Link to code example:

```
import {LexicalComposer} from '@lexical/react/LexicalComposer';
import {PlainTextPlugin} from '@lexical/react/LexicalPlainTextPlugin';
import {ContentEditable} from '@lexical/react/LexicalContentEditable';
import {HistoryPlugin} from '@lexical/react/LexicalHistoryPlugin';
import {OnChangePlugin} from '@lexical/react/LexicalOnChangePlugin';
import LexicalErrorBoundary from '@lexical/react/LexicalErrorBoundary';
import {useLexicalComposerContext} from '@lexical/react/LexicalComposerContext';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {$getRoot, $getSelection} from 'lexical';
import {useEffect} from 'react';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Editor />
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

const theme = {
  // Theme styling goes here
  // ...
}

function onError(error: any) {
  console.error(error);
}

function onChange(editorState: any) {
  editorState.read(() => {
    // Read the contents of the EditorState here.
    const root = $getRoot();
    const selection = $getSelection();

    console.log(root, selection);
  });
}

function MyCustomAutoFocusPlugin() {
  const [editor] = useLexicalComposerContext();

  useEffect(() => {
    // Focus the editor when the effect fires!
    editor.focus();
  }, [editor]);

  return null;
}

const Editor = () => {
  const initialConfig = {
    namespace: 'MyEditor',
    theme,
    onError,
  }

  return (
    <LexicalComposer initialConfig={initialConfig}>
      <PlainTextPlugin
        contentEditable={<ContentEditable />}
        placeholder={<div>Enter some text...</div>}
        ErrorBoundary={LexicalErrorBoundary}
      />
      <OnChangePlugin onChange={onChange} />
      <HistoryPlugin />
      <MyCustomAutoFocusPlugin />
    </LexicalComposer>
  )
}

```

## The current behavior

The above error occurs on next.js console.

## The expected behavior

This error should not occur

**Comment by Yidaotus** [comment]
You can prevent your Editor component from being rendered on the server with nextjs's dynamic imports:

```javascript
const Editor = dynamic(() => import("../components/Editor/Editor"), {
	ssr: false,
});
```

I don't think preventing this is the responsibility of the package itself?

**Comment by shamod** [comment]
@Yidaotus 
thank you so much, 
this totally makes sense.
