### ISSUE TITLE
Lexical and Formik

### ISSUE THREAD

**Issue by iPreacher** [facebook/lexical#3327]
Hello! Please tell me how can I use Lexical with Formik?

**Comment by acywatson** [comment]
You have to provide some minimal reproducible example of a problem before we can attempt to help you, especially with libraries like Formik. There happens to be a discussion going on about Formik in our Discord channel, so I'd advice plugging in there.

**Comment by ron-ts** [comment]
Can we can to the discord channel / point us out to where I can find it?
