### ISSUE TITLE
Simplify placeholder creation for custom layouts

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#3349]
From internal feedback the placeholder creation is complicated. It is particularly hard when custom nodes (beyond a simple TextNode) are involved. For example, our Workplace Post Composer structure that contains a Header + Body as a placeholder. We should research a better and generic way to simplify this problem.

> Text placeholder needs lots of extra moves to setup correctly. It gonna need to be simplified?? Maybe building it atop of paragraph node and absolute positioning?

**Comment by thegreatercurve** [comment]
#3379
