### ISSUE TITLE
Feature: parent editor should trigger `onChange` event while nested editor content changed 

### ISSUE THREAD

**Issue by LvChengbin** [facebook/lexical#3351]
I listen to the `onChange` event of parent editor and save content automatically, but while content in nested editor changed, the event isn't triggered.

Is there any to trigger parent editor's `onChange` event? 
Otherwise is it should be implemented in the nested editor composer?

**Comment by trueadm** [comment]
We've thought about this a lot internally and we feel that the current usage of `registerUpdateListener` should be only for a specific editor. The `OnChangePlugin` is just a wrapper around this behavior. Would you be happy for the `OnChangePlugin` to also propagate changes to parent editors that also use the `OnChangePlugin` too? That could provide a way for bubbling of `onChange`.

**Comment by thegreatercurve** [comment]
I think this could get confusing very fast, especially if the nested composer can also accept it's own `OnChangePlugin` child component.  The simplest solutions to me would be to allow both the parent and nested composer accept their own `OnChangePlugin` and then have them call the same callback with the parent editor state.

**Comment by LvChengbin** [comment]
I think it should be implemented internally.

1. If someone implements a decorator node with nested editor, others who use this implementation shouldn't need to know nested editors are used and they only need to face to the single editor.
2. `OnChangePlugin` provide `editorState` as argument for callback function, using multiple `OnChangePlugin` for nested editors prevent users to use unified callback function.
3. Methods for example `editorState.toJSON` get nested editorState automatically, but nested editor changes cannot notice parent editors, it sounds weird.

The code bellow is the callback function I'm using to listen to parent editor change:

```ts
function handleChange( editorState: EditorState ): void {
    const json = editorState.toJSON();
    const text = editorState.read( () => $getRoot().getTextContent() );
    onChange?.( { json, text } );
}
```

and callback code for nested editor:

```ts
const [ parentEditor ] = useLexicalComposerContext();

function handleChange(): void => {
    if( parentEditor ) {
        const editorState = parentEditor.getEditorState();
        parentEditor.setEditorState( editorState );
    }
}
```

Do you think I implemented this in the correct and elegant way?

**Comment by LvChengbin** [comment]
Is there anyone who can give me some suggestions? The way I posted before destroys sharing history between the parent editor and nested editor.

**Comment by CanRau** [comment]
Hmm also a little confused by this and the best way forward 🤔 

To me this stuff makes a lot of sense https://github.com/facebook/lexical/issues/3351#issuecomment-1333869853

**Comment by CanRau** [comment]
Hey @LvChengbin did you find a better way?

I'm currently passing a `onUpdateState` method down via `Context` which I call from the child's `OnChangePlugin`.
At the moment `onUpdateState` receives the `nodeKey` and then does
```ts
currentEditor.update(() => {
  $getNodeByKey(nodeKey)?.markDirty();
});
```
This seems to work fine so far and shared history also seems to work properly

Though I guess it should work without `Context` and just using `const [ parentEditor ] = useLexicalComposerContext();` and calling `markDirty` from within the child

**Comment by LvChengbin** [comment]
@CanRau Yes, I created a `EditorContext` and it can store the `onChange` callback function, so that nested editors can use the same `onChange` callback. 
And then, I made my own `SharedHistoryContext` for storing a `historyState` that be shared between root editor and all nested editors.
After that, I created a `SharedHistoryPlugin` and pass the shared `historyState` to `@lexical/react/LexicalHistoryPlugin` by adding `externalHistoryState` prop.
I'm using lexical@0.12.2, the methods above resolves most of problems because of using nested editors. But I don't know if my method is bad or not, I'll paste some of my codes here and I hope it can provide you some idea.

### SharedHistoryProvider.tsx
```tsx
import React, { createContext, useContext, useMemo } from 'react';
import { createEmptyHistoryState, HistoryState } from '@lexical/react/LexicalHistoryPlugin';

export interface SharedHistoryContextShape {
    historyState?: HistoryState;
}

const SharedHistoryContext = createContext<SharedHistoryContextShape>( {} );
export const useSharedHistoryContext = () => useContext( SharedHistoryContext );

export interface SharedHistoryProviderProps {
    children: React.ReactNode;
}

export function SharedHistoryProvider( props: SharedHistoryProviderProps ): JSX.Element {
    const { children } = props;

    const value = useMemo( () => {
        return {
            historyState : createEmptyHistoryState()
        };
    }, [] );

    return (
        <SharedHistoryContext.Provider value={value}>
            {children}
        </SharedHistoryContext.Provider>
    );
}
```

### SharedHistoryPlugin

```tsx
import React from 'react';
import { HistoryState, HistoryPlugin } from '@lexical/react/LexicalHistoryPlugin';
import { useSharedHistoryContext } from '@fims/www-common/editor/providers/SharedHistoryProvider';

export interface SharedHistoryPluginProps {
    externalHistoryState: HistoryState;
}

export default function SharedHistoryPlugin( props: SharedHistoryPluginProps ): JSX.Element {

    const { historyState } = useSharedHistoryContext();

    return (
        <HistoryPlugin
            externalHistoryState={historyState}
            {...props}
        />
    );
}
```

### Code in NestedEditor
```tsx
    const [ parentEditor ] = useLexicalComposerContext();
    const { onChange : onChangeContext } = useEditorContext();

    const handleChange = ( editorState: EditorState ): void => {
        if( onChange?.( editorState ) !== false ) {
            const editorState = parentEditor.getEditorState();
            onChangeContext?.( editorState );
        }
    };
```

**Comment by CanRau** [comment]
Finally getting to finish our new editor and I think I got it working pretty nice thanks to your help 🙏🏼 ❤️
