### ISSUE TITLE
Feature: destroyDOM callback

### ISSUE THREAD

**Issue by byTimo** [facebook/lexical#3352]
It'll be great to have a controllable callback for destroying DOM that's been generated by the node. It'd be useful for removing event listeners and removing the DOM nodes from some kind of maps and caches. I'm working on some tooltip that should be shown when a DOM node is hovered and for now don't have an idea how to unsubscribe an event handler correctly.

**Comment by acywatson** [comment]
Can you use a mutation listener for this?

https://lexical.dev/docs/concepts/listeners#registermutationlistener
```
const removeMutationListener = editor.registerMutationListener(
  MyCustomNode,
  (mutatedNodes) => {
    // mutatedNodes is a Map where each key is the NodeKey, and the value is the state of mutation.
    for (let [nodeKey, mutation] of mutatedNodes) {
      if (mutation === "destroyed") {
        const dom = editor.getElementByKey(nodeKey);
        // do whatever
      }
    }
  },
);
```

**Comment by byTimo** [comment]
Yeah, I've already used this way as a workaround, but I had to implement and maintain the plugin instead of just using the node. Moreover, mutation listeners aren't executed during the editor unmounting, so I had to collect all DOM elements in some special array, that is used for removing listeners to avoid memory leaks. I have to keep the array relevant throughout the entire life cycle of the editor. And how knows, maybe I missed some more pitfalls

**Comment by acywatson** [comment]
> Yeah, I've already used this way as a workaround, but I had to implement and maintain the plugin instead of just using the node. Moreover, mutation listeners aren't executed during the editor unmounting, so I had to collect all DOM elements in some special array, that is used for removing listeners to avoid memory leaks. I have to keep the array relevant throughout the entire life cycle of the editor. And how knows, maybe I missed some more pitfalls

I don't think you need to worry about explicitly cleaning up those listeners. The runtime GC should get those for your once the underlying DOM Nodes are dereferenced.

**Comment by trueadm** [comment]
As @acywatson already explained, the reason Lexical doesn't need this method is because cleanup is handled for you in almost all cases by the GC working as expected with unreferenced DOM nodes. Closing as I don't see the need for more code in core around this, but feel free to re-open if you feel this discussion needs more nuance.
