### ISSUE TITLE
question: how do I resolve an error caused by using the ImagesPlugin with the RichTextPlugin?

### ISSUE THREAD

**Issue by johanpaolorodriguez** [facebook/lexical#3356]
I got an error in React that I can't resolve when I try to integrate the ImagesPlugin alongside the RichTextPlugin.
Here is the message: 

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `RichTextPlugin`.
RichTextPlugin@http://localhost:3000/static/js/bundle.js:74334:7
LexicalComposer@http://localhost:3000/static/js/bundle.js:73675:7

I've reproduced the error in the ImagePlugin of @akmarzhan1 by simply changing the PlainTextPlugin to that of the RichTextPlugin
Here's a link to my forked sandbox https://codesandbox.io/s/goofy-sammet-40x116?file=/src/Editor.js

![image](https://user-images.githubusercontent.com/68212981/201477250-d945647f-b572-44b3-a980-ca3f8d3a3fde.png)

**Comment by acywatson** [comment]
Take a look at #3328. You need an error boundary I think

**Comment by johanpaolorodriguez** [comment]
Thank you, that did it :)

**Comment by lychee22** [comment]
Thank you !!!! I finally figure it out !!!!Its very usefull
