### ISSUE TITLE
When the code block in html is echoed by generateNodesFromDOM, elements and styles are missing

### ISSUE THREAD

**Issue by Lerbron** [facebook/lexical#3383]
this is my default html:
`<code class="PlaygroundEditorTheme__code" spellcheck="false" data-highlight-language="javascript"><span class="PlaygroundEditorTheme__tokenAttr">let</span><span> a</span><span class="PlaygroundEditorTheme__tokenOperator">=</span><span> </span><span class="PlaygroundEditorTheme__tokenProperty">1</span><span class="PlaygroundEditorTheme__tokenPunctuation">;</span></code>`

Use this html to generate nodes through the $generateNodesFromDOM function and insert the editor:
        
        const parser = new DOMParser();

        const dom = parser.parseFromString(defaultHtml, 'text/html');

        const nodes = $generateNodesFromDOM(editor, dom);

        const root = $getRoot();

        const paragraphNode = $createParagraphNode();

        nodes.forEach((n)=> paragraphNode.append(n));

        root.append(paragraphNode);

After the node is generated, it becomes like this
`<code data-lexical-text='true'><span class="PlaygroundEditorTheme__textCode">let a=1;</span></code>`

**Comment by acywatson** [comment]
You have a few options here:

1) if what you want is just the exact HTML that Lexical renders, just use getRootElement and access the innerHtml property to get that:
```
editor.getRootElement().innerHtml
```

2) If you want to control how the HTML is exported from these nodes, you have to learn about Serialization:

https://lexical.dev/docs/concepts/serialization

You can use the new (in v0.6.2) $applyReplacementNode API to overrride CodeNode and CodeHighlight node with your own nodes that implement exportDOM however you want.
