### ISSUE TITLE
Bug: Body is not scrollable using mouse wheel when using the draggable block plugin on Chrome

### ISSUE THREAD

**Issue by zignis** [facebook/lexical#3389]
Lexical version: Latest

## Steps To Reproduce

1. Visit playground and fill in enough nodes to make the editor overflow the body.
2. Try dragging the topmost node to the bottom.

## The current behavior
The body can't be scrolled when the node is being dragged.

## The expected behavior
The body should be able to scroll when the node is being dragged, which is very crucial when moving nodes that are overflowing the viewport.

**Comment by Sabin-Subedi** [comment]
Yes this bug is still there in playground and i think this should be resolved. @trueadm i would like to work on this bug

**Comment by trueadm** [comment]
Go for it @Sabin-Subedi  :)

**Comment by LuciNyan** [comment]
I tried to reproduce this issue but failed. How did you do it? Could you record a video?


https://user-images.githubusercontent.com/22126563/204425838-3bab1f2d-95d3-4c34-ba08-a992064b5025.mov

**Comment by zignis** [comment]
> Hi @zignis! I tried to reproduce this issue but failed. How did you do it? Could you record a video?
> 
>  2022-11-29.10.34.56.mov

Sorry for not being specific enough, the scrolling works when you drag but the mouse wheel events do not work when a block is being dragged. Try dragging a block and using the mouse wheel at the same time.

**Comment by LuciNyan** [comment]
> Sorry for not being specific enough, the scrolling works when you drag but the mouse wheel events do not work when a block is being dragged. Try dragging a block and using the mouse wheel at the same time.

Thanks for your response! <3

**Comment by thegreatercurve** [comment]
Closing this as I don't necessarily think we should be adding in hacky fixes to accommodate the mousewheel scroll functionality, especially if it's more of a browser issue on MacOS. 

There are [open bugs for Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=642214), which can be used instead for tracking the issue.
