### ISSUE TITLE
Bug: Lexical Rich Text Sandbox

### ISSUE THREAD

**Issue by RiedelNicolas** [facebook/lexical#3407]
On the Rich Text Sandbox when I try to select an element from the dropdown menu : 
![image](https://user-images.githubusercontent.com/44354888/203580014-be0917f5-1ee1-4cfd-8daa-96a40f46a27e.png)
There is a type error 
![image](https://user-images.githubusercontent.com/44354888/203584253-94e76f10-1e42-4f83-b4fe-b17600f9480c.png)

Lexical version:

0.6.2

## Steps To Reproduce

1. Go to : https://codesandbox.io/s/lexical-rich-text-example-5tncvy
2. select an element from de dropwdown select

Link to code example:
https://codesandbox.io/s/lexical-rich-text-example-5tncvy

## The current behavior
You cant select an option
## The expected behavior
You should be able to select an option

**Comment by trueadm** [comment]
Should be fixed now. Sorry, it was updated to a newer version where the API for that changed.

**Comment by trueadm** [comment]
Ah, my save didn't get applied. Try again once more – sorry.
