### ISSUE TITLE
Bug: Selection issues around block level decorator nodes

### ISSUE THREAD

**Issue by Piliuta** [facebook/lexical#3417]
Typing or pasting text does not work if the editor has only one (block) decorator node in the content.

Lexical version: 0.6.3

## Steps To Reproduce

1. Remove all content
2. Add a block node decorator (not a horizontal rule, that has been fixed)
3. Remove all spaces before and after the node
4. Set focus on the node and change cursor position to left or right (press Arrow Left/Right)
5. Attempt to type or paste any text - nothing happens.
 
**Notes:**
- Pressing Enter does work
- This is not an issue if content has any other (even empty) nodes

https://user-images.githubusercontent.com/1575198/203802959-25acb8a6-05a7-490c-9883-9d782c1413cb.mov

**Comment by Piliuta** [comment]
@trueadm this is still a problem with other block decorator nodes. The horizontal rule was an example, but this is a problem with all such nodes. I do not think this should be fixed on the node level. It needs a general fix.

**Comment by trueadm** [comment]
@Piliuta This doesn't seem like a Lexical bug though. The problem is how selection is handled by browser rendering engines in respect to content editable. `<hr>` as a block level element can have selection around it, but oddly, `<div>` can't it seems. I'm not sure there is a general fix here. Maybe you can help me do some more research around what types of element work and do not (using a standard content editable element).

**Comment by Piliuta** [comment]
> @Piliuta This doesn't seem like a Lexical bug though. The problem is how selection is handled by browser rendering engines in respect to content editable. `<hr>` as a block level element can have selection around it, but oddly, `<div>` can't it seems. I'm not sure there is a general fix here. Maybe you can help me do some more research around what types of element work and do not (using a standard content editable element).

Not promising anything, but I can take a look. We should keep this issue open as it does not resolve the problem completely.

**Comment by trueadm** [comment]
I wonder if someone has filed a browser bug around this before. I feel this should be something browser vendors should be fixing.

**Comment by trueadm** [comment]
For what it's worth, making the container `<div>` for your decorator `inline` or `inline-block` seems to fix the selection issues too.

**Comment by Piliuta** [comment]
> For what it's worth, making the container `<div>` for your decorator `inline` or `inline-block` via CSS `display` seems to fix the selection issues too.

Yeah, it does work for me. Do you think this can cause other side effects or it can be set as a style by default for decorator nodes?

**Comment by Piliuta** [comment]
> For what it's worth, making the container `<div>` for your decorator `inline` or `inline-block` via CSS `display` seems to fix the selection issues too.

Applying inline classes to all nodes causes different issues, but doing it for the case when there is only node seems to be working

```css
.ContentEditable__root > [contenteditable="false"]:only-child {
  display: inline;
}
```

I'll probably go with this as a low lift solution.

**Comment by Piliuta** [comment]
Well, this does not work when there are more than one such node and no other nodes in the content 😕

**Comment by trueadm** [comment]
I figured it out. Having an extra `<div contenteditable="false">` in the main editor allows for selection oddly. This is what ProseMirror uses for its emulated cursors.

**Comment by Piliuta** [comment]
> 

Not sure that understand what you mean. Decorator nodes are `<div contenteditable="false">` in the main editor but it does not work 🤔

**Comment by Piliuta** [comment]
> I figured it out. Having an extra `<div contenteditable="false">` in the main editor allows for selection oddly. This is what ProseMirror uses for its emulated cursors.

Not sure that understand what you mean. Decorator nodes are `<div contenteditable="false">` in the main editor but it does not work 🤔

**Comment by trueadm** [comment]
@Piliuta The element also needs to be empty! I have some work on this in https://github.com/facebook/lexical/pull/3434
