### ISSUE TITLE
Feature: Implement iterator into LexicalNode to allow simple tree traversal

### ISSUE THREAD

**Issue by nextend** [facebook/lexical#3419]
I needed to tell whether the current selection is inside the current node or not. I wrote a generator function to iterate over nodes until I found a node with node.isSelected() === true. I think an iterator would help others as well.

I think you just need to extends these two classes with generator functions:

```
class LexicalNode {
	* makeIterator(){
		yield this;
	}
}

class ElementNode(){
	* makeIterator(){
		yield* super.makeIterator();
	
		for(childNode of node.getChildren()){
			yield* childNode.makeIterator();
		}
	}
}
```

This code can be optimized even more:
```
class LexicalNode {
	* makeIterator(){
		yield this;
	}
}

class ElementNode(){
	* makeIterator(){
		yield* super.makeIterator();
	
		const self = this.getLatest();
		const children = self.__children;

		for (let i = 0; i < children.length; i++) {
			const childNode = $getNodeByKey(children[i]);

			if (childNode !== null) {
				yield* childNode.makeIterator();
			}
		}
	}
}
```

Usage:
```
    for (const currentNode of node.makeIterator()) {
        if (currentNode.isSelected()) {
            console.log('A node is selected on this branch');
            break;
        }
    }
```

**Comment by thegreatercurve** [comment]
We have an issue open to refactor `getChildren` to use a linked list (#1860). This would probably be more useful for your usecase, as it will necessarily introduce some methods which are similar to the iterable protocol implemented by generators, so developers could call `next` or `previous` on the list of child nodes.
