### ISSUE TITLE
Bug: FloatingToolbar updatePopup loop and flickering within cursor range selection

### ISSUE THREAD

**Issue by maxhelsel** [facebook/lexical#3427]
Lexical version:
0.6.X, playground editor

## Steps To Reproduce

1. Rich text editor with FloatingTextFormatToolbarPlugin enabled
2. Type a paragraph, hit enter/return twice, type another paragraph
3. Use cursor to highlight bottom paragraph, drag to empty line and rest
4. Seems to me that the cursor gets stuck between the FloatingToolbar and the editor body, causing update loops to the Toolbar updatePosition function

* seems to also happen when highlighting and dragging to a line above that has text, if the toolbar position clips with the cursor

Link to code example:
https://playground.lexical.dev/
https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/FloatingTextFormatToolbarPlugin/index.tsx

![Kapture 2022-11-25 at 11 03 43](https://user-images.githubusercontent.com/46327674/204022162-3618f786-8fdc-4b11-b663-6395b66cb0c2.gif)

## The current behavior
flickering when holding mouse down and resting between paragraphs

## The expected behavior
the toolbar should update position if there is text selected within anchor and the focus has 0 text length,
OR the toolbar should have "pointer-events: none" if user is currently holding down mouse button so updatePosition is not triggered

**Comment by trueadm** [comment]
Thanks for the detailed report. If you get a chance and would like to contribute a fix, then a PR would be really appreciated. :)

**Comment by thegreatercurve** [comment]
This was fixed by the exceptional work of @LuciNyan in #4013!
