### ISSUE TITLE
Bug:  correcting a word using Grammarly will also insert word where the cursor is if in a different paragraph.

### ISSUE THREAD

**Issue by scvet-ct** [facebook/lexical#3428]
Lexical version: 0.5.0 

## Steps To Reproduce

1. enable grammarly extension (turn off autocorrect)
2. write a paragraph
3. start a new paragraph with an incorrectly spelled word.
4. click back into the previous paragraph
5. hover over the incorrectly spelled word (don't click on it) and then click on Grammarly's suggested change to select it
6. the word will change but also be placed in the previous paragraph where the cursor is.

Link to code example:
This happens in the current version of Lexical Playground.

## The current behavior
<img width="426" alt="image" src="https://user-images.githubusercontent.com/114913876/203997116-72a87c73-fc95-4b5d-ab28-28ed31c53af8.png">
<img width="418" alt="image" src="https://user-images.githubusercontent.com/114913876/203997187-0afd7703-f390-4473-8ace-22c84e6e92b3.png">

## The expected behavior
<img width="426" alt="image" src="https://user-images.githubusercontent.com/114913876/203997116-72a87c73-fc95-4b5d-ab28-28ed31c53af8.png">
<img width="349" alt="image" src="https://user-images.githubusercontent.com/114913876/203997262-08cfcb51-f9f0-47ec-8607-05d125067c0b.png">

**Comment by trueadm** [comment]
I'm a muppet and somehow undid the fix before landing that PR. I fixed in https://github.com/facebook/lexical/pull/3438.

**Comment by scvet-ct** [comment]
Amazing, thank you for fixing it so quickly. Will update our version of lexical when it's in main 👍
