### ISSUE TITLE
Bug: Image resizing on Read-Only mode

### ISSUE THREAD

**Issue by bilobom** [facebook/lexical#3439]
Images inserted into the playground can be resized, and added a caption to.

Lexical version: latest on the playground

## Steps To Reproduce

1. go to lexical playground
2. insert a sample image
3. click the image to show resizing layer
4. toggle edit mode to read-only mode
5. resize the image or add caption

## video

[screen-capture (1).webm](https://user-images.githubusercontent.com/19841175/204271374-2908d6cc-55f0-4d66-a830-4e05baf1e16f.webm)

## The current behavior
resize the image or add caption on read-only mode

## The expected behavior
not resize the image or add caption on read-only mode

**Comment by Faizan711** [comment]
does this issue still needs to be resolved, if so i would like to be assigned for it.

**Comment by thegreatercurve** [comment]
> does this issue still needs to be resolved, if so i would like to be assigned for it.

Happy for you to take a look. It should be a case of checking if `editor.isEditable()` is true in the ImageResizer component.

**Comment by thegreatercurve** [comment]
@Faizan711 Apologies, but I ended up fixing this as part of another PR (#3445). It turned out to just be a couple of lines to fix.

**Comment by Faizan711** [comment]
Ok no worries, I'll try to fix the next one.
