### ISSUE TITLE
Bug: LexicalAutoFocusPlugin looks wrong

### ISSUE THREAD

**Issue by birtles** [facebook/lexical#3461]
Lexical version: 0.6.4

See the following code, introduced in https://github.com/facebook/lexical/commit/2f78eeb41daa8ee4a60c47107ff67953bcfeb8df:

https://github.com/facebook/lexical/blob/a2f3b2fe157bcd20d69c1e85b9203d6c52d244ab/packages/lexical-react/src/LexicalAutoFocusPlugin.ts#L28-L35

This appears to call `rootElement.focus()` any time `rootElement` is not `null` which both fails to guard against `rootElement` being `null` in the previous line, and also makes the previous line redundant:

Presumably, it should be an `&&` condition such as we have in `updateDOMSelection`:

https://github.com/facebook/lexical/blob/a2f3b2fe157bcd20d69c1e85b9203d6c52d244ab/packages/lexical/src/LexicalSelection.ts#L2793-L2801

**Comment by thegreatercurve** [comment]
Yeah, I think you're right. `!rootElement.contains(activeElement)` could result in a type error without the null check in front of it.

**Comment by birtles** [comment]
Thanks!

**Comment by steven-prybylynskyi** [comment]
The **Simple Setup** example on the homepage https://lexical.dev/ has a `MyCustomAutoFocusPlugin` example which does not work, although all it does is just calls [editor.focus](https://lexical.dev/docs/api/classes/lexical.LexicalEditor#focus)
