### ISSUE TITLE
Feature: Is there a custom way to serialize/deserialize EditorState

### ISSUE THREAD

**Issue by turnerguo** [facebook/lexical#3463]
While user use Lexical in a collaboration document it might be a big doc-data to save to the database, which the data maybe get from `editor.getEditorState().toJSON()`, but it returns only a tree like data structure that may not user want, in this case we may need to customize the data structure like a Nodes Array or something else to support better data saving strategy.

After I read the document but not found a right way to do that, seems like the `https://lexical.dev/docs/api/classes/lexical.EditorState#read` API remove `state` param from the `callbackFn` which can not custom the EditorState, could you please provide a better way to support custom editor structure?

**Comment by trueadm** [comment]
You can use `editor.read()` like you mention. `state` isn't passed, but you can use `$getRoot()` and traverse the tree from the root and create your own output as you want.

**Comment by acywatson** [comment]
Let us know if Dominic's response doesn't solve your problem

**Comment by turnerguo** [comment]
Thanks @trueadm @acywatson, that means I have to use `parseEditorState` to create a tree according to `SerializedEditorState` structure then use `editor.setEditorState()`, is that correct?
