### ISSUE TITLE
Bug: Getting error after upgrading to >= 0.6.0 version of lexical from 0.5.0

### ISSUE THREAD

**Issue by WoodenPC** [facebook/lexical#3465]
Lexical version:
0.6.0 and above

## Steps To Reproduce

upgrade lexical version from 0.5.0 to 0.6.0 and above
0.5.0 is working !
![image](https://user-images.githubusercontent.com/25397745/204826270-ba448ee1-a548-4aef-826e-23ba708725a8.png)

**Comment by trueadm** [comment]
They are named exports now. See the playground for examples. For this case you can do:

```
import {RichTextPlugin} from '@lexical/react/RichTextPlugin';
```

**Comment by WoodenPC** [comment]
@trueadm Thank you for help. I already use named imports . My code based on examples from docs and playground. But it not working after update from 0.5.0 -> 0.6.4 :(
```
import { LexicalComposer } from '@lexical/react/LexicalComposer';
import { RichTextPlugin } from '@lexical/react/LexicalRichTextPlugin';
```

**Comment by trueadm** [comment]
Are all your versions for your references to other modules in your package.json files also 0.6.4?

**Comment by WoodenPC** [comment]
"lexical": "0.6.4",
"@lexical/react": "0.6.4",
"@lexical/clipboard": "0.6.4",
"@lexical/code": "0.6.4",
"@lexical/file": "0.6.4",
"@lexical/hashtag": "0.6.4",
"@lexical/link": "0.6.4",
"@lexical/list": "0.6.4",
"@lexical/mark": "0.6.4",
"@lexical/overflow": "0.6.4",
"@lexical/plain-text": "0.6.4",
"@lexical/rich-text": "0.6.4",
"@lexical/selection": "0.6.4",
"@lexical/table": "0.6.4",
"@lexical/utils": "0.6.4",

**Comment by trueadm** [comment]
Try clearing out your node_modules and doing npm install again?

**Comment by WoodenPC** [comment]
deleting node_modules and reinstalling packages not helped me at all :(  Same error in console

**Comment by WoodenPC** [comment]
Btw i use @swc/core and swc-loader for webpack . I updated them. And error dissapeared
