### ISSUE TITLE
Bug: TextEntity infinite loop with provided HashtagPlugin

### ISSUE THREAD

**Issue by pro-vi** [facebook/lexical#3468]
Lexical version: 0.6.4

## Steps To Reproduce

Type `#aaa #bbb` which is parsed into two `HashtagNode`s, copy, paste right after `#bbb` no space, `TextEntity` will start to loop infinitely. See recording.

https://github.com/facebook/lexical/blob/67b159ee9275e4a8f67c53b9aad97d0d97cddb8b/packages/lexical-react/src/LexicalHashtagPlugin.ts#L280-L284

In `LexicalText`, could have something to do with `HashtagNode` being an `instanceof TextNode`, leaving no break point when two hashtag nodes are adjacent, infinite parsing.

https://github.com/facebook/lexical/blob/67b159ee9275e4a8f67c53b9aad97d0d97cddb8b/packages/lexical-text/src/index.ts#L183-L187

Curiously, I wasn't able to reproduce this in the playground, while I don't see any specific logic handling this behavior, and that it uses the same Hashtag Regex.

Link to code example: https://codesandbox.io/s/lexical-plain-text-example-forked-4rspdy?file=/src/Editor.js

https://user-images.githubusercontent.com/9211198/204885829-5598d7b0-460f-4b31-8f5f-9bca9493f05f.mov

**Comment by alisnic** [comment]
This is a workaround for the issue in case anyone else needs it:

```typescript
  useEffect(() => {
    return editor.registerCommand(
      PASTE_COMMAND,
      event => {
        if (event instanceof ClipboardEvent && event.clipboardData?.types.includes('text/plain')) {
          const pastedText = event.clipboardData.getData('text');

          if (pastedText[0] !== '#') {
            return false;
          }

          editor.update(() => {
            const selection = $getSelection();
            if (selection) {
              const nodes = selection.getNodes();
              const targetNode = nodes.length === 1 ? nodes[0] : nodes[0]?.getPreviousSibling();
              const finalText = targetNode?.getType() === 'hashtag' ? ` ${pastedText}` : pastedText;
              selection.insertText(finalText);
            }
          });

          return true;
        }

        return false;
      },
      COMMAND_PRIORITY_HIGH
    );
  }, [editor]);

```
