### ISSUE TITLE
Feature: Unable to customize indentation value

### ISSUE THREAD

**Issue by yunseop-dev** [facebook/lexical#3473]
I would like to use a customized theme in my product, but it is inconvenient because the indentation value is fixed at 20px.

It is changing in the `setElementIndent` function of `packages/exical/src/LexicalReconciler.ts`.

It would be great if we could customize the indent by receiving the value like `initialConfig.theme.indent` of LexicalComposer component.

**Comment by thegreatercurve** [comment]
We can probably do this by setting a CSS variables and then using calc to update the indentation margin
