### ISSUE TITLE
Bug: Checklist converts back to Bullet List on $generateNodesFromDOM

### ISSUE THREAD

**Issue by joma-mc** [facebook/lexical#3479]
I have an html string and when I used the the $generateNodesFromDom, it turns the checkbox into listType = "bullet"

`<html><head></head><body><ul class="editor-list-ul"><li role="checkbox" tabindex="-1" aria-checked="false" value="1" class="editor-listitem editor-list-unchecked"><p class="editor-paragraph"><span>123</span></p></li></ul></body></html>`

<img width="456" alt="image" src="https://user-images.githubusercontent.com/119643689/205204940-64f2816a-521e-4f03-bcc8-250bdbba0974.png">

<img width="492" alt="image" src="https://user-images.githubusercontent.com/119643689/205204981-b371bd9a-140d-4376-b2d7-56aef73d2bb9.png">

Lexical version: 0.6.4

## Steps To Reproduce

1. Please see screenshots above

**Comment by acywatson** [comment]
Fixed by #3579
