### ISSUE TITLE
Feature: Provide a way to add a custom node  key in LexicalNode when doing `editor.update`

### ISSUE THREAD

**Issue by turnerguo** [facebook/lexical#3485]
Lexical version: latest

For some reason we need to custom the LexicalNode key, but got this error:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/633880/205435310-5aeeb93b-1630-4644-89e5-f7d0daa5ca2f.png">

 
## Steps To Reproduce
1. try create a lexical editor demo or modify lexical-playground. 
2. add custom node key logic with `editor.update`:
```js
editor.update(() => {
    const root = $getRoot();

    // this works correct
    // const p1 = $createParagraphNode();
    // p1.append($createTextNode(`This is the first TextNode.`));
    // root.append(p1);

    // but I can not put custom key here
    const p2 = $applyNodeReplacement(new ParagraphNode('my-paragraph-2'));
    p2.append(
      $applyNodeReplacement(
        new TextNode(
          `This is a TextNode with custom NodeKey.`,
          'my-text',
        ),
      ),
    );
    root.append(p2);
});
```

After debug into the error, seems to be the `__key` was not found in `_nodeMap`:
```js
getLatest(): this {
    const latest = $getNodeByKey<this>(this.__key);
    if (latest === null) {
      invariant(
        false,
        'Lexical node does not exist in active editor state. Avoid using the same node references between nested closures from editor.read/editor.update.',
      );
    }
    return latest;
  }
```

So, after another research I found that `editor._pendingEditorState` may help to do some customization before `editor.activeEditorState`, this is du to some lexical updating mechanism like `immer` data, after modify the code it is works:

```js
editor.update(() => {
    const root = $getRoot();

    // this works correct
    // const p1 = $createParagraphNode();
    // p1.append($createTextNode(`This is the first TextNode.`));
    // root.append(p1);

    const p2Key = 'my-paragraph-2';
    const p2Node = new ParagraphNode(p2Key);
    const p2 = $applyNodeReplacement(p2Node);
    editor._pendingEditorState?._nodeMap.set(p2Key, p2Node);

    const t2Key = 'my-text-2';
    const t2Node = new TextNode(
      `This is the second TextNode with custom NodeKey.`,
      t2Key,
    );
    const t2 = $applyNodeReplacement(t2Node);
    editor._pendingEditorState?._nodeMap.set(t2Key, t2Node);

    p2.append(t2);
    root.append(p2);
});
```

But `editor._pendingEditorState?._nodeMap` looks ugly, and seems to be like using a `private property`, does lexical provide some proper way to do such things like:

```js
// give a api on editor
const pendingEditorState = editor.getPendingEditorState();

// give a $ function that only run into the closure
// $getPendingEditorState();

// or give a arg like `draftEditorState`
editor.update(({draftEditorState}) => {
  // the `draftEditorState` may target on `editor._pendingEditorState` to let developer have more extensibility
});
```

**Comment by trueadm** [comment]
Keys are an internal mechanism managed by Lexical, and you shouldn't be trying to supply your own.

**Comment by turnerguo** [comment]
@trueadm thanks for your remind, but I really got confused with Lexical docs~ 😂 
it's really hard to find a right way to extends the EditorState with my own needs, I got more doubts here:
1.  is that `_`, `__` started properties mentioned in API Docs can be used as the public property? like [`_pendingEditorState`](https://lexical.dev/docs/api/classes/lexical.LexicalEditor#_pendingeditorstate), `_pendingEditorState._nodeMap`,  [`__text`](https://lexical.dev/docs/api/classes/lexical.TextNode#__text), if so, why can't use that directly?
2. when user want to serialize a big doc's data `EditorState` to database, they may need to press the tree data (`EditorState`) into some other data structure, e.g. Array. which the Array will save to the database, while refresh the UI the Array item id from database need to be mapped with Lexical `EditorState`'s `node` to keep the editor state, how can I do that correctly?

**Comment by trueadm** [comment]
You're right in that you're not meant to access those fields directly. However, we provide a nice public API for you to use on an existing editor state – `editorState.read(() => { const root = $getRoot(); // do stuff })`. It's here were you can convert the structure into your own one, and this is also what we do in some instances internally too.

**Comment by trueadm** [comment]
Closing as this isn't a feature we're looking to add.
