### ISSUE TITLE
Bug: Weird Backspace key behavior in nodes containing inputs

### ISSUE THREAD

**Issue by goale** [facebook/lexical#3488]
When I try to delete text in a node that contains an input element by hitting Backspace it ends up deleting text after the node. Playground does seem to have this issue too with Poll node.

Lexical version: 0.6.5

## Steps To Reproduce

1. Go to [Lexical Playground](https://playground.lexical.dev/)
2. Insert a Poll node and type in some poll options
3. Put the cursor on the text after the inserted node
4. Put the cursor back in one of the input options
5. Try to delete characters with Backspace

![Peek 2022-12-04 16-52](https://user-images.githubusercontent.com/4661017/205514383-07997790-ffce-43dd-acdc-a99c44cf14ff.gif)

## The current behavior
Characters are being deleted in text before or after the node
## The expected behavior
Characters are being deleted in the input element

**Comment by trueadm** [comment]
I’ll look into this. Seems like an obvious issue looking at the video

**Comment by hamodhalsatry** [comment]
MOHAMMED

**Comment by hamodhalsatry** [comment]
> MOHAMMED

**Comment by hamodhalsatry** [comment]
Halo
