### ISSUE TITLE
Bug: splitting a paragraph with inline decorator nodes only fires a destroy mutation in the mutation listener

### ISSUE THREAD

**Issue by Yidaotus** [facebook/lexical#3490]
I synchronize a list of nodes in my application with the registerMutationListener function. Splitting a paragraph which contains this node (inline decorator) only fires a destroy mutation and I lose track of this node.

Lexical version: 0.6.4

## Steps To Reproduce

1. Create an inline decorator node inside a paragraph (RichTextPlugin)
2. Register a mutation listener for that node with registerMutationListener
3. Split the paragraph node at any point before the inline node, so the inline node moves in to the new paragraph, by pressing return

Link to code example: https://codesandbox.io/s/lexical-plain-text-example-forked-9iw8ts?file=/src/Editor.js

## The current behavior
Only a destroy mutation is fired in our mutation listener and we lose track of our nodes.

## The expected behavior
Either only one 'update' mutation should be fired or an additional 'create' mutation in order to keep the state synchronous.

**Comment by trueadm** [comment]
Definitely seems like a bug with the mutation logic. @zurfyx mind taking a look when you get a chance please?
