### ISSUE TITLE
Support Google Translate

### ISSUE THREAD

**Issue by li-yechao** [facebook/lexical#3496]
Lexical editor need support google translate, it's because of Lexical's DOM mutation observers reverting the content back.

Lexical version: 0.6.0

## Steps To Reproduce

1. Translate web page contain lexical editor in Chrome.

Link to code example:

## The current behavior
Lexical editor content not translated.

**Comment by trueadm** [comment]
So looking more into this and it's a really complex one. Essentially, the DOM mutation observers are doing the right job – they're treating the Lexical EditorState as the source of truth – not the DOM. If we change this logic for read only mode, then this assumption is no longer true and subsequent updates to the EditorState will likely fail.

In your case, if you want to have Google Translate support, I'd suggest not using Lexical to render the content if this is possible to do. Instead, you can extract the HTML from the EditorState and render that directly as part of your view logic.

**Comment by Soxasora** [comment]
The content we show via Lexical is final (e.g. can't change), so we pinpointed the mutation type that Google Translate needed (`characterData`) and removed it from Lexical's DOM mutation observers. [The workaround is very simple](https://github.com/stackernews/stacker.news/pull/2705) and it only involves filtering out `characterData` from Lexical's `_observer`.
