### ISSUE TITLE
Bug: Checklist markdown shortcut not working

### ISSUE THREAD

**Issue by FrancescoBia** [facebook/lexical#3500]
Lexical version: 0.6.3

## Steps To Reproduce

1. start writing the markdown shortcut for the checklist: `- [ ]`
2. after the `- ` the editor will convert the item to a bullet point, ignoring the following characters, and preventing the checklist to be created via the markdown shortcut. 

## Video example:

https://user-images.githubusercontent.com/9106253/205894472-75c7eae8-94d2-48ba-8ac6-24cb4dfb1c2c.mp4

## The current behavior
`- [ ]` gets converted to a bullet point

## The expected behavior
`- ` creates a bullet point, then by adding the remaining characters (`[ ]`/`[x]`) the line gets converted to a checklist

**Comment by FrancescoBia** [comment]
Thanks. I can use that syntax or a custom one when writing directly, but this creates a couple of complications:
1. I need to communicate to the user the cases where my editor differs from the standard markdown syntax.
2. It creates issues when I import a markdown document into the editor. Currently, I created a custom transformer for the unordered list and added a regex lookahead (`/^(\s*)[-*+]\s(?!(\[(\s|x)?\]))/`), but this doesn't work while the user inputs the syntax directly in the editor.

Furthermore, the `- []` character combination seems to be technically included by the markdown transformer for the checklist item, but since the unordered list gets triggered at `- `, it doesn't work. Therefore I wanted to report it as a bug instead.

Maybe it's not too relevant for the purpose of this bug, but the desired behavior is quite common in markdown-supported editors (e.g. Notion, Obsidian, ...). Thanks!

**Comment by thegreatercurve** [comment]
Generally, I think this behaviour is fine and expected within the playground. Starting a sentence with `[` should be enough to trigger the checkbox list styling.
