### ISSUE TITLE
Feature: Add a new field in EditorState to save data other than NodeMap and Selection

### ISSUE THREAD

**Issue by yf-yang** [facebook/lexical#3501]
Now (I'm using V0.6) EditorState has two data fields: nodeMap and selection. However, someone may need additional fields to save data not organized by nodes.

One scenario is to reduce the editor state size (for serialization). For example, multiple ImageRefNode may link to the same image saved **locally** in EditorState. Now, the only solution is to  save the image multiple times in each node. It makes the state large, and I need additional mechanisms to make sure they are synchronized with each other.

To solve the problem, two solutions are possible. 
The first one is adding a new field, then make EditorState type a generic and provide an additional hook (with a type parameter) to set and get the data. 
An alternative way is to allow developers to extend EditorState class. I am not sure how this way could be implemented.

**Comment by thegreatercurve** [comment]
Thanks for the suggestion, but I'm not sure if there's a strong enough use case for this feature. 

The node map and selection fields on the EditorState class are internal methods (hence the underscore) and shouldn't be used to store global state or to dedupe common values on repeated nodes, especially as we typically just use the EditorState class as a frozen immutable snapshot of the state at a certain point in time which we clone when we do an update.

If you need to dedupe common values for sending to an API, you can just do that at the point of serialisation.
