### ISSUE TITLE
Feature: Is there a way to paginate the editor?

### ISSUE THREAD

**Issue by vladcl** [facebook/lexical#3504]
Hey, guys!

I'm using this editor to create a document style and then create a pdf document with another lib, but the user is not able to know how many pages there are when he is creating the document style in the editor. is there any way to add pagination to the editor?

**Comment by trueadm** [comment]
There’s no built in pagination one common approach is to have a different editor for each page and using a node transform to detect when content goes past the bottom to move it into the other editor.
