### ISSUE TITLE
Bug:  Experimental table can‘t display in plainText mode

### ISSUE THREAD

**Issue by wsyks** [facebook/lexical#3517]
when isRichText is false  the Experimental table is empty
because cellEditor is null  
in TableComponent.tsx:
```
  if (cellEditor === null) {
    return;
  }
```

**Comment by trueadm** [comment]
Tables are a form of rich content?

**Comment by acywatson** [comment]
Yes, this doesn't make sense. If you want to use tables, you can't be in plain text mode.
