### ISSUE TITLE
Bug: Selection not using window of current view 

### ISSUE THREAD

**Issue by bilobom** [facebook/lexical#3534]
## Context
- I'm using lexical inside an iframe portal , some functionalities work after [#2918](https://github.com/facebook/lexical/pull/2918), but selection doesn't seem to work. I suspect the reason is not using the window of the current view when reconciliation finished and selection is triggered . Specifically when getting DOM selection here : [#L533](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalUpdates.ts#L533) because it using this [shared/getDOMSelection](https://github.com/facebook/lexical/blob/main/packages/shared/src/getDOMSelection.ts) which is using top window not of the current view.

- This can have multiple implications, for exapmle KEY_ENTER_COMMAND not inserting line break ...etc because $getSelection will always return null.

Lexical version: 0.7.1

## Steps To Reproduce

1. [this codesandbox](https://codesandbox.io/s/objective-monad-h3z7gb?file=/src/plugins/ToolbarPlugin.js:4073-4117) includes a lexical editor inside an iframe portal and `<h1></h1> ` as content, when selected, selection is not triggered by `SELECTION_CHANGE_COMMAND`
2. See ToolbarPlugin for logs.

## The current behavior
Selection is null on iframe portals

## The expected behavior
Should have Selection on iframe portals

**Comment by cmmartin** [comment]
@bilobom I think this is fixed by https://github.com/facebook/lexical/pull/3578. Can you try [v0.7.3](https://github.com/facebook/lexical/releases/tag/v0.7.3)

**Comment by bilobom** [comment]
@cmmartin , I confirm this is working perfectly. thanks @trueadm .
