### ISSUE TITLE
Bug: Gboard causes cursor to jump back when navigating

### ISSUE THREAD

**Issue by Spencer-Sleep** [facebook/lexical#3538]
Lexical version: 0.7.1

## Steps To Reproduce

1. Use an (Android?) phone with Gboard
2. Put the cursor somewhere in the editor input that is not the end of a line
3. Click somewhere else in the editor input

Link to code example: https://codesandbox.io/s/lexical-plain-text-example-g932e

## The current behavior
When attempting to move the cursor, it jumps back to the current location immediately. Doesn't happen if the cursor is at the end of a line, doesn't happen if the keyboard is minimized.

Only happens if Gboard is enabled. Tested it on 3 different Android phones, all had the same behavior. Not sure if it happens on iOS as well.

### Video example
https://user-images.githubusercontent.com/1776412/207128608-edc8dda5-63a7-4303-a5c2-56898109512a.mp4

## The expected behavior
The cursor moves and stays were you put it

**Comment by trueadm** [comment]
Did this happen in earlier versions of Lexical?

**Comment by trueadm** [comment]
Thanks for that. Looking at the diff between 0.4 and 0.3.9, the one thing that stands out to me was logic around handling mousedown – which I assume might be occurring on Android when moving selection around. Specifically this:

https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalEvents.ts#L382-L394

I wonder if you can test locally disabling this logic (i.e. comment out that function). If that solves it, then I think the best plan of action is to switch from using the `mousedown` event to using the `pointerdown` event – which allows us to detect if the input type is mouse or touch (this logic is only meant for mouse users I believe).

**Comment by thegreatercurve** [comment]
This seems to be a Chromium specific bug. Tested on Firefox on Android and it works fine.

**Comment by trueadm** [comment]
@thegreatercurve if you make the change I mention above and comment out that function, does it resolve the problem?

**Comment by Spencer-Sleep** [comment]
@trueadm removing that event handler does fix the issue

**Comment by thegreatercurve** [comment]
> @thegreatercurve if you make the change I mention above and comment out that function, does it resolve the problem?

@trueadm It does indeed! Need to check for the `pointerType` as well, as `pointerdown` fires on mobile as well. 

#3541 should close the issue.

**Comment by reymon359** [comment]
Hey there 👋🏽  

I am facing a very similar issue in my app, and I am using version `"lexical": "0.7.6"`

when I click in the end of a word/line, it jumps to the beginning of it

Here is an example with the lexical playground

https://user-images.githubusercontent.com/31936665/227817927-b3d3ec6c-2b49-4341-adf3-1cce9481ac85.mp4

I am using a Google Pixel android phone with Gboard

Do you have any idea on how to fix it?
Did you make any change related to the code recently that may be causing this?

**Comment by reymon359** [comment]
Btw, I created an issue for the above https://github.com/facebook/lexical/issues/4207
