### ISSUE TITLE
Bug: Lexical Playground - Image is draggable

### ISSUE THREAD

**Issue by alessandroias** [facebook/lexical#3539]
## Into `ImageComponent.js`
`draggable` is set to `false`, not `"false"`.
https://github.com/facebook/lexical/blob/a2f3b2fe157bcd20d69c1e85b9203d6c52d244ab/packages/lexical-playground/src/nodes/ImageComponent.tsx#L104

**Comment by thegreatercurve** [comment]
I think this should actually be fine: 

> Warning: This attribute is [enumerated](https://developer.mozilla.org/en-US/docs/Glossary/Enumerated) and not Boolean. A value of true or false is mandatory, and shorthand like <img draggable> is forbidden. The correct usage is <img draggable="false">.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable
