### ISSUE TITLE
Feature: [Playground] Show href in status bar when hovering over links

### ISSUE THREAD

**Issue by zeitstein** [facebook/lexical#3545]
When hovering over links in the Playground, the status bar – which usually appears in browser's bottom-left corner displaying the href – does not appear. Would be nice to support this standard/expected behaviour.

Outside of scope of the issue but related: arguably, the cursor should be a pointer when hovering over links. You can select within a link, yes, but clicking on the link does not position the cursor (it opens the link).

**Comment by zeitstein** [comment]
> Hi I found the solution.

Are you certain? I had already tried that in my own project – the only thing it does is show the pointer on hover, doesn't show the link in the status bar? The issue seems related to the fact that the anchors are inside a `contenteditable`. E.g. setting `contenteditable=false` on the anchors regains the default behaviour.

**Comment by thegreatercurve** [comment]
If you want to show the actual link address on hover of the link, an easy solution is just to add the `title` attribute to the linke node so it shows on the `a` element.

**Comment by thegreatercurve** [comment]
Upon looking into this a little further, I think this constitutes default browser behaviour when a link is within a `contenteditable`.
