### ISSUE TITLE
Bug: List Indentation doesn't work in the playround

### ISSUE THREAD

**Issue by flex-kwoncheol** [facebook/lexical#3554]
Lexical version: 7.1.0

## Steps To Reproduce

1. Visit [lexical playground](https://playground.lexical.dev/).
2. Place the cursor on a list item.
3. Press Tab key

Link to code example: 

## The current behavior

Pressing the Tab key moves the cursor outside the editor. But the playground code has a [plugin for list indentation](https://github.com/facebook/lexical/blob/8680e5bdd8cc300dee6b52d041a5dfb5bbbc7a47/packages/lexical-playground/src/Editor.tsx#L161). #2855 seems to affect this and should be adrressed. 

## The expected behavior

List indentation changes when you press the Tab key on a list item in Playground.

**Comment by thegreatercurve** [comment]
We took it out in #2855 by default as it's inaccessible, but you can still add a plugin if you need that behaviour.
