### ISSUE TITLE
Bug: [Playground] Strange behaviour of popover menu when editing mentions

### ISSUE THREAD

**Issue by zeitstein** [facebook/lexical#3555]
## Steps To Reproduce

1. Add the "Aayla Secura" mention in Playground.
2. Type in "X" to change to "Aayla SecXura"
3. Move the cursor around – the mention popover appears in some positions.

It happens with other mentions/inputs as well. Notice that the popover appears also when changing the mention. For instance, if changed to "Admayla Secura" shows the popover with the admirals.

## The current behavior

In this example, the popover appears when offset is 3-5 and 9 (in img below).

![image](https://user-images.githubusercontent.com/8146007/207524880-2d0a8505-ed8f-4d0b-9ebe-0ecff4ccd2b4.png)

## The expected behavior

Honestly don't know, but current behaviour seems wrong.

**Comment by thegreatercurve** [comment]
@zeitstein Want to have a go at submitting a PR? This could be a good first issue.

**Comment by blacktoast** [comment]
Is it okay if I try to fix this issue?

**Comment by blacktoast** [comment]
I don't know if this is a bug, but in the picture below, it seems to read the string after @ and before the cursor to get the mention list.

If this is a bug, it should read the string after the @ character and before the newline to get the list of mentions, regardless of the cursor. 

e.g. In a situation like the photo, all strings after @ and before `aayla seea` should be read as

![Kapture 2023-02-10 at 19 27 27](https://user-images.githubusercontent.com/10705018/218069485-02f7d332-e1c1-4f8a-b6ba-0b2f4ba888b4.gif)

so Should I think it's a bug and correct it as I said?

@thegreatercurve @zeitstein

**Comment by tylerjbainbridge** [comment]
This is generally how mentions work, otherwise you wouldn't be able to mention someone in the middle of a paragraph without all of the text being sucked in. 

Maybe a compromise could be the cursor _OR_ the next space following the cursor?

Try it out in a few text editors and maybe leave some videos here with your findings :) But I believe most will only grab the text between the @ and the cursor.
