### ISSUE TITLE
Bug: Where to find - `LexicalTabIndentationPlugin`?

### ISSUE THREAD

**Issue by ScottAgirs** [facebook/lexical#3556]
As denoted in [these notes](https://github.com/facebook/lexical/pull/3522#issue-1486755613), indentation on <kbd>tab</kbd> press is no longer enabled by default, and the suggested solution is to use `LexicalTabIndentationPlugin`; however, I am failing to find the plugin.

Is this an oversight, or was the idea that we should create a plugin ourselves to enable back the <kbd>tab</kbd> indents? 

Frankly, (despite [this note](https://github.com/facebook/lexical/pull/2855#issue-1344599982)), I think it's a great feature to have enabled by default in Rich editor. That said, IMHO, this would be true for plain text, but I would argue that Rich Text Editing would benefit from having slightly more focus than simply indexing through.

Alternatively, maybe Lexical could pioneer something like <kbd>tab</kbd> + <kbd>alt</kbd> for indents and <kbd>tab</kbd> + <kbd>alt</kbd> + <kbd>shift</kbd> for outdents? 😃

**Comment by ScottAgirs** [comment]
Oh gawd, hate when this happens - creating an issue and finding the answer right after 🤦🏼 😅 

https://github.com/facebook/lexical/blob/8cb0c5ba04fa546e869aa8e35653aaac5f0adcab/packages/lexical-react/src/LexicalTabIndentationPlugin.tsx.

Sorry folks 😁

**Comment by trueadm** [comment]
Try doing:

```js
import { TabIndentationPlugin } from '@lexical/react/LexicalTabIndentationPlugin';
```

**Comment by ScottAgirs** [comment]
Hey @trueadm, many thanks; this works! 🥳
