### ISSUE TITLE
Bug: [Playground] Image gets stuck in resizing state

### ISSUE THREAD

**Issue by SharatChandar** [facebook/lexical#3562]
When resizing an Image over a long distance in lexical playground, the draggable event of the image is getting triggered. This causes the image to be stuck in the resizing state.
Lexical version:  "0.7.1",

## Steps To Reproduce

1. Add an image in playground
2. Resize over a considerable amount of distance by dragging the resize pointer

## Video

https://user-images.githubusercontent.com/27125472/207875504-2b69c7c9-5798-43ac-a801-cb694acd7040.mp4

## The current behavior
Image gets stuck in resize state

## The expected behavior
Image should not be draggable while resizing

**Comment by SharatChandar** [comment]
Fixed this by checking for resizing before setting image draggable to true in packages/lexical-playground/src/nodes/ImageComponent.tsx. Can i take up this issue myself and raise a PR ?

**Comment by acywatson** [comment]
> Fixed this by checking for resizing before setting image draggable to true in packages/lexical-playground/src/nodes/ImageComponent.tsx. Can i take up this issue myself and raise a PR ?

Yes, PR welcome. Thank you!

**Comment by acywatson** [comment]
> Fixed this by checking for resizing before setting image draggable to true in packages/lexical-playground/src/nodes/ImageComponent.tsx. Can i take up this issue myself and raise a PR ?

Yes, PR welcome. Thank you!
