### ISSUE TITLE
Bug: Editor crashes after using forward delete on decorate block

### ISSUE THREAD

**Issue by apiatetskyi** [facebook/lexical#3563]
If block emulated cursor (was added in #3434) is the last one in the editor state and you try to forward delete you will get error `Uncaught Error: Minified Lexical error #66`.

Lexical version: 0.7.1

## Steps To Reproduce

1. Go to https://playground.lexical.dev/
2. Delete all content
3. Insert horizontal rule
4. Delete last paragraph after horizontal rule
5. Move cursor to the right with arrow key (it should be horizontal emulated cursor)
6. Hit forward delete (mac: press fn+delete, win: press delete, not backspace)
7. Check console for errors

If it helps to solve... I tried to debug and after I added this check the problem was solved:
```ts
// packages/lexical/src/LexicalSelection.ts:1871

deleteCharacter(isBackward: boolean): void {
    if ($isRootOrShadowRoot(this.anchor.getNode())) {
      return;
    }

    // ...rest of the code...

```

https://user-images.githubusercontent.com/13763030/207917489-fb6a5246-8860-433e-b9a7-78dca874688e.mov

## The current behavior
Editor crashes after trying to forward delete when selection is on emulated cursor.

## The expected behavior
Maybe we should just skip such action.

**Comment by trueadm** [comment]
The issue is here:

https://github.com/facebook/lexical/blame/main/packages/lexical/src/LexicalSelection.ts#L1885-L1887

This should be re-written to check for the parent instead of throwing on it being null. So maybe something like:

```js
const parent = anchorNode.getParent();
const nextSibling = anchorNode.getNextSibling() || (parent === null ? null : parent.getNextSibling());
```

As the root node will never have a parent, we should always validate the parent is not null. Feel free to put up a PR
