### ISSUE TITLE
Bug: call $setSelection in editorState.read()

### ISSUE THREAD

**Issue by yf-yang** [facebook/lexical#3570]
I notice `$setSelection` only calls `getActiveEditorState`( without `errorOnReadOnly` and `getActiveEditor`), which means I am able to update selection in a `editorState.read` call. Is it a desired behavior?

To reproduce:
``` typescript
editor.getEditorState().read(() => {
      const selection = $getSelection();
      $setSelection(null);
});
```

Desired behavior: throw an error.

**Comment by trueadm** [comment]
Nice spot. Feel free to put up a fix and we can get it merged :)

**Comment by yf-yang** [comment]
A suggestion: 
In my understanding, `LexicalNode.getLatest` and `LexicalNode.getWritable` not only provide a consistent node from pending editorState, but also checks if write permission is allowed. Similarly, when I need to implement a `$` API function with write permission, I may need to
1. call a built-in `$` write function.
2. call a LexicalNode method that writes something.
3. modifies something managed by myself, but prohibits the function being called in a read context.
For case 3, `errorOnReadOnly` is not exported from the core package. I think providing some utility functions like `getWritable()` that wraps `errorOnReadOnly` is necessary.

**Comment by trueadm** [comment]
Calling `getWritable()` will always do the readonly check, so we advise non core packages to do that. In fact, we've tried to remove calls to `errorOnReadOnly` where we know `getWritable()` is being called in core too – to keep it uniform (we might have missed some places though).
