### ISSUE TITLE
Feature: Remove a block

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [facebook/lexical#3585]
Hey guys, 

I am looking at the playground and it looks like there is no easy way to remove a block (like an icon on the right side or an even when clicking on the right button). Am I missing something, maybe an additional config or this is the correct behaviour?

Thanks a lot :)

Cheers,

Francesco

**Comment by trueadm** [comment]
What do you mean by removing a block? Does backspace or delete on your keyboard not work?

**Comment by FrancescoSaverioZuppichini** [comment]
hey @trueadm thanks for your reply! I made a loom video since I think it's easier to show what I meant 

https://www.loom.com/share/859d7152f13340748029a28cbbfbb320

**Comment by acywatson** [comment]
> hey @trueadm thanks for your reply! I made a loom video since I think it's easier to show what I meant
> 
> https://www.loom.com/share/859d7152f13340748029a28cbbfbb320

I think the confusion here is that Lexical isn’t a block-based editor like notion. It could be used to build such an editor, but I don’t think we need to introduce block management as a first-class concept in the playground. You should be able to do this yourself if you want to.

**Comment by FrancescoSaverioZuppichini** [comment]
@acywatson thanks! I am indeed a little bit confused, by scanning the playground code I can see there is a notion of "block" base, when you hit enter for instance you create a new "block" that you can move around. 

I am very excited by lexical and plan to use it to build an open-source text editor strongly focused on leverage AI language models and I would like to ask for a little bit of guidance. 

It would be great if you can ping point in the right place in the playground code where "block" are handled (I am referring to the icon on the left that let you move around the block). Moreover, I'd love to ask the same thing for the plugin that handles the "/" chars, the feature where you hit "/" and opens the command palette on the text editor.

I hope this is the right place and I don't want to bother you guys too much, I really love lexical philosophy but I am a little intimidate by the amount of code/plugins in the playground section and I think a little bit of guidance will help me a lot

**Comment by thegreatercurve** [comment]
The slash command is otherwise known as the `ComponentPickerPlugin`  and the drag and drop functionality is in the `DraggableBlockPlugin` plugin.

**Comment by FrancescoSaverioZuppichini** [comment]
Thanks a lot @thegreatercurve

**Comment by nabanita-sarkar** [comment]
> The slash command is otherwise known as the `ComponentPickerPlugin` and the drag and drop functionality is in the `DraggableBlockPlugin` plugin.

Is there any documentation for these plugins? I couldn't find these in https://lexical.dev/
