### ISSUE TITLE
Bug: `MarkdownImport` does not escape plus signs in the provided tag

### ISSUE THREAD

**Issue by tehapo** [facebook/lexical#3596]
I was trying to use `++` as the tag for underline when converting to and from Markdown by adding a custom `TextFormatTransformer`. Unfortunately this fails with an invalid regular expression error.

Looking at the source code, it seems to me like this could be fixed by escaping the plus sign in [MarkdownImport](https://github.com/facebook/lexical/blob/main/packages/lexical-markdown/src/MarkdownImport.ts#L372), but I don't know if there are any unwanted side-effects of doing that.

```typescript
// This...
const tagRegExp = tag.replace(/(\*|\^)/g, '\\$1');

// ...should also include the plus sign?
const tagRegExp = tag.replace(/(\*|\^|\+)/g, '\\$1');
```

This is the `TextFormatTransformer` I was trying to use.
```typescript
{
  format: ['underline'],
  tag: '++',
  type: 'text-format'
}
```

**Comment by fantactuka** [comment]
Sounds reasonable, feel free to create a PR! 👍
