### ISSUE TITLE
Bug: MarkNode cannot be overriden

### ISSUE THREAD

**Issue by moy2010** [facebook/lexical#3605]
The `MarkNode` from `@lexical/mark` cannot be overriden as per the current notion of [Node Overrides](https://lexical.dev/docs/concepts/node-replacement).

Lexical version: 0.7.4

## The current behavior

The issue comes from the fact that the `exportJSON` method implementation of `MarkNode` returns `SerializedMarkNode`. Unfortunately, returning `SerializedElementNode` is not an option since `SerializedMarkNode` has an `ids` property which `SerializedElementNode` doesn't have, and adding it to it feels out of place.

## The expected behavior

The `MarkNode` should be overridable, just like any other node.

**Comment by moy2010** [comment]
Some additional thoughts:

The implementation of `MarkNode` feels too tightly coupled to the `CommentPlugin`, and the `ids` property on `SerializedMarkNode` is a proof of that. 

I have also been thinking about if this functionality (wrapping in a `mark` node) should be provided by an `ElementNode` rather than by a format from the `TextNode` (exactly just like the `code` format). 

A few days ago I opened a [PR](https://github.com/facebook/lexical/pull/3583) to add this since I wasn't aware of the existance of the `@lexical/mark` package, but after a few days of interacting with the API i feel more and more inclined to the reasoning explained above.

**Comment by acywatson** [comment]
> The implementation of `MarkNode` feels too tightly coupled to the `CommentPlugin`, and the `ids` property on `SerializedMarkNode` is a proof of that.

I don't see how this is proof of anything - an id is a generic way of associated literally anything with the mark. it can be a comment or it can not be a comment or it doesn't have to have an id at all (AFAIK).

On the other hand, I don't see a reason why we can't have both here. A Lexical MarkNode, like every other LexicalNode, doesn't have a mutually exclusive relationship to a particular DOM node. You can have a TextNode format that adds an HTML mark, like in your PR. I don't see an issue with that, but you might run into some limitations depending on your use case.

> The issue comes from the fact that the exportJSON method implementation of MarkNode returns SerializedMarkNode. Unfortunately, returning SerializedElementNode is not an option since SerializedMarkNode has an ids property which SerializedElementNode doesn't have, and adding it to it feels out of place.

This is an issue with the serialization type system and not necessarily related to MarkNode specifically.

**Comment by moy2010** [comment]
> I don't see how this is proof of anything - an id is a generic way of associated literally anything with the mark. it can be a comment or it can not be a comment or it doesn't have to have an id at all (AFAIK).
> 

Well, yes, of course. For me it can be either, it just depends on the perspective you are looking at the problem from; I just see the `ids` property as an implementation detail that does not belong in the `MarkNode`. 

I wanted to bring this up for discussion among the contributors since I have just spent a few days with Lexical and I'm not aware of all the design decisions behind it. I will re-open the PR and see if we can push it forward :).
