### ISSUE TITLE
Bug: Unable to select text on nested fields in decorator nodes

### ISSUE THREAD

**Issue by Piliuta** [facebook/lexical#3620]
Lexical version: 0.7.4

## Steps To Reproduce
1. Create a contenteditable field inside a decorator node (or use any existing decorator and inject it via dev tools for example, see screenshot)
2. Set focus inside the lexical content
3. Attempt to select text in the contenteditable field

<img width="637" alt="image" src="https://user-images.githubusercontent.com/1575198/209196328-4c583a47-3446-41cd-8674-c93512c35b65.png">

https://user-images.githubusercontent.com/1575198/209196552-7587f4ee-2b64-4aa3-a36b-01e073dc2114.mov

**Note:** Text can be selected if lexical content is not focused.

**Comment by Piliuta** [comment]
hey @trueadm Thank you for fixing this issue so fast. It does work in this specific case, however, it is still a problem with nested elements that are meant to be selectable. It feels like it needs a more generic approach for selectable elements.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/1575198/209308619-574d90d1-1406-4ddd-ab5d-d91dc2d52466.png">

https://user-images.githubusercontent.com/1575198/209309010-68b71e05-6d47-4c69-89e0-8e641eac87bd.mov

**Comment by trueadm** [comment]
I can’t think of a more generic way of doing this, unless you can?

**Comment by Piliuta** [comment]
Are there any reasons it resets the selection apart from that nested lexical editors have the shared listener?

Can the condition be the opposite - allow any selections within decorator nodes unless it is focused on a nested lexical field?

```js
!($isDecoratorNode($getNearestNodeFromDOMNode(anchorDOM)) && activeElement.__lexicalEditor != null)
```

**Comment by trueadm** [comment]
That doesn't change anything unfortunately. You can still select the text, you just need to click it first – which isn't perfect but definitely isn't a blocker IMO. The biggest issue we have to deal with is ranges of selection – and where the range might start within a decorator and end outside – something impossible to model within Lexical. So we do our best to prevent it from occuring.

**Comment by Piliuta** [comment]
It is an issue in my implementation because I have decorator nodes with other contenteditable fields (not lexical) that provide a "click to edit" interface (similar to JIRA fields as an example). So the click triggers a different action and it does not allow selecting the text.

> The biggest issue we have to deal with is ranges of selection – and where the range might start within a decorator and end outside
Why is it an issue with lexical at all? And again, why it is **not** an issue when lexical is not focused?

It seems to me that ignoring events that are fired with non-lexical elements being active is pretty legit. I would expect having a simple condition as `if (activeElement.__lexicalEditor === null) { /* ignore event */ }` to work, even without checking if it is inside the decorator or not. (Obviously, I might be missing something lexical specific)

**Comment by trueadm** [comment]
I tried doing that but it didn’t seem to affect anything. I’ll take another look at this after the holiday season :)

**Comment by Piliuta** [comment]
> I tried doing that but it didn’t seem to affect anything. I’ll take another look at this after the holiday season :)

Sure thing. Thank you so much for all the work. 🤲

**Comment by Piliuta** [comment]
hey @trueadm. Any chance this can be investigated again?

**Comment by trueadm** [comment]
I'm limited on bandwidth right now. Will try if I get time.
