### ISSUE TITLE
Feature: DraggableBlockPlugin for multiplayer

### ISSUE THREAD

**Issue by katsuya** [facebook/lexical#3626]
I'm trying to implement the title feature, but with the current implementation that manages orders in arrays, it's difficult to move blocks without conflicts.

Is there any motivation to change to a specification such as fractional indexing used by figma? https://www.figma.com/blog/realtime-editing-of-ordered-sequences/#fractional-indexing

Finally, lexical is really cool, thanks for making it OSS.

**Comment by thegreatercurve** [comment]
All sets of sibling block elements are implemented with a doubly linked list. This is something that we implemented fairly recently for performance reasons, changing from a standard Array.

In terms of adding fractional index, we've not had many reports about the linked lists leading to issues with collaborative editing, yet, and I wouldn't want to complicate an implementation which is already quite complex.

**Comment by thegreatercurve** [comment]
Closing this as I don't think this is a change we will implement.
