### ISSUE TITLE
Feature: Provide a way to customize generateRandomKey and exportJson and importJson

### ISSUE THREAD

**Issue by katsuya** [facebook/lexical#3627]
I would like to break up the exported json by node to store it in RDS and only update the record associated with the node that has changed.

For the above we need the following features.

1. replacing the function that issues the key
2. adding key to export json
3. restore key on import

I think exposing the key is quite different from the intention. However, I believe it is necessary in order to store each node in RDS. Also, if you provide a way to do the same without publishing the key, that would be great.

Related Issue: https://github.com/facebook/lexical/issues/3485

**Comment by thegreatercurve** [comment]
We use the generated keys internally to optimize the reconciler. Letting users override these and set them individually could break this logic. I don't think this is something we ever want to support. 

If you need to add dynamic keys to your JSON, you could do this outside of Lexical via an update listener.
