### ISSUE TITLE
Feature: List nesting

### ISSUE THREAD

**Issue by rahulgoyal8312** [facebook/lexical#3628]
Currently we are building Editor for Content formatting and transformation and Listing is a very crucial part of any content along with Nested lists but in latest updates of Lexical nested lists have been removed. Earlier when Nesting of list was possible the format wasn't correct semantically, it was creating a separate List Item Node then Adding List in that and then handling the behaviour with the help of CSS.

Example (in previous lexical version):

`<ul><li><span>abc</li><li><ul><li><span>child of abc</span></li></ul></li></ul>`

But how it should be:

`<ul><li><span>abc</span><ul><li><span>child of abc</span></li></ul></li></ul>`

It would be great if this functionality is present and enables user(s) to add nested list, Thanks in advance!

**Comment by surya** [comment]
I need this functionality too. But there's an issue already: #2951.

**Comment by thegreatercurve** [comment]
Closing as duplicate
