### ISSUE TITLE
Bug: Editor doesn't create `em` tag if both bold and italic are applied on a text node

### ISSUE THREAD

**Issue by surya** [facebook/lexical#3629]
Lexical version: 0.7.4

## Steps To Reproduce

1. Go to https://playground.lexical.dev/
2. Select some text and apply both bold and italic formatting

Link to code example: https://playground.lexical.dev/

## The current behavior

1. Editor wraps the text in `strong` but not `em`.
2. If you remove bold formatting, editor converts the `strong` element to `em`

`sample text` -> apply bold and italic -> `<strong classes="classes for bold and italic">sample text</strong>` -> remove bold -> `<em classes="classes for italic">sample text</em>`

## The expected behavior

1. Editor should create both `strong` and `em` elements if both bold and italic formatting are applied. Current html output is not consistent and creates problems if we render it in a different place where custom styling is not available.

`sample text` -> apply bold and italic -> `<strong classes="classes for bold"><em classes="classes for italic">sample text</em></strong>` -> remove bold -> `<em classes="classes for italic">sample text</em>`

**Comment by trueadm** [comment]
This was already fixed yesterday. :)

**Comment by emaborsa** [comment]
> This was already fixed yesterday. :)

But still not merged, right?

**Comment by karmaral** [comment]
This seems to be happening still!

**Comment by emaborsa** [comment]
In version 0.12.2 seems to be fixed.

**Comment by karmaral** [comment]
[This sandbox](https://codesandbox.io/s/lexical-rich-text-example-5tncvy) (taken from the official docs) uses 0.12.2 and it produces the bug:  
Italic + bold markup is  
`<strong class"editor-text-bold editor-text-italic>text</strong>`  
instead of  
`<strong><em>text</em></strong>`

**Comment by emaborsa** [comment]
I fear this is not a bug, it is a feature. As you can see, they use the right element for the first style you apply and the inline CSS for the further ones. If you try to add underlined and strikethrough, you will find more inline styles, but the element remains `strong`.

**Comment by jhb123** [comment]
I was experiencing a similar thing to what is described in this issue, but I found that it was happening because I hadn't set the theme up. Adding styles for bold and italic fixed my problem
