### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by lacvapps** [facebook/lexical#3633]
Lexical version: 0.7.5

## Steps To Reproduce

1. create a new react app
2. install lexical and lexical/react
3. try to use the CollaborationPlugin

## The current behavior
Uncaught TypeError: yjs.UndoManager is not a constructor

## The expected behavior
it works

**Comment by trueadm** [comment]
I don’t see the same issue? It works fine for me

**Comment by acywatson** [comment]
Please re-open if/when you can provide a repro.

**Comment by lacvapps** [comment]
If you run this code on code sandbox it works fine, but if you clone the repo and run locally you will get the error

Code Sandbox
https://codesandbox.io/s/brave-bose-z9vw95

Github
https://github.com/lacvapps/lexical-react-collab

**Comment by lacvapps** [comment]
@acywatson @trueadm I am unsure how to reopen the issue

**Comment by trueadm** [comment]
It’s likely an issue with your local env loading multiple yjs’s. You can try asking in the Lexical discord for how other folks have fixed similar issues with their build setups

**Comment by lacvapps** [comment]
This was fixed by using yarn instead of npm
