### ISSUE TITLE
Bug: `DELETE_WORD_COMMAND` is dispatched even when keys other than `ctrl` are pressed

### ISSUE THREAD

**Issue by zeitstein** [facebook/lexical#3642]
## Steps To Reproduce

1. Try `ctrl+shift+backspace` in Playground.

## The expected behavior

The command should be dispatched only on `ctrl+backspace/delete`. This is the default and expected behaviour; `beforeinput` only fires for that particular combination. I think the issue originates here: https://github.com/facebook/lexical/blob/6e65c989c0d379dccfe28078a76ef49e4dc66443/packages/lexical/src/LexicalEvents.ts#L895-L900

**Comment by thegreatercurve** [comment]
This seems like expected behavior even in native elements like textareas. If I use Option+Shift+Backspace on my Mac keyboard in a HTML `textarea`, the word gets fully deleted as well.

**Comment by zeitstein** [comment]
Apologies. I had tested my claims, but now had a friend who is also on Windows verify – it seems `ctrl+shift+backspace` doesn't work only on my machine.

Can you suggest a way to cancel the default behaviour for this key combination? I have registered a listener for `KEY_MODIFIER_COMMAND` but I cannot find a way to cancel the `DELETE_WORD_COMMAND` (for only this particular combination). The latter command takes a boolean, not a keyboard event, as payload. And it seems to always run first.
