### ISSUE TITLE
Bug: Markdown mode with multiline code-block = invalid line numbers indicator

### ISSUE THREAD

**Issue by comerc** [facebook/lexical#3645]
**expected behavior**
<img width="294" alt="Screen Shot 2022-12-27 at 16 38 56" src="https://user-images.githubusercontent.com/1025241/209675266-ee546059-988d-48f1-897a-5df5ea6c5897.png">

**bug**
<img width="310" alt="Screen Shot 2022-12-27 at 16 42 35" src="https://user-images.githubusercontent.com/1025241/209675277-6ffed66f-aecc-4b0b-ae5b-4ac29ee6962b.png">

**Comment by comerc** [comment]
<img width="832" alt="Screen Shot 2022-12-27 at 16 46 38" src="https://user-images.githubusercontent.com/1025241/209675707-a3a413bf-54f8-402e-bb5f-5921144b68e0.png">

**Comment by comerc** [comment]
<img width="755" alt="Screen Shot 2022-12-29 at 21 22 42" src="https://user-images.githubusercontent.com/1025241/209993828-fc9253dd-9cd2-4328-b017-d42fda4b07d0.png">

solution: uncomment line 100

**Comment by thegreatercurve** [comment]
Line numbers are a known issue and we have open issue to refactor the code block, in general, including fixing the line numbers. Closing this as a duplicate.
