### ISSUE TITLE
Feature: Devtools extension would recognize the Lexical editor even if it render later

### ISSUE THREAD

**Issue by juniorbatistadev** [facebook/lexical#3647]
The devtools extension seems to recognize the Lexical editor only when it's present during the page's initial load. I know extensions have limited access to the DOM and can't read modifications to the DOM after page load. However, I believe it's possible to inject a script tag. The injected script would have full access to the DOM. And would detect when the Lexical Editor is rendered.

Our specific case is a Next.js page with an auth conditional, the editor doesn't show until the user is authed. With the conditional, the extension doesn't work because the editor is not rendered until later. Without the conditional, the editor is recognized by the extension.

**Comment by thegreatercurve** [comment]
The DevTools extension is unstable and is still under active development, hence why it's not been published to any browser stores. This is a point worth noting though when we undertake development of this extension at some point this half. 

Closing this as we have an issue for the progress of building the browser extension (#2127).
