### ISSUE TITLE
Bug: LexicalCharacterLimitPlugin CHARACTER_LIMIT - 5 (hardcoded) cant be changed

### ISSUE THREAD

**Issue by harryranakl** [facebook/lexical#3648]
Lexical version:v0.7.5

## Steps To Reproduce
1. try lexical playground and enable char limit from the options
2. CHARACTER_LIMIT is fixed to 5 and cant be changed

Link to code example:
https://github.com/facebook/lexical/blob/6e65c989c0d379dccfe28078a76ef49e4dc66443/packages/lexical-react/src/LexicalCharacterLimitPlugin.tsx#L15

## The expected behavior
CHARACTER_LIMIT should be through the plugin props, similar to MaxLengthPlugin

reference to CharacterLimitPlugin -
https://github.com/facebook/lexical/blob/6e65c989c0d379dccfe28078a76ef49e4dc66443/packages/lexical-playground/src/Editor.tsx#L217

reference to MaxLengthPlugin - 
https://github.com/facebook/lexical/blob/6e65c989c0d379dccfe28078a76ef49e4dc66443/packages/lexical-playground/src/Editor.tsx#L120

**Comment by trueadm** [comment]
Fixed in https://github.com/facebook/lexical/pull/3649
