### ISSUE TITLE
Bug: MaxLengthPlugin throws error when pasting large content

### ISSUE THREAD

**Issue by 1kvsn** [facebook/lexical#3650]
When MaxLength is enabled in Playground, clear the editor and paste large text into it, you'll find an error appears in console and the paste was rejected.

The error is: https://lexical.dev/docs/error?code=52

Lexical version: 0.7.5

## Steps To Reproduce

1. Clear the Playground Editor
2. Enable MaxLength Plugin
3. Open Console in DevTools
4. Copy Large Content Into Clipboard. I copied this entire page content (https://en.wikipedia.org/wiki/Project_Gutenberg)
5. Paste into Playground Editor
6. Check Console

## The current behavior

`main.7743b947.js:21 Uncaught Error: Minified Lexical error #52; visit https://lexical.dev/docs/error?code=52 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

![image](https://user-images.githubusercontent.com/17102570/209760517-bea5bc7b-1206-476d-bcd3-dab5584c460a.png)

## The expected behavior
The MaxLengthPlugin should not throw error.

**Comment by HovhannesMkoyan** [comment]
I am also getting an error when pasting larger content than specified in the `maxLength`. However, this seems to be different: `Error: remove: cannot be called on root nodes`

<img width="1688" alt="Screenshot 2023-01-05 at 22 51 31" src="https://user-images.githubusercontent.com/2642271/210857994-58e565a2-34eb-4bb7-9816-cf4e07731de7.png">

**Comment by SenaHuang** [comment]
There is something wrong after paste large content. I create a new issue #4559
