### ISSUE TITLE
Bug:  Build failure in remix github action 

### ISSUE THREAD

**Issue by chenchunaidu** [facebook/lexical#3653]
Description: I am using  @lexical/react package inside remix when i try to build in my local code is working fine 
but when it runs on the ci/cd pipeline build is failing an saying

<img width="1013" alt="Screenshot 2022-12-28 at 9 51 19 PM" src="https://user-images.githubusercontent.com/38114196/209841923-feaa7b72-b19b-4e93-8b36-329acc079ff1.png">

Lexical version:  "@lexical/react": "^0.7.5",

## The current behavior
1. Build failure

## The expected behavior
Build should done successfully

**Comment by thegreatercurve** [comment]
@chenchunaidu Are you importing the `lexical` library in your `package.json` as well? Closing for the moment as I don't think this is necessarily a Lexical-specific issue.
