### ISSUE TITLE
Bug: editorState.isEmpty not working as expected in case of rich-text

### ISSUE THREAD

**Issue by sebakerckhof** [facebook/lexical#3656]
It seems like `editorState.isEmpty()` is only true if there's no selection and only a root node: https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalEditorState.ts

However, when initializing a new editor with the rich text plugin, you automatically get an empty paragraph node as child of root. And when you type text and remove it again, there's also an empty text node. So in all of these cases the contenteditable is empty, but `isEmpty` returns false. 

I understand that this might be difficult in the general case, since who knows what kind of nodes people add. There might be invisible nodes etc.
So maybe the isEmpty method just needs better documentation, as I found this quite confusing.

Btw, my current approach is: `editorState.toJSON().root.children?.[0]?.children?.length;`, but this obiously seems very hacky. Suggesions for a better solution are very welcome.

**Comment by sebakerckhof** [comment]
ah, found this: https://github.com/facebook/lexical/blob/main/packages/lexical-react/src/useLexicalIsTextContentEmpty.ts

**Comment by bilobom** [comment]
use this instead to check form empty editor: 
```ts
import { $canShowPlaceholder } from "@lexical/text";

lexicalEditor.getEditorState().read(() => {
  // if editor is empty (contain pragraph inside it <br>)
  const isEmpty = $canShowPlaceholder(lexicalEditor.isComposing());
});

```
