### ISSUE TITLE
Bug: Impossible to click on an image or a checkbox in a Chakra modal

### ISSUE THREAD

**Issue by Godefroy** [facebook/lexical#3657]
I'm using a lot of editor instance in [Chakra UI modals](https://chakra-ui.com/docs/components/modal) and I get a persistent bug:

It's impossible to click on an image to resize it or to toggle a checkbox.

You can test it here: https://storybook.rolebase.io/?path=/story/richeditor--in-modal

Code of the story "InModal" I used to test it: https://github.com/lonestone/rolebase.io/blob/main/src/components/molecules/editor/lib/RichEditor.stories.tsx#L168 

I'm searching why but I don't understand what's going on.

Lexical version: 0.7.5

**Comment by trueadm** [comment]
The Lexical checklist plugin adds a document click event handler. It would seem that some logic somewhere in the modal code is also incorrectly listening to the click event and stopping propagation.

**Comment by Godefroy** [comment]
Indeed, well seen!

As I understand, this behaviour is intended:
https://github.com/chakra-ui/chakra-ui/issues/4010

I think lexical should listen to events from specific elements instead of root document when possible.

**Comment by Godefroy** [comment]
Thank you @thegreatercurve for the fix!

It seems it only fixes it for checkboxes but not for images. Do you think you could do the same fix for images?

**Comment by username14415** [comment]
+1
I use headless ui dialog modal and the same, images are not clickable

**Comment by Godefroy** [comment]
@thegreatercurve Coul you please reopen this issue?
