### ISSUE TITLE
Experimental Table

### ISSUE THREAD

**Issue by emaborsa** [facebook/lexical#3660]
Hi all, for testing purpuses I am trying to include/copy the experimental table from the playground into my project. The code is running without errors, but just an empty paragraph node is added to the node. The `INSERT_NEW_TABLE_COMMAND` is triggered and catched by the `TablePlugin`. I know it is hard to find a problem without takeing a look to the code, but I wanted to ask if there could be an particular reason why the node is not added.

**Comment by trueadm** [comment]
It's really hard to know the issue without seeing any code. My guess is that you're running into an error somewhere? Have you checked your console? Have you registered the experimental table node on your editor's initial config?

**Comment by thegreatercurve** [comment]
Closing for the moment as the underlying issue is unclear.
