### ISSUE TITLE
Feature: make excluded properties from yjs sync configurable

### ISSUE THREAD

**Issue by husseinraoouf** [facebook/lexical#3670]
I need to be able to exclude specific fields from yjs sync, because i want to centralize logic related to the node in the node class not just the node's data

I see there a Set called `excludedProperties` defined statically in lexical code https://github.com/facebook/lexical/blob/4dae4fb39d1ba6e4cc181b22652bfeed72a67e34/packages/lexical-yjs/src/Utils.ts#L42-L52
I mainly want a way to be able to add more filed in that set

the alternative solution is to keep a map that observe the nodes create through a mutation listener and just keep the data i don't want to sync there

I can make a PR if it is okay to implement this feature

**Comment by trueadm** [comment]
Feel free to put up a PR that exposed a way of doing this. i.e.

```js
export function addExcludedProperty(property: string): void {
  excludedProperties.add(property);
}
```

**Comment by Vishruta-Patil** [comment]
@trueadm  If this issue is not resolved, can I work on it ?

**Comment by zurfyx** [comment]
I believe this issue is still open to contributors

**Comment by fantactuka** [comment]
Hi @husseinraoouf, could you explain your usecase a bit more, I wonder if there's another way around rather than storing data on node and excluding it from collab sync. We've discussed current approach a bit more, and want to get more context for further enhancements

**Comment by GermanJablo** [comment]
Hey @fantactuka and @zurfyx, so is there a way to exclude a property from yjs?

My use case is that I have a very complex decorator node, and I want to put the controller (think something analogous to `LexicalComposer`'s `editor`) in a property of the node.

I've tried to get around this by just using the controller inside the `decorate` method, where I have access naturally, but the state of Lexical and that of this Decorator are very deeply integrated in external places like markdown transformers, or custom selection classes.

**Comment by dropmann** [comment]
+1
