### ISSUE TITLE
Feature: Single line input / prevent line break

### ISSUE THREAD

**Issue by marcospassos** [facebook/lexical#3675]
Is there any way to prevent line breaks somehow? Out use case is a rich text editor for headlines where line breaks aren't allowed.

**Comment by trueadm** [comment]
The simplest way is to use a node transform on your heading node and check its children for a line break and remove it. This will scale well for when someone might copy and paste a linebreak in too (vs the naive approach of blocking the keyboard shortcut).

**Comment by markcnunes** [comment]
In case someone is looking for an example, here is what worked for me:

```
  useEffect(
    () =>
      mergeRegister(
        editor.registerNodeTransform(RootNode, (rootNode: RootNode) => {
          if (rootNode.getChildrenSize() <= 1) return;
          rootNode.getLastChild()?.remove();
        }),
        editor.registerNodeTransform(LineBreakNode, (node) => {
          node.remove();
        }),
      ),
    [editor],
  );
```
