### ISSUE TITLE
Feature: official HorizontalRulePlugin

### ISSUE THREAD

**Issue by DaniGuardiola** [facebook/lexical#3680]
HorizontalRulePlugin is currently part of the playground code, but we're using it and we had to copy it into our codebase to use it, which comes with disadvantages like missing updates and having to do manual maintenance. This also feels weird because the node itself is actually shipped as part of the lexical packages.

**Comment by trueadm** [comment]
It’s part of the `@lexical/react` package on npm

**Comment by DaniGuardiola** [comment]
@trueadm the node is, but AFAIK the plugin is not. At least the only one I can find is in the playground package.

**Comment by trueadm** [comment]
Feel free to create a PR to move the HorizontalRulePlugin into `@lexical/react` package :) thank you!
