### ISSUE TITLE
Bug: Removing paragraph before decorator nodes breaks state stucture

### ISSUE THREAD

**Issue by Piliuta** [facebook/lexical#3683]
Lexical version: 0.7.5

## Steps To Reproduce

1. Add any decorator node in a text
2. Select the whole paragraph above the node (tripple-click)
3. Delete it

https://user-images.githubusercontent.com/1575198/211014899-3d261136-ea0d-40d4-a314-60d91af66d24.mov

## The current behavior
All nodes after the deleted one become wrapped into a paragraph

## The expected behavior
Lexical should never generate an invalid state (and thus not render it as such). I think this is a high-priority problem as invalid states lead to unexpected consequences and thus make the product unstable. E.g. this generates HTML output like `<p><p></p></p>` which is not valid because paragraphs should never contain block elements.
It would be great to have a logic that controls state somewhere in the core so it never happens (I remember that was a different scenario with decorator nodes which generated invalid states, so it is not a one time issue)

**Comment by ntalamdotcom** [comment]
I am saving a list. but always wrapped by some dumb P tag
