### ISSUE TITLE
Bug: Toolbar button bug

### ISSUE THREAD

**Issue by Birddle** [facebook/lexical#3689]
Lexical version:^0.7.5

## Steps To Reproduce

1.A rich text editor was written to follow the official website documentation
https://codesandbox.io/s/lexical-rich-text-example-5tncvy
https://lexical.dev/docs/react/plugins#lexicalrichtextplugin
https://lexical.dev/docs/getting-started/react
2.When I use the native HTML tag <form><editor /></form>, clicking on any of the Toolbar buttons will set off the submit event.

Link to code example:
Just add <form></form> tags to the official template.
https://codesandbox.io/s/lexical-rich-text-example-5tncvy?file=/src/App.js
![image](https://user-images.githubusercontent.com/86408260/211311307-bd0a151d-b421-4ae9-8ef2-0cc032bc81c8.png)

**Comment by trueadm** [comment]
This isn't a Lexical bug. This is something you need to handle from React. If you add a button with type of submit, you need to handle that using a form, or add on `onClick` handler and do `event.preventDefault()` in the callback for it.

**Comment by Birddle** [comment]
Hi @trueadm 
I am using MUI and react-hook-form and yup plugins. When I add event.preventDefault() the problem goes away but I will not be able to submit the form. Maybe there is some plugin conflict in the current version?
There is my code:

```
const ArticleFields = () => {
    const {callSnackbar} = useSnackbar();
    const location = useLocation();
    const dataSet = location.state;
    //const {categories, tags} : any = useLoaderData();
    const categories = ['ngingx','java','nac'];
    const tags = [
        {title:'nginx',icon:"asdad"},
        {title:'saf', icon: "afgfsd"},
        {title:'zf',icon:"asdad"},
        {title:'java', icon: "afgfsd"},
        {title:'zsd',icon:"asdad"},
        {title:'dsfsf', icon: "afgfsd"},
    ];
    //Tags default value, data.tags fields === tags.title fields
    let tagSet: any[] | undefined = [];
    if (dataSet){
        tagSet = dataSet.tags.map((tag: string)=>{
            let n = tags.findIndex(t=> t.title === tag);
            return tags[n].title;
        })
    }
    const schema = Yup.object({
        title: Yup.string().required(),
        category: Yup.string().required(),
        tags: Yup.array().required(),
        //content: Yup.string().required(),
    }).required();
    const {register, handleSubmit, control, formState: {errors}} = useForm({
        resolver: yupResolver(schema),
    });
    const onSubmit = (data:any) => {
        callSnackbar(true, "Saved", "success");
        console.log(data);
    };
    return (
        <Box sx={{mt:5}}>
            <form onSubmit={handleSubmit(onSubmit)}>
                <Stack spacing={2}>
                    <TextField  {...register("title")} label="Title" placeholder="Article Title" defaultValue={dataSet? dataSet.title : ''}/>
                    <Controller control={control} name="category" render={({ field: { onChange } })=>(
                        <Autocomplete {...register("category")} disablePortal defaultValue={dataSet && dataSet.category} options={categories}
                                      onChange={(event, item) => {onChange(item);}} renderInput={(params)=> (
                            <TextField {...params} label="Category" />
                        )}/>
                    )}/>
                    <Controller control={control} name="tags" render={({ field: { onChange } })=>(
                        <Autocomplete {...register("tags")} defaultValue={tagSet} multiple limitTags={1} options={tags.map((option) => option.title)} filterSelectedOptions
                                      onChange={(event, item) => {onChange(item);}}
                                      renderInput={(params)=> (
                                          <TextField {...params} label="Tags" placeholder="Choose tags" />)}
                        />
                    )}/>
                    <Card>
                         //There is Lexical rich text editor
                        <MyEditor />
                    </Card>
                    <Box>
                        <Button variant="contained" type="submit">Save</Button>
                    </Box>
                </Stack>
            </form>
        </Box>
    );
}
```

**Comment by trueadm** [comment]
In that case you want a preventDefault in your onSubmit function instead.

**Comment by Birddle** [comment]
Sincerely thank you for your help, I am a rookie, I changed the code but now the submit button is not working, now the submit button is not working. 
```
<form onSubmit={(event: FormEvent<HTMLFormElement>) => {event.preventDefault();handleSubmit(onSubmit)}}>
```

I think maybe lexical could consider integrating some popular plugins? Using lexical in forms is a very widespread requirement.

**Comment by trueadm** [comment]
You won't need the `event.preventDefault()` in the button logic only the form logic. You need preventDefault otherwise the form will load the action, which will refresh the page.

**Comment by Birddle** [comment]
<form onSubmit={() => {preventDefault();handleSubmit(onSubmit)}}>


> Can you explain it in detail? I can't seem to implement preventDefault without the event.preventDefault() method, yes. I didn't google to this result

**Comment by trueadm** [comment]
Hold on, going back to your original question. What should the "Save" button do? If it shouldn't submit the form, then you need to remove `type="submit"` from the button.

**Comment by Birddle** [comment]
> Hold on, going back to your original question. What should the "Save" button do? If it shouldn't submit the form, then you need to remove `type="submit"` from the button.

This is a blog feature. I included the title, category, tag field and editor in the form and the save button is responsible for submitting the form to the REST API

**Comment by trueadm** [comment]
What does the code look like for your editor toolbar buttons?

**Comment by Birddle** [comment]
MyEditor.tsx
```
function Placeholder() {
    return <div className="editor-placeholder">Enter some rich text...</div>;
}

const editorConfig: any = {
    // The editor theme
    theme: EditorTheme,
    // Handling of errors during update
    onError(error: any) {
        throw error;
    },
    // Any custom nodes go here
    nodes: [
        HeadingNode,
        ListNode,
        ListItemNode,
        QuoteNode,
        CodeNode,
        CodeHighlightNode,
        TableNode,
        TableCellNode,
        TableRowNode,
        AutoLinkNode,
        LinkNode
    ]
};

export default function MyEditor() {
    return (
        <LexicalComposer initialConfig={editorConfig}>
            <div className="editor-container">
                <ToolbarPlugin />
                <div className="editor-inner">
                    <RichTextPlugin
                        contentEditable={<ContentEditable className="editor-input" />}
                        placeholder={<Placeholder />}
                        ErrorBoundary={LexicalErrorBoundary}
                    />
                    <HistoryPlugin />
                    <AutoFocusPlugin />
                    <CodeHighlightPlugin />
                    <ListPlugin />
                    <LinkPlugin />
                    <AutoLinkPlugin />
                    <ListMaxIndentLevelPlugin maxDepth={7} />
                    <MarkdownShortcutPlugin transformers={TRANSFORMERS} />
                </div>
            </div>
        </LexicalComposer>
    );
}

```
EditorTheme.tsx
```
export const EditorTheme = {
    ltr: "ltr",
    rtl: "rtl",
    placeholder: "editor-placeholder",
    paragraph: "editor-paragraph",
    quote: "editor-quote",
    heading: {
        h1: "editor-heading-h1",
        h2: "editor-heading-h2",
        h3: "editor-heading-h3",
        h4: "editor-heading-h4",
        h5: "editor-heading-h5"
    },
    list: {
        nested: {
            listitem: "editor-nested-listitem"
        },
        ol: "editor-list-ol",
        ul: "editor-list-ul",
        listitem: "editor-listitem"
    },
    image: "editor-image",
    link: "editor-link",
    text: {
        bold: "editor-text-bold",
        italic: "editor-text-italic",
        overflowed: "editor-text-overflowed",
        hashtag: "editor-text-hashtag",
        underline: "editor-text-underline",
        strikethrough: "editor-text-strikethrough",
        underlineStrikethrough: "editor-text-underlineStrikethrough",
        code: "editor-text-code"
    },
    code: "editor-code",
    codeHighlight: {
        atrule: "editor-tokenAttr",
        attr: "editor-tokenAttr",
        boolean: "editor-tokenProperty",
        builtin: "editor-tokenSelector",
        cdata: "editor-tokenComment",
        char: "editor-tokenSelector",
        class: "editor-tokenFunction",
        "class-name": "editor-tokenFunction",
        comment: "editor-tokenComment",
        constant: "editor-tokenProperty",
        deleted: "editor-tokenProperty",
        doctype: "editor-tokenComment",
        entity: "editor-tokenOperator",
        function: "editor-tokenFunction",
        important: "editor-tokenVariable",
        inserted: "editor-tokenSelector",
        keyword: "editor-tokenAttr",
        namespace: "editor-tokenVariable",
        number: "editor-tokenProperty",
        operator: "editor-tokenOperator",
        prolog: "editor-tokenComment",
        property: "editor-tokenProperty",
        punctuation: "editor-tokenPunctuation",
        regex: "editor-tokenVariable",
        selector: "editor-tokenSelector",
        string: "editor-tokenSelector",
        symbol: "editor-tokenProperty",
        tag: "editor-tokenProperty",
        url: "editor-tokenOperator",
        variable: "editor-tokenVariable"
    }
};
```

**Comment by trueadm** [comment]
If you go to the `ToolbarPlugin`. If you lookup each `<button>` and where there is an `onClick`, make sure inside you're doing `event.preventDefault()`. Let me know if that helps. It might be how you've embedded Lexical in your form. If you still are struggling, you'll need to put together a Codesandbox so I can properly look at your code :)

**Comment by Birddle** [comment]
> If you go to the `ToolbarPlugin`. If you lookup each `<button>` and where there is an `onClick`, make sure inside you're doing `event.preventDefault()`. Let me know if that helps. It might be how you've embedded Lexical in your form. If you still are struggling, you'll need to put together a Codesandbox so I can properly look at your code :)

It's working now and there are no errors. I will update the CodeSandbox link later to be able to help you with any possibilities for your development. Thank you very much for your help. I sincerely hope that lexical will be the next great library after react!

**Comment by Birddle** [comment]
> If you go to the `ToolbarPlugin`. If you lookup each `<button>` and where there is an `onClick`, make sure inside you're doing `event.preventDefault()`. Let me know if that helps. It might be how you've embedded Lexical in your form. If you still are struggling, you'll need to put together a Codesandbox so I can properly look at your code :)

https://codesandbox.io/s/heuristic-wildflower-b1l39f?file=/src/App.tsx
I reverted my code as much as I could (I've added preventDefault to each button as you suggested), but the SVG doesn't display.
