### ISSUE TITLE
Bug: invalid state - list items wrapped in paragraph nodes instead of list

### ISSUE THREAD

**Issue by DaniGuardiola** [facebook/lexical#3701]
Lexical version: 0.7.5 (I think? I used the playground just now)

## Steps To Reproduce

1. Replicate what happens in the video below.

https://user-images.githubusercontent.com/8862967/211608329-c38f45cd-949f-46b5-bf33-203c45f39fb3.mp4

## The current behavior

List items are wrapped in paragraph blocks.

## The expected behavior

List items are *converted* into paragraph blocks individually.

## Insight / solution proposal

AFAIK, this bug is related to `$setBlocksType_experimental` and/or list normalization. Not sure what the correct way to handle this would be, but it makes sense that this happens because `$setBlocksType` does exactly that: turn the top level blocks contained in the selection into a different block type (the old `$wrapNodes`). After that happens, I'm guessing the list normalization should be responsible for turning each list item into a separate paragraph and flattening the parent paragraph. But I don't really know.

**Comment by thegreatercurve** [comment]
@EgonBolton as the author of the above method, would you have any thoughts on how this should be implemented?

**Comment by EgonBolton** [comment]
Oh I hadn't noticed this thread and I duplicated it last week! https://github.com/facebook/lexical/issues/3776

Yes, I already tried some things and I have an idea to solve it. If you want, assign it to me and I'll try to do it soon. @thegreatercurve
