### ISSUE TITLE
Feature: ContentEditable should accept a ref

### ISSUE THREAD

**Issue by DaniGuardiola** [facebook/lexical#3703]
Our use case is giving an editor in a dialog initial focus when the dialog is opened.

A `ref` prop should be accepted here: https://github.dev/facebook/lexical/blob/168f0d43fcbd3d4d3129aff2e57eb9cfab0ba8e4/packages/lexical-react/src/LexicalContentEditable.tsx#L14-L36

**Comment by trueadm** [comment]
Feel free to add it in a PR?

**Comment by DaniGuardiola** [comment]
@trueadm will do, can you assign me to the issue?

**Comment by thegreatercurve** [comment]
@DaniGuardiola I'm not sure we need to forward the ref to this component or necessarily should. We already use a ref within `LexicalContentEditable` to set it as the root element for the editor instance (i.e. where it should inject any DOM updates).

If you need to autofocus an editor, you can [add the `AutoFocusPlugin` to that editor](https://github.com/facebook/lexical/blob/main/packages/lexical-react/src/LexicalAutoFocusPlugin.ts#L26-L34).

**Comment by thegreatercurve** [comment]
@DaniGuardiola We can merge the refs, but I still think we already expose most of the potential use cases through the `editor` instance, which we should probably encourage users to use over refs. 

For example. to imperatively focus/blur the editor, you can call `editor.focus()` or `editor.blur()`. That logic comes with [some cross browser bug fixes, and some logic for focusing to the end of of a contenteditable with pre-populated content](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalEditor.ts#L836-L888).

**Comment by DaniGuardiola** [comment]
@thegreatercurve good point... I guess something that bugs me with that approach is that accessing the editor instance is not very ergonomic since if you're abstracting lexical into a component, you either need to:

- split it into the context provider and the plugins/other stuff inside (which in turn means you have to split your app components so that you can consume the context which a bunch of prop drilling), or
- assign to a ref so that the parent can access it (which also means no accessing it during render - probably a good thing, and a nullable type that you have to check or optionally chain - `editorRef.current?.focus`)

That's a different topic though, around ergonomics of the context etc etc. In conclusion, gotcha :P

**Comment by duc-gp** [comment]
> @DaniGuardiola We can merge the refs, but I still think we already expose most of the potential use cases through the `editor` instance, which we should probably encourage users to use over refs.
> 
> For example, to imperatively focus/blur the editor, you can call `editor.focus()` or `editor.blur()`. That logic comes with [some cross browser bug fixes, and some logic for focusing to the end of of a contenteditable with pre-populated content](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalEditor.ts#L836-L888).

`editor.focus()` is only available within the `LexicalComposer` right?

how would you focus the editor when the button to click on to focus it is outside of the `LexicalComposer` ?

**Comment by RiceCrisp** [comment]
Is there a better solution? This prevents tab from being able to tab past the input.

**Comment by saconni** [comment]
We ran into a similar problem, and we came up with this hack.

```
export const RefPlugin = forwardRef<HTMLElement>((props, ref) => {
  const [editor] = useLexicalComposerContext();

  useEffect(() => {
    editor.registerRootListener((root, _prevRoot) => {
      if (!ref) return;
      if (typeof ref === 'function') {
        ref(root);
      } else {
        throw new Error('non-callback ref not supported');
      }
    });
  }, [editor]);

  return null;
});
```

```
const ref = useCallback((element: null | HTMLElement) => {
  console.log('Yeah!', element);
}, []);

return (
  <LexicalComposer initialConfig={initialConfig}>
    <RichTextPlugin
      contentEditable={contentEditable}
      ErrorBoundary={LexicalErrorBoundary}
      placeholder={null}
    />
    <RefPlugin ref={ref} />
  </LexicalComposer>
);
```

Not likely to be a good solution... just a hack to be used at your own peril.

Note: Not sure what will happen if the root element ever changes in the editor and the ref callback is called a second time
