### ISSUE TITLE
Bug: deleting a block decorator node (divider) causes loss of selection

### ISSUE THREAD

**Issue by DaniGuardiola** [facebook/lexical#3707]
Lexical version: 0.7.6

## Steps To Reproduce

1. Replicate the steps in the video below.

https://user-images.githubusercontent.com/8862967/211872809-710dac40-28d9-4b64-8204-fba40ae97078.mp4

## The current behavior

After deleting, the selection is lost.

## The expected behavior

After deleting, there is still a selection where it makes sense.

**Comment by gaurav21r** [comment]
@DaniGuardiola A lil off topic, but could you tell me the screen shot app you used to generate the keystrokes? I have a reproducible bug for Lexical which I couldn't explain but I think this tool will make this clear in the issues!

**Comment by DaniGuardiola** [comment]
@gaurav21r it's screenkey: https://www.thregr.org/~wavexx/software/screenkey/

**Comment by gaurav21r** [comment]
@DaniGuardiola Thank you so much ❤️ I think it is Linux only?

**Comment by etrepum** [comment]
Can't reproduce with current lexical
