### ISSUE TITLE
Bug: `DecoratorBlockNode.isInline` should return `false`

### ISSUE THREAD

**Issue by DaniGuardiola** [facebook/lexical#3708]
Lexical version: 0.7.6

It is my understanding that this class is a base for *block* nodes, so `isInline()` should return `false`. Currently it returns `true` as inherited by its superclass. Link to code: https://github.dev/facebook/lexical/blob/168f0d43fcbd3d4d3129aff2e57eb9cfab0ba8e4/packages/lexical-react/src/LexicalDecoratorBlockNode.ts#L26

**Comment by moy2010** [comment]
It is not a base for block nodes.

**Comment by DaniGuardiola** [comment]
@moy2010 care to elaborate? What is it for then? I might be misusing them :stuck_out_tongue:

**Comment by moy2010** [comment]
Decorator nodes are a special type of nodes. Check the documentation on
nodes.

**Comment by DaniGuardiola** [comment]
@moy2010 this issue refers to decorator **block** nodes, not just decorator nodes. It directly implies it's supposed to be a block, has formatting (alignment) logic, and renders as a `<div>` (block element). I think you might have missed the "block" part :)

**Comment by moy2010** [comment]
Nope. Check the codebase, these are only used for nodes such as YoutubeNode
and company.

**Comment by DaniGuardiola** [comment]
@moy2010 :facepalm: YoutubeNode is a **block**. Literally [all](https://github.dev/facebook/lexical/blob/168f0d43fcbd3d4d3129aff2e57eb9cfab0ba8e4/packages/lexical-playground/src/nodes/FigmaNode.tsx#L129) [usages](https://github.dev/facebook/lexical/blob/168f0d43fcbd3d4d3129aff2e57eb9cfab0ba8e4/packages/lexical-playground/src/nodes/TweetNode.tsx#L217) [in the codebase](https://github.dev/facebook/lexical/blob/168f0d43fcbd3d4d3129aff2e57eb9cfab0ba8e4/packages/lexical-playground/src/nodes/YouTubeNode.tsx#L131) are blocks, they all return `false` from `isInline`.

You're missing the point. But I digress.

**Comment by moy2010** [comment]
Sorry, you're right. I thought that `DecoratorBlockNode` was `DecoratorNode`, but I realized that it's actually extending it.

The fix is super easy, just override the method.

**Comment by DaniGuardiola** [comment]
@moy2010 yeah, that's what I'm doing now, but it caused a few bugs for a while because I had assumed that was already the case in the super class. So that's why I filed this bug report.

I'd be happy to contribute the fix btw, as soon as I get confirmation that it it actually wanted.

**Comment by trueadm** [comment]
The default is inline for decorators – which is how we mostly use them internally. I don't think changing it (a major breaking change) is really needed? I'm closing for now, as I'm not sure there's actually an issue reported here? Maybe open a discussion top if you want to talk more about this :)

**Comment by DaniGuardiola** [comment]
@trueadm I understand, but this issue is about `DecoratorBlockNode` (not `DecoratorNode`!). All examples in the codebase are blocks:

- https://github.dev/facebook/lexical/blob/168f0d43fcbd3d4d3129aff2e57eb9cfab0ba8e4/packages/lexical-playground/src/nodes/FigmaNode.tsx#L129
- https://github.dev/facebook/lexical/blob/168f0d43fcbd3d4d3129aff2e57eb9cfab0ba8e4/packages/lexical-playground/src/nodes/TweetNode.tsx#L217
- https://github.dev/facebook/lexical/blob/168f0d43fcbd3d4d3129aff2e57eb9cfab0ba8e4/packages/lexical-playground/src/nodes/YouTubeNode.tsx#L131

In all these instances, you're having to manually return `false` from `isInline()`. In my case, it caused bugs because we assumed Decorator *Block* Node was already a *block*, which I think is reasonable and something that is likely to happen to other users :P

So I would consider this a proper issue that needs fixing unless I'm missing something :)
