### ISSUE TITLE
Bug: Ctrl + Del remove table cell nodes

### ISSUE THREAD

**Issue by bilobom** [facebook/lexical#3710]
If yout hit CTRL+ DEL before table , table cells will be deleted one by one

![image](https://user-images.githubusercontent.com/19841175/211948302-b72ffa5a-4ff5-4ba6-b021-636a2af3ba4e.png)

Lexical version: latest on playground

## Steps To Reproduce

1.create a table 
2.hit Ctrl+Del before the table at the cursor shown in this image

**Comment by thegreatercurve** [comment]
@bilobom What version of Lexical are you using? What OS and browser as well?

**Comment by tylerjbainbridge** [comment]
I believe I fixed this a few months ago and can't repro on the current version. Feel free to re-open if it still happens on the latest version:)
