### ISSUE TITLE
Bug: Can't build for production use Vite/rollup with react plugin @lexical/react

### ISSUE THREAD

**Issue by ccoombsesmail** [facebook/lexical#3711]
"@lexical/react": "^0.7.5",
"lexical": "^0.7.5",

When running in dev mode with Vite, everything works fine. 

when building for production with Vite, it gives this error

 ERROR  [commonjs--resolver] Failed to resolve entry for package "@lexical/react". The package may have incorrect main/module/exports specified in its package.json.                   

file:///home/ccoombsesmail/deployments/deployments2/civil_frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:34107
    throw new Error(`Failed to resolve entry for package "${id}". ` +
          ^

Error: Failed to resolve entry for package "@lexical/react". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///home/ccoombsesmail/deployments/deployments2/civil_frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:34107:11)
    at resolvePackageEntry (file:///home/ccoombsesmail/deployments/deployments2/civil_frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:34104:5)
    at tryNodeResolve (file:///home/ccoombsesmail/deployments/deployments2/civil_frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:33842:20)
    at Object.resolveId (file:///home/ccoombsesmail/deployments/deployments2/civil_frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:33602:28)
    at file:///home/ccoombsesmail/deployments/deployments2/civil_frontend/node_modules/rollup/dist/es/shared/rollup.js:22748:40 {
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs--resolver',
  hook: 'resolveId'
}                     

It seems @lexical/react does not have a lib/dist with an export/main entry point in package.json like other packages?

**Comment by thegreatercurve** [comment]
You need to import any dependencies from `@lexical/react` as `import {PlainTextPlugin} from '@lexical/react/LexicalPlainTextPlugin';`. Wed don't expose all of the modules through a shared `index.js` dist file as it's harder to tree-shake.

**Comment by Xuhv** [comment]
I encountered the same problem. Using rollup's config option `manualChunks` to package @lexica/react leads to this.

**Comment by amitrahav** [comment]
@Xuhv Found a way of using @lexica/react and setting the `manualChunks` option?

**Comment by Xuhv** [comment]
@amitrahav List all plugin used and it should work.

```js
{
    manualChunks: {
        "lexical": [
            "lexical", 
            "@lexical/react/LexicalComposer", 
            // ....
            "@lexical/react/LexicalErrorBoundary"
        ],
    }
}
```

**Comment by RabbitPL** [comment]
> [@amitrahav](https://github.com/amitrahav) List all plugin used and it should work.
> 
> {
>     manualChunks: {
>         "lexical": [
>             "lexical", 
>             "@lexical/react/LexicalComposer", 
>             // ....
>             "@lexical/react/LexicalErrorBoundary"
>         ],
>     }
> }

Had the same issue — your solution totally worked. Really appreciate it!
