### ISSUE TITLE
Bug: Grammarly replacements across more than one node causes unexpected node deletion.

### ISSUE THREAD

**Issue by scvet-ct** [facebook/lexical#3713]
When Grammarly is used to fix a Grammar mistake that spans more than one node (e.g. a node with colored text and an unmodified text node), the replacement text also replaces the node preceding the first node that is being changed. We noticed this in our colored nodes (which are custom-built nodes that change colour when specific keywords are typed) but it also happens in the lexical playground (see image examples below) on links or any instance where the Grammarly correction spans multiple nodes. With longer paragraphs, this can result in a lot of text being deleted.

I am using the Grammarly Chrome Extension.

Lexical version: We are still using 0.6.4 for now, but this also happens on the playground, so it is in the latest version too.

## Steps To Reproduce

1. Write some text including something like 'left hand' which Grammarly will pick up as a Grammatical error
2. Change the text on Grammarly's suggestion using the Grammarly interface (not manually)

## The current behavior

On the playground:

<img width="629" alt="Screenshot 2023-01-12 at 12 06 50" src="https://user-images.githubusercontent.com/114913876/212065736-2b338728-5cfd-471b-8ae4-9f6bdb0aeaec.png">
<img width="658" alt="Screenshot 2023-01-12 at 12 07 22" src="https://user-images.githubusercontent.com/114913876/212065750-2701f7b0-6788-4605-95af-03d28ec686b8.png">
<img width="674" alt="Screenshot 2023-01-12 at 12 22 29" src="https://user-images.githubusercontent.com/114913876/212065799-3ad0ed77-8a30-4f37-b03b-83a2a910228f.png">

In our application:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/114913876/212067351-b6693571-0e63-4869-a0a6-be67f633ca5e.png">
<img width="652" alt="image" src="https://user-images.githubusercontent.com/114913876/212067449-c4bf130a-d7e6-44c0-8641-34d2f32c3bdc.png">

## The expected behavior

<img width="692" alt="Screenshot 2023-01-12 at 12 16 46" src="https://user-images.githubusercontent.com/114913876/212067014-fc5594f9-1bc7-4305-98cb-b20cf65f167b.png">

Or something like this:

<img width="431" alt="Screenshot 2023-01-12 at 12 17 49" src="https://user-images.githubusercontent.com/114913876/212067021-db43c988-d9da-4914-aafc-25b432cf45ba.png">

**Comment by trueadm** [comment]
This is something Grammarly need to fix. They're not dispatching a `beforeinput` event for Lexical, meaning we have no way to know what they're actually doing. They seem to be using `document.exectCommand` which is really problematic for Lexical as it will directly mutate the DOM before firing an `input` event – by which time it is already too late and Lexical will have reverted their DOM mutation as it doesn't match the EditorState.

**Comment by strdr4605** [comment]
Hey @trueadm @thegreatercurve, I investigated this for some time and don't understand how 
> dispatching a `beforeinput` event for Lexical

will fix this issue in the condition statement

https://github.com/facebook/lexical/blob/81e9bf404f5ccba084867b3e3b20e0b4bd5ce53f/packages/lexical/src/LexicalEvents.ts#L185-L226

Maybe we can reach out to Grammarly so they can fix this from their side?!
