### ISSUE TITLE
Bug: Layout shifts while using typeahead menu

### ISSUE THREAD

**Issue by harish-sethuraman** [facebook/lexical#3716]
While the page is longer than just the viewport height with the typeahead menu open, while navigating through keyboard, on reaching the last value and pressing bottom button again shifts the page. I don't think this is expected? 

Lexical version:

## Steps To Reproduce

1. Go to https://playground.lexical.dev/ 
2. Copy and paste content so that content is more than one page long
3. try `:a`
4. navigate using keyboard until last option and while at last option click the down button again. 

## The current behavior
While first element comes to focus through keyboard from the last element screen shifts.

https://user-images.githubusercontent.com/32865581/212252950-0cf61fc1-2728-4a6c-a9fc-cb99f16953b6.mov

## The expected behavior
This should'nt happen

**Comment by blacktoast** [comment]
I want to solve this issue, is it okay?

 and I'm new to the project so If I get any additional details like codes focus on or  document recommened would be helpful

**Comment by thegreatercurve** [comment]
Feel free to take a look @blacktoast. We've not got any docs for this, but all of the logic for this typeahead is in `/packages/lexical-react/src/LexicalTypeaheadMenuPlugin.tsx`.

**Comment by blacktoast** [comment]
Thank you
