### ISSUE TITLE
Bug: Copy/Cut from input field within DecoratorNode component (for example PollComponent)

### ISSUE THREAD

**Issue by PSmolic** [facebook/lexical#3717]
Lexical version: v0.7.6

## Steps To Reproduce

1. Add Poll to the sandbox and add some text to option fields
2. Try to copy/cut from the option field

https://user-images.githubusercontent.com/4542049/212292551-6dac68b4-05d9-4151-b3e1-f4fb5bac734f.mov

## The current behavior
On Copy/Cut from the Poll text field error gets thrown:
```
main.22f383cc.js:21 Uncaught Error: Expected valid LexicalSelection
    at ev (main.22f383cc.js:21:247217)
    at av (main.22f383cc.js:21:250901)
    at main.22f383cc.js:21:252025
    at Vf (main.22f383cc.js:21:179169)
    at Hf (main.22f383cc.js:21:179802)
    at Wf (main.22f383cc.js:21:182038)
    at Tm.update (main.22f383cc.js:21:209325)
    at qf (main.22f383cc.js:21:178724)
    at HTMLDivElement.o (main.22f383cc.js:21:208073)
```

## The expected behavior
Text gets copied/cut to the clipboard.

**Comment by DaniGuardiola** [comment]
In general, having text inputs (possibly other types too) in decorator nodes is very buggy in my experience. Seems like even though they are inside a `contenteditable="false"` context, Lexical gets confused by the events and selection inside of them. I've partially gotten around some of the issues by stopping the propagation of some of the events (e.g. `keydown`), but there are still many issues.
