### ISSUE TITLE
What is `config.namespace`? It's required, but undocumented! 

### ISSUE THREAD

**Issue by michal-kurz** [facebook/lexical#3723]
I just upgraded Lexical from an archaic version to `0.7.6`, and I now get en error with my existing code: 

``` tsx
 <LexicalComposer initialConfig={{ onError: console.log, nodes: [SsmlTagNode] }}>
```
> Property 'namespace' is missing in type `InitialConfigType`

The problem is, this `namespace` property seems to be completely undocumented, or at least the documentation is very hard to find. Search in docs/issues/source code/Google yeilded nothing, except for documentation merely stating that it exists, but no information about what it does. 

So my question is: what does it do exactly? The prop name gives some hint, but it's hard to guess the implications. In my app, I'm dynamically rendering dozens of Lexical instances (my text inputs use Lexical internally). Should I generate an unique id on mount of each editor just for the purpose of assigning it to `namespace`, or is it something more abstract and OK to share across all instances of the same kind of editor?

Thank you 🙏

**Comment by trueadm** [comment]
It's a name for the type of instance your applying. If you have many instances, they should all have the same namespace as they're of the same type. If an editor has all the same plugins and nodes, it can be of the same namespace.

**Comment by gaurav21r** [comment]
@trueadm Maybe this issue should be closed after documenting this?

**Comment by trueadm** [comment]
@gaurav21r I'm limited on bandwidth right now, but if you have some time and would like to contribute to Lexical – maybe you'd like to create a PR? Thank you :)
