### ISSUE TITLE
Bug: Floating toolbar flashes on hover over empty lines when the selection is backwards.

### ISSUE THREAD

**Issue by EgonBolton** [facebook/lexical#3727]
Lexical version: 0.7.6

## Steps To Reproduce

1. Go to the [playground](https://playground.lexical.dev/)
2. Inserts one or more blank lines in the middle of the editor.
3. Start the selection after the empty lines and move the cursor up to the empty lines, hovering over the floating toolbar.

## The current behavior
Floating toolbar start blinking rapidly.

## The expected behavior
Floating toolbar shouldn't blink.

**Comment by AlessioGr** [comment]
https://user-images.githubusercontent.com/70709113/220928584-1808c5d8-86c8-4bf1-b0bf-2b9a86774702.mp4

Pretty annoying! Also wanted to add a video showcase of the bug
