### ISSUE TITLE
Bug: Excalidraw Modal auto closes on ANY keypress because of this Code

### ISSUE THREAD

**Issue by gaurav21r** [facebook/lexical#3728]
Integrating the Excalidraw Plugin & Node from the playground package into a custom Instance of Lexical, makes the Excalidraw Modal auto close when ANY `keypress` is emitted, including Excalidraw's own text tool!

Lexical version: Latest

## Steps To Reproduce

1. Used the code template given in the home page of Lexical in CodeSandbox.
2. Integrated Excalidraw Plugin from the Playground package
3. On press of any key, the Excalidraw modal gets closed and the element gets erased from the Editor.

Since my Editor is part of a package with proprietary Code I am unable to share a CodeSandbox, but if someone can give me a hint as to why this piece of code is failing, I'll be able to submit a PR if this issue is happening in environments outside the playground.

Commenting this line resolves the issue. I don't understand why we have to delete the entire `Excalidraw` element on a `keypress`? 

https://github.com/facebook/lexical/blob/eb573a0da6c1a7564dd422f809caa11d46bcfc87/packages/lexical-playground/src/nodes/ExcalidrawNode/ExcalidrawModal.tsx#L103

This code basically says, if the `ref` for the modal exists, and ANY `keypress` happens, delete the entire element! WHY??

**Comment by gaurav21r** [comment]
Thanks @thegreatercurve ! Although, would've been great it if you had marked it as a `good first issue`. Would've loved my contribution to `lexical` with this PR 🙈 Next opportunity then!

**Comment by thegreatercurve** [comment]
@gaurav21r I'm not sure exactly what permissions you have when creating a new Issue, but if you can, feel free to add the label yourself, or assign yourself the issue. We always welcome fire time contributors!

**Comment by gaurav21r** [comment]
Thanks @thegreatercurve ! I tried all that you've mentioned, sadly all options were frozen for me :( I don't know if this is a permission issue for the repo or something in my end!
