### ISSUE TITLE
How to get the paragraph "text-align" property of a selection?

### ISSUE THREAD

**Issue by nickschinestzki** [facebook/lexical#3739]
I have a text alignment dropdown on which I want to show the user what is the text alignment of the text nodes on the current selection. I tried to get the "text-align" property using the `$getSelectionStyleValueForProperty` method, but it only returns me the default value. 

```
const updateToolbar = useCallback(() => {
    const selection = $getSelection();

   // I expected this to return ("left" || "center" || "right")    
   const align = $getSelectionStyleValueForProperty(selection, "text-align", "left")

}, [editor])
```

Is it possible to get that value using selection? And what happens if I select 2 paragraphs with different text-align values?

**Comment by thegreatercurve** [comment]
We don't store the alignment in the CSS, it's directly on the nodes themselves. For each paragraph node you can use `getFormatType` to work out which way its aligned. This will unique for different paragraphs with different alignments.
```
      const anchor = selection.anchor;
      const anchorNode = anchor.getNode();
      const alignment = anchorNode.getFormatType();
```

**Comment by nickschinestzki** [comment]
This method gives me an error: `anchorNode.getFormatType() is not a function`

**Comment by Inkluter** [comment]
> We don't store the alignment in the CSS, it's directly on the nodes themselves. For each paragraph node you can use `getFormatType` to work out which way its aligned. This will unique for different paragraphs with different alignments.
> 
> ```
>       const anchor = selection.anchor;
>       const anchorNode = anchor.getNode();
>       const alignment = anchorNode.getFormatType();
> ```

Could you please provide working example? Trying to use your code in `updateToolbar` and it is not working. Result is always `undefined`.

```
const updateToolbar = useCallback(() => {
    const selection = $getSelection();

    if ($isRangeSelection(selection)) {
      const anchor = selection.anchor;
      const anchorNode = anchor.getNode();
      const alignment = anchorNode.getFormatType && anchorNode.getFormatType();
      console.log(alignment);
    }
  }, [editor]);
```
