### ISSUE TITLE
Bug: node.select() method inside an editor.update trigger an additional update. 

### ISSUE THREAD

**Issue by EgonBolton** [facebook/lexical#3744]
Lexical version: 0.6.4

## Steps To Reproduce

1. Run some ElementNode.select() method inside an editor.update()
2. Listen to changes in an update listener.

Link to code example: https://codesandbox.io/s/fast-forest-bm0fvw?file=/src/plugins/BugPlugin.js

## The current behavior
Every time you press the button it triggers two console logs.

## The expected behavior
Should trigger only one.

**Comment by trueadm** [comment]
This might be because the browser is changing the selection to a different location?

**Comment by EgonBolton** [comment]
So this is the expected behavior?
I would have expected that the selection could be changed as part of a single update.

**Comment by trueadm** [comment]
When Lexical changes DOM selection, you get a X update from that. However, sometimes the browser doesn’t agree, and moves it to where it wants it. These can cause another update in some cases. If you look at the editor state between updates, are there any differences in the selection between the two?

**Comment by EgonBolton** [comment]
Yes, [there are](https://codesandbox.io/s/fast-forest-bm0fvw?file=/src/plugins/BugPlugin.js:652-664).

**Comment by trueadm** [comment]
Okay. So the reason here is because of normalization. If there exists text at the same position as element selection and you have text there it will always go to it. To avoid this, select the next node rather than the paragraph node. You can do paragraph.selectEnd()

**Comment by EgonBolton** [comment]
Cool! Thank you very much, this thread can be closed :D
