### ISSUE TITLE
Feature:   parsing html for the original state and returning html 

### ISSUE THREAD

**Issue by thegirlyoucallryan** [facebook/lexical#3755]

**Comment by thegreatercurve** [comment]
@thegirlyoucallryan Hey! Can you give a bit more detail about what you mean here?

**Comment by thegirlyoucallryan** [comment]
Yes, I'd really appreciate some guidance!!  I found more last night, but I am stuck on something... so I am using vite / so React.  There is a text block on the page that is HTML that when edit is clicked the code editor opens.(obviously)  I need it to parse the html to prepopulate the editor for editing.  I cant figure out how to pass in the editor.   sorry its messy, Kind of a Junior...


Here is my code thus far: 


import ExampleTheme from './ExampleTheme'
import { LexicalComposer } from '@lexical/react/LexicalComposer'
import { RichTextPlugin } from '@lexical/react/LexicalRichTextPlugin'
import { ContentEditable } from '@lexical/react/LexicalContentEditable'
import { HistoryPlugin } from '@lexical/react/LexicalHistoryPlugin'
import { AutoFocusPlugin } from '@lexical/react/LexicalAutoFocusPlugin'
import LexicalErrorBoundary from '@lexical/react/LexicalErrorBoundary'
// import TreeViewPlugin from './plugins/TreeViewPlugin'
import ToolbarPlugin from './ToolbarPlugin'
import { HeadingNode, QuoteNode } from '@lexical/rich-text'
import { TableCellNode, TableNode, TableRowNode } from '@lexical/table'
import { ListItemNode, ListNode } from '@lexical/list'
import { CodeHighlightNode, CodeNode } from '@lexical/code'
import { AutoLinkNode, LinkNode } from '@lexical/link'
import { LinkPlugin } from '@lexical/react/LexicalLinkPlugin'
import { ListPlugin } from '@lexical/react/LexicalListPlugin'
import { MarkdownShortcutPlugin } from '@lexical/react/LexicalMarkdownShortcutPlugin'
import { OnChangePlugin } from '@lexical/react/LexicalOnChangePlugin'
import { TRANSFORMERS } from '@lexical/markdown'
import './styles.css'
// import ListMaxIndentLevelPlugin from './plugins/ListMaxIndentLevelPlugin'
// import CodeHighlightPlugin from './plugins/CodeHighlightPlugin'
import AutoLinkPlugin from './AutoLinkPlugin'
import { $createLinkNode } from '@lexical/link'

import { $createListItemNode, $createListNode } from '@lexical/list'
import { $generateHtmlFromNodes } from '@lexical/html'
import { $createHeadingNode, $createQuoteNode } from '@lexical/rich-text'
import { useState } from 'react'
import {
  $createParagraphNode,
  $createTextNode,
  $getRoot,
  $isElementNode,
  DOMChildConversion,
  DOMConversion,
  DOMConversionFn,
  LexicalEditor,
  LexicalNode,
} from 'lexical'
import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext'

function Placeholder({ placeholder }: { placeholder: string }) {
  return (
    <div
      className="editor-placeholder"
      // dangerouslySetInnerHTML={{ __html: placeholder }}
    >
      ...enter text
    </div>
  )
}

export function $generateNodesFromDOM(
  editor: LexicalEditor,
  dom: Document,
): Array<LexicalNode> {
  let lexicalNodes: Array<LexicalNode> = []
  const elements: Array<Node> = dom.body ? Array.from(dom.body.childNodes) : []
  const elementsLength = elements.length

  for (let i = 0; i < elementsLength; i++) {
    const element = elements[i]

    if (!IGNORE_TAGS.has(element.nodeName)) {
      const lexicalNode = $createNodesFromDOM(element, editor)

      if (lexicalNode !== null) {
        lexicalNodes = lexicalNodes.concat(lexicalNode)
      }
    }
  }

  return lexicalNodes
}
const IGNORE_TAGS = new Set(['STYLE'])

function getConversionFunction(
  domNode: Node,
  editor: LexicalEditor,
): DOMConversionFn | null {
  const { nodeName } = domNode

  const cachedConversions = editor._htmlConversions.get(nodeName.toLowerCase())

  let currentConversion: DOMConversion | null = null

  if (cachedConversions !== undefined) {
    for (const cachedConversion of cachedConversions) {
      const domConversion = cachedConversion(domNode)

      if (
        domConversion !== null &&
        (currentConversion === null ||
          currentConversion.priority < domConversion.priority)
      ) {
        currentConversion = domConversion
      }
    }
  }

  return currentConversion !== null ? currentConversion.conversion : null
}

function $createNodesFromDOM(
  node: Node,
  editor: LexicalEditor,
  forChildMap: Map<string, DOMChildConversion> = new Map(),
  parentLexicalNode?: LexicalNode | null | undefined,
): Array<LexicalNode> {
  let lexicalNodes: Array<LexicalNode> = []

  if (IGNORE_TAGS.has(node.nodeName)) {
    return lexicalNodes
  }

  let currentLexicalNode = null
  const transformFunction = getConversionFunction(node, editor)
  const transformOutput = transformFunction
    ? transformFunction(node as HTMLElement)
    : null
  let postTransform = null

  if (transformOutput !== null) {
    postTransform = transformOutput.after
    currentLexicalNode = transformOutput.node

    if (currentLexicalNode !== null) {
      for (const [, forChildFunction] of forChildMap) {
        currentLexicalNode = forChildFunction(
          currentLexicalNode,
          parentLexicalNode,
        )

        if (!currentLexicalNode) {
          break
        }
      }

      if (currentLexicalNode) {
        lexicalNodes.push(currentLexicalNode)
      }
    }

    if (transformOutput.forChild != null) {
      forChildMap.set(node.nodeName, transformOutput.forChild)
    }
  }

  // If the DOM node doesn't have a transformer, we don't know what
  // to do with it but we still need to process any childNodes.
  const children = node.childNodes
  let childLexicalNodes = []

  for (let i = 0; i < children.length; i++) {
    childLexicalNodes.push(
      ...$createNodesFromDOM(
        children[i],
        editor,
        new Map(forChildMap),
        currentLexicalNode,
      ),
    )
  }

  if (postTransform != null) {
    childLexicalNodes = postTransform(childLexicalNodes)
  }

  if (currentLexicalNode == null) {
    // If it hasn't been converted to a LexicalNode, we hoist its children
    // up to the same level as it.
    lexicalNodes = lexicalNodes.concat(childLexicalNodes)
  } else {
    if ($isElementNode(currentLexicalNode)) {
      // If the current node is a ElementNode after conversion,
      // we can append all the children to it.
      currentLexicalNode.append(...childLexicalNodes)
    }
  }

  return lexicalNodes
}

export function Editor({ placeholder }: { placeholder: string }) {
  const parse = new DOMParser()
  const text = parse.parseFromString(placeholder, 'text/html')
  console.log(text, 'texxet')

  function prepopulatedRichText() {
    const root = $getRoot()
    if (root.getFirstChild() === null) {
      const paragraph = $createParagraphNode()
      paragraph.append($createTextNode($generateNodesFromDOM(, text)))
      root.append(paragraph)
    }
  }
  const editorConfig = {
    // The editor theme
    nameSpace: 'RichTextEditor',
    theme: ExampleTheme,
    editorState: prepopulatedRichText,
    // Handling of errors during update
    onError(error: any) {
      throw error
    },
    // Any custom nodes go here
    nodes: [
      HeadingNode,
      ListNode,
      ListItemNode,
      QuoteNode,
      CodeNode,
      CodeHighlightNode,
      TableNode,
      TableCellNode,
      TableRowNode,
      AutoLinkNode,
      LinkNode,
    ],
  }

  return (
    <div className="App">
      <LexicalComposer initialConfig={editorConfig}>
        <div className="editor-container">
          <ToolbarPlugin />
          <div className="editor-inner">
            <RichTextPlugin
              contentEditable={<ContentEditable className="editor-input" />}
              placeholder={<Placeholder placeholder={text.body} />}
              ErrorBoundary={LexicalErrorBoundary}
            />
            <HistoryPlugin />
            <AutoFocusPlugin />
            <AutoLinkPlugin />
            <ListPlugin />
            <LinkPlugin />
            <OnChangePlugin onChange={(state) => console.log(state)} />
          </div>
        </div>
      </LexicalComposer>
    </div>
  )
}

**Comment by sakib412** [comment]
> Yes, I'd really appreciate some guidance!! I found more last night, but I am stuck on something... so I am using vite / so React. There is a text block on the page that is HTML that when edit is clicked the code editor opens.(obviously) I need it to parse the html to prepopulate the editor for editing. I cant figure out how to connect the html to the editor, i either don't have an instance of editor or If I try to create a plugin like such what would I return from it?. sorry its messy, Kind of a Junior... I have to use the DomParse because I cannot require, Thats what happened with the first RTE, Vite wouldn't bundle it right.
> 
> Here is my code thus far:
> 
> ```
> 
> export function SerializeHtmlPlugin(placeholder: string) {
>   const [editor] = useLexicalComposerContext()
> 
>   useEffect(() => {
>     editor.update(() => {
>       const parse = new DOMParser()
>       const text = parse.parseFromString(placeholder, 'text/html')
>       const nodes = $generateNodesFromDOM(editor, text)
>       const root = $getRoot()
> 
>       nodes.forEach((n) => root.append(n))
>     })
>   }, [editor, placeholder])
> }
> 
> export function Editor({ placeholder }: { placeholder: string }) {
>   
>   // function prepopulatedRichText() {
>   //   const root = $getRoot()
>   //   if (root.getFirstChild() === null) {
>   //     const paragraph = $createParagraphNode()
> 
>   //     paragraph.append($createTextNode(placeholder))
>   //     root.append(paragraph)
>   //   }
>   // }
> 
>   const editorConfig = {
>     // The editor theme
> 
>     theme: ExampleTheme,
> 
>     // Handling of errors during update
>     onError(error: any) {
>       throw error
>     },
>     // Any custom nodes go here
>     nodes: [
>       HeadingNode,
>       ListNode,
>       ListItemNode,
>       QuoteNode,
>       CodeNode,
>       CodeHighlightNode,
>       TableNode,
>       TableCellNode,
>       TableRowNode,
>       AutoLinkNode,
>       LinkNode,
>     ],
>   }
> 
>   return (
>     <div className="App">
>       <LexicalComposer initialConfig={editorConfig}>
>         <div className="editor-container">
>           <ToolbarPlugin />
>           <div className="editor-inner">
>             <RichTextPlugin
>               contentEditable={<ContentEditable className="editor-input" />}
>               placeholder={<Placeholder placeholder={placeholder} />}
>               ErrorBoundary={LexicalErrorBoundary}
>             />
>             <SerializeHtmlPlugin placeholder={placeholder} />
>             <HistoryPlugin />
>             <AutoFocusPlugin />
>             <AutoLinkPlugin />
>             <ListPlugin />
>             <LinkPlugin />
>             <OnChangePlugin onChange={(state) => console.log(state)} />
>           </div>
>         </div>
>       </LexicalComposer>
>     </div>
>   )
> }
> ```
> 
> ```
> 
> import ExampleTheme from './ExampleTheme'
> import { LexicalComposer } from '@lexical/react/LexicalComposer'
> import { RichTextPlugin } from '@lexical/react/LexicalRichTextPlugin'
> import { ContentEditable } from '@lexical/react/LexicalContentEditable'
> import { HistoryPlugin } from '@lexical/react/LexicalHistoryPlugin'
> import { AutoFocusPlugin } from '@lexical/react/LexicalAutoFocusPlugin'
> import LexicalErrorBoundary from '@lexical/react/LexicalErrorBoundary'
> // import TreeViewPlugin from './plugins/TreeViewPlugin'
> import ToolbarPlugin from './ToolbarPlugin'
> import { HeadingNode, QuoteNode } from '@lexical/rich-text'
> import { TableCellNode, TableNode, TableRowNode } from '@lexical/table'
> import { ListItemNode, ListNode } from '@lexical/list'
> import { CodeHighlightNode, CodeNode } from '@lexical/code'
> import { AutoLinkNode, LinkNode } from '@lexical/link'
> import { LinkPlugin } from '@lexical/react/LexicalLinkPlugin'
> import { ListPlugin } from '@lexical/react/LexicalListPlugin'
> import { MarkdownShortcutPlugin } from '@lexical/react/LexicalMarkdownShortcutPlugin'
> import { OnChangePlugin } from '@lexical/react/LexicalOnChangePlugin'
> import { TRANSFORMERS } from '@lexical/markdown'
> import './styles.css'
> // import ListMaxIndentLevelPlugin from './plugins/ListMaxIndentLevelPlugin'
> // import CodeHighlightPlugin from './plugins/CodeHighlightPlugin'
> import AutoLinkPlugin from './AutoLinkPlugin'
> import { $createLinkNode } from '@lexical/link'
> 
> import { $createListItemNode, $createListNode } from '@lexical/list'
> import { $generateHtmlFromNodes } from '@lexical/html'
> import { $createHeadingNode, $createQuoteNode } from '@lexical/rich-text'
> import { useState } from 'react'
> import {
>   $createParagraphNode,
>   $createTextNode,
>   $getRoot,
>   $isElementNode,
>   DOMChildConversion,
>   DOMConversion,
>   DOMConversionFn,
>   LexicalEditor,
>   LexicalNode,
> } from 'lexical'
> import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext'
> 
> function Placeholder({ placeholder }: { placeholder: string }) {
>   return (
>     <div
>       className="editor-placeholder"
>       // dangerouslySetInnerHTML={{ __html: placeholder }}
>     >
>       ...enter text
>     </div>
>   )
> }
> 
> export function $generateNodesFromDOM(
>   editor: LexicalEditor,
>   dom: Document,
> ): Array<LexicalNode> {
>   let lexicalNodes: Array<LexicalNode> = []
>   const elements: Array<Node> = dom.body ? Array.from(dom.body.childNodes) : []
>   const elementsLength = elements.length
> 
>   for (let i = 0; i < elementsLength; i++) {
>     const element = elements[i]
> 
>     if (!IGNORE_TAGS.has(element.nodeName)) {
>       const lexicalNode = $createNodesFromDOM(element, editor)
> 
>       if (lexicalNode !== null) {
>         lexicalNodes = lexicalNodes.concat(lexicalNode)
>       }
>     }
>   }
> 
>   return lexicalNodes
> }
> const IGNORE_TAGS = new Set(['STYLE'])
> 
> function getConversionFunction(
>   domNode: Node,
>   editor: LexicalEditor,
> ): DOMConversionFn | null {
>   const { nodeName } = domNode
> 
>   const cachedConversions = editor._htmlConversions.get(nodeName.toLowerCase())
> 
>   let currentConversion: DOMConversion | null = null
> 
>   if (cachedConversions !== undefined) {
>     for (const cachedConversion of cachedConversions) {
>       const domConversion = cachedConversion(domNode)
> 
>       if (
>         domConversion !== null &&
>         (currentConversion === null ||
>           currentConversion.priority < domConversion.priority)
>       ) {
>         currentConversion = domConversion
>       }
>     }
>   }
> 
>   return currentConversion !== null ? currentConversion.conversion : null
> }
> 
> function $createNodesFromDOM(
>   node: Node,
>   editor: LexicalEditor,
>   forChildMap: Map<string, DOMChildConversion> = new Map(),
>   parentLexicalNode?: LexicalNode | null | undefined,
> ): Array<LexicalNode> {
>   let lexicalNodes: Array<LexicalNode> = []
> 
>   if (IGNORE_TAGS.has(node.nodeName)) {
>     return lexicalNodes
>   }
> 
>   let currentLexicalNode = null
>   const transformFunction = getConversionFunction(node, editor)
>   const transformOutput = transformFunction
>     ? transformFunction(node as HTMLElement)
>     : null
>   let postTransform = null
> 
>   if (transformOutput !== null) {
>     postTransform = transformOutput.after
>     currentLexicalNode = transformOutput.node
> 
>     if (currentLexicalNode !== null) {
>       for (const [, forChildFunction] of forChildMap) {
>         currentLexicalNode = forChildFunction(
>           currentLexicalNode,
>           parentLexicalNode,
>         )
> 
>         if (!currentLexicalNode) {
>           break
>         }
>       }
> 
>       if (currentLexicalNode) {
>         lexicalNodes.push(currentLexicalNode)
>       }
>     }
> 
>     if (transformOutput.forChild != null) {
>       forChildMap.set(node.nodeName, transformOutput.forChild)
>     }
>   }
> 
>   // If the DOM node doesn't have a transformer, we don't know what
>   // to do with it but we still need to process any childNodes.
>   const children = node.childNodes
>   let childLexicalNodes = []
> 
>   for (let i = 0; i < children.length; i++) {
>     childLexicalNodes.push(
>       ...$createNodesFromDOM(
>         children[i],
>         editor,
>         new Map(forChildMap),
>         currentLexicalNode,
>       ),
>     )
>   }
> 
>   if (postTransform != null) {
>     childLexicalNodes = postTransform(childLexicalNodes)
>   }
> 
>   if (currentLexicalNode == null) {
>     // If it hasn't been converted to a LexicalNode, we hoist its children
>     // up to the same level as it.
>     lexicalNodes = lexicalNodes.concat(childLexicalNodes)
>   } else {
>     if ($isElementNode(currentLexicalNode)) {
>       // If the current node is a ElementNode after conversion,
>       // we can append all the children to it.
>       currentLexicalNode.append(...childLexicalNodes)
>     }
>   }
> 
>   return lexicalNodes
> }
> 
> export function Editor({ placeholder }: { placeholder: string }) {
>   const parse = new DOMParser()
>   const text = parse.parseFromString(placeholder, 'text/html')
>   console.log(text, 'texxet')
> 
>   function prepopulatedRichText() {
>     const root = $getRoot()
>     if (root.getFirstChild() === null) {
>       const paragraph = $createParagraphNode()
>       paragraph.append($createTextNode($generateNodesFromDOM(, text)))
>       root.append(paragraph)
>     }
>   }
>   const editorConfig = {
>     // The editor theme
>     nameSpace: 'RichTextEditor',
>     theme: ExampleTheme,
>     editorState: prepopulatedRichText,
>     // Handling of errors during update
>     onError(error: any) {
>       throw error
>     },
>     // Any custom nodes go here
>     nodes: [
>       HeadingNode,
>       ListNode,
>       ListItemNode,
>       QuoteNode,
>       CodeNode,
>       CodeHighlightNode,
>       TableNode,
>       TableCellNode,
>       TableRowNode,
>       AutoLinkNode,
>       LinkNode,
>     ],
>   }
> 
>   return (
>     <div className="App">
>       <LexicalComposer initialConfig={editorConfig}>
>         <div className="editor-container">
>           <ToolbarPlugin />
>           <div className="editor-inner">
>             <RichTextPlugin
>               contentEditable={<ContentEditable className="editor-input" />}
>               placeholder={<Placeholder placeholder={text.body} />}
>               ErrorBoundary={LexicalErrorBoundary}
>             />
>             <HistoryPlugin />
>             <AutoFocusPlugin />
>             <AutoLinkPlugin />
>             <ListPlugin />
>             <LinkPlugin />
>             <OnChangePlugin onChange={(state) => console.log(state)} />
>           </div>
>         </div>
>       </LexicalComposer>
>     </div>
>   )
> }
> ```

I am facing this issue too, But I am not sure is this because of ParagraphNode importDOM method or in the $generateNodesFromDOM function
