### ISSUE TITLE
Bug: `$getRoot().getTextContentSize()` does not account for overriden `getTextContentSize` in descendants

### ISSUE THREAD

**Issue by GiacomoRandazzo** [facebook/lexical#3772]
Lexical version: 0.7.6

## Steps To Reproduce

1. Create custom node that overrides both `getTextContent` and `getTextContentSize`, where `getTextContent().length !== getTextContentSize()`;
2. Call `$getRoot().getTextContent()` and `$getRoot().getTextContentSize()`, they will both account for the `getTextContent` override but not the `getTextContentSize` override.

Link to code example: https://codesandbox.io/s/lexical-gettextcontentsize-2if3vk (forked from https://codesandbox.io/s/lexical-plain-text-example-g932e).

In `EmojiNode.js` I override `getTextContent` to return `emoji:${this.__text}` and `getTextContentSize` to return `1`.
Add an emoji to the editor by typing `:)`, in the console it will log:

```
getTextContent emoji:🙂 
getTextContentSize 8
```

The output logged for `getTextContent` is expected, the one for `getTextContentSize` is not. I expect it to be `1` instead of `8`.

## Motivation

We have a custom equation node. To customize the text/plain clipboard behavior we return `"$" + this.equation + "$"` as text content. But in order to enforce a maximum length on the editor text content we override `getTextContentSize` to return the length of `this.equation`, without accounting for the delimiters "$".
Is there a better approach?

**Comment by trueadm** [comment]
Feel free to put up a PR that adjusts the logic to use `getTextContentSize()` rather than using the length. I think this is likely down the an expectation that we didn't think anyone would have differing values in these.
