### ISSUE TITLE
How to apply common nodes style to the list item node?

### ISSUE THREAD

**Issue by nickschinestzki** [facebook/lexical#3777]
I'm trying to use CSS to make the list item markers (1, 2, 3 or a bullet in unordered lists) to follow the style of its content. 

Here's an example of how it is right now: 
 
<img width="431" alt="Captura de Tela 2023-01-25 às 10 00 03" src="https://user-images.githubusercontent.com/33634787/214570104-7add22a9-4dda-427b-8a41-42778af700ad.png">

The markers are the same regardless of the font size and color of its content (plus font-weight, etc). 
So, how can I apply styles to a whole list item when selecting the full ListItemNode?

**Comment by thegreatercurve** [comment]
Possibly, add a node transform for the ListItemNode, and then based on the properties of that node conditionally add classes to the editor which target the `::marker` pseudo selector?

**Comment by thegreatercurve** [comment]
Closing this as I think this can be achieved with CSS.

**Comment by mgslone** [comment]
@thegreatercurve Is there a solution that doesn't involve the use of pseudo-selectors?  CSS-in-js doesn't support pseudo-selectors. We use lexical to flexibly render user-driven input, so it's not like we can make a stylesheet with every possible style a user might want to employ.
