### ISSUE TITLE
Bug: @lexical/headless not working in jest test

### ISSUE THREAD

**Issue by strdr4605** [facebook/lexical#3783]
We are creating a function that parses lexical plain text plugin state to plainText + mentions offset (for legacy React Native editor).
We want to make sure that the plainText from our function is equal to `parsedEditorState.read(() => $getRoot().getTextContent())` of the headless editor.

We had issues with `editor.parseEditorState(JSON.strigify({root: ... }))` so we decided to create the state with lexical functions.

Lexical version: `0.7.6`

## Steps To Reproduce

```js
import { createHeadlessEditor } from "@lexical/headless";

import { $createParagraphNode, $createTextNode, $getRoot } from "lexical";

it("Checks if lexical headless works", () => {
  const editor = createHeadlessEditor({
    nodes: [],
    onError: () => {}
  });

  editor.update(() => {
    $getRoot().append(
      $createParagraphNode().append($createTextNode("Hello world"))
    );
  });

  const editorState = editor.getEditorState().toJSON();
  console.log("editorState", editorState);

  expect(editorState.root.children).toHaveLength(); // is empty
});
```

Link to code example:

https://codesandbox.io/s/lexical-headless-jest-u88es7?file=/hello.test.js

## The current behavior

editorState.root.children is empty

## The expected behavior

editorState.root should have children

**Comment by trueadm** [comment]
Lexical updates are async, try awaiting the `editor.update()`, or any microtask.

**Comment by strdr4605** [comment]
`await editor.update()` works
https://codesandbox.io/s/lexical-headless-jest-forked-rfywh6?file=/hello.test.js

**Comment by strdr4605** [comment]
This also works. (no need to have a promise)

```js
editor.update(
    () => {
      $getRoot().append(
        $createParagraphNode().append($createTextNode("Hello world"))
      );
    },
    { discrete: true }
  );
```
