### ISSUE TITLE
Bug: Triple-click selections have incorrect format

### ISSUE THREAD

**Issue by Awjin** [facebook/lexical#3784]
https://github.com/facebook/lexical/issues/2648 has related discussion around how triple-click selection should behave, but this is a separate bug.

Lexical version: 0.7.6

## Steps To Reproduce

1. Create two paragraphs.
2. Triple-click to select the first paragraph.
3. Set the format to "bold".

## Current behavior

```ts
selection.hasFormat("bold") === false
```

## Expected behavior

```ts
selection.hasFormat("bold") === true
```

https://user-images.githubusercontent.com/3211874/214970056-cf024ecb-ec0f-4f76-b9bc-14c300b7ecce.mov

**Comment by Awjin** [comment]
Lexical includes the trailing newline when you triple-click. This is correct behavior selection behavior.

The issue is, there are 2 differing user flows after triple-clicking:

1. Text insertion expects the newline to be included (e.g. deleting a triple-selected line deletes the trailing newline).

2. Text formatting does not expect the newline to be included.

**Comment by trueadm** [comment]
I'm unsure if there's one discrete fix here that wouldn't seem like a hack. This is actually how the browser intends it to work AFAIK.

**Comment by Awjin** [comment]
> I'm unsure if there's one discrete fix here that wouldn't seem like a hack. This is actually how the browser intends it to work AFAIK.

Are you referring to the selection behavior? If so, agreed; the selection behavior is correct.

But, determining whether that selection has a format shouldn't be influenced by the trailing newline.

**Comment by madhusudhand** [comment]
There is another case where, double click to select a work should highlight right format.
It works good if the selection made doesn't include first letter.

In the following scenario, `selection.hasFormat` returned `true` when second work is selected (double click to select), and the same returned `false` when the first word is selected

![lex-formatting](https://user-images.githubusercontent.com/1935113/230641990-14380f59-9100-4b12-8560-614523ebec4e.gif)
