### ISSUE TITLE
Editor state is not updating when I use RTK Query invalidatesTags

### ISSUE THREAD

**Issue by bylly1** [facebook/lexical#3790]
I use lexical for my post card content, but when I create the new post and `RTK Query` invalidates the cache and trigger again the posts feed the content of the new card is not updating but get last post card content

Here is the code of the post content component
``` js
const PostContent = (props: PostContentProps) => {
 const { content } = props;
 
 cont editorConfig = {
  namespace: 'PostContent',
  editable: false,
  editorState: content,
  onError: (err: Error) => throw err,
  nodes: [...PostContentNodes]
 }
 return (
   <LexicalComposer initialConfig={editorConfig}>
      <div>
        <PlainTextPlugin 
           contentEditable={<ContentEditable />
           placeholder={null}
           ErrorBoundary={LexicalErrorBoundary}
         />
        {...some plugins}
     </div>
   </LexicalComposer> 
 )
}
```
In database I store the content as JSON using `editorState.toJSON()`;

**Comment by thegreatercurve** [comment]
You need to actively update the editor state, using one of the provided methods (https://lexical.dev/docs/getting-started/quick-start#updating-an-editor). The state of the editor will not update by providing a new `initialConfig` object.

**Comment by bylly1** [comment]
From what I read in the link that you give me, I need to create another node for updating the `editorState`? In the link I don t know from here you got the `editor`
