### ISSUE TITLE
Bug: Deleting does not update selection format

### ISSUE THREAD

**Issue by TheSwilliam** [facebook/lexical#3792]
Lexical version: 0.7.5

## Steps To Reproduce

1. Toggle bold on
2. addd some text and hit return to add a new line. 
3. Delete the new line

## The current behavior

https://user-images.githubusercontent.com/69976884/215519780-02e1ff06-97a2-4e2e-81c1-7a1f22f781af.mov

## The expected behavior
The selection format should have bold toggled on when it goes back to the original line after delete

**Comment by TheSwilliam** [comment]
Here is a high level work around I found. 
```
useEffect(() => {
    return editor.registerCommand(
      SELECTION_CHANGE_COMMAND,
      (_payload, newEditor) => {
        const selection = $getSelection();
        if ($isRangeSelection(selection) && selection.isCollapsed()) {
          const node = selection.anchor.getNode();
          if ($isTextNode(node)) {
            const bold = node.hasFormat("bold");
            const italic = node.hasFormat("italic");
            const underline = node.hasFormat("underline");
            const strikethrough = node.hasFormat("strikethrough");

            if (selection.hasFormat("bold") !== bold) selection.toggleFormat("bold");
            if (selection.hasFormat("italic") !== italic) selection.toggleFormat("italic");
            if (selection.hasFormat("underline") !== underline) selection.toggleFormat("underline");
            if (selection.hasFormat("strikethrough") !== strikethrough) selection.toggleFormat("strikethrough");
          }
        }
        return false;
      },
      COMMAND_PRIORITY_EDITOR
    );
  }, [editor]);
```

**Comment by trueadm** [comment]
I think the bug is likely related to this code:

https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalEvents.ts#L310-L322

Could you see if something in there looks wrong for when you go back to the line. Any help with this would be much appreciated. :)
