### ISSUE TITLE
Feature: Allow "plaintext-only" as contenteditable

### ISSUE THREAD

**Issue by Arjan-Zuidema** [facebook/lexical#3796]
We are currently working on a rich text editor using Lexical which we load in using a web view in a react-native app. We have a native toolbar for the h1/h2 and B/I/U options. But we do not allow a heading to be bold italic or underlined. When long pressing on a word, a native menu shows with (on iOS called structure) with options to make the selected text bold italic or underline. This menu can be disabled with `contenteditable="plainonly-text"`

Right now we are using the `registerRootListener` to set the attribute to `plaintext-only`. Unfortunately this gets reset because of react rerenders. So we implemented a `MutationObserver` to watch for the attribute to change, and we change it back.
This is not ideal and would be nice if was implemented in Lexical.

**Comment by thegreatercurve** [comment]
Hey! Realistically, I don't think we will support any of the custom `contenteditable` properties any time soon (i.e. `plaintext-only`, `carat` or `events`). 

We have enough issues with the booleanish values. None of experimental custom properties currently work within Firefox, and there's a real lack of clarity around the spec ([link](https://bugzilla.mozilla.org/show_bug.cgi?id=1291467)) causing existing cross-browser bugs.

If you're implementing Lexical through a WebView, could you do something like this instead: [link](https://www.appsloveworld.com/coding/ios/717/remove-bold-italic-underline-in-toolbar-selection-in-wkwebview)
