### ISSUE TITLE
Bug: When the cursor is on the textahead menu, the function of moving the textahead menu with the keyboard works strangely.

### ISSUE THREAD

**Issue by blacktoast** [facebook/lexical#3811]
First,  I enter `:` key
and If you see the textahead menu, hover the cursor over the first textahead menu and press the button below the direction key seven times to select the seventh item that is not visible from the menu.

and then the active state does not go to the 7th but moves the cursor up to the hover item

Lexical version:

## Steps To Reproduce

1. Go to https://playground.lexical.dev
2. try input `:`
3. put the cursor on the textahead menu
4. try pressing the downwards arrow key 5 or 6 times to select invisible elements in textahead menu

## The current behavior
![Kapture 2023-02-03 at 00 01 30](https://user-images.githubusercontent.com/10705018/216365899-9aeea405-595a-485d-878c-6dd1a172fa76.gif)
## The expected behavior
Is this the correct function? 
I expected that I could select the last item of textahead menu and I didn't want the cursor event for hover to activate

**Comment by thegreatercurve** [comment]
I don't think this is really a bug. The hover event should probably take primacy over the keyboard event, especially if the cursor is hovering over a menu entry at the time. The menu works as expected if you move the cursor out of the menu when using the typeahead.
