### ISSUE TITLE
Bug: Compatibility issue with Microsoft Clarity - unordered lists

### ISSUE THREAD

**Issue by scvet-ct** [facebook/lexical#3839]
Lexical version: 0.7.6

We are using Microsoft Clarity to track user activity and have found that if a user clicks on a bullet point that has no text on it, it triggers an error with Clarity n.trim() is not a function. I logged it with Clarity here, but am not sure if it is something that can be resolved on the Lexical side? (https://github.com/microsoft/clarity/issues/341)

Our application is for report writing and we have one mandatory text box in our application that comes pre-loaded with a bullet point, so this error is triggered every time someone writes a report. I can't find a way of catching this error as it's taking place inside the clarity script, where it is expecting a string and receiving something else.

It doesn't affect the user experience but is coming through to Sentry many times a day.

The Clarity script is here: https://www.clarity.ms/eus-d/s/0.7.1/clarity.js

## Steps To Reproduce

1. install MS Clarity in application
2. start an unordered list but don't type anything
3. click off editor
4. click next to empty bullet point and error will appear in console

Link to code example:

## The current behavior

Clicking here:
![image](https://user-images.githubusercontent.com/114913876/217246349-ec12fd23-4346-4cbc-9bc3-229631c5f596.png)
Causes this error:
![image](https://user-images.githubusercontent.com/114913876/217246426-759b0f1a-caf2-4278-8863-76a62a16364f.png)

## The expected behavior

No error when you click on an empty bullet point.

**Comment by thegreatercurve** [comment]
@scvet-ct I don't think there's anything we can really do here from our side as the TypeError is within Clarity. I presume this error is referring to `String.prototype.trim`. In that case, we're not monkey-patching any methods on the `String` prototype from our library, which could lead to the error.
