### ISSUE TITLE
Feature: Allow styling when selection is collapsed

### ISSUE THREAD

**Issue by TheSwilliam** [facebook/lexical#3841]
In all other text editors you can set the font size,color, etc when the selection is collapsed and when you type the styles get applied.

https://user-images.githubusercontent.com/69976884/217268463-91391d32-0f61-4b4c-ad35-eb440179b543.mov

**Comment by niteshmodi** [comment]
Hey i am new here and want to contribute,my skills is all basic concepts of react and good knowledge of javascript,
What skills you need to contribute in good first issue?

**Comment by joeshajan** [comment]
I would like to fix this issue can someone assign this to me?

**Comment by niteshmodi** [comment]
hey can someone assign me this

**Comment by thegreatercurve** [comment]
Fixed by #3863
