### ISSUE TITLE
Bug: Incorrect text representation in registerTextContentListener when copy pasting text

### ISSUE THREAD

**Issue by White-dracke** [facebook/lexical#3849]
The text representation of lexical becomes out of sync with inner lexical state representation when copy-pasting text and more characters. Some paragraphs are represented more than once.

Lexical version: 0.7.7

## Steps To Reproduce
copy text from https://docs.google.com/document/d/1k68xiAMbWsIZfzgP6VR42Pm5u1B-akgdub4Hw-13A5E/edit to the editor and append a new line after the first `a`. 

## Code Sandbox
https://codesandbox.io/s/stupefied-shadow-hufyc0
The bug is visible in the console window.

## The current behavior
The inner text representation becomes
```
a



b

a



b



c
```

## The expected behavior
The inner representation should be:
```
a

b
c
```

**Comment by trueadm** [comment]
Try the latest version of Lexical :)

**Comment by thegreatercurve** [comment]
Verified that this is now working correctly in the CodeSandbox with the latest version. Thanks for the comprehensive bug report @White-dracke! Always really appreciated.
