### ISSUE TITLE
Text data

### ISSUE THREAD

**Issue by darfilp** [facebook/lexical#3852]
This https://drive.google.com/file/d/1SuyUQYdizJ5RcQl-450ZOROTRS12M8i9/view?usp=sharing  is generated by the TreeView. Can I get this data as an object?

Example: https://codesandbox.io/s/admiring-cerf-gzcp9b?file=/src/plugins/TreeViewPlugin.js

**Comment by thegreatercurve** [comment]
You can get the editor state as JSON here: https://lexical.dev/docs/concepts/serialization#json
