### ISSUE TITLE
Feature: Option to disallow cursor placement inside a tokenized TextNode

### ISSUE THREAD

**Issue by aalmazan** [facebook/lexical#3858]
When a `TextNode` is set to a `token` mode, there should be an option to prevent the cursor from appearing within that `TextNode`. When removing a tokenized `TextNode`, it's already the case the a delete/backspace keypress will remove the entire node, so being able to place the cursor within that `TextNode` seems a little misleading as if its contents are editable. 

Example:
1. `[Text Node]| <-- cursor`
2. Press left arrow key
3. `cursor --> |[Text Node]`

I'm not sure about the technicalities on implementing this, but since modifying a selection can only be done on an `editor.read` or `editor.update`, this change might require something more internal? 

Example: 

https://github.com/facebook/lexical/blob/102b01d808f53b560ddbd3f7dcc53ba34d24e4e1/packages/lexical-playground/src/nodes/MentionNode.ts#L117

We change the mode from `segmented` to `token`.

Video of current behavior:

https://user-images.githubusercontent.com/800948/217667031-c556279c-3143-4056-a45b-6d4f8791e9a8.mp4

**Comment by thegreatercurve** [comment]
You can implement this without needing to add extra functionality to core. You can. just check if the node is selected and then adjust the selection accordingly. The reason we generally don't advise doing so is that it may create bugs with native selection management across browsers and devices.
