### ISSUE TITLE
Bug: Styles on collapsed range selections are lost on Firefox

### ISSUE THREAD

**Issue by birtles** [facebook/lexical#3871]
Lexical version: 0.8.0

## Steps To Reproduce

1. Go to the [lexical playground](https://playground.lexical.dev/)
2. Place the cursor at the end of a line
3. Click the color dropdown (the big A)
4. Choose a color, e.g. red
5. Press a character, e.g. "a"

## The current behavior

An "a" is appended without any color.

## The expected behavior

A red "a" is appended. 

We have a "pending styles plugin" we use to manage this in our app. With 0.8.0 I was really hoping we could rip it out and just use lexical's style handling but after trying to do so, I noticed the pending styles case is still not handled. Trying similar steps with the playground as above also fails.

**Comment by birtles** [comment]
Updated title to reflect that this reproduces for me on Firefox (Nightly, Windows) but not on Chrome.

**Comment by thegreatercurve** [comment]
I'm trying the stable version, but this seems to work for me on the latest version of Firefox. 

https://user-images.githubusercontent.com/7748470/218062163-8cec1e16-70f5-4629-aa06-abd4ced69251.mov

The color picker doesn't immediately close on select, which may be causing a related UX issue. Fixed in #3874

**Comment by birtles** [comment]
Yes, you're right. It works for me on beta, but not on Nightly. That might be due to having `editor.join_split_direction.compatible_with_the_other_browsers` set there (which is an upcoming change to Gecko's editor behavior -- see [bug 1735608](https://bugzilla.mozilla.org/show_bug.cgi?id=1735608) for details).

Can you please re-open this so I can investigate it next week? The core regression is not fixed.

**Comment by birtles** [comment]
I can't seem to reproduce this -- not sure if Firefox (Nightly) or Lexical changed or if it's just user error. Sorry for the false alarm.
