### ISSUE TITLE
Bug: Dragging nodes is almost impossible to initiate on Android, and fails to move the node if you do manage to initiate it

### ISSUE THREAD

**Issue by Slapbox** [facebook/lexical#3872]
Lexical version: Playground, so presumably latest `0.8.0`

## Steps To Reproduce

1. Try to drag nodes in the default example on Android  (Specifically tested in Chrome on Android 13)
2. Usually you cannot select them, but if you do manage to, then dragging creates the blue line showing intent to move, but the node does not actually move and the blue line persists

Link to code example: https://playground.lexical.dev/

## The current behavior

Nearly impossible to select and nodes fail to move if you do

## The expected behavior

Dragging nodes just works

**Comment by thegreatercurve** [comment]
We should probably just disable this on mobile devices, especially as it's not a native exported plugin.

Handling drag-and-drop or `touchmove` events is [notoriously tricky on mobile browsers](https://caniuse.com/?search=touchmove), and I don't want to overcomplicate the playground plugin, which is meant to be more of an illustrative example.

**Comment by Slapbox** [comment]
That's sad - definitely not the resolution I was hoping for, but I understand. Thanks for your speedy reply.

I don't understand the link to caniuse.com though, because it seems that every major browser, including mobile, supports it without any caveats?

**Comment by gaurav21r** [comment]
@Slapbox Agreed, totally not an ideal resolution. This would give Lexical *Notion* like superpowers on mobile. However I think @thegreatercurve wanted to point out [this](https://caniuse.com/?search=drag) link instead.

I think the core issue is non support of standard HTML5 DnD in mobile browsers. I'm trying a few simple solutions like polyfills etc and would let everyone know here if I manage to make something releasable.

**Comment by thegreatercurve** [comment]
Yeah, I was meant to link to the `touchmove` event which is also badly supported, but the point still stands in that this isn't a core node of Lexical, it's just a simple illustrative example. 

Adding support for drag-and-drop functionality isn't something we necessarily want the burden of maintaining, when we have other things planned with the core.

**Comment by gaurav21r** [comment]
@thegreatercurve Yes I understand, I believe all the packages in the `playground` package are more of examples rather than core maintenance? While the ones outside fall under "Core" ones which will be supported?

Since DnD is already there (and works pretty well for desktop) I just thought I'd try my hand at brining mobile support (maybe with a polyfill). I've raised a few issues in the `Excalidraw` plugin which you have so helpfully solved :) So i just thought any enhancements here can remain "community supported" rather than the core team taking the responsibility?

**Comment by thegreatercurve** [comment]
Anything that falls within the `lexical-playground` folder are NOT core features. 

We surface them primarily to provide testable examples for our E2Es, and to give those in the community a starting point if they want to build something similar. 

If you want to build a fully-featured draggable plugin, we'd absolutely welcome the effort! 

The best place to potentially host it though may be as your own NPM package, so others can import and contribute.

**Comment by qaws5503** [comment]
@gaurav21r Found this threads which need the same feature, may I ask how was your work on mobile DnD? Have you found a suitable solution that will let us implement a fully device supported DnD?
