### ISSUE TITLE
Bug: Uncaught Error: Dynamic require of "lexical" is not supported

### ISSUE THREAD

**Issue by stonix26** [facebook/lexical#3873]
I created a custom editor component and bundled it with [Tsup](https://tsup.egoist.dev/) inside my Turbo repo. It successfully bundled, but when I tried running it in Storybook, it shows me this console error: `Uncaught Error: Dynamic require of "lexical" is not supported`. I also tried running it inside my NextJS app, but it still crashes my app with this same error.

![Screenshot from 2023-02-10 13-35-50](https://user-images.githubusercontent.com/15176029/218009575-b14a6e75-3b09-4c39-8a3a-5ab54ef3b858.png)

Lexical version: "@lexical/react": "^0.8.0", "lexical": "^0.8.0"
Tsup version: "tsup": "^6.5.0"
React version: "react": "^18.2.0"

... and here's my tsup config inside my package.json:
`"tsup": {
    "entry": [
      "src/index.ts"
    ],
    "format": [
      "cjs",
      "esm"
    ],
    "dts": true,
    "keepNames": true,
    "splitting": true,
    "sourcemap": true,
    "minify": true,
    "clean": true
  },`

What am I missing in order to fix this?

**Comment by thegreatercurve** [comment]
There was a related issue with the 0.7.8 release. Try upgrading to the latest version to fix this issue.

**Comment by stonix26** [comment]
> There was a related issue with the 0.7.8 release. Upgrading to the latest version should fix this issue.

Yes, I use version 0.8.0, the latest as of this writing.

**Comment by thegreatercurve** [comment]
I'm not sure in that case. We've definitely not made any amendments to the module logic or changed any of the imports in that file.

**Comment by thegreatercurve** [comment]
Closing this as I don't think it's Lexical specific and I can't seem to replicate it in my Next.js project.

**Comment by lluiscab** [comment]
Hi @stonix26, I'm facing a similar issue here, did you manage to resolve it?

**Comment by stonix26** [comment]
> Hi @stonix26, I'm facing a similar issue here, did you manage to resolve it?

I haven't resolved it. I switched to Tiptap editor as I have no time investigating it that time 😄
