### ISSUE TITLE
Bug: Playground inline code that starts with @ can be tricked into acting as @-mention

### ISSUE THREAD

**Issue by Slapbox** [facebook/lexical#3887]
Lexical version:

## Steps To Reproduce

1. Click around on the text `@lexical/react` - specifically on the first and second letters after the `@` symbol
2. Eventually the @-mentions dropdown will appear
3. Select an item for the list and it will replace part of the inline code

## The current behavior

@-mentions inside of inline code are recognized (with difficulty)

## The expected behavior

@-mentions should not occur inside of inline code

![image](https://user-images.githubusercontent.com/6835891/218283296-1c6a03ef-42f2-4019-ae0d-d38affa345cc.png)

![image](https://user-images.githubusercontent.com/6835891/218283316-ca64d669-ccd3-44d7-9351-54d301f8d970.png)

![image](https://user-images.githubusercontent.com/6835891/218283319-e4ded4cc-2737-48d4-b63d-9844565d011f.png)

**Comment by thegreatercurve** [comment]
You could update the `checkForMentionMatch` logic in the `MentionsPlugin` to check for whether or not you're in a `CodeNode`, but the fact we're checking inside a code is somewhat inconsequential. The logic works correctly in that it matches the Regex and then correctly splits the node to insert the mention.
