### ISSUE TITLE
Feature: Example of adding an integration form to a document

### ISSUE THREAD

**Issue by Birddle** [facebook/lexical#3888]
I'm working on used lexical for form field and would like add an example to official docs to be possible

**Comment by thegreatercurve** [comment]
@Birddle Are there any specific problems you're struggling with when it comes to integrating Lexical with forms? Lexical works independently of HTML forms or React form libraries. 

The only thing to really be aware of is that you are updating React form library state using the `OnChangePlugin` or that you are getting the editor state on submit of your HMTL form.

**Comment by Birddle** [comment]
> @Birddle Are there any specific problems you're struggling with when it comes to integrating Lexical with forms? Lexical works independently of HTML forms or React form libraries.
> When I integrate with React-hook-form, I have to use useRef to get the editorState, while registering the fields. But this does not seem to register successfully.
```
const {register, handleSubmit, control, setValue, formState: {errors}} = useForm({
        resolver: yupResolver(schema),
    });
    const editorRef: any = useRef();
    if (editorRef.current !== undefined) {
        if (editorRef.current) {
            register("content",{value: JSON.stringify(editorRef.current.getEditorState())})
            setValue("content",JSON.stringify(editorRef.current.getEditorState()))
        }
    }
> The only thing to really be aware of is that you are updating React form library state using the `OnChangePlugin` or that you are getting the editor state on submit of your HMTL form.

I didn't use the ONChange event because I just wanted to implement the blog edit and save functionality.

**Comment by thegreatercurve** [comment]
This might be too niche of a case for the general docs, as all form libraries work differently, but the code example above could definitely be useful if someone searches through these issues.
