### ISSUE TITLE
Bug: Selecting color on the color picker creates multiple entries on the undo stack

### ISSUE THREAD

**Issue by TheSwilliam** [facebook/lexical#3890]
Lexical version: 0.8.0

## Steps To Reproduce

1. Select text
2. Expand the font color color picker and drag the handle around to adjust color

## The current behavior
Currently the color gets added to the undo stack on the mouse move event.

https://user-images.githubusercontent.com/69976884/218330664-261e5d2b-98ec-4faa-aa1b-0a3a2e3e5d9f.mov

## The expected behavior
The color should only get added to the undo stack when the mouse up event fires on the color picker. 

Figma has this working currently 

https://user-images.githubusercontent.com/69976884/218330901-f7ba4591-536c-4509-a156-0aa9a740f94c.mov

**Comment by MohitBansal321** [comment]
Hey, I didn't see any mouse move event in it @TheSwilliam

**Comment by KhalfounMehdi** [comment]
I will work on this one
