### ISSUE TITLE
Feature: If html has custom attributes, copy and paste will end up removing them

### ISSUE THREAD

**Issue by hyperjump888** [facebook/lexical#3893]
Copy and paste text such as:

<span data-attribute="abc">Hello</span>

When it is pasted:

<span>Hello</span>

The custom attributes are removed. Any ideas why it is being designed this way? Would be nice if we preserve any custom attributes.

**Comment by thegreatercurve** [comment]
You can overwrite the custom `importDOM` logic of overridden default anodes to translate the HTML attributes into editor state. Otherwise though, we just strip out any unrecognised HTML as part of the normalization process on paste.

**Comment by hyperjump888** [comment]
> 

Ok thanks for the tips
