### ISSUE TITLE
Bug: Backspace triggers a delete on Android Devices

### ISSUE THREAD

**Issue by gaurav21r** [facebook/lexical#3896]
Lexical version: 0.8.0 (Latest as of writing)

## Steps To Reproduce

1. Please see the below screen capture. The cursor is moved to a point and Backspace is pressed which triggers a `backspace` **AND** a `delete` command.

https://user-images.githubusercontent.com/1716462/218439928-73234a62-0653-4017-934c-976a8f3aac4e.mp4

## The current behaviour
The cursor is brought after `L` and backspace is pressed so **WELCOME** becomes **WEOME**

This is happening in Lexical across keyboards: Google's default GBoard, the popular Microsoft SwiftKey etc and NOT happening in other websites.

**Comment by gaurav21r** [comment]
@trueadm @acywatson @thegreatercurve 

I think I have found the offending LOC. I say this because the backspace `keyCode` on Android devices, at least the Samsung ones is `229`.

https://github.com/facebook/lexical/blob/fad90c6132c6c1fcbb55d31fa5bd3b54868086f8/packages/lexical/src/LexicalEvents.ts#L471
<img width="662" alt="image" src="https://user-images.githubusercontent.com/1716462/218441049-44d42c7b-ecd2-4f20-b30f-961a67adf6c7.png">

and
https://github.com/facebook/lexical/blob/fad90c6132c6c1fcbb55d31fa5bd3b54868086f8/packages/lexical/src/LexicalEvents.ts#L428
<img width="631" alt="image" src="https://user-images.githubusercontent.com/1716462/218441263-18b466c2-0806-466a-ab50-976fbc50d60b.png">

I think the `dispatchCommand` is firing incorrectly at https://github.com/facebook/lexical/blob/fad90c6132c6c1fcbb55d31fa5bd3b54868086f8/packages/lexical/src/LexicalEvents.ts#L491

**Comment by gaurav21r** [comment]
Thank you for the prompt response @trueadm (as usual :) ) We have a very mission critical app running with lexical and built using Hybrid App tech (Capacitor / Cordova). Can you suggest a temporary fix we can make in our own codebase for now? can we just remove the `if isPossiblyAndroidKeyPress(event.timestamp)` block of code for now until Chromium resolves this?

**Comment by trueadm** [comment]
I thought offending block was the else block?

```js
event.preventDefault();
dispatchCommand(editor, DELETE_CHARACTER_COMMAND, true);
```

**Comment by gaurav21r** [comment]
@trueadm You are absolutely right! I commented this and our app is fine now on Android (For now ❗️) 

I plan to make a ton of contributions, as you would've seen already a lil active in the issues. However can you or @thegreatercurve or @acywatson  please guide me as to how I can include my fork inside my app?

The `package.json` scripts are very confusing with no documentation on what to run what. At first I tried `npm run release` and `npm run build` and copied the built directory over our app but strangely every folder then contained an `src` folder which our `imports` could not process.

Next I tried `npm install github.com/gaurav21r/lexical#main` in our project I get the following Folder structure:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/1716462/218693603-80f60d36-2a78-4a81-8d61-24cf30fabed3.png">

Only the `monorepo` is getting updated from my fork, the other folders are coming from the `facebook` github repo.

Also there is a `@lexical` and `lexical` both in `node_modules`. Changing `lexical` and not `@lexical` works.

I am sorry if all this is standard stuff, I don't have much experience in `npm` scripts. Perhaps you could point me to a tutorial or a rough explanation?

**Comment by thegreatercurve** [comment]
If you run `npm run build-release` and then copy over the `dist` folder for each package, you will get the compiled production code we release to NPM. 

In terms of linking in-development code to your local app, you can potentially look at using `npm link` to create a symlink for making changes to your Lexical fork and then seeing them updated in your local app.

**Comment by thegreatercurve** [comment]
Closing this as we have an in-progress ticket logged with Chromium

**Comment by gaurav21r** [comment]
@thegreatercurve Thank so much just the info I wanted! `link` indeed is exactly what I was looking for & thank you for helping me outside the scope of `lexical`. Hopefully will be able to contribute more because of this.

When I run `npm run build-release` I am getting a very weird folder structure, just like when I was playing with the other script commands as I had commented to @trueadm 

There is no `dist` folder instead there is a `.ts-temp` and each of the sub packages has an `src`. This is causing a ton of issues while importing to my local app 

<img width="226" alt="image" src="https://user-images.githubusercontent.com/1716462/218980278-3138cfc5-b4b9-45b3-be0c-7c730100860e.png">

I am on a **Macbook** M1 on **Monterey** and **Node** v19.6.0 and **npm** v9.4.0

**Comment by kirandash** [comment]
> Closing this as we have an in-progress ticket logged with Chromium

Hi @thegreatercurve Any update on this? I don't seem to find any update on the chrome ticket either.

The fix mentioned on this ticket also isn't a good fix since it causes other issue
