### ISSUE TITLE
Bug: TOGGLE_LINK_COMMAND not triggering an editor update if there is a proceeding node

### ISSUE THREAD

**Issue by r1chm8** [facebook/lexical#3897]
Lexical version: 0.7.9

## Steps To Reproduce

1. Insert a link with a proceeding node
2. Select link and click the link button again (to remove the link)
3. The link is removed but the insert link popover is still open

If you repeat these steps without a node after the link, the popover will close.

Link to code example: https://playground.lexical.dev/

## The current behavior
The editor doesn't detect the update when calling `editor.dispatchCommand(TOGGLE_LINK_COMMAND, null);` if there is a node directly after the link node being removed.

## The expected behavior
The editor should detect that the link node has been removed.

**Comment by thegreatercurve** [comment]
@r1chm8 Can you elaborate a little more on how to reproduce the bug? I'm struggling to see anything in the playground with the link pop up.

**Comment by r1chm8** [comment]
Hi @thegreatercurve 

It's become apparent today that this issue is on the plaground code and not an issue with lexical.

It is a little ticky to see on the playground, however on the component I've been building (based on the playground) it was a lot more obvious. The playground leaves the link popover open after a link node has been removed using the `editor.dispatchCommand(TOGGLE_LINK_COMMAND, null);` command.

- Click on a link (which has any node after it, a `.` in the video below)
- Click on the toolbar button to toggle link
- The popover is still in the dom

[Screencast from 14-02-23 12:33:51.webm](https://user-images.githubusercontent.com/25925437/218740054-13aee1bd-92cc-484f-80b0-51201463c265.webm)

I've found a fix, within [FloatingLinkEditorPlugin](https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx) file by updating lines 247-257:

```javascript
useEffect(() => {
  return editor.registerCommand(
    SELECTION_CHANGE_COMMAND,
    (_payload, newEditor) => {
      updateToolbar();
      setActiveEditor(newEditor);
      return false;
    },
    COMMAND_PRIORITY_CRITICAL,
  );
}, [editor, updateToolbar]);
```

to the following:

```javascript
useEffect(() => {
  return mergeRegister(
    editor.registerUpdateListener(({ editorState }) => {
      editorState.read(() => {
        updateToolbar();
      });
    }),
    editor.registerCommand(
      SELECTION_CHANGE_COMMAND,
      (_payload, newEditor) => {
        updateToolbar();
        setActiveEditor(newEditor);
        return false;
      },
      COMMAND_PRIORITY_CRITICAL,
    ),
  );
}, [editor, updateToolbar]);
```

Hopefully you can see how it wasn't listening to the editor correctly so didn't know when to hide the popover element.

Many thanks!

p.s. I've been having a great time working with Lexical! :+1:

**Comment by thegreatercurve** [comment]
@r1chm8 Thanks for the detailed repro steps and the potential fix. That looks good to me, but please open a PR and I can merge it in.
