### ISSUE TITLE
Bug: Dragging text in Lexical Playground causes drag bar to stay permanently

### ISSUE THREAD

**Issue by JeremyBernier** [facebook/lexical#3905]
Lexical version: 0.8.0

## Steps To Reproduce

1. Go to https://playground.lexical.dev
2. Highlight some text
3. Attempt to drag the text elsewhere

## The current behavior

The drag line just stays there permanently (blue line below)

<img width="615" alt="image" src="https://user-images.githubusercontent.com/6643718/218869100-7cacb89f-9096-4adf-bf61-a972db06215a.png">

## The expected behavior

The drag line should disappear

**Comment by thegreatercurve** [comment]
@JeremyBernier What browser and OS are you using? I can't replicate this issue

**Comment by acywatson** [comment]
Can't repro this, and the drag plugin isn't supposed to support moving text anyway - it's only for "blocks"
