### ISSUE TITLE
Bug: $generateNodesFromDOM fails in headless mode

### ISSUE THREAD

**Issue by DaniGuardiola** [facebook/lexical#3907]
Lexical version: 0.8.0

## Steps To Reproduce

1. In a Node.js environment, try to parse some HTML that contains links and lists using a headless editor and `$generateNodesFromDOM`, as per the documentation example.
2. :boom: `HTMLElement is not defined` or `HTMLAnchorElement is not defined`

The reason is that in a server environment, those browser-exclusive globals are not present. Polyfilling is hard and clunky, since it's usually just not necessary with libs like `JSDOM` or `happy-dom`, which create sandboxed environments rather than polluting the global space.

Offending lines that I found:

- Lists package: https://github.com/facebook/lexical/blob/3228323a2e32245386dacc0327d844de6390e5a6/packages/lexical-list/src/LexicalListNode.ts#L290
- Links package: https://github.com/facebook/lexical/blob/3228323a2e32245386dacc0327d844de6390e5a6/packages/lexical-link/src/index.ts#L237

Other that I found by grepping the repo but I haven't tested:

- Code package: https://github.com/facebook/lexical/blob/3228323a2e32245386dacc0327d844de6390e5a6/packages/lexical-code/src/CodeNode.ts#L71
- Checklist: https://github.com/facebook/lexical/blob/3228323a2e32245386dacc0327d844de6390e5a6/packages/lexical-react/src/LexicalCheckListPlugin.tsx#L162

## The current behavior

Crashes.

## The expected behavior

It works because that code doesn't depend on browser-only globals (or there is a documented, supported, and feasible solution like executing the conversion inside `JSDOM`'s sandbox or something like that).

**Comment by acywatson** [comment]
We can honestly probably get rid of these - they're really to satisfy the type checker, as far as I recall.
