### ISSUE TITLE
Bug: Bullet list and heading 1 take effect at the same time

### ISSUE THREAD

**Issue by wuyxp** [facebook/lexical#3908]
Lexical version: 0.8.0

## Steps To Reproduce

1. select a line of text
2. Set to heading 1
3. then set to bullet list

Link to code example: https://playground.lexical.dev/

## The current behavior
Only bullet list takes effect, and heading 1 is invalid

## The expected behavior
Bullet list and heading 1 take effect at the same time

**Comment by thegreatercurve** [comment]
This is expected behaviour. Bulleted lists can't be headings at the same time.
