### ISSUE TITLE
Bug: undo button not enabled if only one change has been made

### ISSUE THREAD

**Issue by r1chm8** [facebook/lexical#3912]
Lexical version: 0.7.9

## Steps To Reproduce

Make one change within the editor, the undo button is disabled until a second change is made.

Link to code example: https://codesandbox.io/embed/bold-sara-zgy1pv

## The current behavior
The undo button isn't being enabled until two changes have been made.

## The expected behavior
The undo button should be enabled after one change has been made.

**Comment by acywatson** [comment]
This doesn't repro in the playground on 0.8.0, AFAICT

**Comment by r1chm8** [comment]
It's working on the playground because both the `CodeHighlightPlugin` and `AutoLinkPlugin` are doing something which fixes the issue. For example if I include the `AutoLinkPlugin` on the demo (https://codesandbox.io/s/condescending-cerf-zix2yh) the undo works as expected.

I unfortunately do not know enough about what this plugin in doing which is fixing the issue.

**Comment by acywatson** [comment]
@r1chm8 It actually seems to have something to do with the initial editorState you're setting in the config. If you remove that in your code sandbox, everything seems to work as it should. I'll re-open this while I investigate a bit more.

**Comment by acywatson** [comment]
Actually if you just remove "root.selectEnd()" everything works fine:

https://codesandbox.io/s/hungry-mestorf-eedzzu?file=/src/Editor.js

**Comment by r1chm8** [comment]
When I found this issue I was setting the inital state as follows:

```
<LexicalComposer initialConfig={{
  editorState: () => $convertFromMarkdownString(markdown, TRANSFORMERS)
}}>
```

Which I found here: https://lexical.dev/docs/packages/lexical-markdown

**Comment by acywatson** [comment]
K here ya go: https://github.com/facebook/lexical/pull/3914

Not sure if this is the right fix - this conditional dates back to when the original history plugin was written and I don't know what @fantactuka's intent was.
