### ISSUE TITLE
Bug: Clicking inside of inline code on Playground prevents clicking another spot in the same inline code, and causes editor to lose focus

### ISSUE THREAD

**Issue by Nantris** [facebook/lexical#3917]
Lexical version:

## Steps To Reproduce

1. Click where the red arrow is in the image below
2. Note the inability to click anywhere earlier in the same node - but you can still click after the caret

![image](https://user-images.githubusercontent.com/6835891/219227897-77ab8168-23da-496d-92a6-e3164203be46.png)

## The current behavior

Clicking inside of inline code should be allowed at all times and never blur the editor

## The expected behavior

Clicking is disallowed and the editor is blurred

**Comment by acywatson** [comment]
I have a hunch that this might be related:

https://github.com/facebook/lexical/issues/3887

**Comment by Slapbox** [comment]
@acywatson - confirming your hunch - it's the typeahead menu from mentions that's intercepting pointer events.

![image](https://user-images.githubusercontent.com/6835891/219499085-cb038078-5b7d-4575-b6f3-429f9cf21a6a.png)

**Comment by etrepum** [comment]
Can't reproduce. I can get the typeahead menu to appear just by clicking which probably shouldn't happen (would make sense to have it based on some sort of state where text input is required to trigger it) but it doesn't prevent anything else from happening.

<img width="320" alt="Screenshot 2024-12-09 at 08 54 15" src="https://github.com/user-attachments/assets/fd3f7cea-f265-4ecc-9701-1f8aae6f06e3">
