### ISSUE TITLE
Bug: $patchStyleText does not clear styles or update the style cache on collapsed selections

### ISSUE THREAD

**Issue by birtles** [facebook/lexical#3921]
Lexical version: Current trunk (1217fac5a8c0d956163a7c8012c7d74d96e801ad)

## Steps To Reproduce

Call `$patchStyleText(selection, { 'property': null })` with a collapsed selection

## The current behavior

The collapsed selection style is not updated

## The expected behavior

As with non-collapsed selections, `null` should clear the style for `'property'`

**Comment by nickjmoss** [comment]
@birtles Thank you so much for fixing, was having this problem and I could not figure out why until I found this. I updated all of my lexical packages and it now works like a charm!

**Comment by birtles** [comment]
> @birtles Thank you so much for fixing this, I was having this problem and I could not figure out why until I found this. I updated all of my lexical packages and it now works like a charm!

Thanks @nickjmoss. Glad to hear it!
