### ISSUE TITLE
Bug: Unable to type after tabbing within a code block

### ISSUE THREAD

**Issue by luo-git** [facebook/lexical#3923]
Lexical version: 0.8.0

## Steps To Reproduce

1. Create a code block with ```
2. Tab
3. Type any character other than tab

![image](https://user-images.githubusercontent.com/51979232/219329076-3ac896c0-ed83-4fb5-8810-1cdc858e0dd3.png)

Link to code example: https://codesandbox.io/s/lingering-water-uu7fwr?file=/src/Editor.tsx

## The current behavior
Typing any character other than tab has no effect.
Somehow it works fine in the playground demo here: https://playground.lexical.dev/

## The expected behavior
Should be able to type after tabbing for indentation.

Edit: Make code example more minimal.

**Comment by moy2010** [comment]
I thought it could be related to this: https://github.com/facebook/lexical/pull/3770. But it seems that it's still happening in 0.8.0. :/

**Comment by abelsj60** [comment]
Just quoting [this Discord convo](https://discord.com/channels/953974421008293909/953974421486436393/1099492021732917361): 

> Hi @ nithiwatter. This is definitely an issue. If it's what I think it is, you may be in luck. 
> 
> 1. I pull requested a fix a few months ago. The troubling code is here:
> https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalUtils.ts#L576
> 
> 2. The triggering can method was added to the textNode here:
> https://github.com/facebook/lexical/blob/main/packages/lexical/src/nodes/LexicalTextNode.ts
> 
> 3. To use it, add canContainTabs() { return true } to an extended CodeHighlightNode and it should — 🤞 — magically just work.
> 
> If it does, I really do have to give thanks to @ trueadm, who was very easy going about getting this fix over the line.

Postscript: I'm told it did work for nithiwatter! But he had to override the `CodeHighlightNode` to activate the fix.

Maybe the `CodeHighlightNode` should be updated to trigger it by default? When I debugged this (https://github.com/facebook/lexical/pull/3770), I was building a custom code package, and I did not modify this bit of original source code, so as to touch as little of Lexical as possible.

(It would have to be tested first, though.)

Perhaps this additional information will be helpful to someone in the future.

-j

**Comment by acywatson** [comment]
This works fine as of 0.11.1 in the code sandbox
