### ISSUE TITLE
Bug: $generateNodesFromDOM drops text style in source html

### ISSUE THREAD

**Issue by evskorobogatij** [facebook/lexical#3929]
I want use html as source in editor.  But styling (font color and background color dropped)

Lexical version: 0.7.6

Link to code example: 
[https://codesandbox.io/s/optimistic-hugle-ow1skx?file=/src/Components/plugins/LoadingHTMLData.ts](https://codesandbox.io/s/optimistic-hugle-ow1skx?file=/src/Components/plugins/LoadingHTMLData.ts)

## The current behavior
Dropping font color in imported html

## The expected behavior
Appling text and background color from source html to editor text

**Comment by acywatson** [comment]
We currently don't have any intention of changing this in the core, as it would lead to the default paste behavior being to render background color and font color, even in editors that don't support such functionality. In my experience, users do not like this (and many don't know the shortcut to paste as plain text). 

You can add this functionality by [overriding](https://lexical.dev/docs/concepts/node-replacement) TextNode and re-implementing importDOM to function however you want. Another option would be to just register a custom text node (with no override) that has an importDOM that handles span tags differently.
