### ISSUE TITLE
Bug: getTextContent Removes a New Line on Rich Text Editor

### ISSUE THREAD

**Issue by francistogram** [facebook/lexical#3934]
Lexical version: 0.8.0

## Steps To Reproduce

[Recorded a video](https://user-images.githubusercontent.com/3721449/235963873-726a2998-8b76-4aab-8ac7-16571d1341dc.mp4)

Basically the issue is that in `rootNode.getTextContent()` there's a point where two of the same exact editor states result in two different text contents

Seems to be easy to reproduce by
#### 1. Having at least two lines with text
```
Row 1
Row 2
```

The text content is `Row1\n\nRow2`

#### 2. Add a new line between them
```
Row 1

Row 2
```
The text content is `Row1\n\n\n\nRow2`

#### 3. On the 2nd line type anything
```
Row 1

dRow 2
```
The text content is `Row1\n\ndRow2`

Where did the two `\n`'s go?

### Link to code example:
[CodeSandbox](https://codesandbox.io/s/naughty-taussig-kop5pp?file=/src/Editor.js)

## The current behavior
It's possible to get two different text contents for the same editor state and it seems to remove some new lines

## The expected behavior
An editor state should always return the same text content

**Comment by francistogram** [comment]
Whoops, hadn't realized you had just upgraded last week. That being said. I just tired on `0.8.0` and the issue still persists

Updated the CodeSandbox and the initial comment to be `0.8.0` from `0.7.6`

**Comment by trueadm** [comment]
My hunch is that we're missing some logic. I'm no longer working on Lexical but maybe I can help you dig into this locally and maybe that can help you fix your problem and potentially put up a PR?

https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalReconciler.ts#L289

https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalReconciler.ts#L619-L620

Seems like we might just be missing updating the `editorTextContent`?

**Comment by francistogram** [comment]
Would love some help digging in to it to be able to put up a PR

Will poke around the `LexicalReconciler`, hadn't looked in there. Although I do think that the `editorTextContent` is updated? Not sure if you did a quick look at [the video](https://share.getcloudapp.com/Z4unbb1B) I recorded but the text content does change every time just not to what's expected

**Comment by francistogram** [comment]
To be clear this seems to only happen when using the `RichTextPlugin` but it works as expected with the `PlainTextPlugin`

**Comment by TomasHubelbauer** [comment]
I am running into the same issue. In my case it is manifesting in `PlainTextPlugin` though. Initially, the Lexical content is populated correctly. I am using the `OnChangePlugin` to monitor the changes to `$getRoot().getTextContent()` and the first call always returns the expected text. After making any sort of a change though, all of the subsequent calls loose all of the `\n\n`s in the entire text content. Visually though, in the editor, everything is still displayed in paragraphs as expected.

**Comment by francistogram** [comment]
@TomasHubelbauer good catch just uploaded a video of the bug to GitHub directly

Interestingly enough I'm able to get it to work perfectly fine with the `PlainTextPlugin` and only run in to this issue with the `RichTextEditor`

**Comment by TomasHubelbauer** [comment]
I'm trying to isolate a repro right now, hopefully I'll manage to get one.

**Comment by TomasHubelbauer** [comment]
Ah, nevermind, my Lexical issue happens in 0.7.5 (what I am using in my app) but works in latest (0.8.0) so I need to find a way to update: https://codesandbox.io/s/priceless-rubin-x35v51

**Comment by acywatson** [comment]
This still repros in 0.11.1

**Comment by zxhlyh** [comment]
Any updates on this issue?

**Comment by jackple** [comment]
```
useEffect(() => {
        return editor.registerCommand(
            KEY_ENTER_COMMAND,
            event => {
                if (event?.key == 'Enter') {
                    event?.preventDefault()
                    editor.dispatchCommand(INSERT_LINE_BREAK_COMMAND, false)
                    return true
                }
                return false
            },
            COMMAND_PRIORITY_HIGH
        )
    }, [editor, onSubmit, withShift])
```

I think we can take over `Enter` to fix this problem....

**Comment by etrepum** [comment]
I can't reproduce this

**Comment by larrygotto** [comment]
@etrepum i wish this issue wasn't closed, because it is still a problem over here. 
The @jackple code did fix the issue, and I think it shows 2 things:

1. The issue is real and reproduzable
2. The fix should be something native from the library, since having two `\n` markers when it should be a single one is a bug in my opinion. If we need to take over the enter command and override the event function, something is wrong.

> ```
> useEffect(() => {
>         return editor.registerCommand(
>             KEY_ENTER_COMMAND,
>             event => {
>                 if (event?.key == 'Enter') {
>                     event?.preventDefault()
>                     editor.dispatchCommand(INSERT_LINE_BREAK_COMMAND, false)
>                     return true
>                 }
>                 return false
>             },
>             COMMAND_PRIORITY_HIGH
>         )
>     }, [editor, onSubmit, withShift])
> ```
> 
> I think we can take over `Enter` to fix this problem....

**Comment by etrepum** [comment]
If you think this is still an issue please create a new one with a clear reproduction that uses the current lexical build.

That workaround looks like it changes enter to use line breaks instead of creating a new paragraph, which is not intended behavior for the rich text editor.
