### ISSUE TITLE
Feature: Export the matcher of AutoLinkPlugin

### ISSUE THREAD

**Issue by Karibash** [facebook/lexical#3940]
Currently, in order to implement an automatic linking function for URLs and mail addresses, matchers must define their own matchers using AutoLinkNode.
It would be useful to be able to use the URL and mail address matchers implemented in Playground as is.

```ts
import { AutoLinkPlugin, urlLinkMatcher, emailLinkMatcher } from '@lexical/react/LexicalAutoLinkPlugin';

const matchers = [
  urlLinkMatcher,
  emailLinkMatcher,
];

export default function LexicalAutoLinkPlugin(): JSX.Element {
  return <AutoLinkPlugin matchers={matchers} />;
}
```

**Comment by acywatson** [comment]
> AutoLinkNode.

Maybe instead of exporting it we can make it the default in the plugin. The issue is then that we have to officially support, but maybe that’s ok.
