### ISSUE TITLE
Bug: getStyleObjectFromCSS should return a read-only object

### ISSUE THREAD

**Issue by birtles** [facebook/lexical#3946]
Lexical version: 0.8.0

The object returned by `getStyleObjectFromCSS` is the same object stored in the style cache. Mutating it will have undesired effects since the cache key will no longer correspond to the contents of the object. This causes bugs like #3944.

We should, at a minimum, return a `Readonly<>` object so that TS users get an error if they try to mutate the object. We could possibly freeze the object too if we wanted the extra runtime guarantee.

Happy to make up a PR if you agree with this change. It would be a breaking change to the current API but any code broken by the change is possibly already broken in practice.

**Comment by LuciNyan** [comment]
Good catch!

**Comment by iambharathpadhu** [comment]
I can work on this !

**Comment by thegreatercurve** [comment]
Thanks @birtles! Adding the `ReadOnly` return type of something like `ReadOnly<{[key: string]: string}>` seems like a sensible change, and we can probably freeze the object just for the `__DEV__` environment, like we do [elsewhere in the codebase](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalReconciler.ts#L650-L653). We only freeze the object in dev for performance reasons.

**Comment by JatinRanka** [comment]
@thegreatercurve @zurfyx I have raised a PR to fix this issue. Thoughts on freezing the object regardless of the environment?
