### ISSUE TITLE
Question: Why the method of getElementByKeyOrThrow was not exposed in lexical?

### ISSUE THREAD

**Issue by Corle-He** [facebook/lexical#3947]
Lexical version: latest ([v0.7.9](https://github.com/facebook/lexical/releases/tag/v0.7.9))

In the process of using lexical, I've noticed that there's a good method to getting an element by `NodeKey`

- [getElementByKeyOrThrow](https://github.com/facebook/lexical/blob/f8a0ba22a169b6e2b9e6b973a02b6a08318a4d53/packages/lexical/src/LexicalUtils.ts#L1176-L1188)

But , I am very curious why this method was not exposed in [lexical](https://github.com/facebook/lexical/blob/f8a0ba22a169b6e2b9e6b973a02b6a08318a4d53/packages/lexical/src/index.ts#L130-L148
)

So, just leave tow question:
1. Is there any concern?
2. Is it possible for lexical lexical to expose this method?

And it seems that there are other ways to get the element through Node

**Comment by Hey-hy** [comment]
This problem can be solved in [PR](https://github.com/facebook/lexical/pull/3948)

**Comment by thegreatercurve** [comment]
You can just use the below method to get a DOM element which is exposed directly on the editor instance:  
```
const domElement = editor.getElementByKey(nodeKey);
```
