### ISSUE TITLE
Bug: Custom node doesn't work with `AutoLinkPlugin`

### ISSUE THREAD

**Issue by ratasorin** [facebook/lexical#3955]
I created a custom node: `CustomLinkNode`, extending `AutoLinkNode`. 
This node should display links on a red background. 
Following the documentation, I registered the node in the `editorConfig`, replacing `AutoLinkNode`: 
```js
{
  nodes: [
   CustomLinkNode,
    {
      replace: AutoLinkNode,
      with: (node) => $createCustomLinkNode(node)
    } 
  ]
}
```
I use the `AutoLinkPlugin` provided by `@lexical/link`: 
```js
import { AutoLinkNode } from "@lexical/link";

<LexicalComposer initialConfig={editorConfig}>
    <AutoLinkPlugin />
</LexicalComposer>
```

Lexical version: 0.8.0

Link to code example: https://codesandbox.io/s/custom-link-plugin-q99eth

## The current behavior
I noticed that the `createDOM` method on the `CustomLinkNode` doesn't fire when a link is created (thus no background color is applied). 
When investigating the source code for `LexicalAutoLinkPlugin.ts` I noticed that the link is "created" via:
```ts
// here `linkNode` is an instance of `CustomLinkNode` 💯 
linkTextNode.replace(linkNode);
```
Then I jumped into the browser dev tools and placed a breakpoint on this line:
```js
🔴 linkTextNode.replace(linkNode); 
```
Here is a screenshot with what happens when typing `www.google.com`: 
![bug](https://user-images.githubusercontent.com/71311944/221189460-44080f88-3fdf-441a-8a44-d503907b4953.png)

When entering the `replace` function, `replaceWith` is still `CustomLinkNode`: 
![image](https://user-images.githubusercontent.com/71311944/221190108-d25ea35b-e540-4754-84aa-69f3f3c2a7b9.png)

Later into the execution context, `writableReplaceWith` is instantiated as `AutoLinkNode`:
![image](https://user-images.githubusercontent.com/71311944/221190534-96348269-710c-49c2-b244-096678c14917.png)

And from there on `writableReplaceWith` is used in the `replace` function.
I _guess_ this is the cause of the issue.

## The expected behavior
`writableReplaceWith` should remain a `CustomLinkNode`.

**Comment by acywatson** [comment]
The problem is that you were passing the AutoLinkNode key into the constructor for CustomLinkNode inside $createCustomLinkNode. If you pass a key into the constructor, then you're associating it with an existing instance in the internal nodeMap. We should make it harder to do this.

Here's a working codesandbox: https://codesandbox.io/s/custom-link-plugin-forked-g57cir?file=/src/Editor.js

**Comment by ratasorin** [comment]
Thanks a lot! ❤️
