### ISSUE TITLE
Bug: Local build of Lexical not working causing me not fix / test / contribute.

### ISSUE THREAD

**Issue by gaurav21r** [facebook/lexical#3958]
As per @thegreatercurve s suggestion [here](https://github.com/facebook/lexical/issues/3896#issuecomment-1429593096), 

When I run `npm run build-release` I am getting a very weird folder structure.

There is no `dist` folder instead there is a `.ts-temp` and each of the sub packages has an `src`. The files in `src` are only TypeScript definitions `*.d.ts`. This is causing a ton of issues while importing to my local app 

<img width="226" alt="image" src="https://user-images.githubusercontent.com/1716462/218980278-3138cfc5-b4b9-45b3-be0c-7c730100860e.png">

I am on a **Macbook** M1 on **Monterey** and **Node** v19.6.0 and **npm** v9.4.0

I have a feeling maybe my build is silently failing? Is there something I'm doing wrong or is there any way I can turn on verbose logging?

<img width="581" alt="image" src="https://user-images.githubusercontent.com/1716462/218981913-4b72ffa4-0437-4b3e-80a1-52938ccdaa62.png">

**Comment by thegreatercurve** [comment]
You can delete them. The `.ts-temp` files are where we output the TS declaration files before moving them into their respective packages for publishing to NPM.

**Comment by gaurav21r** [comment]
@thegreatercurve ❗️I think you misunderstood me, I don't want to delete them, I am getting no `dist` folder which lexical uploads to NPM

**Comment by thegreatercurve** [comment]
@gaurav21r The `dist` folder is in the respective package. For example, the main package for Lexical core appears under `packages/lexical/dist`.  That then gets copied to NPM. If you symlink or `npm link` to that package and re-run the build script any time you make a change in your local fork, you should then be able to debug locally.

**Comment by joncodo** [comment]
How is /dist different than /npm?
