### ISSUE TITLE
Bug: Getter method in custom link node is defined unless it uses this.getWritable()

### ISSUE THREAD

**Issue by milaabl** [facebook/lexical#3960]
I have this code for my custom link node (I've built a custom link node extending the LinkNode class in order to have control over classNames attribute):

```
export class CustomLinkNode extends LinkNode {
  __url: string;
  __target: string;
  __classNames: Array<string>;
  setfoo: (value : Array<string>) => void;
  constructor(
    url: string,
    target: string,
    classNames: Array<string>,
    key?: NodeKey
  ) {
    super(url, { target });
    this.__url = url || 'https://';
    this.__target = target || '_self';
    this.__classNames = classNames || [];
  }

  static getType() {
    return "custom-link";
  }

  createDOM() {
    const link = document.createElement("a");

    link.href = this.__url;

    link.setAttribute("target", this.__target || "_blank");

    utils.addClassNamesToElement(link, (this.__classNames || []).join(" "));

    return link;
  }

  setfoo (value: Array<string>) {
    this.getWritable().__classNames = value.join(' ').split(' ').filter((v : string) => v !== ' ');
  };

  updateDOM() {
    return false;
  }
}
```

This custom node works perfectly unless I try to call the setfoo function. If the setfoo function gets called, there's an error stating that getfoo is not a function and when I check that in Developer tools Console, I see that it's not defined.

setfoo function is defined on the CustomLinkNode class object only when I use this.__classNames in my getfoo function.

But when I use it this way (this.__classNames = ), then an error complains that __classNames is a read-only property.

@facebook-github-bot 

@LuciNyan 

@acywatson 

Please help me with an advice!

**Comment by acywatson** [comment]
Sorry, I don't fully understand the issue here. I don't see "getfoo" anywhere in this code. What's the specific error that you're getting? Can you repro it in a codesandbox?

**Comment by milaabl** [comment]
@acywatson , thank you so much for getting back to me! I'll make a codesandbox project to show you the full code to reproduce.

**Comment by milaabl** [comment]
I'm preparing a repo

**Comment by milaabl** [comment]
@acywatson , please have a look at this repo: (after git clone repo, just do npm i and npm run dev, you'll see it running on localhost:3000 then)

![image](https://user-images.githubusercontent.com/86361434/220974091-d37fe059-8c91-45a2-a6f5-bafcfef08e4d.png)


I've tried uploading it to Codesandbox but the project is probably too large so it errored.


The Lexical editor- and custom node-related stuff is in src/appBase/components/markdownEditor/

and src/appBase/components/markdownEditor/plugins/customLink


Please have a look, thank you so much for your replies.

**Comment by milaabl** [comment]
@acywatson , please have a look at this Codesandbox here: https://codesandbox.io/p/github/milaabl/lexiclal--issue-getwritable/draft/admiring-wing?workspaceId=8ff52f1b-6192-4939-821f-c36ea37473d7

You'll see an error that the setfoo function is undefined if you try to toggle the link, then select over the link node and click on the save button.

**Comment by acywatson** [comment]
This is an issue with the base class not being properly extended, I don't see a bug here.
