### ISSUE TITLE
Bug: Removing element with keyboard throws "Lexical node does not exist in active editor state. Avoid using the same node references between nested closures from editorState.read/editor.update."

### ISSUE THREAD

**Issue by milaabl** [facebook/lexical#3962]
When I implement the static clone() method in my custom link node, when deleting the element with keyboard then (just pressing backspace until the text content contains one character), I receive an error "Lexical node does not exist in active editor state. Avoid using the same node references between nested closures from editorState.read/editor.update." and the element doesn't get deleted.

Video: https://streamable.com/oztbw4

Code:

```
export class CustomLinkNode extends LinkNode {
  __url: string;
  __target: string;
  __classNames: Array<string>;
  __setfoo: (value : Array<string>) => void;
  constructor(
    url: string,
    target: string,
    classNames: Array<string>,
    key?: NodeKey
  ) {
    super(url, { target });
    this.__url = url || 'https://';
    this.__target = target || '_self';
    this.__classNames = classNames || [];
    this.setfoo = function (value: Array<string>) {
      this.getWritable().__classNames = value.join(' ').split(' ').filter((v : string) => v !== ' ');
    };
  }

  static getType() {
    return "custom-link";
  }

  createDOM() {
    const link = document.createElement("a");

    link.href = this.__url;

    link.setAttribute("target", this.__target || "_blank");

    utils.addClassNamesToElement(link, (this.__classNames || []).join(" "));

    return link;
  }
  static clone(node: LinkNode): LinkNode {
    return new CustomLinkNode(
      node.__url,
      node.__target,
      node.__classNames,
      node.__key,
    );
  }

  __setfoo (value : Array<string>) {
    console.log(value);
    const writable = this.getWritable();

    writable.__classNames = value.join(' ').split(' ').filter((v : string) => v !== ' ');

    return null;
  };

  updateDOM() {
    return false;
  }
}
```

The editor is classic, not headless or anything.

I can see the error is coming from the clone method, as I used a console.log('cloning') to see if the problem is coming from the clone functions call.

**Comment by acywatson** [comment]
We need a codesandbox or something to with a repro to be able to help. You should be able to create a sandbox with a *minimal* reproduction of the issue. Please re-open when you have this

**Comment by milaabl** [comment]
@acywatson , sure, I've created a codesandbox with a minimal reproduction code, please have a look: https://codesandbox.io/p/github/milaabl/lexiclal--issue-getwritable/draft/admiring-wing?workspaceId=8ff52f1b-6192-4939-821f-c36ea37473d7&file=%2Fsrc%2Fpages%2Flocalhost.tsx&selection=%5B%7B%22endColumn%22%3A34%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A34%2C%22startLineNumber%22%3A5%7D%5D


https://0dri13-3000.preview.csb.app/


There's only minimal code related to the lexical library itself, please have a look

**Comment by milaabl** [comment]
https://codesandbox.io/p/github/milaabl/lexiclal--issue-getwritable/draft/admiring-wing?workspaceId=8ff52f1b-6192-4939-821f-c36ea37473d7

**Comment by milaabl** [comment]
@acywatson , oh, sorry, I've created so many issues in different repos on Github today, and didn't notice your comment was for another problem I've experienced with Lexical.

But I'll provide a reproduction example for this one too.

The links in orevious comments are for another issue #3960

**Comment by milaabl** [comment]
@acywatson , please have a look at this Codesandbox for this specific issue: https://codesandbox.io/p/github/milaabl/lexiclal--issue-getwritable/draft/festive-stallman?workspaceId=8ff52f1b-6192-4939-821f-c36ea37473d7&file=%2Fsrc%2FappBase%2Fcomponents%2FmarkdownEditor%2Fplugins%2FcustomLink%2FCustomLinkNode.tsx&selection=%5B%7B%22endColumn%22%3A18%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A18%2C%22startLineNumber%22%3A5%7D%5D

You'll see that error "Lexical node does not exist in active editor state..." if you toggle a custom link (with a button in the tollbar) and then try to delete the created node by either selecting it and clicking on backspace or cutting out, or clicking a backspace button multiple times
