### ISSUE TITLE
Bug: Can't go to next step when using code in markdown

### ISSUE THREAD

**Issue by mweel1** [facebook/lexical#3963]
**Steps to reproduce**

https://lexical.dev/docs/demos/plugins/markdown

Go to the end of the document and enter ```Ok

First, OK will be truncated once going into the code component. 

Second,  there doesn't seem to be a way to go to the next line after the code block.

**The expected behavior**

I would expect to be able to end the code block with ``` and it would take me to the next line, or I would have space to click outside of the code block on the next line and begin typing text.

**Comment by acywatson** [comment]
This also repros in the playground

**Comment by fantactuka** [comment]
It's not really an issue:

- Text after ``` used as a highlight language: e.g., you can do ```js or ```python to pick syntax highlighting. To avoid any coupling between markdown and code highlighting plugins we're not checking if that text is actually a syntax name or just random string. I think it's a fair tradeoff.

- You can "escape" code block by hitting enter twice:
![Kapture 2023-02-24 at 15 10 46](https://user-images.githubusercontent.com/132642/221281480-477b9a5e-2918-4da0-b3e7-6d5d698ac32d.gif)

**Comment by mweel1** [comment]
Shouldn't you get a cursor at the end of the code block?
