### ISSUE TITLE
Bug: Getter method in custom link node is defined unless it uses this.getWritable()

### ISSUE THREAD

**Issue by milaabl** [facebook/lexical#3964]
I have this code for my custom link node (I've built a custom link node extending the LinkNode class in order to have control over classNames attribute):

```
export class CustomLinkNode extends LinkNode {
  __url: string;
  __target: string;
  __classNames: Array<string>;
  __setfoo: (value : Array<string>) => void;
  constructor(
    url: string,
    target: string,
    classNames: Array<string>,
    key?: NodeKey
  ) {
    super(url, { target });
    this.__url = url || 'https://';
    this.__target = target || '_self';
    this.__classNames = classNames || [];
    this.__setfoo = function (value: Array<string>) {
      this.getWritable().__classNames = value.join(' ').split(' ').filter((v : string) => v !== ' ');
    };
  }

  static getType() {
    return "custom-link";
  }

  createDOM() {
    const link = document.createElement("a");

    link.href = this.__url;

    link.setAttribute("target", this.__target || "_blank");

    utils.addClassNamesToElement(link, (this.__classNames || []).join(" "));

    return link;
  }
  /*
  throws an error https://github.com/facebook/lexical/issues/3962
  static clone(node: LinkNode): LinkNode {
    console.log('clone');
    return new CustomLinkNode(
      node.__url,
      node.__target,
      node.__classNames,
      node.__key,
    );
  }*/

  __setfoo (value : Array<string>) {
    console.log('classname', value);
    const writable = this.getWritable();

    writable.__classNames = value.join(' ').split(' ').filter((v : string) => v !== ' ');

    return null;
  };

  updateDOM() {
    return false;
  }
}
```

The Codesandbox project with the minimal reproduction code:
https://codesandbox.io/p/github/milaabl/lexiclal--issue-getwritable/draft/admiring-wing?workspaceId=8ff52f1b-6192-4939-821f-c36ea37473d7

This custom node works perfectly unless I try to call the setfoo function. If the setfoo function gets called, there's an error stating that getfoo is not a function (![image](https://user-images.githubusercontent.com/86361434/220988581-88d6ca8d-0a07-4360-b99b-c13f9a75d235.png)) and when I check that in Developer tools Console, I see that it's not defined.

The setfoo function is defined on the CustomLinkNode class object only when I use this.__classNames in my setfoo function instead of this.getWritable().__classNames = ...somevalue.

But when I use it this way (this.__classNames = ), then an error complains that __classNames is a read-only property. (TypeError: Cannot assign to read only property '__classNames' of object '#<CustomLinkNode>':
![image](https://user-images.githubusercontent.com/86361434/220989287-d1bfab02-af86-4d88-a891-3e7cd5b90278.png))

**Comment by milaabl** [comment]
@acywatson , could you please have a look?

**Comment by acywatson** [comment]
Code sandbox link doesn't work

**Comment by milaabl** [comment]
@acywatson , can I invite you to the repo as a collaborator? The repo is public, but for some reason codesandbox says that:
![image](https://user-images.githubusercontent.com/86361434/221025353-5b8cc859-3b73-40fd-a926-8e1ee3565cca.png)

**Comment by milaabl** [comment]
I've invited you right now, please accept the invitation and you should be able to see the Codesandbox project running

**Comment by milaabl** [comment]
@acywatson , does this link work for you now? https://codesandbox.io/p/github/milaabl/lexiclal--issue-getwritable/draft/admiring-wing?workspaceId=8ff52f1b-6192-4939-821f-c36ea37473d7&workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clehdty5i0011356if4hqoqzc%2522%253A%257B%2522key%2522%253A%2522clehdty5i0011356if4hqoqzc%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cleheao0k00hd356igk5r6c2y%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cleheam9g00e1356imiaux9yo%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clehdty5i0011356if4hqoqzc%2522%252C%2522spacesOrder%2522%253A%255B%2522clehdty5i0011356if4hqoqzc%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

**Comment by milaabl** [comment]
* admiring-wing is for the getWritable and function undefined issue and festive-stallman is for the clone method "Node doesn't exist in the active editor" issue

**Comment by milaabl** [comment]
On the festive-stallman sandbox please open the page called /localhost

**Comment by acywatson** [comment]
I'm 99.9% certain this an issue with how you've set up this subclass. If you can create a codesandbox with a minimal repro, I'll look, otherwise I can't spend more time on this.
