### ISSUE TITLE
Bug: typing a #hashtag at the end of a line in a new style inserts keystrokes in wrong order

### ISSUE THREAD

**Issue by isaacw-science** [facebook/lexical#3965]
Lexical version: live, at https://playground.lexical.dev/

## Steps To Reproduce

1. Open https://playground.lexical.dev/
2. Place cursor at end of a non-heading text line, e.g. `Try typing in some text with different formats.<cursor>`
3. Select a style, such as Bold, or change the font
4. Type the key sequence `#hashtag`

## The current behavior
Result: `#hshtaga`
The editor goes `#<cursor>`, `#h<cursor>`, **`#h<cursor>a`**, `#h<cursor>sa`, ... `#hshtag<cursor>a`
![Screenshot 2023-02-23 at 10 17 30 AM](https://user-images.githubusercontent.com/117307209/220995567-9951e2e1-5da7-4a3a-9d26-343f4a36dd3f.png)

## The expected behavior
Expected result is `#hashtag`

**Comment by acywatson** [comment]
Good one - thanks for reporting

**Comment by KhalfounMehdi** [comment]
@acywatson @fantactuka Please check PR :   https://github.com/facebook/lexical/pull/3986
