### ISSUE TITLE
Bug: If the anchor is after the focus, the selected nodes cannot be retrieved correctly

### ISSUE THREAD

**Issue by kosei28** [facebook/lexical#3973]
This issue describes the bug fixed in #3966.

Lexical version: 0.8.1

## Steps To Reproduce

1. Open https://playground.lexical.dev/
2. Delete all entered text
3. Enter multiple lines of text after an empty line; Use Shift+Enter to break lines or turn off rich text to avoid separating paragraphs
4. Select from the middle of the text to the top

## The current behavior
You can see in the Debug view that the getNodes method of RangeSelection retrieves completely different nodes from the selected range.

The anchor is after the focus and the selected nodes cannot be retrieved correctly.
![image](https://user-images.githubusercontent.com/104847600/221181953-28064519-1baa-4e5b-a753-dade724a185b.png)

If the selection is made from top to bottom and the anchor is before the focus, the selected nodes can be retrieved correctly.
![image](https://user-images.githubusercontent.com/104847600/221182781-62e13445-1d9e-4cf7-b0b4-187e9c57968c.png)

The getNodes method does not take into account the possibility that the anchor may be after the focus at all, so it may not get the selected nodes correctly, even outside of the case shown here.

## The expected behavior
It is expected that the selected nodes will be retrieved correctly regardless of whether the anchor is before or after the focus.
In both cases, the nodes retrieved should be the same.

**Comment by wingedrasengan927** [comment]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/34920015/221433537-997b2b95-0db5-4135-a205-d20b062ca4c8.png">
It's working fine for me even if the selection is backwards

**Comment by kosei28** [comment]
@wingedrasengan927 
This is because the first empty line is in a different paragraph than the lines that follow.
Try all lines as one paragraph.
