### ISSUE TITLE
Bug: Lexical Table Plugin input type number in Modal for number of Rows and Columns get the editor unusable until we click outside of it.

### ISSUE THREAD

**Issue by Neelakandan** [facebook/lexical#3981]
Lexical version: Latest Version or previous versions 

## Steps To Reproduce

1. Change the Input type from text to number in the modal to insert rows or columns.
2. Insert a Table with any number of rows or columns.
3. Click on the up arrow in input type number , its incrementing recursively or decrement based on the arrow event until we click outside of it and its hanged.
4. This can be reproduced in lexical playground as well.

Link to code example:

## The current behavior
1. After creation of Table first time , click on the input type number (by either keyboard Up or Down Arrow or Mouse Event Click Up or Down) the number increment or decrement continously firing until we click outside of it.

## The expected behavior
Input type number should only increment or decrement by 1 or more based on user event not automatically.

**Comment by thegreatercurve** [comment]
I can't repro any issues with this input. It's just a simple React component with some basic local state. Either way, there's not much we need to do. The input works fine as a text `input`.

**Comment by yingning-00** [comment]
I am having the same problem where no table is rendered after I click on the insert table button.
I have to click on the placeholder first, after the cursor is displayed, then the insert table button can work.

https://user-images.githubusercontent.com/130023653/230266253-c45d7c07-5d54-46dc-a8d1-6500a96609f1.mov
