### ISSUE TITLE
Bug: editor.update is being run twice in a plugin

### ISSUE THREAD

**Issue by wingedrasengan927** [facebook/lexical#3982]
I created a test plugin which calls `editor.update` function only once. When I register this `TestPlugin` with the editor, the `editor.update` function runs twice.
Lexical version: 0.7.6

## Steps To Reproduce

1. Create a test plugin which calls `editor.update` function.
<img width="948" alt="image" src="https://user-images.githubusercontent.com/34920015/221433097-f1b16ea3-d53e-40be-9687-404d17a6792b.png">
2. Register this plugin with the editor.
<img width="926" alt="image" src="https://user-images.githubusercontent.com/34920015/221433128-cbf139a0-5c09-4d97-afdc-6164d5262f6a.png">

Link to code example: https://codesandbox.io/s/lexical-plain-text-example-forked-ei7x9g?file=/src/Editor.js

## The current behavior
<img width="651" alt="image" src="https://user-images.githubusercontent.com/34920015/221432759-3d67772f-9189-468b-817d-def576c9b1ec.png">

## The expected behavior
<img width="659" alt="image" src="https://user-images.githubusercontent.com/34920015/221432777-f2fa92be-5c8a-433c-b253-7f251a8e13fa.png">

**Comment by acywatson** [comment]
Does this still happen if you disabled React Strict Mode?

https://beta.reactjs.org/reference/react/StrictMode

**Comment by wingedrasengan927** [comment]
> Does this still happen if you disabled React Strict Mode?
> 
> https://beta.reactjs.org/reference/react/StrictMode

It doesn't happen. Thanks a lot @acywatson. Closing the issue.
