### ISSUE TITLE
Bug: Line height does not accurately match font size when paragraph is empty and when font size is less then 15px

### ISSUE THREAD

**Issue by TheSwilliam** [facebook/lexical#3992]
Lexical version: 0.8.1

## Steps To Reproduce

**First problem**: Make all of the text in a paragraph have a font size smaller than 15px.
**Second problem**: Set the font size on an empty paragraph element

## The current behavior

https://user-images.githubusercontent.com/69976884/221610254-136a9fdc-a759-403f-aa26-681d31b53f13.mov

## The expected behavior

https://user-images.githubusercontent.com/69976884/221610622-3516fe28-18c3-4458-a695-0212c5553913.mov

**Comment by thegreatercurve** [comment]
There's not much we can do about this. This is just how the default browser cursor works in a `contenteditable`. Editors like GDocs have their own stylized cursor, so aren't dependent on browser behaviour.
