### ISSUE TITLE
Feature: Adding the ability to set line height on ElementNodes(Paragraph, List, Heading)

### ISSUE THREAD

**Issue by TheSwilliam** [facebook/lexical#3993]
Setting line height is very common in all text editors and I think making it easily settable within lexical would be beneficial. Currently there is not a clean way to achieve the desired behavior. 

This is an example within google docs

https://user-images.githubusercontent.com/69976884/221614006-2723041e-2b22-49a3-8264-3dbccafdc1f5.mov

**Comment by thegreatercurve** [comment]
You can add this value to an `ElementNode` via the node replacement API, but I don't know if it's common enough of a use case that we want to add it to core.
