### ISSUE TITLE
Bug: Editing text in child editor does not trigger update in parent editor

### ISSUE THREAD

**Issue by fpetterlate** [facebook/lexical#3995]
Im using your ImageNode and ImageComponent from your Playground. The main difference is that my root editor is not editable, 
while the editor in ImageComponent are.

Lexical version: 0.8.0

## The current behavior
I have a button that when clicked I want to export the full HTML from the whole editor. My problem is that when I try to use $generateHtmlFromNodes(mainEditor, null) it does not get the latest version of the editorState. The state in the main editor is not updated when the children editor editorState change. I have found  that if I click the main editor the editorState is updated as It gets focus. 

## The expected behavior
When child editors editorState change I also want the main editors editorState to be updated. I also want the listeners to fire on the main editor.

**Comment by thegreatercurve** [comment]
Thanks for the report @fpetterlate!

Unfortunately, I think it's a bug that we're allowing your editor to get into the state where the parent composer can be uneditable but the nested composers are editable. We've debated this issue in the past, and we want to avoid Lexical serving as a layout engine with a disabled parent editor and then have multiple nested composers with fixed positions. 

It opens up the potential for many unforeseen bugs, and this can be the basic job of HTML.
