### ISSUE TITLE
Feature: Drag and drop multiple blocks

### ISSUE THREAD

**Issue by errmayank** [facebook/lexical#3996]
I can't find it anywhere in the docs the ability to drag and drop multiple blocks at the same time, so i'm assuming it's not possible right now? 🤔

One more thing, the text selection seems to be buggy if multiple blocks are selected when dragging them

![drag_and_drop_multiple_blocks](https://user-images.githubusercontent.com/64462998/221869563-aa4eb35e-369e-4f1b-ae09-5f104c0fe132.gif)

**Comment by thegreatercurve** [comment]
We're unlikely to add this to the playground. It doesn't serve much of an illustrative purpose.
