### ISSUE TITLE
Bug: ToolbarPlugin not working on a react modal

### ISSUE THREAD

**Issue by SohelKabir** [facebook/lexical#4008]
Lexical version: 0.8.0

## Steps To Reproduce

1. Render the text editor on top of a modal.

Link to code example:

## The current behavior 
when i tried to render the text editor with toolbar plugin on top of a modal and try to format the text with block option by clicking "Normal" the modal dropdown wasn't showing, so i fixed the issue by adding a z-index to "dropdown" class in ToolbarPlugin it was rendering on top of the modal. But 
the menus in drop down list is not working anymore. When i click on each menu for example "Small Heading" it doesn't format texts i selected in editor. 
But this editor component I'm rendering on top of a modal, if I render same component in a regular component instead of a modal everything works perfectly. 

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/33397287/222131619-030c0e69-01a1-4a2a-b02d-9a3cd76144db.png">

**Comment by thegreatercurve** [comment]
I'm not sure about this one. We don't support the tool bar plugin out-of-the-box. Maybe the element with the higher `z-index` is intercepting the click event, instead of the dropdown item instead? 

Closing as this isn't specific to Lexical core.
