### ISSUE TITLE
Bug: Mentions in LexicalMention Plugin are changable with cursor insertions in between

### ISSUE THREAD

**Issue by InfamousBolt** [facebook/lexical#4019]
Lexical version: 0.5.0

## Steps To Reproduce

1. Mention any user using the mention plugin provided on Github or CodeSandBox
2. You will find that you can insert your cursor in between the mentioned names and change the name which ideally should not happen.

Link to code example: https://codesandbox.io/s/lexical-mention-plugin-example-ojn42n

## The current behavior

https://user-images.githubusercontent.com/47386839/222651746-1a80abc1-aeb5-4a03-b593-d42b8d01eefa.mp4

## The expected behavior

https://user-images.githubusercontent.com/47386839/222651938-a8f4d414-07f1-456f-81af-d59932b2a074.mp4

(Mentioned users should not be clickable hence changeable)

**Comment by thegreatercurve** [comment]
This is by design. If you set the below on your MentionNode though it will work as intended: 
```js
  isToken(): true {
    return true;
  }
```

**Comment by ankitsharma-99** [comment]
@thegreatercurve shouldn't the highlight disappear when any word of the entire name is deleted? Eg, "Tim Murphy". If "Tim" is removed , shouldn't the highlight go off from "Murphy" as well?
