### ISSUE TITLE
Bug: Using ListItemNode results in error "Cannot call set() on frozen node map..."

### ISSUE THREAD

**Issue by rferreira98** [facebook/lexical#4021]
I'm importing a word document with another package and parsing it to meet lexical format. After parsing a document with lists and matching these with ListNodes and ListItemNodes I'm left with an error when trying to open the editor.

Stack Trace:

> Lexical Error:  Error: Cannot call set() on a frozen Lexical node map
>     at nodeMap.set (Lexical.dev.js:5426:1)
>     at ListItemNode.getWritable (Lexical.dev.js:6241:1)
>     at ListItemNode.setValue (LexicalList.dev.js:659:1)
>     at updateChildrenListItemValue (LexicalList.dev.js:279:1)
>     at ListItemNode.createDOM (LexicalList.dev.js:473:1)
>     at createNode (Lexical.dev.js:1687:1)
>     at createChildren (Lexical.dev.js:1769:1)
>     at createChildrenWithDirection (Lexical.dev.js:1760:1)
>     at createNode (Lexical.dev.js:1707:1)
>     at createChildren (Lexical.dev.js:1769:1)
> 

This is my editorConfig
Lexical version: 0.8.0

## Steps To Reproduce

1. Generate editor state from createEditor > getEditorState() > toJson()
2. Use on new LexicalComposer config

Link to code example:

https://codesandbox.io/s/lexical-list-plugin-example-error-forked-0w7u9l

## The current behavior
Genrating editor state with "createEditor" resolves in error when using lists.

## The expected behavior
To work.

Notes:

Noticed some differences on the generated json by "createEditor" vs creating root on "editorstate" option.

ListItemNodes have same value on property "value".

Example JSON:

> {
    "root": {
      "children": [
        {
          "children": [
            {
              "children": [
                {
                  "detail": 0,
                  "format": 0,
                  "mode": "normal",
                  "style": "styleName: List Paragraph;",
                  "text": "One item list",
                  "type": "text",
                  "version": 1
                }
              ],
              "direction": null,
              "format": "",
              "indent": 0,
              "type": "listitem",
              "version": 1,
              "value": 1
            },
            {
              "children": [
                {
                  "detail": 0,
                  "format": 0,
                  "mode": "normal",
                  "style": "styleName: List Paragraph;",
                  "text": "2",
                  "type": "text",
                  "version": 1
                }
              ],
              "direction": null,
              "format": "",
              "indent": 0,
              "type": "listitem",
              "version": 1,
              "value": 1
            }
          ],
          "direction": null,
          "format": "",
          "indent": 0,
          "type": "list",
          "version": 1,
          "listType": "number",
          "start": 1,
          "tag": "ol"
        }
      ],
      "direction": null,
      "format": "",
      "indent": 0,
      "type": "root",
      "version": 1
    }
  }

**Comment by acywatson** [comment]
Here's a working codesandbox:

https://codesandbox.io/s/lexical-list-plugin-example-error-forked-4nxwsm?file=/src/Editor.js

The problem is that createEditor does not support passing a stringified EditorState. LexicalComposer API does accept that and contains logic to parse the string into an EditorState object before passing it to createEditor.

https://lexical.dev/docs/api/modules/lexical#createeditorargs
