### ISSUE TITLE
Bug: copy paste an image from browser doesn't work on iOS

### ISSUE THREAD

**Issue by andreaSimonePorceddu** [facebook/lexical#4043]
If I try to copy an Image from safari(iOS) and then want to paste this image on the lexical editor, it doesn't work as expected. 
The action doesn't produce any feedback, and the image is not pasted.

Lexical version: 0.8.1

## Steps To Reproduce

1. Copy an image from the Safari browser(iOS)
2. Paste the image on a lexical editor (I'm using the lexical playground)

Link to code example:

It can be tested on the lexical playground: https://playground.lexical.dev/

## The current behaviour

The image isn't pasted.
https://user-images.githubusercontent.com/55460313/223376540-88e9167b-ab8b-4740-9879-692711b1721c.mp4

## The expected behaviour
The image should be pasted

**Comment by thegreatercurve** [comment]
This is an issue with Google Photos Search that they probably need to fix. The behaviour works as expected with other types of images copied from other sources in Safari. I think Google don't allow you to add images directly to the paste board from Photos Search for copywrite reasons.
