### ISSUE TITLE
Bug: TS Check failed with Error TS1005 parcing @lexical/code/CodeHighlightNode.d.ts

### ISSUE THREAD

**Issue by Quaaani** [facebook/lexical#4050]
Hello guys!

First of all, thank you for such a nice library, you did a great job!

My report based on TS Check with @lexical/code/CodeHighlightNode.d.ts file
The problem is with import syntax where you use "import {type ...} from '...'" instead of "import type {...} from '...'"

Is there a chance that you can change the import syntax to this:
`
import {TextNode, ElementNode } from 'lexical'
`
`
import type {EditorConfig, LexicalNode, NodeKey, SerializedTextNode, Spread} from 'lexical'
`

If there are any other solutions, I would love to take an advice from you guys

Thank you,
Azamat

**Comment by thegreatercurve** [comment]
Hey @Quaaani! Thanks for the report. I'm not sure about the bug, but it's an easy inconsequential change to make (attached). I think it's just an auto- formatting reason that we use that nested syntax.
