### ISSUE TITLE
Bug: When a conservative Content Security Policy is set, copy/paste from rich text sources in Chrome loses formatting (or ends up with weird formatting)

### ISSUE THREAD

**Issue by dps-stripe** [facebook/lexical#4051]
I'm using lexical in a context where we want to set as restrictive a content security policy as possible. Without a `style-src` CSP including `unsafe-inline`, pasting rich text content (e.g. from Google Docs) into a lexical editor in Chrome loses formatting due to CSP violations. The only workaround I have found is to use a `style-src: unsafe-inline` CSP config, but that means my application is now vulnerable to malicious inline style attacks.

Lexical version: 0.7.7
Chrome version: 110.0.5481.177 (Official Build) (arm64) 

Lexical [clipboard handling](https://github.com/facebook/lexical/blob/main/packages/lexical-clipboard/src/clipboard.ts#L120) for rich text works by parsing HTML on the clipboard using a web API `DOMParser` object.

Since Chrome version 86.0.4240.193, Chromium applies the parent document's Content Security Policy to stuff being processed with DOMParser. Per this [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1148221), it appears that this functionality was introduced into Chromium by mistake in 2020, but it has not been fixed (or confirmed as intended behavior) since then. Firefox appears to consider this intended behavior however, so it seems unlikely the Chromium issue will be prioritized and it would be desirable for lexical to fix.

## Steps To Reproduce

1. Set a restrictive Content Security Policy on the page a rich text lexical editor is rendered on (e.g. `style-src: self` only)
2. Copy text with rich text formatting from Google Docs
3. Paste into lexical editor and observe:
(i) formatting is lost or mangled
(ii) several CSP violation errors have appeared in the Javascript console

Here are some example errors:
```
LexicalClipboard.dev.js:79 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' ...". Either the 'unsafe-inline' keyword, a hash ('sha256-hyojjHuWfbXbsAwKgSlnD+VOEXbede2xjvPsvi01uIg='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

$insertDataTransferForRichText @ LexicalClipboard.dev.js:79
editor.update.tag @ LexicalRichText.dev.js:333
processNestedUpdates @ Lexical.dev.js:6465
beginUpdate @ Lexical.dev.js:6527
updateEditor @ Lexical.dev.js:6620
update @ Lexical.dev.js:9834
triggerCommandListeners @ Lexical.dev.js:6370
dispatchCommand @ Lexical.dev.js:1274
eventHandler @ Lexical.dev.js:3243
```

## The current behavior
- Formatting is lost, or if any bold text is present, all pasted content is bold and other formatting is lost.
## The expected behavior
- Paste from a rich text source like Google Docs preserves formatting

**Comment by thegreatercurve** [comment]
@dps-stripe Thanks for the comprehensive bug report! 

If you're encountering this bug when we call `DOMParser`, which seems to be the case, this is probably more of a bug with Google Docs that they need to fix. It adds a load of inline styles to the pasteboard when you copy: 
```
<meta charset='utf-8'><meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-aae1df68-7fff-ecb7-e55e-4f44422697ed"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Hello world</span></p></b><br class="Apple-interchange-newline">
```
From the Lexical side, we don't want to try to write a less secure version of `DOMParser` to compensate for the above.

We do apply some inline styles though ourselves especially for Google Docs cases ([here](https://github.com/facebook/lexical/blob/main/packages/lexical-rich-text/src/index.ts#L340)). If you disable that do the errors disappear?

**Comment by thegreatercurve** [comment]
Closing this as I don't think there's much we can do from our side. This seems to be more of an issue with GDocs
