### ISSUE TITLE
Bug: Pushing enter multiple times in markdown view jumps out of the code element

### ISSUE THREAD

**Issue by r1chm8** [facebook/lexical#4054]
Lexical version: 0.8.1

## Steps To Reproduce

1. Go to the [playground](https://playground.lexical.dev/)
2. Click markdown view
3. Click at the end of the content
4. Push the Enter button 3 times
5. You're now outside of the `code` element, any content added here will be lost when you go back to the richeditor view

[Screencast from 08-03-23 11:10:15.webm](https://user-images.githubusercontent.com/25925437/223700944-261d339b-45f3-4a66-b3f5-54a4b90d76f7.webm)

## The current behavior
You can navigate outside of the markdown code element

## The expected behavior
You should not be able to navigate outside of the markdown code element, or add content.

**Comment by thegreatercurve** [comment]
This is intended behaviour to be able to escape the CodeBlock. Use SHIFT+Enter instead.

**Comment by r1chm8** [comment]
I understand the use case when in the richtext view, however I'm not sure why you'd want this behaviour while in the markdown view, is there something I'm not seeing here?

**Comment by themagickoala** [comment]
@thegreatercurve I second this, why would you want to break out of the code block when the code block _is_ the input field?

**Comment by thegreatercurve** [comment]
> I understand the use case when in the richtext view, however I'm not sure why you'd want this behaviour while in the markdown view, is there something I'm not seeing here?

There isn't an exclusively markdown view. That button just takes the existing editor state and converts it to markdown in a CodeBlock. The editor should still function as an actual rich text editor.
