### ISSUE TITLE
Bug: EditorState is corrupted in next.js

### ISSUE THREAD

**Issue by soosap** [facebook/lexical#4055]
I have developed a very simple editor for which I am trying to set the initial state. I am running the same experiment in both, a Create-React-App (CRA) and in a Create-Next-App (NextJS) environment.

I should also note, that it is not directly a next.js problem. If you create a new next.js project and set things up there it works. I have a standalone CRA + storybook based component library. Everything works in there. But as soon as I package it up and import the editor in a NextJS environment, that's where I see this corrupted Lexical Editor State.

i.e. `import { MyEditor } from '@mycompany/molecules'`

![CleanShot 2023-03-08 at 13 46 12@2x](https://user-images.githubusercontent.com/7187705/223717141-329dac21-2104-404d-b240-2ba76782e944.png)

The component that works perfectly in the CRA environment, throws an error on the NextJS environment.

![CleanShot 2023-03-08 at 13 49 14@2x](https://user-images.githubusercontent.com/7187705/223717822-bc5e3c9a-2a78-47aa-bfbf-f07ced8258f6.png)

![CleanShot 2023-03-08 at 14 03 19@2x](https://user-images.githubusercontent.com/7187705/223720429-165ef14a-9135-442d-a0eb-7a41e48f91a8.png)

Lexical version: 0.8.1

## Steps To Reproduce

Not that easy to reproduce, but ask me what I should try, I will do and post a screenshot in here. In case you still want to here's how to reproduce

1. npx create-react-app molecules && cd molecules
2. Create a simple editor component where you pass the initialEditorState as a function to the editorConfig
3. You will observe that the initialEditorState function executes successfully in the CRA environment
4. You are happy with the editor and want to make it available to your other apps. So you build (with rollup) and publish the component library to a npm registry.
5. You then import the editor in your other projects and try to render your editor with an initialEditorState function i.e. `<MyEditor initialEditorState={initialEditorState} />`
6. Error message "Unable to find active editor state" will be thrown

## The expected behavior

The first and second screenshot should look identical. Instead in the second screenshot I am left with a somewhat corrupted editor state.

**Comment by acywatson** [comment]
Also what is the initialEditorState you're passing in?

**Comment by soosap** [comment]
@acywatson here is my `initialEditorState` function. This is actually working if I render this component in my local storybook environment. Only after packaging and importing into a next.js app I get this corrupted editor state. Will try to set up a reproduction repo.

<img width="726" alt="CleanShot 2023-03-08 at 21 55 16@2x" src="https://user-images.githubusercontent.com/7187705/223847694-35cd6ee8-0034-457d-90f1-6ad0d12b9ad5.png">

The `initialEditorState` function is directly passed to `editorConfig.editorState` like so.

<img width="469" alt="CleanShot 2023-03-08 at 21 59 40@2x" src="https://user-images.githubusercontent.com/7187705/223848588-a845fef2-db6d-4396-a394-2de39336694f.png">

**Comment by acywatson** [comment]
I don't think this has anything to do with editor state being corrupted. Somehow that initialEditorState function is not being invoked in an editor.update callback.

As a quick test, try just taking that editor that gets passed into initialEditorState and calling update on it, then doing the rest of your logic. What are you doing with initialEditorState inside of EditorVivaldi component?

**Comment by soosap** [comment]
Ok I was able to setup a reproduction repo. I am not doing much in **initialEditorState** yet, because I can't get it running in the first place. But my goal is to prepopulate the editor exactly like in the [Lexical Playground](https://playground.lexical.dev/). The error persists whether or not the **initialEditorState** logic is put inside `editor.update(() => { // here })`. And just to be clear, in the Lexical Playground too, the logic is directly placed inside the initialEditorState function.

![CleanShot 2023-03-10 at 01 10 06@2x](https://user-images.githubusercontent.com/7187705/224189663-cef72ecf-676a-4b9e-b06a-24bdc6280baa.png)


This is the repo with the error message! Inside this next.js app I am trying to import and render MyEditor.
https://codesandbox.io/p/sandbox/amazing-bohr-3k6s80?file=%2Fsrc%2Fpages%2Findex.tsx
https://github.com/soosap/my-app

This is the link to the repo of my custom lexical editor that is packaged up using rollup.
https://codesandbox.io/s/github/soosap/my-editor?file=/src/components/MyEditor/MyEditor.tsx
https://github.com/soosap/my-editor

**Comment by acywatson** [comment]
> And just to be clear, in the Lexical Playground too, the logic is directly placed inside the initialEditorState function.

Right, but that's because that function is called inside an editor.update in the implementation of LexicalComposer. I couldn't tell if that's also happening in "MyEditor", because I couldn't see the implementation of that component.

**Comment by soosap** [comment]
@acywatson oh okay now I understand, sorry. Yes that’s right, the logic is called inside an editor.update environment. It’s passed directly to **editorConfig.editorState**.

**Comment by acywatson** [comment]
Well, one thing that might be an issue is that lexical is a dependency of my-editor, but not of my-app. It should probably be a peerDependency of my-editor and a dependency of my-app. I'm not sure this is the issue, but this doesn't sound like a Lexical-specific problem so far.

**Comment by soosap** [comment]
Hi @acywatson, I can't believe it - you were right :D The missing peer dependency was the problem here. Lesson learned! Thanks for the pointers.
