### ISSUE TITLE
Edit link modal is shown when the selection spans further than the link

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#4064]
https://user-images.githubusercontent.com/193447/223874604-c9c4612e-6685-4422-b851-275d370ac1bf.mov

Possible solutions:
1. Fix the logic around the trigger so that it only triggers when the selection is fully contained within the link
2. Disable link edit on non-collapsed selection

**Comment by ArslanYM** [comment]
Can I work on this issue?

**Comment by ArslanYM** [comment]
Is this issue still open?

**Comment by moy2010** [comment]
> Is this issue still open?

If you follow the merged pull request mentioned above, you will see that this has been fixed. This issue should be closed.

**Comment by renato** [comment]
> If you follow the merged pull request mentioned above, you will see that this has been fixed. This issue should be closed.

I don't think that's the case, this issue was created from something noticed while reviewing that PR, which addressed something else.

**Comment by zurfyx** [comment]
> I don't think that's the case, this issue was created from something noticed while reviewing that PR, which addressed something else.

This is correct. The issue still persists
