### ISSUE TITLE
Bug: Styles on selection are not maintained when coming back to an empty paragraph

### ISSUE THREAD

**Issue by TheSwilliam** [facebook/lexical#4066]
Lexical version: 0.8.2

## Steps To Reproduce

1. style some text within a paragraph
2. delete the text but leave the empty paragraph
3. move the selector to a different paragraph and then come back to the empty paragraph

## The current behavior

https://user-images.githubusercontent.com/69976884/223877619-44222cae-ac2e-4c70-a324-c1b1ace2499d.mov

## The expected behavior
Google Docs and Word handle this correctly

https://user-images.githubusercontent.com/69976884/223877641-92b30278-8d9e-4121-a881-26f61bc6fd4b.mov

**Comment by thegreatercurve** [comment]
There's not really a way around this as you're effectively deleting the text node with all of it's formatting data. I think the current behaviour is fine though and it's consistent with other similar editors like ProseMirror and Quill.
