### ISSUE TITLE
Bug: InsertNode from html error: topLevelElement is root node

### ISSUE THREAD

**Issue by Deuscx** [facebook/lexical#4085]
Lexical version: 0.8.1

## Steps To Reproduce

1.insert html
the simple html is ok
```html
<p class="PlaygroundEditorTheme__paragraph" dir="ltr"><span>a</span></p><p class="PlaygroundEditorTheme__paragraph" dir="ltr"><br></p>
```

but complex html like this will throw error
```html
<p class="PlaygroundEditorTheme__paragraph" dir="ltr"><span>a</span></p><p class="PlaygroundEditorTheme__paragraph" dir="ltr"><span>as</span></p><p class="PlaygroundEditorTheme__paragraph"><br></p><code class="PlaygroundEditorTheme__code" spellcheck="false" data-highlight-language="javascript"><span>asd</span></code><p class="PlaygroundEditorTheme__paragraph"><br></p><p class="PlaygroundEditorTheme__paragraph" dir="ltr"><span>abc</span></p>
```
2.Import from demo https://lexical.dev/docs/concepts/serialization#html---lexical
```ts
import {$generateNodesFromDOM} from '@lexical/html';

editor.update(() => {
  // In the browser you can use the native DOMParser API to parse the HTML string.
  const parser = new DOMParser();
  const dom = parser.parseFromString(htmlString, textHtmlMimeType);

  // Once you have the DOM instance it's easy to generate LexicalNodes.
  const nodes = $generateNodesFromDOM(editor, dom);

  // Select the root
  $getRoot().select();

  // Insert them at a selection.
  $insertNodes(nodes);
});
```

Link to code example:

## The current behavior
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/48537979/224204778-fac0d6d0-11b1-4676-be52-8a47b8ae5d74.png">

**Comment by milaabl** [comment]
If you add <br /> instead of <br>, does it work?

**Comment by milaabl** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code

**Comment by Deuscx** [comment]
this `<code></code>` is generated by `$generateHtmlFromNodes` api, is it able to generate by ParagraphNode .

**Comment by Deuscx** [comment]
> If you add `<br />` instead of `<br>`, does it work?

@milaabl  i made a playground for test this case. https://codesandbox.io/s/infallible-tess-1dpk2y?file=/src/plugins/ExportPlugin.js , the `<br>` is ok for generateNodesFromDOM. but `<code></code>` is not allowed

**Comment by Deuscx** [comment]
sry . I try this new version again,  it's ok now. but i found that the `$generateNodesFromDOM` will lost attribute.

## before
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/48537979/224875474-6b6815cb-4cbd-40de-a89e-236dcb3aeb93.png">

```html
<code class="PlaygroundEditorTheme__code" spellcheck="false" data-highlight-language="javascript"><span>code</span></code>
```
## after
<img width="974" alt="image" src="https://user-images.githubusercontent.com/48537979/224876032-69dca854-54c1-42b5-bf76-fe0ccd9f1cc7.png">

```html
<p class="PlaygroundEditorTheme__paragraph PlaygroundEditorTheme__ltr" dir="ltr"><code data-lexical-text="true"><span class="PlaygroundEditorTheme__textCode">code</span></code></p>
```
`code` element will change to `p` element

**Comment by FirstWhack** [comment]
At it's very root, is this not the same as #2452 and #3042? 

It appears the commonality is that Lexical would produce a faithful (or even somewhat similar) representation of the provided `dom`, but it does not.

**Comment by FirstWhack** [comment]
I'm going to stop tagging the relevant issues for fear of generating spam. They are many.

**Comment by acywatson** [comment]
> It appears the commonality is the expectation that Lexical would produce a faithful (or even somewhat similar) representation of the provided dom

As discussed elsewhere - it totally will, if you configure it to do so.  There's a conversion happening between HTML and editor state - Lexical doesn't just render exactly the HTML you pass in. It has to be told how to convert that HTML to nodes and properties on those nodes.

**Comment by acywatson** [comment]
I'm not sure what else we can do here - I don't see a problem that can't be solved with proper configuration.  If you want the exact HTML that Lexical produces in the browser, you can just take the innerHtml property of the contentEditable root. But don't expect that to produce the exact same Lexical state you had when you pass it into $generateNodesFromDOM, as the translation between those two formats is lossy.

**Comment by FirstWhack** [comment]
> I'm not sure what else we can do here - I don't see a problem that can't be solved with proper configuration. If you want the exact HTML that Lexical produces in the browser, you can just take the innerHtml property of the contentEditable root. But don't expect that to produce the exact same Lexical state you had when you pass it into $generateNodesFromDOM, as the translation between those two formats is lossy.

I think the scenario some folks are looking for is the ability to take the innerHTML, save it, and then bring it back into Lexical. Essentially using HTML as the source of truth rather than the EditorState. You've explained quite well how this IS possible but is not something provided by Lexicay. Thanks anywatson!
