### ISSUE TITLE
Bug: Equation copy and paste behaviour in edit mode is incorrect 

### ISSUE THREAD

**Issue by FlatMapIO** [facebook/lexical#4086]
Lexical version: 0.9.0

## Steps To Reproduce

1. Insert Equation, input "x = 1"
2. Double click Node, Enter Edit mode
3. Mouse select all content, COPY, PASTE-PASTE--PASTE

https://user-images.githubusercontent.com/1720349/224213686-9228ae38-33f0-4740-8c02-5b7cd5ae7d7e.mov

Link to code example: https://playground.lexical.dev/

## The current behavior

Content is pasted outside

## The expected behavior

Content is pasted/replaced inside

**Comment by khanakia** [comment]
I am having the same issue

https://user-images.githubusercontent.com/2174170/228886758-7def22bd-ca79-4bb1-bfb4-d6eebdefb35e.mov

**Comment by zurfyx** [comment]
Fixed by https://github.com/facebook/lexical/pull/4246
