### ISSUE TITLE
Feature: Merge Cell Functionality is missing in Table Plugin

### ISSUE THREAD

**Issue by Rajatava** [facebook/lexical#4087]
Merging 2 or more cell of a table is a very common and useful functionality which is missing in Lexical's Table plugin.

Moreover,  the rowspan and colspan attributes are not handled properly in importDom and exportDom method. so, when html content of a table, having merged cell(s), is populated inside editor, the content is manipulated wrongly.

**Comment by zurfyx** [comment]
Introduced in https://github.com/facebook/lexical/pull/4046, still very experimental and wouldn't recommend relying on it in production, plan is to have a solid cell merge feature by EOH.

**Comment by red-co** [comment]
@zurfyx 
> Introduced in #4046, still very experimental and wouldn't recommend relying on it in production, plan is to have a solid cell merge feature by EOH.

Sorry for a stupid question, but what does EOH mean?
