### ISSUE TITLE
Feature: Track changes mode

### ISSUE THREAD

**Issue by GauravGambhirr** [facebook/lexical#4088]
Hey, Please add tracking of changes like the deleted text should be shown in red color with a strike-through and add text can be shown in red color.

For Example 

![Screenshot 2023-03-10 111850](https://user-images.githubusercontent.com/51080726/224234157-126d104f-b93e-44d6-aa12-0788d356e532.png)

In the above screenshot, Text in black is already existing text. Text shown in red color with a strike-through is the text i have deleted from existing text and text shown in red color with underline is the text that has been added.

**Comment by thegreatercurve** [comment]
This seems like an interesting plugin idea, and certainly achievable with the current functionality but we've not really got much reason to add it to the playground, as it doesn't really demonstrate any new functionality beyond what is already there.

**Comment by GauravGambhirr** [comment]
@thegreatercurve can You tell me how can I achieve this with vanila js as my project is in vue. I tried changing Color with $patchStyleText like 

$patchStyleText(selection, {
        color: "#f41010",
      });

this was not working for me.
