### ISSUE TITLE
Bug: how to prepopulate text in editorconfig in lexical 0.8.0 

### ISSUE THREAD

**Issue by kelvinkaicheung** [facebook/lexical#4098]
folowing the markdown plugin example, https://codesandbox.io/s/lexical-markdown-plugin-example-4076jq?from-embed,
if you change the version of lexical to 0.8.0, there would be error.
There is no example of how to populate texts or simply display text in lexical.
I tried to getEditorState() and then display the data in another page. However, example in this implementation is lacking

Lexical version: 0.8.0

## Steps To Reproduce

1.https://codesandbox.io/s/lexical-markdown-plugin-example-4076jq?from-embed
2. change the version of lexical to 0.8.0

Link to code example:

**Comment by strdr4605** [comment]
I changed the version to 0.8.0 and it works ok
https://codesandbox.io/s/interesting-mendeleev-n0n8w5?file=%2Fsrc%2FEditor.js

<img width="1473" alt="image" src="https://user-images.githubusercontent.com/16056918/224477528-128a44c1-d855-4494-992e-bec91c7ed2ed.png">

**Comment by kelvinkaicheung** [comment]
<img width="1440" alt="Screenshot 2023-03-11 at 2 34 22 PM" src="https://user-images.githubusercontent.com/99903113/224490497-df5db57b-ac28-436b-8be4-9852f2b5719d.png">

**Comment by kelvinkaicheung** [comment]
https://codesandbox.io/s/laughing-gates-pphp7y

**Comment by acywatson** [comment]
Works on 0.9 too:

https://codesandbox.io/s/amazing-frog-j7zvch

Happy to help you with questions around initializing the editor with text on Discord, but I don't think this is a bug.

**Comment by strdr4605** [comment]
@acywatson I don't see 0.9 in releases, did the lexical team decide to drop GitHub releases in favor of changelog.md?
