### ISSUE TITLE
Bug: Text is inserted at the wrong positions when editor is set to non-editable

### ISSUE THREAD

**Issue by Systemcluster** [facebook/lexical#4102]
Repeatedly calling `$getSelection()` and then calling `insertText` or `insertParagraph()` on that selection when the editor is set to non-editable (`editor.setEditable(false)`) will insert the text and paragraphs at the wrong positions.

Lexical version: `0.9.0`

## Steps To Reproduce

Link to code example:

https://codesandbox.io/s/lexical-plain-text-example-forked-erl6oj?file=/src/Editor.js

Press `CTRL+Enter` in the editor to call the generate function. All the text will be inserted at the initial selection position, instead of the updated position at the end.

When removing `editor.setEditable(false)` at line `23`, the text is inserted at the correct position.

## The current behavior

All the text will be inserted at the start at the initial selection position, instead of the end at the updated position.

https://user-images.githubusercontent.com/2847328/224503578-bc50e55c-a68e-4fb6-b68e-74017e984c15.mp4

## The expected behavior

The text is inserted at the updated position, behaving the same as when the editor is not set to non-editable.

https://user-images.githubusercontent.com/2847328/224503634-bf7c782b-779d-40a0-9b6d-c3a186337c43.mp4

**Comment by milaabl** [comment]
I've found out the issue is inserting a text node. If you insert paragraph node with a text node inside it works perfectly fine, excpet for extra new lines.

**Comment by Systemcluster** [comment]
Is there a workaround for this? Any other way to lock the editor and prevent inputs or selection changes without setting it to non-editable?

**Comment by milaabl** [comment]
@Systemcluster , I'm not sure, haven't found time to have a closer look at the issue.

**Comment by milaabl** [comment]
Maybe try a custom paragraph node that will have a style resetting it to being inline? Not sure though. Good luck!

**Comment by milaabl** [comment]
The behavior is explainable, as you're not supposed to edit a non-editable (readonly) editor. Looking for another way to lock editing other than setEditable looks like the best option to consider

**Comment by zurfyx** [comment]
While selection does exist when the editor is non-editable (this is also true for a native `contenteditable`), you probaly shouldn't rely on it. A non-editable editable is not meant to be edited, modifications via plugins should probably not rely on this.

**Comment by Systemcluster** [comment]
I'm currently working around this by capturing and stopping certain DOM events on the root element:

```tsx
const preventInputHandler = (blocked: RefObject<boolean>, event: Event) => {
    if (!blocked.current) return
    event.stopPropagation()
    event.preventDefault()
}

const registerPreventInputPlugin = (editor: LexicalEditor, blocked: RefObject<boolean>) => {
    return mergeRegister(
        editor.registerRootListener((root, prev) => {
            const preventInput = preventInputHandler.bind(null, blocked)
            if (!root) return
            root.addEventListener('keydown', preventInput, { capture: true })
            root.addEventListener('pointerdown', preventInput, { capture: true })
            root.addEventListener('beforeinput', preventInput, { capture: true })
            root.addEventListener('input', preventInput, { capture: true })
            root.addEventListener('cut', preventInput, { capture: true })
            root.addEventListener('paste', preventInput, { capture: true })
            root.addEventListener('selectstart', preventInput, { capture: true })
            root.addEventListener('dragstart', preventInput, { capture: true })
            if (!prev) return
            prev.removeEventListener('keydown', preventInput, { capture: true })
            prev.removeEventListener('pointerdown', preventInput, { capture: true })
            prev.removeEventListener('beforeinput', preventInput, { capture: true })
            prev.removeEventListener('input', preventInput, { capture: true })
            prev.removeEventListener('cut', preventInput, { capture: true })
            prev.removeEventListener('paste', preventInput, { capture: true })
            prev.removeEventListener('selectstart', preventInput, { capture: true })
            prev.removeEventListener('dragstart', preventInput, { capture: true })
        })
    )
}

type PreventInputPluginProps = {
    blocked: RefObject<boolean>
}
const PreventInputPlugin = ({ blocked }: PreventInputPluginProps) => {
    const [editor] = useLexicalComposerContext()
    useLayoutEffect(() => {
        return registerPreventInputPlugin(editor, blocked)
    }, [editor, blocked])
    return <Fragment />
}

export default PreventInputPlugin
```

It would still be very useful to have an internal event transform/filter method available in Lexical, to allow blocking/reacting to actual editor events instead of working on DOM events that may or may not impact the editor. This workaround is also sub-optimal in that it prevents non-editor functionality, like browser events (e.g. `CTRL+R`) among others.

Another alternative I considered was overwriting `editor.dispatchCommand`, but most events directly call `dispatchCommand` in `LexicalUtils` without going through the editor method, so this isn't viable.

ProseMirror for example provides a [`dispatchTransaction`](https://prosemirror.net/docs/ref/#view.DirectEditorProps.dispatchTransaction) hook that does just that, allowing to throw away a transaction if desired. Would it be possible to add something similar to Lexical? Possibly a [listener](https://lexical.dev/docs/concepts/listeners) hooking into [`dispatchCommand`](https://github.com/facebook/lexical/blob/2bcf11bec944cd3bd69b7e7b40903e593b716a06/packages/lexical/src/LexicalUtils.ts#L1156)?

**Comment by fantactuka** [comment]
Given DOM selection is not reconciled in read mode, you'll need to move Lexical selection manually. You can also use insertRawText to handle newlines for you

https://codesandbox.io/s/lexical-plain-text-example-forked-xddp3d?file=/src/Editor.js
