### ISSUE TITLE
in Chrome extension selection is always null

### ISSUE THREAD

**Issue by Wicat21** [facebook/lexical#4110]
Hello there! 

I tried to find what could cause this issue, but unfortunately I wasn't successful. 
We develop extension with lexical, where lexical is in the content script.
The firefox extension with manifest v2 works perfectly, but chrome (with manifest 3) doesn't. 
document.getSelection and window.getSelection works perfectly, so I think it is not related to permissions regard google chrome. 
When I call root.select(), the selection is not null, but when I do anything it will always be null. 

Could you give some clues, where to continue?

Thank you in advance!

Lexical version: 0.8.1

## The current behavior
If I select a text, selection will be null always

## The expected behavior
Selection should contain the same as in firefox.

**Comment by milaabl** [comment]
Please share the full file where you try to get the selection.

**Comment by milaabl** [comment]
We need a minimal reproducible example in order to help you figure out what the issue is

**Comment by thegreatercurve** [comment]
I obviously can't verify, but to me this seems more like a Chromium bug than a Lexical issue. We had a Developer Tools web extension for a little while (before deprecating in favour of the inline tools) which successfully showed the Lexical selection (#4023).

**Comment by Wicat21** [comment]
Thank you for your comments! 
For future readers: I found out that the new manifest version causing the problem. Although the window.getSelection is not null, but is doesn't contain what it should. And it's pretty difficult to get the selection inside a chrome extension - and it requires some workaround with lexical too (I am still working on it)
