### ISSUE TITLE
Bug: The drag bar will always exist after the selected text is dragged and inserted in the windows 11

### ISSUE THREAD

**Issue by SGDS666** [facebook/lexical#4118]
Step 1 Select the text and click the selected text to drag
![image](https://user-images.githubusercontent.com/86196091/224872593-e7af4edf-24ec-4c84-b6c2-ccd417e9ee25.png)

Step 2: Put the text in another line and drag the bar will always 
![image](https://user-images.githubusercontent.com/86196091/224872622-57a35b33-54d5-4a25-bd11-b7a5d0ffd40e.png)
How to solve this problem

**Comment by Alex-Github-Account** [comment]
Hello!
Unfortunately they (@acywatson specifically) either no answer or [straight away close](https://github.com/facebook/lexical/issues/4121) the issues related to UI, even if it is about reference UI implementation right from the official docs.
I may help you but please note that there is some text was lost in your post after "Step 2: Put the text in another line and drag the bar will always (guess something was here) ".  so it hard to understand what was meant, so please correct the text

**Comment by LuciNyan** [comment]
Hi @SGDS666! Could you please record a quick video? I'm having trouble reproducing the issue on my Mac and I'm not sure if it's a Windows-only bug. Thanks!

**Comment by LuciNyan** [comment]
> Unfortunately they (@acywatson specifically) either no answer or [straight away close](https://github.com/facebook/lexical/issues/4121) the issues related to UI, even if it is about reference UI implementation right from the official docs.

Please understand that they may not be comfortable interacting with someone who engages in personal attacks (@Alex-Github-Account specifically). Let's try to keep the discussion respectful and productive. Thank you. :)

**Comment by Alex-Github-Account** [comment]
> Please understand that they may not be comfortable interacting with someone who engages in personal attacks (@Alex-Github-Account specifically). Let's try to keep the discussion respectful and productive. Thank you. :)

You imply that @acywatson is offended that when he send me to 'build you own text editor first' he got response that I've actually built, and first? thus he ditching the issues I am opening about (not even his) product? 
FYI, I don't care. I usually have bugs already fixed (in my forks) by the time I open issues about them, so I could not care less.
Note I offered help here for somehone here because I already fixed floating-panel UI bug that seems related to this. 
Thanks you for starting this interaction with me, but I don't see interest in interacting with you until it is offtopic, no offense.

**Comment by SGDS666** [comment]
> 你好@SGDS666！你能录制一个快速视频吗？我在我的 Mac 上重现该问题时遇到问题，我不确定它是否是仅限 Windows 的错误。谢谢！

I can be sure that this is a problem with Windows, because this is a problem tested by my colleague, and I also use the mac logic. The mac cannot drag the selected text after the selected text is boxed. Windows can, so it needs to be tested with Windows
