### ISSUE TITLE
Bug: Dropdown menus are not working

### ISSUE THREAD

**Issue by Alex-Github-Account** [facebook/lexical#4121]
Well, lexical is headless, but this still may be relevant.
Docs (https://github.com/facebook/lexical) provides an example 
https://codesandbox.io/s/lexical-rich-text-example-5tncvy
of rich text editor implementation
And it has a bug that prevents usage of features
The bug - proposed UI don't takes into considiration #top layer browser feature.
So if editor is inside modal dialog, dropdowns renders behind the dialog and are unaccessible:
Before dropdown click:
![image](https://user-images.githubusercontent.com/60236507/224928709-a9309b89-b607-4aa5-92e5-19b179cc82b3.png)
After dropdown click (dropdown hightlighted by browser tools -> inspect element):
![image](https://user-images.githubusercontent.com/60236507/224927678-8ed303bb-d423-49c5-a761-d2b813d5371b.png)
because dropdowns are fake and are just a div's, which cant go above #top-layer

Lexical version: latest, that one with bugs

## Steps To Reproduce

1. Put proposed by the docs rich text editor implementation in dialog, open it with .showModal() command (this way)
2. See  dropdowns not working

Link to code example:

## The current behavior
Dropdowns are made as we did it in 1995 - by creating a div with z-index

## The expected behavior
Take modern browser standards and features in consideration. Should be rendered above top-layer

**Comment by acywatson** [comment]
Lexical is not concerned with layering issues in your editor UI. This is something you'll have to fix in your implementation.

**Comment by Alex-Github-Account** [comment]
> Lexical is not concerned with layering issues in your editor UI. This is something you'll have to fix in your implementation.

That's not my UI this is a UI from official docs, the links are in the post

**Comment by Alex-Github-Account** [comment]
Nevermind, fixed within a minute and line of code. It took longer for you to write 'let docs remain misleading, not our job' than for me to track and fix issue )
