### ISSUE TITLE
Bug: Unable to override exportJSON in CustomListItemNode or importJSON in CustomListItemNode or CustomParagraphNode

### ISSUE THREAD

**Issue by TheSwilliam** [facebook/lexical#4132]
Lexical version: 0.9.0

## Steps To Reproduce

1. Create a CustomParagraphNode that extends ParagraphNode. Create a method that overrides importJSON
2. Create a CustomListItemNode that extends ListItemNode. Create a methods that override importJSON and exportJSON

## Example with Error message

**CustomParagraphNode code that causes error message when trying to override importJSON**

I think a possible fix would be to remove the type property from SerializedParagraphNode and SerializedListItemNode. This would then mirror how SerializedTextNode is.

This is the example of a CustomParagraphNode that has a compiler error on the class. The error message states: 
Class static side 'typeof CustomParagraphNode' incorrectly extends base class static side 'typeof ParagraphNode'.
  Types of property 'importJSON' are incompatible.
    Type '(serializedNode: SerializedCustomParagraphNode) => CustomParagraphNode' is not assignable to type '(serializedNode: SerializedParagraphNode) => ParagraphNode'.
      Types of parameters 'serializedNode' and 'serializedNode' are incompatible.
        Type 'SerializedParagraphNode' is not assignable to type 'SerializedCustomParagraphNode'.
          Property 'backgroundColor' is missing in type 'SerializedParagraphNode' but required in type '{ type: "custom_paragraph"; backgroundColor: string | undefined; }'.ts(2417)
CustomParagraphNode.tsx(14, 5): 'backgroundColor' is declared here.
```
import {
  DOMConversionMap,
  DOMConversionOutput,
  LexicalNode,
  ParagraphNode,
  SerializedParagraphNode,
  Spread,
} from "lexical";
import { EditorConfig, NodeKey } from "lexical";

export type SerializedCustomParagraphNode = Spread<
  {
    type: "custom_paragraph";
    backgroundColor: string | undefined;
  },
  SerializedParagraphNode
>;

export class CustomParagraphNode extends ParagraphNode {
  __backgroundColor?: string;

  constructor(backgroundColor?: string, key?: NodeKey) {
    super(key);
    this.__backgroundColor = backgroundColor;
  }

  static clone(node: CustomParagraphNode): CustomParagraphNode {
    return new CustomParagraphNode(node.__backgroundColor, node.__key);
  }

  static getType(): "custom_paragraph" {
    return "custom_paragraph";
  }

  setBackgroundColor(color?: string): this {
    const self = this.getWritable();
    self.__backgroundColor = color;
    return self;
  }

  getBackgroundColor(): string | undefined {
    const self = this.getLatest();
    return self?.__backgroundColor;
  }

  static override importJSON(serializedNode: SerializedCustomParagraphNode): CustomParagraphNode {
    console.log("importing json...");
    const node = $createCustomParagraphNode();
    node.setFormat(serializedNode.format);
    node.setIndent(serializedNode.indent);
    node.setDirection(serializedNode.direction);
    node.setBackgroundColor(serializedNode.backgroundColor);
    return node;
  }

  override exportJSON(): SerializedCustomParagraphNode {
    return {
      ...super.exportJSON(),
      type: "custom_paragraph",
      backgroundColor: this.getBackgroundColor(),
      version: 1,
    };
  }
  createDOM(config: EditorConfig): HTMLElement {
    const p = super.createDOM(config);
    if (this.__backgroundColor) p.style.cssText = `background-color: ${this.__backgroundColor}`;

    return p;
  }

  updateDOM(prevNode: CustomParagraphNode, dom: HTMLElement, config: EditorConfig): boolean {
    super.updateDOM(prevNode, dom, config);
    const prevStyle = prevNode.__backgroundColor;
    const nextStyle = this.__backgroundColor;
    if (prevStyle !== nextStyle && nextStyle) {
      dom.style.cssText = `background-color: ${nextStyle}`;
    }
    return false;
  }

  static importDOM(): DOMConversionMap | null {
    return {
      p: (node: Node) => ({
        conversion: convertCustomParagraphElement,
        priority: 0,
      }),
    };
  }
}

function convertCustomParagraphElement(): DOMConversionOutput {
  return { node: $createCustomParagraphNode() };
}
export function $isCustomParagraphNode(node: LexicalNode | null | undefined): node is CustomParagraphNode {
  return node instanceof CustomParagraphNode;
}
export function $createCustomParagraphNode(backgroundColor?: string): CustomParagraphNode {
  return new CustomParagraphNode(backgroundColor);
}
```

**CustomListItemNode exportJSON error**

The error message for importJSON is the same in both. However I think the fix for the error received when overriding exportJSON in the CustomListItemNode is to change the return type to of exportJSON to SerializedElementNode in the LexicalListItemNode. That return type would then mirror what is currently in the LexcicalParagraphNode.

**Comment by zurfyx** [comment]
Fixed by https://github.com/facebook/lexical/pull/4143
