### ISSUE TITLE
Bug: Documentation implies valid HTML can be imported to Lexical via $generateNodesFromDOM

### ISSUE THREAD

**Issue by FirstWhack** [facebook/lexical#4133]
Using the examples from the docs, very basic HTML is either not faithfully generated or entirely fails to be applied.

Lexical version: `0.9.0`

## Steps To Reproduce

1. Run the following code
2. observe missing styles
```tsx
  const initialConfig: InitialConfigType = {
    namespace: 'rich-text-editor',
    editorState: (editor) => {
      editor.update(() => {
        const sampleHTML = `
          <html>
            <body>
              <p style="font-size: 16px">My <strong>first</strong> paragraph.</p>
            </body>
          </html>`;
        const parser = new DOMParser();
        const dom = parser.parseFromString(sampleHTML, 'text/html');
        const nodes = $generateNodesFromDOM(editor, dom);

        $getRoot().select();
        $insertNodes(nodes);
      });
    },
    onError: (error) => {
      throw error;
    },
  };
```

Example 2:

1. Use this sample HTML
2. Observe fatal error from Lexical
```tsx
        const sampleHTML = `
          <html>
            <body>
              <h1 style="font-size: 16px">My <strong>first</strong> paragraph.</h1>
            </body>
          </html>`;
```

Link to code example: Inlined

## The current behavior
I am led to believe I can use Lexical as a RTE for existing HTML, and that I can output HTML to be viewed in an actual DOM.

## The expected behavior
I understand that this is not easily possible with Lexical and is not a goal of Lexical.

## Documentation Issue
I understand from the multitude of issues that this is not a goal of Lexical, however the documentation suggests this is trivial or even possible without doing a ton of heavy lifting yourself, monkey patching code and overriding Nodes.

We should clarify the examples and documentation given so many of us are reaching the same conclusion.

**Comment by acywatson** [comment]
> The second one seems like a bug

Oh this would probably work if you register HeadingNode on the editor, but we should fail gracefully without it.

**Comment by FirstWhack** [comment]
> the issue is that if you bake knowledge about stuff like font-size into the core library, then what do you do when the html is pasted into an editor that doesn't support font-size

Could you elaborate on this a bit? This is where I am having a disconnect I think. I thought Lexical's EditorState was essentially a transformation of HTML represented as JSON, but with implementation details of Lexical. I thought that the end-result of any such operation is to produce HTML (whether this be through markdown or otherwise, you are still producing HTML).

Just trying to gain a better understanding here, I think Lexical is striving to do something higher-level than I am grasping.

**Comment by FirstWhack** [comment]
Maybe worded differently... we have `$patchStyleText` which only supports valid CSS properties. Why is it that I can always safely add inline styles to a selection but I can't import HTML with attached inline styles? This confuses me as it appears we have a common language of valid CSS properties supported by certain Nodes.

**Comment by FirstWhack** [comment]
You explained this very well on the Discord. I won't paste your response here as the words aren't mine but I thought it was a very helpful explanation. There isn't really an issue here, I had some misunderstanding of what Lexical is actually for. Gonna close ✌️
