### ISSUE TITLE
Bug: $insertNodes on root selection is crashing on importing TextNodes with error Uncaught Error: insertNodes: cannot insert a non-element into a root node

### ISSUE THREAD

**Issue by Ug48** [facebook/lexical#4137]
On a lexical editor, if we try to import the HTML `<p><span class="math inline" data-type="equation" data-inline="true" data-equation="260 \mathrm{C}">260 \mathrm{C}</span></p> ` using the code given on documentation https://lexical.dev/docs/concepts/serialization (HTML -> Lexical) it crashes with
Uncaught Error: insertNodes: cannot insert a non-element into a root node
    at RangeSelection.insertNodes (Lexical.dev.js:4052:1)
    at $insertNodes (Lexical.dev.js:5186:1)
    at Editor.tsx:201:1
    at beginUpdate (Lexical.dev.js:5768:1)
    at updateEditor (Lexical.dev.js:5847:1)
    at LexicalEditor.update (Lexical.dev.js:8549:1)

Note the space between `</p>` and the end, if the space is removed, no error occurs. Also I was advised to use $insertGeneratedNodes from clipboard and it also solves the issue. Lexical $generateNodesFromDOM, returns 2 nodes on this HTML, one is paragraph node and the next one is a text node(for the remaining space) which causes the issue. Also on documentation https://lexical.dev/docs/concepts/nodes in RootNode section it mentions that lexical forbids merging TextNode into Root Nodes, so not sure if this is the expected behaviour or a bug. Seeking clarity on best way to pass initial HTML to editor.

Lexical version: 0.8.1

## Steps To Reproduce

1. On Lexical Playground just try using the editor and pass initialHTML using code form documentation as above to initialize the editor.

**Comment by acywatson** [comment]
@Ug48 this is the right way to pass initial HTML to the editor, but I think the best solution to this particular case might be to just trim it before you pass it in to get rid of that whitespace?

**Comment by acywatson** [comment]
Yea, the more I think about this, this function should just handle generating the nodes based on the raw html and importDOM logic. It can't make assumptions about where you're going to insert the content like $insertGeneratedNodes does. Trim the HTML string or wrap the lexical text nodes before you insert them (which is what $insertGeneratedNodes is doing under the hood).

**Comment by malavshah9** [comment]
@Ug48  How did you solve this issue? I am facing the same issue.
