### ISSUE TITLE
Bug: Table prevents text deselection

### ISSUE THREAD

**Issue by henrik-d** [facebook/lexical#4138]
As soon as a table is added to the rich-text-editor, the text (de)selection is bugged. 

Lexical version: 0.9.0

## Steps To Reproduce

1. Insert a table node into the editor. You can reproduce the issue in the playground (https://playground.lexical.dev/)
2. Select some text outside the table
3. Try to move the caret to a position inside the selected text. It won't work. You can only clear the selection by clicking elsewhere.

If you remove the table again, everything works as expected again.

**Comment by acywatson** [comment]
Interesting. @zurfyx could this be related to the recent tables work?
