### ISSUE TITLE
Bug: Command-A select does not work with custom decorator nodes when they are the first child

### ISSUE THREAD

**Issue by DominicSherman** [facebook/lexical#4139]
Lexical version: 0.9.0

## Steps To Reproduce

1. Insert a custom decorator node as the first content in an editor
3. Try to select all using command+a

Link to code example: https://codesandbox.io/s/lexical-plain-text-example-forked-18wzgp

Note: ^ In code example above, I've added a very basic custom node which can be added by typing `customnode`. If it is the first thing you add then add more below, you can no longer select all of the content using command+a. If you add a new line or any text prior to adding the custom node, then select works as expected.

## The current behavior

Does not select

## The expected behavior

It should select

**Comment by thegreatercurve** [comment]
I think this is likely a Chromium related issue. The above Sandbox works as expected in Firefox. 

We've found a few issues to do with  nested `contenteditable:false` elements in a `contenteditable:true`. This one could possibly related to this issue [here](https://bugs.chromium.org/p/chromium/issues/detail?id=931285), which would then cause a bug within the Lexical wrapper around the browser selection.

I've not been able to replicate a minimal replicable example for Chromium bug tracking, but the easy fix is to not extend a `DecoratorNode` for your custom node. 

Closing as this doesn't seem to be an issue with core.
