### ISSUE TITLE
Bug: Underline is not persisted in markdown

### ISSUE THREAD

**Issue by OttlikG** [facebook/lexical#4141]
The underline is not generated in the markdown format.

Lexical version: 0.9.0

## Steps To Reproduce

1. Go [here](https://codesandbox.io/s/underline-not-working-8k00le?file=/src/Editor.js):
2. Type in any text and click the underline button in the toolbar
3. See the console.log that other texet has put in a correct markup format but not underline

Link to code example:
https://codesandbox.io/s/underline-not-working-8k00le?file=/src/Editor.js

## The current behavior
Currently when I see the extracted markdown the text which was clicked to be underline is plain text.
## The expected behavior
It could generate a valid markdown like: ```<ins>text</ins>```

![Screenshot 2023-03-17 at 8 55 10](https://user-images.githubusercontent.com/2817762/225846220-5a21b4dc-87c1-4ccb-a236-d0621e86c458.png)

**Comment by thegreatercurve** [comment]
Underlines aren't part of the CommonMark spec, which we use for our markdown transformers. but the feature is [actively being discussed here](https://talk.commonmark.org/t/feature-request-underline-text/343/22).

You can define custom markdown transforms though within the plugin which should allow you to add the conversion logic for your own particular flavour of underline support within markdown. 

Closing as this isn't default markdown behaviour, but can be added via custom markdown transformers.
