### ISSUE TITLE
Bug: placeholder should not be shown for single DecoratorNode

### ISSUE THREAD

**Issue by vilic** [facebook/lexical#4145]
Lexical version: 0.9

![image](https://user-images.githubusercontent.com/970430/225981474-b634fdfc-f53b-4c6c-8106-8b1744d0e195.png)

It seems that `DecoratorNode` is not checked:

https://github.com/facebook/lexical/blob/5445f2ce45496a5305a1bd6c9df2bc8d7dfc737b/packages/lexical-text/src/index.ts#L114-L137

**Comment by HarrySIV** [comment]
Hey @vilic! I'm having trouble recreating this. Could you give some instructions on what you did?

**Comment by vilic** [comment]
Sure, two changes to the playground:

1. Comment out those to insert image at root:

https://github.com/facebook/lexical/blob/5445f2ce45496a5305a1bd6c9df2bc8d7dfc737b/packages/lexical-playground/src/plugins/ImagesPlugin/index.tsx#L225-L227

2. Make `ImageNode` non-inline by adding:

```
isInline(): boolean {
  return false;
}
```

Then in the playground:

3. Insert a sample image.
4. Delete the leading empty paragraph.
