### ISSUE TITLE
Bug: Gboard Keyboard - Deleting a character in the middle of a word deletes multiple characters

### ISSUE THREAD

**Issue by Shalken** [facebook/lexical#4149]
When deleting characters in the middle of a word, it deletes the intended character and the one to the right of the cursor. This only occurs when using the Gboard keyboard. Tested with Samsung Galaxy S20 Ultra.

Lexical version: Latest - v0.8.1

## Steps To Reproduce

1. Download Gboard from Google Play on Android device and set as primary keyboard
2. Open Chrome. 
3. Navigate to https://playground.lexical.dev/
4. Place cursor in the middle of a word
5. Press delete key

## The current behavior

Two characters are deleted. Character to the left and right of the cursor.

## The expected behavior

One character is deleted. The character to the left of the cursor.

**Comment by thegreatercurve** [comment]
This is a duplicate issues which I've investigated already and found to be a Chromium browser bug. I've logged a bug report here: https://bugs.chromium.org/p/chromium/issues/detail?id=1403455.

Closing as issue tracking should be done there.
