### ISSUE TITLE
Feature: Diff view

### ISSUE THREAD

**Issue by zignis** [facebook/lexical#4151]
Is it possible to perform diffing on two arbitrary editor states and render them on the editor, similar to how quill does it: https://codepen.io/percipient24/pen/eEBOjG ?

We can already perform diffing on the serialized editor states, but it would be better to provide internal methods to diff the editor states.

**Comment by thegreatercurve** [comment]
I think this can easily be achieved with `MarkNodes` and a ref which stores the previous editor state. I don't think there's much point in building this into the playground though, but the idea is there is someone wants to create a CodeSandbox or third-party component.

**Comment by sanuradhag** [comment]
@zignis were you able to come up with a solution for this?

**Comment by zignis** [comment]
@sanuradhag I haven’t had enough time to try it out yet.

**Comment by zignis** [comment]
> https://codepen.io/percipient24/pen/eEBOjG

We can take a naive approach by diffing the serialized JSON (editor state) and adding some markers to identify modified, added, and removed nodes. Implementing this would require quite a bit of work.

**Comment by sep2** [comment]
The serialized JSON losts nodeKeys therefore might be hard to find out the diff.

**Comment by fponticelli** [comment]
Not having IDs in the JSON increases complexity. The naive approach of diffing the two structures is still applicable but as @zignis pointed out, it would be non trivial to implement.

**Comment by ivailop7** [comment]
I've looked into this in the past. I didn't reach a nice solution. The approach I took is: convert both editorstates to the respective HTML and compare the HTMLs themselves. There are a number of libraries that already compare html, sadly mostly are old and don't support newer HTML5 tags, but easily extensible. You can then decorate the newer HTML version with your own 'CustomMarkNode' and serialize the back to json state. This makes you agnostic for nodekeys, etc. For reasonable size files, it should be OK. If you are doing a 'git diff' replica, unlikely to be a nice solution. 

The better solution is making use of Yjs own history of deltas and doing a diff that way. Yjs has an [undocument API](https://discuss.yjs.dev/t/how-to-use-y-permanentuserdata/154) that even allows you to annotate the change with a unique user id, so you can even highlight who added what. Haven't tried this myself, but there's a prosemirror demo using it. It was never formalized in the docs, but I also doubt they'll delete it.
