### ISSUE TITLE
Relatively Huge Bundle Size

### ISSUE THREAD

**Issue by quick007** [facebook/lexical#4152]
*Quick note:* I'm not entirely sure if a bug report is a correct medium for this, but here goes.

## Overview

Lexical is pretty huge. Its size of it has been growing too. As much as I really like the feature set of lexical, it **doubles** the first load js. It also increases tti and blocking time.

## Data

Here's a table of the size of my build for my nextjs website: 
![image](https://user-images.githubusercontent.com/69743171/226198251-ba5f7ff5-c34d-40d2-bbe6-dd71127779a5.png)
If it's not clear already, the ones in red, which are almost double the average page size, are the ones with lexical. 

Looking at [bundlephobia](https://bundlephobia.com/package/lexical@0.9.0), the size of the package has been increasing over time as well:
![image](https://user-images.githubusercontent.com/69743171/226198755-21dc1614-8716-43f0-969b-b98c486aaa0b.png)

## Conclusion

To be honest, I don't expect much to come from this pr. I would love it if there was some way to let go of some of the weight this seems to add.

**Comment by quick007** [comment]
Now that I look at other similar text editors, this is actually pretty good. Draftjs, lexical's predecessor, is 2.3x larger. 
![image](https://user-images.githubusercontent.com/69743171/226199038-8017a03e-db90-4b60-a9a2-452bb06d0b27.png)

**Comment by acywatson** [comment]
Yea, I think Lexical has historically been pretty competitive on this front, though I didn't realize the core has crept up to 28kb. Might be worth looking at whether or not we can reduce that.
