### ISSUE TITLE
Bug: FloatingTextFormat Toolbar ignores half of my clicks

### ISSUE THREAD

**Issue by AlessioGr** [facebook/lexical#4156]
https://user-images.githubusercontent.com/70709113/226222329-13ac52fb-6e73-48b6-833d-9556ae0a125d.mp4

This video showcases everything (my recording software shows the clicks). Can easily be reproduced in Google Chrome on the lexical playground (at the time of writing, lexical v0.9.0).

As you can see, a lot of times I click on the toolbar, and nothing happens. Anyone should be able to reproduce it by clicking on the floating toolbar more often

**Comment by acywatson** [comment]
Weird - I can't seem to repro this. Any special set up you're doing before hand? Can you consistently repro it on a fresh page load?

**Comment by AlessioGr** [comment]
> Weird - I can't seem to repro this. Any special set up you're doing before hand? Can you consistently repro it on a fresh page load?

Yep I can! Although, it is weird and happens very inconsistently. Sometimes more, sometimes less. But I can always get it to happen in the first place.

Here is a complete video from the moment I open the browser, to show that I'm not doing anything special

https://user-images.githubusercontent.com/70709113/226225113-ef0284c3-e02b-4b91-939e-3d244cc8fe16.mp4

Since it's a bit random, sometimes you need to click different buttons more often than other times for this to occur.

**Comment by HarrySIV** [comment]
It's possible it's Mac specific (using their webkit). I also could not reproduce the bug on windows using chrome, but on my iPhone I was having a similar issue, though not as pronounced. I will also add that my phone may be a bit slow updating the changes as they occur, unfortunately I don't have a mac or iPad to test it on.

**Comment by maxhelsel** [comment]
@AlessioGr @acywatson I've noticed that behavior with clicking toolbars buttons as well - the issue is the mouse listeners introduced in #4013

After removing those lines, my editor fires the button `onClick` reliably. Those mouse listeners and styles are interfering with the click event, requiring a perfect click without any mouse movement

**Comment by AlessioGr** [comment]
@maxhelsel I think that's because the
`popupCharStylesEditorRef.current.style.pointerEvents = 'none';`
gets triggered for normal clicks as well if the mouse is moved during it.

Looking into fixing this right now!

**Comment by AlessioGr** [comment]
Oh NVM, seems this was fixed by #4298 already!
