### ISSUE TITLE
Bug: Tables do not work if there are 2 or more lexical editors on one page

### ISSUE THREAD

**Issue by AlessioGr** [facebook/lexical#4157]
When there are 2 or more lexical editors on one page, the table throws a "TableCellResizer: Table cell node not found." error if you hover over it with your mouse.

Lexical version: 0.9.0

## Steps To Reproduce

1. Have 2 editors in one page (as seen in the playground of https://github.com/AlessioGr/lexical/tree/two-editors)
2. place a table and hover over it

Link to code example: https://github.com/AlessioGr/lexical/tree/two-editors

**Comment by AlessioGr** [comment]
https://github.com/AlessioGr/lexical/blob/2adbe542f79cb952acc6ff1ab1b85fd4ad0a53cf/packages/lexical-playground/src/App.tsx#L163

That's how I use 2 editors on one page. This is relevant for me, as I need to be able to have multiple fully functional lexical editors on one page, without them knowing about each other.

**Comment by Othman-dev** [comment]
Is there an answer somewhere regarding this issue, I am facing the exact same issue on my end thought updating would solve but using 12.2 (was 10.0), still issue persists.

**Comment by zawraz** [comment]
Is this issue planned to be resolved any time soon? It's quite a common use case to have multiple editors within one page in an application.

**Comment by ivailop7** [comment]
I believe this was fixed in here: https://github.com/facebook/lexical/pull/6416 can someone confirm this is no longer an issue?
