### ISSUE TITLE
Bug: `$setBlocksType` doesn't work on text node

### ISSUE THREAD

**Issue by montlebalm** [facebook/lexical#4173]
Using `$setBlocksType` while the selection contains a text node within a paragraph does not convert the paragraph into the desired type.

Lexical version: 0.9.0

## Steps To Reproduce

1. Add a "text-match" transformer to `MarkdownShortcutsPlugin` that converts the text node's parent into a different type
2. Initiate the text transformer

Link to code example: https://codesandbox.io/s/lexical-plain-text-example-forked-m5tzve?file=/src/Editor.js

## The current behavior

The text node's parent should be converted into the desired type.

## The expected behavior

The text node's parent is not converted.

**Comment by acywatson** [comment]
Hmmm - this seems more specific than the title implies. Like, setBlocksType seems to be working fine on the playground. In your sandbox, it seems like the selection is somehow on the ParagraphNode when you get it in that replacer (which causes the heuristic in setBlocksType to fail). Maybe something in the markdown transformer API? Will look more closely

**Comment by acywatson** [comment]
Pretty sure this is the issue:

https://github.com/facebook/lexical/blob/556033e636521a7aeae08bef14bca2e1d3a623d8/packages/lexical-markdown/src/MarkdownShortcuts.ts#L113

If you look at the impl of selectNext, it selects the parent when there's no sibling, which is making setBlocksType do weird things because it's not getting the selection it expects.

**Comment by Pushp1992** [comment]
Same error I am also getting

editor.jsx:28 TypeError: $setBlocksType_experimental is not a function
    at editor.jsx:58:13

I am using  `"@lexical/selection": "^0.13.1",`

<img width="632" alt="Screenshot 2024-02-28 at 3 45 27 PM" src="https://github.com/facebook/lexical/assets/16354296/0d4f87b7-15a6-471a-a52b-c10c93d7c31b">

**Comment by minjikimsafetics** [comment]
> Same error I am also getting
> 
> editor.jsx:28 TypeError: $setBlocksType_experimental is not a function at editor.jsx:58:13
> 
> I am using `"@lexical/selection": "^0.13.1",`
> 
> <img alt="Screenshot 2024-02-28 at 3 45 27 PM" width="632" src="https://private-user-images.githubusercontent.com/16354296/308509518-0d4f87b7-15a6-471a-a52b-c10c93d7c31b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzIwMTQsIm5iZiI6MTcyMTE3MTcxNCwicGF0aCI6Ii8xNjM1NDI5Ni8zMDg1MDk1MTgtMGQ0Zjg3YjctMTVhNi00NzFhLWE1MmItYzEwYzkzZDdjMzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDIzMTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YjAyYzI5YWEwZDJkZmJhYmVjYzhkYTYxNjZjMDFlM2ZlODA0ODNlMGYzMGVhZTQxZGI2NjE5Y2VmMmJiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XvY8x2vBZgVTi_Tn5R2ShYx8GvtBP_zYvmZmzz8r7OY">

Hi! i used $setBlockType method instead. And it works!
