### ISSUE TITLE
 Feature: Ability to start the anchor text from the current position of the caret when no text is selected

### ISSUE THREAD

**Issue by neerajtomardg** [facebook/lexical#4176]
When the link icon is clicked without selecting any text , the entire text present is highlighted and converted to the anchor text. I feel it would be more intuitive if the anchor text starts from the caret position when the link icon was clicked.

I would like to bring some thought to what if an option is provided to  have this behaviour: When the user clicks the link-icon in the lexical toolbar and types some text in the editor then the characters that are typed after the click should be taken as the link till a space is encountered. This is the case when user wants to insert a link from the current caret position as they type the text.

Summary
Scenario: No text is selected by user and link icon is clicked in the lexical toolbar
**Current behaviour:**
 When no text is selected and user types some text and click link icon, you will notice the entire text is highlighted and made as a link label (anchor text)
**Requested option:** 
When no text is selected and user types some text, clicks link icon and then starts typing. All the characters that are typed (till the space or end of text) after clicking the icon should be highlighted and taken as a link label (anchor text).

Also it would be helpful in case there was some particular reasoning for the library to behave in the way is it is currently for this particular case.

**Comment by acywatson** [comment]
The library doesn't really behave this way, just the specific playground implementation of link insertion, which is just an example and not part of the public API. You should be able make links behave the way you are describing pretty easily using Lexical (split text, insert LinkNode or whatever).

Feel free to re-open if you have more questions.
