### ISSUE TITLE
Bug: Pressing `ctrl + d` deletes multiple characters in linkNode under linebreakNode

### ISSUE THREAD

**Issue by KeisukeOmata** [facebook/lexical#4183]
If there is a linkNode under the linebreakNode, pressing `ctrl + d` will delete multiple characters in the linkNode.

Lexical version: 0.9.0

## Steps To Reproduce

1. Pressing `shift + enter` adds a linebreakNode
2. To add a linkNode
3. Pressing `ctrl + d` on linebreakNode

https://user-images.githubusercontent.com/50476037/227076504-36c1d7b6-4c45-4761-baac-d07da14407b3.mov

## The current behavior
The characters in linkNode are being deleted in multiples.

## The expected behavior
A single character in linkNode is being deleted.

**Comment by ivailop7** [comment]
I'm not able to reproduce this, over the past 9 months there have been significant improvements in handling links. This is most likely fixed. If still reproduceable, please raise the issue again.
