### ISSUE TITLE
Bug: If the top node is a Collapsible Section, there is no way to append text before it

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#4187]
https://user-images.githubusercontent.com/7893468/227382869-6f4838f8-da73-4601-afcb-c3d2c36bdf5b.mp4

Lexical version: 0.9

## Steps To Reproduce

1. Clear all the editor contents
2. Append a Collapsible Section (the only node)

## The current behavior

Since the node is at the top, there is no way to position the cursor above it (or on the same line before it) to append text before the section. As a workaround, one can type below it and then use the drag-and-drop plugin to push the paragraph above the section to gain the ability to write above. 

## The expected behavior

Having looked at how we handle this for Images and Polls: we allow to position the cursor on the same line before the image, so the user can do newline, which is fine, since they don't take direct text input and don't occupy the whole row. This is an option, but since the collapsible section takes the whole row, ie we need to squeeze the width of the section if we type text next to it or reflow it to a new line and might also create confusion with typing in the section header.

A few ideas:
1) Append an empty paragraph node before the Collapsible Section when it is the top node in the editor. If someone wants to delete the empty line, they can do so manually.
2) Allow to position the cursor on the same line as the section (at the start of the line) and upon any typed text move the section to the next line.

**Comment by ivailop7** [comment]
After playing with other nodes, I noticed the answer exists in the YouTube Node - when a YouTube node is the top node, the cursor becomes an underline when the above node is not a text one, respectively the same if the node below is not text-based either. This is ideal, I'll replicate this behaviour for the collapsible section too.

Example below:

https://user-images.githubusercontent.com/7893468/227804202-fdd71d28-fad8-495c-a709-b07da37ff5e4.mp4

**Comment by ivailop7** [comment]
I've narrowed it down I need to update `updateDOMBlockCursorElement` but not entirely sure how to solve this in a node-type agnostic way, would need some guidance, since the main wrapper (the container node) is not directly selectable, which I believe is why the existing logic doesn't kick in, beyond the lack of "inInline" and "canBeEmpty" not being defined as False in the node definitions.

**Comment by khanakia** [comment]
I was checking how Notion.js handles this basically there are 2 ways
1. SHIFT + ENTER creates a new node below
2. Clicking on the Empty area at the bottom of the editor simply inserts a new paragraph node

**Comment by ivailop7** [comment]
> I was checking how Notion.js handles this basically there are 2 ways
> 
> 1. SHIFT + ENTER creates a new node below
> 
> 2. Clicking on the Empty area at the bottom of the editor simply inserts a new paragraph node

This sounds like an issue when a paragraph node is missing below the section. There's already a logic to auto append paragraph below the section on key down. The question is how to solve it for the case when we are missing a paragraph node above the section.

**Comment by fantactuka** [comment]
#4257 should address it, basically it allows to use key up/down/right/left to append extra paragraph before/after collapsible if it's the first/last element in the document. There're different ways to allow it, including CMD+Enter (insert paragraph after) or CMD+opt+Enter (insert before), or via UI menus like in Notion but those are pretty app-specific

**Comment by ivailop7** [comment]
This has been resolved for a while now. Closing.
