### ISSUE TITLE
Bug: Floating link editor doesn't show up for AutoLinkNode

### ISSUE THREAD

**Issue by AlessioGr** [facebook/lexical#4202]
https://user-images.githubusercontent.com/70709113/227732021-9372e8c6-9ab8-4084-88bb-9ffcdb33b592.mp4

Lexical version: 0.9.1

**Comment by KarthikRaju391** [comment]
Just checked the behaviour on the playground and saw that this issue is still there. @zurfyx, I would like to work on this issue if it's not already being fixed by someone.
