### ISSUE TITLE
Bug: NodeEventPlugin does not work for nodes created in initialConfig.initialEditorState

### ISSUE THREAD

**Issue by jkap-figma** [facebook/lexical#4213]
Lexical version: 0.8.1

## Steps To Reproduce

1. Pass in an initialEditorState that creates nodes and appends them to root
2. Use a NodeEventPlugin handler to print to console when a node is selected
3. Observe that the plugin does not fire on the initial editor state -- but does fire on new nodes you create during the editing session

I believe this is happening because the nodes are created before there's an active editor session, so the mutations [here](https://github.com/facebook/lexical/blob/230903f0f536b8d1a84f2ca43dbb390e9a7f9063/packages/lexical-react/src/LexicalNodeEventPlugin.ts#L48) are not triggered to add these nodes to the list of registered elements.

I don't have too much context to explore a fix here -- but maybe a useEffect could sweep through nodes created from the initialConfig and attach the listeners.

**Comment by acywatson** [comment]
yea or maybe we should change when those mutation listeners fire

**Comment by acywatson** [comment]
To include nodes created by initial state

**Comment by khanakia** [comment]
@jkap-figma 
I am unable to reproduce the issue check video. If you have the code-sandbox link please share

```
<NodeEventPlugin nodeType={ParagraphNode} eventType='mouseup' eventListener={(event) => {
  console.log("NodeEventPlugin", event)
}} />
```

https://user-images.githubusercontent.com/2174170/230165731-afab32e0-b6c1-4284-b6c3-8cfa28ba78c8.mov
