### ISSUE TITLE
Bug: Can't use EditorState constructor due to how it is exported (as a type)

### ISSUE THREAD

**Issue by ProofOfKeags** [facebook/lexical#4217]
Lexical version:

## Steps To Reproduce

1. import { EditorState } from "lexical"
2. new EditorState(...)

Link to code example:

## The current behavior

`'EditorState' cannot be used as a value because it was exported using 'export type'.`

## The expected behavior

Being able to use the constructor that is described in the API docs

**Comment by thegreatercurve** [comment]
See Dominic's answer here for why we don't want to expose this class: https://github.com/facebook/lexical/issues/2500#issuecomment-1164309107

**Comment by ProofOfKeags** [comment]
Ok but then why do the docs expose the constructor as a means of creating an EditorState and how are we supposed to initialize an editor with a certain state using `initialEditorState` argument to `LexicalComposer`?

**Comment by aburd** [comment]
It would be nice if the docs just didn't show this information, or if it did warn the reader that they are barking up the wrong tree.
