### ISSUE TITLE
Bug: PNPM does not match registered node

### ISSUE THREAD

**Issue by onisaint** [facebook/lexical#4225]
Mono-repo projects with pnpm throws the following error for RichText
```ts
Error: Create node: Type heading in node HeadingNode does not match registered node HeadingNode with the same type
    at errorOnTypeKlassMismatch (Lexical.dev.js:4556:13)
    at new LexicalNode (Lexical.dev.js:3566:9)
    at new ElementNode (Lexical.dev.js:8148:5)
    at new HeadingNode (LexicalRichText.dev.js:167:5)
    at Object.$createHeadingNode (LexicalRichText.dev.js:322:40)
    at LexicalMarkdown.dev.js:921:21
    at LexicalMarkdown.dev.js:846:18
    at runElementTransformers (LexicalMarkdown.dev.js:565:7)
    at transform (LexicalMarkdown.dev.js:781:9)
    at LexicalMarkdown.dev.js:831:7
```

works well with monorepo from yarn / npm

Lexical version: 0.8.1, 0.9.1

## Steps To Reproduce

projects using pnpm instead of  yarn / npm

in the demo below type # and space,
what should happen:  convert node to heading node
what happens: throws error

Link to code example:
[codesandbox with workspaces](https://codesandbox.io/p/github/onisaint/lexical-editor-pnpm/main?workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfsg1pga000g3b6mwt95qf9c%2522%253A%257B%2522key%2522%253A%2522clfsg1pga000g3b6mwt95qf9c%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clfsg1pgb000h3b6mx7dntbk0%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clfsg21hi005i3b6mz411ffr2%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clfsg1zdz00293b6mbumlc6q1%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clfsg1pga000g3b6mwt95qf9c%2522%252C%2522spacesOrder%2522%253A%255B%2522clfsg1pga000g3b6mwt95qf9c%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

[codesandbox basic setup](https://codesandbox.io/p/sandbox/fervent-pine-pt09b3?file=%2Fsrc%2FApp.tsx)

**Comment by acywatson** [comment]
That's super weird. If you clear the cache and rebuild the dependencies/lock file, do you get the same result?

**Comment by onisaint** [comment]
It happens on a fresh build

**Comment by zurfyx** [comment]
For reference, this error means that the class reference is not the same. We've seen this same error when imports are not exactly the same (though the point to the same file (i.e. `import from .` and `import from 'lexical'`) and the bundler generates a copy of the file. In which case, if you have registered a HeadingNode with a different import than `$createHeadingNode` it would error. That said, I'm not sure how your setup looks like and why it's be erroring but that'd be a good starting point to dig deeper.

**Comment by onisaint** [comment]
@zurfyx the issue appears for node_modules installed with pnpm, 

[codesandbox with workspaces](https://codesandbox.io/p/github/onisaint/lexical-editor-pnpm/main?workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfsg1pga000g3b6mwt95qf9c%2522%253A%257B%2522key%2522%253A%2522clfsg1pga000g3b6mwt95qf9c%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clfsg1pgb000h3b6mx7dntbk0%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clfsg21hi005i3b6mz411ffr2%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clfsg1zdz00293b6mbumlc6q1%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clfsg1pga000g3b6mwt95qf9c%2522%252C%2522spacesOrder%2522%253A%255B%2522clfsg1pga000g3b6mwt95qf9c%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

[codesandbox basic setup](https://codesandbox.io/p/sandbox/fervent-pine-pt09b3?file=%2Fsrc%2FApp.tsx), 

the reproduction links are above

**Comment by khanakia** [comment]
Both codesanbox seems to be working fine i do not see any error in codesandbox links you shared

**Comment by onisaint** [comment]
@khanakia  can you type in # and space , as MarkdownShortcuts - plugin is registered, it throws the error

**Comment by khanakia** [comment]
Check it seems to work


https://user-images.githubusercontent.com/2174170/229275519-be779e20-7d70-4d96-b57e-1b32909e2ae8.mov

**Comment by onisaint** [comment]
https://user-images.githubusercontent.com/8987882/229289587-c30038e6-2d2b-4800-958d-eafb79231a4c.mov

@khanakia did you start with `pnpm i` ?

**Comment by khanakia** [comment]
Yes check below screenshot of history

![Screenshot 2023-04-01 at 6 35 49 PM](https://user-images.githubusercontent.com/2174170/229290744-a69ffc15-439c-4cc8-b987-ee86bbc3645e.png)

**Comment by onisaint** [comment]
can you clear cache, and try `pnpm i && pnpm dev`

**Comment by khanakia** [comment]
Check video, please

https://user-images.githubusercontent.com/2174170/229292618-fdd26adf-bf6a-43b3-a63d-21644d79e745.mov

**Comment by onisaint** [comment]
@khanakia what is your `pnpm` version ?

**Comment by khanakia** [comment]
```
➜  lexical git:(main) ✗ pnpm --version
8.1.0
```

**Comment by onisaint** [comment]
yup [pnpm@8.x.x changelog](https://github.com/pnpm/pnpm/releases/tag/v8.0.0) and above works, but not for pnpm@7.x.x

**Comment by onisaint** [comment]
codesandbox and i was using 7.x.x , 
8.x.x got released last week, 
Many thanks @khanakia  :)

**Comment by alamothe** [comment]
Have exact same problem with in a Yarn PNP monorepo.

**Comment by aanavadiya03** [comment]
I also facing this problem in a Yarn PNP monorepo. `HeadingNode` and `QuoteNode` which are imported from `@lexical/rich-text`, generating the same error with `# ` and `> ` for heading and quote. Everything else working fine. Using `ToolbarPlugin` if I select heading and quote block then it is adding those node in the DOM and showing heading and quote block.

**Comment by nujhong** [comment]
Running into the same issue in Yarn PNP, basically the package is duplicated ([reference](https://github.com/yarnpkg/berry/issues/3656)). It's likely due to [`@lexical/rich-text` setting `@lexical/selection` as `peerDependencies` other than `dependencies`](https://github.com/facebook/lexical/blob/main/packages/lexical-rich-text/package.json), as how other packages do.

Problem goes away after making sure there's only one instance. 

```
❯ yarn info @lexical/rich-text --virtuals -AR                                                                                                                                                        (lexical|●49✚10…22⚑13)
├─ @lexical/rich-text@npm:0.14.2
│  ├─ Instances: 2
│  └─ Version: 0.14.2
│
├─ @lexical/rich-text@npm:0.14.2 [555d8]
│  ├─ Version: 0.14.2
│  │ 
│  └─ Peer dependencies
│     ├─ @lexical/clipboard@0.14.2 → npm:0.14.2 [a2a1e]
│     ├─ @lexical/selection@0.14.2 → npm:0.13.1 [555d8]
│     ├─ @lexical/utils@0.14.2 → npm:0.14.2 [a2a1e]
│     ├─ @types/lexical@* → ✘
│     ├─ @types/lexical__clipboard@* → ✘
│     ├─ @types/lexical__selection@* → ✘
│     ├─ @types/lexical__utils@* → ✘
│     └─ lexical@0.14.2 → npm:0.14.2
│
└─ @lexical/rich-text@npm:0.14.2 [a2a1e]
   ├─ Version: 0.14.2
   │ 
   └─ Peer dependencies
      ├─ @lexical/clipboard@0.14.2 → npm:0.14.2 [a2a1e]
      ├─ @lexical/selection@0.14.2 → npm:0.14.2 [a2a1e]
      ├─ @lexical/utils@0.14.2 → npm:0.14.2 [a2a1e]
      ├─ @types/lexical@* → ✘
      ├─ @types/lexical__clipboard@* → ✘
      ├─ @types/lexical__selection@* → ✘
      ├─ @types/lexical__utils@* → ✘
      └─ lexical@0.14.2 → npm:0.14.2
```

**Comment by zbigniewzolnierowicz** [comment]
To anyone stumbling upon this repo: make sure you *explicitly* install `@lexical/{code,link,list,rich-test}` - otherwise it will just pull from wherever the hell it wants.
