### ISSUE TITLE
Bug: Only element or decorator nodes can be inserted in to the root node

### ISSUE THREAD

**Issue by SGDS666** [facebook/lexical#4226]
When I try to extract the mentioned component into the toolbar and insert it into the codesandbox, it is normal, but when I use it in a local project, I report this error. I checked and found that the 0.5 version of codesandbox is used locally, and 0.9 is used. What should I do to resolve this? Here is the online address for reproducing the error

https://codesandbox.io/s/distracted-grothendieck-bkpd6r?file=/src/ToolBar.tsx
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/86196091/228301063-d06e1caf-523b-4e7b-8fdd-cb0c2454ff2b.png">

<img width="560" alt="image" src="https://user-images.githubusercontent.com/86196091/228298104-fc62d8a6-c1d2-4fb0-9af8-2e1e2002f9d2.png">

When you set these two dependencies to 0.5, they will work normally

<img width="340" alt="image" src="https://user-images.githubusercontent.com/86196091/228300206-a35d7a77-8f8d-4cac-9f91-6e5635805da3.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/86196091/228300756-3dc75be9-9adb-4b5d-81b0-32b3c408a6cf.png">

What should I do to make it work in version 0.9.1

**Comment by acywatson** [comment]
The error is right here - you can't append a text node directly in the root. You have to put it in a ParagraphNode or something.

**Comment by SGDS666** [comment]
> 错误就在这里——你不能直接在根目录中追加一个文本节点。您必须将它放在 ParagraphNode 或其他东西中。

Can you tell me how to specifically operate it? I don't quite understand

**Comment by SGDS666** [comment]
I added an error capture to handle this scenario because I'm not very familiar with the Lexical API, and I don't know if there's a better way

<img width="715" alt="image" src="https://user-images.githubusercontent.com/86196091/228405744-a953f07f-a364-4b14-b502-063c897b82fb.png">

**Comment by acywatson** [comment]
What you are doing in your original code is creating a TextNode subclass (which cannot be appended to root), then getting the top level element, which is by definition a child of the root, and then inserting your node before the top level element, which means it will always be a child of the root, which violates an invariant.

You must append the CustomVarNode to some ElementNode:

```
const myNode = $createCustomVarNode();
const p = $createParagraphNode();
p.append(myNode);
//append or insert paragraph wherever you want...
```

**Comment by ko-devHong** [comment]
> 

it's work for me Thanks

**Comment by ko-devHong** [comment]
> What you are doing in your original code is creating a TextNode subclass (which cannot be appended to root), then getting the top level element, which is by definition a child of the root, and then inserting your node before the top level element, which means it will always be a child of the root, which violates an invariant.
> 
> You must append the CustomVarNode to some ElementNode:
> 
> ```
> const myNode = $createCustomVarNode();
> const p = $createParagraphNode();
> p.append(myNode);
> //append or insert paragraph wherever you want...
> ```

it's work for me Thanks
