### ISSUE TITLE
Bug: ElementNode function "hasFormat" is error

### ISSUE THREAD

**Issue by moyang-pro** [facebook/lexical#4227]
Lexical version:0.81

## Steps To Reproduce

1. ElementNode function "hasFormat" is error:
old:
hasFormat(type: ElementFormatType): boolean {
    if (type !== '') {
      const formatFlag = ELEMENT_TYPE_TO_FORMAT[type];
      return (this.getFormat() & formatFlag) !== 0;
    }
    return false;
  }
new:
hasFormat(type: ElementFormatType): boolean {
    if (type !== '') {
      const formatFlag = ELEMENT_TYPE_TO_FORMAT[type];
      // moyang bugfix
      return (this.getFormat() === formatFlag);
    }
    return false;
  }

**Comment by zurfyx** [comment]
While it's certainly confusing for ElementNodes, the numeric value allows setting multiple values at once. Hence the binary `&` check. We may move away from it in the future but there's a larger discussion around version compatibility.
