### ISSUE TITLE
Bug: program selection not work

### ISSUE THREAD

**Issue by evskorobogatij** [facebook/lexical#4235]
I try select text after inserting. I used $setSelection to do this. But nothing selected

Lexical version:
lexical: 0.9.1
 
Link to code example:

https://codesandbox.io/s/condescending-tess-ciw6tf?file=/src/plugins/ImageToolbar.tsx

## The current behavior
Selection by $setSelection not work

## The expected behavior
Using $setSelection selected text and highlight it.

**Comment by evskorobogatij** [comment]
So, if I using paragraph.selectEnd() cursor moved to the end of paragraph. If I used paragraph.select(0) -- paragraph selected. This is fine.

But what can I do to select few paragraphs? 

I try to use:

```
editor.update(() => {
      const data = [
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        "Nam metus nulla, aliquam sit amet cursus non, tincidunt tempor velit. Ut vel condimentum lorem.",
        "Integer felis lectus, blandit convallis vehicula id, ornare eget lacus.",
        "Vestibulum eu sem hendrerit, finibus est nec, lobortis diam."
      ];
      const root = $getRoot();
      const p = root.getLastChild();

      data.forEach((text) => {
        const paragraph = $createParagraphNode();
        const textNode = $createTextNode(text);
        paragraph.append(textNode);
        p.insertAfter(paragraph);

        paragraph.select(0);
        nodes.push(paragraph);
      });

      const sel = $createRangeSelection();
      sel.getNodes().push(...nodes);
      $setSelection(sel);

    });
```

But nothing selected. How select all inserted paragraphs?

**Comment by acywatson** [comment]
You have to set the anchor and the focus of the range selection. You can't mutate the nodes in the selection by pushing to the result of getNodes.

```
selection.anchor.set()
selection.focus.set()
```
