### ISSUE TITLE
Bug: Pressing Enter unexpectedly deletes ImageNode as the only child of ListItemNode

### ISSUE THREAD

**Issue by kazukinagata** [facebook/lexical#4236]
After looking at the code for a bit, it seems that the root of the problem lies in the $handleListInsertParagraph function.

You can find the code here: 
https://github.com/facebook/lexical/blob/main/packages/lexical-list/src/formatList.ts#L500.

The function is supposed to remove a ListItemNode when the selection.anchor is an empty ListItemNode, but it also deletes the node even if it contains an ImageNode.

To work around this issue, I added a check to ensure that the length of the children is equal to 0 at [line 509](https://github.com/facebook/lexical/blob/main/packages/lexical-list/src/formatList.ts#L509). However, I'm not certain if this is the proper way to handle it.

```typescript
  if (
    !$isListItemNode(anchor) ||
    // add this
    anchor.getChildren().length !== 0 ||
    anchor.getTextContent() !== ''
  ) {
    return false;
  }
```

If you have any better suggestions, please let me know. I'm willing to create a PR if that works for you.

Lexical version: 0.9.1

## Steps To Reproduce

1. Go to the [playground](https://playground.lexical.dev/) and create a ListItem.
2. Insert image to the ListItem.
3. Press Enter key.
4. The image and the parent ListItem will be deleted.

https://user-images.githubusercontent.com/4246353/228444754-efbde971-9b09-49ed-88b0-a8c7306c0e9a.mp4

## The current behavior

- Create a sibling ListItem and leave the ImageNode.

## The expected behavior

- It delete the ListItem and ImageNode.

**Comment by khanakia** [comment]
@zurfyx I was debugging the code and found that `selection.anchor.getNode()` only gets the TextNode or ElementNode

It does not handle the DecoratorNode so it fallback to ListItemNode when there is only a Decorator Node

It works only if there some TextNode is present on the ListitemNode

I could not find the proper way to fix it as `selection.anchor.getNode()` does not return the DecoratorNode so should we modify that function first to be able to get the decoratorNode first and then add a validation check so it does not delete the item?

What are you thought about this?

https://github.com/facebook/lexical/blob/6b380d581300cb4e121c534177cc510236e579d3/packages/lexical-list/src/formatList.ts#L507

https://user-images.githubusercontent.com/2174170/229292393-f5f53293-ad08-4432-a53b-c7d2f6fc3f1b.mov

**Comment by ivailop7** [comment]
This looks fixed. Closing.
