### ISSUE TITLE
Bug: OnChangePlugin doesn't fire when editor is blurred

### ISSUE THREAD

**Issue by ProofOfKeags** [facebook/lexical#4239]
Lexical version: 0.9.1

## Steps To Reproduce

1. Set up basic editor with OnChangePlugin
2. console.log in onChange callback
3. observe no event fires when clicking outside the editor

Link to code example:

This can be observed in the provided sandbox without modification
https://codesandbox.io/s/lexical-plain-text-example-g932e

## The current behavior

OnChange is not fired when editor is blurred (de-focused)

## The expected behavior

SelectionState should be set to null, causing a change to the editorstate and firing the onChange callback

**Comment by khanakia** [comment]
OnchangePlugin only works on editor state change, not on blur

However you can create a custom plugin like this
https://codesandbox.io/embed/lexical-plain-text-example-forked-x6vxm8?fontsize=14&hidenavigation=1&theme=dark

```
const EditorBlurPlugin = () => {
  const [editor] = useLexicalComposerContext();
  useEffect(() => {
    editor.registerCommand(
      BLUR_COMMAND,
      () => {
        console.log("test");
      },
      COMMAND_PRIORITY_EDITOR
    );
  }, []);

  return null;
};
```

**Comment by khanakia** [comment]
no blur does not changes the editor state itself so onChange will never be triggered

**Comment by thegreatercurve** [comment]
@khanakia is correct. We don't change the editor state on blur, even if selection is changed.
