### ISSUE TITLE
Bug: $unmergeCell is not exported in build

### ISSUE THREAD

**Issue by Godefroy** [facebook/lexical#4247]
I tried applying last playground modifications to my project and I was stuck in `TableActionMenuPlugin` because I cannot Import `$unmergeCell`.

Lexical version: 0.9.1

**Comment by acywatson** [comment]
@zurfyx can we expose?

**Comment by khanakia** [comment]
It seems to be already exposed https://github.com/facebook/lexical/commit/99d5a9dce213877d75a060fbe59560da817207f3#diff-25a394b4836934a3bd9f81cbb3bdd3fc780904ca985a73295cde46dcde13bb75

but not yet in current release

**Comment by Godefroy** [comment]
Thanks @khanakia, I assumed current release was synced with main branch when I applied last playground modifications to my project. I'll wait for the update then!

**Comment by namoshizun** [comment]
Just wondering is there a set date for the next release? I am trying to apply the `TableActionMenuPlugin` from the playground but got stuck at this as well...
