### ISSUE TITLE
Bug: Lexical Mentions Plugin not working in nextjs

### ISSUE THREAD

**Issue by bleedingAyush** [facebook/lexical#4248]
Lexical version: 0.9.1
Nextjs: 13.2.4

## Steps To Reproduce

1. Install lexical and @lexical/react in nextjs 
2. Add Mentions Plugin.

Link to code example: [codesandbox](https://codesandbox.io/p/github/bleedingAyush/twitter/master?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clfw10oql0000g3jrbfin1rj2%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfwn4dnl000x3n6jiyigklji%2522%253A%257B%2522key%2522%253A%2522clfwn4dnl000x3n6jiyigklji%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clfwn4dnm000y3n6jj6girta2%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clfwn4dnn000z3n6jub8kdh6g%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clfwn4dnl000x3n6jiyigklji%2522%252C%2522spacesOrder%2522%253A%255B%2522clfwn4dnl000x3n6jiyigklji%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)
Link to [Github code](https://github.com/bleedingAyush/twitter)

## The current behavior
Thowing "document is not defined error"

```
error - ReferenceError: document is not defined
    at useMenuAnchorRef (C:\Users\palla\ReactJsProjects\twitter\node_modules\@lexical\react\LexicalTypeaheadMenuPlugin.dev.js:466:41)
    at LexicalTypeaheadMenuPlugin (C:\Users\palla\ReactJsProjects\twitter\node_modules\@lexical\react\LexicalTypeaheadMenuPlugin.dev.js:541:28)
    at renderWithHooks (C:\Users\palla\ReactJsProjects\twitter\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
```

## The expected behavior
Should run lexical Mentions Plugin

**Comment by bleedingAyush** [comment]
Update: When I remove the <Editor/> component it starts working fine. But when I refresh the page the same error
```document is not defined``` starts showing up

**Comment by acywatson** [comment]
Try this:

https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr
