### ISSUE TITLE
Bug: cannot escape lists

### ISSUE THREAD

**Issue by affvalente** [facebook/lexical#4266]
On the playground, on iOS, when I add 2 bullets and then hit enter to add a new bullet and then enter to try to escape the list, it doesn't work so it's not possible to escape a list with double enter 

I’m getting a line break, which keeps the bullet, empty line, new line indented under the bullet. New enters just keep this going

Thanks
Andre

**Comment by affvalente** [comment]
Also happens on other platforms. Thanks

**Comment by affvalente** [comment]
Any news on this one?

**Comment by pistachiomatt** [comment]
I'm still seeing this in 0.12 (however it's fixed in the Playground). Is there something special to do to get this to work?
