### ISSUE TITLE
Bug: Converting from markdown ignores empty lines

### ISSUE THREAD

**Issue by affvalente** [facebook/lexical#4271]
When converting from .md to lexical (on the playground and other implementations), empty lines in the markdown get ignored 

In markdown, I use empty lines to separate text, headings etc, to improve readability 

I would expect the conversion to keep those empty lines too, as  empty lines (think empty line after block of text, before an h2)

For instance, this markdown
“Aaa
Aaa

Bbb
Bbb"

Should translate into 5 nodes within lexical. 

I’m finding sometimes this converts to 4 (ignores blank line) or 2 (2 paragraphs, one with all the As and one with all the Bs) each with 2 lines separated by linebreak

**Comment by onisaint** [comment]
this seems to be default behaviour of markdown,
more context here https://stackoverflow.com/questions/15721373/how-do-i-ensure-that-whitespace-is-preserved-in-markdown

**Comment by affvalente** [comment]
Obsidian.md have an elegant solution for this. 

They call it "strict line breaks" and have it as an option (which is off by default): 
- in strict mode, the editor follows the markdown standard. 
- In 'normal' mode it does what you'd expect: empty line on md translates to empty line on preview

**Comment by affvalente** [comment]
We also seem to have the reverse bug

Go to playground and type

"
## heading 2
A
"

Then check markdown code for this. Lexical creates 
"
## heading 2
<empty line>
A
"

**Comment by affvalente** [comment]
I've read up more on this and indeed Lexical uses the markdown standard well. 

Not sure there's a way to not follow the standard without breaking other things down the line, so we may have to close this 

It's a problem for people that want markdown in/out but need to use the JSON in the middle because lexical changes the input

**Comment by tbuschto** [comment]
> I’m finding sometimes this converts to 4 (ignores blank line) or 2 (2 paragraphs, one with all the As and one with all the Bs) each with 2 lines separated by linebreak

I see the second behavior and that seems to be within the markdown standard, though most implementations seem to ignore newlines within a paragraph. To make those broduce a line break the line needs to end with either two empty spaces, a `<br>` or a `\`.  See https://www.markdownguide.org/basic-syntax/#line-breaks.  But if you import these in to lexical it doesn't know what to do with those extra characters and just makes them part of the text node.

So to work around all of this a made a transformer that exports line break nodes (created via by Shift+Enter) with a `\n` and strips those away again on import:

```ts
export const LINE_BREAK_FIX: TextMatchTransformer = {
  dependencies: [LineBreakNode],
  export: (node) => {
    if (!$isLineBreakNode(node)) return null;
    return '\\\n';
  },
  regExp: /\\$/,
  importRegExp: /\\$/,
  replace: (textNode) => {
    if (!textNode?.getParent()) return;
    textNode.replace($createTextNode());
  },
  trigger: '',
  type: 'text-match',
};
```
So far it seems to work, though it will still ignore `<br>`.

**Comment by casield** [comment]
@tbuschto you are a life saver!

**Comment by fantactuka** [comment]
You can also add support for `<br>` if needed for MD import:

```
export const BR: TextMatchTransformer = {
  dependencies: [LineBreakNode],
  export: (node) => {
    return null;
  },
  importRegExp: /<br\s?\/?>/,
  regExp: /<br\s?\/?>/,
  replace: (textNode) => {
    const parentNode = textNode.getParent();
    if (parentNode.getChildrenSize() === 1) {
      textNode.remove();
    } else {
      textNode.replace($createLineBreakNode());
    }
  },
  trigger: '',
  type: 'text-match',
};
```

**Comment by Steven-Ireland** [comment]
For anyone else running into this: The above solutions didn't _quite_ work for me, but this did: 

```typescript
export const LINE_BREAK_FIX: ElementTransformer = {
  dependencies: [ParagraphNode],
  export: (node) => {
    return null;
  },
  regExp: /^$/,
  replace: (textNode, nodes, _, isImport) => {
    if (isImport && nodes.length === 1) {
      console.log(textNode)
      nodes[0].replace($createParagraphNode());
    }
  },
  type: 'element'
};
```

along with this in my onchange plugin for export:

```typescript
$convertToMarkdownString(transformers).replaceAll(/\n{2}/gm, '\n')
```

The reason this works is that the markdown plugin export joins all "lines" with `\n\n`. so markdown like this:
```md
hello
world

1
2
3
```

would get converted (normally) to: `hello\n\nworld\n\n\n1\n\n2\n\n3`. By removing the `\n\n` join, you're left with: `hello\nworld\n\n1\n2\n3`, which is much closer to what you'd actually want exported. 

From there, on import, a text match transformer can't pick up the newlines because the input string is split on `\n` -- so text match transformers would operate on `['hello', 'world', '', '1', '2', '3']. That's where the element transformer comes in, picking up blank lines with the regex `/^$/` and transforming it to a new paragraph node.

Hope this helps anyone else using this library!

**Comment by addlistener** [comment]
> For anyone else running into this: The above solutions didn't _quite_ work for me, but this did:
> 
> ```ts
> export const LINE_BREAK_FIX: ElementTransformer = {
>   dependencies: [ParagraphNode],
>   export: (node) => {
>     return null;
>   },
>   regExp: /^$/,
>   replace: (textNode, nodes, _, isImport) => {
>     if (isImport && nodes.length === 1) {
>       console.log(textNode)
>       nodes[0].replace($createParagraphNode());
>     }
>   },
>   type: 'element'
> };
> ```
> 
> along with this in my onchange plugin for export:
> 
> ```ts
> $convertToMarkdownString(transformers).replaceAll(/\n{2}/gm, '\n')
> ```
> 
> The reason this works is that the markdown plugin export joins all "lines" with `\n\n`. so markdown like this:
> 
> ```
> hello
> world
> 
> 1
> 2
> 3
> ```
> 
> would get converted (normally) to: `hello\n\nworld\n\n\n1\n\n2\n\n3`. By removing the `\n\n` join, you're left with: `hello\nworld\n\n1\n2\n3`, which is much closer to what you'd actually want exported.
> 
> From there, on import, a text match transformer can't pick up the newlines because the input string is split on `\n` -- so text match transformers would operate on `['hello', 'world', '', '1', '2', '3']`, but skip the empty string due to a length check. That's where the element transformer comes in, picking up blank lines with the regex `/^$/` and transforming it to a new paragraph node.
> 
> Hope this helps anyone else using this library!

@Steven-Ireland it seems that nested paragraphs are created this way

Thanks a lot for your input BTW, typing ENTER in the playground should create a paragraph node so only your example works for the playground.

**Comment by addlistener** [comment]
And way to go to build a stable md editor. For example, there are diff between an empty paragraph and a linebreak

```
 root
  ├ (2895) heading  
  | └ (2894) text  "the following is an empty paragraph"
  ├ (2904) paragraph  
  ├ (2908) heading  
  | └ (2907) text  "the following is an empty paragraph with a hard line break"
  ├ (2914) paragraph  
  | └ (2917) linebreak  
```

Maybe GFM with HTML support is a solution? 

```
the following is an empty paragraph

<p></p>

the following is an empty paragraph with a line break

<p><br/></p>
```

**Comment by mark-archer** [comment]
None of the above solutions were quite what I was looking for.  Adding what worked for me in case it helps anyone else.  

```typescript
export const PRESERVE_NEWLINES: ElementTransformer = {
  type: 'element',
  dependencies: [ParagraphNode],
  export: (node) => {
    if ($isParagraphNode(node)) {
      const content = node.getTextContent();
      if (!content.trim()) {
        return '\n \n';
      }
    }
    return null;
  },
  regExp: /^ $/, // a line with only a space
  replace: (textNode, nodes, _, isImport) => {
    if (isImport && nodes.length === 1) {
      textNode.append($createTextNode(''));
    }
  },
};

// when pulling out the markdown, this keep things consistent
const markdown = $convertToMarkdownString(customMarkdownTransformers).replace(/\n\n\n \n\n\n/gm, '\n\n \n\n');
```
