### ISSUE TITLE
I am having problem where no table is rendered after I click on the insert table button.

### ISSUE THREAD

**Issue by yingning-00** [facebook/lexical#4274]
I am having the problem where no table is rendered after I click on the insert table button.
I have to click on the placeholder first, after the cursor is displayed, then the insert table button can work.

https://user-images.githubusercontent.com/130023653/230266253-c45d7c07-5d54-46dc-a8d1-6500a96609f1.mov

_Originally posted by @yingning-00 in https://github.com/facebook/lexical/issues/3981#issuecomment-1498447058_

**Comment by zurfyx** [comment]
The problem you're having is that the editor does not have selection. You can make it work by clicking the editor first, then inserting the table, or something similar via the API. The fix (via `insertNodes`) is merged #4180 but will have to wait until 0.9.2.
