### ISSUE TITLE
Feature: markdown transform horizontal rule

### ISSUE THREAD

**Issue by arantespp** [facebook/lexical#4279]
I'd like to have a horizontal rule markdown transformation for the `---` string. 

I was investigating the [MarkdownTransformers.ts](https://github.com/facebook/lexical/blob/main/packages/lexical-markdown/src/MarkdownTransformers.ts) file, and I think that something like this would solve the issue:

```ts
import { $createHorizontalRuleNode } from '@lexical/react/LexicalHorizontalRuleNode';
import {
  $isHorizontalRuleNode,
  HorizontalRuleNode,
} from '@lexical/react/LexicalHorizontalRuleNode';
import {
  ElementTransformer,
  TRANSFORMERS as LEXICAL_TRANSFORMERS,
} from '@lexical/markdown';

export const HORIZONTAL_RULE: ElementTransformer = {
  dependencies: [HorizontalRuleNode],
  export: (node) => {
    if (!$isHorizontalRuleNode(node)) {
      return null;
    }
    return '---';
  },
  regExp: /---/,
  replace: (parentNode) => {
    const node = $createHorizontalRuleNode();
    parentNode.replace(node);
  },
  type: 'element',
};
```

(I implemented the [HORIZONTAL_RULE transformer](https://github.com/terezatech/tereza-tech/blob/main/packages/components/src/components/Editor/MarkdownTransformers.tsx) on my project editor. [Check the live editor](https://storybook.tereza.tech/?path=/story/components-editor--with-initial-value).)

**Comment by 9larsons** [comment]
@arantespp great example - did you have any issue getting this RegExp to be picked up? For some reason I'm only able to do this with a space, e.g. `regExp: /---\s$?/`. If I try what you have, it doesn't work.

**Comment by fantactuka** [comment]
The reason HorizontalLine is not included into markdown package is that it's a decorator node, that is framework-dependant. E.g., it will be different for Vue or Svelte. So for this particular case, it should be added on application level, similar as we did in the playground:

https://github.com/facebook/lexical/blob/4803905936a23481b064c13ae58f433db0ed42a4/packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts#L53-L73

**Comment by 9larsons** [comment]
Yep, that's exactly how I'm trying to implement it. However the `/---/` RegExp is not working for me, while it is in @arantespp 's example. 

@fantactuka while this could be closed as a feature, I wonder if it's the implementation or a bug. The 0-1 space only triggers when there's one space.

e.g. in the playground you have to type '--- ' and not just '---'. If you do '---' then press enter for a new line, you don't get a horizontal rule, when likely you would've wanted one.

**Comment by misha-erm** [comment]
@fantactuka sorry for bringing old topic, but won't it make sense to make horizontalrulenode framework-agnostic? Or maybe add some way to configure decoration nodes per env

It seems to be a quite basic element which can't be parsed with default lexical plugins on backend. 
Am I right that my only option right now is to either copy-paste LexicalHorizontalRuleNode to backend but override decorate method like `decorate: () => null`?
