### ISSUE TITLE
Bug: H2 and H3 text formatting to Uppercase

### ISSUE THREAD

**Issue by N03111990** [facebook/lexical#4312]
Lexical version: https://github.com/facebook/lexical/releases/tag/v0.9.1

https://playground.lexical.dev/

## Steps To Reproduce

1. type multiple sentences in the editor
2. select a sentence and format to Heading-2 or Heading-3

Link to code example:

## The current behavior
Upon formatting to H2 or H3, the selected text turns uppercase.

## The expected behavior
Upon formatting to H2 or H3, the selected text should remain in user inserted case.

**Comment by acywatson** [comment]
This is configurable via your editor theme:

https://github.com/facebook/lexical/blob/c6df5fcfa70e918f7499492d9e86ce104929f024/packages/lexical-playground/src/themes/PlaygroundEditorTheme.css#L41

https://github.com/facebook/lexical/blob/c6df5fcfa70e918f7499492d9e86ce104929f024/packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts#L56
