### ISSUE TITLE
Bug: resizing an image makes the cursor over the text `default` (arrow) instead of `text`

### ISSUE THREAD

**Issue by EgonBolton** [facebook/lexical#4317]
Lexical version: 0.9.1

## Steps To Reproduce

1. Resize an image in the playground
2. Move the mouse towards the text.

Link to code example: https://playground.lexical.dev/

## The current behavior
when hovering over the text, `cursor: default`.

## The expected behavior
when hovering over the text, `cursor: text`.

**Comment by MohitSinghChauhan** [comment]
Hello, I would be interested in working on this issue. Could it be assigned to me? My GitHub handle is @MohitSinghChauhan. Thank you for your time and consideration.
