### ISSUE TITLE
Bug: lexical/react - KEY_ENTER_COMMAND not working on mobile chrome/mozilla/safari

### ISSUE THREAD

**Issue by IrvingArmenta** [facebook/lexical#4322]
I am trying to trigger a callback onEnter by using the ` KEY_ENTER_COMMAND` from lexical, but the callback is not triggered when seeing the application/website, and it seems to go back to the "original" behavior, that is inserting a new line. 

Lexical version: 0.9.1 (latest 4/14/2023)

## Steps To Reproduce

1. Create a command using the KEY_ENTER_COMMAND 

```tsx
import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext'
import { COMMAND_PRIORITY_EDITOR, KEY_ENTER_COMMAND } from 'lexical'
import { useEffect } from 'react'

export function SubmitOnEnterPlugin(props: { callback: () => void }) {
  const [editor] = useLexicalComposerContext()
  const { callback } = props

  useEffect(() => {
    editor.registerCommand(
      KEY_ENTER_COMMAND,
      (event) => {
        // Handle enter key presses here
        if (event && !event.shiftKey) {
          event.preventDefault()
          callback()

          return true
        }

        return true
      },
      COMMAND_PRIORITY_EDITOR
    )
  }, [editor, callback])

  return null
}
```
2. Run your application in mobile chrome/safari/mozilla 

## The current behavior 
Seeing the website/application on mobile chrome will not trigger the `callback()` on "enter" and just trigger a new line.

## The expected behavior 
Seeing the website/application on mobile chrome will trigger the `callback()` on "enter" and will not

**Comment by acywatson** [comment]
Don’t use COMMAND_PRIORITY_EDITOR, as that’s the same priority the editor uses. You need to use a higher priority if you want to intercept and override the command listener.

**Comment by IrvingArmenta** [comment]
@acywatson Thanks for the feedback, it does seem to fix my issue.
but now it makes me wonder, why `COMMAND_PRIORITY_EDITOR` works okay in the desktop browser, compared to the mobile browser?

**Comment by acywatson** [comment]
Really good question - I don't know. My best guess is a race condition, rather than mobile vs desktop browser being the issue. Depending on which command is registered first, if they have the same priority then sometimes it would work as you expect and sometimes not. My hunch is some non-deterministic behavior, but I'm not 100% sure.
