### ISSUE TITLE
Bug: Unnecessary padding-inline-start in the nested list.

### ISSUE THREAD

**Issue by jourmooney** [facebook/lexical#4328]
Lexical version: 0.9.1

## Steps To Reproduce

1. generate a nested list
2. generate a JSON snapshot with the toJSON() function and a stringified version of the EditorState with the JSON.stringify() function.
3. unnecessary and ugly padding-inline-start appears.

Link to code example:
[https://codesandbox.io/s/lexical-plain-text-example-forked-l4oxnv](url)

## The current behavior
unnecessary and ugly padding-inline-start appears.
![image](https://user-images.githubusercontent.com/79959835/232111650-74d65994-f1f6-44b3-af3b-6ffcb797ee9a.png)

This padding seems to be caused by the code below.
`packages/lexical/src/LexicalReconciler.ts`
```tsx
  dom.style.setProperty(
    'padding-inline-start',
    indent === 0 ? '' : `calc(${indent} * ${indentationBaseValue})`,
  );
```

This seems to be related to #4240

**Comment by acywatson** [comment]
There's a merged PR with the fix in the issue that you linked. Will be released in 0.9.2
