### ISSUE TITLE
how to save all nodes with their unique ids in lexical file?

### ISSUE THREAD

**Issue by ghost** [facebook/lexical#4330]
The screenshot belongs to lexical file node tree which is downloaded from playground.lexical.dev. Nodes are not saved with their unique ids.

How can we make that all nodes are saved with their unique ids?

![image](https://user-images.githubusercontent.com/130306508/232182107-457efc7d-b4c2-45f9-82bc-a3948fb5e46c.png)

**Comment by acywatson** [comment]
Why do you want to do this? Those keys are not supposed to be stable across editors or sessions.

**Comment by tommy-taken** [comment]
If user adds a checkbox item inside of a note, I want to be able to show them as tasks in other section of the app as well. And whenever the user edits, mark/unmark it as checked in one section(either task or note), it should synced across both sections.

So basically, I would like to create kind of synced block experience like Notion has (https://www.notion.so/help/synced-blocks).
Actually Evernote has this feature as well which is called Tasks.

Would be happy to know how I could achieve this result.

![image](https://user-images.githubusercontent.com/130306508/232261679-50bb0e68-cea4-479f-801f-e73bf66bf014.png)

**Comment by joshdavenport** [comment]
This is also useful for saving and restoring the editor state (to JSON, or whatever) and an associated selection, using the keys that where there when the content was created and saved.

**Comment by Slapbox** [comment]
I'd be interested to know about this too. I assume there's some concept of storing data on a node which a user could then serialize and later deserialize, but I'm not sure what that might be based on my reading of the docs.

I hope such a concept exists?

**Comment by zurfyx** [comment]
In this case, you may want to extend or override the Node to have a unique ID of your own. The current `__key` is just meant to be unique within the page, retaining them can cause key collision when restoring the state onto another editor as @acywatson pointed out above.

For the same reason, if you introduce your own identifier you will have to resolve the merge conflicts yourself.

**Comment by acywatson** [comment]
> but would doing so still result in the possibility of nodes in the editor with duplicated persistent IDs?

No, this is fine to do with something like a UUID.

**Comment by Slapbox** [comment]
Awesome. So in `createDOM` devs could just use `element.dataset.persistentid = uuidGen()` - or does that also need to go in `updateDOM`? Or both? I'm not entirely clear on when each is invoked.

**Comment by jiangyuhang0506** [comment]
Is there a solution to this problem? How to add a unique ID? I want to know how to add a unique ID. After the JSON with the ID goes to parseEditorState, it can then be toJSON, and this ID should be retained and returned to the backend interface

**Comment by mayneyao** [comment]
Has there been any progress :D

**Comment by w-66** [comment]
Keeping an eye on it, hopefully there will be a solution that will reach or similar effect

**Comment by etrepum** [comment]
As described above, if you want to add unique ids to your nodes then just do it. Some flavor of UUID would be a good choice. The node keys are ephemeral, think of them like memory addresses. You don't get to choose the memory address when you allocate something, and you can't refer to that address after your app shuts down.

* Subclass each Lexical node that you want to add a unique id to
* Add the implementation for the unique id (constructor, unique id getter, import/export, clone, etc.)
* Use node overrides so that your app will use these nodes instead of the base classes
