### ISSUE TITLE
Bug: After the table is inserted into a row, the newly inserted row cannot be deleted.

### ISSUE THREAD

**Issue by xyyjk** [facebook/lexical#4331]
Lexical version: 
https://playground.lexical.dev/

## Steps To Reproduce

1. Insert row above
2. Insert row below
3. In the row just created, click Delete Column.

https://user-images.githubusercontent.com/2508421/232227802-14ac5505-e3c9-41cd-aaab-3dc3390d2f99.mp4

## The current behavior
No normal deletion

**Comment by xyyjk** [comment]
https://user-images.githubusercontent.com/2508421/232229321-da6bcd15-4828-44ff-b704-c4fd6faa422e.mp4

**Comment by icrosil** [comment]
Looking into it 👀

**Comment by icrosil** [comment]
Hi @xyyjk, it seems both issues are not reproducible anymore, please see videos below.


https://github.com/facebook/lexical/assets/5208565/0f80f35b-9e4a-4430-ac99-a205e8384f1f

https://github.com/facebook/lexical/assets/5208565/deac7be4-3b22-482e-bb22-e563fb87b143

I'm going to close issue, but let us know if there is another way to fail like before, thanks.
