### ISSUE TITLE
Bug: new line at start of heading

### ISSUE THREAD

**Issue by affvalente** [facebook/lexical#4335]
When pressing enter at the start of a heading, Lexical creates a <br> after the ##, rather than add an empty line before the heading which is the expected behaviour

The "##" are not visible so the enter is pressed with the cursor at the start of the visible line

Current outcome:
```
## 
Heading
```

Expected / desired outcome:
```
<empty line>
## Heading
```

Don't think anyone pressing enter for a new line at the start of a heading wants to create a two line heading but rather wants to create more space from the prior paragraph

Thanks

**Comment by acywatson** [comment]
I can't reproduce this in the playground - can you help me with some steps and/or a codesandbox?

**Comment by affvalente** [comment]
> I can't reproduce this in the playground - can you help me with some steps and/or a codesandbox?

Here you go - does this help?
https://user-images.githubusercontent.com/25633523/232400450-add8dda2-316d-46c7-b747-ed9c65201bef.MOV

**Comment by affvalente** [comment]
Just explained, in case the video doesn't work

Open clear playground 
Type

Paragraph
## Heading 2
Paragraph 

Which converts ## to a proper heading and hides the ##


Move cursor just to the left of the H in Heading

Check markdown code for this: it will show

##
Heading 2

**Comment by affvalente** [comment]
Any news on this one?

**Comment by fantactuka** [comment]
Looks like it's the same problem as #4266: on mobile Shift is auto-pressed for a newline, so when hitting enter, it'd be Shift + Enter causing line break instead of new paragraph to be inserted.
