### ISSUE TITLE
CMD + K to trigger link dialog

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#4347]
Ctrl/CMD + K is a common convention to toggle link

**Comment by AnuragBalhra** [comment]
Sounds like a good first issue, I can pick it up if no one else is working on it yet.

**Comment by Slapbox** [comment]
@AnuragBalhra are you planning to work on this? Do you know how the `Ctrl/Cmd+B` are handled for Bold for an example of how to add this?

**Comment by AnuragBalhra** [comment]
Yes I'm starting to work on this. 
I don't already know how to do it but I'll try to investigate how it's done for Ctrl/Cmd+B. If someone already knows any documentation/references about how they are implemented, that would be really helpful.

**Comment by evskorobogatij** [comment]
I do

**Comment by acywatson** [comment]
Closed by #4413
