### ISSUE TITLE
Feature: support Hocuspocus provider in collab (alternative to y-websocket)

### ISSUE THREAD

**Issue by GermanJablo** [facebook/lexical#4351]
In January of this year, the stable release of Hocuspocus was published and made open source, making y-websocket obsolete.

For a comparison of these two solutions and others that are less well known, you can see [this link](https://discuss.yjs.dev/t/meta-post-collection-of-yjs-servers-and-invitation-to-unify-efforts/1623).

Hocuspocus adds support for things like auth, persistence, and scalability.

I have tried using the `CollaborationPlugin` with Hocuspocus without much success.

Among other things [they just added support 3 weeks ago with version 2.0 to Multiplexing](https://github.com/ueberdosis/hocuspocus/releases/tag/v2.0.0). In their words: "Multiplexing allows you to synchronize multiple documents over the same websocket connection. This is especially useful when working with multiple documents at the same time and will make this experience even faster".

From what I can make out of the `CollaborationPlugin` code, it seems to be quite tied to y-websocket and its typescript interface.
AFAIK, every time the document (id) is changed the connection is closed and reopened, not taking advantage of multiplexing.

There has been a conversation about Lexical/Hocospocus [here](https://discord.com/channels/818568566479257641/841708462500085810/1070462618483040368) (Tiptap/Hocuspocus Discord server). One of the maintainers confirmed my suspicions:

> Never used lexical, but in general I think they should not be able to trigger the connect of our provider 🤔
> ... the only think that lexical should do is write to the ydoc, everything else should be done by our hocuspocus provider

Note: I've set up a sandbox repository [here](https://github.com/EgonBolton/collab).

**Comment by Bunkerbewohner** [comment]
It would be great if Lexical supported Hocuspocus (or vice versa, I guess).
 
I'm currently trying to migrate from Tiptap to Lexical, and using the `HocuspocusProvider` which should implement the same y-js Provider protocol as `y-websocket`. It doesn't quite work. 

I see that the `onLoadDocument` and `onStoreDocument` methods on the HocuspocusProvider are called, but Lexical just displays the `initialEditorState` and in `onStoreDocument` I only ever receive the same initial content after each edit.

**Comment by Bunkerbewohner** [comment]
I'm currently migrating from Tiptap to Lexical. The developers behind Tiptap also developed Hocuspocus and that combination just works. I had expected Lexical to also just work with Hocuspocus since that presumably just implements a Yjs Provider protocol just like y-websocket does. 

However, I can't get it to work at all right now. The websocket connection is established and I see the `onLoadDocument` and `onStoreDocument` being called, but always with empty or the initial ydoc, no matter what is changed in the editor.

**Comment by Bunkerbewohner** [comment]
Still debugging what the issue is and maybe I found the root of the problem?
I see two shared types in the Ydoc:

- `"root" => YXmlText`
- `"default" => YXmlFragment`

I think Lexical uses "root" and Hocuspocus (TipTap) use "default", so they're kind of working alongside but unaware of each other.

<img width="504" alt="image" src="https://user-images.githubusercontent.com/500529/235501414-6d8cebd3-1201-400b-a726-d3b495f18976.png">

**Comment by EgonBolton** [comment]
Thanks for your input @Bunkerbewohner !

Apparently it is as you say, hocuspocus satisfies the interface of y-websocket, so it is possible to use it. I've managed to fix a couple of issues I had in the process and it seems to be working even with multiplexing. The implementation can be seen in the repo I posted above.

The problem right now is a bug in which the listeners are fired when changing the document, [as I explain here](https://github.com/facebook/lexical/issues/4517). Did you have it too? Were you able to fix it?

As an additional note, when opening a document the browser console also complains with the following message: "WebSocket connection to 'ws://localhost:1234/' failed: WebSocket is closed before the connection is established." It seems that this is not something inherent to hocuspocus but to CollaborationPlugin, since it also happens to me with y-websocket. Either way, even though at some point the CollaborationPlugin is trying to call the close method early, it doesn't prevent it from working properly AFAICT.

**Comment by davlet61** [comment]
Hi folks! 
I have recently migrated an app using Draftjs to Lexical. It was a bit of work, but so far no regrets.
I am also using `HocusPocusProvider` with `CollaborationPlugin`. 

I was able to handle almost everything, from persisting to loading initial document. However, there seems to be an issue where provider opens multiple connections while using `HocusPocus` 
Some of them are immediately closed, but other still open ( `wss.clients.size` on server also returns same number of connection) 

<img width="1180" alt="Screenshot 2023-06-10 at 00 29 17" src="https://github.com/facebook/lexical/assets/30911739/2569f301-112d-4810-85bc-b1e601bdb5c9">

The open connections drop down to two if I add a `webSocketProvider` to config like this
```javascript
  const websocketProvider = new HocuspocusProviderWebsocket({
    url: WEBSOCKET_ENDPOINT,
    parameters: params,
    connect: false,
  });

  const provider = new HocuspocusProvider({
    url: WEBSOCKET_ENDPOINT,
    name: id,
    document,
    token,
    parameters: params,
    websocketProvider,
  });

  return provider;
```

Works fine with `y-websocket`though when `{ connect: false }`.

**Comment by GermanJablo** [comment]
@davlet61 it seems that you are referring to the "WebSocket is closed before the connection is established" problem that I mentioned above.

I can confirm that using `connect: false` and disabling React's strict mode in most cases gives me two connections.

I've updated [my minimal reproducible example](https://github.com/GermanJablo/collab) as well as the [lexical fork](https://github.com/GermanJablo/lexical/tree/collab) to contain `connect: false` and disable React strict mode. Also on the hocuspocus server I have disabled debounce to make it easier to debug.

Contributions to either of the two repositories are welcome. In both cases `npm run dev` and `npm run collab-server` are required.

Currently these are the problems I ran into:
- The additional ws connection we are talking about (I don't know if it's a major issue as AFAICT doesn't prevent it from working.)
- Changing the document triggers the listeners ([link to the issue](https://github.com/facebook/lexical/issues/4517)).
- In my project the documents get out of sync very soon. This doesn't happen in the two repositories I linked to. Anyway, I haven't debugged this problem yet because I'm focused on the previous one.

**Comment by davlet61** [comment]
> @davlet61 it seems that you are referring to the "WebSocket is closed before the connection is established" problem that I mentioned above.
> 
> I can confirm that using `connect: false` and disabling React's strict mode in most cases gives me two connections.
> 
> I've updated [my minimal reproducible example](https://github.com/GermanJablo/collab) as well as the [lexical fork](https://github.com/GermanJablo/lexical/tree/collab?rgh-link-date=2023-06-12T19%3A11%3A26Z) to contain `connect: false` and disable React strict mode. Also on the hocuspocus server I have disabled debounce to make it easier to debug.
> 
> Contributions to either of the two repositories are welcome. In both cases `npm run dev` and `npm run collab-server` are required.
> 
> Currently these are the problems I ran into:
> 
> * The additional ws connection we are talking about (I don't know if it's a major issue as AFAICT doesn't prevent it from working.)
> * Changing the document triggers the listeners ([link to the issue](https://github.com/facebook/lexical/issues/4517)).
> * In my project the documents get out of sync very soon. This doesn't happen in the two repositories I linked to. Anyway, I haven't debugged this problem yet because I'm focused on the previous one.

@GermanJablo  , thanks for the insight! 
I was able to get only one connection with provider singleton. The problem was/is component re-render which creates a new connection (which is what `StrictMode` does, mount/unmounts components).

**Comment by GermanJablo** [comment]
It is good to hear!
Can you tell what you did differently than [this](https://github.com/GermanJablo/collab/blob/main/src/components/Editor.tsx#L50-L69)? I keep getting 2 connections most of the time with that example.

On the other hand, your use case requires switching between different documents? Have you encountered the second bug?

**Comment by davlet61** [comment]
> It is good to hear! Can you tell what you did differently than [this](https://github.com/GermanJablo/collab/blob/main/src/components/Editor.tsx?rgh-link-date=2023-06-12T19%3A48%3A36Z#L50-L69)? I keep getting 2 connections most of the time with that example.
> 
> On the other hand, your use case requires switching between different documents? Have you encountered the second bug?

So to eliminate multiple connections I used a ref:
```typescript
export function createWebsocketProvider({ id, yjsDocMap }: ProviderOptions) {
  let document = yjsDocMap.get(id);

  if (document === undefined) {
    document = new Doc();
    yjsDocMap.set(id, document);
  } else {
    document.load();
  }

  const WEBSOCKET_ENDPOINT = `${process.env.API_ENDPOINT?.replace('http', 'ws')}/collab`;
  const token = new Token().toString();

  const websocketProvider = new HocuspocusProviderWebsocket({
    url: WEBSOCKET_ENDPOINT,
    connect: false,
  });

  const provider = new HocuspocusProvider({
    url: WEBSOCKET_ENDPOINT,
    name: id,
    document,
    token,
    websocketProvider,
  }) as unknown as Provider;

  return { provider, websocketProvider };
}
``` 

```typescript
 <CollaborationPlugin
	  key={id}
	  id={id}
	  providerFactory={(id, yjsDocMap) => {
	    if (!providerRef.current) {
	      const { provider, websocketProvider } = createWebsocketProvider({
	        id,
	        yjsDocMap,
	      });
	      providerRef.current = provider;
	      websocketProviderRef.current = websocketProvider;
	      return providerRef.current;
	    }
	    return providerRef.current;
	  }}
	  shouldBootstrap={true}
	  username={user?.name}
	  cursorsContainerRef={cursorsContainerRef}
	/>
```

I haven't encountered docs getting out of sync. 
I am also disconnecting in `useEffect` cleanup.

I have another problem though, I am saving to DB in JSON,  but could not figure out how to convert `LexicalState` to `Ydoc` , the content gets duplicated every now and then 🙃

**Comment by jvandenaardweg** [comment]
> I have another problem though, I am saving to DB in JSON, but could not figure out how to properly convert LexicalState to Ydoc , the content gets duplicated every now and then

Been there. The only way around that is to store the YDoc as the Uint8Array/Bytes/Buffer, as stated here: https://tiptap.dev/hocuspocus/guides/persistence#faq-in-what-format-should-i-save-my-document

**Comment by GermanJablo** [comment]
> Also i think this issue can be closed. Lexical works with HocusPocus. 

Yeah. I recommend for more specific problems opening a separate issue.

**Comment by Sagarmikeylevi** [comment]
> Update: I found the root of the problem, and it was my mistake. I see two shared types in the Ydoc:
> 
> * `"root" => YXmlText`
> * `"default" => YXmlFragment`
> 
> <img alt="image" width="504" src="https://user-images.githubusercontent.com/500529/235501414-6d8cebd3-1201-400b-a726-d3b495f18976.png">
> 
> Lexical uses "root" while TipTap used "default", so that's what I was checking on the server and that explains why it always came up empty. To test it, I disabled my custom Hocuspocus persistence extension (which persists the ydoc in the DB) so that there's just the plain hocuspocus server, which is essentially a websocket provider like y-websocket. And on the client side my code looks similar like this:
> 
> function Editor({documentId}: {documentId: string}) {
>     const providerFactory = useMemo( () => (id: string, yjsDocMap: Map<string, Doc>) => {
>       let doc = yjsDocMap.get(id);
>       if (doc === undefined) {
>         doc = new Doc();
>         yjsDocMap.set(id, doc);
>       } else {
>         doc.load();
>       }
> 
>       return new HocuspocusProvider({
>         url: COLLABSERVER_URL,
>         name: id,
>         document: doc,
>       });
>   }, []);
> 
>   return <LexicalComposer initialConfig={initialConfig}>
>     <div id="editorcontent">
>       <RichTextPlugin
>           contentEditable={<ContentEditable/>}
>           placeholder={null}
>           ErrorBoundary={LexicalErrorBoundary}
>       />
>     </div>
>     <CollaborationPlugin
>         id={documentId}
>         providerFactory={providerFactory}
>         shouldBootstrap={true}
>     />
>   </LexicalComposer>
> }
> And this essentially works. Except Awareness doesn't quite (I see short flashes of the cursors only when switching windows right now). Also I didn't test document multiplexing yet. I just create a new Provider whenever the current document changes (my app only ever has one active document at the same time).
> 
> So, [@egonbolton](https://github.com/egonbolton) it seems Lexical and Hocuspocus work together in principle already.



@Bunkerbewohner Hi

So how did  the onLoadDocument() worked for you it still did not work for me
