### ISSUE TITLE
Bug: Experimental Table usually cannot be deleted - and if it is, it breaks undo/redo history

### ISSUE THREAD

**Issue by Slapbox** [facebook/lexical#4352]
Lexical version: Playground (presumably 0.10.0)

## Steps To Reproduce

1. Insert a 5x5 table at the end of the Playground
2. Select it by selecting the blocks before and after
3. User Delete or Backspace keys to try to delete it. The state will show changes but the table will remain
4. Eventually you may succeed at removing the table, but in that case Ctrl+Z and Ctrl+Y will no longer work properly. If the table does get added back (which it usually doesn't) then the entire page will crash

I have tried screencapping this by my videos keep coming back [like this](https://user-images.githubusercontent.com/6835891/232930686-f83867a0-2514-416c-9357-0d2539d8be86.mp4) - sorry - I guess some Linux weirdness.

Link to code example:

https://playground.lexical.dev/

## The current behavior

Removing table should be possible via Backspace, Delete, or at least via a custom method via the toolbar or hotkey

## The expected behavior

Difficult to remove and success corrupts the editor state

**Comment by ivailop7** [comment]
Experimental table got deprecated a few months back.
