### ISSUE TITLE
Bug: Adding custom nodes rerenders sibling nodes

### ISSUE THREAD

**Issue by yjhtry** [facebook/lexical#4356]
When I insert a custom node to the root node, the previous sibling node re-renders

This example displays the rerendered log output in the console

**[This is an example](https://codesandbox.io/p/sandbox/relaxed-river-h6oe24?file=%2FREADME.md)**

Lexical version: 0.9.1 and 0.9.2

## Steps To Reproduce

1. Open example and open console
2. click Insert Scene button

## The current behavior
The sibling node before the new node is rerendered

## The expected behavior
The previous sibling element is not rerendered

**Comment by acywatson** [comment]
I believe the node object is being cloned because the parent is marked dirty when the sibling is inserted. The DOM shouldn't be updated here, so I think this is working as intended.

@zurfyx

**Comment by yjhtry** [comment]
> I believe the node object is being cloned because the parent is marked dirty when the sibling is inserted. The DOM shouldn't be updated here, so I think this is working as intended.
> 
> @zurfyx

However, reinserting the sibling node into the parent node will cause the modification already made on this root node to be lost.

As shown in the figure below, when I call setActive in the program to set the state of the node, the next time I insert the SceneNode, the active of the node will be invalid due to clone
<img width="568" alt="image" src="https://user-images.githubusercontent.com/39440537/233222445-dec2fd7f-fa1f-4b0a-bc81-737c96fec6f1.png">

I had to add an active property to the SceneNode to set the correct state on every createDom call.
So I'm looking for a solution where adjacent children don't re-render

**Comment by acywatson** [comment]
> > I believe the node object is being cloned because the parent is marked dirty when the sibling is inserted. The DOM shouldn't be updated here, so I think this is working as intended.
> > @zurfyx
> 
> However, reinserting the sibling node into the parent node will cause the modification already made on this root node to be lost.
> 
> As shown in the figure below, when I call setActive in the program to set the state of the node, the next time I insert the SceneNode, the active of the node will be invalid due to clone <img alt="image" width="568" src="https://user-images.githubusercontent.com/39440537/233222445-dec2fd7f-fa1f-4b0a-bc81-737c96fec6f1.png">
> 
> I had to add an active property to the SceneNode to set the correct state on every createDom call. So I'm looking for a solution where adjacent children don't re-render

Setting a property on the node is definitely one way to solve this. Then pass that property through on clone. I'd probably avoid modifying the dom outside of createDOM or updateDOM - there's no reason to do that here.

**Comment by yjhtry** [comment]
@acywatson Thank you very much for your answer. I am a novice in lexical. If I want to provide a custom node to modify the internal dom how to do it is the most appropriate
