### ISSUE TITLE
Bug: Can not get caption after Image add caption

### ISSUE THREAD

**Issue by duypham90** [facebook/lexical#4362]
Lexical version:

## Steps To Reproduce

1. Pull repository lexical
2. yarn dev
3. Go to \lexical\packages\lexical-playground\src\Editor.tsx
4. After useEffect add code as below:
```ts
  function handleChange(editor: LexicalEditor) {
    editor.update(() => {
      const rawHTML = $generateHtmlFromNodes(editor, null);
      console.log(rawHTML);
    });
  }
```
5. Add Plusgin as below after  <CollapsiblePlugin />
```ts
<OnChangePlugin onChange={(_, editor) => handleChange(editor)} />
```

## The current behavior
- After insert image we click to add caption
- After add caption and get the html. Caption doesn't include html

## The expected behavior
- In image must have caption text include

**Comment by acywatson** [comment]
You have to teach Lexical how to serialize and deserialize to/from HTML:

https://lexical.dev/docs/concepts/serialization#html

**Comment by duypham90** [comment]
Sorry, I don't know how to export exportDOM for caption after clone https://github.com/facebook/lexical and run yarn dev

**Comment by Kepron** [comment]
> You have to teach Lexical how to serialize and deserialize to/from HTML:
> 
> https://lexical.dev/docs/concepts/serialization#html
> 
> In this case you'd want to change the exportDOM and importDOM on your image node to do whatever you want with the caption.

I tried to edit `importDOM` and `exportDOM`

`exportDOM` was successful, but `importDOM` was a real headache. No matter what I did, I couldn’t get it to work, and it kept me busy for three days. With `exportDOM` I was getting an output like this:

```html
<figure>
  <img src="https://example.com/image.png">
  <figcaption>Example Caption</figcaption>
</figure>
```

But I couldn’t manage to import it. I think some special handling is needed for the figure element, but I don’t understand.

**Comment by etrepum** [comment]
Yes you're right, you will need to write an importer for the figure tag that creates the ImageNode with the caption from the figcaption child.

You shouldn't ask for help on closed GitHub issues. The correct venues are [Discord](https://discord.gg/KmG4wQnnD9) and [github discussions](https://github.com/facebook/lexical/discussions).
