### ISSUE TITLE
Bug: After enabling read-only mode, formatting and history hotkeys no longer work

### ISSUE THREAD

**Issue by Nantris** [facebook/lexical#4365]
Lexical version:

## Steps To Reproduce

1. Open playground.dev.lexical
2. Lock editor
3. Unlock editor
4. Try Ctrl+B or Ctrl+Z. You can see that both will update the `commands` list in the editor state, but nothing is reflected in the editor. If Ctrl+Z does work, it will crash the entire editor

Link to code example:
https://playground.lexical.dev/

## The current behavior

Read-only is forever and causes crashes when disabled.

## The expected behavior

Read-only is toggleable without errors.

**Comment by etrepum** [comment]
Can't reproduce
