### ISSUE TITLE
Bug: Typeahead menu can invisibly appear over elements - but I'm not sure when or why

### ISSUE THREAD

**Issue by Nantris** [facebook/lexical#4366]
Lexical version: playground.lexical.dev

## Steps To Reproduce

1. Unknown
2. Try to click the affected element - you cannot because the typeahead menu placed over the element

![image](https://user-images.githubusercontent.com/6835891/233222572-f81217a1-9c70-4f0d-9ed0-a1c6fc284ff2.png)

Link to code example:

https://playground.lexical.dev

## The current behavior

Typeahead menu can appear and get stuck in random places

## The expected behavior

Typeahead menu never interferes with non-typeahead editor functionality

**Comment by Slapbox** [comment]
> I assume you opened the typeahead element previously at some point during this session?

Not that I recall, but it's possible since merely clicking into the inline code that begins with `@` triggers it:

![image](https://user-images.githubusercontent.com/6835891/233479492-799e400a-2c71-4630-8800-9a49552cfb62.png)

**Comment by Slapbox** [comment]
Related to, but not identical to #3917

**Comment by etrepum** [comment]
Can't reproduce, possibly fixed whenever #3917 was fixed
