### ISSUE TITLE
Bug: Clicking top/bottom padding area of codeblock moves selection to start or end of block

### ISSUE THREAD

**Issue by Slapbox** [facebook/lexical#4368]
Lexical version: playground

## Steps To Reproduce

![image](https://user-images.githubusercontent.com/6835891/233225179-3730c3fc-41f8-435c-96c7-c40e80263ea6.png)

0. Insert a codeblock with any text
1. Click the indicated areas in a codeblock
2. For the top, because it's after the last character I'd expect it to move selection to end of line, but it moves to start of codeblock instead
3. For the bottom, because it's before the first character, I'd expect it to move selection to start of line, but it moves to end of codeblock instead

Link to code example: playground.lexical.dev

## The current behavior

Clicking these areas leads to counter-intuitive selections

## The expected behavior

Clicking these areas should either not do anything, or should move the selection to the nearest area of the nearest line - rather than beginning or end of entire codeblock

**Comment by Slapbox** [comment]
For context, I tested adding padding around a codeblock in Slate and it does not behave this way. If you click in a padded area, it still moves the cursor as intended to the nearest spot in the text rather than the start/end of the block.

**Comment by fantactuka** [comment]
Not sure how it is a problem or an issue, clicking on top moves cursor to the beginning, on the bottom - to the end of code block. Sometimes it could be a misclick and it goes into text node vs padded area of the code block. But overall Lexical does not do anything special around this behaviour and let browser do selection

https://user-images.githubusercontent.com/132642/233720505-2f846f36-3de4-4c52-8cbc-04faf52fbf85.mov

**Comment by Slapbox** [comment]
If I make a regular `<div contenteditable></div>` it behaves as what I see as the intended behavior - not as Lexical does. I still believe this is non-correct behavior based on my testing. Is there something I'm overlooking?

**Comment by Slapbox** [comment]
I re-tested this on my Windows machine and it works properly. This seems to be related to my Linux machine, which reports the `pointerType` as `pen` - which I assume is responsible.

I now agree, there's no issue here. Apologies.
