### ISSUE TITLE
Bug: Toolbar heading dropdown menu not reacting to scroll properly (stays fixed)

### ISSUE THREAD

**Issue by dev23t** [facebook/lexical#4371]
Behavior: 

https://user-images.githubusercontent.com/91459898/233331365-7efc78c4-569b-4d46-b41a-c0d3316926ff.mov

Code: https://codesandbox.io/s/vibrant-nightingale-172df9?file=/src/Editor.js

Expected behavior: Dropdown menu to follow rich text editor position.

Can someone help me with this problem?

**Comment by acywatson** [comment]
Sorry, this is a UI issue, not a lexical one. You can use any number of open source dropdown elements in your toolbar, or you can modify this one to work in your UI context. Unfortunately we just don't have the capacity to help with things like this right now.
