### ISSUE TITLE
Bug: Android backspace removes a character after the caret unless the at the end of a block

### ISSUE THREAD

**Issue by Slapbox** [facebook/lexical#4374]
Lexical version: https://playground.lexical.dev (0.10.0?)

## Steps To Reproduce

1. Open Playground with Android and gBoard
2. Put caret anywhere besides the end of a block and use backspace
3. You will see unexpected characters be removed

Link to code example: https://playground.lexical.dev

## The current behavior

Characters before and after caret are removed

## The expected behavior

Only the character before caret is removed

## Additional context

Can't replicate this in an emulator using my keyboard's backspace button but it occurs if I use the backspace key on the emulator's keyboard.

**Comment by ScottKitchell** [comment]
I'm seeing the the same thing on an Android, on both Gboard and MS SwiftKey.

**It seems to be doing a double delete.** 

If you backspace one character, it will remove the previous character and the next. If you select a 5 letter word and then backspace it will remove the word and the next 5 characters.

**Comment by thegreatercurve** [comment]
I investigated this as part of another issue. It's a bug within Chromium itself. I logged a bug report with them here: https://bugs.chromium.org/p/chromium/issues/detail?id=1403455#c1

Closing this as this should be tracked via Chromium.
