### ISSUE TITLE
Bug: LexicalTableOfContents.prod.js - TypeError: Cannot read property 'scope' of null 

### ISSUE THREAD

**Issue by mbwsims** [facebook/lexical#4385]
Lexical version: 0.9.1

## Steps To Reproduce

1. Occurs during production build
2. Node Version 14.17.6
    React version: 17.0.2

**Comment by fantactuka** [comment]
Prod build works just fine, please provide more details and reopen issue if still a problem

```
➜  lexical git:(delete-sibling-element) npm run build-prod
```

**Comment by mbwsims** [comment]
Continuing to get the same error. It's possible that it's specific to my environment, but no other Lexical module has caused any issues. Table of Contents works fine in dev. Also tried Lexical 0.9.2 and 0.10.0, but the error persists. Let me know if you have any ideas of suggestions. Thanks!
