### ISSUE TITLE
Feature: Comments should synchronize to document updates

### ISSUE THREAD

**Issue by zignis** [facebook/lexical#4397]
The text slice citation inside the comment should be updated as the relevant highlighted text changes, and it should show an empty/error state (such as 'text not available' or 'text removed') when the original text is not available or has been removed. Currently, it only shows the static version of the highlighted text slice. One possible solution is to use the selection range instead of directly inserting the text inside the comment, and listen for document updates. I think this would be pretty straightforward.

**Comment by acywatson** [comment]
It's not clear to me that this is how it should work - if I totally change the text that someone commented on, why would I want to see a reference to the new text in the comment? Then you've lost the context associated with the original comment, which is the point of taking that snapshot of the commented-on text in the first place.

I also don't think this is very straightforward to implement, but I may be wrong here. Either way, this is just the playground implementation and I don't think there's any reason to change it, tbh. Individual editors can implement commenting however they want.

**Comment by zignis** [comment]
> It's not clear to me that this is how it should work - if I totally change the text that someone commented on, why would I want to see a reference to the new text in the comment? Then you've lost the context associated with the original comment, which is the point of taking that snapshot of the commented-on text in the first place.
> 
> I also don't think this is very straightforward to implement, but I may be wrong here. Either way, this is just the playground implementation and I don't think there's any reason to change it, tbh. Individual editors can implement commenting however they want.

I somewhat agree with this, but a label such as "outdated citation" under the comment might be helpful as there would be no target to scroll to when the citation is clicked (which is the default behavior). I won't reopen this issue as I feel this would be too specific for the playground, but I welcome your views on this.
