### ISSUE TITLE
Bug: paragraph removed  when the last character of the first paragraph was deleted

### ISSUE THREAD

**Issue by yaojiu19** [facebook/lexical#4406]
Lexical version: 0.10.0

Link to code example:
![Apr-25-2023 17-55-04](https://user-images.githubusercontent.com/18085334/234242054-64d9a1bc-4c52-4607-bd84-957601eab02a.gif)

**Comment by acywatson** [comment]
Seems like this only occurs under certain conditions shown in the video. Perhaps related to canBeEmpty/existence of the blockquote directly below.

**Comment by yaojiu19** [comment]
> Seems like this only occurs under certain conditions shown in the video. Perhaps related to canBeEmpty/existence of the blockquote directly below.

its easy to occur

![Apr-27-2023 13-35-14](https://user-images.githubusercontent.com/18085334/234768710-43a58357-537e-44ae-ae8a-713471ecc07e.gif)
