### ISSUE TITLE
Bug: Weird resizing and scrollbar on load of editor

### ISSUE THREAD

**Issue by quick007** [facebook/lexical#4410]
Lexical version: ^0.10.0

## Steps To Reproduce

1. Create a lexical editor
2. Set it with content, like this
```ts
useEffect(() => {
		editor.setEditable(editable);
		if (initialState || initialStateEditor) {
			if (
				(
					editor.getEditorState().toJSON().root.children[0] //@ts-expect-error Lexical types r bad
						.children as unknown[]
				).length == 0
			)
				editor.setEditorState(
					initialStateEditor ||
						editor.parseEditorState(
							initialState as unknown as SerializedEditorState
						)
				);
		}
	}, [editable, initialState, updatedState, initialStateEditor]);
```

Link to code example: https://gist.github.com/quick007/d9de3c1d71bc5d66e5adf1f483d455fe

## The current behavior

Heres a video of the issue: https://streamable.com/4kti7q

Look specifically at what happens with the scrollbar on the right when I switch pages. For a second, it gets really long for some reason.

## The expected behavior

The editor shouldn't have that weird scaling issue.

**Comment by thegreatercurve** [comment]
From a quick glance, it appears that you empty the editor state, hence the check to ensure that the nodes are 0, and then set the right editor state. I think this is likely causing he editor to return to some kind of mind height? If not, I don't think this is a bug specifically related to Lexical core.

**Comment by quick007** [comment]
@thegreatercurve That is my assumption too. I had assumed that someone else had encountered this bug too so we might be able to pinpoint it. I can create a minimal repro if thats helpful
