### ISSUE TITLE
Feature: Allow infinite list nesting

### ISSUE THREAD

**Issue by Slapbox** [facebook/lexical#4412]
This may already be possible, but I can't see how. The Playground is limited to 6 levels of nesting but I can't figure out what defines the maximum nesting allowed.

Can anyone provide a pointer? Or is this really a limitation of Lexical itself currently?

**Comment by acywatson** [comment]
https://github.com/facebook/lexical/blob/30b41877703e8f6da22046b37c1117b9e960c820/packages/lexical-playground/src/Editor.tsx#L186
