### ISSUE TITLE
Bug: editor crashes when selecting list item preceding divider

### ISSUE THREAD

**Issue by montlebalm** [facebook/lexical#4416]
There's a bug in the playground where double-clicking the last list item before a divider crashes the editor and floods the console with lexical error 68. 

https://user-images.githubusercontent.com/739390/234598342-e462e206-d0c7-4b69-97a2-9fb69262cd83.mov

Lexical version: 0.10.0

## Steps To Reproduce

1. Create a list with one or more items
2. Create a divider directly below the list
3. Double click the last word of the last list item

Link to code example: https://playground.lexical.dev/

## The current behavior

The editor crashes with a flood of errors.

## The expected behavior

The editor should not crash and the double-clicked word should be selected.

**Comment by acywatson** [comment]
I can repro - looks like you need to click just after the end of the text. Clicking in the middle works normally for me.

https://lexical.dev/docs/error?code=68

getNodesBetween: ancestor is null

**Comment by flex-junwoo** [comment]
any update here?
