### ISSUE TITLE
Bug: Code blocks in generated html looses their formatting.

### ISSUE THREAD

**Issue by panditraghav** [facebook/lexical#4417]
When rendering html generated from `$generateHtmlFromNodes(editor)`, the code blocks in generated html looses their formatting because the `code` element is not inside a `pre` element.

Lexical version: 0.10.0

[Screencast from 26-04-23 07:27:35 PM IST.webm](https://user-images.githubusercontent.com/90890063/234599256-c678e2f1-6bb8-4a59-a7e4-2c9b3ac02143.webm)

Adding exportDOM method to `CodeNode` fixes the problem.
```ts
  exportDOM(editor: LexicalEditor): DOMExportOutput {
    const theme = editor._config.theme?.code;
    const codeElement = document.createElement('code');

    return {
      element: codeElement,
      after: (generatedElement: HTMLElement | null | undefined) => {
        if (generatedElement) {
          const preElement = document.createElement('pre');
          const codeElement = document.createElement('code');
          const spans = generatedElement.querySelectorAll('*');
          addClassNamesToElement(codeElement, theme);

          spans.forEach((span) => {
            codeElement.appendChild(span);
          });

          preElement.appendChild(codeElement);
          return preElement;
        }
        return undefined;
      },
    };
  }

```

## The current behavior
In generated html code blocks looses their formatting.
## The expected behavior
Code should retain it's formatting when rendering generated html.

**Comment by panditraghav** [comment]
Oh I got it, it's not a bug it's a feature😅

**Comment by acywatson** [comment]
> Oh I got it, it's not a bug it's a feature😅

Hehe, I think so - I appreciate the report anyway. I might consider it a bug if there was evidence that this is inconsistent somehow with conventional HTML transfer structure for code blocks between editors (to the extent there is a convention). Like, if GDocs, Github, VSCode, and JetBrains were all wrapping code in a pre tag, then I'd say maybe we need to change our default behavior.
