### ISSUE TITLE
Bug: ParagraphNode's children not copied when using $copyNode (possibly related to exportJSON())

### ISSUE THREAD

**Issue by RyoSogawa** [facebook/lexical#4419]
Hello,

I'm not sure if this is a bug or not, but I encountered an issue and would appreciate some guidance. Here are the details:

I'm trying to create a duplicate of a ParagraphNode, but when I use `$copyNode`, it results in an empty ParagraphNode. 
Also, I'm wondering if this might be related to the fact that `ParagraphNode.exportJSON()` returns an empty array for children.

Is this by design, and is there another way to handle this?
Thank you in advance for your assistance.

Lexical version: 0.10.0

## Steps To Reproduce

1. add buttons to playground
```tsx
<button
  onClick={() => {
    editor.update(() => {
      const root = $getRoot();
      const paragraphNode = $createParagraphNode();
      const textNode = $createTextNode('Hello world');
      paragraphNode.append(textNode);
      root.append(paragraphNode);
    });
  }}>
  add paragraph
</button>
<button
  onClick={() => {
    editor.update(() => {
      const root = $getRoot();
      const lastChild = root.getLastChild();
      if (!lastChild) return;
      const copy = $copyNode(lastChild);
      root.append(copy);
    });
  }}>
  duplicate
</button>
```

2. click button `add paragraph` -> `duplicate`

## The current behavior
ParagraphNode is copied but contents is empty (The following is the contents of the debug view)

```
 root
  ├ (3) paragraph  
> | └ (4) text  "Hello world"
  └ (5) paragraph  
```

## The expected behavior
I would like it to be copied with the following structure
```
 root
  ├ (3) paragraph  
> | └ (4) text  "Hello world"
  └ (5) paragraph  
     └ (6) text  "Hello world"
```

**Comment by acywatson** [comment]
$copyNode copies just the node, not it's children. For a deep copy, you'd need something like this:

https://github.com/facebook/lexical/pull/4230

@zurfyx

**Comment by RyoSogawa** [comment]
@acywatson (@zurfyx )
Thank you so much for your help! Your suggestion worked perfectly, and I was able to resolve the issue.

For future reference and anyone else who might encounter a similar issue, I made a slight modification to the code you provided:

```diff
export function $copyNodeDeep<T extends LexicalNode>(node: T): T {
  const nodeCopy = $copyNode(node);
  const stack: Array<[LexicalNode, LexicalNode]> = [[node, nodeCopy]];
  let stackLength: number;
  while ((stackLength = stack.length) > 0) {
    for (let i = 0; i < stackLength; i++) {
      const tuple = stack.shift();
      if (tuple !== undefined) {
        const [currentNode, currentNodeCopy] = tuple;
        if ($isElementNode(currentNode) && $isElementNode(currentNodeCopy)) {
          const children = currentNode.getChildren();
          for (const child of children) {
            const childCopy = $copyNode(child);
+            if ($isTextNode(child) && $isTextNode(childCopy)) {
+              childCopy.setFormat(child.__format);
+              childCopy.setStyle(child.__style);
+            }
            currentNodeCopy.append(childCopy);
            stack.push([child, childCopy]);
          }
        }
      }
    }
  }
  return nodeCopy;
}
```

Once again, I really appreciate your assistance. Have a great day!
