### ISSUE TITLE
Feature:  HTML content hook

### ISSUE THREAD

**Issue by c-mella** [facebook/lexical#4427]
I'm using Lexical as a editable text framework for an app that ingests and exports html text blocks (p tags & spans), it would be great if there were an HTML content hook or plugin that allowed you to set the html content and automatically export it. The solutions i've found online usually have you insertingNodes after converting them but this can result in duplicative text to the point that if you mess up you'll cause an infinite loop when the app re-renders.

**Comment by acywatson** [comment]
I'm not totally clear on what you're trying to achieve that can't already be trivially done with the html primitives we provide. Is generateHtmlFromNodes exports HTML, generateNodesFromDom imports it. Is it just about wrapping that in a hook for your specific use case?

**Comment by c-mella** [comment]
Sorry let me provide more context into my use-case and the larger feature I was requesting.

BACKGROUND: I'm working on a headless cms for a project and i'm using Lexical as the conduit to display, edit, and update the text elements on the pages. 

As such I'm trying to figure out the best way to load the html content dynamically in the editor, currently i'm doing it by creating a local copy of the string, converting it to nodes, and then inserting that into the editor using editor.update. However this has a couple of drawbacks:
a) anytime the app re-renders it adds the text again leading to duplicates
b) I'm also trying to house variants of the text for things like breakpoints and conditions and at the moment I can't swap out content without either destroying the instance and starting again or using the method above and getting other content.

As for the exporting that works fine, it's mostly a nice-to-have if we're ingesting to also have an export feature.


FEATURE DESCRIPTION:  Have a more user-friendly hook, service, or plugin to take an html string and use it as the editor content, likewise it would be great to be able to swap out the content in the case of having multiple values or having a value swap happen in the application.  For example, if i'm showing variant A of the text and I want to switch to variant B there should be a replaceContent function that work more seamlessly.

**Comment by c-mella** [comment]
@acywatson Just wanted to confirm you saw this

**Comment by eneroth** [comment]
I haven't worked with Lexical yet, I'm just investigating it for a potential use-case. 

Isn't the basic functionality provided by `setEditorState`. Maybe I'm assigning it properties that it doesn't have, but it sounds like you should be able to swap the state with this. Doing so with HTML would involve bouncing it through a couple of functions, I'd assume.

I'm interested in the answer to this since it would definitely be a requirement to arbitrarily swap the editor content for what I have in mind.

**Comment by acywatson** [comment]
> Doing so with HTML would just involve bouncing it through a couple of functions, I'd assume.

@eneroth Basically, yes - $generateNodesFromHtml returns an array of LexicalNodes, but not a full EditorState. You'd probably just clear the RootNode and then append that array to the RootNode rather than creating a new state and calling setEditorState.

**Comment by c-mella** [comment]
Hey @acywatson, what's the best way to clear the root node? I think that would solve my issue, currently i'm updating the editor once a new value comes in but i'm getting a duplicate so clearing the node between updates would probably clear that up.

**Comment by acywatson** [comment]
> Hey @acywatson, what's the best way to clear the root node? I think that would solve my issue, currently i'm updating the editor once a new value comes in but i'm getting a duplicate so clearing the node between updates would probably clear that up.
> 
> CODE FOR REFERENCE: ` useEffect(() => { if (!text) return;
> 
> ```
>     editor.update(() => {
>         const parser = new DOMParser();
>         const dom = parser.parseFromString(text, "text/html");
> 
>         const nodes = $generateNodesFromDOM(editor, dom);
> 
>         $getRoot().select();
> 
>         const selection = $getSelection();
> 
>         selection?.insertNodes(nodes);
>     });
> }, [editor, text]);
> ```
> 
> `

$getRoot.clear()

https://lexical.dev/docs/faq#how-do-i-clear-the-contents-of-the-editor

**Comment by c-mella** [comment]
Thank you so much
