### ISSUE TITLE
CMD + Left Arrow doesn't work on white space

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#4433]
Double hop is intended when you have `(space)code(caret)`, but the second time you press CMD + Left it does nothing

https://user-images.githubusercontent.com/193447/235378494-c24d970a-1618-457e-a17a-2a766b860543.mov

**Comment by aquarius-wing** [comment]
I cannot reproduce your step on [Playground](https://playground.lexical.dev/).
Which version of your lexical?
Can you provide a sandbox link?

**Comment by zurfyx** [comment]
> I cannot reproduce your step on [Playground](https://playground.lexical.dev/). Which version of your lexical? Can you provide a sandbox link?

Sorry, forgot to attach PR
