### ISSUE TITLE
Feature: Table Resizing

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#4440]
The current behaviour is: upon resizing the last column (dragging the right table border), it reflows the column widths preserving the width of the table to 100%, rather than actually shrinking the table to take less width overall. It would be great if it actually resized the table to take less space.

**Comment by karam-qaoud** [comment]
@ivailop7 thanks for reporting this issue! It seems like this behavior isn't native to lexical table resizing (table plugin). It could be easily customizable by providing a different theme via the initialConfig of the editor. Here's a quick fix for it #4775

**Comment by ivailop7** [comment]
I can't believe the fix was that simple! Thank you for fixing this!
