### ISSUE TITLE
Bug: Copying (cmd+c) doesn't work properly when editable is false

### ISSUE THREAD

**Issue by SamCB-CT** [facebook/lexical#4446]
Lexical version: 0.9.1

## Steps To Reproduce

As per the codesandbox example below:

1. Have a node set to editable, the other without it
2. Optionally, a custom node with `getTextContent()` overwritten so you can see plaintext changes.
3. Copy from the text field
4. Paste into a clipboard inspector (such as: https://evercoder.github.io/clipboard-inspector/)

Link to code example:

https://codesandbox.io/s/quizzical-tristan-o459jr?file=/src/App.tsx

## The current behavior

Copying from the enabled editor, paste into the clipboard inspector will result in:

```
text/plain:  A VALUE THAT WILL BE UPPERCASE WHEN COPIED.
text/html:   <meta charset='utf-8'><span>A value that will be uppercase when copied.</span>
application/x-lexical-editor:
             {"namespace":"MyEditor","nodes":[{"detail":0,"format":0,"mode":"normal","style":"","text":"A value that will be uppercase when copied.","type":"shouting-text","version":1}]}
```

Copying from the editor with editable set to false will only copy the actual value from within the div box, no reformatting, no custom clipboard behaviour.

```
text/plain:  But this will not be uppercase when copied.
text/html:   <meta charset='utf-8'><div id="root" style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="App" style="font-family: sans-serif; line-height: 2rem;"><div aria-autocomplete="none" contenteditable="false" spellcheck="true" data-lexical-editor="true" style="user-select: text; white-space: pre-wrap; word-break: break-word;"><p class="editor-paragraph ltr" dir="ltr" style="text-align: left; margin: 0px 0px 15px; position: relative;"><span data-lexical-text="true">But this will not be uppercase when copied.</span></p></div></div></div>
```

## The expected behavior

Copying from the editor, regardless of setting, results in the appropriate formatting and custom clipboard behaviour:

```
text/plain:  A VALUE THAT WILL BE UPPERCASE WHEN COPIED.
text/html:   <meta charset='utf-8'><span>A value that will be uppercase when copied.</span>
application/x-lexical-editor:
             {"namespace":"MyEditor","nodes":[{"detail":0,"format":0,"mode":"normal","style":"","text":"A value that will be uppercase when copied.","type":"shouting-text","version":1}]}
```

## Exploration

According to: 

https://github.com/facebook/lexical/blob/970fba28337b311784084f9649395a77a12258b9/packages/lexical/src/LexicalEvents.ts#L1161-L1166

It appears to be that the copy event is only dispatched when editing is enabled. While it probably makes sense that most events are disabled, I'd imagine that copy is a reasonably safe exception to that rule?

**Comment by acywatson** [comment]
Yea, I think it is a safe exception. Unfortunately there's not a pre-existing pattern for registering some of those events when editable is false, so we'll need to build that path.

**Comment by etrepum** [comment]
As far as I can tell this is fixed, the isEditable condition is lifted to individual events. For example, it will stop a cut or paste but not a copy. #6232
