### ISSUE TITLE
Bug: CMD + Backspace doesn't delete a custom node text 

### ISSUE THREAD

**Issue by abhagsain** [facebook/lexical#4452]
Lexical version: ^0.10.0

## Steps To Reproduce

1. Create a custom text node (Codesandbox attached below)
2. Try to delete the whole line using CMD + Backspace (This shortcut deletes the entire line)
3. The node doesn't get deleted, in the Codesandbox it doesn't show any errors but on local the error says `Error: Lexical node does not exist in active editor state. Avoid using the same node references between nested closures from editorState.read/editor.update.`

Core nodes are getting deleted without any errors.

Windows doesn't have a shortcut to delete the entire line but word by word using Ctrl + Backspace (Windows) and Option + Backspace (Mac) works fine

Link to code example:

[CodeSandBox URL](https://codesandbox.io/s/competent-panna-njskot?file=/src/Editor.tsx)

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/36589645/236184083-48a3e64c-119f-4085-8e97-f88d517dd5da.png">

## The current behavior

The text line doesn't get deleted

## The expected behavior

The text line should get deleted

**Comment by trueadm** [comment]
You've not setup your custom node correctly. Your clone method isn't setup correctly, nor is your constructor. Here is the fix:

https://codesandbox.io/s/pensive-tree-rkhfun

Specifically, you need to be passing in the key between clones, as this must be consistent and stable:

```js
  static clone(node: CustomTitle): CustomTitle {
    return new CustomTitle(node.__id, node.__placeholder, node.__key);
  }
```

Plus your constructor needs to accept this value:

```js
  constructor(id: string, placeholder = "Add a title", key: string) {
    super(key);
    this.__placeholder = placeholder;
    this.__id = id;
  }
```
