### ISSUE TITLE
Support div on paste

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#4465]
```
<div>
a
</div>
<div>
b
</div>
```

Should return 
```
a
b
```

instead of `       a              b       `

**Comment by Liakhov** [comment]
any progress on this issue?

**Comment by potatowagon** [comment]
Issue: when copy pasting from html articles, block content such as `<div>` loose its formatting and appear inline.

## Repro
1. Paste this into codepen (to generate the html)
```
<div>
a
</div>
<div>
b
</div>
```
2. copy the generated html. it should look like this
```
a
b
```
3. paste into lexical. content appears inline
```
ab
```
expected:
```
a
b
```
