### ISSUE TITLE
Bug: merging two merged cell --> Error #19: selection has been lost

### ISSUE THREAD

**Issue by bilobom** [facebook/lexical#4470]
When merging two merged cells , the following error happens: 

`updateEditor: selection has been lost because the previously selected nodes have been removed and selection wasn't moved to another node. Ensure selection changes after removing/replacing a selected node.`

Lexical version: latest on playground

## Steps To Reproduce

https://user-images.githubusercontent.com/19841175/236870912-cabf1288-148c-4c4b-b31e-25e3a3a8c2c5.mp4

**Comment by zurfyx** [comment]
Can't repro but likely fixed in the last batch of table fixes. Feel free to reopen the issue otherwise.
