### ISSUE TITLE
Feature: LexicalNode select itself

### ISSUE THREAD

**Issue by Darcrandex** [facebook/lexical#4473]
The Class: LexicalNode has [selectNext](https://lexical.dev/docs/api/classes/lexical.LexicalNode#selectnext) method, but can not select itself.

when I get the node by nodeKey, how can I select the node?

```javascript
const node = $getNodeByKey(nodeKey)
// node?.setSelected()
```

**Comment by ivailop7** [comment]
What are you trying to do? If you already have a reference to the node itself, why do you need to self-select it?

**Comment by Darcrandex** [comment]
@ivailop7  Thanks, there is a demo [lexical-node-select](https://github.com/Darcrandex/lexical-node-select.git), maybe it helps.

I need to achieve two requirements
1. [select on created](https://github.com/Darcrandex/lexical-node-select/blob/f87878312f482590095bdd76ef24a0e864cba26d/src/components/MyEditor/plugins/CustomContent/Plugin.ts#L26)
2. [select when data got](https://github.com/Darcrandex/lexical-node-select/blob/f87878312f482590095bdd76ef24a0e864cba26d/src/App.tsx#L39)

**Comment by ivailop7** [comment]
you can do: 'node.select();'

**Comment by Darcrandex** [comment]
Thanks, but [LexicalNode](https://lexical.dev/docs/api/classes/lexical.LexicalNode) doesn't provide such an API, does it?
```javascript
console.log(node.select) // undefined
```

**Comment by ivailop7** [comment]
Should be 'select()', but yes, it's available on nodes extending ElementNode or TextNode, DecoratorNode doesn't have it, since you can have basically anything anything inside a DecoratorNode having the native selection work, if actually not as trivial.

**Comment by Darcrandex** [comment]
That's a good suggestion, thanks.
