### ISSUE TITLE
Bug: Editor is focused when the initialConfig editorState converts from markdown and registerNodeTransform has been used

### ISSUE THREAD

**Issue by darsee** [facebook/lexical#4474]
In the codesandbox linked below, the editor is focused on mount when the `initialConfig` `editorState` converts a markdown heading and `registerNodeTransform` has been used. Is this expected?

Lexical version: 0.10.0

## Steps To Reproduce

1. Open the codesandbox below
2. Observe that the editor is initially focused (cursor is visible)
3. Change `value` to `test` (uncomment line 27)
4. Reload the browser preview, observe that the editor is _not_ focused (cursor is not visible)
6. Change `value` back to `# test` and comment out `<TestPlugin />`
7. Reload the browser preview, observe that the editor is _not_ focused (cursor is not visible)

Link to code example:

https://codesandbox.io/s/lexical-editor-focused-after-node-transform-sfm1wn?file=/src/Editor.js

## The current behavior

On reloading the browser preview, the editor is initially focused (cursor is visible).

## The expected behavior

I expect the editor not to be initially focused unless using `@lexical/react/LexicalAutoFocusPlugin`?

**Comment by darsee** [comment]
Hey @aquarius-wing, thanks for the PR!

I don't think it solves the issue for me though - the problem in the scenario above is that the editor _is_ focused when it loads but I am expecting it _not_ to be focused until I click it. Your PR (if I understand correctly) causes the editor to be focused even if the markdown conversion doesn't match on anything - I'm not sure if this behaviour would be expected.

**Comment by aquarius-wing** [comment]
So, is it possible that I misunderstood your meaning? I thought you wanted the focus to be only when text is inputted. So, you mean the opposite, that even when '# text' is inputted, it should not be focused? I'm quite confused. 😂

**Comment by aquarius-wing** [comment]
I feel that it should be up to the lexical official to determine whether a separate configuration item is needed to control whether to auto-focus.

**Comment by danchurch-alphasights** [comment]
Hi @darsee!

I ran into a very similar problem with `$convertFromMarkdownString` recently.

I was able to work around it by:
```Javascript
useEffect(() => {
  // Set the editor to not editable - it won't take focus while in that state
  editor.setEditable(false);

  const unregister = editor.registerNodeTransform(TextNode, (textNode) => {
    console.log("node transformed", textNode);
  });

  // Set the editor back to editable a frame later
  requestAnimationFrame(() => editor.setEditable(true));

  return unregister;
}, [editor]);
```

<details>
  <summary>The pattern could be encapsulated in a function to use in multiple places</summary>

<br />
The code sandbox was in Javascript, so I put the types in comments

```Javascript
const whileEditorDisabled = /* <R> */(editor /* : LexicalEditor */, fn /* : () => R */) /* : R */ => {
  editor.setEditable(false);

  const value = fn();

  requestAnimationFrame(() => editor.setEditable(true));

  return value;
};
```

Usage:
```Javascript
useEffect(() => {
  return whileEditorDisabled(editor, () => editor.registerNodeTransform(
    TextNode,
    (textNode) => console.log("node transformed", textNode)
  ));
}, [editor]);
```

</details>

Using this pattern in the code sandbox seems to work!

Probably not a perfect solution, but hopefully it's able to help you with a short-term solution

**Comment by darsee** [comment]
Hey @danchurch-alphasights!

Thanks a lot for the input - this looks like a very clever workaround.

I need to see if I can apply it to my actual use case where `registerNodeTransform` is called inside `useAutoLink` in `LexicalAutoLinkPlugin`:

https://github.com/facebook/lexical/blob/5595519202f9241e3e2b8ab3b240c787c58484e2/packages/lexical-react/src/LexicalAutoLinkPlugin.ts#L293-L309

My current workaround is to conditionally use `AutoLinkPlugin` only if the editor is focused (which we track in state for other reasons anyway) but that feels very hacky.

**Comment by vedkribhu** [comment]
Any updates here? This is very irritating issue as registerNodeTransform is focusing the editor. The workaround mentioned above are hacky and leads to more issues where we have to track focus state of the editor to ensure consistent behaviour.

**Comment by nikitastryuk** [comment]
+1
looks like there is no way to set initial value without focusing the editor

**Comment by vmihda** [comment]
Hey, try this
```
editor.update(() => {
	firstLoad.current = alwaysUpdate;
	const parser = new DOMParser();
	const dom = parser.parseFromString(initialContent, 'text/html');
	const nodes = $generateNodesFromDOM(editor, dom);
	$getRoot().append(...nodes);
});
```

**Comment by etrepum** [comment]
I think this should all be sorted out in #6894 - either by default, or by adding the skip-dom-selection tag strategically to updates where you don't want to the editor to be focused.

**Comment by darsee** [comment]
@etrepum Thank you! ❤
