### ISSUE TITLE
Feature: Allow matcher funcion for markdown transformers

### ISSUE THREAD

**Issue by davbrito** [facebook/lexical#4481]
Only regexp can be used as matchers for Transformers on @lexical/markdown

The only way i've found is making very complex regexes, or instead very loose regexes and then matching on the replace function.

**Comment by RavenColEvol** [comment]
@davbrito I would like to get more feedback from you to exactly understand the requirement so that a good PR that solves this issue can be made.
Could you provide us some example of your today's flow of code versus what you feel should be like?

**Comment by GermanJablo** [comment]
This issue does not adequately describe a problem nor does it propose an alternative. Since it is not actionable, can someone from the Lexical team please close it?
