### ISSUE TITLE
Bug: nested list html format

### ISSUE THREAD

**Issue by annarichardson-dt** [facebook/lexical#4484]
The $generateHtmlFromNodes returns unexpected nested list format html. I would expect the nested list format to follow best practices as seen [here](https://www.w3schools.com/html/html_lists_ordered.asp)
```
<ol>
  <li>Coffee</li>
  <li>Tea
    <ol>
      <li>Black tea</li>
      <li>Green tea</li>
    </ol>
  </li>
  <li>Milk</li>
</ol>
```

This causes problems for the html to not be in expected format.

Lexical version: 0.9.1

## Steps To Reproduce
Type a nested list into the editor like so
![Screenshot 2023-05-10 at 12 27 11 PM](https://github.com/facebook/lexical/assets/84400902/8cbfb8b5-6f0d-45ec-8679-b6c7afbcf553)

You will need to have the ListPlugin and TabIndentationPlugin if you want to be able to use nested lists.

## The current behavior
The html using $generateHtmlFromNodes from the editor is 
```
<ul class="editor-list-ul">
  <li class="editor-listitem" value="1">
    <span>one</span>
  </li>
  <li class="editor-listitem" value="2">
    <span>two</span>
  </li>
  <li class="editor-listitem editor-nested-listitem" value="3">
    <ul class="editor-list-ul">
      <li class="editor-listitem" value="1">
        <span>nested three</span>
      </li>
     <li class="editor-listitem" value="2">
       <span>nested four</span>
     </li>
    </ul>
  </li>
</ul>
```

## The expected behavior
I would like it to return properly nested list format like
```
<ul class="editor-list-ul">
  <li class="editor-listitem" value="1">
    <span>one</span>
  </li>
  <li class="editor-listitem" value="2">
    <span>two</span>
    <ul class="editor-list-ul">
      <li class="editor-listitem" value="1">
        <span>nested three</span>
      </li>
     <li class="editor-listitem" value="2">
       <span>nested four</span>
     </li>
    </ul>
  </li>
</ul>
```

**Comment by acywatson** [comment]
Please see this issue: https://github.com/facebook/lexical/issues/2951

I'm aware of this, but there are limitations to the semantics of HTML here. We should work to fix this soon. In the meantime, you can completely control how lists are represented in serialized HTML via exportDOM methods on ListNode and ListItemNode.
