### ISSUE TITLE
Comment doesn't get removed from comment sidebar on undo

### ISSUE THREAD

**Issue by jspaargaren** [facebook/lexical#4488]
Lexical version: current on Playground

## Steps To Reproduce

1.  add comment
2. undo

## The current behavior

User adds a comment
![image](https://github.com/facebook/lexical/assets/40719991/2de03cde-b720-46d0-bab9-134f6f3e3a10)

User clicks on "undo" arrow in header menu

Comment highlighting is removed from editor, but not removed from sidebar...

![image](https://github.com/facebook/lexical/assets/40719991/36c4e4f8-59bf-432d-a060-28731dd178d4)

## The expected behavior

Comment should also be removed from sidebar

**Comment by acywatson** [comment]
This is a surface-by-surface decision, and I while I don't disagree with you that it's a sane way for a commenting system to behave, the playground doesn't need to implement all this to demonstrate how commenting can work with Lexical.
