### ISSUE TITLE
Feature: How do I insert a component on the line where the caret is located?

### ISSUE THREAD

**Issue by ymgn-dev** [facebook/lexical#4494]
I want to display a button next to the text editor that follows the line where the caret is located. 
I see that there is an `insertText` function in the RangeSelection obtained from `const selection = $getSelection();`, but it doesn't seem to be able to insert complex things like React components.

Is there any other smart solution?
I am considering building a UI like the one shown in the attached video.

<video src=https://github.com/facebook/lexical/assets/35668159/971b2a51-d5b0-49a0-bbdd-d05e2ac03350 width=240px />

**Comment by acywatson** [comment]
Did you look at selection.insertNodes?
