### ISSUE TITLE
Bug: selection has been lost error is raised when selecting text next to decorator nodes

### ISSUE THREAD

**Issue by tiagoamaro** [facebook/lexical#4499]
Lexical version: 0.10.0

## Steps To Reproduce

1. Go to the Lexical playground
2. Delete everything
3. Write any text (e.g.: "foo")
4. Insert a horizontal rule right after the text
    * The `HorizontalRuleNode` is a decorator node. This bug also happens placing a `StickyNode`, but it's easier to visualize with the horizontal rule  
6. Double click your text at the end of the paragraph
    * Notice how your `focus` key from your `$getSelection()` now points to `root` 
8.Delete the node
9. You will see the following error:

```
updateEditor: selection has been lost because the previously selected nodes have been removed and selection wasn't moved to another node. Ensure selection changes after removing/replacing a selected node.
```

## The current behavior

Here's a screencast on how you can reproduce the error:

[Screencast 2023-05-15 12:10:57.webm](https://github.com/facebook/lexical/assets/1538066/e6298417-9b70-4650-bda4-8dec64f61f45)

## The expected behavior

Do not raise errors when selecting text next to decorator nodes.

## More context

I'm working in a project where we are implementing several decorator nodes with the `isInline` static method set to `false`. They are meant to be entire blocks occupying lines.

This issue frequently happens while our users are using Lexical to manipulate paragraphs that are next to our custom decorator nodes.

I tried to investigate how Lexical `$getSelection` and its focus works and the reasoning why the range selection is loosing focus when double clicking / selecting some pixels before a decorator node, but I couldn't identify the issue.

**Comment by etrepum** [comment]
Can not reproduce with current lexical
