### ISSUE TITLE
Bug: Unmerge merged cells deforms the table

### ISSUE THREAD

**Issue by bilobom** [facebook/lexical#4505]
unmerging cells that spans multiple rows after merging them deforms the sape of the table. see the video bellow 

Lexical version:1.10.0

## Steps To Reproduce

https://github.com/facebook/lexical/assets/19841175/71a90c22-2c66-4a56-bc2e-c126266bc1c3

**Comment by ivailop7** [comment]
This has been fixed. Closing.
