### ISSUE TITLE
Bug: TableRowNode and TableCellNode's `importDom` methods don't take into account the element's height and width respectively

### ISSUE THREAD

**Issue by GMchris** [facebook/lexical#4518]
Every transformation (exportDOM, importJSON, exportJSON, createDOM) take into account a TableRowNode or TableCellNode's height or width, however trying to parse HTML (even if it was outputted by Lexical itself) doesn't set the height/width of the node. This seems like a mistake, however it's specifically only these two things that don't get imported.

Lexical version: 0.10.0

## Steps To Reproduce

1. Create a lexical editor with the `TablePlugin` and the `Table`, `TableRow` and `TableCell` nodes
2. Implement some functionality for resizing `TableCell`s or `TableRow`s (I more or less replicated the logic provided in the playground.
3. Using `$generateNodesFromDOM` on some DOM that features a table, with rows that have `style="height: xx"` or cells that have `style="width: xx"`

## The current behavior

The width/height in the DOM is ignored. Cell/Row nodes are added without these properties set

## The expected behavior

These properties should get set, especially because they're already part of their corresponding classes.

## Proposed solution

The constructors of these nodes already support receiving this sizing property, let's look at some code within the cell node. This code is ran to turn a dom node into a lexical table cell node.

```typescript
export function convertTableCellNodeElement(
  domNode: Node,
): DOMConversionOutput {
  const domNode_ = domNode as HTMLTableCellElement;
  const nodeName = domNode.nodeName.toLowerCase();

  const tableCellNode = $createTableCellNode(
    nodeName === 'th'
      ? TableCellHeaderStates.ROW
      : TableCellHeaderStates.NO_STATUS,
  );
  tableCellNode.__colSpan = domNode_.colSpan;
  tableCellNode.__rowSpan = domNode_.rowSpan;
  const backgroundColor = domNode_.style.backgroundColor;
  if (backgroundColor !== '') {
    tableCellNode.__backgroundColor = backgroundColor;
  }

  return {
    forChild: (lexicalNode, parentLexicalNode) => {
      if ($isTableCellNode(parentLexicalNode) && !$isElementNode(lexicalNode)) {
        const paragraphNode = $createParagraphNode();
        if (
          $isLineBreakNode(lexicalNode) &&
          lexicalNode.getTextContent() === '\n'
        ) {
          return null;
        }
        paragraphNode.append(lexicalNode);
        return paragraphNode;
      }

      return lexicalNode;
    },
    node: tableCellNode,
  };
}
```

I believe the only necessary fix here is to include an additional line which reads the "width/height"

```typescript
  const width = domNode._style.width;
  const tableCellNode = $createTableCellNode(
    nodeName === 'th'
      ? TableCellHeaderStates.ROW
      : TableCellHeaderStates.NO_STATUS,
      domNode_.colSpan,
      width || null,
  );
  tableCellNode.__colSpan = 
  tableCellNode.__rowSpan = domNode_.rowSpan;
  const backgroundColor = domNode_.style.backgroundColor;
  if (backgroundColor !== '') {
    tableCellNode.__backgroundColor = backgroundColor;
  }
```

**Comment by GMchris** [comment]
If the proposed solution works for you, I'd be willings to push a PR with the changes.

**Comment by fantactuka** [comment]
Makes sense, would appreciate PR for this one!

**Comment by utkarsh-shrivastav77** [comment]
Hi is this issue still open

**Comment by alhridoy** [comment]
Hi @GMchris I would love to work on it.
