### ISSUE TITLE
Bug: LinkNode.importDOM doesn't support image content

### ISSUE THREAD

**Issue by roeycohen** [facebook/lexical#4533]
loading the following HTML:
`<a href="https://facebook.com"><img src="https://server/img.jpg"/></a>`
drops the A element.

this happens because of this:
https://github.com/facebook/lexical/blob/5595519202f9241e3e2b8ab3b240c787c58484e2/packages/lexical-link/src/index.ts#L286

Lexical version: 0.10

if I may suggest the fix could look like this:
`if ((content !== null && content !== '') || domNode.querySelector('img') !== null)`

**Comment by acywatson** [comment]
Thanks for reporting this - fix looks ok, but actually I think we should probably handle other node content as well. Maybe it would be more like domNode.children.length > 0 as an additional condition.

**Comment by roeycohen** [comment]
seems like @utkarsh-shrivastav77 

hi @acywatson, would you like me to create PR for the fix?
