### ISSUE TITLE
Bug: add initial html without focusing editor

### ISSUE THREAD

**Issue by annarichardson-dt** [facebook/lexical#4546]
I would like to be able to add initial html to the editor without focusing it.

Lexical version: 0.11.0

## Steps To Reproduce
1. Use $insertNode to add initial html to my text editor like so
editor.update(() => {
        const parser = new DOMParser();
        const dom = parser.parseFromString(
          sanitizeHtml(initialHtml),
          'text/html'
        );
        const nodes = $generateNodesFromDOM(editor, dom);
        $insertNodes(nodes);
}
2. This focuses the editor even though I don't want the editor to be focused on load

## The current behavior
- Using $insertNodes like shown here https://lexical.dev/docs/concepts/serialization#html---lexical focuses the editor even though that's not the desired behavior

## The expected behavior
I would like to be able to add an initial value to the editor without focusing it

**Comment by acywatson** [comment]
You should be able to do this already - $generateNodesFromDOM returns a list of Lexical nodes. You can append those wherever you want without using $insertNodes. For example

```
$getRoot().append(...nodes);
```

**Comment by eonhkao** [comment]
If you're following the lexical docs and you're doing something like 
```editor.update(() => {
  // In the browser you can use the native DOMParser API to parse the HTML string.
  const parser = new DOMParser();
  const dom = parser.parseFromString(htmlString, textHtmlMimeType);

  // Once you have the DOM instance it's easy to generate LexicalNodes.
  const nodes = $generateNodesFromDOM(editor, dom);

  // Select the root
  $getRoot().select();

  // Insert them at a selection.
  $insertNodes(nodes);
});```

you can try importing $setSelection and then setting that to null that's what I ended up doing

**Comment by Svish** [comment]
@eonhkao That will still steal the focus away from whatever was focused before though, right?
