### ISSUE TITLE
Bug: Lexical collapses non-collapsible whitespace on paste [regression]

### ISSUE THREAD

**Issue by birtles** [facebook/lexical#4564]
(Originally posted as a question at https://github.com/facebook/lexical/pull/4467#issuecomment-1560524576)

Lexical version: 0.11.0 and 0.11.1

## Steps To Reproduce

1. Open the lexical playground in one browser (e.g. Firefox)
2. Type "A⍽⍽⍽B" where ⍽ is a non-collapsible space such as full-width space "　" (U+3000) or a non-breaking space (U+00A0).

   (A full-width space is easy to type using, e.g. a Japanese IME. For a non-breaking space, on Windows I can it into notepad using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Space</kbd> and then paste into Lexical Playground).
   
3. Select the "A⍽⍽⍽B" text and copy it to the clipboard
4. Open the lexical playground in another browser (e.g. Chrome)
5. Paste it

Assuming GitHub doesn't normalize whitespace here, an even simpler STR is:

1. Copy this string here: "A　　　B"
2. Paste into Lexical Playground

## The current behavior

"A⍽⍽⍽B" gets converted into "A B" (i.e. a single U+0020 separating A and B)

## The expected behavior

"A⍽⍽⍽B" gets pasted as-is

## Notes

(For the first STR you need to copy and paste between different browsers so that we follow the "paste HTML" codepath, not the "paste Lexical" one.)

Appears to be a regression from #4467.

The spec mentioned in that PR doesn't appear to allow collapsing full-width or non-breaking space characters. Specifically it has:

> Except where specified otherwise, white space processing in CSS affects only the document white space characters: spaces (U+0020), tabs (U+0009), and [segment breaks](https://www.w3.org/TR/css-text-3/#white-space-processing).

I couldn't find anywhere that allows collapsing other whitespace characters..

Looking at the patch, it seems to be using the `\s` character class in a number of places, e.g.

```js
  textContent = textContent
    .replace(/\r?\n|\t/gm, ' ')
    .replace('\r', '')
    .replace(/\s+/g, ' ');
```

However, `\s` expands to `[\f\n\r\t\v\u0020\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]` whereas I think we are only interested in matching `[\t\u0020]` here?

**Comment by CYBAI** [comment]
> However, `\s` expands to `[\f\n\r\t\v\u0020\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]` whereas I think we are only interested in matching `[\t\u0020]` here?

I'm also looking into this issue and most of @birtles 's summary is correct but based on the quoted spec, I wonder we are interested in matching not only `\t` and `\u0020` but also `\r\n` and `\n`.

Thus, I wonder changing the text content replace in `convertTextDOMNode` to 

```js
textContent = textContent.replace(/\r?\n|\t/gm, ' ') 
```

should match the spec.

@zurfyx what do you think?
