### ISSUE TITLE
Feature: LexicalClickableLinkPlugin should support ctrl click mode

### ISSUE THREAD

**Issue by fuchen** [facebook/lexical#4565]
In editing mode, when clicking at a link text, I expect move the cursor position rather than open the link. Usually `Ctrl+click` is expected to open the link.

**Comment by arnabrahman** [comment]
I want to take a look @ivailop7

**Comment by ivailop7** [comment]
Go for it!

**Comment by arnabrahman** [comment]
@ivailop7 i have submitted a PR

**Comment by arnabrahman** [comment]
I got the issue wrong. @fuchen is it possible to provide a screenshot of the issue? When in the editing mode, if I click on a link it doesn't open anything. The link only opens in a new tab from the editor during the read mode. I am not sure if I am doing anything wrong or not.

**Comment by arnabrahman** [comment]
@ivailop7 If you have any insight it will help too

**Comment by ivailop7** [comment]
@arnabrahman I agree the `Ctrl + Click` on a link inside the editor should open the link in a new tab, it's an industry-wide behaviour that makes sense to me. It should be implemented in the Playground. The current behaviour on the mouse click inside a link is to move the cursor to that position and not open the link, which is what's described at the original comment, so I don't see the need for any further changes there.

**Comment by arnabrahman** [comment]
[Lexical Playground.webm](https://github.com/facebook/lexical/assets/12469224/a6517fa5-0edf-45c1-a2e6-b21170c7ea63)

Sorry to ping you again, but I just need to confirm the requirement of this issue. So here when I click on the link with `ctrl+click` it should open in a new tab? Attached is the video @ivailop7

**Comment by ivailop7** [comment]
> Lexical.Playground.webm 
> Sorry to ping you again, but I just need to confirm the requirement of this issue. So here when I click on the link with `ctrl+click` it should open in a new tab? Attached is the video @ivailop7

Yep, that's all.

**Comment by utkarsh-shrivastav77** [comment]
is this issue open

**Comment by sathishsridhar** [comment]
is this issue still open, I was able to find a fix for this, can I open a PR ?

**Comment by davlet61** [comment]
> is this issue still open, I was able to find a fix for this, can I open a PR ?

Hey, what's your fix? I am planning to implement the same in my app, maybe I can get some inspiration from you :)

**Comment by sathishsridhar** [comment]
Kindly check the above PR for the fix @davlet61

**Comment by tarngerine** [comment]
fwiw just using the plugin provided in `@lexical/react` worked for me: 

`import LexicalClickableLinkPlugin from "@lexical/react/LexicalClickableLinkPlugin";`

**Comment by tarngerine** [comment]
fwiw this behavior already exists in `@lexical/react`'s `LexicalClickableLinkPlugin`: https://github.com/facebook/lexical/blob/0f4211532431b17eb157270a36e88fa1ec095896/packages/lexical-react/src/LexicalClickableLinkPlugin.tsx#L88-L99
