### ISSUE TITLE
Bug: toolbar menu does not works correct in table cell.

### ISSUE THREAD

**Issue by turnerguo** [facebook/lexical#4571]
Lexical version: latest

## Steps To Reproduce

1. open https://playground.lexical.dev/
2. input some string, and try select some of them and click some text menu buttons, maybe you can do it right.
3. but if select text to the end of the string, you may not able to click any text-menu buttons.
<img width="582" alt="image" src="https://github.com/facebook/lexical/assets/633880/32491fd9-85bb-4e13-8e45-8d6611acfccf">

sometime if select part of text it still not work.

Link to code example:

**Comment by ivailop7** [comment]
I can reproduce, proper bug with 0.11.1

**Comment by turnerguo** [comment]
I see lots of same table bugs reports but no reply:
<img width="949" alt="image" src="https://github.com/facebook/lexical/assets/633880/d5548273-04d8-49fe-bddd-646509fb0383">

also critical issues like this one https://github.com/facebook/lexical/issues/4576 also no one give some comments.
what's happen on here? can Lexical members show some meesage? 😃  @zurfyx @trueadm @acywatson

**Comment by acywatson** [comment]
> I see lots of same table bugs reports but no reply: <img alt="image" width="949" src="https://user-images.githubusercontent.com/633880/242819424-d5548273-04d8-49fe-bddd-646509fb0383.png">
> 
> also critical issues like this one #4576 also no one give some comments. what's happen on here? can Lexical members show some meesage? 😃 @zurfyx @trueadm @acywatson

Yea we overhauled tables recently, so some bugs are to be expected. We are aware and we'll prioritize these things when we are able to do so. I hope that's helpful.

**Comment by turnerguo** [comment]
> > I see lots of same table bugs reports but no reply: <img alt="image" width="949" src="https://user-images.githubusercontent.com/633880/242819424-d5548273-04d8-49fe-bddd-646509fb0383.png">
> > also critical issues like this one #4576 also no one give some comments. what's happen on here? can Lexical members show some meesage? 😃 @zurfyx @trueadm @acywatson
> 
> Yea we overhauled tables recently, so some bugs are to be expected. We are aware and we'll prioritize these things when we are able to do so. I hope that's helpful.

That's was great, thanks for your response.

**Comment by icrosil** [comment]
Hello @turnerguo, I'm looking into this issue but cannot reproduce on latest version 0.12.2 

https://github.com/facebook/lexical/assets/5208565/8ac02a6e-a6be-4aad-8bf7-5f58d410b5e9

I'm going to close issue as non reproducible, but if you have steps to reproduce - please feel free to reopen.
