### ISSUE TITLE
Feature: Enhance thread/comment click behavior for a smoother user experience

### ISSUE THREAD

**Issue by robertoalvarezalonso** [facebook/lexical#4573]
Hello, currently, when clicking on a thread, the scroll in the editor updates instantly. However, this instantaneous update may not provide the best user experience. To improve this behavior, I suggest implementing a smooth transition when scrolling, which can be easily achieved by adding the "behavior: smooth" [option](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollBy#:~:text=Copy%20to%20Clipboard-,Using%20options%3A,-window.scrollBy) to the call of the "scrollBy" function.

https://github.com/facebook/lexical/blob/a82b7547ea158a5472afda0f702ed844ca25fd0a/packages/lexical/src/LexicalUtils.ts#LL1217C1-L1218C1

**Comment by thegreatercurve** [comment]
The default behaviour is `auto` which means the browser decides. To set the scroll behaviour to smooth, I think you should just have to add this CSS property: https://css-tricks.com/almanac/properties/s/scroll-behavior/

**Comment by robertoalvarezalonso** [comment]
Thank you @thegreatercurve, what about providing a scroll margin? I tried with https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin and scroll-padding without success 😕
