### ISSUE TITLE
Bug: Impossible to insert text when there is only a DecoratorBlockNode or TableNode in root

### ISSUE THREAD

**Issue by fuchen** [facebook/lexical#4574]
![image](https://github.com/facebook/lexical/assets/1988999/19d41382-d380-4ca8-92b1-ace88d4e444c)

Steps to reproduce:
1. Open playground and clear editor
2. Insert a TwitterNode
3. Delete the empty paragraphs before and after the TwitterNode
4. Now it's impossible to insert any text, unless delete the TwitterNode first.

**Comment by fantactuka** [comment]
Have you tried pressing up/right arrows? There's a block level cursor (horizontal blinking cursor) that should appear indicating that user can type text

**Comment by fuchen** [comment]
@fantactuka I tried your steps and it works. But it is not straightforward and users might be confused.

**Comment by ivailop7** [comment]
Closing this one, as per @fantactuka's comment. If you want to modify the behaviour and add an empty paragraph node above when inserting, you can override the tweet node copying the behaviour of the collapsible section node from the playground, which when inserted adds an empty paragraph node above and if the paragraph above is deleted adds a new one when the cursor is moved above.
