### ISSUE TITLE
Feature: Dynamically update the values when the values are updated elsewhere in the application 

### ISSUE THREAD

**Issue by HitaishLokeshEntr** [facebook/lexical#4575]
In my application there is a certain feature called "Trees" which can be created in another part of the applications. Certain operation like delete is also possible for this particular feature. 

I am trying to append the "Trees" that are created in the other part of the application onto the Lexical editor by creating my own custom Lexical component. I have a backend API that is fetching me all the data of the created "Trees" and i am saving it as a JSON onto the editor. Even when I reload the page I am doing a get call which is getting my data to be populated on the screen. 

My challenge is that when somebody decided to delete a particular "Tree" how do i get the updated state in Lexical when I already have it on the editor ( which is basically in the DOM? ). 

Considered using node-replacement which was given in the documentation. But I am not really sure if that is the right way to go about it. 

I would be open to any kinds of thoughts or approaches to how this could be solved ? 

Thank you

**Comment by fantactuka** [comment]
This isn't an enhancement, nor a feature request but rather app specific problem you're solving. Consider using discord or stackoverflow to ask it
