### ISSUE TITLE
Bug: the whole editor features will broken sometime when drag line between table column 

### ISSUE THREAD

**Issue by turnerguo** [facebook/lexical#4576]
Lexical version:

## Steps To Reproduce

1. add a table and merge some cells, then drag the rightmost line of table
2. the blue indicate line could never go back normal, and the whole editor features will be broken
<img width="954" alt="image" src="https://github.com/facebook/lexical/assets/633880/09989716-d3de-4cf4-9824-58c841c7dd1a">

Link to code example:

**Comment by turnerguo** [comment]
checked in latest playground, this bug still their,  @acywatson was mentioned in https://github.com/facebook/lexical/issues/4571#issuecomment-1574207377 that they are overhauled tables, is there any progress? @icrosil @acywatson

**Comment by turnerguo** [comment]
Hi @icrosil, could you please take a look at this issue? I saw table has a lot of rewrite. Does playground update to 0.15.0? It can still reproduce in playground.

**Comment by ivailop7** [comment]
This should be fixed now, from 0.16.0 and up.
