### ISSUE TITLE
Bug: URLs copied from MS Edge browser's address bar are pasted as titles

### ISSUE THREAD

**Issue by AkhrHysd** [facebook/lexical#4578]
Lexical version: 0.9.1

## Steps To Reproduce
Precondition: Create a RichTextPlugin without importing any other plugins, where text can be input.

1. Copy an existing website's URL from the address bar of MS Edge browser.
2. Paste the copied URL into the TextField created in the precondition.

Link to code example: https://codesandbox.io/s/focused-heyrovsky-ec6jcs?file=/src/Editor.js

https://github.com/facebook/lexical/assets/16951235/ffbbb888-8809-4176-8518-6f74458b49e5

## The current behavior

The website's title is being pasted.

## The expected behavior

The website's URL should be pasted.
or appropriately converted into a node with title + anchor.

## Note
This behavior does not occur in the Lexical Playground, where pasting results in an anchor being generated with the title set as the text and the URL set as the href. However, in cases where the relevant plugin is not used, it seems that users would expect the URL to be pasted as is, or appropriately converted into a node with title + anchor.

**Comment by ivailop7** [comment]
Hi @AkhrHysd , I managed to replicate this on Windows inside Edge with the Paste -> Paste as Link. I have a good hunch on why this is the case, your code sandbox has only the RichTextPlugin, which is unaware of link semantics. This should remain this way. This is why separate packages exist `@lexical/link`. You should install it to be recognized as a link, you will need to add the LinkPlugin and LinkNode to the Editor.

**Comment by AkhrHysd** [comment]
Hi  @ivailop7 , thank you for your swift and informative response. I understand now that this behavior is by design, and not a bug, and can be resolved by utilizing the @lexical/link package. I appreciate your guidance in pointing me towards the correct usage of the LinkPlugin and LinkNode within the Editor. This indeed clarifies and resolves the issue for me. Thanks again.

**Comment by ivailop7** [comment]
@AkhrHysd very welcome!
