### ISSUE TITLE
import cycles in lexical playground

### ISSUE THREAD

**Issue by aviv-skillset** [facebook/lexical#4599]
# Remove import cycles from lexical-playground

[import cycles are a dangerous anti-pattern](https://github.com/import-js/eslint-plugin-import/blob/88dd8153571373151c3c7b508c5944cb2bba1588/docs/rules/no-cycle.md?plain=1#L96
) and should be avoided. Honestly, I couldn't figure out a better way to implement this by myself and I think this should be discussed.  Whether this issue should be resolved from the lexical framework API side ('lexical', '@lexical/react'...), or from the user side (in this case: lexical-playground is the user side)

## cycle example: Image Node <-> Image Component
https://github.com/facebook/lexical/blob/c298349457c85f8fc46cef79fedd828c95b2342c/packages/lexical-playground/src/nodes/ImageComponent.tsx#L58
https://github.com/facebook/lexical/blob/c298349457c85f8fc46cef79fedd828c95b2342c/packages/lexical-playground/src/nodes/ImageNode.tsx#L251-L255
https://github.com/facebook/lexical/blob/c298349457c85f8fc46cef79fedd828c95b2342c/packages/lexical-playground/src/nodes/ImageComponent.tsx#L109
https://github.com/facebook/lexical/blob/c298349457c85f8fc46cef79fedd828c95b2342c/packages/lexical-playground/src/nodes/ImageNode.tsx#L26-L29

This issue is also relevant for Table Node <-> Table Component

Thanks for reading. please leave a comment or hit a reaction button if you found this issue useful. if you found room for improvement, don't hesitate! please let me know

## References:
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md
https://github.com/import-js/eslint-plugin-import/issues/2265

**Comment by acywatson** [comment]
If you read the conversation in the github issue linked to that import rule, you'll see that dynamic imports are an acknowledged circumstance where "circular" dependencies can't have a practical impact at runtime. At the same time, the existence of these type guards on the same module as the node class is just a convention, so we could easily move them if we really wanted to, but I'm not seeing/hearing a compelling reason to do that yet.
