### ISSUE TITLE
Bug: Typeahead menu anchor element doubling up

### ISSUE THREAD

**Issue by RyoSogawa** [facebook/lexical#4607]
Repeatedly displaying the Typeahead menu and selecting an item may cause the anchor element to remain without being removed.

I think it tends to occur at the bottom of the editor or around the height where the screen needs to be scrolled.

<a href="https://gyazo.com/2af7e886cdabbc909c40eaea9928f132"><img src="https://i.gyazo.com/2af7e886cdabbc909c40eaea9928f132.png" alt="Image from Gyazo" width="943"/></a>

Lexical version: `0.11.0` or `0.11.1`(playground)

## Steps To Reproduce

1. Use the mention plugin or emoji plugin to input mentions and emojis.
2. Line breaks and extending sentences down the line.
3. If the above operation is repeated, it will occur under some conditions at the bottom of the screen.

**Comment by thegreatercurve** [comment]
I've been trying to replicate this for the last few minutes, but I've not had much luck on Chrome or Safari. Have you been able to replicate this consistently?

**Comment by ivailop7** [comment]
This issue happened to me when the plugin is added twice to the Editor component. Check if you've added ComponentPickerPlugin more than once to the Editor.

**Comment by ivailop7** [comment]
@RyoSogawa were you able to check if the a plugin was added twice to the Editor component?

**Comment by RyoSogawa** [comment]
@thegreatercurve 
@ivailop7 
Sorry for the delay.
I was testing by opening Playground in Chrome.
So I guess the Plugin was not registered twice.

It was happening consistently, but when I tried again, it didn't happen, so it may have been resolved in some update.

Thanks for the replies.
