### ISSUE TITLE
Bug: $convertFromMarkdownString doesn't work in SSR

### ISSUE THREAD

**Issue by 777PolarFox777** [facebook/lexical#4609]
Hello, it looks like method `$convertFromMarkdownString` doesn't actually fill the `editorState` in SSR. The generated HTML doesn't have any text content in it. Because of that the UI "jumps" as the text in the editor is rendered in the browser which is not the best UX.

I did some investigation on my own and it looks like in the `MarkdownImport` update is made but not applied to the root node.
https://github.com/facebook/lexical/blob/e8e3f4ae74fdecc28648681ee975cbb60917ece6/packages/lexical-markdown/src/MarkdownImport.ts#L120

If I add the `console.log(rootNode._size)` right after that line it prints 0, like the elementNode wasn't appended at all.
 

Lexical version: @lexical/react@0.0.11

## Steps To Reproduce

1. In the `initialConfig.editorState` call the `$convertFromMarkdownString` method with some text
2. Right after that call print the editor state to the console, so you can see how it looks in SSR
<img width="368" alt="image" src="https://github.com/facebook/lexical/assets/19393384/f2cc2897-bfb6-4d66-83f1-99b1eea8793b">

3. You can also inspect the DevTools tab to see the generated HTML
<img width="1100" alt="image" src="https://github.com/facebook/lexical/assets/19393384/f4a4601e-bfe8-4e65-89d5-228e8f1122c1">

Link to code example:
https://codesandbox.io/p/sandbox/sleepy-lalande-tikwyj

## The current behavior
The call of `$convertFromMarkdownString` is ignored, the editor state remains empty, the generated HTML doesn't have any text nodes.
## The expected behavior
The call of `$convertFromMarkdownString` fills the editor state, the generated HTML have all the text nodes.

**Comment by etrepum** [comment]
I don't think this should be reproducible with current Lexical
