### ISSUE TITLE
Feature: AutoFocusPlugin act the same behavior in Safari and Chrome.

### ISSUE THREAD

**Issue by gaozhijie94** [facebook/lexical#4610]
I use AutoFocusPlugin in my own project.

but this Plugin have different behavior in Safari and Chrome on my Mac.

In Chrome, the cursor will at the **start** of the content, and the content is at the **start** too.
But in  Safari, the cursor will at the **end** of the content, and the content is at the **end** too.

Chrome
<img width="507" alt="截屏2023-06-06 16 32 59" src="https://github.com/facebook/lexical/assets/76510265/706aa47f-0eed-46d1-bdbe-0d3b0a38d17d">

Safari
<img width="514" alt="截屏2023-06-06 16 30 42" src="https://github.com/facebook/lexical/assets/76510265/5d6ab0de-e6c0-4ddd-9e0d-4c9e31ba5782">

**Comment by gaozhijie94** [comment]
Actually, Chrome can auto fucus without AutoFucusPlugin, this may be overrided ?

**Comment by fantactuka** [comment]
I'll close this one for now, feel free to reopen if you have reproducible scenario with playground or codesandbox
