### ISSUE TITLE
Bug: List Plugin example in Playground is outdated

### ISSUE THREAD

**Issue by dashedstripes** [facebook/lexical#4612]
I am attempting to use Lexical to create nested lists. I'm using the example shown in the playground [here](https://lexical.dev/docs/demos/plugins/lists) and am able to nest lists by using the Tab key.

However, when creating a project locally using the same code, nesting does not work. When I revert lexical version back to 0.5.0 as shown in playground, nesting works as expected. What has changed since 0.5.0? Can we update the example code so that the lists behave as expected for the most recent version? Thanks!

Lexical version: ^0.11.1 (vs 0.5.0 in playground example)

**Comment by simonecervini** [comment]
An easy fix would be to use the `TabIndentationPlugin` plugin — imported from `@lexical/react/LexicalTabIndentationPlugin`
