### ISSUE TITLE
Bug: Lists are not always combined when possible

### ISSUE THREAD

**Issue by GermanJablo** [facebook/lexical#4618]
This worsens accessibility, and also causes unexpected behavior in numbered lists. Maybe it's a good use case for transformations, since there are many possible scenarios.

This has already been the cause of several related issues. The ones I have been able to find:
- https://github.com/facebook/lexical/issues/3433
- https://github.com/facebook/lexical/issues/3781
- https://github.com/facebook/lexical/issues/3141
- https://github.com/facebook/lexical/issues/1045

Curiously, #3781 was closed for being a duplicate of #3433. Then #3433 was "resolved", without resolving the use case of #3781.

https://www.loom.com/share/3572a83400d04b1084d3ac17f8f44973

Lexical version: 0.11.1

## Steps To Reproduce

case 1: delete a paragraph that is separating two lists.
case 2: drag one list next to another

Link to code example: https://playground.lexical.dev/

## The current behavior
Two contiguous but separate lists appear

## The expected behavior
Lists should be combined into one

**Comment by HarleySalas** [comment]
Correct semantics: (nested list, inside of the previous `<li>`)
```
<ol>
  <li>
    1
    <ol>
      <li>
        1.1
      </li>
    </ol>
  </li>
</ol>
```

how lexical tries to render it: (nested list inside of a new `<li>`)
```
<ol>
  <li>
    1
  </li>
  <li>
    <ol>
      ...
  </li>
</ol>
```

The way lexical is doing it, is not compatible with css `counter`, so not only is is semantically in-correct, but it breaks the way that lists are intended to work with css, resulting in things like this:

![image](https://github.com/facebook/lexical/assets/38236585/3b10e004-09af-46ac-b432-e21aec1fc266)

Is this related to the issue being described here, or should I open a separate issue?

**Comment by GermanJablo** [comment]
> Is this related to the issue being described here, or should I open a separate issue?

Neither of them. It is already open: https://github.com/facebook/lexical/issues/2951

**Comment by kevinansfield** [comment]
We also ran into this problem at Ghost so we [added a transform](https://github.com/TryGhost/Koenig/blob/main/packages/kg-default-transforms/src/transforms/merge-list-nodes.ts) that covers the basic functionality. Would be nice if this was handled in core 👍
