### ISSUE TITLE
Feature: Improve prod error message

### ISSUE THREAD

**Issue by strdr4605** [facebook/lexical#4624]
We receive a lot of lexical errors in production, some of those errors have `%s` like https://lexical.dev/docs/error?code=67.
It would be nice to have https://lexical.dev/docs/error?code=67&v=MentionNode.

<img width="493" alt="image" src="https://github.com/facebook/lexical/assets/16056918/a21e9f13-74f4-44bf-9f25-6b7ca77f3bd3">

As I understand from this comment formatProdErrorMessage can receive 3 args

https://github.com/facebook/lexical/blob/c3a392e2ba977e1e1581b787eb83bde26c6da1dd/scripts/error-codes/transform-error-messages.js#L31-L37

but in formating only the code is used.

https://github.com/facebook/lexical/blob/c3a392e2ba977e1e1581b787eb83bde26c6da1dd/scripts/error-codes/formatProdErrorMessage.js#L15

I tried reproducing prod error message locally in lexical playground, but no success, so I am not sure if the comment above is right.

```diff
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    replaceCodePlugin({
      replacements: [
        {
          from: /__DEV__/g,
-          to: 'true',
+          to: 'false',
        },
      ],
    }),
```

Does the idea make sense, can we do this?

**Comment by fantactuka** [comment]
It's annoyingly hard to test it on local, so just tested with PR branch and preview deployment
