### ISSUE TITLE
Bug: Editor doesn't render color, italic, strikethrough, underline or other inline stylings

### ISSUE THREAD

**Issue by maliuta-oleksandr** [facebook/lexical#4626]
I can't find a reason why the editor doesn't render inline styles. When I export the state to HTML and render - I can see all these html attributes like` u, i, strong...` 

**Enabled Editor**
<img width="288" alt="image" src="https://github.com/facebook/lexical/assets/124672558/445014ca-3e71-4660-8e1d-a4ee8414b096">
<img width="386" alt="image" src="https://github.com/facebook/lexical/assets/124672558/a0dfa157-47e2-429f-900f-ed6adc2d0fe4">

**HTML overview of converted state**
<img width="243" alt="image" src="https://github.com/facebook/lexical/assets/124672558/0e8d2bf9-23b1-4c46-bf7a-f18fd8fe2834">
<img width="358" alt="image" src="https://github.com/facebook/lexical/assets/124672558/5268df3c-2d52-4bd4-8956-db741ac38f70">

Lexical version: 0.11.1

Commands I use (from Lexical Playground demo)

`applyStyleText({ 'background-color': '#000' });`
`editor.dispatchCommand(FORMAT_TEXT_COMMAND, 'underline');`
...

<img width="398" alt="image" src="https://github.com/facebook/lexical/assets/124672558/ed97dfaa-6a08-40af-94e2-248f6e7f80bf">
<img width="809" alt="image" src="https://github.com/facebook/lexical/assets/124672558/b290f638-a294-448c-8183-0922adb153ea">

<img width="728" alt="image" src="https://github.com/facebook/lexical/assets/124672558/a6dd2e87-f627-45a9-825b-6b753baffaeb">

**Comment by fantactuka** [comment]
Concider creating code sandbox to reproduce the issue

**Comment by maliuta-oleksandr** [comment]
> Concider creating code sandbox to reproduce the issue. It's likely something wrong with setup, and screenshot debugging is no fun

As simple example with style.color

https://codesandbox.io/s/wispy-haze-zvrxmt?file=/src/index.tsx

**Comment by maliuta-oleksandr** [comment]
Added Underline command
https://codesandbox.io/s/wispy-haze-zvrxmt?file=/src/toolbar.tsx

**Comment by maliuta-oleksandr** [comment]
Typically I can use Stylings without dispatching internal commands.. Seems like I just need to create custom Transformer like here https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling 
?

**Comment by fantactuka** [comment]
Your theme does not have text styles, e.g. see those in playground theme:

https://github.com/facebook/lexical/blob/80bbe7ff92706560a7c03c671b42be5e2a0d6059/packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts#L102-L112

**Comment by maliuta-oleksandr** [comment]
@fantactuka thanks) so easy, I haven't noticed that 

What about inline styles, like second action provided in the sandbox - apply color, turn to HTML preview and enable it again - styles removed, why it happens ?

**Comment by maliuta-oleksandr** [comment]
Yes, I've used this approach - it works perfect https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling 

Thank you, my issue is solved )

**Comment by hsab1997** [comment]
@maliuta-oleksandr i would like to know how you resolved this issue. can you show it in the code pen example https://codesandbox.io/s/wispy-haze-zvrxmt?file=/src/toolbar.tsx 

i have followed the doc https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling but not able to make it working 
useEffect(() => {
    if (initialHtml) {
      loadHtmlContent('<p style="color:blue;">my name is hussain</p>');
    }
  }, [initialHtml]);

  // Function to load HTML content into Lexical
  const loadHtmlContent = (htmlString: string) => {
    const parser = new DOMParser();
    const dom = parser.parseFromString(htmlString, 'text/html');
    console.log('Parsed HTML:', dom.body.innerHTML);
    editor.update(() => {
      const nodes = $generateNodesFromDOM(editor, dom);
      console.log('Generated Nodes:', nodes);
      const root = $getRoot();
      console.log('root Nodes:', root);
      root.clear();
      root.append(...nodes);
    });
  };

**Comment by alex-malyita** [comment]
@hsab1997 
I have created my own ExtendedTextNode

```
import { DOMConversionMap, TextNode, SerializedTextNode } from 'lexical';
import { patchStyleConversion } from '../utils/patch-style-conversation';

export class ExtendedTextNode extends TextNode {
    static getType(): string {
        return 'extended-text';
    }

    static clone(node: ExtendedTextNode): ExtendedTextNode {
        return new ExtendedTextNode(node.__text, node.__key);
    }

    isSimpleText(): boolean {
        return this.__type === 'extended-text' && this.__mode === 0;
    }

    static importDOM(): DOMConversionMap | null {
        const importers = TextNode.importDOM();
        return {
            ...importers,
            code: () => ({
                conversion: patchStyleConversion(importers?.code),
                priority: 1
            }),
            em: () => ({
                conversion: patchStyleConversion(importers?.em),
                priority: 1
            }),
            span: () => ({
                conversion: patchStyleConversion(importers?.span),
                priority: 1
            }),
            strong: () => ({
                conversion: patchStyleConversion(importers?.strong),
                priority: 1
            }),
            sub: () => ({
                conversion: patchStyleConversion(importers?.sub),
                priority: 1
            }),
            sup: () => ({
                conversion: patchStyleConversion(importers?.sup),
                priority: 1
            }),
        };
    }

    static importJSON(serializedNode: SerializedTextNode): TextNode {
        return TextNode.importJSON(serializedNode);
    }

    exportJSON(): SerializedTextNode {
        return {
            detail: this.getDetail(),
            format: this.getFormat(),
            mode: this.getMode(),
            style: this.getStyle(),
            text: this.getTextContent(),
            type: this.getType(),
            version: 1,
        };
    }
}
```

**Comment by hsab1997** [comment]
@alex-malyita thank you for taking your time to respond on this. if you could give me some example like
 if you have created any codesandbox link would help me to understand this how it work.
