### ISSUE TITLE
Feature: Inserting non-semantic elements

### ISSUE THREAD

**Issue by filmerjarred** [facebook/lexical#4630]
I'm trying to add an in-line react feature where you can highlight text and add an emoji next to it.

I've tried adding in the emoji as a decorator node under a paragraph node, but it seems to mess with the selection (due to chrome contenteditable issues) and when I make a new paragraph it gets moved to the new paragraph (as text would if I made a new paragraph with the cursor in the middle of a sentence).

I've tried manually hacking it in as a child element outside the lexical flow, but it seems there's a check that removes dom elements that don't have a corresponding lexical node.

So adding it in as a lexical node seems to cause issues, but not having it in also seems to be an issue.

I'm hacking something together with position absolute but just wanted to check I'm not missing a different way of handling this.

**Comment by fantactuka** [comment]
Unless your emoji is a part of content, it should not be inserted into the editor (contenteditable), as it'll be causing selection issue (the one you've mentioned). Instead you can render that react component outside of the editor and then position it next to the node you've highlighted. E.g., playground's codeblocks have copy and format buttons which are rendered and positioned this way:

https://github.com/facebook/lexical/assets/132642/0e9c3b2c-953d-4c17-85d0-076563944f04

**Comment by filmerjarred** [comment]
That's what I figured, I've put together something that works with position:absolute, but it feels quite convoluted.

Thank you for confirming
