### ISSUE TITLE
Questions: Is there any recommend way of rendering some uneditable content inside the editor area ?

### ISSUE THREAD

**Issue by vipulbhj** [facebook/lexical#4634]
At InVideo, we a very specific video script format, and we are trying to create a script editor with Lexical. 
I wanna create an experience where I have some Node ```[Scene: <scene_name> ⚙️]``` and I only wanna allow users to edit scene name.

Currently I am doing this by marking specific elements ```contenteditable=false```, but I wondering if there are any recommended ways of doing this ?

```javascript
export class InvideoMLHeadingOpenTagNode extends ElementNode {
  static getType() {
    return "invideo-ml-heading-open-tag";
  }

  static clone() {
    return new InvideoMLHeadingOpenTagNode();
  }

  createDOM() {
    // All top level nodes in Lexical are paragraphs
    // So, when we need to create a container for our custom nodes,
    // we need to use a container that's an allowed member inside a paragraph.
    // Refer: https://stackoverflow.com/questions/4291467/nesting-block-level-elements-inside-the-p-tag-right-or-wrong
    const dom = document.createElement("span");
    dom.classList.add("text-read-only");
    dom.contentEditable = false;
    dom.innerText = `[Scene: `;

    return dom;
  }

  updateDOM() {
    return false;
  }
}

export class InvideoMLHeadingCloseTagNode extends ElementNode {
  static getType() {
    return "invideo-ml-heading-close-tag";
  }

  static clone() {
    return new InvideoMLHeadingCloseTagNode();
  }

  createDOM() {
    const dom = document.createElement("span");
    dom.classList.add("text-read-only");
    dom.contentEditable = false;
    dom.innerText = `]`;

    return dom;
  }

  updateDOM() {
    return false;
  }
}

export class InvideoMLHeadingNode extends ElementNode {
  constructor(text, optionKey, key) {
    super(key);
    this.__text = text;
    this.__optionKey = optionKey;
  }

  static getType() {
    return "invideo-ml-heading";
  }

  static clone(node) {
    return new InvideoMLHeadingNode(node.__text, node.__optionKey, node.__key);
  }

  createDOM() {
    const dom = document.createElement("span");
    dom.classList.add("invideo-ml");
    dom.classList.add("scene-heading");
    return dom;
  }

  updateDOM() {
    return false;
  }

  getOptionKey() {
    return this.__optionKey;
  }
}

export function $createInvideoMLHeadingNode(text, url) {
  const [, data] = text.split(": ");
  const content = $createTextNode(data);

  const headingNode = new InvideoMLHeadingNode(text, url);
  const open = new InvideoMLHeadingOpenTagNode();
  const button = new InvideoMLButtonNode();
  const close = new InvideoMLHeadingCloseTagNode();

  headingNode.append(open);
  headingNode.append(content);
  headingNode.append(button);
  headingNode.append(close);

  return headingNode;
}
```

Thanks for the help, much appreciated 🙏🏻

**Comment by zurfyx** [comment]
I believe CSS, as suggested by @aminick, is the best approach. You will have to include some aria indicator for screen readers to understand the context of the input.

The second option is to use a DecoratorNode (and optionally a NestedEditor) but the fact that we don't control them and come with `contenteditable="false"` means that there's some trade-offs with a11y and selection.

**Comment by vipulbhj** [comment]
Yes, I am working with that approach, but that seems to be leading to some weird behaviour, specifically with new lines. <br /> are super messy. 

Is it okay if I use `display: flex` in places ?

Also, I am seeing random `<br />` s which are causing problems with styles.

**Comment by vipulbhj** [comment]
I created a sandbox for what I am trying if that helps. You can find it at [https://codesandbox.io/s/trusting-aryabhata-rwmdv7?file=/src/Editor/styles.css](https://codesandbox.io/s/trusting-aryabhata-rwmdv7?file=/src/Editor/styles.css)

I would love some feedback if you guys have any.

**Comment by vipulbhj** [comment]
Currently the biggest issue which I am facing is, if you see any `heading`, `property` node, they all seem to have `<br />` which I have no idea, how they ended up there, and I can't even get rid of those.

**Comment by nigelgutzmann** [comment]
Lexical adds `<br/>` tags if the ElementNode is not marked as being inline. If you add to your node this override, then this behaviour will stop:

```
    override isInline(): boolean {
        return true;
    }
```
