### ISSUE TITLE
Bug: UI Multi-Bulletpoints on tab indent with ListPlugin and MarkdownPlugin

### ISSUE THREAD

**Issue by Thoma997** [facebook/lexical#4640]
Lexical version: 0.11.1

## Steps To Reproduce

1. Install Lexical on a new React project
2. Create a minimum viable nested-list editor like the one prodided in the following: 

Link to code example:
// Editor.tsx
```
import { LexicalComposer } from '@lexical/react/LexicalComposer';
import { RichTextPlugin } from '@lexical/react/LexicalRichTextPlugin';
import { ContentEditable } from '@lexical/react/LexicalContentEditable';
import { HeadingNode, QuoteNode } from '@lexical/rich-text';
import { TableCellNode, TableNode, TableRowNode } from '@lexical/table';
import { ListItemNode, ListNode } from '@lexical/list';
import { CodeHighlightNode, CodeNode } from '@lexical/code';
import { AutoLinkNode, LinkNode } from '@lexical/link';
import { ListPlugin } from '@lexical/react/LexicalListPlugin';
import { MarkdownShortcutPlugin } from '@lexical/react/LexicalMarkdownShortcutPlugin';
import { TabIndentationPlugin } from '@lexical/react/LexicalTabIndentationPlugin';
import { TRANSFORMERS } from '@lexical/markdown';

const editorConfig = {
  // Handling of errors during update
  onError(error) {
    throw error;
  },
  // Any custom nodes go here
  nodes: [
    HeadingNode,
    ListNode,
    ListItemNode,
    QuoteNode,
    CodeNode,
    CodeHighlightNode,
    TableNode,
    TableCellNode,
    TableRowNode,
    AutoLinkNode,
    LinkNode,
  ],
};

export default function Editor() {
  return (
    <LexicalComposer initialConfig={editorConfig}>
        <RichTextPlugin
          contentEditable={<ContentEditable />}
        />
        <ListPlugin />
        <MarkdownShortcutPlugin transformers={TRANSFORMERS} />
        <TabIndentationPlugin />
    </LexicalComposer>
  );
}
```

## The current behavior

https://github.com/facebook/lexical/assets/29661532/ddd3c1a7-c1d0-4ae7-8a04-e80ae5f5ebc9

## The expected behavior
No doubled bullet points like in the lexical playground example at https://playground.lexical.dev/

**Comment by acywatson** [comment]
Add this:

https://github.com/facebook/lexical/blob/2a64b34f9393325bd14e8f3d5fcd65edce93192b/packages/lexical-playground/src/themes/PlaygroundEditorTheme.css#L377

Here:

https://github.com/facebook/lexical/blob/2a64b34f9393325bd14e8f3d5fcd65edce93192b/packages/lexical-playground/src/themes/PlaygroundEditorTheme.ts#L70

to get the behavior you want.
 
I'll leave this open while I think about possible ways to improve this.

**Comment by Thoma997** [comment]
Thanks, works perfectly now. 
And I agree, it would be great if this was the default behaviour of displaying nested lists using minimal setup.
