### ISSUE TITLE
Bug: insertNodes: cannot insert a non-element into a root node

### ISSUE THREAD

**Issue by maliuta-oleksandr** [facebook/lexical#4646]
I'm trying to initialize the Editor with HTML like this. If I add `<code />` element - it throws me this error.

`<p class="paragraph" dir="ltr"><span>Text. </span><a href="https://google.com" rel="noopener" class="link"><span style="color: rgb(255, 105, 0);">Double</span></a><span> click to </span></p><code class="code" spellcheck="false"><span>edit</span></code>`

Lexical version: last

**CodeNode** is added to **Nodes**

## Steps To Reproduce

1. Using Lexical add Code element with $`createCodeNode`
2. Convert into **HTML** using `$generateHtmlFromNodes(editor, null);` 
3. Then try again to init the Editor.

```
editor.update(() => {
            const parser = new DOMParser();
            const dom = parser.parseFromString(content.trim(), 'text/html');
            const nodes = $generateNodesFromDOM(editor, dom);
            $getRoot().select();
            const selection = $getSelection();
            selection?.insertNodes(nodes);
        });
```

**Comment by maliuta-oleksandr** [comment]
<img width="287" alt="image" src="https://github.com/facebook/lexical/assets/124672558/eb6a2650-b809-4b25-98c8-f8cdc95c6fe1">

**Comment by fantactuka** [comment]
Please use this one for html import instead of $insertNodes:

```
$insertGeneratedNodes(editor, nodes, $getRoot().select());
```
