### ISSUE TITLE
Bug: dispatchCommand FORMAT_TEXT_COMMAND if Editor without text selection doesn't reflect

### ISSUE THREAD

**Issue by maliuta-oleksandr** [facebook/lexical#4656]
I want to update all text nodes to Bold without text selection. What's the best way to apply any changes without manual selection ?
- Tried with simple command `editor.dispatchCommand(FORMAT_TEXT_COMMAND, 'bold');` , but it works only with Selection.
- Tried to select in different way
```
editor.setEditable(true);
$getRoot().select();
$getSelection()?.getNodes().forEach((node) => {
  if ($isTextNode(node)) {
    node.setFormat('bold');
  }
})
```

Lexical version: Last

## Steps To Reproduce
1. Set **editable: false**

## The current behavior 
None of my methods work

## The expected behavior
All text nodes in Editor becomes bold or vice versa

**Comment by thegreatercurve** [comment]
You can use an editor transform to target one specific type of node. Something like the below should do what you need: 
```js
editor.registerNodeTransform(TextNode, (textNode) => {
  if (textNode.getFormat() !== IS_BOLD) {
    textNode.setFormat(IS_BOLD);
  }
});
