### ISSUE TITLE
Bug: Non-experimental $insertTableColumn crashes the editor when trying to add multiple columns

### ISSUE THREAD

**Issue by PeterBul** [facebook/lexical#4660]
When calling $insertTableColumn with multiple columns, cells are added to the rows while looping. This causes the second iteration of the loop to select the newly created cell node as target node. This does not seem like it is the intended functionality, since getCordsFromCellNode is called on the target node, which causes Lexical to crash because the newly created node does not exist in the DOM yet.

$insertTableColumn__EXPERIMENTAL is also available, but since this is experimental, and also does not work with multiple columns (tested in playground), I don't see this as a valid replacement yet. It would therefore be preferable to to fix the current $insertTableColumn.

Lexical version: 0.11.1

## Steps To Reproduce

1. Add a table with 2 or more columns.
2. Mark cells in table spanning at least 2 columns.
3. Open table cell action menu and click "Insert x columns left"

Link to code example:
https://codesandbox.io/s/lexical-table-plugin-example-forked-qd40pm

## The current behavior
The editor crashes with the message: "Cell not found in table."

## The expected behavior
The editor should not crash, and two columns should be added.

**Comment by ivailop7** [comment]
Nice find! I reproduced it after a few attempts.

**Comment by PeterBul** [comment]
I managed to fix it by moving some code out of the inner loop of $insertTableColumn. I'm not sure how one would test this though, since the playground uses $insertTableColumn__EXPERIMENTAL by now

**Comment by zurfyx** [comment]
> I managed to fix it by moving some code out of the inner loop of $insertTableColumn. I'm not sure how one would test this though, since the playground uses $insertTableColumn__EXPERIMENTAL by now

Thank you for looking into this! Feel free to publish the PR without test plan. You can temporarily drop the experimental call and run the table tests locally (`npm run test-e2e-chromium -- Tables.spec`)
