### ISSUE TITLE
Query: How can I change styling of the paragraph based on whether editor is in focus or not 

### ISSUE THREAD

**Issue by vedkribhu** [facebook/lexical#4662]
Not a bug per se, I have just started using lexical and I have a very basic question. I have a usecase where I want to change styling of my paragraph node when my editor is in focus. I know we can have listeners on `BLUR_COMMAND` and `FOCUS_COMMAND`, but what am I suppose to do inside those listeners?

Lexical version: 0.11.1

## Steps To Reproduce

I have a class named 'c1' which should be applied to paragraph element when the editor is in focus and when the editor is not in focus class c2 should be applied, any idea how can I achieve this?

Link to code example:

**Comment by fantactuka** [comment]
You can add/remove class to root node in those listeners that will affect nested paragraph styling

Please consider using Discord for questions

**Comment by vedkribhu** [comment]
Posting solution here in case someone else is looking into similar usecase: `<ContentEditable class="editor-input">` then apply css like `editor-input:focus .editor-paragraph`
