### ISSUE TITLE
Bug: Losing format after click inside editor.

### ISSUE THREAD

**Issue by Dan86de** [facebook/lexical#4687]
https://github.com/facebook/lexical/assets/23312063/1655764d-0215-47f5-a737-b02ab614c95d

- I have active formatting and an empty editor state
- click outside editor wo changing formatting
- click back into empty editor and formatting is deleted

## The expected behavior
- editor should keep selected formatting even if it's empty
- same problem is on Lexical Playground

**Comment by etrepum** [comment]
This appears to have been fixed
