### ISSUE TITLE
Bug: $cloneWithProperties() does not generate a new key for the clone it creates.

### ISSUE THREAD

**Issue by rucker** [facebook/lexical#4691]
The [documentation](https://lexical.dev/docs/api/modules/lexical_selection#clonewithproperties) for `$cloneWithProperties()` states:
>Returns a copy of a node, but generates a new key for the copy.

Looking through the code, it looks like a call to `$setNodeKey(null)` or `generateRandomKey()` is all that would be needed.

Lexical version: v0.11.1

## Steps To Reproduce

1. Clone a node using `$cloneWithProperties()`.
2. Observe that the clone node has the same key as the original node.

Link to code example: https://codesandbox.io/s/lexical-plain-text-example-forked-4p39cd
Using that example, type into the editor and look at the console output.

## The current behavior
The node is cloned, but has the same key as the original node.
## The expected behavior
The clone node should have a newly generated key.

**Comment by acywatson** [comment]
I think the are wrong here - cloning operations in Lexical typically preserve the key. A copy operation would not.

**Comment by etrepum** [comment]
The docs are not wrong anymore
