### ISSUE TITLE
Bug: Error when using ExtendedTextNode "Uncaught Error: insertNode: topLevelElement is root node"

### ISSUE THREAD

**Issue by ko-devHong** [facebook/lexical#4693]
Lexical version: 0.11.1

## Steps To Reproduce

1. It is recommended that you create and use an ExtendedTextNode, which is customNode, because you lose the style for text tags when importing them. Reference link: https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling
2.The style is applied well when applied, but it uses the phrase below in addition to the custom node, converts it back to HTMLString, and causes an error when importing it back to Lexical. 
3. error is "Uncaught Error: insertNode: topLevelElement is root node"4. 

An expected reason is that the extension node does not have parent and next, prev values.
OR use code tag 

<img width="733" alt="스크린샷 2023-06-23 오전 9 36 16" src="https://github.com/facebook/lexical/assets/45538347/476f4ad4-4e1b-4e92-86ce-553da953a304">

So it works normally when you remove only the ExtendedTextNode association.

I give you for my htmlString 
```
<p class="TextEditorTheme__paragraph" dir="ltr"><span>test</span></p><h1 class="TextEditorTheme__h1" dir="ltr"><span>test</span></h1><h2 class="TextEditorTheme__h2" dir="ltr"><span>test</span></h2><h3 class="TextEditorTheme__h3" dir="ltr"><span>test</span></h3><ul class="TextEditorTheme__ul"><li value="1" class="TextEditorTheme__listItem"><span>test</span></li></ul><ol class="TextEditorTheme__ol1"><li value="1" class="TextEditorTheme__listItem"><span style="background-color: rgb(163, 151, 104);">test</span></li></ol><ul class="TextEditorTheme__ul" __lexicallisttype="check"><li role="checkbox" tabindex="-1" aria-checked="false" value="1" class="TextEditorTheme__listItem TextEditorTheme__listItemUnchecked"><span>test</span></li></ul><blockquote class="TextEditorTheme__quote" dir="ltr"><span>test</span></blockquote><code class="TextEditorTheme__code" spellcheck="false" data-highlight-language="javascript"><span>test</span></code><code class="TextEditorTheme__code" spellcheck="false" data-highlight-language="objc"><span>test</span></code><code class="TextEditorTheme__code" spellcheck="false" data-highlight-language="javascript"><span>test</span></code><code class="TextEditorTheme__code" spellcheck="false" data-highlight-language="javascript"><span>test</span></code><p class="TextEditorTheme__paragraph" dir="ltr"><span>test</span></p><p class="TextEditorTheme__paragraph" dir="ltr"><span>test</span></p><p class="eTextEditorTheme__paragraph" dir="ltr"><span>test</span></p><p class="TextEditorTheme__paragraph" dir="ltr"><span>test</span></p><p class="TextEditorTheme__paragraph" dir="ltr"><span>test</span></p><p class="TextEditorTheme__paragraph" dir="ltr"><span>test</span></p><p class="TextEditorTheme__paragraph" dir="ltr"><span>test</span></p><p class="TextEditorTheme__paragraph" dir="ltr"><br></p><p class="TextEditorTheme__paragraph" dir="ltr"><br></p>
```

## The current behavior

<img width="1098" alt="스크린샷 2023-06-23 오전 9 43 17" src="https://github.com/facebook/lexical/assets/45538347/d2a561af-bdff-481c-8239-cf63288ddf2c">

**Comment by ant-coding** [comment]
It's not much, but when I remove the code tags from your example, I get the editor without the errors.

This is what I removed:
```
<code class="TextEditorTheme__code" spellcheck="false" data-highlight-language="javascript"><span>test</span></code>
<code class="TextEditorTheme__code" spellcheck="false" data-highlight-language="objc"><span>test</span></code>
<code class="TextEditorTheme__code" spellcheck="false" data-highlight-language="javascript"><span>test</span></code>
<code class="TextEditorTheme__code" spellcheck="false" data-highlight-language="javascript"><span>test</span></code>```

**Comment by ninawangyimei** [comment]
`code` node need a parent Node, like this:
```
<p class="PlaygroundEditorTheme__paragraph" dir="ltr">
    <code class="TextEditorTheme__code" spellcheck="false" data-highlight-language="javascript">
        <span>test</span>
    </code>
</p>
```

**Comment by etrepum** [comment]
There isn't really enough information here to verify if this is still reproducible. If you are still experiencing this issue please create an issue with full reproduction instructions, including code, that is easy to run (e.g. on stackblitz or codesandbox)
