### ISSUE TITLE
Bug:  Issue with Changing Block Type to Quote after Shift+Enter

### ISSUE THREAD

**Issue by Micko1994** [facebook/lexical#4696]
When Shift+Enter is pressed to create a new line of text and the attempt to change the block type to a quote is made, an error occurs.

Lexical version: 0.10.0

## Steps To Reproduce

1. Open the editor.
2. Press Shift+Enter to create a new line of text.
3. Try to change the block type to a quote.

## The current behavior
The block type should change to a quote without any errors.

## The expected behavior
An error occurs when attempting to change the block type to a quote after pressing Shift+Enter.

https://github.com/facebook/lexical/assets/47939644/3f00560a-8241-4f1a-b569-718b33d76de1

**Comment by naveen8801** [comment]
Fix - #4776
