### ISSUE TITLE
Bug: Importing "@lexical/react" via vite occurs `Failed to resolve entry for package "@lexical/react"`

### ISSUE THREAD

**Issue by minamorl** [facebook/lexical#4705]
Lexical version: 0.11.1

**Updated: 2023-06-26 See the comment I attached below**

## Steps To Reproduce

1. set up vite project
2. install the latest @lexical/react with others
3. import { ... } from "@lexical/react"

This seems really strange for me. I thought package is broken but i couldn't find anything from the codebase.
Context: I am trying to provide a rich text editor for general users who are not familiar with Lexical.
I attached my github repo. package.json is just for lexical.
`npm run install` and `npm run dev` on my repo

Link to code example: https://github.com/trishulaorg/veil

## The current behavior
got

```
  ✘ [ERROR] Failed to resolve entry for package "@lexical/react". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
```

## The expected behavior
Should be imported

**Comment by minamorl** [comment]
I figured out this was because of there's no `index.js`. Is it intentional? Me personally think it is better for users to provide index file IMHO

**Comment by acywatson** [comment]
I think we can add an index file in @lexical/react

**Comment by minamorl** [comment]
@acywatson If you need my help let me know. I think I can take handle of it when I'm available.

**Comment by fantactuka** [comment]
In case someone's app won't have tree shaking, they'll end up having every single @lexical/react plugin bundled. Is there any issues with explicitly importing plugins like `@lexical/react/LexicalListPlugin`?

**Comment by acywatson** [comment]
> In case someone's app won't have tree shaking, they'll end up having every single @lexical/react plugin bundled. Is there any issues with explicitly importing plugins like `@lexical/react/LexicalListPlugin`?

I don't think this should be an issue. AFAIK every modern toolchain is supporting treeshaking and even our own packages (at least every one except react) is structured in the same way with this expectation in mind. 

I think there is no reason we can't do both though, right?

**Comment by abhinavshm95** [comment]
Experience the same issue 
```
ERROR in dll renderer renderer[11]
Module not found: Error: Can't resolve '@lexical/react' in .....
```

**Comment by wspringer** [comment]
Same here

**Comment by etrepum** [comment]
I think we can close this, at least as described. It's not a bug that there is no barrel file for `@lexical/react`. There's no documentation that tells you to import from there. The API docs cover this package now. A separate feature request to create a barrel file could be created, although that's slightly more complicated than it sounds due to the changes that would also be required for documentation extraction/display and the build scripts.

**Comment by tangzijun** [comment]
The problem still exists and no temporary solution has been found

**Comment by etrepum** [comment]
It’s not a bug, there’s no `@lexical/react` module. Anything you want to import from there is its own module, for example `@lexical/react/LexicalComposer`

**Comment by tangzijun** [comment]
When I use lexical by importing, dev is normal, but after building, an error will be reported when running:
<img width="1229" height="457" alt="Image" src="https://github.com/user-attachments/assets/02c53d30-0f3e-49a6-9072-dfa973a74378" />

import RichTextEditor from '@/components/ex/richTextEditor/RichTextEditor';
<img width="1271" height="218" alt="Image" src="https://github.com/user-attachments/assets/9e7c6986-4234-410e-affa-ff3776249f86" />

It works fine when I change it to:
const RichTextEditor = React.lazy(() => import('@/components/ex/richTextEditor/RichTextEditor'));

I am using tanstack start

**Comment by etrepum** [comment]
Looks like a bundler misconfiguration or a missing “use client”

**Comment by mariusflorescu** [comment]
@tangzijun have you found a solution to this?
