### ISSUE TITLE
Bug: error "Cannot use method in read-only mode" thrown when `isEditable === true` due to parallel call to `editorState.read`

### ISSUE THREAD

**Issue by ilDon** [facebook/lexical#4739]
Trying to set a custom property on a custom node during node cloning results in the error `Cannot use method in read-only mode`, even if `editor.isEditable() === true`

I have a custom node called `AutocompleterNode`. This node extends `TextNode`.

I need to set a custom property, I do so in the constructor. I both have the `set*` and `get*` methods.

While the cloning takes place, I also call `editorState.read(() => {...})` to perform some actions that take place outside of Lexical. I tried using `editorState.read` because I do not need to update the editor, I only need to access the state of the editor. Therefore calling `editor.update` seemed unnecessary.

Even `editorState.clone().read` throws the same error (expected once I've inspected the source code, but counter intuitive).

Please note that this happens only if I try to set the custom property of the custom node. If I omit the custom property from the constructor in the `clone` method, the error is not thrown.

Lexical version: `0.11.1`

## Steps To Reproduce

1. Trigger an update of the editor while also calling `editorState.read`. Ensure that a custom node with some custom property is cloned.
3. `isEditable` is set to `false`
4. the error `Cannot use method in read-only mode` is thrown

Code example:

Where I call `read`:
```
editor.registerMutationListener(
  AutocompleterNode,
  (mutatedNodes) => {
    for (const [nodeKey, mutation] of mutatedNodes) {
      const editorState = editor.getEditorState()
      editorState.read(() => {
        const textNode = $getNodeByKey(nodeKey) as AutocompleterNode
        // call to method outside Lexical
      })
    }
  },
),
```

My custom node:
```
import { $applyNodeReplacement, TextNode } from 'lexical'
import type { EditorConfig, NodeKey, SerializedTextNode } from 'lexical'

interface ISerializedAutocompleterNode extends SerializedTextNode {
  targetNode: string
}

export class AutocompleterNode extends TextNode {
  public static getType (): string{
    return 'autocompleter'
  }

  public static createNode (targetNode: string, text = ''): AutocompleterNode {
    const newNode = new AutocompleterNode(text)
    newNode.setTargetNode(targetNode)
    return $applyNodeReplacement(newNode)
  }

  /*
   * OMITTING the third param (`node.__targetNode`) in the constructor call removes the error
   */
  public static clone (node: AutocompleterNode): AutocompleterNode {
    const clonedNode = new AutocompleterNode(node.__text, node.__key, node.__targetNode)
    return clonedNode
  }

  public static importJSON (serializedNode: ISerializedAutocompleterNode): AutocompleterNode {
    return AutocompleterNode.createNode(serializedNode.targetNode, serializedNode.text)
  }

  constructor (
    text: string,
    key?: NodeKey,
    public __targetNode?: string,
  ) {
    super(text, key)
  }

  public exportJSON (): ISerializedAutocompleterNode {
    return {
      ...super.exportJSON(),
      targetNode: this.getTargetNode(),
    }
  }

  public createDOM (config: EditorConfig): HTMLElement {
    const element = super.createDOM(config)
    return element
  }

  public setTargetNode (targetNode: CustomNodeType): void {
    const self = this.getWritable()
    self.__targetNode = targetNode
  }

  public getTargetNode (): CustomNodeType {
    const self = this.getLatest()
    return self.__targetNode
  }
}

```

## The current behavior

When `editorState.read` is used during a rerender process, concurrent updates to the same editor are blocked.

## The expected behavior

`editorState.read` should not block updates happening outside the callback, or at least this should be documented in [Read Mode / Edit Mode](https://lexical.dev/docs/concepts/read-only)

**Comment by acywatson** [comment]
Thanks for reporting this. I can't grasp exactly what's going on here in terms of the order of operations, so it's hard to tell if this is a bug. But I can give some general advice that might be helpful and then maybe we can get closer to the root of the problem.

Confusingly, read-only mode in this case has nothing to do with the isEditable. These are two different things. Editor state can only be mutated via an editor.update callback, so inside of an EditorState.read callback, we throw on calls to the writeable versions of the node (via LexicalNode.getWriteable).  My best guess here is that somewhere/somehow, something is calling getWriteable in that read callback, but I can't really tell what.

**Comment by acywatson** [comment]
Closing this until we have a repro/ I'm fairly confident there's no bug here.
