### ISSUE TITLE
Bug: Selection has been lost when I replace node

### ISSUE THREAD

**Issue by sophia9211** [facebook/lexical#4778]
Hello, I want to maintain the selection of a specific TextNode after changing it. For example, if I click and change the first selected sentence like this, the selection moves elsewhere. 
My goal is to select the same changed sentence even if the corresponding node is changed to a recommended sentence. However, the node after being changed is unpredictable.
How can I continue selecting the changed TextNode? This is my code.

<img width="728" alt="스크린샷 2023-07-14 오후 12 28 20" src="https://github.com/facebook/lexical/assets/48948598/8b2a1d89-f9fb-459c-822b-e2ba8f63d2b0">

Lexical version:  ^0.11.1

```
export function $replaceTextNode(
  selection: RangeSelection,
  text: string
): void {
  const node = selection.anchor.getNode();
  const textNode = $createTextNode(text);
  node.replace(textNode);
  node.select();
  return;
}
```
The replacement works smoothly, but the selection does not work
<img width="564" alt="스크린샷 2023-07-14 오후 12 17 08" src="https://github.com/facebook/lexical/assets/48948598/33c2876d-bbdc-4bc4-b57c-2516450d0d12">

So if I process the code like this, Select the last sentence. The node key of selection is changed to the key of the last sentence.

```
export function $replaceTextNode(
  selection: RangeSelection,
  text: string
): void {
  const node = selection.anchor.getNode();
  const textNode = $createTextNode(text);
  const newNode = node.replace(textNode);
  newNode.select();
  return;
}
```

If I change only the text with splice, save the key of the node, and then try to maintain the select again with that key, const node = $getNodeByKey(key); node of represents null.

```
export function $replaceTextNode(key: string, text: string): void {
  console.log(key);
  const node = $getNodeByKey(key);
  //If I try like this, node will be null
  node.spliceText(0, node.__text.length, text, false);
  node.select();

  return;
}
```
Is there really no way to keep that node selected after changing the text of that node?
Please help me 😂

**Comment by JohnnyRacer** [comment]
I don't think the built-in selection API enables multiple node selection like how you want. But I think it might be possible to call `selection.getNodes()` and add the nodes to an array to have the selection saved using `useState`. Then you can have a method in the node class that allows to select all the nodes in the array. Your nodes needs to have a unique id that allows for selection within the array for this work.

```js
 const [selNodes, setSelNodes] = useState([]); // Use state to hold the nodes
// ... Nodes are saved in array
   const selection = $getSelection();
   if (!$isNodeSelection(selection)) {
     return null;
   }
   const nodes = selection.getNodes();
setSelNodes(e => [...e, nodes]); // Adding nodes

// ...  Get targeted ids and something with nodes

targetIds = [...someUniqueIds];
const targetNodes = selNodes.filter(e => targetIds.includes(e.id));

```

**Comment by acywatson** [comment]
```
export function $replaceTextNode(
  selection: RangeSelection,
  text: string
): void {
  const node = selection.anchor.getNode();
  const textNode = $createTextNode(text);
  const newNode = node.replace(textNode);
  newNode.select();
  return;
}
```

This is the right way. In your first example, you're selecting a node that you replaced, so that will fail because you tried to move Selection to a node that is no longer in the EditorState.

I think the missing piece here for you is that you need to pass an anchor and focus offset to newNode.select to select the whole node like ```newNode.select(0, newNode.getTextContentSize())```
