### ISSUE TITLE
Bug: When selecting a table cell

### ISSUE THREAD

**Issue by luudv** [facebook/lexical#4782]
I have used the LexicalTablePlugin to create the tables, I have a problem when clicking on a table cell (or a newly created table with a cell selected) shows the error message:
<img width="878" alt="2023-07-15_9-43-08 AM" src="https://github.com/facebook/lexical/assets/2778871/3b82e033-28f7-4c14-9048-c94a7ac49eaa">

Lexical version: 0.11.2

## Steps To Reproduce

1. Click a table cell 

## The current behavior
```
TypeError: findFn is not a function
    at Object.$findMatchingParent (LexicalUtils.dev.js:232:1)
    at $findTableNode (LexicalTable.dev.js:1278:1)
    at Array.eval (LexicalTable.dev.js:943:1)
    at triggerCommandListeners (Lexical.dev.js:9478:1)
    at dispatchCommand (Lexical.dev.js:1395:1)
    at eval (Lexical.dev.js:2693:1)
    at beginUpdate (Lexical.dev.js:9612:1)
    at updateEditor (Lexical.dev.js:9703:1)
    at onSelectionChange (Lexical.dev.js:2626:1)
    at HTMLDocument.onDocumentSelectionChange (Lexical.dev.js:3370:1)
```
## The expected behavior
There is no issue when clicking on the table cell.

**Comment by naveen8801** [comment]
Hi @luudv, can you please share some code sample or any recording, it will surely help us to understand the bug :)

**Comment by slab-sunghwan** [comment]
+1
I just followed very basic example with TablePlugin
```javascript
<LexicalComposer initialConfig={initialConfig}>
  <PlainTextPlugin
    contentEditable={<ContentEditable />}
    placeholder={<div>Enter some text...</div>}
    ErrorBoundary={LexicalErrorBoundary}
  />
  <OnChangePlugin onChange={onChange} />
  <HistoryPlugin />
  <MyCustomAutoFocusPlugin />
  <TablePlugin />
</LexicalComposer>
```
This error occurs in 0.11.2, so I had to downgrade to version 0.11.1 to avoid the error

**Comment by luudv** [comment]
> +1 I just followed very basic example with TablePlugin
> 
> ```js
> <LexicalComposer initialConfig={initialConfig}>
>   <PlainTextPlugin
>     contentEditable={<ContentEditable />}
>     placeholder={<div>Enter some text...</div>}
>     ErrorBoundary={LexicalErrorBoundary}
>   />
>   <OnChangePlugin onChange={onChange} />
>   <HistoryPlugin />
>   <MyCustomAutoFocusPlugin />
>   <TablePlugin />
> </LexicalComposer>
> ```
> 
> This error occurs in 0.11.2, so I had to downgrade to version 0.11.1 to avoid the error

I also used the same code @naveen8801

**Comment by naveen8801** [comment]
Hi @luudv @slab-sunghwan, I tried replicating it [here](https://codesandbox.io/s/lexical-table-plugin-example-forked-6x2ffn?file=/src/Editor.js) but didn't find any thing so far. Let me know if am missing something

**Comment by ivailop7** [comment]
@fantactuka @acywatson @zurfyx there's a regression since 0.11.2 in tables, we rebased on friday and replicate the same issue as above. I think it might have to do with collaborative because I don't observe the issue in the playground where collaborative is off.

**Comment by slab-sunghwan** [comment]
@naveen8801 Hi, check this [Sandbox](https://codesandbox.io/p/sandbox/tender-cdn-l8ykpn?file=%2Fapp%2FEditor.tsx%3A13%2C19)
You can ealily reproduce the case with very simple example.
