### ISSUE TITLE
Bug: Two LineBreak is disappeared when backspace in one linebreak (plain text mode)

### ISSUE THREAD

**Issue by laskdjlaskdj12** [facebook/lexical#4786]
Lexical version:
0.11.2 version
## Steps To Reproduce

1. Type two line lexical editor (base editor)
2. Enter twice linebreak between typed two line
3. delete line break between typed two line

Link to code example:
https://codesandbox.io/s/lexical-plain-text-example-forked-mcdh3v?file=/src/onChange.js

## The current behavior
delete two line break
## The expected behavior
delete one line break

https://github.com/facebook/lexical/assets/16471540/d3dd7de1-c8db-450b-83ed-3ba48fcb5fe0

------------- video --------------

**Comment by etrepum** [comment]
I can't reproduce this at https://playground.lexical.dev/?isRichText=false
