### ISSUE TITLE
Bug: Lexical EditorRefPlugin Typescript issue

### ISSUE THREAD

**Issue by Blackglade** [facebook/lexical#4789]
![Screenshot 2](https://github.com/facebook/lexical/assets/6363077/8b629498-a20a-49dd-9861-701bdeaf644b)

Lexical version: 0.11.2

## Steps To Reproduce

1. `import {EditorRefPlugin} from '@lexical/react/LexicalEditorRefPlugin'` 
2. Insert `<EditorRefPlugin editorRef={ref} />` somewhere within `LexicalComposer`

Complete Code:

```jsx

type EditorProps = {
	name: string
	ref: RefCallback<LexicalEditor>
}

export default function Editor({ name, ref } : EditorProps) {  
	return (
		<div className='relative'>
			<LexicalComposer initialConfig={{
				namespace: name,
				onError: (error: Error) => console.error(error),
			}}>
				<PlainTextPlugin
					contentEditable={<ContentEditable />}
					placeholder={<div>Enter Text Here...</div>}
					ErrorBoundary={LexicalErrorBoundary}
				/>
				<EditorRefPlugin editorRef={ref} />
			</LexicalComposer>
		</div>
	);
}
```

## The current behavior

Typescript complains about the EditorRefPlugin

## The expected behavior

Typescript shouldn't complain about the EditorRefPlugin.

**Comment by vect-tsauques** [comment]
It has been fixed in https://github.com/facebook/lexical/pull/4771, not yet released.
