### ISSUE TITLE
Bug: Table cell data dissapearing with Experimental Table and showing error mesage

### ISSUE THREAD

**Issue by kartikachauhan9** [facebook/lexical#4790]
We tried adding a Lexical Experimental table in our code and tried to type in data but the data is disappearing once focus is out. 
On clicking back on the cell where data disappeared the error is shown as below : 
We were also able to reproduce the same issue in Lexical dev as well a couple of times but it isnt consistent.

https://github.com/facebook/lexical/assets/108726680/de48c24c-2de1-441e-b68f-634377b69f30

Lexical version: 0.10.0
We have also tried with Version 0.11.0 and 0.11.1 ( the issue still exisits ) 

1. Slash command add Lexical Experimental Table. 
2. Try to add data inside the table and do random selections. 
3. The above error is sometimes reproducible.

**Comment by HitaishLokeshEntr** [comment]
Any update on this anybody from the lexical team ?

**Comment by ivailop7** [comment]
Experimental table was deprecated quite some time ago. Closing.
