### ISSUE TITLE
Bug: Experimental Table the data cell is getting empty 

### ISSUE THREAD

**Issue by HitaishLokeshEntr** [facebook/lexical#4791]
We tried adding a Lexical Experimental table in our code and tried to type in data but the data is disappearing once focus is out.
On clicking back on the cell where data disappeared the error is shown as below :
We were also able to reproduce the same issue in Lexical dev as well a couple of times but it isnt consistent.

https://github.com/facebook/lexical/assets/120470917/47d3728a-ef42-40f8-8b2e-b0c45e447b75

Lexical version: 0.10.0
We have also tried with Version 0.11.0 and 0.11.1 ( the issue still exisits )

1. Slash command add Lexical Experimental Table.
2. Try to add data inside the table and do random selections.
3. The above error is sometimes reproducible.

Please help us with it. We really need it to work. We tried debugging it but werent able to get the solution for it. 

The error in console is as follows : 

Uncaught Error: Minified Lexical error #38; visit https://lexical.dev/docs/error?code=38 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error code #38
setEditorState: the editor state is empty. Ensure the editor state's root node never becomes empty.

**Comment by HitaishLokeshEntr** [comment]
Any update on this anybody from the lexical team ?

**Comment by acywatson** [comment]
This table is experimental and unsupported and you shouldn't use it. We can only provide support for the current standard tables plugin.
