### ISSUE TITLE
Feature: Can we have table component to be used twice by having different styling

### ISSUE THREAD

**Issue by kartikachauhan9** [facebook/lexical#4793]
We are trying to implement both tables and columns in our platform. The issue is we are not able to differentiate between the two stylings since we are using table to make it look like a column. 

Can we otherwise know how table plugin can be used twice but with two different styling?

**Comment by HitaishLokeshEntr** [comment]
Any update on this anybody from the lexical team ?

**Comment by ivailop7** [comment]
Just create a new plugin with a custom node extending the TableNode and you can override the style classes uses in your custom node in the createDOM method.

**Comment by HitaishLokeshEntr** [comment]
@ivailop7  Do you have an exmaple i can take inspiration off from?

**Comment by ivailop7** [comment]
Probably easiest to copy the TableNode with its child nodes from the table plugin and go from there: https://github.com/facebook/lexical/tree/main/packages/lexical-table/src
