### ISSUE TITLE
Feature: handle paste text event like in draftjs

### ISSUE THREAD

**Issue by Sotatek-LamHo** [facebook/lexical#4794]
In draftjs, I see there is an event: `handlePastedText` ([link ref](https://draftjs.org/docs/api-reference-editor/#handlepastedtext)) that handles what will happen when I paste text into the editor
I would be very nice if lexical can support this as well (or maybe it supported but I can't see it)?
Thanks

**Comment by ivailop7** [comment]
It's already supported via the importDOM method in your nodes, you can see an example here: https://github.com/facebook/lexical/blob/ccf8bf3704fe568b9ad57e33ef102704b568a821/packages/lexical-code/src/CodeNode.ts#L177-L195 where it differentiates if a table tag is pasted that has GitHub properties to be recognized as a code block.

**Comment by Sotatek-LamHo** [comment]
I know the PASTE_COMMAND and the browser paste event, but both of those are fired when text is pasted, but I want to handle when the event happens and what happen to those text before they are pasted to the editor, not when it's already fired

**Comment by Sotatek-LamHo** [comment]
@acywatson could you pls give me more info for my above statement?

**Comment by acywatson** [comment]
> @acywatson could you pls give me more info for my above statement?

I'm not sure what else to tell you, to be honest. It's perfectly possible to do anything you want in response to a paste event in Lexical by using one of the approaches Ivo and I mentioned.
