### ISSUE TITLE
Bug: Custom Node error: parseEditorState: type "ghost" + not found

### ISSUE THREAD

**Issue by sophia9211** [facebook/lexical#4806]
Editors with custom nodes check for errors that cannot be [parseEditorState](https://lexical.dev/docs/concepts/editor-state#updating-state) 

Lexical version: 0.11.2

I made custom TextNode as this [document](https://lexical.dev/docs/concepts/nodes#extending-textnode)
and showing this error
<img width="588" alt="스크린샷 2023-07-21 오후 3 30 53" src="https://github.com/facebook/lexical/assets/48948598/e911bf4a-7899-43ae-a235-cc011a9dba90">
error: parseEditorState: type "ghost" + not found

https://github.com/facebook/lexical/blob/e0e77b5e9c03d4b609ec913fa4824d53a48ed13a/packages/lexical/src/LexicalUpdates.ts#L299

At first, the custom node does not exist in `editor._nodes`,
After the error occurs, the corresponding custom node exists
<img width="599" alt="스크린샷 2023-07-21 오후 3 31 50" src="https://github.com/facebook/lexical/assets/48948598/f79b6491-c8dc-43f1-93a2-18d3ccfa6caa">
<img width="593" alt="스크린샷 2023-07-21 오후 3 32 07" src="https://github.com/facebook/lexical/assets/48948598/ed9750dd-be03-44af-b23e-d8a93248429b">

It seems like parsing the editor text when the config hasn't been synced yet.
Is there a status variable that checks the completion of the editor's config?
Or, if there is a special work to be done when applying a separate custom node, it is not written in the document.

**Comment by acywatson** [comment]
Did you add the node class to the registered "nodes" array in your editor config?

**Comment by sophia9211** [comment]
Yes this is my code
```
    const initialConfig: InitialConfigType = {
      namespace: 'MyEditor',
      theme: classNames,
      nodes: [LinkNode, GhostCustomNode],
      onError: useErrorLogger,
    };
```

**Comment by acywatson** [comment]
Can you provide the implementation of GhostCustomNode?
