### ISSUE TITLE
Bug: First letter removed while composing in specific condition.

### ISSUE THREAD

**Issue by khsily** [facebook/lexical#4807]
Lexical version: 0.11.2
MacOS version: Ventura 13.4.1

## Steps To Reproduce

1. Enter any text.
2. Remove All text with "backspace".
3. Enter single composition text with any other letters. ex) "아." or "아!"
4. The first letter "아" will be removed.

It only happens after text got removed with backspace.
I can confirm this issue only on MacOS.

Link to code example:
No Code changes. Tested on playground (https://playground.lexical.dev/)

## The current behavior
![Jul-21-2023 15-43-45](https://github.com/facebook/lexical/assets/30749436/0069205d-1550-4599-bb3c-8176b31d87a2)

## The expected behavior
The first text should stay there.

**Comment by khsily** [comment]
I found a workaround solution.
I don't know how it works, but blurring and focusing when 'textContent' is empty solved the issue.

Here's my code:
```typescript
import {useLexicalComposerContext} from '@lexical/react/LexicalComposerContext';
import {useEffect} from 'react';

export function CompositionBugFixerPlugin() {
  const [editor] = useLexicalComposerContext();

  useEffect(() => {
    const removeTextContentListener = editor.registerTextContentListener(
      (textContent) => {
        if (!textContent) {
          editor.update(() => {
            editor.blur();
            editor.focus();
          });
        }
      },
    );

    return () => {
      removeTextContentListener();
    };
  }, [editor]);

  return null;
}
```

**Comment by khsily** [comment]
I found a simple workaround solution.
I don't know how it works, but blurring and focusing when 'textContent' is empty solved the issue.

Here's my code:
```typescript
import {useLexicalComposerContext} from '@lexical/react/LexicalComposerContext';
import {useEffect} from 'react';

export function CompositionBugFixerPlugin() {
  const [editor] = useLexicalComposerContext();

  useEffect(() => {
    const removeTextCotnentListener = editor.registerTextContentListener(
      (textContent) => {
        if (!textContent) {
          editor.blur();
          editor.focus();
        }
      },
    );

    return () => {
      removeTextCotnentListener();
    };
  }, [editor]);

  return null;
}

```

**Comment by tranducck** [comment]
I have the same problem with IBus Vietnamese keyboard on Ubuntu
Ubuntu version: 18.04
IBus version: 1.5.17
