### ISSUE TITLE
Bug: issues with selection when there are 2 or more consecutive decorator nodes

### ISSUE THREAD

**Issue by ifrim** [facebook/lexical#4812]
Lexical version: 0.11.3

## Steps To Reproduce

1. Add 3 or more decorator nodes one after the other
2. Try to move the cursor from right to left and from left to right
3. Try to select the nodes using the keyboard from right to left and from left to right
4. Have the cursor between the **2nd and 3rd decorator nodes** and hit **backspace**
5. Have the cursor between the **1st and 2nd decorator nodes** and hit **delete**

Link to code example: 
repo: https://github.com/ifrim/lexical-selection-issue
- clone the repo locally
- run `npm i`
- run `npm run dev`
- open http://localhost:5173/

## The current behavior
When moving the cursor from left to right and there are at least two decorator nodes one after the other the focus is lost (goes to the root). When moving from right to left it works as expected.

When selecting using the keyboard (SHIFT + RIGHT_ARROW) from left to right and there are at least two decorator nodes one after the other the selection stops after selecting the first decorator node. From right to left works as expected.

When the cursor is between the **2nd and 3rd decorator nodes** and you hit **backspace** two decorator nodes are deleted.
When the cursor between the **1st and 2nd decorator nodes** and you hit **delete** two decorator nodes are deleted.

## The expected behavior
Moving the cursor from left to right doesn't lose the focus and "jumps" one node at a time. (And will be consistent with moving from right to left)

Selecting using the keyboard from left to right selects all decorator nodes one at a time. (And will be consistent with selecting from right to left)

Hitting BACKSPACE or DELETE when between decorator nodes deletes only one node.

## Possibly related issues
- https://github.com/facebook/lexical/issues/4499
- https://github.com/facebook/lexical/issues/4214
- https://github.com/facebook/lexical/issues/3748

### Cursor movement

https://github.com/facebook/lexical/assets/5877494/d7d9e4c1-7b7d-4321-ba53-8df1d5d483d1

### Selecting using the keyboard

https://github.com/facebook/lexical/assets/5877494/546f6e8e-20a7-4945-87a8-80e669cb71c8

### Deleting nodes

https://github.com/facebook/lexical/assets/5877494/90304876-528d-4036-a78e-e1b363118e99

### Behavior in firefox

https://github.com/facebook/lexical/assets/5877494/b5588209-e52b-4714-b4d2-0067a2e47313

In firefox the problem is even bigger because you can't "place" the cursor between decorator nodes.

**Comment by etrepum** [comment]
I don't think this is reproducible anymore? At least not with the inline decorator present in the playground (equation nodes)
