### ISSUE TITLE
Bug: AutoLinkPlugin should recognize common punctuation around URLs

### ISSUE THREAD

**Issue by robfig** [facebook/lexical#4816]
Lexical version: 0.13.0

## Steps To Reproduce

1. Use AutoLinkPlugin
2. Type `Examples (https://www.google.com)`

Expected: the link is linkified
Actual: it is not

This code in AutoLinkPlugin uses surrounding separators to identify links:

```javascript
const PUNCTUATION_OR_SPACE = /[.,;\s]/;

function isSeparator(char) {
  return PUNCTUATION_OR_SPACE.test(char);
}
```

I think it should include parens and brackets, or perhaps it should be possible to override the selection.

Relatedly, I am confused about how this is meant to be used:

```javascript
function createLinkMatcherWithRegExp(regExp, urlTransformer = (text) => text) {
  return (text) => {
    const match = regExp.exec(text);
    if (match === null) return null;
    return {
      index: match.index,
      length: match[0].length,
      text: match[0],
      url: urlTransformer(text),  // <-- this line
    };
  };
}
```

This will run the URL transformer for every match of the regex, including those directly adjacent to non-separators. The result is that the returned text is the match (the URL), and the `urlTransformer` is handed the entire text block that the URL appears in. I would have expected that its only called on matches that are surrounded by separators, OR the url transformer is also handed `match[0]`. I'm not sure what the utility of the current behavior could be.

Thank you very much!

**Comment by ivailop7** [comment]
This is a duplicate, a PR to fix this is open: https://github.com/facebook/lexical/pull/4430 but it hasn't gotten traction lately.
