### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by brandonfake69** [facebook/lexical#4819]
Lexical version:

## Steps To Reproduce

1. git clone https://github.com/facebook/lexical
2. cd lexical/packages/lexical-playground/
3. yarn install (npm install complains of missing husky dependency so using yarn)
4. npm run dev

Link to code example:
https://github.com/facebook/lexical/tree/main/packages/lexical-playground
I am running it with no modifications

https://github.com/facebook/lexical/tree/main/packages/lexical-playground
I am running it with no modifications

## The current behavior
Get an error: 
Failed to load PostCSS config
TypeError: Invalid PostCSS Plugin found at: plugins[0]

## The expected behavior
Expect the dev server to run without errors since it is unmodified

**Comment by ratasorin** [comment]
I think you should ```npm install``` and ```npm run start``` in the root folder of lexical because it is a monorepo, so the dependencies are resolved differently from what you would expect. That is why going into the `packages/playground` does not work, because it relies upon the dependencies of the root

**Comment by acywatson** [comment]
> I think you should `npm install` and `npm run start` in the root folder of lexical because it is a monorepo, so the dependencies are resolved differently from what you would expect. That is why going into the `packages/playground` does not work, because it relies upon the dependencies of the root

This is right

**Comment by brandonfake69** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost:3000/src/index.css
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost:3000/src/themes/PlaygroundEditorTheme.css

**Comment by brandonfake69** [comment]
When I run it in that folder it also looks like it is the same failed to load PostCSS error as before

**Comment by brandonfake69** [comment]
really poor design to have a monorepo, btw. modularity makes things simple
