### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by AnahitWeb** [facebook/lexical#4821]
When I type something in lexical and try to select all and copy, while doing copy action it's throwing error shown in the picture in the console.
The issue started to happen from 0.11.1, it is working properly in 0.10.0 version

<img width="1639" alt="Screenshot_2023-07-25_at_13 41 20" src="https://github.com/facebook/lexical/assets/36818267/b90b0b67-c1f8-4768-810d-0bde91ef6b97">

**Comment by ratasorin** [comment]
Can you provide a minimal reproducible sandbox to test the behaviour, please!

**Comment by acywatson** [comment]
Closing this unless/until we get a repro
