### ISSUE TITLE
Feature: use div instead of CSS marker with list marker

### ISSUE THREAD

**Issue by blurname** [facebook/lexical#4840]
Using div could get fully control on list. For example, I want the marker's color and size be same as the first character. I achieve it in Draft.js's fork in my work. But I counter the problem that the text selection will also contains the div marker. Is it possible to do it with no pain in lexcial

**Comment by acywatson** [comment]
I'm not sure what this issue is about - can you please provide more information or examples?

**Comment by mbohovic** [comment]
I believe that the point is that the list marker can be styled using css. if I have e.g.
`<li><span style="font-size:24px">Good day</span></li>`

so I want it to also have `li:marker ... font-size:24px`

but now it is not possible to achieve or I do not know how. Please advise. Well thank you
