### ISSUE TITLE
Meta Bug: Discussions are no longer accessible

### ISSUE THREAD

**Issue by emilecantin** [facebook/lexical#4841]
I understand as per #4733 that Q&A has moved to Discord.

However, there seemed to be a wealth of answers already there in Discussions (I can see from search results), but they're just gone now... Any way they could still be accessible for reading? Or even better, reopen them; Discord is a terrible way to document software.

Lexical version: N/A

## Steps To Reproduce

1. Search for "lexical image upload" on Google / DDG
2. Click the first search result (which at the time of writing points to https://github.com/facebook/lexical/discussions/2167)

Link to code example: https://duckduckgo.com/?q=lexical+image+upload&ia=web

## The current behavior

I get a 404.

## The expected behavior

I see the actual discussion & answers.

**Comment by emilecantin** [comment]
Note that I would've replied to #4733 if I could, but discussion is restricted...

**Comment by ivailop7** [comment]
Thanks for raising, will update the link!

**Comment by acywatson** [comment]
I restored discussions - although we don't have the bandwidth to answer everything on there AND on Discord, we don't want to lose all the historical/searchable content there.
