### ISSUE TITLE
Bug: Cursor in incorrect position after an Undo in Collaboration Mode

### ISSUE THREAD

**Issue by nadine-nguyen** [facebook/lexical#4846]
Sometimes the cursor ends up in a weird position after an undo in collaboration mode.

Lexical version: 0.11.3

## Steps To Reproduce

Go to the lexical playground with collaboration mode on

1. Type some text across multiple lines
2. Type some extra text inbetween these paragraphs
3. Undo last piece of text

https://github.com/facebook/lexical/assets/19589943/1932c937-5b59-45c7-8552-47b1ed6e9bc2

## The current behavior

The cursor ends up in an unexpected position

## The expected behavior

The cursor should end up where the "undo" happened

**Comment by BobPritchett** [comment]
Another example here with simply selecting text, hitting Ctrl+B to bold it, and then Ctrl+Z to Undo. Cursor jumps to an incorrect position.


https://github.com/facebook/lexical/assets/26860966/81eee5f8-f754-43db-8082-67cafbbfa670

**Comment by StyleT** [comment]
Closed in #6070
