### ISSUE TITLE
Table: On deletion of row

### ISSUE THREAD

**Issue by klentynaveengopi** [facebook/lexical#4848]
Lexical version: 0.11.1

**Steps To Reproduce**
1.Insert row in table
2.Delete row immediately

After this, I can't able to perform any action in editor

Even in lexical playground this issue happens

**Comment by sathishsridhar** [comment]
I am able to reproduce this, shall I work on this ?

**Comment by sathishsridhar** [comment]
I am able to reproduce this issue in my local. When I tried to debug, the first descendant in the code seem to getting null. 

![image](https://github.com/facebook/lexical/assets/21175404/21bc6ed3-e2b7-4b5e-b4cb-3b01c25ddf76)

**Comment by ivailop7** [comment]
This was fixed quite some time ago. Closing.
