### ISSUE TITLE
Bug: MutableRefObject in EditorRefPlugin can be null or undefined

### ISSUE THREAD

**Issue by anton-kostiuchkov** [facebook/lexical#4849]
When initialising ref with `const editorRef = useRef<LexicalEditor>(null);` or `const editorRef = useRef<LexicalEditor>();`  to be used in EditorRefPlugin typescript throws error

![Screenshot 2023-07-31 at 14 24 55](https://github.com/facebook/lexical/assets/77150814/b50d3c46-2c34-47b4-8ec2-33922993e3e7)

Lexical version: 0.11.3

## Steps To Reproduce

1. initialise the ref with `const editorRef = useRef<LexicalEditor>(null);` or `const editorRef = useRef<LexicalEditor>();`
2.  use it in EditorRefPlugin `<EditorRefPlugin editorRef={editorRef} />`

## The current behavior

`editorRef` prop has type `React.RefCallback<LexicalEditor> | MutableRefObject<LexicalEditor>`

## The expected behavior

`editorRef` prop should be `React.RefCallback<LexicalEditor> | MutableRefObject<LexicalEditor | null | undefined>`

**Comment by anton-kostiuchkov** [comment]
I'd love to contribute but I don't have write access to the repo.

**Comment by acywatson** [comment]
> I'd love to contribute but I don't have write access to the repo.

Awesome!! You can just for the repo and make a pull request - this is the conventional way to contribute to an open source project. Let me know if you need additional guidance.
