### ISSUE TITLE
Bug: Issue in Add Column shortcut in Experimental table

### ISSUE THREAD

**Issue by sathishsridhar** [facebook/lexical#4857]
On Hovering a table created using the Experimental version of the table plugin, shortcuts for adding the column and row appears. I am able to hover over the row shortcut and click it to add a new row but unable to do the same for column because the add column shortcut disappears when the mouse pointer leaves the table.

This issue can be reproduced in the Lexical Playground itself.

## The current behavior

https://github.com/facebook/lexical/assets/21175404/a3700168-441d-4dd6-811b-e497278b0d28

**Comment by acywatson** [comment]
This is experimental. We don't support it and won't be addressing any bugs related to it at this time.
