### ISSUE TITLE
Bug: creates multiple custom nodes for no reason

### ISSUE THREAD

**Issue by harbar20** [facebook/lexical#4863]
I'm trying to create a searchbar with filters, similar to Discord's search or Github's issue search. I have a filter called "category:" that filters categories. When you try to create that node, it creates it, but when you hit space to keep typing, it creates another "ghost" one. And then if you delete that node in the text area, it keeps the "ghost" one. No idea what's happening. I even asked in the Discord server with no luck.

Lexical version: 0.11.3

## Steps To Reproduce

1. Click on the sandbox and open the console.
2. Type "category:art" in the text area (without the quotes) and hit enter. It should create the node for you.
3. Hit space. You'll see in the console that it found 2 matches. These matches are getting printed on Line 256 in CategoryPlugin.tsx.

Link to code example: https://codesandbox.io/s/hungry-morse-txj55j 

## The current behavior
It creates 2 nodes.

## The expected behavior
It should create only 1.

**Comment by harbar20** [comment]
These issues might be related, though I'm not entirely sure:

#4806 #4777

**Comment by acywatson** [comment]
Pass the key to the constructor in the clone method in CategoryNode:

```
  static clone(node: CategoryNode): CategoryNode {
    return new CategoryNode(node.__category, node.__key);
  }
  ```

https://codesandbox.io/s/confident-panka-zwc9m2?file=/src/nodes/CategoryNode.ts:568-680

**Comment by harbar20** [comment]
It worked. Thanks!
