### ISSUE TITLE
Bug: Font Colors do not apply to text within cells

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#4880]
Bold, Italic, Underline work by selecting multiple cells and applying those styles, but color and backgroundColor do not get applied:

https://github.com/facebook/lexical/assets/7893468/a09963c6-945c-492d-9d0d-4cd266d22ce9

**Comment by tahir606** [comment]
Hi guys, a question regarding this issue. From what I have been able to capture from going through the code is that gridSelection is being used for table selections. But it has been marked as deprecated throughout the code. Can somebody explain that?

@ivailop7

**Comment by ivailop7** [comment]
The tables guru is @fantactuka

**Comment by tahir606** [comment]
@ivailop7 I have resolved this issue, the functionality for this issue wasn't built, but I have added relevant compatibility.

Here's a [loom video](https://www.loom.com/share/85ac1ef1a3f9434dbff476b6545a1f6c?sid=089343f4-c146-449b-a079-6b52c958c709)


I will be cleaning up the code and opening a PR shortly.

**Comment by tahir606** [comment]
Hi! @ivailop7, I have created a PR for this issue and it is linked above. Please review and let me know if any changes are required. This is my first PR on this project so I might be missing something but I have tested lint. 

Thanks!

**Comment by ivailop7** [comment]
Great! Having a look.
