### ISSUE TITLE
Bug: HTML Generated for Nested Lists has Extra <li> Tags

### ISSUE THREAD

**Issue by yewchienteh** [facebook/lexical#4882]
The HTML generated for nested lists contains extra li tags.

Lexical version: 0.12

## Steps To Reproduce
On the Lexical playground, enter a list like this:
![image](https://github.com/facebook/lexical/assets/77644206/168e6ded-61f4-4c01-a0c1-a66295e2adb0)

## The current behavior
In the HTML generated (shown in screenshot above), there are two li's under the main ul with the second li containing the nested list. The HTML rendered would look like this with an extra bullet.
![image](https://github.com/facebook/lexical/assets/77644206/100135dd-9fa6-4bcd-8082-b01e369cb93f)

## The expected behavior
Expected the HTML to only have one li under the main ul that would contain the nested list. Something like:
```
<ul>
  <li>Tea
    <ul>
      <li>Black tea</li>
      <li>Green tea</li>
    </ul>
  </li>
</ul>
```

**Comment by acywatson** [comment]
Please see this issue: https://github.com/facebook/lexical/issues/2951
