### ISSUE TITLE
Bug: Incorrect URL Recognition in YouTube AutoEmbedPlugin

### ISSUE THREAD

**Issue by jourmooney** [facebook/lexical#4887]
The YouTube AutoEmbedPlugin seems to incorrectly recognize and try to embed non-YouTube URLs. Specifically, I noticed this behavior when I tried using the URL https://github.com/vietanhdev/anylabeling. While I expect the plugin not to consider this as a valid YouTube link, it appears to be treating it as one.

Lexical version: 0.11.1

## Steps To Reproduce

1. copy and paste the URL(`https://github.com/vietanhdev/anylabeling`).
2. you will see Youtube AutoEmbedPlugin activated.

Link to code example:

<img width="1187" alt="image" src="https://github.com/facebook/lexical/assets/79959835/6c652a36-cd10-47e8-9c39-4f5b24c3d105">

## The current behavior
The YouTube AutoEmbedPlugin attempts to embed the provided GitHub URL, presumably recognizing it as a valid YouTube link.

## The expected behavior
The plugin should not recognize non-YouTube URLs (like the GitHub URL in question) as valid YouTube links and should not attempt to embed them.

**Comment by acywatson** [comment]
Yea the regex is pretty loosey goosey here. I think it'll basically match any URL that has "/v" after the TLD.

This would be better:

```^.*(?:youtu(?:\.be|be\.com))\/(v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*```

**Comment by akshayamadhuri** [comment]
@acywatson  can i work on this issue

**Comment by acywatson** [comment]
> @acywatson can i work on this issue

Yea sure just make a PR
