### ISSUE TITLE
Bug: Small font size (e.g. 10px) in Chrome browser always being inspected to be "12px"

### ISSUE THREAD

**Issue by fannifanni** [facebook/lexical#4888]
Lexical version: `main`

## Steps To Reproduce

1. Visit [https://playground.lexical.dev/](https://playground.lexical.dev/)
2. Change the font size of arbitrary text to a number below 12px (excluding 12px). For example, 10px
3. "Right-click" the text and select "Inspect"
4. Follow the instruction below and hover to the text:

  ![step](https://github.com/facebook/lexical/assets/135085401/d567ffe1-efe4-45c6-abdc-7af322d3215e)

## The current behavior
![font-size-10px:11px-not effect](https://github.com/facebook/lexical/assets/135085401/3994b281-116f-49de-9f23-0911dd26da1a)

## The expected behavior

The displayed font-size pointed by the red arrow should be 10px

**Comment by acywatson** [comment]
This appears to be a browser issue - Lexical seems to be applying the styles. That popover is a browser feature which we don't control.
