### ISSUE TITLE
Bug: AutoLink does not work when typing a URL

### ISSUE THREAD

**Issue by robfig** [facebook/lexical#4892]
The auto link plugin stops linkifying URLs prematurely when they are typed out rather than pasted. 

## Steps To Reproduce

1. In the Lexical playground, create a new paragraph and type the following: https://www.google.com

Expected: [https://www.google.com](https://www.google.com)
Actual: [https://www.google](https://www.google).com

**Comment by prestonbrown-me** [comment]
Appears to be the same issue as this. 

https://github.com/facebook/lexical/issues/3546

**Comment by robfig** [comment]
Indeed! Thanks
