### ISSUE TITLE
Bug: Pasting a table inside another table throws an error and breaks the page

### ISSUE THREAD

**Issue by lopezeliecer** [facebook/lexical#4901]
When the user copies and paste a table inside another table and then tries to open the popup menu, in production mode, it throws an error that breaks the app.

The error says "Minified Lexical error #115"

When I try to reproduce it in development mode we get the following error "Error: Unexpected empty cell" and lots of "TypeError: findFn is not a function"

Lexical version: 0.11.2

## Steps To Reproduce

1. Add a table with at least 2 columns
2. Put some text inside both columns
3. Copy the table
4. Paste it right after the text of the second column
5. Open the column menu of the pasted table

https://github.com/facebook/lexical/assets/106270839/5b79c437-56f3-4ddd-a276-af4232e21f07

![Screenshot 2023-08-18 at 11 57 33](https://github.com/facebook/lexical/assets/106270839/73e277e3-de41-444e-a82b-94170144c268)
![Screenshot 2023-08-18 at 11 57 46](https://github.com/facebook/lexical/assets/106270839/82e19ab9-3102-4e79-893c-986695ade509)

## The current behavior
An error is thrown when the user tries to open the column menu in a table that was just pasted inside another table.

## The expected behavior
The column menu is shown without any issues and the user can perform all the actions related to this menu.

**Comment by ivailop7** [comment]
Bump the version to 0.11.3 I believe this one includes the findFn fix, that said nesting tables is not working well right now in general.

**Comment by ivailop7** [comment]
Nested tables was fixed some time ago, not sure which version, but definitely 6 months+ at this point.
