### ISSUE TITLE
Not working with Next.js

### ISSUE THREAD

**Issue by osvald0** [facebook/lexical#4924]
I've used the [plain example code](https://codesandbox.io/s/lexical-plain-text-example-g932e) in a next.js but it isn't working.
Although it has some minor updates to adapt it to next.js the code is exact the same that the code in the codesandbox.
I can't see any error, just the text area input is not editable.
Can you tell me if I'm missing something?

Lexical version: 0.12.0

## Steps To Reproduce

1. Run the project
2. Try to edit the text area input.

Link to code example:

[github](https://github.com/osvald0/nextjs-lexical-test-js)

## The current behavior

The text are input is not editable.

## The expected behavior

The text are input should be editable.

**Comment by zignis** [comment]
It's editable. The problem is that you might be clicking on the placeholder, which is a relatively positioned element as you have not added any styles to it. The actual content editable element sits just before the placeholder. Style the placeholder with position absolute and pointer-events: none so that the placeholder sits on the top of the content editable, like this: https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/ui/Placeholder.css

**Comment by osvald0** [comment]
Thanks for you response.
The placeholder style is there.

![Screenshot 2023-08-27 at 01 53 32](https://github.com/facebook/lexical/assets/20977158/5478037e-4460-4dbf-ac59-38d0ee5f102e)

**Comment by zignis** [comment]
> Thanks for you response. The placeholder style is there.
> 
> ![Screenshot 2023-08-27 at 01 53 32](https://user-images.githubusercontent.com/20977158/263509229-5478037e-4460-4dbf-ac59-38d0ee5f102e.png)

The content editable has `contenteditable="false"`, make sure you pass `editable: true` in your editor config (passed to the composer)

**Comment by osvald0** [comment]
Yes but it keeps the "false" value even when I pass `contentEditable={true}` to the `ContentEditable` lexical component.

```
'use client'

import { LexicalComposer } from "@lexical/react/LexicalComposer";
import { PlainTextPlugin } from "@lexical/react/LexicalPlainTextPlugin";
import { ContentEditable } from "@lexical/react/LexicalContentEditable";
import { HistoryPlugin } from "@lexical/react/LexicalHistoryPlugin";
import { OnChangePlugin } from "@lexical/react/LexicalOnChangePlugin";
import LexicalErrorBoundary from "@lexical/react/LexicalErrorBoundary";
import TreeViewPlugin from "./plugins/TreeViewPlugin";
import EmoticonPlugin from "./plugins/EmoticonPlugin";
import MyCustomAutoFocusPlugin from "./plugins/MyCustomAutoFocusPlugin";
import editorConfig from "./editorConfig";
import onChange from "./onChange";

export default function Editor() {
  return (
    <LexicalComposer initialConfig={editorConfig}>
      <div className="editor-container">
        <PlainTextPlugin
          contentEditable={<ContentEditable contentEditable={true} className="editor-input" />}
          placeholder={<Placeholder />}
          ErrorBoundary={LexicalErrorBoundary}
        />
        <OnChangePlugin onChange={onChange} />
        <HistoryPlugin />
        <TreeViewPlugin />
        <EmoticonPlugin />
        <MyCustomAutoFocusPlugin />
      </div>
    </LexicalComposer>
  );
}

function Placeholder() {
  return <div className="editor-placeholder">Enter some plain text...</div>;
}
```

**Comment by zignis** [comment]
You have to pass `editable: true` in your [editorConfig.js](https://github.com/osvald0/nextjs-lexical-test-js/blob/main/src/components/LexicalTextEditor/editorConfig.js) as such:

```js
import { EmojiNode } from "./nodes/EmojiNode";
import ExampleTheme from "./themes/ExampleTheme";

const editorConfig = {
  theme: ExampleTheme,
  editable: true, // this make the editor editable
  onError(error) {
    throw error;
  },
  nodes: [EmojiNode]
};

export default editorConfig;
```

**Comment by osvald0** [comment]
Is it working from your side? Because it doesn't work from my side.

**Comment by zignis** [comment]
I've created a codesandbox based off your updated repository and it's working fine on my side: [https://codesandbox.io/p/github/zignis/nextjs-lexical-test-js](https://codesandbox.io/p/github/zignis/nextjs-lexical-test-js/main?file=%2Fsrc%2Fcomponents%2FLexicalTextEditor%2FeditorConfig.js%3A1%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clltg0ro0000h2867ohpr4lv5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clltg0ro0000c2867cydzmhi2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clltg0ro0000g2867ngiegmbi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clltg0ro0000e28675uggkgt7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clltg0ro0000c2867cydzmhi2%2522%253A%257B%2522id%2522%253A%2522clltg0ro0000c2867cydzmhi2%2522%252C%2522activeTabId%2522%253A%2522clltgfemv02tj2867fq7adxgu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clltg0ro0000b2867qhw5gu2w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FLexicalTextEditor%252FeditorConfig.js%2522%252C%2522id%2522%253A%2522clltgfemv02tj2867fq7adxgu%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clltg0ro0000e28675uggkgt7%2522%253A%257B%2522id%2522%253A%2522clltg0ro0000e28675uggkgt7%2522%252C%2522activeTabId%2522%253A%2522clltg14x800wg2867mmjeqkec%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clltg14x800wg2867mmjeqkec%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clltg0ro0000g2867ngiegmbi%2522%253A%257B%2522id%2522%253A%2522clltg0ro0000g2867ngiegmbi%2522%252C%2522activeTabId%2522%253A%2522clltg12ry00lj2867c1k2husr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clltg0ro0000f2867ekjgn9wg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clltg0rwv0016e4id0h3k0s4f%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clltg12ry00lj2867c1k2husr%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by zignis** [comment]
I just dug into the source and found out that the editor is editable by default: https://github.com/facebook/lexical/blob/fa68893288693cb9be0b0b5d868b3f02fee14b3b/packages/lexical/src/LexicalEditor.ts#L395

The codesandbox is working fine, on my side, with and without `editable: true`. Can you please provide a reproducible example if it still doesn't work for you?

**Comment by osvald0** [comment]
Yes the github example project I already shared is not working from my side when I run it locally.

👉 [Link](https://github.com/osvald0/nextjs-lexical-test-js)

Thanks for your help!

**Comment by zignis** [comment]
Seems like an issue with your browser, do see encounter any errors? Would you mind sharing your browser details?

**Comment by osvald0** [comment]
I tested it with Safari, Chrome and Firefox with the same result.

![Screenshot 2023-08-27 at 13 19 12](https://github.com/facebook/lexical/assets/20977158/a81467e0-bd7d-4d10-9ba7-c00087711a11)

![Screenshot 2023-08-27 at 13 17 27](https://github.com/facebook/lexical/assets/20977158/60da6298-e598-46d3-82db-59d97e87fadb)

**Comment by zignis** [comment]
hmm interesting, [this codesandbox](https://codesandbox.io/p/github/zignis/nextjs-lexical-test-js/main?file=/src/components/LexicalTextEditor/editorConfig.js:7,19&workspaceId=8a501ff8-9b85-49be-aac0-c6b34330b617) created from your repo works fine for me. Lets wait for someone form the core team.

**Comment by osvald0** [comment]
Thanks a lot for try to help me. My problem is only with Next because If I try the same code but in a project with react and vite it works fine.

**Comment by dirheimerb** [comment]
I initially had issues with Next. The problem is, the editor can't be SSR. So to fix this issue I did this:

```ts
import dynamic from 'next/dynamic';
const EditorContainer = dynamic(
  () => import('@/components/EditorComponent/EditorContainer'),
  { ssr: false },
);

```

Hope that helps!

**Comment by Xananax** [comment]
I found that it works as long as you do not use placeholder. So for example, this works:
```ts
export function Editor({ markdown }: { markdown: string }) {
  const initialConfig: InitialConfigType = {
    nodes,
    editorState: () => {
      $convertFromMarkdownString(markdown, TRANSFORMERS);
    },
  };

  return (
    <LexicalComposer initialConfig={initialConfig}>
      <AutoLinkPlugin />
      <LinkPlugin />
      <CodeHighlightPlugin />
      <RichTextPlugin
        contentEditable={<ContentEditable />}
        placeholder={null}
        ErrorBoundary={LexicalErrorBoundary}
      />
      <MarkdownShortcutPlugin />
      <FloatingTextFormatToolbarPlugin />
    </LexicalComposer>
  );
}
```

But you get the initially collapsed content boxes as described in https://github.com/facebook/lexical/issues/4960

To work around that, I made my own placeholder plugin:

```ts
import { useEffect, useState } from "react";
import { useLexicalComposerContext } from "@lexical/react/LexicalComposerContext";

/**
 * The placeholder feature of RichText/PlainText of lexical has hydrations issues with SSR.
 * This is a quick hack to show something initially and then hide it as soon as the editor
 * loads.
 */
export function MarkdownPlaceHolderPlugin({ children }: { children: React.ReactNode }) {
  const [editor] = useLexicalComposerContext();
  const [show, setShow] = useState(true);

  useEffect(() => {
    setShow(false);
  }, [editor]);

  return show ? <pre style={{ whiteSpace: "pre-wrap" }}>{children}</pre> : null;
}

```

And then use it:

```ts
export function Editor({ markdown }: { markdown: string }) {
  const initialConfig: InitialConfigType = {
    nodes,
    editorState: () => {
      $convertFromMarkdownString(markdown, TRANSFORMERS);
    },
  };

  return (
    <LexicalComposer initialConfig={initialConfig}>
      {/* snip - same plugins as before */}
      <MarkdownPlaceHolderPlugin>{markdown}</MarkdownPlaceHolderPlugin>
    </LexicalComposer>
  );
}
```
