### ISSUE TITLE
Bug: The mentions plugin seems to be suggesting names even when used without the '@' symbol

### ISSUE THREAD

**Issue by KarthikRaju391** [facebook/lexical#4950]
## Steps To Reproduce

1. Open lexical [playground](https://playground.lexical.dev/)
2. Start typing for example "Kar" on a new line and you'll see the mention plugin's menu pop up with suggested names.

## The current behavior
It shows the names even without the '@' symbol being added.

## The expected behavior
Should show the list of names only when the '@' symbol is there

**Comment by KarthikRaju391** [comment]
> This is a different plugin called Autocomplete or something.

@acywatson, what I mentioned above is happening with the autocomplete option disabled in the settings.
![image](https://github.com/facebook/lexical/assets/67912316/56647870-d92c-44d8-90b6-e11c113b37fa)

The way autocomplete plugin works is different
![image](https://github.com/facebook/lexical/assets/67912316/f4d84f80-5e04-46c7-8524-81ecb9e860d3)

**Comment by acywatson** [comment]
Ok, it's not autocomplete, it's just a feature of mentions:

https://github.com/facebook/lexical/blob/ad4411e6f8b97d8a529e74c021308802c4a1484b/packages/lexical-playground/src/plugins/MentionsPlugin/index.tsx#L537

It's still not a bug.
