### ISSUE TITLE
Bug: Placeholder rendered outside the Editable Field

### ISSUE THREAD

**Issue by rishkwal** [facebook/lexical#4953]
The code sample in [Lexical React Docs](https://lexical.dev/docs/getting-started/react) renders the placeholder outside the editable field.
The blue bordered box is the editable field and "Enter some text..." is supposed to be the placeholder:
```
<LexicalComposer initialConfig={initialConfig}>
  <PlainTextPlugin
    contentEditable={<ContentEditable />}
    placeholder={<div>Enter some text...</div>}
    ErrorBoundary={LexicalErrorBoundary}
  />
  <HistoryPlugin />
  <MyCustomAutoFocusPlugin />
</LexicalComposer>
```

Lexical version: 0.12.0

## The current behavior
Placeholder rendered outside the editable field
<img width="453" alt="Lexical placeholder" src="https://github.com/facebook/lexical/assets/62797354/baaad59b-da07-42a3-ae90-8c37328f284e">

## The expected behavior

The placeholder should be rendered inside the editable field

**Comment by arthurac1337** [comment]
Having the same issue

**Comment by acywatson** [comment]
This is just how it works. You need to position it inside the content editable (or wherever you want it to be positioned). Check the playground example. or search for other issues about this that suggest alternative approaches.
