### ISSUE TITLE
Bug: using the `useLexicalEditable` hook results in "cannot find lexical composer context"

### ISSUE THREAD

**Issue by KarthikRaju391** [facebook/lexical#4959]
Lexical version: 0.12.0

## Steps To Reproduce

1. Import useLexicalEditable from '@lexical/react/useLexicalEdtiable'
2. In the Editor component, try the following code: `const isEditable = useLexicalEditable()`

Code example:
<img width="820" alt="image" src="https://github.com/facebook/lexical/assets/67912316/003a76d5-3a18-41d4-9da2-6d87a468f752">

Error:
<img width="785" alt="image" src="https://github.com/facebook/lexical/assets/67912316/34c217bc-003c-4166-968b-76e09147e402">

**Comment by acywatson** [comment]
Do you have the Editor component wrapped in a LexicalComposerContext? Typically we recommend using LexicalComposer, which wraps it's children in LexicalComposerContext, enabling you to use hooks such as this one in those plugins. Another option is just to use an editable listener: https://lexical.dev/docs/concepts/listeners#registereditablelistener

**Comment by KarthikRaju391** [comment]
I have wrapped the Editor component inside the the LexicalComposer. Basically, I am doing it exactly the same as it's done in the source code of the playground...

**Comment by sumitvekariya** [comment]
Facing the same error, how to fix this?

**Comment by siyasiyasiya** [comment]
Hey, has anyone found a solution?
