### ISSUE TITLE
Bug: Mentions triggered somehow for list types

### ISSUE THREAD

**Issue by safa-kajabi** [facebook/lexical#4976]
Lexical version: "@lexical/react": "^0.12.0",

## Steps To Reproduce

-- Make sure that you are using the mentions plugin --

1. Create a list
2. Click the first word beside the dot or number type in the list and you will see the mentions

https://github.com/facebook/lexical/assets/127859730/b95326b5-a154-4321-905e-34811cb8c79f

Link to code example:

https://playground.lexical.dev/

## The current behavior

It shows the mentions when we click the word in the list

## The expected behavior

It should not trigger the mentions if it is not a mention.

**Comment by acywatson** [comment]
I think we should just disable the capital-word trigger for the playground mentions plugin. It's annoying and trivial to implement if someone wants to do it in their own editor.

**Comment by safa-kajabi** [comment]
> I think we should just disable the capital-word trigger for the playground mentions plugin. It's annoying and trivial to implement if someone wants to do it in their own editor.

Yeah this is the problem. What should ı do to disable it in my own editor ?  @acywatson

**Comment by safa-kajabi** [comment]
I think we can disable it with returning the "match" instead of using the `checkForCapitalizedNameMentions` function. Right?

```js
export const getPossibleQueryMatch = (text: string): MenuTextMatch | null => {
  const match = checkForAtSignMentions(text, 1);
   return match;
  return match === null ? checkForCapitalizedNameMentions(text, 3) : match;
};

```

**Comment by acywatson** [comment]
> I think we can disable it with returning the "match" instead of using the `checkForCapitalizedNameMentions` function. Right?
> 
> ```js
> export const getPossibleQueryMatch = (text: string): MenuTextMatch | null => {
>   const match = checkForAtSignMentions(text, 1);
>    return match;
>   return match === null ? checkForCapitalizedNameMentions(text, 3) : match;
> };
> ```

yep, that works!

https://github.com/facebook/lexical/blob/75c9ae53e4961042527416ace9f7d05b54986b2e/packages/lexical-playground/src/plugins/MentionsPlugin/index.tsx#L587

**Comment by safa-kajabi** [comment]
Nice! Thanks!

**Comment by acywatson** [comment]
https://github.com/facebook/lexical/pull/4991

**Comment by safa-kajabi** [comment]
> #4991

Thanks a lot!!
