### ISSUE TITLE
Bug: ElementNode can not resolve in vscode

### ISSUE THREAD

**Issue by liuweiGL** [facebook/lexical#4981]
`const parentNode = node.getParentOrThrow()` then `parentNode.xxx` doesn't have autocomplete feature.

Lexical version: 0.12.2

## The current behavior
vscode can not resolve ElementNode  in LexicalNode.d.ts
![动画](https://github.com/facebook/lexical/assets/21048878/cc38af25-a3db-4e7a-a4b5-0be7413ce4d6)

## The expected behavior
ElementNode  can be correctly resolved

**Comment by acywatson** [comment]
This works fine for me - are you sure it's not a configuration issue on your end?

**Comment by thegreatercurve** [comment]
Closing as related PR has also been closed.
