### ISSUE TITLE
Feature: Pass `LexicalEditor` to `LexicalComposer`

### ISSUE THREAD

**Issue by montlebalm** [facebook/lexical#4986]
It would be useful to be able to pass an instance of `LexicalEditor` into `LexicalComposer` just like you're able to do with `LexicalNestedComposer`.

I'm working with a setup where a `DecoratorNode` needs to generate serialized versions of 2 editors rendered with a React component. It's simpler if the `DecoratorNode` controls the editor instances and passes them down to the component. The alternative is having the `DecoratorNode` prop drill the params necessary to render the editors, let the React component instantiate the editors, and then access the instances via multiple levels of refs.

The `LexicalComposer` config still allows for a `editor__DEPRECATED` param that makes my proposal possible. My feature request is to drop the `__DEPRECATED` label and support it as a config option.

To avoid confusion, the initial config could support both `editor` and `editorState`, but only allow one at a time.

PR that deprecated the `editor` prop: https://github.com/facebook/lexical/pull/1407

**Comment by yf-yang** [comment]
After examine the code, I found you can create your own provider of LexicalComposerContext, it is exported.

**Comment by etrepum** [comment]
If you're not using it to create the editor, then you should create a LexicalComposerContext directly
