### ISSUE TITLE
Bug: Limitations of `TextNode` node overrides, caused by `node.type === 'text'` checks

### ISSUE THREAD

**Issue by giacomoran** [facebook/lexical#4987]
Lexical version: 0.12.1

## Steps To Reproduce

Example symptom of the problem:

1. Create `CustomTextNode` node override of `TextNode`
2. Insert some text and select some portion of it
3. Toggle bold on, now we have two `CustomTextNode` next to each other
4. Toggle bold off, the two `CustomTextNode` will not merge (using `TextNode` they would merge)
5. Override the `isSimpleText` method to account for the custom node's type

```js
isSimpleText() {
  return (
    (this.__type === "text" || this.__type === "custom-text") &&
    this.__mode === 0
  );
}
```

6. Repeat, the two `CustomTextNode` will now merge

Link to code example: https://codesandbox.io/s/textnode-override-node-type-type-38lf28

https://github.com/facebook/lexical/assets/8596184/ba0f773e-8ba4-4fda-8fa0-82542908ee4a

## The current behavior

The behavior of `TextNode` node overrides unexpectedly deviates from `TextNode`.
That's because of `node.type === 'text'` checks [throughout the codebase](https://github.com/search?q=repo%3Afacebook%2Flexical+%22type+%3D%3D%3D+%27text%27%22&type=code).
The custom node's `type` property must necessarily be different from `'text'`

Our use case is to filter out some characters from JSON serialized `TextNode`s. We were hoping to use node overrides, following [the documentation](https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling). But the approach appears to be brittle.

## The expected behavior

If the problem cannot be fixed, it should be documented.

**Comment by acywatson** [comment]
This is a good point - thanks for making this issue. I don't actually know why we're doing check against the raw type string in all these cases. Possibly for performance reasons to avoid instanceof checks. We should be able to get most of the best of both worlds though by just abstracting this check into something overrideable.

**Comment by acywatson** [comment]
Out of curiosity, have you tried locally changing these checks to see if it fixes your problem? If so, maybe a PR would be a good idea.

**Comment by giacomoran** [comment]
If I override `isSimpleText` the problems are gone, but I'm worried about undetected problems since the check appears elsewhere in the codebase.

Instead, I'm currently monkey patching `TextNode`, following https://github.com/facebook/lexical/issues/1262#issuecomment-1036438842

---

I see that `TabNode`, `KeywordNode`, `HashtagNode` and other nodes, all extend `TextNode`.
In those cases checking for `node.__type === 'text'` in `isSimpleText` makes sense.

My use case is different, I need to override the default `TextNode`.

**Comment by giacomoran** [comment]
`$isXNode` uses `instanceof`.
Maybe, as you were suggesting, we could have an abstract `$isXNodeStrict` that uses the type string. It shoud account for node overrides, like `$createXNode` does using `$applyNodeReplacement`.

I can open a PR.

**Comment by acywatson** [comment]
> I can open a PR.

Yea I think this would be a good way to continue the conversation - can get feedback from the rest of the team too.

Thank you!

**Comment by giacomoran** [comment]
Upon more diligent review, I realized it suffices to override `isSimpleText`, my bad.
I opened #5006 to update the docs.

**Comment by acywatson** [comment]
> Upon more diligent review, I realized it suffices to override `isSimpleText`, my bad. I opened #5006 to update the docs.

No worries! Thanks for looking into it!

**Comment by timotgl** [comment]
Overriding `isSimpleText` in a class inheriting from `TextNode` causes an issue with `RangeSelection.extract()` for us (we're using lexical 0.13.1). This method calls `TextNode.splitText()` internally and we can see how the text node *is* properly split, but the new node that contains just the selected slice of text is not added to the editor. Any clue what might cause this? Is overriding `isSimpleText` officially supported?

CC @cideM

**Comment by Kamyil** [comment]
Same thing happening for me when trying to override default `exportDOM()` method for `TableCellNode` to remove inline `border: 1px solid black;` styling
https://github.com/facebook/lexical/blob/main/packages/lexical-table/src/LexicalTableCellNode.ts#L157

It throws me

```
 Error: Create node: Type tablecell in node ExtendedTableCellNode does not match registered node _TableCellNode with the same type
 ```
 
despite setting the explicit replacement in nodes array
```
// ...
	{
		replace: TableCellNode,
		with: (node: TableCellNode) =>
			new ExtendedTableCellNode(
				node.__headerState,
				node.__colSpan,
				node.__rowSpan,
				String(node.__width)
			)
	},
// ...
```

Is there any other way to handle this without monkey-patching maybe? 🥹

**Comment by etrepum** [comment]
That error is telling you that you implemented ExtendedTableCellNode incorrectly and what to fix. Two nodes can not have the same type, so give it a unique one.

**Comment by Kamyil** [comment]
Okay, thank you. This one moved the solution forward. But now it throws this error on content which was previously using default tablecell

```
Error: Lexical node does not exist in active editor state. Avoid using the same node references between nested closures from editorState.read/editor.update.
```

while still having previous replacement code in place.
Here's my `ExtendedTableCell` node

```
import { TableCellNode } from '@lexical/table';
import type {
  DOMExportOutput,
  LexicalEditor,
} from 'lexical';

const COLUMN_WIDTH = 75;

export class ExtendedTableCellNode extends TableCellNode {
  static getType(): string {
      return 'extended-tablecell'
  }
  exportDOM(editor: LexicalEditor): DOMExportOutput {
    const { element } = super.exportDOM(editor);

    if (element) {
      const element_ = element as HTMLTableCellElement;

      if (this.__colSpan > 1) {
        element_.colSpan = this.__colSpan;
      }
      if (this.__rowSpan > 1) {
        element_.rowSpan = this.__rowSpan;
      }
      element_.style.width = `${this.getWidth() || COLUMN_WIDTH}px`;
      element_.style.verticalAlign = 'top';
      element_.style.textAlign = 'start';
      // Removed the border style here to prevent inline border styling
    }

    return {
      element,
    };
  }
}
```

What should I change in order to let Lexical recognize this as a proper replacement for default tablecell node?
Thank you once again!

**Comment by etrepum** [comment]
clone is a required method, no node will work without it. you'll likely also want to implement importJSON and exportJSON. If you're using a recent version of lexical you should be getting warnings about those as well.
