### ISSUE TITLE
Bug: When I use CustomTextNode to overrides TextNode, useLexicalTextEntity is not working.

### ISSUE THREAD

**Issue by zxhlyh** [facebook/lexical#5023]
When I use CustomTextNode to overrides TextNode, useLexicalTextEntity is not working.

Lexical version: 0.12.2

## Steps To Reproduce

1. type {{a}}

Link to code example:
https://codesandbox.io/s/inspiring-darwin-2dxxkd?file=/src/Editor.js

### using TextNode
<img width="1328" alt="image" src="https://github.com/facebook/lexical/assets/16177003/299a43e4-9591-4e70-9b9d-9ac66bcb94b2">

### using CustomTextNode
<img width="1308" alt="image" src="https://github.com/facebook/lexical/assets/16177003/daba9c91-b42b-43e9-aa78-7d9c3c6b10e0">

## The expected behavior
<img width="660" alt="image" src="https://github.com/facebook/lexical/assets/16177003/e1741d4a-f00b-4c05-a30c-a9dbf0cf407d">

**Comment by acywatson** [comment]
try returning true from isSimpleText method on your CustomTextNode

**Comment by zxhlyh** [comment]
> try returning true from isSimpleText method on your CustomTextNode

I tried but it doesn't work

**Comment by yeion7** [comment]
@zxhlyh I faced the same issue, I found that the solution is to use `withKlass`

```js
{
  replace: TextNode,
  with: (node) => new CustomTextNode(node.__text),
  withKlass: CustomTextNode, // <--- here
},
```

Reading the lexical code for `registerNodeTransform`, the transformation get attached to the node, but also attach the transformation to the class passed in `withKlass`, [check this code](https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalEditor.ts#L855-L877)

<img width="2052" alt="image" src="https://github.com/facebook/lexical/assets/9127504/3b76f416-0a15-4eba-8be3-bbb36f8e1cdc">

**Comment by zxhlyh** [comment]
Problem solved perfectly, thank you very much.
