### ISSUE TITLE
Bug: Attempted to create node CodeNode that was not configured to be used on the editor.

### ISSUE THREAD

**Issue by jLynx** [facebook/lexical#5033]
Hi Team I am attempting to get markdown formatting (with code syntax formatting) to work with your example from the docs https://lexical.dev/docs/packages/lexical-markdown

I am trying to set it to render on initial load. This works fine for more basic markdown such as bold text etc.. but when I try and format code, I get an error
`Error: Create node: Attempted to create node CodeNode that was not configured to be used on the editor.`

Lexical version: `"@lexical/react": "^0.12.0",`

Link to code example:

```
<LexicalComposer
      initialConfig={{
        editorState: () => {
          $convertFromMarkdownString(myMarkdown, TRANSFORMERS)
        },
        editable: false,
        onError: (e, ee) => {
          console.log(e)
          console.log(ee)
        },
      }}
    >
      {/* <MarkdownShortcutPlugin transformers={TRANSFORMERS} /> */}
      <RichTextPlugin
        contentEditable={
          <ContentEditable
            style={{ tabSize: 1 }}
            className={
              "pl-3 pr-2 w-full rounded-md border border-input bg-background overflow-y-auto py-2 max-h-[11rem] min-h-[5rem] bg-white placeholder:text-muted-foreground"
            }
          />
        }
        placeholder={null}
        ErrorBoundary={LexicalErrorBoundary}
      />
    </LexicalComposer>
```

## The current behavior

Errors out and doesnt render anything.

## The expected behavior

Should render the code with syntax highlighting.

**Comment by jLynx** [comment]
> Did you try adding CodeNode and CodeHighlightNode to your editor config?

I cant seem to work out how to do that, not can I find an example. Do you have a code snippet for me to go off of?

**Comment by jLynx** [comment]
Scratch that. I worked out I needed it to be inside of nodes for it to work. I was trying to add it outside 

`nodes: [CodeNode, CodeHighlightNode],`

Thanks for pointing me in the right direction

**Comment by acywatson** [comment]
> Scratch that. I worked out I needed it to be inside of `nodes` for it to work. I was trying to add it outside
> 
> `nodes: [CodeNode, CodeHighlightNode],`
> 
> Thanks for pointing me in the right direction

No prob
