### ISSUE TITLE
Bug: @lexical/link TOGGLE_LINK_COMMAND not working

### ISSUE THREAD

**Issue by varun-s22** [facebook/lexical#5034]
Lexical version: "@lexical/link": "^0.12.2",

I tried creating a link from this command. I added a button, and on clicking it, i can't seem to add the hyperlink on the editor.

Link to code example:
Here's the code:

```  
const [isLink, setIsLink] = useState<boolean>(false)
<span
            role="button"
            onClick={() => {
              setIsLink((prev) => !prev)
              editor.dispatchCommand(TOGGLE_LINK_COMMAND, {
                url: 'https://www.google.com/',
              })
            }}
            className={`${
              isLink ? 'bg-slate-300' : ''
            } hover:bg-slate-500 hover:cursor-pointer w-6 h-6 flex justify-center items-center`}
          >
            A
          </span>
```

## The current behavior
The link is not created
<img width="461" alt="Screenshot 2023-09-21 at 18 51 50" src="https://github.com/facebook/lexical/assets/93476421/2a07c63e-05f5-40ce-bb40-3d6dafe5d7ec">

## The expected behavior
Link should be created

**Comment by acywatson** [comment]
Did you add LinkNode to your nodes in the EditorConfig?

If so, please provide a code sandbox so I can repro.

**Comment by mhedgpeth** [comment]
I have the LinkNode added to my project, with the dispatch command as above and this works for me, in the latest version. I think this issue can be closed.
