### ISSUE TITLE
Bug: Markdown exportTextFormat treats literal string as regex

### ISSUE THREAD

**Issue by robfig** [facebook/lexical#5036]
## Steps To Reproduce

1. On https://playground.lexical.dev/, clear the text area and enter the string `$$`.
2. Click Markdown export button.

## The current behavior

`$$` is exported as `$`

## The expected behavior

`$$` is exported as `$$`

The bug is here:
https://github.com/facebook/lexical/blob/716d409085e44fb7ab47a35d517e39623b4a5fc0/packages/lexical-markdown/src/MarkdownExport.ts#L168

String.prototype.replace is used for literal string replacement. In that context, "$$" in the replacement string inserts a single "$", as described here
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement

It can be fixed with this diff:

```diff
-  return textContent.replace(frozenString, output);
+  return textContent.split(frozenString).join(output);
```

**Comment by etrepum** [comment]
Can't reproduce
