### ISSUE TITLE
Bug: [playground] editor with form voice recording when press enter in input element

### ISSUE THREAD

**Issue by suhaotian** [facebook/lexical#5055]
Lexical version: latest

## Steps To Reproduce

1. open  https://bug-reproduce-for-lexical.netlify.app/

2. focus on first input, and press enter

<img width="1198" alt="image" src="https://github.com/facebook/lexical/assets/6512574/8f967fd6-6b27-4007-96c3-30ea643f19e8">

Link to code example: https://github.com/suhaotian/lexical/blob/lexical-playground-enter-recording-bug/packages/lexical-playground/src/App.tsx#L148

## The current behavior
Vocie recording when press enter in input element

## The expected behavior

This shouldn't happen.

**Comment by acywatson** [comment]
You've basically just copy pasted the entire playground - this isn't something we support, so you'll have to debug this on your own.

**Comment by suhaotian** [comment]
@acywatson Appreciated for the reply!

I just figure out what happened: this is browser's default behaviour that will fire the first button onClick when press `Enter` with form.


Maybe others will meet the same problem, so I just put my two solutions here:

- add a {display: none} button at first
-  don't wrap with form
