### ISSUE TITLE
Bug: сursor is not visible when placed before an image

### ISSUE THREAD

**Issue by vadimyen** [facebook/lexical#5063]
## Description
When an image is inserted in the RTE, and the cursor is placed before it, it is not visible. However, typing is still possible. The issue occurs only if there are no characters before the image. It's confusing since it's hard to find your current position, and it looks like the RTE is not focused.

Lexical version: 0.11.3

## Steps to Reproduce
1. Open the RTE.
2. Insert an image.
3. Place the cursor before the image.

## Link to code example:
 Just paste any image here: https://playground.lexical.dev/

## The current behavior
The cursor is not visible when placed before the image, although typing is still possible.

The cursor is at the first character:
![image](https://github.com/facebook/lexical/assets/22547943/4d8bc326-1a83-4a5e-aadd-b18a8d27a8d5)

The cursor is visible if there is a character before the image:
![image](https://github.com/facebook/lexical/assets/22547943/e866d674-83d3-4e39-8417-a694488ff0ff)

## Expected Behavior
The cursor should be visible when placed before the image, indicating the current position.

As in Wordpad:
![image](https://github.com/facebook/lexical/assets/22547943/891b4bbf-078b-4182-ba35-ab45f3c67fe9)
Or [in other editors](https://onlinehtmleditor.dev/):
![image](https://github.com/facebook/lexical/assets/22547943/35e20f12-acf0-4924-bd35-7cc06d377254)

**Comment by thegreatercurve** [comment]
I can repro this on Chromium when an image is at the start of a new line.

I think it's actually related to recently opened Chromium bug here, in that we always use the native cursor, and the image is a `contenteditable=false` element: https://bugs.chromium.org/p/chromium/issues/detail?id=1499405.

Closing so it can be tracked on Chromium.

**Comment by vadimyen** [comment]
@thegreatercurve, thank you for the response. However, I tried the same in Firefox and got the same behavior:
![image](https://github.com/facebook/lexical/assets/22547943/9a9b7c2c-1fd6-429e-a4ce-e095974fffd9)
