### ISSUE TITLE
Bug: "ImportDOM" ignores styles applied by "$patchStyle" 

### ISSUE THREAD

**Issue by Shinnosuke-Hara** [facebook/lexical#5067]
I'm in trouble because when I decorate text with style, save it to the database, and then insert it again into Lexical, it is ignored, and the style disappears when it is finally inserted.

I have reproduced this phenomenon in a Sandbox and I will share it.

Lexical version:0.12.2

## Steps To Reproduce

1. Prepare HTML with the style attribute as defaultValue.
2. Insert that HTML into Lexical using $generateNodesFromDOM().

Link to code example: https://codesandbox.io/s/kind-brown-6z9cgw?file=/src/plugins/DefaultValuePlugin.ts

## The current behavior
The style disappears, and if font-weight: 700; is specified in the style, it becomes the BOLD attribute.
## The expected behavior
The style is inserted into Lexical as is, preserving its original styling.

**Comment by acywatson** [comment]
https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling
