### ISSUE TITLE
Bug: Builds failing

### ISSUE THREAD

**Issue by Amnesthesia** [facebook/lexical#5080]
Lexical version: Current

Not sure how else to report it but the failing builds are obviously blocking all releases including nightlies, any plans to resolve this soon?

**Comment by zurfyx** [comment]
`npm run build-prod` seems to be working fine for me. If you're referring to the CI and E2E tests, we're aware of this, there's some flaky E2E tests that needs to either be addressed/disabled or moved to Unit.

**Comment by acywatson** [comment]
The nightly releases never worked properly in the first place - I am trying to fix that soon. In the meantime, there is nothing blocking releases. The core team just has to do it manually.
