### ISSUE TITLE
Bug: auto import statement says "no suggestions"

### ISSUE THREAD

**Issue by ALagoni97** [facebook/lexical#5093]
I am not sure whether or not this has anything to do with Lexical but I don't seem to have this problem with any other libraries. I think it has something to do with my tsconfig or general setup, but can't seem to find it.

The problem:
When trying to import methods / classes from the Lexical library my IDE shows "no suggestions." for the auto import. 
![image](https://github.com/facebook/lexical/assets/68890168/18e79c7b-9595-43d8-a216-b7f6b980d3d8)

Lexical version:
^0.12.2

## The current behavior
Curent behaviour in my .tsx file:
```js
import { FC, useState } from "react";

export const EditorHeader: FC = (props) => {
  const [editor] = useLexicalComposerContext();
};
```
When trying to get auto imports for `useLexicalComposerContext` it shows "no suggestions". 

My tsconfig.json:
```ts 
{
  "compilerOptions": {
    "target": "ES2020",
    "rootDir": "./src",
    "outDir": "./dist/",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    },
    "resolveJsonModule": true
  },
  "include": [
    "./src/next-env.d.ts",
    "./src/**/*.ts",
    "./src/**/*.tsx",
    "./src/.next/types/**/*.ts",
    ".next/types/**/*.ts"
  ],
  "exclude": ["node_modules"]
}

```
## The expected behavior
Auto import should suggest the following import:
`import { useLexicalComposerContext } from "@lexical/react/LexicalComposerContext";`

I suspect it has something to do with it being an ESM package and maybe my project is not configured correctly?

**Comment by funbinhe1996** [comment]
hi @ALagoni97  I believe this is more related to your  local project setting.

**Comment by ALagoni97** [comment]
@funbinhe1996 Yeah probably but I would love a repo example of a working one as I can't seem to find a way to make it work. I suspect it should work fine with import suggestions even when it's split into modules?

**Comment by funbinhe1996** [comment]
Maybe you can provide your whole project, then I can try with your project.  how about you create a new project and install lexical, it still does not work?

**Comment by ALagoni97** [comment]
https://github.com/ALagoni97/content-helper-v2

@funbinhe1996  here is a repo where the issue is.
At the `src/app/page.tsx` file I am trying to import the `useLexicalComposerContext` but the auto import suggestion is not popping up. Just a standard next project.

**Comment by funbinhe1996** [comment]
hi Alagoni97, I just git clone with your repo, and execute npm install ,then  everything is okay, i believe it's your own environment issue, i think it's okay to close this issue.
<img width="855" alt="Screenshot 2023-11-02 at 20 46 44" src="https://github.com/facebook/lexical/assets/132207366/9ba8c051-6c9a-4c46-a40f-ec65322cce82">

**Comment by ALagoni97** [comment]
The screenshot you provided does not indicate the issue I was having? If you remove the import statement for `useLexicalComposerContext()` and try and add it by autosuggestion - Does that work ? That's my issue 😄
