### ISSUE TITLE
Feature: 

### ISSUE THREAD

**Issue by cecibet** [facebook/lexical#5111]
Hello, I'm not sure if I should post this here, feel free to delete my post if it doesn't look right.

I've been trying to implement a custom MentionPlugin, mostly with success. Depending on the trigger character, a different mention type is suggested.
The thing is, that for a type of mention, on selecting one of the options, I would like it to transform into a link readable on the read-only mode. I could do this by using the TOGGLE_LINK_COMMAND of @lexical/link, but I would like it to work with React-Router, so I don't make a full refresh.
I was trying to add an onClick prop to the element created on the exportDom function, but the prop is ignored and not added to the node. 
I'm quite lost on which layer of the whole editor is the one that will allow me to add this feature.

**Comment by wobsoriano** [comment]
hey, would love to see your solution

**Comment by cecibet** [comment]
> hey, would love to see your solution
Hi, check the "NodeEventPlugin" that you can add inside the LexicalComposer. So you can add something like this:
```
<NodeEventPlugin
							nodeType={MentionNode // AnyNode you need}
							eventType={'click'}
							eventListener={(e) => {
								e.preventDefault();
								if (whatever you need here) {}
							}
						/>
```
I just added some functions inside the eventListener and that was it.

**Comment by dominictobias** [comment]
> > hey, would love to see your solution
> > Hi, check the "NodeEventPlugin" that you can add inside the LexicalComposer. So you can add something like this:
> 
> ```
> <NodeEventPlugin
> 							nodeType={MentionNode // AnyNode you need}
> 							eventType={'click'}
> 							eventListener={(e) => {
> 								e.preventDefault();
> 								if (whatever you need here) {}
> 							}
> 						/>
> ```
> 
> I just added some functions inside the eventListener and that was it.

`NodeEventPlugin` doesn't seem to be exported?

**Comment by cecibet** [comment]
I think it's just for events, yes
