### ISSUE TITLE
Bug: return types of methods are not resolved by typescript

### ISSUE THREAD

**Issue by piotrwrzodak** [facebook/lexical#5117]
Lexical version: 0.12.2

## Steps To Reproduce

1. Set `moduleResolution` to something other than "node" ("Bundler" in my case) in tsconfig.json's compilerOptions

Link to code example: [stackblitz](https://stackblitz.com/edit/vitejs-vite-h2jpdu?file=src%2FApp.tsx)

## The current behavior

Some of the methods on lexical objects have return type `any`.

![image](https://github.com/facebook/lexical/assets/56254514/b98b746a-b253-43f5-8723-56c1cbd1f4fb)

I know it is possible to cast it but I believe it is better to get to the root cause of this.

## The expected behavior

Those methods should have proper return type.

![image](https://github.com/facebook/lexical/assets/56254514/0287707e-1847-49bc-be96-27ad81456bee)

**Comment by SebastianGarces** [comment]
+1 having the exact same issue.
