### ISSUE TITLE
Bug: Jumping through hoops to make Lexical work with latest Remix.run

### ISSUE THREAD

**Issue by Abyrd9** [facebook/lexical#5120]
I'm running the latest remix.run from `npx create-remix@latest`

How I would like to import the packages from lexical:
```
import { type InitialConfigType, LexicalComposer } from "@lexical/react/LexicalComposer"
import { ContentEditable } from "@lexical/react/LexicalContentEditable"
import LexicalErrorBoundary from "@lexical/react/LexicalErrorBoundary"
import { HistoryPlugin } from "@lexical/react/LexicalHistoryPlugin"
import { OnChangePlugin } from "@lexical/react/LexicalOnChangePlugin"
import { RichTextPlugin } from "@lexical/react/LexicalRichTextPlugin"
```

But this produces the error:
![9b8f70313e76cbeb6d3bad37abfb360e](https://github.com/facebook/lexical/assets/22533745/44e7fa9b-92d5-45be-95f9-25707fad1ede)

But even when I import directly from the `.js` file:
`import { ContentEditable } from "@lexical/react/LexicalContentEditable.js"`

I'm met with a named export error:
![6f6617b6ad14319ba7830e604c3f849b](https://github.com/facebook/lexical/assets/22533745/ddb6b9b6-3c34-4b7a-902b-c548bc84682d)

So this forces me setup my imports in this way:
```
import LexicalComposerPkg from "@lexical/react/LexicalComposer.js";
import ContentEditablePkg from "@lexical/react/LexicalContentEditable.js";
import LexicalErrorBoundary from "@lexical/react/LexicalErrorBoundary.js";
import HistoryPluginPkg from "@lexical/react/LexicalHistoryPlugin.js";
import OnChangePluginPkg from "@lexical/react/LexicalOnChangePlugin.js";
import RichTextPluginPkg from "@lexical/react/LexicalRichTextPlugin.js";
import type { InitialConfigType } from "@lexical/react/LexicalComposer";

const LexicalComposer = LexicalComposerPkg.LexicalComposer;
const ContentEditable = ContentEditablePkg.ContentEditable;
const HistoryPlugin = HistoryPluginPkg.HistoryPlugin;
const OnChangePlugin = OnChangePluginPkg.OnChangePlugin;
const RichTextPlugin = RichTextPluginPkg.RichTextPlugin;
```

I also tried simply adding the imports to the `serverDependenciesToBundle` in my `remix.config.js` file.
[docs on that](https://remix.run/docs/en/main/guides/gotchas#importing-esm-packages).

I don't necessarily think it's the right use-case for this? But when I did attempt it,
I'd be met with this error:
![72bcd7911e03bb8eb9990a042a24992e](https://github.com/facebook/lexical/assets/22533745/2866672a-28cf-46ab-b8dd-e2abcd9dfbec)

this dynamic require is found here: https://github.com/facebook/lexical/blob/main/scripts/build.js#L600

I guess the bug is that I'd expect the lexical packages to work like the imports example I have at the top of this report.
The fixes I've implemented work, but they're not ideal. I know there's a lot to work through around CJS and ESM and supporting both, but I guess I'm asking if this is on the radar? 

Lexical version: `0.12.2`

## Steps To Reproduce

1. clone: https://github.com/Abyrd9/remix-lexical-error
2. run: `npm install && npm run dev`
3. navigate to localhost:3000
4. verify there are no build errors from lexical
5. go to ./app/lexical/LexicalEditor.tsx
6. follow the comment steps to switch the imports
7. open remix.config.js and uncomment out serverDependenciesToBundle
8. see module errors

Link to code example:
https://github.com/Abyrd9/remix-lexical-error

## The current behavior
Have to import like this on the latest version of Remix.run:
```
import LexicalComposerPkg from "@lexical/react/LexicalComposer.js";
import ContentEditablePkg from "@lexical/react/LexicalContentEditable.js";
import LexicalErrorBoundary from "@lexical/react/LexicalErrorBoundary.js";
import HistoryPluginPkg from "@lexical/react/LexicalHistoryPlugin.js";
import OnChangePluginPkg from "@lexical/react/LexicalOnChangePlugin.js";
import RichTextPluginPkg from "@lexical/react/LexicalRichTextPlugin.js";
import type { InitialConfigType } from "@lexical/react/LexicalComposer";

const LexicalComposer = LexicalComposerPkg.LexicalComposer;
const ContentEditable = ContentEditablePkg.ContentEditable;
const HistoryPlugin = HistoryPluginPkg.HistoryPlugin;
const OnChangePlugin = OnChangePluginPkg.OnChangePlugin;
const RichTextPlugin = RichTextPluginPkg.RichTextPlugin;
```

## The expected behavior
Would like to import like this:
```
import { type InitialConfigType, LexicalComposer } from "@lexical/react/LexicalComposer"
import { ContentEditable } from "@lexical/react/LexicalContentEditable"
import LexicalErrorBoundary from "@lexical/react/LexicalErrorBoundary"
import { HistoryPlugin } from "@lexical/react/LexicalHistoryPlugin"
import { OnChangePlugin } from "@lexical/react/LexicalOnChangePlugin"
import { RichTextPlugin } from "@lexical/react/LexicalRichTextPlugin"
```

**Comment by jordisantamaria** [comment]
Same problem here, thanks for the example so can manage to make it work somehow, even if syntax is weird.

**Comment by arman94** [comment]
I have the same problem with Lexical

**Comment by rodolphoasb** [comment]
Maybe this helps? https://github.com/remix-run/remix/discussions/7623
