### ISSUE TITLE
Bug: table copy and paste only works sometimes

### ISSUE THREAD

**Issue by tina-pina** [facebook/lexical#5163]
Copying text and pasting it into another cell only works in the "original" table created but not if more rows/columns are added. 

**Lexical version:**

latest (0.12.2)

**## The current behavior**

When pasting data in a new row/column, then the data is pasted in the next cell and the table looks broken

https://github.com/facebook/lexical/assets/40612227/2db9827e-e941-46b5-86bb-1045356f4e06

**## The expected behavior**

When pasting data in a new row/column the data is shown in the correct column and the table looks not broken

**Comment by tahir606** [comment]
I was trying to replicate this issue but was not able to. Am I missing a step?


https://github.com/facebook/lexical/assets/20771570/7e5a1e28-962f-4eee-9f7e-1d3f4e26bc0d

**Comment by tina-pina** [comment]
@tahir606 yes i am also not able to reproduce it anymore. The only difference from your example was that i copied the text from the first column (and not from the second as you did). But now it seems to work on your side at least.

**Comment by thegreatercurve** [comment]
Closing as this appears to be working now.
