### ISSUE TITLE
Bug: TableActionMenuPlugin in Playground has unexpected behavior

### ISSUE THREAD

**Issue by SimYunSup** [facebook/lexical#5199]
playground version: https://lexical-playground-3ezi6rvaa-fbopensource.vercel.app/

> It would be nice to report the package version in the playground.

## Steps To Reproduce

1. Merge Any header cell.
2. Unmerge merged cell.
3. Select cell that doesn't has background, and click "Remove Row Header"

https://github.com/facebook/lexical/assets/47362439/6a398ff3-61cd-40b0-a414-24095ce39024

## The current behavior 

It toggles `TableCellHeaderStates.Row`.

## The expected behavior

All cell in Selected Row should add or delete `TableCellHeaderStates.Row`.

## The solution I think 

1. `$unmergeCell` should create cell with `TableCellHeaderStates.Row` / `TableCellHeaderStates.Column` according to the near row / column.
2. (related to 1) `$insertTableRow__EXPERIMENTAL` / `$insertTableColumn__EXPERIMENTAL` should create cell with `TableCellHeaderStates.Row` / `TableCellHeaderStates.Column` according to the near row / column.
3. `toggleTableRowIsHeader` / `toggleTableColumnIsHeader` should use `TableCellNode.setHeaderStyles` not `TableCellNode.toggleHeaderStyles`.

**Comment by ivailop7** [comment]
This was fixed some time ago. Closing.

**Comment by SimYunSup** [comment]
Was there a modification to the merge logic that I'm not aware of?

Same behavior on https://lexical-playground-2p9vpui47-fbopensource.vercel.app/ .

And also no change on below.

https://github.com/facebook/lexical/blob/5319bf68fe1771d48b6a2cb5872bc246acd44fdf/packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx#L411

https://github.com/facebook/lexical/blob/5319bf68fe1771d48b6a2cb5872bc246acd44fdf/packages/lexical-playground/src/plugins/TableActionMenuPlugin/index.tsx#L454
