### ISSUE TITLE
Bug: Lexical Playground bug & Lexical internal logic bug in every lexical version

### ISSUE THREAD

**Issue by youngkyo0504** [facebook/lexical#5202]
Lexical version: every version

## Steps To Reproduce

https://github.com/facebook/lexical/assets/78121870/1ec772c8-4511-4d07-8e4b-e1cb685e59e0

1. select `20px` in toolbar 
2. click editor 

Link to code example:

## The current behavior
- reset default fontSize

## The expected behavior
- keep current style

I found what makes bug.  [onSelectionChange](https://github.com/facebook/lexical/blob/ed8f85fb5e5106dba237e2a166e57acaa28e8fbe/packages/lexical/src/LexicalEvents.ts#L258) has below logic.

```typescript
        if (
          currentTimeStamp < timeStamp + 200 &&
          anchor.offset === lastOffset &&
          anchor.key === lastKey
        ) {
          selection.format = lastFormat;
          selection.style = lastStyle;
      }
```

If conditional statement is true, It works expected. but `currentTimeStamp < timeStamp + 200` is false. 
What is the intention of this code??

**Comment by acywatson** [comment]
https://github.com/facebook/lexical/pull/1989

You can use Git Blame to see the commit that introduced a diff, which can help you understand the intent.

**Comment by youngkyo0504** [comment]
@acywatson  thank you! 
I have created a pull request. Could you please review my commit?
