### ISSUE TITLE
Feature: Add support for MarkDeep

### ISSUE THREAD

**Issue by arjunrbery** [facebook/lexical#5213]
Currently lexical doesn't support a way to use Markdown style diagram that can be edited on the fly. In Hugo, [GoAT](https://github.com/bep/goat) is an extremely useful and easy to learn diagramming tool, however, diagrams only generate at build time through Go. [Markdeep](https://casual-effects.com/markdeep/) is a JS implementation of the the same method of diagramming and can be used to generate the previews in real time.

As an alternative, I've considered diagramming in Draw.io and then linking to the file/image, however, that increases the number of steps in the process and defeats the flow of having a single more powerful editor.

<img width="276" alt="image" src="https://github.com/facebook/lexical/assets/20059577/6b23ad30-6b06-4780-9a0a-a45d7bf8a4b4">
<img width="289" alt="image" src="https://github.com/facebook/lexical/assets/20059577/f08062ae-2584-45f3-9fa6-5baacf0eda16">

Images taken from: [https://casual-effects.com/markdeep/](https://casual-effects.com/markdeep/)

**Comment by thegreatercurve** [comment]
I'm not sure if we want to add this to core, but this could be a potential separate open-source project someone who wanted to implement it separately. A lot of the logic could be copied from `@lexical/markdown` and then added as it's own plugin.
