### ISSUE TITLE
Bug: Node override does not change the LexicalNode

### ISSUE THREAD

**Issue by nolikob** [facebook/lexical#5215]
I have an feature request for custom list node. I had to use node override to replace ListItemNode with my CustomListItemNode. While following the documentation I had stumbled upon the need of keeping the attributes of new LexicalNode instance empty in order to create my CustomListItem node. When attributes provided, Lexical kept rendering ListItemNode, even tho it was overwritten.

Lexical version: 0.12.2

## Steps To Reproduce

1. Create custom Lexical node from ListItemNode
2. Add it to nodes array of initialConfig object.
3. Check based on selection what element is at anchor position.
4. In my case there was always ListItemNode instead of CustomListItemNode

### Initial config cut
```
                ListNode,
		CustomListItemNode,
		{
			replace: ListItemNode,
			with: (_: ListItemNode) => {
				return new CustomListItemNode(_.__value, _.__checked, _.__key);
			},
		},
```

### Custom node implementation

```
export type SerializedCustomListItemNode = Spread<
	{  }, // custom props
	SerializedListItemNode
>;

export class CustomListItemNode extends ListItemNode {
	smthn: any;
	static getType() {
		return "custom-list-item";
	}

	static clone(node: CustomListItemNode): CustomListItemNode {
		return new CustomListItemNode(node.__value, node.__checked, node.__key);
	}

	constructor(value?: number, checked?: boolean, key?: NodeKey) {
		super(value, checked, key);
	}

	setSmthn(smthn?: number) {
		const self = this.getWritable();
		self.__smthn = smthn;
	}

	getSmthn() {
		const self = this.getLatest();
		return self.__smthn;
	}

	createDOM(config: any) {
		const element = super.createDOM(config);
		element.value = this.__value;
		return element;
	}

	exportDOM(): DOMExportOutput {
		const element = document.createElement("li");
		return { element };
	}

	updateDOM(_: ListItemNode, dom: HTMLElement) {
		// updateDOM implementation
	}

	exportJSON(): SerializedCustomListItemNode {
		// exportJSON implementation
	}

	static importJSON(serializedNode: SerializedCustomListItemNode) {
		// import implementation
	}
}

export function $createCustomListItemNode() {
	return new CustomListItemNode();
}
```

## The current behavior
Custom node is only taken into account without arguments in constructor.

## The expected behavior
Custom node is used even when arguments are provided.

**Comment by acywatson** [comment]
Don't pass the key to the replacement node constructor

**Comment by nolikob** [comment]
> Don't pass the key to the replacement node constructor

Would you be able to elaborate on why? I do see the reason why not.

**Comment by acywatson** [comment]
> > Don't pass the key to the replacement node constructor
> 
> Would you be able to elaborate on why? I do see the reason why not. I see in the example with CustomParagraph the constructor is omitted and only `clone` is present but my intention was to pass into the instance additional attributes and I thought based on the inheritance I needed to pass in the original attributes via the `super()` method to the parent class.

Yea, passing the key causes Lexical to reuse the same node object reference (the one associated with that key) from the internal node map. I think that's why your override isn't working.

You can still pass the other args, just not key.

**Comment by nolikob** [comment]
> > > Don't pass the key to the replacement node constructor
> > 
> > 
> > Would you be able to elaborate on why? I do see the reason why not. I see in the example with CustomParagraph the constructor is omitted and only `clone` is present but my intention was to pass into the instance additional attributes and I thought based on the inheritance I needed to pass in the original attributes via the `super()` method to the parent class.
> 
> Yea, passing the key causes Lexical to reuse the same node object reference (the one associated with that key) from the internal node map. I think that's why your override isn't working.
> 
> You can still pass the other args, just not key.

Thanks for the clarification, I finally understand it. It would be nice however to see it in the docs for node overrides as I presume I won't be the only one in the future facing this confusion.

**Comment by acywatson** [comment]
Yea it definitely should be in the docs. I'll add that
