### ISSUE TITLE
Bug: $generateNodesFromDOM removing inline styles.

### ISSUE THREAD

**Issue by The-Code-Monkey** [facebook/lexical#5217]
So using your example on the playground where you are able to set the text color or bg color. this works fine but after using $generateHtmlFromNodes i get a html string that contains those styles perfect, I save that to my DB, on retrieving that and passing it through  $generateNodesFromDOM i lose all that extra styling 

Lexical version:

## Steps To Reproduce

1. use this function to set the initial editor state
```javascript
const getEditorState = (editor: LexicalEditor) => {
    editor.update(() => {
      const parser = new DOMParser();
      const dom = parser.parseFromString("<span data-lexical-text="true" style="color: rgb(208, 2, 27);">typing</span>", 'text/html');

      // Once you have the DOM instance it's easy to generate LexicalNodes.
      const nodes = $generateNodesFromDOM(editor, dom);

      // Select the root
      $getRoot().select();

      // Insert them at a selection.
      $insertNodes(nodes);
    });
  };

return (
  <LexicalComposer
      initialConfig={{ ...editorConfig, editorState: getEditorState }}
    >
...

```
2. you will see that the editor contains no styles

Link to code example:

https://codesandbox.io/s/old-cloud-wxqlmr?file=/src/Editor.js:1655-1695

## The current behavior 

Styles get removed

## The expected behavior

Styled should stay.

**Comment by ivailop7** [comment]
Please refer to the documentation on handling extended HTML styling in the Serialize/Deserialize HTML section.

**Comment by rusicsemenov** [comment]
@The-Code-Monkey Hi, you should  override textNode https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling it will fix import with styles. 
![image](https://github.com/facebook/lexical/assets/20163858/b06dcc64-c6de-415d-994b-3adafea416da)
This code will add additional styles to the node

**Comment by The-Code-Monkey** [comment]
Cheers, yeah got it added it to my wrapper.

**Comment by mohamm3d-dev1** [comment]
@ivailop7  Why $generateNodesFromDOM removes inline styles and is there any solution to add inline style without overriding TextNode and I store data from editor as html by $generateHtmlFromNodes
