### ISSUE TITLE
Bug: Fix tuple typo

### ISSUE THREAD

**Issue by Jufrench** [facebook/lexical#5228]
## Steps To Reproduce

1. Navigate to https://lexical.dev/docs/api/modules/lexical_text & find the following section.
<img width="779" alt="image" src="https://github.com/facebook/lexical/assets/29068597/d74ee721-8744-4163-a79c-6aa5172e34b5">

## The current behavior
The word "touple" is misspelled. 
## The expected behavior
It should be spelled "tuple".

**Comment by Sparky338** [comment]
PR #5229
