### ISSUE TITLE
Bug: Double-click selection in Firefox selects more nodes than actually selected

### ISSUE THREAD

**Issue by AlessioGr** [facebook/lexical#5234]
https://github.com/facebook/lexical/assets/70709113/3b95f9ad-8bc5-417a-9399-d947bb094d75

In the video, you can see Firefox on the left and a Chromium-based browser on the right.

When **double-clicking the bold text node**, you can see in the TreeView that on Firefox, it also **marks the previous text node ("Some") as selected even though it is not**.

On Chrome, it works as expected and only marks the bold text as selected.

**Comment by thegreatercurve** [comment]
There's not really a lot we can do about this within Lexical as we just wrap the native DOM selection APIs with some convenience method.

I am able to replicate the bug in Firefox using just a standard `contenteditable`. 

<img width="1717" alt="image" src="https://github.com/facebook/lexical/assets/7748470/2681ab13-03f3-4176-8be8-f392f6da91ed">

I'd recommend logging a bug here with Firefox: https://bugzilla.mozilla.org/buglist.cgi?quicksearch=selection+contenteditable
