### ISSUE TITLE
Bug: Unable to select the text typed if it initiates the Mention plugin

### ISSUE THREAD

**Issue by KarthikRaju391** [facebook/lexical#5235]
Lexical version:

## Steps To Reproduce

1. Try typing `Perfect` in a blank editor
2. Mention Plugin will be initiated for a fraction of a second
3. Try double clicking on the typed word

https://github.com/facebook/lexical/assets/67912316/4c1f6ca9-8044-43d0-bef7-a63622d4c6cc

**Comment by thegreatercurve** [comment]
@KarthikRaju391 Is this the playground editor? If not, I'm not sure if there's much we can do. It looks more like an issue with the underlying Regex.

**Comment by KarthikRaju391** [comment]
@thegreatercurve, This is the custom editor that I have been working on. But, I have just been using the mention plugin as is from the playground.
