### ISSUE TITLE
copy a link text from the rich text and paste it

### ISSUE THREAD

**Issue by RETnEee** [facebook/lexical#5240]
### Discussed in https://github.com/facebook/lexical/discussions/5239

<div type='discussions-op-text'>

<sup>Originally posted by **RETnEee** November 17, 2023</sup>
when I was copied a link text from the rich text and pasted it, the view tree was not correct, but I can not reproduce it in playground. it's a little confusing to me
![image](https://github.com/facebook/lexical/assets/21081209/9a7af677-a5a5-449e-8b99-ca30e5345b19)

but playground seems not have this problem, anyone know what happened?
![image](https://github.com/facebook/lexical/assets/21081209/946c75cb-3959-4000-92c6-f57ee42ecffb)
</div>

**Comment by moy2010** [comment]
Please don't open issues if you cannot reproduce them.
