### ISSUE TITLE
Bug: Issue deleting consecutive BlockWithAlignableContents.

### ISSUE THREAD

**Issue by ssoju** [facebook/lexical#5249]
Lexical version: 0.12.2

## Steps To Reproduce

1. Insert "Horizontal Rule" consecutively without blank paragraphs
2. Enter Backspace twice in a row at the cursor position after the last hr.

https://github.com/facebook/lexical/assets/138416737/c8018c8c-f703-4b0c-9153-b7ea4219f163

Link to code example: https://playground.lexical.dev/

## The current behavior
There is an issue where deleting with backspace when BlockWithAlignableContents is contiguous deletes the previous node along with it.

## The expected behavior
Only the selected nodes should be deleted.

**Comment by disalechinmay** [comment]
@ssoju - Which browser are you using? I tried on Chrome Version 119.0.6045.160 (Official Build) (64-bit) and Firefox Version 120.0 (64-bit) both on Windows 11. It seems to work fine on my end.

**Comment by ssoju** [comment]
@disalechinmay My chrome is "119.0.6045.159". It also happens on Canary, which is "121.0.6144.0".  Firefox is "120.0".
If you watch the video, it still happens.

https://github.com/facebook/lexical/assets/11021464/4719916c-4787-419f-a4b1-03c2adf78f33

**Comment by ivailop7** [comment]
This is interesting, will investigate.
