### ISSUE TITLE
Bug: Link transformer not handling target property?

### ISSUE THREAD

**Issue by cmarouan** [facebook/lexical#5257]
Lexical version: latest

## Steps To Reproduce

1. send target when dispatching `TOGGLE_LINK_COMMAND`
![image](https://github.com/facebook/lexical/assets/44669758/b5ee668f-73ff-4bd9-9a42-76465ed8f2a3)

2. Nothing related to the target exists in the generated markdown or in the transformer (on the codebase).

generated markdown:
`[link](https://github.com/facebook/lexical)`

codebase:
https://github.com/facebook/lexical/blob/ede6500447068c86b18188597909b1b8b54da5ca/packages/lexical-markdown/src/MarkdownTransformers.ts#L340

am I missing something here?

**Comment by GermanJablo** [comment]
Can you explain the issue in more detail?
What is the output you expect?

**Comment by cmarouan** [comment]
@GermanJablo I 100% agree. It's possible using HTML or by updating `document.links`, but at that time, I was thinking we could update the Link transformer and support it. I already did that on a project since I wanted to use a Link transformer, even though it's possible in other ways. Here's an example of the transformer I used:

```
const LINK: TextMatchTransformer = {
  dependencies: [LinkNode],
  export: (node, _, exportFormat) => {
    if (!isLinkNode(node)) {
      return null;
    }
    const target = node.getTarget();
    const title = node.getTitle();
    const rel = node.getRel();
    const linkContent = `[${node.getTextContent()}](${node.getURL()}${` "${title ?? ''}"`}${` "${target ?? ''}"`}${` "${
      rel ?? ''
    }"`})`;
    const firstChild = node.getFirstChild();

    if (node.getChildrenSize() === 1 && isTextNode(firstChild)) {
      return exportFormat(firstChild, linkContent);
    } else {
      return linkContent;
    }
  },
  importRegExp:
    /(?:\[([^[]+)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))/,
  regExp:
    /(?:\[([^[]+)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))$/,
  replace: (textNode, match) => {
    const [, linkText, linkUrl, linkTitle, linkTarget, linkRel] = match;

    // since we need all the links to be opened on a new tab by default
    let attributes: LinkAttributes = { target: linkTarget ?? '_blank' };

    if (linkTitle) {
      attributes = { ...attributes, title: linkTitle };
    }

    if (linkRel) {
      attributes = { ...attributes, rel: linkRel };
    }

    const linkNode = createLinkNode(linkUrl, attributes);
    const linkTextNode = createTextNode(linkText);
    linkTextNode.setFormat(textNode.getFormat());
    linkNode.append(linkTextNode);
    textNode.replace(linkNode);
  },
  trigger: ')',
  type: 'text-match'
};
```

Anyway, I see the reasons behind this. But since I'm working using Lexical almost all the time, I just wanted to do it the Lexical way. <3
