### ISSUE TITLE
Bug: unable to delete the first character on android chrome

### ISSUE THREAD

**Issue by kirandash** [facebook/lexical#5274]
when there is one character left at any line it wont delete it and it will jump to the beginning of line without deleting the character

Lexical version: 0.12.4

## Evidence

https://github-production-user-asset-6210df.s3.amazonaws.com/19841175/276697867-50d93d4c-f6db-474a-bfb0-b63280e587da.mp4

**Comment by kirandash** [comment]
I will be creating a PR for this based on my solution shared here: https://github.com/facebook/lexical/issues/4941#issuecomment-1818305883

**Comment by bnol** [comment]
+1

**Comment by rohini21** [comment]
@kirandash @acywatson Thanks for this fix. When will this be published?

**Comment by kirandash** [comment]
> @kirandash @acywatson Thanks for this fix. When will this be published?

@rohini21 Not sure when it will be released next. In the meantime, you can use a patch ex: patch-package for npm or pnpm patch etc to patch Lexical.dev.js and Lexical.prod.js files on your project.

How to generate the Lexical.dev.js and Lexical.prod.js file with the fix?
Go to LexicalEvent.ts file: add the fix code and run `npm run build-release`. Once the build is ready, use those files from dist folder on your project.

Hope that helps.

**Comment by kirandash** [comment]
@rohini21 This is now merged to main and available in release version `v0.12.5`
