### ISSUE TITLE
Bug: `@lexical/*` packages contain misleading type definition files

### ISSUE THREAD

**Issue by thorn0** [facebook/lexical#5285]
Lexical version: 0.12.4

## Steps To Reproduce

1. Install `@lexical/selection`
2. Try importing `$getAncestor`. IDE will suggest importing it from `@lexical/selection/range-selection` as the package contains the `range-selection.d.ts` file that contains `export declare function $getAncestor`. However, there is no corresponding JS file. Even though the code typechecks, the bundler can't find such a module.

Same thing with other Lexical packages. A lot of `.d.ts` files without corresponding `.js`.

This is annoying as often real and "phantom" modules export functions with the same name, so IDE autoimport imports wrong things. E.g. `$findMatchingParent` is imported by `@lexical/utils`, but VS Code tends to autoimport it from `lexical/LexicalUtils`.

## The expected behavior

Either don't include these `.d.ts` files in packages or include corresponding JS files.

**Comment by CanRau** [comment]
I think I notices the same and also getting

```
'LexicalNode' cannot be used as a value because it was exported using 'export type'.ts(1362)
```

when trying to create a custom Node based on it, importing it like so `import { LexicalNode } from "lexical";`, then I found this [Remove type from export in d.ts files](https://github.com/auth0/nextjs-auth0/pull/1037) and I think this would be the fix.

This is possibly not exactly the same issue as you're describing @thorn0 though I wanted to give yours more visibility as I'm facing it as well and pointing out that `type` might be better left off of exports

**Comment by etrepum** [comment]
I don't think this happens anymore since conditional exports are used (since around 0.15.0) so the IDE should know exactly which package imports are allowed.

LexicalNode is intentionally not exported as a value, think of it as an abstract interface and not a class. This interface is implemented by exactly four classes: ElementNode, DecoratorNode, LineBreakNode and TextNode which are all exposed as values.

**Comment by EmilianoMorghen** [comment]
This:
> This is annoying as often real and "phantom" modules export functions with the same name, so IDE autoimport imports wrong things. E.g. $findMatchingParent is imported by @lexical/utils, but VS Code tends to autoimport it from lexical/LexicalUtils.

Is still happening with:
- `"@lexical/react": "^0.32.0"`
- `"@lexical/utils": "^0.32.1"`
- `"lexical": "^0.32.0"`
