### ISSUE TITLE
Bug: Long text tokens cause the editor to collapse

### ISSUE THREAD

**Issue by moy2010** [facebook/lexical#5287]
Long text tokens can bring down the editor. This is easy to reproduce in the playground, just paste this: SomeVeryLongTextStartsToLagALot. Or you can type it and you'll see how performance starts degrading until the editor becomes unresponsive.

I'm suspicious of Regex-related plugins such as `@lexical/markdown` and `AutoLinkPlugin`, but haven't digged deeper. So far I've only narrowed the issue down to the smallest reproducible example after a few hours of debugging.

Lexical version: Tested in both 0.12.4 and 0.12.2. The issue is present in both versions.

It's also worth mentioning that I discovered the issue after opening a text that I created in june this year, so whatever is causing this issue should be part of a very recent version.

## Steps To Reproduce

1. Type a very long text token (i.e. with no white spaces)
2.Profit

## The current behavior

The editor becomes unresponsive.

## The expected behavior

The editor should handle long text tokens.

**Comment by ivailop7** [comment]
I replicate the slowness. It's either the insertNodes rewrite or indeed a regex somewhere :/ it's indeed a commit in the past 3 months.

**Comment by moy2010** [comment]
@ivailop7, I'm playing with the playground right now and I can reproduce it in the plain-text playground.

**Comment by ivailop7** [comment]
Can you try the preview in this PR https://github.com/facebook/lexical/pull/5201 , I think this PR restores the performance back.

**Comment by moy2010** [comment]
That PR indeed fixed the slowness. Let's wait until it gets merged then :smiley: .
