### ISSUE TITLE
Bug: strange logic in getSelectedNode in playground

### ISSUE THREAD

**Issue by thorn0** [facebook/lexical#5294]
Lexical version: 0.12.4

## Steps To Reproduce

Open the playground. Insert this content:

----

foo

barbarbarbarbarbarbar [link](https://example.com/).

----

Start selecting backwards from somewhere in the middle of the link. See the link editor is shown as `getSelectedNode` returns the link node. Keep expanding the selection backwards. When the focus point leaves the link, the link editor disappears. However, when you move the focus point up to the end of the previous paragraph, the link editor will unexpectedly reappear. This happens because `getSelectedNode` uses `$isAtNodeEnd` in its implementation, and when this function returns true, that means "we are at the end of _any_ node". Looks like a bug, but I don't know what a solution could look like as I'm struggling to understand the original intent behind this use of `$isAtNodeEnd`.

**Comment by etrepum** [comment]
I can't reproduce this
