### ISSUE TITLE
Bug: Multiple paragraphs to code node causes crash error

### ISSUE THREAD

**Issue by mok419** [facebook/lexical#5297]
Lexical version: 0.12.4

## Steps To Reproduce

1. Open [Lexical playground ](https://playground.lexical.dev)
2.  Write 'Hi' enter, 'Hi' enter, 'Hi' enter
3. Highlight the 3 lines and choose to turn it into a code block.
4. Error Expected node x to have a parent
[Error code # 66 on lexical](https://lexical.dev/docs/error?code=66&v=49)
Expected node 52 to have a parent

<img width="621" alt="image" src="https://github.com/facebook/lexical/assets/135124328/752766b8-2161-4916-90bb-9c493440bcc9">

This shows where the error originates from the code: (in the toolbar plugin)
<img width="756" alt="image" src="https://github.com/facebook/lexical/assets/135124328/8e5d0aac-6a82-4e3a-b84a-a77a645b1a79">

Here is my version, showing node 5 as the culprit. However we can see from getNodes() that node with key 5 has a parent of root.
<img width="760" alt="image" src="https://github.com/facebook/lexical/assets/135124328/203543d9-5ac1-4d80-bdf1-e21323392224">

Interestingly, if I add a line break after the 3rd hi and and highlight the 4 lines, the error doesn't occur?! but it doesn't convert the content, instead it adds repeated text in a new code block.
<img width="940" alt="image" src="https://github.com/facebook/lexical/assets/135124328/f10146dc-5bab-40ec-b18a-4c961f425537">

**Comment by mok419** [comment]
Ok I found a fix: but I found another bug now haha.

Focusing on this problem, I fixed it by adding empty text to the selection:
<img width="746" alt="image" src="https://github.com/facebook/lexical/assets/135124328/7f065749-da66-4e22-8fb8-0d497de085d6">


A lil hacky, but now it works as expected with no errors:
<img width="456" alt="image" src="https://github.com/facebook/lexical/assets/135124328/7e0ff6a7-0308-4386-b0ee-227e00403832">

**Comment by mok419** [comment]
new issue that technically isnt an issue but lets resolve for fun:

Here is where I am at - so now I have my code block, which is now a single block, but we started as 3 seperate paragraph nodes.
<img width="268" alt="image" src="https://github.com/facebook/lexical/assets/135124328/ce78179e-9208-4823-bcbf-b48fe134ab9f">

If I now convert to any type of list, only the first item will be considered a list item, the next two lines are part of the first list item - so we now need to convert line breaks to seperate nodes before conversion.
<img width="252" alt="image" src="https://github.com/facebook/lexical/assets/135124328/59ff9236-545f-46ec-92e4-fcf88e91a47a">

changing to a heading node also shows this pretty nicely
<img width="229" alt="image" src="https://github.com/facebook/lexical/assets/135124328/08c914a8-6f3f-4118-93b1-ffc3132e9ea3">

will try to fix now, although its not technically an issue as who is going to convert between code and list, but for someone playing about it means a lot. Well to me it means a lot haha!

**Comment by mok419** [comment]
Ok the simplest solution I can think of is to getNodes from the selection and loop through each node checking for a code-highlight node, and replace it with a paragraph node and add its text to it. then carry out the block logic. 
I could encapsulate this in a function and check if the blockType === 'code' and run the function for every block change.

But this is highly inefficient, and complicates things further as I then need to store the new temporary selection. I would rather just allow the user to fix things if they need to! 

We had some fun anyway, thanks lexical!

**Comment by etrepum** [comment]
Selection is the roughest part of Lexical in my experience too, something like this will probably work and be more efficient:

```typescript
            const textContent = selection.getTextContent();
            selection.removeText();
            const codeNode = $createCodeNode();
            selection.insertNodes([codeNode]);
            selection.insertRawText(textContent);
```
