### ISSUE TITLE
Supporting Grammarly and Google Translate

### ISSUE THREAD

**Issue by trueadm** [facebook/lexical#53]
DraftJS doesn't work with either because of many reasons that either: conflict with React's rendering, or just don't support Draft's internal model. I feel that we should do better here.

These browser plugins are not only heavily used by a large majority of the Internet, they also provide a much better experience for users that depend on these for accessibility reasons (which includes plugins other than these two). 

I feel like we should spent some effort on investigating and possibly implementing support for these browser plugins. We can obviously disable them (you can use DOM attributes and classes to do so) but I feel like we should at least explore this space.

**Comment by li-yechao** [comment]
> Grammarly support added in #54.

How about google translate?

**Comment by trueadm** [comment]
@li-yechao Does Google Translate not work at all with your Lexical content? Last time I checked, it worked fine for me.

**Comment by li-yechao** [comment]
> @li-yechao Does Google Translate not work at all with your Lexical content? Last time I checked, it worked fine for me.

It not worked for me, example page: https://www.robertmao.com/blog/post/yvstwPLWHCsNz-XN

What am I doing wrong here?

**Comment by trueadm** [comment]
Ah, it's because of Lexical's DOM mutation observers reverting the content back. I wonder if we should relax the DOM mutation listeners in non-editable mode.

**Comment by trueadm** [comment]
@li-yechao Can you open a separate issue for this please? We can track it and maybe come up with a solution.

**Comment by li-yechao** [comment]
> @li-yechao Can you open a separate issue for this please? We can track it and maybe come up with a solution.

#3496
