### ISSUE TITLE
Bug: <del> tag not parsed correctly when converting from html to the Lexical editor state

### ISSUE THREAD

**Issue by KulovacNedim** [facebook/lexical#5301]
Lexical version: 0.12.4

## Steps To Reproduce

Code snippet:
```
const htmlString = '<p>Let's test <strong>bold</strong>, <em>italic</em>, <del>strikethrough</del> text.</p>'

export function RichTextEditor({
    initialEditorStateHtml,
}: EditorProps) {
    const editorConfig = {
        ...DEFAULT_EDITOR_CONFIG,
        theme: editorTheme,
        editable: !readonly,
        editorState: (editor: LexicalEditor) => {
            const parser = new DOMParser();
            const dom = parser.parseFromString(
                htmlString, 'text/html',
            );
            const nodes = $generateNodesFromDOM(editor, dom);
            const rootNode = $getRoot();
            for (const node of nodes) {
                try {
                    rootNode.append(node);
                } catch (err) {
                    continue;
                }
            }
        },
    };
    return (
        <LexicalComposer initialConfig={editorConfig}>
         ....
        </LexicalComposer>
    );
}
```

## The current behavior
The snippet above results in:
Let's test **bold**, *italic*, strikethrough text.

## The expected behavior
It should result in:
Let's test **bold**, *italic*, ~strikethrough~ text.

**Comment by KulovacNedim** [comment]
Okay, so I sniffed the codebase a bit and found replacing `<pre>` with `<s>` tag works fine. I'll leave the PR open in case you want to support `<pre>` tag as well. Otherwise, you can close it at any time 🤞

**Comment by moy2010** [comment]
There are no `<pre>` tags in your code snippet

**Comment by KulovacNedim** [comment]
> There are no `\<pre\>` tags in your code snippet

Sorry man, what I meant was the `<del>` tag. I'll update my comment above 👍

**Comment by acywatson** [comment]
Interesting - I actually didn't know about this element. You can also use HTML overrides to support any element you want, so I don't think we need to make any changes right now.
