### ISSUE TITLE
Feature: Export more functions from Lexical core package

### ISSUE THREAD

**Issue by yf-yang** [facebook/lexical#5333]
This feature request comes from https://github.com/facebook/lexical/issues/5313

# Description
1. export all exports of LexicalUtils.ts to lexical's users
2. export `getActiveEditor` and `getActiveEditorStates` from LexicalUpdate.ts

# Motivation
1. Utility functions benefit both internal library maintainers and library users. For example, `$getNodeByKeyOrThrow`, as a variant of `$getNodeByKey` with type guard, is useful for TypeScript users. Currently I have to copy paste the source again somewhere because it is not exported from the core package. More annoyingly, those functions appear in auto completion, but they are actually not accessible.
2. `getActiveEditor` and `getActiveEditorStates` are not commonly used, but they are pretty useful when trying to access the editor instance within a `LexicalNode`'s scope, especially in `importJSON` method. For my personal use case, that would be useful to map a node to editor-specific contextual data. That would also be useful when using Lexical along with other state management libraries since Lexical may not be the only one. Currently, there is no way to backlink a node to its containing editor.

# Considerations
Some considerations specifically related to 2:
- Export `getActiveEditorStates` may not be so useful since `$getRoot` is also available, it is enough to access the whole tree from a node.
- I am not sure by design `importJSON` should be treated as a pure function. The use case is that I do need to interact with external stuff when moving nodes between nested editors (which needs serialization and deserialization), but Lexical does not offer an api to deal with side effects.

**Comment by acywatson** [comment]
I don't have a problem with this - I opened a PR to do it a long time ago, but @zurfyx had some light reservations:

https://github.com/facebook/lexical/pull/4325
