### ISSUE TITLE
Feature Request/Question: Is It Possible to Use Lexical as a VSCode Plugin? 

### ISSUE THREAD

**Issue by disbolog** [facebook/lexical#5337]
Hi,

I am wondering - would it be hard to package Lexical as a plugin for VSCode, if that's not yet done?

I believe, it would be very beneficial for the community, should such a plugin exist, cause it would supercharge the editing on VSCode.

Thank you all for the great work.

**Comment by GermanJablo** [comment]
I have also thought something like that, and maybe in the future I will do it.

However, I think it is outside the scope of this project.

**Comment by etrepum** [comment]
There are vscode extensions that use lexical, such as https://marketplace.visualstudio.com/items?itemName=dineug.textflow-editor-vscode which is open source so you can see how they did it https://github.com/dineug/textflow
