### ISSUE TITLE
Bug: symbols Â are displayed when typing text.

### ISSUE THREAD

**Issue by edshkliaruk** [facebook/lexical#5339]
With each entered symbol, symbols Â are displayed to the right of the cursor, and for each symbol, there are 3 Â characters.

Lexical version: 
It is reproducible with 0.8.1 and 0.12.4 versions.

Device:
Samsung Galaxy A5 (2017) (Android version - 8.0.0)

![photo_2023-12-06_13-30-23](https://github.com/facebook/lexical/assets/125352863/7c50ef03-3ac0-452f-88d6-b1b9b7532fc8)

**Comment by edshkliaruk** [comment]
One more info, it is reproducible for 
Samsung S21 5G
Android version, 13

**Comment by fantactuka** [comment]
Can you reproduce it on the [playground](https://playground.lexical.dev/)?

**Comment by edshkliaruk** [comment]
@fantactuka I should implement this example into my application. I am using Capacitor, where I have lexical library.
So, but I checked your link in chrome browser of my device and I could not reproduce this issue.

**Comment by nikolay-rodzhev** [comment]
> Can you reproduce it on the [playground](https://playground.lexical.dev/)?
<img width="292" alt="Screenshot 2024-02-02 at 16 36 57" src="https://github.com/facebook/lexical/assets/124592633/d68ae4b4-c3a3-487e-8b9d-a283a24e5054">
<img width="252" alt="Screenshot 2024-02-02 at 16 51 03" src="https://github.com/facebook/lexical/assets/124592633/e7e42e32-c38e-4d70-8fe9-f793646b51fc">


The reported issue is not reproduced in browser environment(lexical playground for example), it is only reproduced on native android level. Important note that it is not on every android device. I can reproduce it on Android Studio emulator. The emulated device is: Google Pixel 3a with Android version 14.0. I provide a screenshot of what is displayed in the tree view, there are also strange characters in it.
