### ISSUE TITLE
Bug: Broken Command Type in the Debug View in the Playground

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#5344]
At some point we've broken the TreeView, showing UNKNOWN for all dispatched commands.
Will look into fixing this.

![image](https://github.com/facebook/lexical/assets/7893468/4b0740ee-ebb0-4f26-9d01-e31528dfcec1)

**Comment by yf-yang** [comment]
I think it is a desired behavior. When self hosting the playground, the type could be correctly shown.

https://github.com/facebook/lexical/blob/2c825792956f219f97da88c455d53855ddb1d9f5/packages/lexical/src/LexicalCommands.ts#L13-L15

**Comment by ivailop7** [comment]
@acywatson @zurfyx @fantactuka do you know why this was made to work only in DEV ? This seems very strange to me.

**Comment by ivailop7** [comment]
Not sure the increased bundle size is worth it, even though it would be nice to see the events in the playground for easier reproduction of issues. Closing.
