### ISSUE TITLE
Bug: Import of ToolbarPlugin, HeadingNode and QuoteNode

### ISSUE THREAD

**Issue by erikmartinessanches** [facebook/lexical#5361]
Lexical version: ^0.12.5

## Steps To Reproduce

1. I mainly followed the example provided[ here, see Editor.js](https://codesandbox.io/p/sandbox/lexical-plain-text-example-g932e?file=%2Fsrc%2Findex.js)
2. I would like to make use of HeadingNode and ToolbarPlugin, are these exposed from your package?

Link to code example: [See index.js](https://stackblitz.com/edit/typescript-ghhdva?file=index.ts)

## The current behavior
Unable to import  HeadingNode and QuoteNode
`'@lexical/rich-text' should be listed in the project's dependencies. Run 'npm i -S @lexical/rich-text' to add it`

**Comment by moy2010** [comment]
Don't create issues for questions around development. Create a topic under the `discussions` section or use the Discord channel for this.

**Comment by ivailop7** [comment]
Please use the Discord chat for such discussions. The toolbar you can copy paste from the Playground. The heading node is exposed by the rich text package as mentioned in the error.
