### ISSUE TITLE
Bug: Converting to markdown breaks the editor with certain contents

### ISSUE THREAD

**Issue by PEsteves8** [facebook/lexical#5370]
Playing around with markdown conversion, I noticed that sometimes, for certain content, the conversion fails and breaks the editor entirely. 

Eg copying the contents of this [page](https://www.semrush.com/blog/free-seo-tools/) to the playground and trying to convert to markdown breaks the editor. Alternatively you can import this lexical state into the playground (I tried to attach a .lexical file but github doesn't let me): 
```
{"editorState":{"root":{"children":[{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"You can unlock much more keyword data in ","type":"text","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Keyword Gap","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"link","version":1,"rel":null,"target":null,"title":null,"url":"https://www.semrush.com/analytics/keywordgap/"}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"l","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"link","version":1,"rel":null,"target":null,"title":null,"url":"https://www.semrush.com/analytics/keywordgap/"}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Keyword Manager","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1},{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Keyword Manager","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"link","version":1,"rel":null,"target":null,"title":null,"url":"https://www.semrush.com/analytics/keywordmanager/"}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}},"lastSaved":1702327856275,"source":"Playground","version":"0.12.5"}
```

I think there might be multiple situations in which something like this occurs, since sometimes deleting random characters seems to fix it.

Locally it returns the error: 
```
Uncaught Error: One or more transforms are endlessly triggering additional transforms. May have encountered infinite recursion caused by transforms that have their preconditions too lose and/or conflict with each other.
```

I tried figuring out which node or pattern was causing this, links, whitespace, whatever, but failed.

Lexical version: 0.12.5

Note: I'm not related to the blog page itself, it's just a sample in which this error occurs.

## Steps To Reproduce

1. Paste the contents of  [page](https://www.semrush.com/blog/free-seo-tools/) into the lexical playground (or import a .lexical file with the trimmed version of the contents above)
2. Try to convert it to markdown
3. The editor will break

**Comment by 2wheeh** [comment]
Hi! I guess it is similar to this one i just opened: #5403
