### ISSUE TITLE
Bug: AutoLinkPlugin triggers breakdown with certain input

### ISSUE THREAD

**Issue by 2wheeh** [facebook/lexical#5403]
Lexical version: Latest (0.12.5)

## Steps To Reproduce

1. go to the Playground
2. make editor empty
3. copy and paste this snippet on the editor:
```
123456789012345612345678901234567[link1](https://lexica1.dev/)[link2](https://lexica2.dev/)12345678901234567[link3](https://lexica3.dev/) 
```

Link to code example: can reproduce it on the Playground.

## The current behavior

https://github.com/facebook/lexical/assets/40269597/5202e79b-182c-4e79-be86-5687ddab39c2

### TL;DR
- **`text.substring` trims the left-sided invalid match text already, yet we still use `invalidMatchEnd` to adjust offset.**
- **This is somewhat duplicative.**
------------------
1. `AutoLinkPlugin` registers a listener in `useAutoLink`:
https://github.com/facebook/lexical/blob/520af1d29a0dd01194592429b487f45bbb8caa42/packages/lexical-react/src/LexicalAutoLinkPlugin.ts#L435
2. The listener calls `handleLinkCreation` and it calls `isContentAroundIsValid`. This function checks whether the characters at certain positions are separators by regex matching:
https://github.com/facebook/lexical/blob/520af1d29a0dd01194592429b487f45bbb8caa42/packages/lexical-react/src/LexicalAutoLinkPlugin.ts#L271
3. The current issue stems from passing an incorrect index here, specifically due to `invalidMatchEnd`.
5. The issue happens when this tells an invalid one as a valid one mistakenly.
    For example: when the match is `https://lexica2.dev/)`
    <img width="568" alt="스크린샷 2023-12-19 오전 4 27 08" src="https://github.com/facebook/lexical/assets/40269597/45c91841-34ff-42df-ad4a-3d5b40ac3377">

7.  It proceeds the logic for the valid around in `createAutoLinkNode`
    - `currentNode` gets split https://github.com/facebook/lexical/blob/520af1d29a0dd01194592429b487f45bbb8caa42/packages/lexical-react/src/LexicalAutoLinkPlugin.ts#L193
    - and merged again    https://github.com/facebook/lexical/blob/520af1d29a0dd01194592429b487f45bbb8caa42/packages/lexical/src/LexicalNormalization.ts#L81
8. This makes it repeat everything from the start endlessly.
9. The way I see it:
    - **`text.substring` trims the left-sided invalid match text already, yet we still use `invalidMatchEnd` to adjust offset.**
    - **This is somewhat duplicative.**
    
## The expected behavior

AutoLinkPlugin doesn't break the app.

## Proposed fix

~Let `text.substring` trim the invalid text and remove `invalidMatchEnd`.~
--> **this spawns some other bugs** 

Pass the constant initial text to `isContentAroundIsValid` instead of text which is being trimmed

**Comment by 2wheeh** [comment]
It seems`AutoLinkPlugin` is changing a lot (#4430), which might resolve this one ...🤔

**Comment by moy2010** [comment]
Thanks for pointing out to that PR. I actually faced the same issue when pasting a URL within parentheses.

**Comment by 2wheeh** [comment]
This wrong indexing triggers this one too:
When first match is invalid and the second match is valid, it fails to tell the second one as valid in some cases.


https://github.com/facebook/lexical/assets/40269597/a6edc757-401d-4120-a21f-5ddc84c7b225

**Comment by 2wheeh** [comment]
It happens in facebook as well:
``` 
1234567890123456123456789012345678901234 https://lexica1.dev/ 1234567 https://lexica2.dev/ 123456789012345678901234 https://lexica3.dev/  
```

https://github.com/facebook/lexical/assets/40269597/a3ffef83-c4eb-4c88-a4f9-a1797aae30a0

I guess facebook has different implementation of AutoLingPlugin (probably the matcher or those regex things) but still breaks by same cause.
