### ISSUE TITLE
Bug: ts not exported for @lexical/table 

### ISSUE THREAD

**Issue by zhihengGet** [facebook/lexical#5411]
Lexical version: latest

## Steps To Reproduce
import {$isGridSelection, GridSelection} from '@lexical/table';

`$isGridSelection, GridSelection `are not exported from @lexical/table, vscode shows module not found

Link to code example:

**Comment by moy2010** [comment]
Have you installed the `@lexical/table` package? If so, have you restarted VSCode?

**Comment by thorn0** [comment]
A version of `@lexical/table` with these exports hasn't been released yet.

**Comment by zhihengGet** [comment]
i think @lexical/table just need to create a release for these types; It is just typing issue :)

 im on 0.12.5 @lexical/tables

**Comment by guotie** [comment]
same problem

**Comment by khanakia** [comment]
I am having the same issue and I am using the latest version `"0.12.5"`

**Comment by ivailop7** [comment]
Could someone confirm, this is fixed as of 0.12.6 ?

**Comment by guotie** [comment]
seems ok

**Comment by CrisAlejo26** [comment]
I currently have these versions in my project: 

```
"@lexical/react": "^0.17.1", 
"@lexical/selection": "^0.18.0", 
```

`$isGridSelection, GridSelection` They are not exported from @lexical/table, vscode shows module not found
