### ISSUE TITLE
Bug:  Duplicate Text Node Creation in $generateNodesFromDOM Function

### ISSUE THREAD

**Issue by MarNeumann** [facebook/lexical#5430]
The `$generateNodesFromDOM` function creates Lexical text nodes with duplicate content for a single text segment in the HTML. For instance, with the HTML string `'<p class="editor-paragraph" dir="ltr"><span style="white-space: pre-wrap;">Next test</span></p>'`, the output includes one text node with the content "Next testNext test".

Lexical version:

```json
    "dependencies": {
        "@lexical/react": "^0.12.5",
        "lexical": "^0.12.5",
        "next": "14.0.4",
        "react": "^18",
        "react-dom": "^18"
    }
```

## Steps To Reproduce

1. Clone repository/Open codesandbox
2. `npm run dev`

Link to code example:

[Codesandbox](https://codesandbox.io/s/github/MarNeumann/lexical-issue)
[Github Repository](https://github.com/MarNeumann/lexical-issue)

## The expected behavior

The `should interpret the HTML string correctly and generate a correct Lexical node for each distinct text segment in the HTML.

**Comment by 2wheeh** [comment]
It seems more like react issue in dev mode.

**Comment by MarNeumann** [comment]
I edited the `next.config.js` as follows:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
    reactStrictMode: true,
};

module.exports = nextConfig;
```

unfortunately this didn't resolve the issue.

**Comment by MarNeumann** [comment]
you're the man 🙏
