### ISSUE TITLE
Feature: support text formats out of the box

### ISSUE THREAD

**Issue by Rusinas** [facebook/lexical#5440]
Lexical version: 0.12.5

## Steps To Reproduce

1. Type something into editor
2. Try to apply bold by pressing ctrl+B
3. Text will become bold
4. Apply italic to the same selection by pressing ctrl+I
5. Nothing will be changed
6. Press ctrl+B again
7. Bold will be removed and the italic will be "revealed"

Link to code example: https://github.com/Rusinas/lexical-rich-text-bug

## The current behavior
Only one modifier can be applied at a time

## The expected behavior
All the modifiers applied simultaneously 

I am pretty sure I did something wrong during the configuration though .__. Also, I am using Vue and am not sure if the problem is related to it. Didn't have time to try on vanilla setup

**Comment by ivailop7** [comment]
I'm not able to reproduce in https://playground.lexical.dev

**Comment by Rusinas** [comment]
> I'm not able to reproduce in https://playground.lexical.dev

Could you please try to run my code?

**Comment by Rusinas** [comment]
@ivailop7 here is live demo
https://stackblitz.com/~/github.com/Rusinas/lexical-rich-text-bug

**Comment by nsnl-coder** [comment]
```
<template>
  <div class="wrapper">
    <h1>Lexical bug</h1>
    <div id="editor" contenteditable="true" />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'

import {
    createEditor,
    type CreateEditorArgs,
} from 'lexical'

import {
    registerRichText,
} from '@lexical/rich-text'

const EMPTY_STATE = '{"root":{"children":[{"children":[],"direction":null,"format":"","indent":0,"type":"paragraph","version":1}],"direction":null,"format":"","indent":0,"type":"root","version":1}}'

const config: CreateEditorArgs = {
    editable: true,
    namespace: 'editorie',
    theme: {
        paragraph: 'editor-paragraph',
        text:{
          bold:"bold",
          italic:"italic"
        }
    },
    onError: console.error
};

const editor = createEditor(config)

const parsed_state = editor.parseEditorState(EMPTY_STATE)

editor.setEditorState(parsed_state)

registerRichText(editor)

onMounted(() => {
    editor.setRootElement(document.getElementById('editor'));
})
</script>

<style>
.wrapper {
  display: grid;
  gap: 20px;
}
#editor {
  width: 800px;
  background-color: #f7f7f7; 
}

.bold {
  font-weight: 700;
}

.italic{
   font-style: italic;
}
</style>

```

This works when i added class for text style.

**Comment by Rusinas** [comment]
@nsnl-coder LOL it now works indeed. Thank you so much!

**Comment by Rusinas** [comment]
But I am not going to close this issue for now. I guess it should work out of the box and I can remember it worked fine before without this.

**Comment by moy2010** [comment]
Please don't open issues when the issue is only in your code.

**Comment by acywatson** [comment]
> But I am not going to close this issue for now. I guess it should work out of the box and I can remember it worked fine before without this.

I guess we might be able to have some fallback styles to make this work out of the box. We'd have to inline them in the core. Probably not a high priority.

**Comment by Rusinas** [comment]
@moy2010 how could I know?

**Comment by moy2010** [comment]
> @moy2010 how could I know?

You have the playground at your disposal. It's always running on the latest version. That's why ivailop7 told you that the problem wasn't reproducible:

> I'm not able to reproduce in https://playground.lexical.dev
