### ISSUE TITLE
Bug: $generateNodesFromDOM does not correctly display colors and backgrounds.

### ISSUE THREAD

**Issue by SenaHuang** [facebook/lexical#5441]
Lexical version: 0.12.5

## Steps To Reproduce

1. add color and background color from playground
2. store the export string by using $generateHtmlFromNodes 
3. import the string by using $generateNodesFromDOM
4. check the playground

Code example to reproduce:
```javascript
editor.update(() => {
  const htmlString = $generateHtmlFromNodes(editor, null);
  console.log('$generateHtmlFromNodes(editor, null)', htmlString);

  const parser = new DOMParser();
  const dom = parser.parseFromString(htmlString, 'text/html');
  const nodes = $generateNodesFromDOM(editor, dom);
  if (onClear == null) {
    const root = $getRoot();
    const selection = $getSelection();
    const paragraph = $createParagraphNode();
    root.clear();
    root.append(paragraph);

    if (selection !== null) {
      paragraph.select();
    }
  } else {
    onClear();
  }
  $insertNodes(nodes);
});
```

## The current behavior

there is no color and background.

![截圖 2024-01-03 上午9 16 01](https://github.com/facebook/lexical/assets/58679278/b499535e-3565-432d-9c3e-3dab1b4dcb8c)

## The expected behavior

the setting should be displayed in the editor

![截圖 2024-01-03 上午9 03 45](https://github.com/facebook/lexical/assets/58679278/c289490a-81c1-444b-8a1d-90fa20139052)

**Comment by acywatson** [comment]
See Ivo's comment on the PR, plus all the other issues and closed PRs around this.
