### ISSUE TITLE
Bug: logic issue in LexicalSelection.ts file that make collapseAtStart never run

### ISSUE THREAD

**Issue by nsnl-coder** [facebook/lexical#5449]
Lexical version: 0.12.5

## Steps To Reproduce

1. add collapseAtStart function inside LayoutItemNode
2. delete at start of item node and collapseAtStart will not run.

I found the issue in LexicalSelection.ts file.

```typescript

  deleteCharacter(isBackward: boolean): void {
    const wasCollapsed = this.isCollapsed();

     // delete logic here but i removed it

    if (
      isBackward &&
      !wasCollapsed && // it should be wasCollapsed here
      this.isCollapsed() &&
      this.anchor.type === 'element' &&
      this.anchor.offset === 0
    ) {
      const anchorNode = this.anchor.getNode();
      if (
        anchorNode.isEmpty() &&
        $isRootNode(anchorNode.getParent()) &&
        anchorNode.getIndexWithinParent() === 0
      ) {
        anchorNode.collapseAtStart(this);
      }
    }
  }
```

After the deletion logic, the code is checking whether it should run collapsedAtStart function.
The collapsedAtStart function should run when wasCollapsed is true, not when it is false.

Also, collapseAtStart should be working for node which is not top level node.
I believe  $isRootNode(anchorNode.getParent()) check can be removed so i can easily handle event when **nested element node** collapsed at start.

## The current behavior
collapseAtStart function is not running.
## The expected behavior
collapseAtStart function should run.

**Comment by etrepum** [comment]
The use case of this is not very clear, and it sounds like it would not be backwards compatible. If you can more clearly explain what you're trying to do in a new issue, rather than focus on some specific implementation details, I think you would have a better chance of getting support for whatever it is you're trying to accomplish with this change.
