### ISSUE TITLE
Bug: LineBreakNode as Last Node breaks selection

### ISSUE THREAD

**Issue by KingSora** [facebook/lexical#5465]
Lexical version: 0.12.5

## Steps To Reproduce
When you have a paragraph which contains text and the last last node of that paragraph is a linebreak node it breaks your selection.

1. Insert a paragraph
2. Insert text with different linebreaks (no new paragraphs!)
3. make sure the last node is a linebreak node
4. Press Ctrl+A to select all the text and try to delete all the selected text with backspace
5. Only the first character is deleted intead of everything

I've created a short video to show the bevior on your playground:

https://github.com/facebook/lexical/assets/12936317/f0909896-e0d4-41c3-a49a-7579e6352844

**Comment by etrepum** [comment]
Can not reproduce this with current lexical
