### ISSUE TITLE
Uncaught TypeError: Class constructor DecoratorNode cannot be invoked without 'new'Bug: 

### ISSUE THREAD

**Issue by caizhisheng** [facebook/lexical#5488]
Lexical version:  0.12.6

## Steps To Reproduce

1.  select insert image and select type with 'File'
2.  click Confirm button after selected local image file

## The current behavior
chrome appear errors:   Uncaught TypeError: Class constructor DecoratorNode cannot be invoked without 'new'
![image](https://github.com/facebook/lexical/assets/13362401/be58c367-ea1f-4b3e-933a-dd63d139ca98)

why ?

**Comment by etrepum** [comment]
You’re compiling the javascript to a very old target, the output should have class syntax. You’ll need to fix your configuration of babel, webpack, typescript, or whatever else you are compiling with. ES2015 or something more modern would be a typical setting that should work.
