### ISSUE TITLE
Bug: The "Build to extend" on the homepage is outdated

### ISSUE THREAD

**Issue by ondrejsevcik** [facebook/lexical#5501]
The example "build to extend" on the [lexical homepage](https://lexical.dev/) shows how to extend the editor, but the method `addTransform` does not exist anymore. 

![CleanShot 2024-01-16 at 11 31 45@2x](https://github.com/facebook/lexical/assets/4136929/a9191942-8ec9-4c85-913f-5a81be800098)

**Comment by etrepum** [comment]
These examples come from the repo now, so they don't go out of date as easily
