### ISSUE TITLE
Bug: registerLexicalTextEntity does not work with ExtendedTextNode

### ISSUE THREAD

**Issue by fsuk** [facebook/lexical#5508]
When using the ExtendedTextNode example (https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling) the useLexicalExtendedTextEntity hook / registerLexicalTextEntity no longer calls the match method

Lexical version: 0.12.6

## Steps To Reproduce

1. Implement the ExtendedTextNode example with a keywords / token node plugin
2. Keywords/tokens are not transformed

Link to code example:
TextNode and Token plugin (works): https://codesandbox.io/p/sandbox/textnode-and-token-zlym8g?file=%2Fsrc%2FEditor.js
ExtendedTextNode and Token plugin (dosnt work): https://codesandbox.io/p/sandbox/extendedtextnode-and-token-f3q8d9

## The current behavior
The text is not highlighted as the match callback is not called on the Token Plugin

## The expected behavior
Enter "{{ abc }}" (with braces, without quotes) the text should be highlighted red

**Comment by etrepum** [comment]
I think this should be fixed in more recent versions when using `withKlass` in the node override
