### ISSUE TITLE
Question: Is it possible to transform HTML to Lexical State

### ISSUE THREAD

**Issue by Babadzhanov** [facebook/lexical#5530]
For example I have this HTML generated from Lexical state:

```
<h1 class="editor-heading-h1" dir="ltr">
  <span style="white-space: pre-wrap;">Welcome to the playground</span>
</h1>
<p class="editor-paragraph" dir="ltr">
  <span style="white-space: pre-wrap;">Make sure to check out the various plugins in the toolbar.</span>
</p>
```

Using the RichTextPlugin I want to edit text and then save only the HMTL code, later I want to load that HTML for further edits. So far I have figured out how to save as HTML, but not the other way around. Is this possible?

**Comment by acywatson** [comment]
Yes: https://lexical.dev/docs/concepts/serialization#html---lexical

There is some loss of fidelity in the conversion with the out-of-the-box setup though. You may need to fiddle with the importDOM and exportDOM overrides.
