### ISSUE TITLE
Bug: when the table is only child, selection by keyboard breaks the editor

### ISSUE THREAD

**Issue by 2wheeh** [facebook/lexical#5544]
Lexical version: the latest (v0.12.6)

## Steps To Reproduce

1. go to the playground
2. enter a table
3. remove any other siblings (paragraphs)
4. try to select the table backward by pressing `SHIFT` + `UP`
5. it throws an error that ancestor is null

https://github.com/facebook/lexical/assets/40269597/afde292b-a58a-421a-8a46-9d83c78e094a

Link to code example: playground

## The current behavior
it fails to select table

## The expected behavior
select table correctly

**Comment by 2wheeh** [comment]
#5583 fixed this not to break the editor,
but still works a bit weird:

https://github.com/facebook/lexical/assets/40269597/a0cd86eb-fdb2-498f-a5f1-480d0d9edcdd

**Comment by Sahejkm** [comment]
i am not able to replicate this, i think it was fixed with #5543

**Comment by 2wheeh** [comment]
@Sahejkm Yes the original issue is fixed. I will open a new issue for the comment one. I just checked it's still happening.
