### ISSUE TITLE
Bug: console.info accidentally included in released package @lexical/react@0.13.0

### ISSUE THREAD

**Issue by yf-yang** [facebook/lexical#5553]
Lexical version: 0.13.0
<img width="691" alt="image" src="https://github.com/facebook/lexical/assets/36890796/c74bbc0a-9893-4993-91b2-598760653eca">
View it on npm registry: https://www.npmjs.com/package/@lexical/react?activeTab=code

**Comment by yf-yang** [comment]
@acywatson @fantactuka @zurfyx URGENT, production codes are also polluted

<img width="637" alt="image" src="https://github.com/facebook/lexical/assets/36890796/9274aa18-a188-43d7-9d62-a257c9c437e2">

**Comment by zurfyx** [comment]
@yf-yang - Sorry about that, we'll release 0.13.1 today

**Comment by zurfyx** [comment]
Released v0.13.1
