### ISSUE TITLE
Bug: Right Align in Toolbar for RTL direction shows Left Align Icon

### ISSUE THREAD

**Issue by fahad12398** [facebook/lexical#5560]
The icon for Right Align, in case of RTL direction, should be Right Align icon in Toolbar in Lexical Playground. Currently, it is Left Align icon. The right align will always keep your text to the right irrespective of text direction (LTR, RTL).

![image](https://github.com/facebook/lexical/assets/48366592/6f531516-eac2-4633-9e27-b0ba5ba371ae)

In `packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx`, `iconRTL` for `right` ELEMENT_FORMAT_OPTIONS should be `right-align`.

Lexical version:
v0.13.1

## Steps To Reproduce

1. Go to Lexical Playground.
2. Select Right Align.
3. type some text.
4. Change Direction to RTL.
5. The icon for Right Align should stay as it was before changing direction to RTL. 

Link to code example:
https://playground.lexical.dev/

## The current behavior
The icon for Right Align, in case of RTL direction, is Left Align icon.

## The expected behavior
The icon for Right Align, in case of RTL direction, should be Right Align icon.

**Comment by CRIMSON-CORP** [comment]
Im sorry pls how were you able to change the text Direction on lexical? setDirection() does not do anything for me

**Comment by fahad12398** [comment]
Sorry for late reply, i changed the direction in Lexical Playground using context menu. The steps are below:

1. right click on the mouse.
2. go to writing direction menu.
3. select Right to Left.
