### ISSUE TITLE
Feature: Add banners plugin

### ISSUE THREAD

**Issue by Grantoed** [facebook/lexical#5562]
It would be great to have a banners plugin similar to how it works in ClickUp

https://github.com/facebook/lexical/assets/99917295/07d9aa3c-1d62-4952-9499-bbf675220457

**Comment by AliakseiPaseishviliSyntheticabio** [comment]
you can create custom node, which can be a banner plugin....
https://lexical.dev/docs/concepts/nodes#creating-custom-nodes
