### ISSUE TITLE
Bug: Unable to import EditorState class

### ISSUE THREAD

**Issue by Tycholiz** [facebook/lexical#5567]
My project needs to support plaintext as input to the Lexical Rich Text editor to support legacy data. Therefore, I'm trying to write a  utility function that will take the plaintext and convert it to a NodeMap, which can then be used as the input to instantiating a new EditorState object:
```ts
import { EditorState } from 'lexical';
const nodeMap = plainTextToNodeMap(plainTextContent);
const editorStateFromPlainText = new EditorState(nodeMap);
```

However, when I try to instantiate an object with this, I get the ts error:
`'EditorState' cannot be used as a value because it was exported using 'export type'`

And when I try to run the code, I get the same error: `EditorState` is not a class that can be instantiated.

In the Typescript declaration file, the EditorState export is a class:
```ts
export declare class EditorState {
  _nodeMap: NodeMap;
  _selection: null | BaseSelection;
  _flushSync: boolean;
  _readOnly: boolean;
  constructor(nodeMap: NodeMap, selection?: null | BaseSelection);
  isEmpty(): boolean;
  read<V>(callbackFn: () => V): V;
  clone(selection?: null | BaseSelection): EditorState;
  toJSON(): SerializedEditorState;
}
```

It references [this class](https://github.com/facebook/lexical/blob/0cb7f1e645cfe21a6b9ce8b94939a05e0a03e550/packages/lexical/src/LexicalEditorState.ts#L93)

Lexical version: 0.13.0

**Comment by acywatson** [comment]
I think this is intentional - we don't want people directly instantiating EditorState.

Instead, you can use the imperative APIs on an editor instance to build the state you want.

```
editor.update(() => {
    const root = $getRoot();
    root.append($createParagraphNode().append($createTextNode(plainTextContent)));
})
```

**Comment by Tycholiz** [comment]
this works for what I need! thanks for your suggestion
