### ISSUE TITLE
Bug: Loss of Formatting When Pasting Text from Slack to Editor

### ISSUE THREAD

**Issue by safa-kajabi** [facebook/lexical#5576]
When I try to copy and paste formatted (bold, italic) text from Slack to the editor, it loses the formatting when I paste it. If I do the same from the editor to Slack, it preserves the formatting. Is this expected behavior? Is there a way to solve this issue?

Lexical version: 

## Steps To Reproduce

1. Go to Slack.
2. Make the text bold.
3. Copy it to the playground.
4. Bold format will be lost.
5. Do the same for Editor to Slack.
6. It will preserve the formatting

https://github.com/facebook/lexical/assets/127859730/39c1ab68-63fe-4d5e-87f7-e9445fd8271d

Link to code example: Playground

## The current behavior

When you copy and paste formatted text from Slack to the Editor, the formatting is lost.

## The expected behavior

It should preserve the formatting when pasting markdown or formatted text into the editor.

**Comment by kevinansfield** [comment]
It looks like this is unfortunately expected. I've just tested this and Slack only stores plain text on the clipboard when copying from the editor so there's nothing Lexical can do to preserve formatting when pasting back in.

**Comment by kevinansfield** [comment]
I'm going to close the issue because it's a Slack problem rather than a Lexical one.
