### ISSUE TITLE
Bug: Selection over collapsible section gets lost

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#5582]
Lexical: 0.13.1

In the below video selecting backwards, always selects the contents inside a collapsible section, but when I select forward, sometimes, the offset becomes -1. As shown in the below video:

https://github.com/facebook/lexical/assets/7893468/c1b5d348-c67e-4de4-9616-a82d36cf3ce4

**Comment by ivailop7** [comment]
I found what causes it, not sure how to fix it.
If the element in the createDOM method is changed from 'details' to 'div' everything works correctly, however, I think it makes sense to preserve the details tag irrespectively. This seems to be a very low-level thing, around how selection work. I do think, details should be treated as a div for all intended purposes, but unsure where in the selection logic, there is differentiation between the div and non-divs. Interestingly, it works fine for 'summary' which is a child of the div.

**Comment by ivailop7** [comment]
Also think, details and summary should be added to:

https://github.com/facebook/lexical/blob/8a57b66abceda34aee403bccfbb809b57ed29af5/packages/lexical/src/LexicalUtils.ts#L1644-L1650

**Comment by ivailop7** [comment]
I can confirm this works fine in Safari and Firefox, and in Chrome only when the line before is empty. We have a selection issue in Chrome, which we don't in Firefox, compare the number of calls two recordings below in different browsers:

Firefox - OK (<50 hits):

https://github.com/facebook/lexical/assets/7893468/d468c211-0e44-4b28-922a-addf4ef3e278

Chrome - Problematic (1k+ hits):

https://github.com/facebook/lexical/assets/7893468/68870bdb-4cf9-4a85-84d4-7faaedda2891

**Comment by ivailop7** [comment]
Continued investigating, the root of the issue appears to be the discrepancy of the DOM selection returned by the browser (Correct in Firefox, Safari - Range Selection, Chrome returns caret collapsed selection)

<img width="1496" alt="Screenshot 2024-05-26 at 23 14 31" src="https://github.com/facebook/lexical/assets/7893468/ba36a13f-97ac-4150-b1c5-b0b7d4634405">

**Comment by zurfyx** [comment]
I can't repro this exact issue (is it Windows?) but `section` seems buggy on Chrome, maybe we should consider a `div` implementation as you suggested above as the least intrusive way to mitigate the issue.

https://codepen.io/zurfyx/pen/mdYOmbv?editors=1010

Notice 2 issues with selection:
1. With the mouse I need to move my cursor past the collapsible.  `document.getSelection` reports a misleading caret selection, which in Lexical we would incorrectly reconcile and lose this strange in-progress state.
2. With the keyboard I can't get past the collapsible.

Mouse:

https://github.com/facebook/lexical/assets/193447/c32b6ff0-924b-46c6-8de2-1613522cf746

Keyboard (shift + arrow right):

https://github.com/facebook/lexical/assets/193447/afea0b3d-b3e4-47dc-b5b8-3b3366821ed8

**Comment by turnerguo** [comment]
<img width="608" alt="image" src="https://github.com/facebook/lexical/assets/633880/cd299d71-1d44-4a2c-8b7d-1fa0dd254691">

I found a similar bug in Safari, see if you have only a table inside, when you **move up** the cursor from the first table cell it will broken the selection, the cursor will become vertical and the table border also broken.

<img width="647" alt="image" src="https://github.com/facebook/lexical/assets/633880/085d8d68-4285-4f2f-aeda-2c84c809a256">

**Comment by ivailop7** [comment]
We fixed this by switching the createDOM to Div for Chrome. Closing.
