### ISSUE TITLE
Attach image click listeners to editor root element instead of document

### ISSUE THREAD

**Issue by cmattick** [facebook/lexical#5599]
As mentioned in https://github.com/facebook/lexical/issues/3657#issuecomment-1460784076 the fix for issue https://github.com/facebook/lexical/issues/3657 was only applied to checkboxes not images.
I have exactly the same problem with images in a react app, where at some point the event propagation is stopped (which i cannot deactivate without getting trouble at other points in the app).

**Comment by username14415** [comment]
+1
I use headless ui dialog modal and the same, images are not clickable

**Comment by etrepum** [comment]
Please re-open with more information if you can still reproduce this issue. Lexical doesn't have "images", at least not that it exports in the API. There are some demo nodes in the playground, but it's really not clear which ones you're talking about here.
