### ISSUE TITLE
Allow `getLatest` to be temporarily deactivated

### ISSUE THREAD

**Issue by ccapndave** [facebook/lexical#5604]
We are working on a Lexical project where an editor state is analysed, important chunks of text are identified and then we wrap them in little boxes by putting custom nodes around them.  Exactly where the custom nodes need to be inserted is specified with this type:

```ts
export type AnalyserRange = {
  fromPoint: PointType;
  toPoint: PointType;
};
```

However, this means that we need to take care to update subsequent ranges based on what has already been inserted, as inserting nodes can cause text nodes to be split and keys to change.  Luckily we know that the text content of the editor state will never change during this phase, and therefore we have a simple algorithm to go through the content assigning an index to each point, which then allows us to remap a range from one editor state to another.

The function we use to do this has this signature:

```ts
function remapTextPoint(
  point: PointType,
  fromEditorState: EditorState,
  toEditorState: EditorState
): PointType | null;
```

In order to save rendering multiple times to the DOM we do all the work in a single `update` cycle.

However, this has thrown up a problem; no matter which editor state you retrieve a node from, the node's functions will *always* work on the pending state because everything calls `this.getLatest()` before doing anything.  Although 99% of the time this is the correct behaviour, we explicitly need access to nodes in a particular state (even if its not the latest) in order to remap our points.

Here is a test explicitly illustrating the situation:

```ts
it("lets us use nodes from the active state", () => {
    const editor = createEditor();

    let textNode!: TextNode;
    editor.update(
      () => {
        const p = $createParagraphNode();
        textNode = $createTextNode("hello");
        $insertNodes([p.append(textNode)]);
      },
      { discrete: true }
    );

    editor.update(() => {
      const helloNode = $getNodeByKey(textNode.getKey(), editor.getEditorState());
      expect(helloNode?.getTextContent()).toBe("hello");

      // Update the text in the text node
      textNode.setTextContent("goodbye");

      // Now, even though we `$getNodeByKey` specifically from the active editor state, we actually
      // get the node from the pending state (because everything calls `getLatest`).
      const goodbyeNode = $getNodeByKey(textNode.getKey(), editor.getEditorState());
      expect(goodbyeNode?.getTextContent()).toBe("goodbye");

      // Although this is usually the behaviour we want, sometimes we want to disable this.  Can we?

      // !! DO SOME MAGIC HERE !!

      const activeNode = $getNodeByKey(textNode.getKey(), editor.getEditorState());
      expect(activeNode?.getTextContent()).toBe("hello");
    });
  });
```

My initial idea was to temporarily monkeypatch `getLatest()` on the prototype of `LexicalNode` in our function, but `LexicalNode` is only exported as a type and so this doesn't seem to be possible.

So, my questions are:

 - are we being stupid and there is a much simpler way to go about all of this?
 - if not, is there any way to temporarily disable `getLatest`?
 - if not, would you accept a PR with functions to enable and disable `getLatest`?  I know its a bit of a strange one....

Cheers!

**Comment by ccapndave** [comment]
Now that I've written this all down, I realise that one way to do this would be to walk through all the nodes in the editor state monkey patching `getLatest`, and then doing the same to unmonkeypatch afterwards, but this seems a bit wasteful.

**Comment by ccapndave** [comment]
Here is a temporary solution:

```ts
export function $withActiveEditorState(fn: () => void) {
  const getLatestOriginals = new WeakMap<LexicalNode, () => LexicalNode>();

  const searchResults = $dfs();

  searchResults.forEach(({ node }) => {
    getLatestOriginals.set(node, node.getLatest);
    node.getLatest = function () {
      return this;
    };
  });

  fn();

  searchResults.forEach(({ node }) => {
    node.getLatest = getLatestOriginals.get(node)!;
  });
}
```

which can be used like this:

```ts
editor.getEditorState().read(() => {
  $withActiveEditorState(() => {
    const activeNode = $getNodeByKey(textNode.getKey());
    expect(activeNode?.getTextContent()).toBe("hello");
  });
});
```

**Comment by acywatson** [comment]
Do you need to operate on nodes from both states, or just read one and operate on the other? If it's the latter, can you try using EditorState.read, and get the information from that editor state that way?

Another way to go at this might be to directly access the nodeMap property of the EditorState, rather than getNodeByKey.

**Comment by ccapndave** [comment]
Even using `EditorState.read` to get the active state will operate on the pending state once you start using any of the `get*` methods on nodes as they all call `getLatest`.

However, we have actually gone down a completely different path of temporarily inserting custom nodes just for the purposes of marking points that we are interested in during the update.  Then Lexical takes care of keeping the nodes in the correct place and we can retrieve and delete them as we go through the process.  This turns out to work excellently!

We also had a go with the `@lexical/offset` package which should do exactly what we were trying to do with the indexes, but we couldn't get it to work reliably.  Not sure if thats because of us or the package :)

**Comment by etrepum** [comment]
I think the only reasonable solution to this is to nest an `editor.getEditorState().read(…)` in your update when you want to read the previous version of that node. There's no reason to do all of the stuff with keys and states directly, the editor.update or editorState.read context provides that.

```ts
it("lets us use nodes from the active state", () => {
    const editor = createEditor();

    let textNode!: TextNode;
    editor.update(
      () => {
        const p = $createParagraphNode();
        textNode = $createTextNode("hello");
        $insertNodes([p.append(textNode)]);
      },
      { discrete: true }
    );

    editor.update(() => {
      expect(textNode.getTextContent()).toBe("hello");

      // Update the text in the text node
      textNode.setTextContent("goodbye");

      expect(textNode.getTextContent()).toBe("goodbye");

      // Visit the past
      editor.getEditorState().read(() => {
        expect(textNode.getTextContent()).toBe("hello");
      });
    });
  });
```
