### ISSUE TITLE
Bug: Why $generateHtmlFromNodes  generated <code> tag to <pre>

### ISSUE THREAD

**Issue by DeadMonstr** [facebook/lexical#5605]
![image](https://github.com/facebook/lexical/assets/74488870/7c88f44b-5e3a-4659-a96f-530766a7f538)
![image](https://github.com/facebook/lexical/assets/74488870/e5f65a6b-5557-40a3-8d4c-a74e039702fa)

I don't know this is bug or not

**Comment by 2wheeh** [comment]
It's not

**Comment by ivailop7** [comment]
Working as designed. 'pre' (preformatted) refers to multiline code block where the leading whitespace is preserved. So upon exporting HTML you want it as 'pre'. The 'code' single line is a inline code block, and multiline is pre block. I think code was kept for backwards compatibility.

**Comment by ivailop7** [comment]
Since you can have pre being non-code, I think this is why we kept multiline code as a code block, but still export as 'pre' for rendering. Might be forgetting the whole reasoning now, but it was along those lines.

**Comment by DeadMonstr** [comment]
thanks
