### ISSUE TITLE
Bug: dom.setAttribute is not a function

### ISSUE THREAD

**Issue by v1valasvegan** [facebook/lexical#5610]
Lexical version:  0.13.1
I'm trying to implement a custom node insert functionflity. I followed the steps from this video https://www.youtube.com/watch?v=abZNazybzvs, the only difference is that I'm trying  to insert node and want it to be done by pressing 'p' on keyboard. But for some reason I've got an error `dom.setAttribute is not a function` (you should open the console to see this)

## Steps To Reproduce

1. Put a cursor inside a contenteditable div
2. Press 'p'

Link to code example: https://replit.com/@v1valasvegan/InfamousScalyZip

**Comment by ivailop7** [comment]
Please use Discord, for these types of questions.
