### ISSUE TITLE
Bug: Unable to use toolbar on Android. How can I disable the context menu on text selection?

### ISSUE THREAD

**Issue by safa-kajabi** [facebook/lexical#5624]
In the playground, if I highlight text, the Android context menu prevents me from selecting an option from the toolbar because it appears on top of the selected text. On iOS, it appears below the selection. Is there any solution for this?

<img src="https://github.com/facebook/lexical/assets/127859730/4c280448-81d7-4337-ac93-9c48c8728c77" width=250 />

Lexical version: 0.13.1

## Steps To Reproduce

1. Use Android device
2. Go to playground
3. Highlight a text on top of the editable content area
4. You will notice that the Android context menu prevents selecting an option from the toolbar

Link to code example: 

## The current behavior

The Android context menu appears on top of the highlighted text, which prevents us from selecting an option from the toolbar.

## The expected behavior

The context menu should be displayed above the highlighted text to allow for selection, or it should not be displayed at all.

**Comment by moy2010** [comment]
The playground is, as its name suggests, only a showcase of what can be done with Lexical. That is, the functionality available there is provided for demonstration purposes, it's not expected to be production-ready. It's up to you to come up with UI/UX solutions that suit your use case(s).
