### ISSUE TITLE
Bug: The selection changes unexpectedly when changing font family (or anything using inline style)

### ISSUE THREAD

**Issue by trinhvinhtruong96** [facebook/lexical#5632]
Lexical version: v0.13.1

## Steps To Reproduce

1. Type some text
![image](https://github.com/facebook/lexical/assets/48130078/fbb00245-5f98-412e-a07b-4c98000b1c66)
2. Shift- Enter to add a linebreak and type some text. 
![image](https://github.com/facebook/lexical/assets/48130078/2b2721d1-b640-4e77-880d-0f0623460181)
3. Select text include 2 line
![image](https://github.com/facebook/lexical/assets/48130078/33b97d4c-347a-4079-8664-810d990354b1)
4. Change the font family (or anything using inline style)
![image](https://github.com/facebook/lexical/assets/48130078/b7da3348-8276-49d6-ae55-c70060c95666)
-> The selection changes unexpectedly

Link to code example: https://playground.lexical.dev/

## The current behavior
The selection changes unexpectedly
 # The expected behavior
The selection stays the same as before changing the font family

**Comment by etrepum** [comment]
I can't reproduce this
