### ISSUE TITLE
Feature: 🤖 LLM search (ChatGPT) in Docs

### ISSUE THREAD

**Issue by ADTC** [facebook/lexical#5635]
Given that a rich text editor framework has a bit of a learning curve, it would be nice to see an LLM chat bot instead of standard search [in the Docs website](https://lexical.dev/docs/intro). One that has a thorough understanding of the existing docs and can answer your queries about it.

The standard search is there, of course, powered by Algolia. But a GPT-powered search can not only find keywords but also answer questions, and quite possibly generate personalized code for me, and answer follow-up questions as well.

_Side note: I think `https://lexical.dev/docs` should redirect to `https://lexical.dev/docs/intro`. Currently gives 404._

**Comment by thegreatercurve** [comment]
Closing, as I think this is an unlikely addition. It seems like a lot of effort for little reward, especially as the effort should be more on improving our docs. 

We'd have to build the full front and back-ends for the LLM as this isn't a default plugin for Docusaurus, like the [native Algolia search plugin](https://docusaurus.io/docs/search). There's issues around re-training the model on any doc changes as well, which is going to be a lot of work. 

On the plus side though, we certainly don't prohibit any third-party LLMs from scraping our docs, so if you can allow list our domain any where where it will be consumed.
