### ISSUE TITLE
Bug: data-gutter not exported in <code/> after export to html

### ISSUE THREAD

**Issue by addlistener** [facebook/lexical#5640]
Lexical version: 0.13.1

## Steps To Reproduce
Just use playground.lexical.dev and add a code block, click export dom
<img width="1692" alt="image" src="https://github.com/facebook/lexical/assets/4531670/3aa0b0b2-ad4d-481d-b32b-cf21ca690337">

## The current behavior
data-gutter not exported, so line numbers will be missing. I can also reproduce locally this even if I add https://lexical.dev/docs/concepts/serialization#handling-extended-html-styling this patch after cloning the repo.

## The expected behavior
data-gutter is exported

## My local verisons
     "lexical": "0.13.1",
     "@lexical/clipboard": "0.13.1",
     "@lexical/code": "0.13.1",
     "@lexical/file": "0.13.1",
     "@lexical/hashtag": "0.13.1",
     "@lexical/link": "0.13.1",
     "@lexical/list": "0.13.1",
     "@lexical/mark": "0.13.1",
     "@lexical/overflow": "0.13.1",
     "@lexical/plain-text": "0.13.1",
     "@lexical/react": "0.13.1",
     "@lexical/rich-text": "0.13.1",
     "@lexical/selection": "0.13.1",
     "@lexical/table": "0.13.1",
     "@lexical/utils": "0.13.1",

**Comment by 2wheeh** [comment]
https://github.com/facebook/lexical/pull/4735#issuecomment-1620807057
Lexical team didn't want to expose `data-gutter` on purpose ...

There was a PR to replace `data-gutter` but found out not working on Firefox or Safari so PR just got closed (#4743).

Anyway, here is my workaround with `HTMLconfig`:

```ts
//  html-config.ts

import { $isLineBreakNode, type HTMLConfig } from 'lexical';
import { CodeNode } from '@lexical/code';
import { addClassNamesToElement } from '@lexical/utils';

// https://github.com/facebook/lexical/releases/tag/v0.12.3
// referenced an internal function updateCodeGutter in @lexical/code
// to keep 'data-gutter' on exported html.
export const htmlConfig: HTMLConfig = {
  export: new Map([
    [
      CodeNode,
      (editor, node) => {
        // TODO: remove assertion to CodeNode after lexical fixes the type for parameter
        // https://github.com/facebook/lexical/pull/5507
        const codeNode = node as CodeNode;
        const element = document.createElement('pre');
        addClassNamesToElement(element, editor._config.theme.code);
        element.setAttribute('spellcheck', 'false');
        const language = codeNode.getLanguage();

        if (language) {
          element.setAttribute('data-highlight-language', language);
        }

        const children = codeNode.getChildren();
        const childrenLength = children.length;

        let gutter = '1';
        let count = 1;
        for (let i = 0; i < childrenLength; i++) {
          if ($isLineBreakNode(children[i])) {
            gutter += '\n' + ++count;
          }
        }

        element.setAttribute('data-gutter', gutter);
        return { element };
      },
    ],
  ]),
};
```

```ts
// Editor.tsx
import { htmlConfig } from './html-config';

function Editor() {
  const initialConfig: InitialConfigType = {
    // .. other configs
    html: htmlConfig,
  };
  
  return (
    <>
      <LexicalComposer initialConfig={initialConfig}>
  // ...
```
