### ISSUE TITLE
Bug:  Deleting selected text node not working on Android (Chrome)

### ISSUE THREAD

**Issue by hamza512b** [facebook/lexical#5645]
Lexical version: 0.13.1

## Steps To Reproduce

1. Open Lexical Playground on Chrome Android latest release
2. Write a sentance. 
3. Select the whole sentance.
4. Delete the sentance. Not working.

Here a video of demostartion how this is happening!
https://github.com/facebook/lexical/assets/63897375/2c1b3778-b4db-4fb8-bc20-357c656a608d

**Comment by thegreatercurve** [comment]
Tried repro-ing with latest version and this appears to have been fixed as of #5644.
