### ISSUE TITLE
Bug: If editable is false, $setSelection doesn't update the visual highlight of selection in page

### ISSUE THREAD

**Issue by ADTC** [facebook/lexical#5648]
If `editable` is set to `false` (read-only mode), then the `$setSelection` doesn't appear to work. Actually it works, but it only updates the internal selection. It doesn't change the visual highlight in the DOM/page.

Lexical version: 0.13.1 (also @lexical/react)

## Steps To Reproduce

1. Initialize editor with `editable` as false and with some dummy content.
2. Add a debug mode visualizer plugin if you want to see the internal selection. (optional)
3. Try setting a selection using `$setSelection`.

Link to code example: https://codesandbox.io/p/sandbox/green-microservice-q3c3w8

<img width="630" alt="image" src="https://github.com/facebook/lexical/assets/6047296/2a2a4e47-c07f-4777-a26e-148e5e268eb5">

## The current behavior

Selection does not update visually in page if editable is false.

## The expected behavior

Selection should update visually in page regardless of editable boolean value.

_PS: The [plain text sandbox link](https://codesandbox.io/s/lexical-plain-text-example-g932e) is dead._

**Comment by etrepum** [comment]
This is currently intended behavior to avoid the browser from "stealing focus" when a read-only document is updated programmatically, the #6872 SelectionAlwaysOnDisplay plugin should provide this functionality if you want a visual selection in situations like this
