### ISSUE TITLE
Bug: Nested Lists are rendered wrongly in Editor

### ISSUE THREAD

**Issue by dunklesToast** [facebook/lexical#5661]
Lexical version: 0.13.1

## Steps To Reproduce

1. Open CodeSandBox: https://codesandbox.io/p/sandbox/lexical-list-indentation-ghdg6l
2. Type a word, press `numbered` - a numbered list appears
3. Press `Enter` and then `Tab` - a nested bullet gets attached but the first level bullet is also being rendered

Link to code example: https://codesandbox.io/p/sandbox/lexical-list-indentation-ghdg6l

## The current behavior

Lexical renders something like this:
```
1. This is the first level
2. 1. This is the second level 
```

https://github.com/facebook/lexical/assets/17279485/f7d271f7-6f46-4727-9ab3-a32a7352967e

## The expected behavior
```
1. This is the first level
  1. This is the second level 
```

**Comment by amanharwara** [comment]
This is not an actual bug. You're probably just missing styles for that. Take a look how the playground handles this: https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/themes/PlaygroundEditorTheme.css#L379-L381

**Comment by acywatson** [comment]
Agreed with above - please see the styles at the code pointer and use those to achieve your use case.

**Comment by pleunv** [comment]
I do think this is in fact a bug and Lexical is generating incorrect markup for nested lists. To my knowledge nested lists should have the following markup:

```html
<ul>
  <li>
    First item
    <ul>
      <li>Nested first item</li>
    </ul>
  </li>
</ul>
```
While Lexical is generating the following:
```html
<ul>
  <li>First item</li>
  <li>
    <ul>
      <li>Nested first item</li>
    </ul>
  </li>
</ul>
```
Which leads to the undesired styling above. Nested list styling should work out-of-the-box with browser stylesheets, the fact that it doesn't indicates that something's off.

**Comment by thmsbkkr** [comment]
Please re-open this ticket as what @pleunv above mentions is correct. 
The HTML generated from the plugin is formatted incorrectly.

**Comment by acywatson** [comment]
> Please re-open this ticket as what @pleunv above mentions is correct. The HTML generated from the plugin is formatted incorrectly.

Please refer to this issue: https://github.com/facebook/lexical/issues/2951
