### ISSUE TITLE
Bug: Inserting a table from external source can lead to Lexical crash

### ISSUE THREAD

**Issue by vect-spasquereau** [facebook/lexical#5662]
Hello there. I'm working with lexical tables and I was trying to implement background color control. I was testing with tables copied from external resources (google doc, google spreadsheet). Lexical is able to import the tables, but is crashing when I trying to leave the table.

Lexical version: 0.13.1

## Steps To Reproduce

1. Go in Google doc, insert a table and copy it
2. Paste it into Lexical
3. Go to last cell and press the right arrow to focus the table end
4. Press Enter to insert a paragraph underneath the table
5. Lexical is crashing

https://www.loom.com/share/dc72b967351a49afa1de3e5f0d1d7b66?sid=c3b11039-a4fd-4877-a176-74204fd36c4a

Link to code example: reproductible in Lexical playground

After investigation, I think Lexical is going in an infinite loop in LexicalSelection -> removeTextAndSplitBlock
(@birtles I think you've been working on this 👀)

**Comment by birtles** [comment]
@vect-spasquereau Sorry I'm on leave at the moment so I haven't had a chance to dig through old issues but did I mention working on something like that? Or did I cause a regression here?

**Comment by vect-spasquereau** [comment]
@birtles sorry I didn't notice you are on leave. I just checked the file history and saw you were the last one implementing/refactoring the LexicalSelection -> removeTextAndSplit and LexicalSelection -> splitNodeAtPoint functions. I assumed it could mean something for you 🙂
Nevermind, it's an edge case, I'll try to come up with a fix to break this infinite loop

**Comment by vect-spasquereau** [comment]
well, that was a wrong lead. Fixing the `convertTableCellNodeElement` when copying tables from external sources.

**Comment by vect-spasquereau** [comment]
https://github.com/facebook/lexical/pull/5670

**Comment by birtles** [comment]
> @birtles sorry I didn't notice you are on leave.

Not at all! GitHub doesn't make that information very visible.

> I just checked the file history and saw you were the last one implementing/refactoring the LexicalSelection -> removeTextAndSplit and LexicalSelection -> splitNodeAtPoint functions. I assumed it could mean something for you 🙂 Nevermind, it's an edge case, I'll try to come up with a fix to break this infinite loop

I'm afraid I haven't touched lexical code since that patch. It sounds like you worked it out though!
