### ISSUE TITLE
Bug: Inserting a new paragraph after a decorator node in a collapsible node leads to infinite loop when selection offset is positive

### ISSUE THREAD

**Issue by saveliyvasilev** [facebook/lexical#5674]
Lexical version: 0.13.1

## Steps To Reproduce

1. Run a Lexical Playground instance
2. Add a new Collapsible Node
3. In the content section, insert some decorator node (for example a HorizontalRule, Twitter or YouTube node)
4. Delete the paragraph right after the decorator node 
![image](https://github.com/facebook/lexical/assets/1032234/81cdb235-5053-4517-8e8d-eca8fd8ee6dd)
5. Hit enter when the cursor is in horizontal mode right below the decorator node. The cursor will leave the collapsible container, go back to the spot indicated above and try again (up-arrow twice and then go down with the arrow). **This will set the selection offset=2**. Hit enter.
![image](https://github.com/facebook/lexical/assets/1032234/21ae7cf0-1494-49f4-a577-f25b42431c4e)

6. This will cause an infinite loop inserting new paragraphs, which eventually will throw an `RangeError: Map maximum size exceeded` exception.
![image](https://github.com/facebook/lexical/assets/1032234/92db6019-917d-419c-8b14-8a6560195e16)

Link to code example:
just run the current version. My local git clone breaks, the deployed one also fails

## The current behavior
Loads the CPU until crash because of memory constraints, editor stalled after this

## The expected behavior
Adds a paragraph

**Comment by Sahejkm** [comment]
@saveliyvasilev this bug is not replicable now , should be fixed with #5969. Feel free to reopen if this is still replicable
