### ISSUE TITLE
Feature: proposal for Lexical Devtools

### ISSUE THREAD

**Issue by Aemulatio** [facebook/lexical#5675]
Hi. First of all thank for your framework, its great!
I'm working with lexical and when creating some intricate logic I want to see current state of the lexical (e.g. json format) for that I create a temporary button which help me to get it.. Sooo, it would be amazing to see devtools browser extension in the future. 

As I think the most hard part is get all instances on the page. 
Maybe somehow get all namespaces (if they are unique) and getting data for each of them.

**Comment by StyleT** [comment]
Hello! I think it's on the roadmap, and personally I wanted to work on it if no one takes it on first.

**Comment by StyleT** [comment]
This one is in progress: #5747  #5830

**Comment by StyleT** [comment]
**Development plan (v1, MVP):**

- [x] Scaffold a new [cross-browser web extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension) which works with Firefox, Chrome, Edge, and Safari.
    #5747 
- [x] Port the existing inline ASCI Lexical state tree representation to the extension.
    #5830
- [ ] @StyleT Register (& share access with Core Team) developer accounts in:
  - [ ] Chrome Web Store ($5 one time fee)
  - [ ] Apple Developer Program ($100/mo)
  - [ ] [Firefox AMO](https://extensionworkshop.com/documentation/publish/submitting-an-add-on/#listing-on-amo) (free)
- [ ] @StyleT Build a CI pipeline within our Github Actions which handles publishing new extension versions to their respective web extension stores and publish v1 to the respective stores

**Development plan (v2):**
- [ ] _[Up for grabs]_ Create a more interactive representation of the Lexical state tree, akin to the Component view within [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en).
  - [ ] Respective tree nodes should be collapsible or expandable.
  - [ ] Respective tree nodes should highlight the relevant DOMNode on hover of the Lexical Node.
  - [ ] Add slide out panel with all properties on the node.
  - [ ] Add a view for the current selection.
  - [ ] Add the ability to time-travel between different editor states.
  - [ ] Add a log of all Lexical commands and their respective payloads.
  - [ ] View should be performant even for larger Lexical state trees.
  - [ ] View should have a suite of unit and E2E tests which test for basic Lexical states.
  - [ ] Add details of editor config.
- [ ] _[Up for grabs]_ Add the extension to each of our test browser environments, so we can better debug failing E2E tests.

See also 1st attempt on extension creation here: 
- Issue: #2127
- Deprecation PR: #4023

**Comment by etrepum** [comment]
I think we can close this because there has been a browser extension for some time
