### ISSUE TITLE
Bug: Typing an invalid or partially valid hashtag followed by a valid hashtag causes infinite transform execution

### ISSUE THREAD

**Issue by jefflieb-wavy** [facebook/lexical#5703]
Hi!  Typing `#eggs#eggs #e` in a Lexical editor causes infinite transform execution, sometimes followed by the editor no longer responding properly to input.  Additionally, hashtags seem like they should either be valid when directly adjacent, or they should never be valid when adjacent, as in the first `#eggs` should not be a hashtag once the second `#` is appended.

This also happens in a plaintext editor.

<img width="1107" alt="Screenshot 2024-03-12 at 10 24 22 AM" src="https://github.com/facebook/lexical/assets/116473469/9674f875-b68f-4c98-9088-40634063ba5e">

Lexical version: 0.13.1

## Steps To Reproduce

1. Open the [Lexical playground](https://playground.lexical.dev/)
2. Type `#eggs#eggs #e`, observe the console error.  On mac at least, cmd+A no longer selects all text.  Backspace also does not remove text.

Link to code example:

https://playground.lexical.dev/

## The current behavior

- The first `#eggs` instance is marked as a hashtag despite being invalid
- `#e` is not marked as a hashtag
- An infinite transform error is thrown
- The editor may or may not respond to select all via keyboard
- The editor may respond to backspaces by moving the beginning of the selection range backward instead of deleting characters, or it may do nothing

## The expected behavior

- The two instances of `#eggs` are both either valid or invalid.
- `#e` is marked as a hashtag
- An infinite transform error is not thrown
- The editor responds to key input properly

**Comment by muskan2622** [comment]
![image](https://github.com/facebook/lexical/assets/84541807/1437a7c2-5658-40f5-b924-28d68d517020)


Adding Space between the hashtags is working absolutely fine.

**Comment by 2wheeh** [comment]
It can reproduce with 
```
#a#b some more texts here ... #c
```

as well.
It seems to fail to transform nextMatch (`#c`) somehow and iterate infinitely ...

**Comment by 2wheeh** [comment]
It's a dup of #3468

If you don't need hashtag to be adjacent in your service, you could consider this workaround #5322

**Comment by jefflieb-wavy** [comment]
Ope, thanks, sorry for the duplicate.  I was able to work around this by creating a plugin which uses a regex that matches hashtags only when they have valid leading and trailing characters, with only the hashtag portion being returned as the match for the text entity.
