### ISSUE TITLE
Bug: Indentation in Markdown is not being reflected

### ISSUE THREAD

**Issue by RyoSogawa** [facebook/lexical#5704]
Lexical version: playground

## Steps To Reproduce

1. Switch to Markdown display mode
2. Input indentation using, for example, the Tab key
3. Switch back to original display mode and convert Markdown string

https://github.com/facebook/lexical/assets/23335687/b1c6aba0-23b2-4a2f-b8a7-07e2c13efad3

Link to code example:

## The current behavior
Indentation on Markdown is being ignored

## The expected behavior
Indentation on Markdown should be reflected

**Comment by muskan2622** [comment]
![image](https://github.com/facebook/lexical/assets/84541807/650a4959-5e33-430f-8327-45d1bdc58f6f)


Hey , it is working absolutely fine in mine.

**Comment by 2wheeh** [comment]
Currently, it counts \t character as same as one space. 
So if you use tab key for indentation here, it has to be 4 strokes as you do with space key.
It feels like a bug for me as well.
