### ISSUE TITLE
Feature: React 16 Support

### ISSUE THREAD

**Issue by lscheibel** [facebook/lexical#5712]
I was wondering if the peer-dependency on React >= 17 could be dropped to >= 16. I am currently working with Apache Superset who, for various reasons, can't upgrade React in the near future. Are there any functions from React 17 that Lexical depends on?

**Comment by ivailop7** [comment]
Unlikely, but for your use case you can just add an override for "react" in your "package.json" and it will override all versions of react to use that specific one.

**Comment by lscheibel** [comment]
Good point, thanks for the quick response!
