### ISSUE TITLE
Bug: failure to build with Webpack due to "Module not found: Error: Default condition should be last one" [regression]

### ISSUE THREAD

**Issue by birtles** [facebook/lexical#5731]
Lexical version: 0.14.0 and 0.14.1

## Steps To Reproduce

1. Attempt to build a project that uses @lexical/react with Webpack

## The current behavior

You get a bunch of errors of the form:

```
Module not found: Error: Default condition should be last one
```

## The expected behavior

It should build without error.

## Analysis

This appears to be a regression from #5618 which changed `lexical-react/package.json` adding a bunch of exports of the form:

```json
  "exports": {
    "./LexicalAutoEmbedPlugin": {
      "import": {
        "default": "./LexicalAutoEmbedPlugin.esm.js",
        "types": "./LexicalAutoEmbedPlugin.d.ts"
      },
      "require": "./LexicalAutoEmbedPlugin.js"
    },
```

Webpack wants the `default` there to come last, i.e. after `types`.

I've confirmed locally that just switching the order of those two lines in each instance allows the build to pass again.

I'll make up a PR for this as soon as I get a spare moment (I'm currently on leave so feel free to steal this from me).

**Comment by ivailop7** [comment]
Waiting to see if there are other issues with the version before we publish a 0.14.2

**Comment by 2wheeh** [comment]
This is breaking nextjs app as well

<img width="908" alt="image" src="https://github.com/facebook/lexical/assets/40269597/6b30686c-0e0c-4f36-8c87-1d27af074dc9">
