### ISSUE TITLE
Bug: ComponentPickerPlugin scrolling is buggy - dropdown disappears onScroll

### ISSUE THREAD

**Issue by JingkangZhang** [facebook/lexical#5740]
In some edge cases, the component dropdown plugin cannot be scrolled correctly - if you scroll down, the dropdown disappears. Fairly frustrating user experience.

https://github.com/facebook/lexical/assets/30300487/67a496fc-2cb1-4ea8-ba17-74959612bb2b

Lexical version: live on the [playground](https://playground.lexical.dev/) as of now

## Steps To Reproduce

1. input the text as shown in the video
2. type '/' to bring up the component picker and scroll down 

Link to code example:

## The current behavior
see above

## The expected behavior
dropdown shouldn't disappear

**Comment by JingkangZhang** [comment]
From my preliminary investigation, in this unhappy case, isInView [here](https://github.com/facebook/lexical/blob/6e4f072ea194e7d3e631e488ad1ca1be79add50e/packages/lexical-react/src/shared/LexicalMenu.ts#L225) becomes false when the scroll happens and the menu gets closed. 

So two monkey patches came to me, that I tested and confirmed would work:
1. delete the [logic to position the dropdown on top](https://github.com/facebook/lexical/blob/6e4f072ea194e7d3e631e488ad1ca1be79add50e/packages/lexical-react/src/shared/LexicalMenu.ts#L517-L525) - never place it on top. This is not ideal when it's opening up at the very bottom. Well, actually, it just might be that the top px calculation is off - perhaps the calculation is supposed to make sure it doesn't overlap, but it does visually.
<img width="498" alt="Screenshot 2024-03-20 at 3 14 15 AM" src="https://github.com/facebook/lexical/assets/30300487/10d2098d-6c03-4467-9398-b8a65cbe9cbd">
<img width="391" alt="Screenshot 2024-03-20 at 3 14 23 AM" src="https://github.com/facebook/lexical/assets/30300487/a01f7b82-24af-44a9-9f33-39a37a1a4fb8">

2. could be something wrong with this [isTriggerVisibleInNearestScrollContainer function](https://github.com/facebook/lexical/blob/6e4f072ea194e7d3e631e488ad1ca1be79add50e/packages/lexical-react/src/shared/LexicalMenu.ts#L225-L234) - not clear what is not visible here, and then, why close the dropdown at all on scrolling? So getting rid of the logic entirely seems to work for me.

but yeah, pretty shallow reading of the logic on my end for sure, hope experts can chime in. cc @tylerjbainbridge

**Comment by etrepum** [comment]
I can't reproduce this
