### ISSUE TITLE
Bug: Failed to upgrade Laxical from `0.13.1` to `0.14.x` (React)

### ISSUE THREAD

**Issue by maichongju** [facebook/lexical#5746]
When using upgrading from `0.13.1` to `0.14.x`, it will always failed with the following error message.

```
npm ERR! Found: @lexical/react@0.13.1
npm ERR! node_modules/@lexical/react
npm ERR!   @lexical/react@"0.14.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @lexical/react@"0.14.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: lexical@0.14.2
npm ERR! node_modules/lexical
npm ERR!   peer lexical@"0.14.2" from @lexical/react@0.14.2
npm ERR!   node_modules/@lexical/react
npm ERR!     @lexical/react@"0.14.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Lexical version: 0.13.1

## Steps To Reproduce

1. create any new project with `npm init`
2. run `npm install --save lexical@0.13.1 @lexical/react@0.13.1`
3. run `npm install --save lexical@0.14.2 @lexical/react@0.14.2`

The error should happen when running step 3

Link to code example:

No example

## The current behavior

Auto upgrade failed. 

Work around:
Deleting `node_module` and `package.lock` before upgrade to `0.14.x`

## The expected behavior

The upgrade should work without the workaround.

**Comment by ivailop7** [comment]
Pretty sure, it's an npm issue. Clear your npm cache and 'node_modules' and 'npm install' again.
