### ISSUE TITLE
Feature: Extend error boundary to all editor listeners

### ISSUE THREAD

**Issue by micaelbergeron** [facebook/lexical#5748]
After working on some Lexical integration, I was confused when my `onError` handler wasn't getting called when one of my editor listener was throwing an error.

After taking a look at the code, what happens is quite clear: only `editor.update(…)` wraps the user-defined code for error handling via the `onError` handler.

For instance, if I want my error handling to be homogeneous, I would like to have

```javascript
const initialConfig = {
  …,
  onError: (error, editor) => {
    logger.error(error.message) // with potentially more context
  }
} as const;

const handleOnChange = (editorState, editor) => {
  // do some business logic here
  // but sometimes I might throw a nasty error
  if (somethingGoesSuperWrong) {
    throw new Error('Boom');
  }
}

// Then set this up in my LexicalComposer
<LexicalComposer initialConfig={initialConfig}>
  <OnChangePlugin onChange={handleOnChange} />
</LexicalComposer>
```

This, won't work, unless I wrap my `onChange` within an `editor.update(…)` — is this the expected behavior?

There are multiple workarounds here, for instance I could change `handleOnChange` to the following:
```javascript
const handleOnChange = (editorState, editor) => {
  try {
    // do some business logic here
    …
  } catch (err) { 
    if (editor._onError) return editor._onError(err);
    throw err;
  }
}
```

Which actually works, but seems like extra boilerplate, especially when building custom plugins (which hooks directly into `editor.registerUpdateListener(…)`).

Any pointers or suggestions would be appreciated :)

**Comment by acywatson** [comment]
Thanks for opening this.

I think this is expected?

In your example, the change handler is just your business logic that lexical invokes. If something throws in there, that's not an editor error, that's an error in the business logic. The error handler on Lexical is specifically to catch and handle errors that happen during the editor lifecyle.

This is my take, but I guess the counterargument is that it may be more convenient to define/invoke your error handler in fewer places. Honestly, I think the "workarounds" are sufficient in this case.
