### ISSUE TITLE
Bug: Updating to version 0.14 esm error

### ISSUE THREAD

**Issue by zifahm** [facebook/lexical#5749]
Upgraded from version 0.13 to 0.14 and while running the app, the following error shows up

```
/home/afi/Documents/Retention-Script/node_modules/@lexical/react/LexicalComposer.esm.js:7
import * as modDev from './LexicalComposer.dev.esm.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
```

Lexical version:0.14

## Steps To Reproduce

1. upgrade version 0.13 to 0.14
2. Run app

## The current behavior
Produces the error shown above.

## The expected behavior
Work normally with esm

**Comment by etrepum** [comment]
Can you post a reproduction (in a repo, stackblitz, or something like that) that fails? There's not enough information in the error message alone to reproduce.

**Comment by vchirikov** [comment]
Ran into the same issue with 0.14.2 with vite v5.2.6
```
(node:23152) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
01:13:46 [vike][request(3)][Error] Transpilation error:
\node_modules\@lexical\react\LexicalComposer.esm.js:7
import * as modDev from './LexicalComposer.dev.esm.js';
^^^^^^
```

package.json has `"type": "module",`

**Comment by etrepum** [comment]
The next release should address this and you will no longer need additional config

**Comment by etrepum** [comment]
0.14.3 is out which should resolve this issue

**Comment by acywatson** [comment]
> 0.14.3 is out which should resolve this issue

Resolving per this comment, please lmk if not resolved.
