### ISSUE TITLE
Bug: Delete all hangs for a long time on big documents.

### ISSUE THREAD

**Issue by pmioulet** [facebook/lexical#5764]
Lexical version:

## Steps To Reproduce

1. Go to https://fr.wikipedia.org/wiki/Industrie_automobile_par_pays
2. Copy all the content
3. Paste in https://playground.lexical.dev/
4. Use the delete button to delete all the content
5. It takes a very long time to delete (while adding the content was very fast)

## The current behavior
The browser hangs with no information given to the user and it takes a very long time to delete the content.

## The expected behavior
The content should be deleted as quickly as it appeared on screen or a loading information should allow the user to know the browser has not crashed.

**Comment by pmioulet** [comment]
When we delete all the content and call root.clear() do we really need to iterate through all the elements? Could we not do something more direct?

![image](https://github.com/facebook/lexical/assets/3446555/e5f7a767-4d78-41aa-87c3-98b96ea2ce1d)

**Comment by ivailop7** [comment]
This will preserve the history stack, if you don't care about it, you can change the composeKey on LexicalComposer and it will reset everything.

**Comment by pmioulet** [comment]
Sorry, I'm not sure what you're referring to. Is there an example I could look at in the codebase by any chance? Thanks.

**Comment by ivailop7** [comment]
https://github.com/facebook/lexical/blob/fbf49e8cdfd3e719d710d8470b9cddb97f6e0f74/packages/lexical-playground/src/App.tsx#L135 add a key prop in here and modify it.

**Comment by pmioulet** [comment]
ahhh thanks, sorry i was looking for an actual attribute named composeKey in the codebase :)
