### ISSUE TITLE
Feature: Bundle on React pack with svgs

### ISSUE THREAD

**Issue by c0ncentus** [facebook/lexical#5771]
WYSIWYG editor bundle like the playground already done.

It would be nice to have 
```
import {BundleWysiwygEditorText } from "@lexical/react"
 ```

for context, I install lexical not to configure Wysig, but for the most use HTML Wisywg ready with 2 params like a regular form .
```
<BundleWysiwygEditorText onChnage input/>
```
I have Tauri app so I must link in other way ALL the svg you put in demo and it is extremly painfull to do. It might be interesting to do in css only for not having such pain and READY-To-USE philosophy in mind.

**Comment by acywatson** [comment]
Yea I think this is a common request, and something we'd love to do eventually. It does take some time and increase the surface area of things we have to maintain, though.

Lexical is first and foremost a library for building text editors, and not a full-featured text editor itself. Some assembly is required.

That being said, I appreciate your feedback here and we do hope to do this someday!
