### ISSUE TITLE
Bug: unable to save styles after importing html to editor

### ISSUE THREAD

**Issue by WoodenPC** [facebook/lexical#5775]
I have html with tags td, th, table. After importing html into the editor, styles and other attributes (align and some custom data attributes) are missing. How can I fix this problem?

Lexical version:

0.14.2

## Steps To Reproduce

1. Create html nodes that have td with styles and some custom attributes
2. Add nodes to the root node of the editor

## The current behavior

Attributes and styles are missing

## The expected behavior
Attributes and styles present in the html editor

**Comment by WoodenPC** [comment]
I figured it out. Need to create custom TableCellNode and add some login to createDOM function

**Comment by Frank-MJ** [comment]
> I figured it out. Need to create custom TableCellNode and add some login to createDOM function

hello，How did you solve it? Can you post the code?
