### ISSUE TITLE
Bug: the minified version of ESM build of @lexical/text doesn't work with vite SSR

### ISSUE THREAD

**Issue by umaranis** [facebook/lexical#5779]
Lexical version: 0.14.1 (same issue with 0.14.2 as well)

## Steps To Reproduce

1. Add the `@lexical/text package` as one of the dependencies
2. Ensure the `vite` version is 5 or higher
3. Access any of the helper functions from the `@lexical/text` package
4. Run the dev build

Link to code example: https://stackblitz.com/~/github.com/umaranis/lexical-esm-sveltekit-vanilla-js
Above is the fork of the original code example from @etrepum with the launch of ESM support in PR #5618 . I have added the `@lexical/text` dependency and called one of the support functions from the package.

## The current behavior

The vite SSR rendering fails with the following error:

```log
18:12:39 [vite] Error when evaluating SSR module /node_modules/@lexical/text/LexicalText.prod.esm.js:
|- SyntaxError: Unexpected token ':'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///home/umaranis/lexical-esm-sveltekit-vanilla-js/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:54943:28)

18:12:39 [vite] Error when evaluating SSR module /node_modules/@lexical/text/LexicalText.esm.js: failed to import "/node_modules/@lexical/text/LexicalText.prod.esm.js"
|- SyntaxError: Unexpected token ':'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///home/umaranis/lexical-esm-sveltekit-vanilla-js/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:54943:28)

18:12:39 [vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "/node_modules/@lexical/text/LexicalText.esm.js"
|- SyntaxError: Unexpected token ':'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///home/umaranis/lexical-esm-sveltekit-vanilla-js/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:54943:28)

SyntaxError: Unexpected token ':'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///home/umaranis/lexical-esm-sveltekit-vanilla-js/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:54943:28)
```

## The expected behavior
This should work without any issue.

## Potential Issue
**It seems to be an issue caused by minification (terser) as replacing the contents of `LexicalText.prod.esm.js` with `LexicalText.dev.esm.js` resolves the issue.**

**Comment by canastro** [comment]
Faced the same issue, discussed in Discord and this commit should fix it: https://github.com/facebook/lexical/commit/a4abe51ac1c8cf23f1acae461f39550f60ec43f0

**Comment by umaranis** [comment]
Thanks @canastro & @etrepum  

Any idea when can we get that released in the npm package?

**Comment by etrepum** [comment]
Should be by the end of next week, based on what I've seen from maintainers on the discord.

**Comment by etrepum** [comment]
0.14.3 is out which should resolve this issue
