### ISSUE TITLE
Bug: Incorrect Table Of Contents Order

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#5792]
Lexical version: 0.14.2

When the heading is within a table, collapsible section or any other type of Element Node, the order inside the Table Of Contents is incorrect and it appends the new headings to the top, rather than in the correct position order.

https://github.com/facebook/lexical/assets/7893468/59424954-9d9c-495a-86bd-bb56b51b0af3

**Comment by StyleT** [comment]
IMO headings from within tables shall not appear within TOC :P 
It's hard to come up with a sane reason for this to be a valid use case. But I may be terribly wrong.

**Comment by ivailop7** [comment]
@KatsiarynaDzibrova is working on this one

**Comment by ivailop7** [comment]
Was fixed in https://github.com/facebook/lexical/pull/5946
