### ISSUE TITLE
Feature: Add `createDocumentJSON` Function in @lexical/file for Generating `.lexical` JSON in Headless Environments

### ISSUE THREAD

**Issue by matsuyama-k1** [facebook/lexical#5796]
I have a trouble during creating a AWS lambda function to generate a `.lexical` formatted JSON file from a yjs shared type(YDoc).
The existing `exportFile` function in the `@lexical/file` package is designed for browser environments and includes functionality for downloading files, which is not suitable for my headless environment needs.
So I wrote function that make `.lexical` alternatively but I concern about the long-term compatibility.

https://github.com/facebook/lexical/blob/5d61ab28edcd8ffe44e5411dcdf089e44dae4bc9/packages/lexical-file/src/fileImportExport.ts#L66

So I want  `createDocumentJSON` function in the `@lexical/file` package. This function should enable the export of .lexical compatible JSON specifically for headless environments like below.
```
createDocumentJSON(editor, config): DocumentJSON
```

**Comment by etrepum** [comment]
`serializedDocumentFromEditorState` from #6028 does this
