### ISSUE TITLE
Bug: Inserting a table from  "Clickup" can lead to Lexical crash

### ISSUE THREAD

**Issue by denindka** [facebook/lexical#5812]
Lexical version: - 0.14.2

## Steps To Reproduce

1. Go in "Clickup", insert a table and copy it
2. Paste it into Lexical
3. Go to some cell with text
4. Press Enter(new line)
5. Lexical is crashing

https://github.com/facebook/lexical/assets/20279408/048c3643-91bb-4e6a-af7c-d96e91408d58

**Comment by StyleT** [comment]
Hi! 
Can you provide any other way to reproduce this issue for those who doesn't have clickup.com account?

**Comment by denindka** [comment]
Hi! of course here an attachment
[Playground 2024-04-08T07_26_04.935Z.lexical.zip](https://github.com/facebook/lexical/files/14902295/Playground.2024-04-08T07_26_04.935Z.lexical.zip)

**Comment by Sahejkm** [comment]
closing this as it should be fixed now
