### ISSUE TITLE
Bug: INSERT_CHECK_LIST_COMMAND doesn't work from @lexical/list

### ISSUE THREAD

**Issue by mdmuhtasimfuadfahim** [facebook/lexical#5821]
## Description:

I have tried `packages/lexical-playground` code in my project. I have implemented some needed plugins for my project. But lexical `Check list` is not working. But others are working in that dropdown.

Lexical version: 0.14.2

## Method used:

I am using the below function to show the `check list`:

```
const formatCheckList = () => {
  if (blockType !== 'check') {
    editor.dispatchCommand(INSERT_CHECK_LIST_COMMAND, undefined);
  } else {
    formatParagraph();
  }
};
```

This doesn't work for me. But if I use another command like `INSERT_ORDERED_LIST_COMMAND` in this function. This works perfectly. But the `INSERT_CHECK_LIST_COMMAND` doesn't work. Please help me with the solution and thanks in advance.

**Comment by informsharique** [comment]
I'm also facing the same issue.

**Comment by mdmuhtasimfuadfahim** [comment]
@etrepum Yes. Because I didn't find anything called <CheckboxPlugin />
