### ISSUE TITLE
Bug: IS_IOS, IS_SAFARI, IS_APPLE_WEBKIT, CAN_USE_BEFORE_INPUT not found in lexical import errors

### ISSUE THREAD

**Issue by lsbyerley** [facebook/lexical#5827]
```
export 'IS_IOS' (imported as 'IS_IOS') was not found in 'lexical'
export 'IS_SAFARI' (imported as 'IS_SAFARI') was not found in 'lexical'
export 'IS_APPLE_WEBKIT' (imported as 'IS_APPLE_WEBKIT') was not found in 'lexical' 
export 'CAN_USE_BEFORE_INPUT' (imported as 'CAN_USE_BEFORE_INPUT') was not found in 'lexical'
```

Lexical version: 0.14.2

## Steps To Reproduce

1. Upgrade from 0.13.1 to 0.14.2 results in the above errors during build

## The current behavior
- The 4 import errors above are shown in the build logs

## The expected behavior
- No import errors

**Comment by lsbyerley** [comment]
@2wheeh Yes, we are still observing these import errors on 0.14.3

**Comment by ivailop7** [comment]
These were never exported, they've always been in the shared folder for the Playground, which was never packaged. Copy-pasting is the current method. I do agree it makes sense to be part of the lexical-utils package.

**Comment by etrepum** [comment]
I would also like to see these be exported, I copied them into a project I worked on because I basically had a hybrid of registerPlainText and registerRichText and they both depend on these constants.

For what it's worth, here are the private imports used by those implementations:

`packages/lexical-rich-text/src/index.ts`
```typescript
import caretFromPoint from 'shared/caretFromPoint';
import {
  CAN_USE_BEFORE_INPUT,
  IS_APPLE_WEBKIT,
  IS_IOS,
  IS_SAFARI,
} from 'shared/environment';
```

`packages/lexical-plain-text/src/index.ts`
```typescript
import {
  CAN_USE_BEFORE_INPUT,
  IS_APPLE_WEBKIT,
  IS_IOS,
  IS_SAFARI,
} from 'shared/environment';
```

**Comment by ivailop7** [comment]
> I would also like to see these be exported, I copied them into a project I worked on because I basically had a hybrid of registerPlainText and registerRichText and they both depend on these constants.
> 
> For what it's worth, here are the private imports used by those implementations:
> 
> `packages/lexical-rich-text/src/index.ts`
> 
> ```ts
> import caretFromPoint from 'shared/caretFromPoint';
> import {
>   CAN_USE_BEFORE_INPUT,
>   IS_APPLE_WEBKIT,
>   IS_IOS,
>   IS_SAFARI,
> } from 'shared/environment';
> ```
> 
> `packages/lexical-plain-text/src/index.ts`
> 
> ```ts
> import {
>   CAN_USE_BEFORE_INPUT,
>   IS_APPLE_WEBKIT,
>   IS_IOS,
>   IS_SAFARI,
> } from 'shared/environment';
> ```

Feel free to raise a PR, happy to move it forward
