### ISSUE TITLE
Bug: Delete a row in the table Delete

### ISSUE THREAD

**Issue by chaihan** [facebook/lexical#5854]
Lexical version:0.14.3

## Steps To Reproduce

1.Create a 5x5 table (not the experimental) in the Lexical Playground.
2.Merge the first four rows of cells in the first column
3.Merge the first three rows of cells in the third column
4.Delete the third row

Link to code example:

## The current behavior
1.
![11](https://github.com/facebook/lexical/assets/70357130/e3659e3d-4bed-4c83-99f5-be6418f507f8)
2.
![22](https://github.com/facebook/lexical/assets/70357130/9f1ac76e-6dbf-405f-adb5-05ee699e0d9e)
3.
![33](https://github.com/facebook/lexical/assets/70357130/4fccae4f-d199-40de-9300-f27345345d73)
4.
![44](https://github.com/facebook/lexical/assets/70357130/768d7f90-04fc-47e5-8dd4-b426af570dc9)

## The expected behavior
Table rows can be deleted normally, and the table content is not disordered

**Comment by ivailop7** [comment]
Still valid as of 0.16.0

**Comment by chaihan** [comment]
Will this issue be fixed later

**Comment by chaihan** [comment]
> Still valid as of 0.16.0

Will this issue be fixed later

**Comment by etrepum** [comment]
This bug still reproduces. It should be straightforward to fix at this point though.
