### ISSUE TITLE
Bug: convertToMarkdownString removes nested list

### ISSUE THREAD

**Issue by Eklinden** [facebook/lexical#5873]
After i convert the node to markdown, it removes nested <ul> elements.
This is how i use the convertToMarkdownString
`import { $convertToMarkdownString, TRANSFORMERS } from '@lexical/markdown';`
`
let md = editorState.read(() =>
    $convertToMarkdownString(
      TRANSFORMERS
    )
  );
`
NOTE: The images of logs is of logs of the variable, editorState
This is how the message is structured **before** the markdown:
<img width="594" alt="Screenshot 2024-04-11 at 2 30 11 PM" src="https://github.com/facebook/lexical/assets/76260367/19a4cae6-9643-4d8d-a84e-78164a33e433">

and after the convert, the output is:
"- helloworld"
When i want it to be
"- hello
"  - world
Node that "hello" was in the first TextNode and "world" was in the second TextNode in the nested list.
It looks like the convertToMarkdownString just smashes them together. 

The message structure after i save the converted markdown:
<img width="590" alt="Screenshot 2024-04-11 at 2 31 02 PM" src="https://github.com/facebook/lexical/assets/76260367/a5acf39b-0232-49f6-a83c-fe1252efc038">

Lexical version: 0.12.2

## Steps To Reproduce

1. Have a message that is structured like
`<ul><li><span>hello</span><ul><li><span>world</span></li></ul></li></ul>`
2. Convert that message to markdown

**Comment by p-christ** [comment]
yes how do we solve this problem?

**Comment by fantactuka** [comment]
It works just fine on a playground, feel free to reopen with more details:


https://github.com/user-attachments/assets/f51f511c-4633-4b38-a645-fc5deba1e284
