### ISSUE TITLE
Bug: Links don't follow Link style if text formatting is applied

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#5893]
Lexical version: 0.14.3

## Steps To Reproduce

Type any text, add a link, select the text and the link, change the color to 'red'. The link also changes color, rather than keep the 'link' styling defined in the theme object. Reason is, the 'span' inside the anchor tag takes the applied color and overrides the link style CSS.

## Expected behaviour

Despite the applied styling, for the link to keep the defined link theme style.

**Comment by ivailop7** [comment]
Can be achieved by overriding the CSS class directly. Closing.

**Comment by DyNamite-TNT-1** [comment]
Hi @ivailop7, I am facing to this issue. Can you show me how to solve this in detail?

**Comment by ivailop7** [comment]
Just add a CSS class matching your link class name:

.yourLinkClassName span {
  color:....
}

**Comment by DyNamite-TNT-1** [comment]
> Just add a CSS class matching your link class name:
> 
> .yourLinkClassName span { color:.... }

That's really simple! Thank you @ivailop7
