### ISSUE TITLE
Bug: @lexical/react 0.14.4 brings in @lexical/devtools-core dependency without declaring it

### ISSUE THREAD

**Issue by etrepum** [facebook/lexical#5901]
Lexical version: 0.14.4

## Steps To Reproduce

1. Update a project to @lexical/react 0.14.4 without adding @lexical/devtools-core as a dependency
2. Try and build or run the project

Link to code example:

https://github.com/etrepum/lexical-esm-nextjs but anything that imports @lexical/react/LexicalTreeView should demonstrate the problem

## The current behavior

Tries to import from @lexical/devtools-core which is not published yet

## The expected behavior

It should not import @lexical/devtools-core, or that package should be published and @lexical/react should have a dependency on it

## Root cause

[blame of packages/lexical-react/src/LexicalTreeView.tsx](https://github.com/facebook/lexical/blame/main/packages/lexical-react/src/LexicalTreeView.tsx) shows that this was last added in this commit: https://github.com/facebook/lexical/commit/c0cca39759172d5fa51f49842f39ab75c7adc767

**Comment by StyleT** [comment]
It's a bummer :( Let me take a look

**Comment by etrepum** [comment]
#5876 should take care of the build and publish scripts (and the fix to update-version to handle devDependencies is in there too). There is of course some risk in making large changes to them, but the build is broken or at least fragile anyway…

**Comment by etrepum** [comment]
The v0.14.5 release fixes this with next.js, I will verify that the other minimal framework examples still work and confirm shortly

**Comment by etrepum** [comment]
Confirmed that v0.14.5 is working with my sveltekit and astro examples as well! Closing as fixed 💯
