### ISSUE TITLE
Refactor: Move AutoCompleteNode styling to theme.

### ISSUE THREAD

**Issue by mrAJAY1** [facebook/lexical#5943]
![image](https://github.com/facebook/lexical/assets/88980778/8ba05023-a48a-4c1d-a4f7-ede4a742b9e2)

Move the `AutoCompleteComponent` used by `AutoCompleteNode` styling to the theme instead of using inline styling. 
This issue is based on the TODO comment found in the code.

* Currently working on this issue.

**Comment by ivailop7** [comment]
Fixed
