### ISSUE TITLE
Bug: LexicalClipboard pasting over mention crashes Chrome

### ISSUE THREAD

**Issue by danielbuechele** [facebook/lexical#5950]
Lexical version: 0.14.5

## Steps To Reproduce

1. Open Lexical Playground in Chrome and add an @-mention
2. Copy some any text to your clipboard
3. Create a selection that starts at the beginning of the @-mention (it can end within, at the end or after the mention)
4. Now paste from clipboard

## The current behavior

In most cases this crashes Chrome, in rare cases it only takes very long and produces a warning `[Violation] 'paste' handler took 95275ms`. This affects up-to-date Chrome on macOS and Windows. Safari on macOS is not affected.

In a case where Chrome wasn't entirely crashing I was able to take this performance trace (sorry, I only took a screenshot instead of exporting the trace)
<img width="1535" alt="image" src="https://github.com/facebook/lexical/assets/685740/2f2b9a3f-a8cc-41ba-81f9-12a3704295e7">

**Comment by ivailop7** [comment]
I reproduced. Wow!

**Comment by thegreatercurve** [comment]
Closed by #5956
