### ISSUE TITLE
Bug: Selection is removed when changing style of 2 different nodes

### ISSUE THREAD

**Issue by Danidude** [facebook/lexical#6008]
Lexical version: latest (02 May 2024)

## Steps To Reproduce

1. Select text with two different stylings
2. Choose one new style for them both
3. Selection is put at start of selected area.

Link to code example:

https://github.com/facebook/lexical/assets/1169254/d78d18bc-3f41-43cb-8558-9817388d20c1

## The current behavior
Selection is removed

## The expected behavior
Keep the selected area

**Comment by uniqueeest** [comment]
Hello! @StyleT, I'm interested in this issue. Can I try to solve it?

**Comment by StyleT** [comment]
Hi! Sure! Go ahead ;)
