### ISSUE TITLE
Bug: Cursor jumps to the end of the document after undo checkbox adding

### ISSUE THREAD

**Issue by KatsiarynaDzibrova** [facebook/lexical#6010]
Cursor jumps to the end of the document after undo checkbox adding. Only reproducible when collaboration mode is on 

Lexical version: v0.14.5

## Steps To Reproduce

1. Launch playground with collaboration mode on
2. Add several paragraphs
3. Add checkbox in between paragraphs
4. Undo

## The current behavior
![checkbox-cursor](https://github.com/facebook/lexical/assets/47710336/5884b134-6a57-41bb-ab9c-f2edb0820449)

## The expected behavior
Cursor stays where undo was done

**Comment by KatsiarynaDzibrova** [comment]
Similar issues are mentioned in #4846

**Comment by StyleT** [comment]
Also related: #5975 #5974

**Comment by CARPEDIEM05** [comment]
Hey, I am working on it.

**Comment by StyleT** [comment]
Closed in #6070

**Comment by matsuyama-k1** [comment]
Is it ok to copy&paste codes from other pull request already exists?
If it is ok with rule of Lexical.js but I have bad feeling now.

mine
https://github.com/facebook/lexical/pull/5975/files#diff-3d291634235852090f5aa491928d6d43fa366302bf0222b0629adf3580e64ab2R549

yours
https://github.com/facebook/lexical/pull/6070/files#diff-3d291634235852090f5aa491928d6d43fa366302bf0222b0629adf3580e64ab2R552
