### ISSUE TITLE
Feature: picker active state on devtool UI 

### ISSUE THREAD

**Issue by 2wheeh** [facebook/lexical#6068]
Currently, devtool  doesn't reflect picker state on `EditorInspectorButton`.

I think It would be better if it reflects pickerActive state on UI.

For example:

https://github.com/facebook/lexical/assets/40269597/cf114ea3-1cb0-4ee5-a0c9-4c9eaaba4405

**Comment by H0onnn** [comment]
@StyleT Hello ! Can I solve this problem ?

**Comment by 2wheeh** [comment]
@H0onnn Hi I worked this on #6077 😿

**Comment by StyleT** [comment]
Closed with https://github.com/facebook/lexical/pull/6077 will be released with the next extension update
