### ISSUE TITLE
Feature: Git Checks for running test.yml workflows and size.yml workflows are getting skipped for PRs

### ISSUE THREAD

**Issue by Sahejkm** [facebook/lexical#6074]
Recently the git checks from test.yml are flaky and getting skipped on PR updates few times
Example PR: https://github.com/facebook/lexical/pull/6056/checks

Could be various reasons as per https://stackoverflow.com/questions/77996177/how-can-i-handle-a-required-check-that-isnt-always-triggered

**Comment by etrepum** [comment]
I noticed this as well, it seemed to start around https://github.com/facebook/lexical/pull/6071 or https://github.com/facebook/lexical/pull/6056 - I don't believe that it has anything to do with the workflow configuration but also I haven't seen anything on https://www.githubstatus.com/ about this

**Comment by etrepum** [comment]
I think that the checks that are running are not workflow based at all, but are instead triggered by webhooks to other services

**Comment by etrepum** [comment]
I suspect that someone with a high enough access level on the repo or org has to tick some boxes or solve a billing issue to get workflows going again

**Comment by ivailop7** [comment]
Gerard took care of it

**Comment by Sahejkm** [comment]
think 
- still need this to move more tests from e2e to unit wherever possible, so that we don't face budget restraints in future, 
- Nicole / Bob / Acy are also helping in optimising the git workflows for future.
