### ISSUE TITLE
Feature: Deprecate default exports from public entrypoints (or at least give every module named exports)

### ISSUE THREAD

**Issue by etrepum** [facebook/lexical#6079]
The following modules use default exports in their entrypoints, which is inconsistent with the rest of the monorepo:

* packages/lexical-react/src/LexicalClickableLinkPlugin.tsx
* packages/lexical-react/src/LexicalErrorBoundary.tsx
* packages/lexical-react/src/LexicalTableOfContents.tsx
* packages/lexical-react/src/useLexicalEditable.ts
* packages/lexical-react/src/useLexicalSubscription.ts

There are other reasons not to use default exports (e.g. the types are wrong in cjs, the module names are not always consistent with what we call them in OSS docs for www reasons, etc.) but I think inconsistency is a good enough reason.

I propose that we, at minimum:

- Add named exports in all of these cases

Bonus points if we can agree to:

- Mark default exports as `@deprecated`
- Add a lint rule to warn when new default exports are added to public entrypoints (at least for packages/lexical-react/ where it has happened several times and has the most impact, everything else is a barrel file or not really API code like lexical-eslint)

**Comment by StyleT** [comment]
@etrepum Hi! Can we close this?

**Comment by etrepum** [comment]
@StyleT yes, it did not get closed because of a bug in the issue template that's fixed by #6124
