### ISSUE TITLE
Bug: pasting via Context menu (right-click menu) changes selection which creates all sorts of issues

### ISSUE THREAD

**Issue by gigantedocil** [facebook/lexical#6106]
If you paste via the Context menu the selection underneath the menu changes and all sort of weird issues happen.

Lexical version: 0.15.0 (latest)

## Steps To Reproduce

https://github.com/facebook/lexical/assets/18426489/d0dd535c-48fb-4ec1-9e56-c4f57369637c

Link to code example:

n/a

## The current behavior

Pasting via the Context menu changes the selection underneath the menu creating all sorts of weird behaviours.

## The expected behavior

Pasting via the Context menu should not change the selection underneath the menu.

**Comment by ivailop7** [comment]
I can repro, need to pin down the commit when this got broken.

**Comment by gigantedocil** [comment]
@ivailop7, not sure if this is helpful but this is also happening on v0.11.3.

In addition to that, I forgot to mention that I reproduced this via the trackpad which involves pressing two fingers to achieve the right-click that brings up the context menu. I have a feeling that lexical interprets that as 2 clicks and that's what's making the selection change. It's possible that with a regular mouse that has a left and right button, pressing the right button won't have this behaviour.

**Comment by ivailop7** [comment]
Thank you for the clarification. There should be no difference between ctrl-v and a context menu paste. Worth investigating for sure.

**Comment by ivailop7** [comment]
Fixed
