### ISSUE TITLE
Bug: Insert an image inside another image's caption

### ISSUE THREAD

**Issue by MaxPlav** [facebook/lexical#6109]
Currently, a user can insert an image inside another image's caption which may cover up or deface the original image.
Probably a variety of elements that can be inserted in an image's caption should be limited.

Lexical version:

## Steps To Reproduce

1. Open https://playground.lexical.dev/ in Chrome
2. Insert a sample image
3. Click on the image caption
4. Go to the Toolbar and insert "Image"
5. Select from "URL".
6. Insert a new image URI.
7. See that the new image covers the original one.

## The current behavior

https://github.com/facebook/lexical/assets/5062807/efb8e972-6d74-4f86-b2b1-d61cd4ed3794

## The expected behavior
A user is not able to insert an image into the caption.

**Comment by StyleT** [comment]
IMO, we shall be running there nested editor that supports only basic rich text (see `examples/react-rich` setup). Maybe even plain text only?

**Comment by rabelmervin** [comment]
Hi Maxplav, I'm Rabel Mervin, I'm reaching out because I'm interested in contributing this project
Could you please provide me any processes I should follow to solve this Issue ?

**Comment by StyleT** [comment]
> Hi Maxplav, I'm Rabel Mervin, I'm reaching out because I'm interested in contributing this project Could you please provide me any processes I should follow to solve this Issue ?

Hi! You can start here: https://github.com/facebook/lexical/blob/main/CONTRIBUTING.md

**Comment by rabelmervin** [comment]
Thanks @StyleT for your help.
