### ISSUE TITLE
Feature: Change size-limit action to measure something more meaningful than the core modules

### ISSUE THREAD

**Issue by etrepum** [facebook/lexical#6137]
The size-limit workflow, as currently configured, has the following deficiencies:

* It only reports changes, it does not enforce any hard limits
* There is no documentation for what these limits should be, currently just vibes based(?) other than the intro docs which say "The core package of Lexical is only 22kb in file size (min+gzip)" which is no longer true, at least w/o further processing it's 30kb (see below)
* It only measures the prod+cjs builds of three modules: `lexical`, `@lexical/plain-text`, and `@lexical/rich-text`
* Notably this does not consider any relationship with dependencies that are meant to be external (yjs, y-websocket, react, react-dom, etc.), dependencies that are meant to be bundled (prism in `@lexical/code`), or anything that involves a significant code transform (other than dead-code elimination of `__DEV__`)

```
$ cat node_modules/lexical/Lexical.prod.js | gzip | wc -c
   30746
```

See also:
* #6132
* https://github.com/facebook/lexical/pull/6133#issuecomment-2118312061

**Comment by etrepum** [comment]
It might also be worth thinking about removing the running time measurements because they are so incredibly noisy in this CI environment. See https://github.com/facebook/lexical/pull/6143#issuecomment-2120500275 which made no change to any code that size-limit can see (the www build is not used in this scenario) but is reporting >20% changes to runtime on two of the three modules. I think errors of this magnitude makes the numbers counter-productive because people may spend time investigating phantom performance regressions.

**Comment by Sahejkm** [comment]
Hi @etrepum do you think we can close this issue right now ? Or do we need to have hard limits of failing the build once it cross a threshold ? Or any other package you think we should include in the size check before closing this ?
