### ISSUE TITLE
Bug: Uncommented Code in Getting Started with React Docs (https://lexical.dev/docs/getting-started/react)

### ISSUE THREAD

**Issue by hkiame** [facebook/lexical#6142]
Following the official Lexical documentation's guide on ["Getting Started with React"](https://lexical.dev/docs/getting-started/react), there seems to be an issue with the provided code snippet.

## Steps To Reproduce

1. Navigate to the [Lexical documentation page](https://lexical.dev/docs/getting-started/react)
2. Locate the section titled "Creating Basic Rich Text Editor".
3. The code example within this section appears to have uncommented code sections denoted by ...
```js
const theme = {
  // Theme styling goes here
  ...
}
```

## The current behavior
The presence of uncommented code (...) disrupts the code flow and might lead to errors or unexpected behavior when users try to copy and use the example directly in their projects.

## The expected behavior
The code snippet should be a complete and functional example. Any sections intended to be omitted should be clearly commented out using // comments to avoid confusion and ensure users can easily copy and use the provided code.

```js 
const theme = {
  // Theme styling goes here
  // ...
}
```

**Comment by etrepum** [comment]
A full theme configuration is over 30 lines long, it's done that way for brevity. Full example projects are available for people that just want to copy something, and one is below that section on the same page.

**Comment by hkiame** [comment]
Hi @etrepum . Maybe you didn't understand what I was saying. I am talking of the spread operator not being commented out thus causing a minor bug when you copy the code. Such minor bug can be hard to find sometime.

<img width="697" alt="image" src="https://github.com/facebook/lexical/assets/18514607/924ca278-f6b6-4a1a-bfae-83ffff669b87">
