### ISSUE TITLE
Bug: AutoLink Styling lost on the last character in the link

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#6155]
Lexical version: 0.15.0

https://github.com/facebook/lexical/assets/7893468/8758bab8-31f8-4636-8001-0479166d2897

The issue was introduced with the PR for fixing the styling, but it doesn't apply to the last character.

For @Shubhankerism to fix.

**Comment by StyleT** [comment]
@MaxPlav FYI ^^
