### ISSUE TITLE
Refactor HTMLCopyAndPaste e2e tests

### ISSUE THREAD

**Issue by potatowagon** [facebook/lexical#6164]
`packages/lexical-playground/__tests__/e2e/CopyAndPaste/html/HTMLCopyAndPaste.spec.mjs`

Refactor these tests to specify expected input output, example: `packages/lexical-playground/__tests__/e2e/CodeBlock.spec.mjs`

**Comment by vantage-ola** [comment]
@potatowagon I want to pick up this issue :) 
what does it entail?

**Comment by potatowagon** [comment]
apologies, its an old issue and comparing CodeBlock.spec.mjs vs HTMLCopyAndPaste.spec.mjs, i cant see any difference, so i could have linked the wrong example. im guessing this may be what i wanted to refer to https://github.com/facebook/lexical/blob/main/packages/lexical/src/__tests__/unit/CodeBlock.test.ts#L115

then again, this is a unit test while HTMLCopyAndPaste is an e2e test that includes user actions so not sure how applicable it is. ill close this issue since i cant rmb the context either
