### ISSUE TITLE
Bug: `$convertFromMarkdownString` places caret at the end of the document (instead there should be a default way of pasting long markdown without scrol-downs due to caret at the end)

### ISSUE THREAD

**Issue by vadimkantorov** [facebook/lexical#6177]
Even at https://playground.lexical.dev/ the caret on load is at the end of the document.

When a document is long, this forces overflow to happen (especially if a hyperlink is at the last line of the document, so a tooltip is rendered and overflow/scrolling is happening), and in general, on document load (from markdown as well) we expect caret to be at the top

In the meanwhile, would you have an advise how to work around this and force the cursor to not jump to the end?

Thanks!

![image](https://github.com/facebook/lexical/assets/1041752/5b1668c7-5243-444f-a597-61058d6317b9)

**Comment by etrepum** [comment]
```
$convertFromMarkdownString(…);
$getRoot().selectStart();
```

**Comment by potatowagon** [comment]
by caret do u mean cursor? if u mean caret (^), i dont see a caret anywhere on  https://playground.lexical.dev/ .
if u mean cursor, why does the cursor need to be at the start of the document?

**Comment by vadimkantorov** [comment]
I meant the cursor, yes: 
![image](https://github.com/facebook/lexical/assets/1041752/14ef5dff-c2ad-4179-8b98-45b1153226b2)

Well, if it's a long document, placing the cursor at the end of the document when importing Markdown leads to a scroll-down/jump-down of the browser window. I'd like to prevent this jump-down from happening (and keep the cursor at the document start when importing markdown). How can I achieve that?

In the meanwhile I'll do `$getRoot().selectStart();`, but I fear that this will still have the jump down-up visible.

**Comment by vadimkantorov** [comment]
Invoking `$getRoot().selectStart();` immediately after `$convertFromMarkdownString` worked as a workaround. My proposal would be to add sth like this directly to `$convertFromMarkdownString` (for long documents auto-scroll-down on Markdown import is strange)

**Comment by etrepum** [comment]
The current behavior seems to be modeled after what would happen if the entire target element node (the root by default) was selected and then the markdown document was pasted in (the target node is cleared and the end of the new content is selected afterwards). Selecting the end is a deliberate choice at least as the code is written today.

A good start would be to document what this function does. I wouldn't expect it to clear the node or change the selection from the name alone. If I didn't know better, I'd expect to get an array of nodes without any document mutations.

**Comment by potatowagon** [comment]
@etrepum @vadimkantorov  based on the conclusion let me know if i can close this issue

**Comment by vadimkantorov** [comment]
@potatowagon I think the issue still exists in the sense that `$convertFromMarkdownString` modifies the place of the caret which leads to page scroll-down when importing a long markdown.

I agree with @etrepum - I think by default importing markdown should be neutral / not modify the caret place (and cause scroll-downs)

**Comment by potatowagon** [comment]
https://github.com/facebook/lexical/pull/4232

> when selection is present we still want to restore it, otherwise we risk facing the lost selection invariant.

^ selecting the end is deliberately done for the above reason

**Comment by potatowagon** [comment]
seems like we need to do a selection to prevent lost selection invariant.

in this PR the selection is changed from end to start and documentation added: https://github.com/facebook/lexical/pull/6220

tho im unsure what is the best way forward as there may still be the "jumping cursor" problem faced in this issue: instead of cursor jumping to end, it jumps to start

@wdyt @etrepum ?

**Comment by etrepum** [comment]
If I were to design this API I would have it return an Array of parsed nodes that have not been inserted into the document yet and the user can decide how/where to insert and what to do about the selection (and clearing the target element node or not).

For this API in particular I think the best thing to do would be to write some documentation describing the current behavior, it's easy enough to manually select the beginning or the end as long as you know that's expected. The decision of beginning or end is arbitrary, and maybe you don't want to change the selection at all if the target node isn't the root and the selection was elsewhere. I don't think there's one correct answer for this API as currently designed.

**Comment by lukasb** [comment]
FYI to whoever picks this up - in addition to the selectEnd() in createMarkdownImport, there are .select() operations in some of the Markdown transformers that can cause focus stealing, eg listReplace.
