### ISSUE TITLE
Bug: Table column context menu is shown way below (and even out of the editor viewport)

### ISSUE THREAD

**Issue by vadimkantorov** [facebook/lexical#6184]
![image](https://github.com/facebook/lexical/assets/1041752/c29ed5d4-1445-4841-aa0b-7e7ef9e8949f)

**Comment by ivailop7** [comment]
Every time this is fixed, it breaks Meta internally, my last attempt was: https://github.com/facebook/lexical/pull/5791, then that part was reverted here: https://github.com/facebook/lexical/pull/5859/files if someone else wants to go for another fix, they are welcome.

**Comment by wenbert** [comment]
This also happens to context menu in the playground.
<img width="1465" alt="screenshot_2024-10-04 23-30-11" src="https://github.com/user-attachments/assets/8b216862-360a-4dd7-8aed-c4debcc7b523">

**Comment by etrepum** [comment]
Duplicate of #4529
