### ISSUE TITLE
Bug: This is a bug that occurs when deleting table columns after selecting multiple cells.

### ISSUE THREAD

**Issue by eleganceJoo** [facebook/lexical#6221]
## The current behavior
1. Add a table.
2. Select multiple cells.
3. Delete column.
4. I can't control the screen.

## The expected behavior
I need to be able to control the screen.

### Attached is a recorded video.
https://github.com/facebook/lexical/assets/157095195/d7f9b7de-3b36-4d62-9298-41e1f69d2f21

**Comment by ivailop7** [comment]
Validated, I can reproduce
```
Uncaught Error: updateEditor: selection has been lost because the previously selected nodes have been removed and selection wasn't moved to another node. Ensure selection changes after removing/replacing a selected node.
```
