### ISSUE TITLE
Proposal: Upstream more of `PLAYGROUND_TRANSFORMERS` (package `lexical-playground`) to `TRANSFORMERS` (package `lexical-markdown`)

### ISSUE THREAD

**Issue by vadimkantorov** [facebook/lexical#6276]
I'm calling `$convertFromMarkdownString` like following:

```js
            editorRef.current?.update(() => {
                const editorState = editorRef.current?.getEditorState()
                if (editorState != null) {
                    $convertFromMarkdownString(markdown, TRANSFORMERS)
                    $getRoot().selectStart()
                }
            })
```

Normally it renders markdown correctly on the first calling, but not for images:
```
# hello world

![](https://raw.githubusercontent.com/vadimkantorov/moncms/gh-pages/assets/cat-typing.29244fe9.gif)
```

gets rendered as 
![image](https://github.com/facebook/lexical/assets/1041752/57475e27-ff59-4f6b-b464-56edc80d91f7): 

header is rendered correctly, but not the image. It is important for markdown documents with images to be rendered correctly on the first go (also setting `<img src="https://raw.githubusercontent.com/vadimkantorov/moncms/gh-pages/assets/cat-typing.29244fe9.gif" height="100px" />` does not seem to be recognized/rendered by the Lexical's markdown plugin, right?).

If I then click on `M↓` twice, the images gets then rendered. How can I render it directly on the first go? (also when clicking `M↓` twice, the caret jumps to the end which may cause unneeded scroll-downs)

This problem is relevant for both v0.12.5 and v0.16.0

Thanks!

**Comment by vadimkantorov** [comment]
So the problem was in using `TRANSFOMERS` from https://github.com/facebook/lexical/blob/main/packages/lexical-markdown/src/index.ts instead of `PLAYGROUND_TRANSFORMERS` from https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts

**Comment by vadimkantorov** [comment]
But HTML images `<img src="https://raw.githubusercontent.com/vadimkantorov/moncms/gh-pages/assets/yellow-flower.a2a7c7a2.jpg" height="100px"/>` are still not being rendered/recognized even with `PLAYGROUND_TRANSFORMERS`

**Comment by fantactuka** [comment]
If we move image into default transformers it'll introduce dependency on ImageNode, which is not part of the core and often very product-specific. That's why it hasn't been added

**Comment by etrepum** [comment]
When/if ImageNode is published in an npm package, this might make sense, but in the meantime there really just isn't a way for this to work.
