### ISSUE TITLE
Feature: support custom generateRandomKey by editor initialConfig generateRandomKey:()=>string

### ISSUE THREAD

**Issue by 1yasa** [facebook/lexical#6313]
https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalUtils.ts#L83

We achieve minimal cost data synchronization by storing each lexical node individually in a database (a modern rich text architecture should support this).

Therefore, each node's key is a unique snowflake ID generated by an algorithm.

**Comment by agscripter** [comment]
Agree. We also need this feature.

**Comment by etrepum** [comment]
The chances of this feature being added are very low, but you can maintain your own map of editor keys to unique ids. For example, a module global `WeakMap<Editor, Map<NodeKey, YourCustomId>>` where given an editor and a node key you can create or look up whatever sort of id you want.
