### ISSUE TITLE
Table Bug: Cursor goes horizontal after deleting text below it

### ISSUE THREAD

**Issue by flying-falcon** [facebook/lexical#6315]
Problem : Cursor goes horizontal after deleting text below it

Lexical version: latest

## Steps To Reproduce

1. Insert a table in https://playground.lexical.dev/ 
2. add text below it.
3. Delete text below.
4. go to table last cell.
5. Goto next line.

Link to code example: https://playground.lexical.dev/

## The current behavior

https://github.com/facebook/lexical/assets/14221696/da2492db-b304-455d-bf1b-e75613fcb960

## The expected behavior
Cursor should be vertical.

**Comment by ivailop7** [comment]
This is the correct behaviour, because there is no paragraph under the table, which is why the block cursor exists to signify areas between widgets that don't have paragraph spacing between them, or in this case are at the end of the document.
