### ISSUE TITLE
Bug: embedded stackblitz examples are not possible to run on Safari

### ISSUE THREAD

**Issue by 2wheeh** [facebook/lexical#6322]
## Steps To Reproduce

1. go to https://lexical.dev on Safari (mac, ios)
2. click any embedded stackblitz example to run

## The current behavior

<img width="936" alt="image" src="https://github.com/facebook/lexical/assets/40269597/73c5e206-3e61-4ee0-919f-5309e5bc8111">

## The expected behavior

It should work.

**Comment by etrepum** [comment]
https://developer.stackblitz.com/platform/webcontainers/browser-support#embedding

> Projects based on WebContainers can be [embedded](https://developer.stackblitz.com/guides/integration/embedding) as any other StackBlitz project. However, the [restrictions detailed above](https://developer.stackblitz.com/platform/webcontainers/browser-support#web-platform-requirements) hit harder when embedding a project since we no longer control the headers under which the embedding content is served.
>
> For that reason, we only support embedding WebContainers-based projects in Chromium-based browsers.
