### ISSUE TITLE
Bug:  $convertFromMarkdownString followed by $convertToMarkdownString yields different markdown.

### ISSUE THREAD

**Issue by orelbn** [facebook/lexical#6325]
Starting and ending spaces are preserved when converting paragraph nodes to Markdown, but spaces are [trimmed](https://github.com/facebook/lexical/blob/772520509308e8ba7e4a82b6cd1996a78b3298d0/packages/lexical-markdown/src/MarkdownImport.ts#L113) when converting from Markdown.

My use case: I am trying to detect changes by checking the saved markdown value (calling convertToMarkdown on editor content) versus the current markdown value (calling convertFromMarkdown to get the editor content followed by calls to convertToMarkdown to check the markdown value of the current content)

Lexical version: 0.16.0

## Steps To Reproduce

Playground:
1. Add whitespace to the end or start of paragraph node. 
![image](https://github.com/facebook/lexical/assets/77707952/76738b77-325e-43dd-ba83-993c0fb4edfe)
2. Press convert from markdown
![image](https://github.com/facebook/lexical/assets/77707952/e089ab36-d5ad-462d-9fb8-81c30f069697)
3. Press convert from markdown again.
4. The content is different.
![image](https://github.com/facebook/lexical/assets/77707952/06da2fa5-8322-462f-8267-ef6acd28eb68)

## The current behavior
- Trims trailing and starting spaces when creating paragraph nodes using convertFrom but does not trim spaces when converting paragraph nodes to markdown string.

## The expected behavior
- Trim spaces in both cases or do not trim in both cases.

**Comment by vadimkantorov** [comment]
Related discussion on change detection: https://github.com/facebook/lexical/discussions/6312

**Comment by vadimkantorov** [comment]
I also wonder to what extent is the editor state <> markdown conversion complete: e.g. can it export centered image as a combination of some HTML div tag and style attribute and markdown's `![alt](imageurl...)` inside?

**Comment by orelbn** [comment]
> I also wonder to what extent is the editor state <> markdown conversion complete: e.g. can it (at least vias some option) export centered image as a combination of some HTML div tag and style attribute and markdown's `![alt](imageurl...)` inside?

I'm not exactly sure what you mean by `export centred image`. Do you mean export state as a markdown string that can be transformed back to a centred image?

**Comment by vadimkantorov** [comment]
Yeah, I mean transforming

an image which is centered to sth like:
```
<div align="center">

![](https://www.google.fr/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png)

</div>
```

rendered:
<div align="center">

![](https://www.google.fr/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png)

</div>

**Comment by vadimkantorov** [comment]
> I would assume you can write custom transformers to handle that; however, it might be a bit complex.

How should one go about doing this? This would be quite frequent: export to markdown some nodes (e.g. color-highlighted text or large font) which are not natively supported by markdown but some minimal html be required to preserve either semantics or visual. This is perfectly legitimate to want to have this sometimes (as typically markdown is then rendered by renderers supporting some html tags). Can this be handled by the current transformers model? Is there anywhere an example of doing this? E.g. is there a general tree visitor model? At least going from the editor state tree to markdown should be relatively easy to write. Then being able to parse back to editor state some limited markdown+html combination is also a useful usecase
