### ISSUE TITLE
Bug: Lexical node with constructor XXXNode attempted to re-use key from node in active editor state with constructor _TextNode.

### ISSUE THREAD

**Issue by milkrong** [facebook/lexical#6326]
Lexical version:0.16.0

## Steps To Reproduce

1. Create a CustomerTextNode
2. replace the Nodes as documents said

Link to code example:
https://codesandbox.io/p/sandbox/buglexical-6y7rcf

## The current behavior
Always raise error: Lexical node with constructor FoxTextNode attempted to re-use key from node in active editor state with constructor _TextNode. Keys must not be re-used when the type is changed.
Why compare constructor name here? It's not make sense since my class name is defined by myself
<img width="642" alt="image" src="https://github.com/facebook/lexical/assets/15906981/ad1e8e78-9470-4d00-8c9b-cbc04a22fb76">

## The expected behavior
There is no error in the past version.

**Comment by milkrong** [comment]
Is seems work if I remove replace config in node registry list. Plz update your documents if things have changed

**Comment by ivailop7** [comment]
When you override the node, you shouldn't pass the 'key'. Before it was silently failing, right now we just made the error visible.

**Comment by etrepum** [comment]
What @ivailop7 is saying is correct, people used to make this mistake and the error message happened later in a confusing place. Here you get it much sooner. Specifically this is the code that's broken:

```ts
      with: (node: TextNode) => {
        return new FoxTextNode(node.__next!, node.__key);
      },
```

It should be this:

```ts
      with: (node: TextNode) => {
        return new FoxTextNode(node.__text);
      },
```

**Comment by milkrong** [comment]
> What @ivailop7 is saying is correct, people used to make this mistake and the error message happened later in a confusing place. Here you get it much sooner. Specifically this is the code that's broken:
> 
> ```ts
>       with: (node: TextNode) => {
>         return new FoxTextNode(node.__next!, node.__key);
>       },
> ```
> 
> It should be this:
> 
> ```ts
>       with: (node: TextNode) => {
>         return new FoxTextNode(node.__text);
>       },
> ```

Thanks, that works.
