### ISSUE TITLE
Bug: Issue with styling consistency with theming and using exported content in email  templates, due to ParagarhNode limitations

### ISSUE THREAD

**Issue by astghikk-adobe** [facebook/lexical#6342]
There is an issue maintaining consistent styling in emails due to the inability to add inline styles to ParagraphNode.
In the theme, we have ` margin:0; padding: 0` for the paragraphs with the className. But that will not apply if the same content is used in the email's body.

I am currently working on extending ParagraphNode to be able add inline styles for the paragraph node. To have a consistentency with the Lexical framework without needing to create a modified version of ParagraphNode in my package, I would like to use sumer.exportDOM(editor) from ParagraphNode and add inline styles directly to the node returned form the exportDOM. However, exportDOM is a private method in the ParagraphNode class.

Question:
What is the recommended approach to handle paragraph field spacing issues for emails given these constraints?

**Comment by 2wheeh** [comment]
You can override HTML with `HTMLConfig` from the editor config: 
```ts
    html: {
      export: new Map([[TextNode, () => ({ element: document.createElement('figure') })]]),
      import: { 'figure': () => ({ conversion: () => ({ node: $createTextNode('yolo') }), priority: 4 }) }
    },
```

This is my workaround to maintain consistency in indent style:
```ts
export const htmlConfig: HTMLConfig = {
  export: new Map([
    [
      ParagraphNode,
      (editor, node) => {
        const targetNode = node as ParagraphNode;
        const element = document.createElement('p');

        if (element && isHTMLElement(element)) {
          if (targetNode.isEmpty()) {
            element.append(document.createElement('br'));
          }

          const formatType = targetNode.getFormatType();
          element.style.textAlign = formatType;

          const direction = targetNode.getDirection();
          if (direction) {
            element.dir = direction;
          }
          const indent = targetNode.getIndent();
          setElementIndent(element, indent, editor._config.theme.indent);
        }

        return {
          element,
        };
      },
    ],
  ]),
};

const DEFAULT_INDENT_VALUE = '40px';

function setElementIndent(dom: HTMLElement, indent: number, indentClassName?: string): void {
  if (indent < 1) {
    return;
  }

  if (typeof indentClassName === 'string') {
    dom.classList.add(indentClassName);
  }

  const indentationBaseValue =
    window.getComputedStyle(dom).getPropertyValue('--lexical-indent-base-value') ||
    DEFAULT_INDENT_VALUE;

  dom.style.setProperty(
    // padding-inline-start is not widely supported in email HTML, but
    // Lexical Reconciler uses padding-inline-start. Using text-indent instead.
    'text-indent',
    `${indent * parseInt(indentationBaseValue, 10)}px`
  );
}

```

**Comment by astghikk-adobe** [comment]
@2wheeh  will  this approach override the entire ParagraphNode? I want to avoid this in order to maintain consistency with the  Lexical's ParagraphNode and just add missing inline styles.

**Comment by astghikk-adobe** [comment]
I would like to do something like this


```
export class CustomParagraphNode extends ParagraphNode {
  exportDOM(editor) {
    const el = super.exportDOM(editor);
    el.element.style.margin = '0px'

    return { element: el.element };
  }
}
```

```
const editorConfig = {
  namespace: 'rte',
  onError(error: Error) {
    throw error;
  },
  theme: Theme,
  nodes: [
    CustomParagraphNode,
    {
      replace: ParagraphNode,
      with: (node: ParagraphNode) => {
        return new CustomParagraphNode();
      }
    }
  ],
};
```

**Comment by 2wheeh** [comment]
> this approach override the entire ParagraphNode?

This override exportDOM method of entire ParagraphNode. So use `ParagraphNode.exportDOM` implementation with your style manipulation.

or you can override the whole Node like this:
```ts
const editorConfig = {
    ...
    nodes=[
        // Don't forget to register your custom node separately!
        CustomParagraphNode,
        {
            replace: ParagraphNode,
            with: (node: ParagraphNode) => {
                return new CustomParagraphNode();
            }
        }
    ]
}
```

with this approach, you can call `super()` to leverage default paragraphNode's behavior somehow if you prefer this to copy and paste.

**Comment by 2wheeh** [comment]
Ah yes you got it

**Comment by astghikk-adobe** [comment]
yes I've tried that, but exportDOM is private in ParagraphNode. That is the blocker

**Comment by 2wheeh** [comment]
> yes I've tried that, but exportDOM is private in ParagraphNode. That is the blocker

Now I get what your first question.

**Comment by 2wheeh** [comment]
Is it private method? It doesn't seem so.

**Comment by 2wheeh** [comment]
```ts
const htmlConfig: HTMLConfig = {
  export: new Map([
    [
      ParagraphNode,
      (editor, node) => {
        const {element} = node.exportDOM(editor);

        if (element && isHTMLElement(element)) {
          element.style.margin = '0px';
        }

        return {
          element,
        };
      },
    ],
  ]),
};
```

In this way, you can leverage default `ParagraphNode.exportDOM` instead of call `super` with customNode.

**Comment by astghikk-adobe** [comment]
Thank you, that was helpful.
