### ISSUE TITLE
Bug: Unable to find "concepts/history" on the lexical website

### ISSUE THREAD

**Issue by TryingToImprove** [facebook/lexical#6348]
This page here: packages/lexical-website/docs/concepts/history.md is not showing up on the lexical.dev website.

![image](https://github.com/facebook/lexical/assets/1690457/65752eae-c5cd-4621-93a7-fda0fd3cadb2)

**Comment by etrepum** [comment]
The PR for this would be simple, it just needs to be added to the array in packages/lexical-website/sidebars.js
