### ISSUE TITLE
Feature: placement of the cursor after inserting text at a specific position

### ISSUE THREAD

**Issue by mbohovic** [facebook/lexical#6351]
Description
After inserting a block of text, the cursor is automatically set to the end of this inserted text. I would need to be able to set the cursor e.g. in the middle or x chars back of the inserted text.

Reason: I am inserting text that is actually a shortcode, e.g. "{text}{/text}cursor here" and I want to write in the tags of this shortcode "{text}cursor here{/text}"

If there is some functionality that knows this, I don't know about it. I will be happy for advice. If it doesn't exist, is it possible to create something like that?
Well thank you

**Comment by mbohovic** [comment]
solved using `selection.setTextNodeRange(anchorNode, anchorPosition, focusNode, focusPosition)`

**Comment by nicholaschiang** [comment]
you can also use `node.selectEnd()`
