### ISSUE TITLE
Bug: ForwardRef Build Issue

### ISSUE THREAD

**Issue by hugs7** [facebook/lexical#6382]
Anyone else seeing this build error. Works fine in development but after running `npm run build` the served site I get the following error in dev tools

![image](https://github.com/facebook/lexical/assets/66514580/83007072-b345-4bfe-be6a-c20d254b35dd)

This leads to this function
![image](https://github.com/facebook/lexical/assets/66514580/08b3b451-9f69-4039-b440-98b54ca6ed86)

... which after doing some digging seems to resolve to a function within Lexical called **TreeViewWrapped**

```javascript
const TreeView = /*#__PURE__*/react.forwardRef(function TreeViewWrapped({
  treeTypeButtonClassName,
  timeTravelButtonClassName,
  timeTravelPanelSliderClassName,
  timeTravelPanelButtonClassName,
  viewClassName,
  timeTravelPanelClassName,
  editorState,
  setEditorState,
  setEditorReadOnly,
  generateContent
}, ref) {
  
....
```

located in `/@lexical/devtools-core/LexicalDevtoolsCore.dev.js`

There's also an equivalent version of this function in the LexicalJevtoolsCore.prod.js file.

Am I doing something wrong here? I've cleaned my node_modules folder, reinstalled with same issue presenting.

Lexical version: 0.16.1

## Steps To Reproduce

1. Make a Lexical app with the TreeView component
2. Run `npm run build` and serve the site statically.

Link to code example:

Please see above screenshots. The code in question is part of Lexical's library.

## The current behavior

Runs fine in vite development mode. When building for production, Chrome shows an error.

## The expected behavior

Building for production should work as it does in development.

## Impact of fix

Making building my app not possible at the moment (without stripping out the TreeView).

**Comment by hugs7** [comment]
Turned out to be an import issue in one of my plugins. Closing

**Comment by hugs7** [comment]
Interestingly, this issue only occurs when I specify manual chunks in my vite config

**Comment by etrepum** [comment]
Sounds pretty specific to your build environment, it's just an import from react.

**Comment by hugs7** [comment]
Hm yeah you could be right. I just don't understand how it works without this yet react imports obv work elsewhere (even in the lexical library). I'll close this one off for now until I've done some more digging

**Comment by hugs7** [comment]
Yeah turned out to be a chunking issue. Still don't know why but fixed by changing `vite.config.ts` chunking options to 

```typescript
 manualChunks(id) {
    if (id.includes("node_modules")) return id.toString().split("node_modules/")[1].split("/")[0].toString();
 },
```

See https://github.com/vitejs/vite/issues/12209
