### ISSUE TITLE
Bug: Cut from a table doesn't remove values

### ISSUE THREAD

**Issue by circlingthesun** [facebook/lexical#6402]
Lexical version: v0.16.1

## Steps To Reproduce

1. Open playground
2. Insert a 5x5 table
3. Fill out a row with values
4. Select the row with aforementioned values
5. Right click and select cut or press cmd + x
6. Observe that the selected values are stil present

https://github.com/user-attachments/assets/deb58c76-ed2b-4189-9371-8645c7328d40

## The current behavior

After cutting the row the values are not removed

## The expected behavior

After cutting the cells should be blank

## Impact of fix

This affects any end user using tables. It's frustrating unexpected behaviour.

**Comment by jrfitzsimmons** [comment]
+1 - from testing it seems like the content is added to the clipboard correctly (paste works fine) it's just the clearing of the cell contents that doesn't work.
