### ISSUE TITLE
Bug: history should work with custom TextNodes containing non-standard properties

### ISSUE THREAD

**Issue by CanRau** [facebook/lexical#6409]
I created my own `TextNode` to have random css class support via the added property `__className` and some methods like `addClass`. While trying it out via a button in my toolbar I realized that the editor wouldn't allow me to undo this change, while all other changes work as expected, checked lexical source code, playground code, issues and searched discord until I asked directly on [Discord](https://discord.com/channels/953974421008293909/1262877639471923272) and after poking around a little @etrepum discovered the hardcoded [`isTextNodeUnchanged`](https://github.com/facebook/lexical/blob/cad2861343c1cffdfdb27bd5aed59198f43dc32f/packages/lexical-history/src/index.ts#L186-L218) helper function which won't consider custom properties.

I think it would be nice to move `isTextNodeUnchanged` as a method maybe `isUnchanged` (or maybe `isChanged` or `hasChanged` or `hasChanges`) into TextNode so subclasses can override it when they need to support custom properties. Then the history plugin would call that method [here](https://github.com/facebook/lexical/blob/cad2861343c1cffdfdb27bd5aed59198f43dc32f/packages/lexical-history/src/index.ts#L301) instead of the hardcoded function.

This method might even live in `LexicalNode` so other nodes could also make use of it, tho I don't have a direct need for this right now I think.

Lexical version: 0.16.1

## Steps To Reproduce

1. Create a `CustomTextNode` extending `TextNode`
2. Add a non-standard property like `__className`
3. Duplicate a method like `setFormat` from TextNode to set your property from 2
4. trigger this method somehow
5. Realize that undo won't work 😅

My `addClass` method
```tsx
addClass(className: string): this {
	const self = this.getWritable();
	const classes = self.__className?.split(" ").map((s) => s.trim());
	classes.push(className);
	self.__className = classes.join(" ");
	return self;
}
```

The button onClick that calls it (my actual code is a little longer and inspired by [`$patchStyleText`](https://github.com/facebook/lexical/blob/cad2861343c1cffdfdb27bd5aed59198f43dc32f/packages/lexical-selection/src/lexical-node.ts#L338-L478), tho this is enough to reproduce the problem)
```tsx
onClick={() => {
    activeEditor.update(() => {
        const selection = $getSelection();
        if ($isRangeSelection(selection)) {
            const selectedNodes = selection.getNodes();
            if ($isTextNode(selectedNodes[0])) {
                selectedNodes[0].addClass("text-red-500");
            }
        }
    });
}}
```

**Comment by etrepum** [comment]
Adding some more context here, this hack came from #2258 where an older version of the playground's `MaxLengthPlugin` did not use `$restoreEditorState` (added in #2273). It may actually be possible to remove the hack entirely.
