### ISSUE TITLE
Bug: table can't be deleted when it has more than one colspan rows

### ISSUE THREAD

**Issue by mrdivyansh** [facebook/lexical#6440]
Lexical version: 0.16.1

## Steps To Reproduce

Sample Table

<table>
  <tr style="height: 21px">
    <td colspan="4">
      <p dir="ltr" style="text-align: center">
        <strong data-lexical-text="true">Colspan row 1</strong>
      </p>
    </td>
  </tr>
  <tr style="height: 21px">
    <td>
      <p dir="ltr">
        <span data-lexical-text="true">Cell a</span>
      </p>
    </td>
    <td>
      <p dir="ltr">
        <span data-lexical-text="true">Cell b</span>
      </p>
    </td>
    <td>
      <p dir="ltr">
        <span data-lexical-text="true">Cell c</span>
      </p>
    </td>
    <td>
      <p dir="ltr">
        <span data-lexical-text="true">Cell d</span>
      </p>
    </td>
  </tr>
  <tr style="height: 21px">
    <td colspan="4">
      <p dir="ltr" style="text-align: center">
        <strong data-lexical-text="true">Colspan row 2</strong>
      </p>
    </td>
  </tr>
</table>

1. Visit https://playground.lexical.dev/
2. Copy and paste the above sample table.
3. Select the table by pressing `Cmd+A`
4. Press `Backspace` to delete the selected table.

## The current behavior
Clears the table cells

https://github.com/user-attachments/assets/47a8f27b-ec43-4864-98b1-73af52fae8cd

## The expected behavior
Deletes the selected content (the table).

**Comment by elbotho** [comment]
I tried to reproduce this and I think the problem actually occurs if the last row has a merged table cell (no matter how many merged cells there are).
Also the selection has to include **only** the table (usually you have a paragraph before/after).
Then I can also reproduce it without copying from your issue.

**Comment by etrepum** [comment]
No longer reproducible with recent table refactoring
