### ISSUE TITLE
Bug: only a table gets deleted on backspace

### ISSUE THREAD

**Issue by mrdivyansh** [facebook/lexical#6441]
Lexical version: 0.16.1

## Steps To Reproduce

1. Visit https://playground.lexical.dev/
2. Insert a table of any dimension
3. Add paragraphs or images.
4. Select all by pressing `Cmd+A`
5. Press `Backspace` to delete the selected content.

## The current behavior
Only the table gets deleted

https://github.com/user-attachments/assets/5a7f4358-44dc-492f-97ca-32bf031d502f

## The expected behavior
All node/content should be deleted.

**Comment by mrdivyansh** [comment]
Only one table get deleted at a time.

https://github.com/user-attachments/assets/20400cfc-ca6e-4032-bdf1-82ac790ade53

**Comment by etrepum** [comment]
This should be fixed in 0.17.0, can not reproduce at https://playground.lexical.dev/
