### ISSUE TITLE
Bug: Selection lost when deleting content below a Decorator node

### ISSUE THREAD

**Issue by Ekeu** [facebook/lexical#6442]
Lexical version: `0.16.1`

## Steps To Reproduce

1. Go to the Lexical playground
2. Delete everything
3. Insert a horizontal Rule
4. Press the backspace key to delete the space below
5. The horizontal rule will be selected
6. Place the cursor below the horizontal rule (Or you can click anywhere below the horizontal rule)
7. Press the backspace key to delete
8. You will see the below error in the console

```
updateEditor: selection has been lost because the previously selected nodes have been removed and selection wasn't moved to another node. Ensure selection changes after removing/replacing a selected node.
```

## The current behavior

Here's a screencast on how you can reproduce the error:

[Screencast from 07-22-2024 04:38:16 PM.webm](https://github.com/user-attachments/assets/4f0dbd46-0513-4628-bc6a-8377c253a99c)

## The expected behavior

Should not raise an error and the horizontal rule should be deleted

**Comment by etrepum** [comment]
I can't reproduce this with current lexical
