### ISSUE TITLE
Bug: Emoji markdown rule in Playground makes pages dead.

### ISSUE THREAD

**Issue by ghost** [facebook/lexical#6452]
Text matching seems be malfunction if a emoji not found, causing page dead when typing.

Step to reproduce the problem;

* In playground, type strings (e.g. "23:59:31" which is a commonly used time format). After the second colon, web page lost response (Chromium, Firefox, Safari, ...).

It could be due to the emoji transformer, as the problem would gone if the pattern is prefixing a whitespace:

```ts
export const EMOJI: TextMatchTransformer = {
  dependencies: [],
  export: () => null,
  importRegExp: /:([a-z0-9_]+):/,
  regExp: /\s:([a-z0-9_]+):/,  /* modified */
  replace: (textNode, [, name]) => {
    const emoji = emojiList.find((e) => e.aliases.includes(name))?.emoji;
    if (emoji) {
      textNode.replace($createTextNode(emoji));
    }
  },
  trigger: ':',
  type: 'text-match',
};
```

**Comment by etrepum** [comment]
Can't reproduce
