### ISSUE TITLE
$convertToMarkdownString does not slashify

### ISSUE THREAD

**Issue by Mark-Buxbaum** [facebook/lexical#6454]
If the editor contains text that can be interpreted as markdown, $convertToMarkdownString assumes the value is the same.  It should escape any markdown sequences with backslashes.

Lexical version: 0.15.0

## Steps To Reproduce

1. Put the text "\*\*foo\*\*" in your clipboard (using your favorite text editor).
2. Go to the lexical playground and paste it.
![image](https://github.com/user-attachments/assets/9a9873f1-ebf3-496e-9d76-8c56c5551a76)

3. Click the convert to markdown button.  The markdown looks incorrect; it still has the value "\*\*foo\*\*".  The proper value is "\\\*\\\*foo\\\*\\\*", with the backslashes.
![image](https://github.com/user-attachments/assets/4d3e6ec8-2ab0-4732-89f3-f548063c8cd6)

4. Unclick the markdown button.  The playground now shows "**foo**", adding boldface and removing asterisks.
![image](https://github.com/user-attachments/assets/c24efcd3-7d7c-4eba-874f-1c11a3c57cf0)

## The current behavior

Markdown is incorrectly encoded with no backslashes.

## The expected behavior

Markdown should be correctly encoded.

## Impact of fix
Pasting into the editor should be lossless.

**Comment by Mark-Buxbaum** [comment]
My first attempt to fix: add this pass to the routine exportTextFormat() in MarkdownExport.ts:
```
  // Go through the text and if it matches an unslashified tag, add slashes
  for (const transformer of textTransformers) {
    const tagWithSlashes = transformer.tag.replaceAll(/(.)/g,"\\$1" )
    const regexp = new RegExp("(?<!\\\\)" + tagWithSlashes, "g");
    output = output.replaceAll(regexp, tagWithSlashes);
  }
```
The only downside is that I have to add the reverse transform to `$convertFromMarkdownString`.

**Comment by cduff** [comment]
Related to https://github.com/facebook/lexical/issues/2715?
