### ISSUE TITLE
Bug: Redo doesn’t work by Key Board (command + Y)

### ISSUE THREAD

**Issue by mapradhan** [facebook/lexical#6495]
Lexical version:
0.17.0
## Steps To Reproduce

1. Make some changes in the editor (https://playground.lexical.dev/)
2. Undo the changes (Using command + Z)
3. Redo the changes (Using command + Y) --- It doesn't do redo rather it opens the browser history (It works when we use the Redo button, but fails when we use the keyboard)

Link to code example:
https://playground.lexical.dev/

## The current behavior
command + Y  doesn't do redo changes in the editor rather it opens the browser history 
## The expected behavior
command + Y  should redo the changes in the editor

**Comment by etrepum** [comment]
The key command for redo on macOS is shift-cmd-Z. I think the only bug here is the tooltip on the redo button.
