### ISSUE TITLE
Bug: _cell gets lost on child table cell nodes when parent table is resized in the playground

### ISSUE THREAD

**Issue by OriginalEXE** [facebook/lexical#6496]
Lexical version: 0.17.0

## Steps To Reproduce

1. Open the [Playground](https://playground.lexical.dev/)
2. Remove all contents, insert table (5x5 but doesn't matter)
3. In the first cell, insert another table (5x5 but doesn't matter)
4. Resize the parent cell containing the child table

[Screencast from 2024-08-06 12-49-19.webm](https://github.com/user-attachments/assets/9a7c3812-e260-4d86-b495-ad8efd47e9d7)

Link to code example: https://playground.lexical.dev/

## The current behavior
You can now no longer resize the child table (because the `_cell` property of it is gone, so `getDOMCellFromTarget` returns null)

## The expected behavior
You can continue resizing the child table

## Impact of fix
Anyone using the table cell resizer plugin

**Comment by etrepum** [comment]
I can't reproduce with v0.20.2
