### ISSUE TITLE
Bug: Editor Crash when selecting an empty paragraph with an image

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#6506]
Version 0.17

The PR https://github.com/facebook/lexical/commit/71880d22f63a8f2631352a7032a22f639238b306 by @jason89521 

Introduced the following bug when upon selection of empty paragraphs it crashes the editor. 

To reproduce:
1. Clear the editor
2. Type a few empty lines
3. Add an image
4. Select over the empty lines

**Comment by ivailop7** [comment]
Cannot revert automatically anymore, due to the number of changes since, but the issue is worth fixing.

**Comment by etrepum** [comment]
I think this bug is just because they were trying to write "readable" code with variables instead of one big condition, but to be correct it has to short-circuit
