### ISSUE TITLE
Bug: Navigating within a table with merged cell crashes

### ISSUE THREAD

**Issue by Shubhankerism** [facebook/lexical#6519]
Lexical version: v0.17.0

Moving to a merged cell in a table using the arrow keys leads to crashes. 

## Steps To Reproduce

1.  Copy a table with merged cells from excel/gdocs.
2.  Go to the last cell and press down ⬇ arrow key

![merge-cells-paste](https://github.com/user-attachments/assets/5c30a285-d0a7-4324-854b-444fab72d71c)

## The current behavior
Crashes with error:
```
Uncaught Error: Node at cords not TableCellNode.
    at rs.getCellNodeFromCordsOrThrow
``` 

## The expected behavior

Cursor should move to the cell below.

**Comment by Shubhankerism** [comment]
Can also be reproduced by directly inserting a table, and merging cells.
Doesn't necessarily have to be copy-pasted from excel/gdocs.

**Comment by turnerguo** [comment]
This may caused by the TableCellNode inner structure, actually the whole table structure are very weak, it breaks on some DecoratorNode or customized nodes such as HR node, which I created a bug on this.
