### ISSUE TITLE
Feature: How can you determine if the current state of the editor needs to be saved, and how to compare the differences with the initial content?

### ISSUE THREAD

**Issue by moyang-pro** [facebook/lexical#6525]
How can you determine if the current state of the editor needs to be saved, and how to compare the differences with the initial content?

**Comment by etrepum** [comment]
You can use [registerUpdateListener](https://lexical.dev/docs/concepts/listeners#registerupdatelistener) (or an abstraction of that such as the `OnChangePlugin`) to get callbacks when the editor's state or selection changes. If the state changed, then you probably want to save (or at least schedule a debounced save).

There are no built-in diff algorithms for comparing editor states, it's up to you to implement whatever makes sense for your use case.
