### ISSUE TITLE
Bug: "text/plain" clipboard data of copied table cells is incorrect

### ISSUE THREAD

**Issue by mshafer** [facebook/lexical#6541]
When copying table cells from Lexical, the `text/plain` data is incorrect – it contains duplicated/nested versions of the content.

Copying this table:
![image](https://github.com/user-attachments/assets/0210770c-8e2b-4252-91d9-04ec772e832f)

Results in this text content when pasted in a text editor:
![image](https://github.com/user-attachments/assets/d74640ab-0839-4602-a421-94dc1a52913c)

Lexical version: `v0.17.0+dev.esm` (current Lexical Playground version)

## Steps To Reproduce

1. Insert a table into the Lexical Playground
2. Select cells from the table, then copy the cells
3. Open a plain text editor and paste the content.
4. Expect just the original cell content, observe that it contains duplicated versions of the original content

## The current behavior

`text/plain` clipboard data of copied table cells contains duplicated content.  

## The expected behavior

`text/plain` clipboard data should be a simple representation of the original table cell content, with no duplication

## Impact of fix

Any users of tables will get correct content when pasting into plain text environments. The current issue does not seem to impact copy paste of the `text/html` or `application/x-lexical-editor` versions of the data on the clipboard.

**Comment by etrepum** [comment]
I can't reproduce this, what exactly is the selection you have and which browser are you using?

**Comment by mshafer** [comment]
It's a table selection with the anchor at the top-left cell and the focus in the bottom-right cell:
<img width="432" alt="image" src="https://github.com/user-attachments/assets/da25ce7b-b46b-4636-9f86-d859387a8bbe">

Inspecting the `ClipboardEvent` in Chrome shows:

```
> event.clipboardData.getData("text/plain")
'A\n\nB\n\n1\n\n2A\n\nBAAABBB1\n\n2111222'
```

This is in Chrome 128.0.6613.85.

Interestingly if I instead do a range selection that spans over the entire table, the pasted plaintext content is then correct.

**Comment by etrepum** [comment]
And how exactly are you copying the table in this scenario and which platform are you using? On macOS, I can't get cmd-C or the Chrome's edit menu copy to trigger the copy with a table selection on the current playground, but it does work with a range selection that includes the table

**Comment by mshafer** [comment]
Oh yes I'm on macOS as well (Sonoma 14.4.1), and in the examples above I was using cmd-C to trigger the copy.

I can also reproduce the same behaviour using either "Edit > Copy" from Chrome's menu bar, or right-clicking a table cell and selecting "Copy". (In between each of these tests I copied some other text to wipe my clipboard data, just to be sure.)

Happy to share screen recordings of any of this if that helps.
