### ISSUE TITLE
Bug: updating from lexical packages 1.17.0 -> 1.17.1 raises errors in CI for @lexical/table

### ISSUE THREAD

**Issue by THEjacob1000** [facebook/lexical#6569]
Lexical version: 0.17.1

## Steps To Reproduce

1. Update the following Lexical packages to version 0.17.1: @lexical/code, @lexical/link, @lexical/list, @lexical/markdown, @lexical/react, @lexical/rich-text, @lexical/selection, @lexical/table, @lexical/utils, and lexical.
2. Run the build process in a CI environment (using pnpm as the package manager).

Link to code example:

Unfortunately, this issue is specifically encountered within our CI environment and is not easily reproducible in an isolated environment like CodeSandbox. However, the issue is directly linked to the import statement in `LexicalTable.prod.mjs`, where it attempts to import `$getClipboardDataFromSelection` from `@lexical/clipboard`:

```
Attempted import error: '$getClipboardDataFromSelection' is not exported from '@lexical/clipboard' (imported as 'q').
```

This error causes the build to fail.

## The current behavior

The build process fails in the CI environment with the following error:

```
../../node_modules/.pnpm/@lexical+table@0.17.1/node_modules/@lexical/table/LexicalTable.prod.mjs
Attempted import error: '$getClipboardDataFromSelection' is not exported from '@lexical/clipboard' (imported as 'q').

Import trace for requested module:
../../node_modules/.pnpm/@lexical+table@0.17.1/node_modules/@lexical/table/LexicalTable.prod.mjs
./src/components/CommentsTextEditor/index.tsx
./src/components/Comments/index.tsx
./src/components/TaskPageActivityTimeline/EventTabs/index.tsx
./src/components/TaskPageCenterContainer/index.tsx
./src/components/Task/index.tsx
```

This issue only occurs in our CI environment, and we are unable to reproduce it locally.

## The expected behavior

The build process should complete successfully without any import errors, as was the case with version 0.17.0.

## Impact of fix

- **Severity:** This bug is causing our CI pipeline to fail, which blocks deployments and affects our ability to push updates to production.
- **Frequency:** The issue occurs every time the CI pipeline is triggered with the updated packages.
- **Beneficiaries:** Any developers or teams using Lexical in their CI environments could be impacted by this issue. Resolving it would benefit anyone upgrading to version 0.17.1.

**Comment by etrepum** [comment]
Have you tried updating all lexical modules to 0.17.1? I don't see `@lexical/clipboard` in your list. Mixing versions of packages from the lexical monorepo is not supported
