### ISSUE TITLE
Bug: CJK text editing does not work properly on Windows 10, Chrome 128 versions.

### ISSUE THREAD

**Issue by yunseop-dev** [facebook/lexical#6577]
Lexical version: 0.14.5

## Steps To Reproduce

1. Windows 10, Chrome 128 versions.
2.

## The current behavior
![Aug-30-2024 21-08-25](https://github.com/user-attachments/assets/241d8a24-9045-47f7-beb9-6305ffa8ec56)

There is a problem that text editing is not possible as in the attached image.

It does not occur in Windows 11 versions.

## The expected behavior
Text must be entered normally.

## Impact of fix
This bug occurs after the Chrome 128 version update. It didn't happen in 127 version.

Looking at the release notes for the Chrome 128 version, there was an update regarding the cachePosition. I think this might have affected it.

link: https://developer.chrome.com/release-notes/128#documentcaretpositionfrompoint

**Comment by etrepum** [comment]
Are you able to reproduce this with 0.17.1? There is only one development branch of Lexical, only the latest version receives updates, fixes are not backported to older versions.

**Comment by yunseop-dev** [comment]
@etrepum Yes, it's an issue with the latest version as well. The thing that's unique is that it only happens with Windows 10, Chrome 128 versions. It doesn't happen with Windows 11, Chrome 128.

**Comment by etrepum** [comment]
I don't think there's really enough information here for anyone else to reproduce or investigate, since it requires custom nodes. It does seem like you have a workaround as well.
