### ISSUE TITLE
Bug: applying formatting to table cells with mixed formatting does not make formatting consistent

### ISSUE THREAD

**Issue by jrfitzsimmons** [facebook/lexical#6589]
Table selection containing a mix of text formatting toggles formatting per cell, rather than for the selection as a whole. The examples below talk about italics but the same applies for bold/underline/strikethrough, etc.

<img width="505" alt="image" src="https://github.com/user-attachments/assets/797dd3a7-04d0-46dd-b37e-022fb53eca0f">

After pressing Italics button:

<img width="504" alt="image" src="https://github.com/user-attachments/assets/fcf42d3d-df53-4a11-9ccc-a85f9d9bb7bb">

Lexical version: latest in Playground as of 2024-09-04

## Steps To Reproduce

1. Insert a table with at least two cells
2. Put text in two different cells
3. Italicise text in one cell
4. Select the cells with text
5. Press the Italics button in the toolbar

## The current behavior

For each cell, if the contents are italics, they become non-italics, and vice versa.

## The expected behavior

The whole selection should become italicised or not, rather than cells toggling individually. This would match the behaviour of a range selection that contains a mix of italics/non-italics: it becomes all-or-nothing italics.

## Impact of fix

It's not breaking any workflows, but the behaviour is unexpected as it differs from other text editors.

**Comment by KatsiarynaDzibrova** [comment]
Was fixed in https://github.com/facebook/lexical/pull/6626
