### ISSUE TITLE
Module not found: Error: Can't resolve 'react/jsx-runtime'

### ISSUE THREAD

**Issue by sometinaintright** [facebook/lexical#6597]
### Description
Hello, has anyone faced this issue?
The consumer is using classic jsx transform, everything works fine before i introduce lexical and I got this error.

```
 ERROR in ../../.yarn/__virtual__/@lexical-react-virtual-c8219025cc/0/cache/@lexical-react-npm-0.17.1-cdb2a1288c-5ecb24cecf.zip/node_modules/@lexical/react/LexicalComposer.dev.mjs 12:0-40
Module not found: Error: Can't resolve 'react/jsx-runtime' in 'myworkspace/.yarn/__virtual__/@lexical-react-virtual-c8219025cc/0/cache/@lexical-react-npm-0.17.1-cdb2a1288c-5ecb24cecf.zip/node_modules/@lexical/react'
.....
```

Per as https://github.com/facebook/react/issues/20235, Don't we support react v17 or could this be an issue of incompatibility with the classic jsx transform? 

### Version
Lexical version: 0.17.1
React: v17.0.2
Webpack5

**Comment by etrepum** [comment]
React 17 is "supported" but only React 18 and 19 are tested so there are no guarantees for older versions.

https://github.com/facebook/react/issues/20235#issuecomment-750911623 seems relevant to your problem

**Comment by sometinaintright** [comment]
> React 17 is "supported" but only React 18 and 19 are tested so there are no guarantees for older versions.
> 
> [facebook/react#20235 (comment)](https://github.com/facebook/react/issues/20235#issuecomment-750911623) seems relevant to your problem

Thank you! But this is not the solution what i need.

It looks like there no jsx-runtime.js file only index.js in node_modules/react directory, maybe i need add some rule to handle this.

**Comment by HJZzzzz** [comment]
@sometinaintright hi, is ur issue resolved?

**Comment by micaelbergeron** [comment]
For posterity, I've ended up reverting the changes to use the classic jsx transformer in `@babel/preset-react`, as this change breaks compatibility with React <= 17.0 and maybe should have tagged as a major version.

https://github.com/muralco/lexical/tree/build/classic-jsx

**Comment by sometinaintright** [comment]
> @sometinaintright hi, is ur issue resolved?

Yes, it's been resolved.

Here my root cause: 
My project originally used jsx, and I checked the configuration of Webpack, then I found that there was a bit of an issue with handling the path for the React package.

This caused it to analyze 'react/jsx-runtime' and resolve it to 'react/index.js/jsx-runtime.js'.
