### ISSUE TITLE
Bug: replace elementNode error

### ISSUE THREAD

**Issue by tyy11017** [facebook/lexical#6604]
I am trying to replace elementNode, but get 
![image](https://github.com/user-attachments/assets/032f8909-4781-4334-bd59-2465b1bd9237)

Lexical version: 0.17.1

## Steps To Reproduce

ExtendElementNode

` 
export class ExtendElementNode extends ElementNode {
  constructor(key?: NodeKey) {
      super(key);
   }

   static getType(): string {
    return 'extended-element';
  }

  static clone(node: ExtendElementNode) {
    return new ExtendElementNode(node.__key);
  }
}
`

<img width="666" alt="image" src="https://github.com/user-attachments/assets/f1e71874-c335-4f71-a3cb-d9c564631c49">

Link to code example:

**Comment by etrepum** [comment]
I think this can happen if you have your bundler configured to build for very old target versions of JavaScript (before classes were available). You'll need to change that setting to something modern. I can't really help you any further without a full example where this error can be reproduced.

**Comment by tyy11017** [comment]
@etrepum   I think bundler configuration is not the reason. I tried it on lexical playground 

<img width="1126" alt="image" src="https://github.com/user-attachments/assets/21c4580f-fa70-4241-a083-4f1e86c26e45">

![image](https://github.com/user-attachments/assets/f45dbad9-f245-4316-a31b-d8ba04721c22)

**Comment by etrepum** [comment]
I'm sorry but I can't tell what you're doing wrong from the screenshots. If you provide a full example that can be run by other people (e.g. codesandbox, stackblitz, or a GitHub repo) then I will take a look

**Comment by etrepum** [comment]
Ok I see, ElementNode is an abstract class that can not be directly used with the editor. Overriding it in the configuration doesn't make sense, because there can't be any ElementNode instances in the first place. You either want to register your class directly without using node replacement, or you want to pick a more specific ElementNode subclass to override (e.g. ParagraphNode).
