### ISSUE TITLE
Feature: Highlight special strings

### ISSUE THREAD

**Issue by mbohovic** [facebook/lexical#6610]
## Description
Maybe someone has already mentioned it somewhere, but I haven't seen anything like that.

I would like a specific string in the text to be highlighted, but I don't know what functions to use for that (if they exist).

The reason is that in the text I use e.g. actually variables in the form `[variableName]` and I would like to have them highlighted in the editor.

e.g. I have a text:
**What is Lorem Ipsum?**
Lorem Ipsum is simply _dummy_ text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever **since the 1500s**, when an unknown [printer] took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries

and I want to automatically have [printer] highlighted in the text, e.g. backgroundColor: yellow.

Thank you for any advice

**Comment by tope96** [comment]
I am also looking for a solution to this!

**Comment by citruscai** [comment]
@etrepum do you think it would be good idea to try tackling this?

**Comment by etrepum** [comment]
@citruscai I think it could be worth making an example, maybe another kind of node + plugin in the playground or a standalone example. I think the `useLexicalTextEntity` facility would be appropriate for this, you can use the Hashtag plugin as a reference for how something like this could be done.

**Comment by etrepum** [comment]
It's not really clear to me what you're trying to do that prints that error but I would start with adding your code to the playground. Creating new packages is for stable, generic and reusable code.

**Comment by citruscai** [comment]
> It's not really clear to me what you're trying to do that prints that error but I would start with adding your code to the playground. Creating new packages is for stable, generic and reusable code.

 i realized that i was overcomplicating it a lot by trying to  create an entire new package for this feature.
