### ISSUE TITLE
Bug: Handling extended HTML styling

### ISSUE THREAD

**Issue by Sunny-liaokai** [facebook/lexical#6611]
Lexical version:

## Steps To Reproduce

1. According to the documentation Handling extended HTML styling Using the latest official example, paste a piece of text in bold and find that it cannot be bold because the bold label also inherits the inline style  And the bold and inline styles are out of order

Link to code example:

https://github.com/user-attachments/assets/e2f0146b-32b4-4587-8920-05d542418d71

**Comment by Sunny-liaokai** [comment]
Sorry, because the project file is too large, it cannot be previewed in codeShadBox. I recorded a video here. You can see from the video that bolding does not take effect.

**Comment by Sunny-liaokai** [comment]
`import {
  $isTextNode,
  DOMConversion,
  DOMConversionMap,
  DOMConversionOutput,
  NodeKey,
  TextNode,
  SerializedTextNode,
  LexicalNode
} from 'lexical';

export class ExtendedTextNode extends TextNode {
  constructor(text: string, key?: NodeKey) {
    super(text, key);
  }

  static getType(): string {
    return 'extended-text';
  }

  static clone(node: ExtendedTextNode): ExtendedTextNode {
    return new ExtendedTextNode(node.__text, node.__key);
  }

  static importDOM(): DOMConversionMap | null {
    const importers = TextNode.importDOM();
    return {
      ...importers,
      code: () => ({
        conversion: patchStyleConversion(importers?.code),
        priority: 1
      }),
      em: () => ({
        conversion: patchStyleConversion(importers?.em),
        priority: 1
      }),
      span: () => ({
        conversion: patchStyleConversion(importers?.span),
        priority: 1
      }),
      strong: () => ({
        conversion: patchStyleConversion(importers?.strong),
        priority: 1
      }),
      sub: () => ({
        conversion: patchStyleConversion(importers?.sub),
        priority: 1
      }),
      sup: () => ({
        conversion: patchStyleConversion(importers?.sup),
        priority: 1
      }),
    };
  }

  static importJSON(serializedNode: SerializedTextNode): TextNode {
    return TextNode.importJSON(serializedNode);
  }

  isSimpleText() {
    return this.__type === 'extended-text' && this.__mode === 0;
  }

  exportJSON(): SerializedTextNode {
    return {
      ...super.exportJSON(),
      type: 'extended-text',
      version: 1,
    }
  }
}

export function $createExtendedTextNode(text: string): ExtendedTextNode {
	return new ExtendedTextNode(text);
}

export function $isExtendedTextNode(node: LexicalNode | null | undefined): node is ExtendedTextNode {
	return node instanceof ExtendedTextNode;
}

function patchStyleConversion(
  originalDOMConverter?: (node: HTMLElement) => DOMConversion | null
): (node: HTMLElement) => DOMConversionOutput | null {
  return (node) => {
    const original = originalDOMConverter?.(node);
    if (!original) {
      return null;
    }
    const originalOutput = original.conversion(node);

    if (!originalOutput) {
      return originalOutput;
    }

    const backgroundColor = node.style.backgroundColor;
    const color = node.style.color;
    const fontFamily = node.style.fontFamily;
    const fontWeight = node.style.fontWeight;
    const fontSize = node.style.fontSize;
    const textDecoration = node.style.textDecoration;

    return {
      ...originalOutput,
      forChild: (lexicalNode, parent) => {
        const originalForChild = originalOutput?.forChild ?? ((x) => x);
        const result = originalForChild(lexicalNode, parent);
        if ($isTextNode(result)) {
          const style = [
            backgroundColor ? `background-color: ${backgroundColor}` : null,
            color ? `color: ${color}` : null,
            fontFamily ? `font-family: ${fontFamily}` : null,
            fontWeight ? `font-weight: ${fontWeight}` : null,
            fontSize ? `font-size: ${fontSize}` : null,
            textDecoration ? `text-decoration: ${textDecoration}` : null,
          ]
            .filter((value) => value != null)
            .join('; ');
          if (style.length) {
            return result.setStyle(style);
          }
        }
        return result;
      }
    };
  };
}`

**Comment by Sunny-liaokai** [comment]
The reason why bolding does not take effect is because this code will make the bold tag also inherit the inline style. However, the parent tag is not bold, so the child container cannot be bold either.

**Comment by Sunny-liaokai** [comment]
@keiseiTi https://codesandbox.io/p/sandbox/lexical-playground-2lx86p?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0utp1dl00063b6l0590j8h3%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0utp1dl00023b6lwangf2du%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0utp1dl00033b6lzyno6no0%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0utp1dl00053b6ltw58wja5%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0utp1dl00023b6lwangf2du%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0utp1dl00013b6l0vccnxyh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cm0utp1dl00023b6lwangf2du%2522%252C%2522activeTabId%2522%253A%2522cm0utp1dl00013b6l0vccnxyh%2522%257D%252C%2522cm0utp1dl00053b6ltw58wja5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0utp1dl00043b6la6y0idi2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522cm0utp1dl00053b6ltw58wja5%2522%252C%2522activeTabId%2522%253A%2522cm0utp1dl00043b6la6y0idi2%2522%257D%252C%2522cm0utp1dl00033b6lzyno6no0%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0utp1dl00033b6lzyno6no0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by Sunny-liaokai** [comment]
![image](https://github.com/user-attachments/assets/d9bcb853-6c11-4141-88a1-eea6758519e5)
The main adjustments are here, according to the official documentation

**Comment by Sunny-liaokai** [comment]
copied copy  https://docs.google.com/document/d/1HLN11ZyMu39GKb_eAyqOcbpTkyFT824ai-76VdOigk0/edit

**Comment by etrepum** [comment]
It's up to you to convert the inline styles in imported text to be compatible with the editor classes that you're using. This is one of the reasons why the default behavior is not to import all inline styles. The example in the documentation is not ready to use for all use cases, it's just a demonstration of the technique for how you would begin such an implementation.

**Comment by Sunny-liaokai** [comment]
那么我应该如何解决这个问题呢，是否有相关的示例

**Comment by Sunny-liaokai** [comment]
@etrepum

**Comment by etrepum** [comment]
I don't believe there is any example that does exactly what you're trying to do. Lexical is built to be a rich text editor, not a HTML editor, and it works from its own data model rather than the HTML/CSS data model. There's basically two approaches you could take, either change your class so that on updateDOM, createDOM, and exportDOM the bold, italic, etc. text formats modify the inline styles accordingly, or you make sure that when you import/export text it will correctly convert the inline styles to Lexical's text format bitmap and remove the inline styles that match those text formats.

**Comment by Sunny-liaokai** [comment]
So I thought, what should I do when I'm bold, through updateDOM, how do I get the current bold content and remove some of the inline styles from the strong tag

**Comment by etrepum** [comment]
I suggest you read the implementation https://github.com/facebook/lexical/blob/main/packages/lexical/src/nodes/LexicalTextNode.ts and take a look at the API documentation for TextNode, particularly the [hasFormat](https://lexical.dev/docs/api/classes/lexical.TextNode#hasformat) method

**Comment by keiseiTi** [comment]
using updateDOM can change the DOM, so you can directly manipulate the DOM.

Bob Ippolito ***@***.***> 于2024年9月10日周二 11:04写道：

**Comment by keiseiTi** [comment]
Using updateDOM can change the DOM, so you can directly manipulate the DOM

**Comment by Sunny-liaokai** [comment]
Well thank you very much, but it will take me some time to understand this area, if the documentation provides some examples, as a user may be faster to get started
