### ISSUE TITLE
Feature: Single Table Cell selection, and add TableCellSelection command

### ISSUE THREAD

**Issue by turnerguo** [facebook/lexical#6621]
## Description
1. currently the table selection does only support selecting more than one table cells, but actually in some case we need use customized toolbar menu to operate a single table cell, a good e.g. from [feishu.cn](https://feishu.cn) like this:

https://github.com/user-attachments/assets/3f5ed55d-bf0c-43b8-8deb-d35a938748a4

2. due to this, we need a TABLE_CELL_SELECTION command to support table cell toolbar customization .

**Comment by etrepum** [comment]
There isn't a TABLE_CELL_SELECTION command (just like there aren't really other commands for creating a selection), but TableSelection supports selecting an individual cell now (anchor and focus on the same TableCellNode).
