### ISSUE TITLE
Bug: setEditable(true) + SelectEnd inside Li  - creates new span per each new typing.

### ISSUE THREAD

**Issue by maliuta-oleksandr** [facebook/lexical#6636]
Lexical version: 0.17.1

## Steps To Reproduce

1.
 ```
`setEditable(true)`
```
2. on UseEffect call
 ```
const selection: BaseSelection | RangeSelection | null = $getSelection();
const lastTextNode = selection?.getNodes()[selection.getNodes().length - 1];

selection?.focus.set('root', $getRoot().getChildrenSize(), 'element');
lastTextNode.selectEnd();
```
3. Now when user types - for each character I get new `span` element.
4. Key point here is applied styles to text. You can check default value in to App.tsx
<img width="396" alt="image" src="https://github.com/user-attachments/assets/1a9ea449-d011-412c-92a5-1a97ea517b2b">

Link to code example:
https://codesandbox.io/p/sandbox/7srx3p
Inside use-pub-sub-listener.ts - enableEditingAndSetCaretToTheEnd func 

## The current behavior
- When I do double click and the editor is not enabled - I apply the selection logic, then just start typing - it create new span.
- When I change cursor manually - works as expected

## The expected behavior
It should continue the same span element

I tried also - anchor.set, no difference

**Comment by etrepum** [comment]
This sandbox is not public so the problem can not be reproduced

**Comment by maliuta-oleksandr** [comment]
@etrepum  sorry, updated https://codesandbox.io/p/sandbox/7srx3p?file=%2Fsrc%2FApp.tsx

**Comment by etrepum** [comment]
It's a bug in your `ExtendedTextNode` node transform (and `ExtendedTextNode` class), if you disable that transform then it has the expected insert behavior. You're overriding the text normalization code, and your `ExtendedTextNode` doesn't implement `isSimpleText() { return true; }` so it won't merge the nodes after the changes you're making in the transform.

**Comment by maliuta-oleksandr** [comment]
@etrepum Thanks for checking.
I disabled transforms - didn't help.
About isSimpleText = but this class extends TextNode, it should take methods

**Comment by etrepum** [comment]
It does inherit the methods of TextNode but the implementation returns false for subclasses

```ts
  /**
   * Returns whether or not the node is simple text. Simple text is defined as a TextNode that has the string type "text"
   * (i.e., not a subclass) and has no mode applied to it (i.e., not segmented or token).
   *
   * @returns true if the node is simple text, false otherwise.
   */
  isSimpleText(): boolean {
    return this.__type === 'text' && this.__mode === 0;
  }
```

**Comment by maliuta-oleksandr** [comment]
Okay, I got it. have to check every method now)
BTW, I disabled all my transformes - now I got another issue - Number List type - wrong values. Do I miss anything in ExtendedListItemNode ?
<img width="155" alt="image" src="https://github.com/user-attachments/assets/040a6f44-931e-4cd7-8344-4583c92ae5d0">

**Comment by etrepum** [comment]
Sorry I am not here to debug all of your problems, if you spend some time trying to debug this yourself and can't figure it out then you should ask in the [discord](https://discord.gg/KmG4wQnnD9)
