### ISSUE TITLE
Bug:  Interoperability between lexical and @lexical/react

### ISSUE THREAD

**Issue by LanVukusic** [facebook/lexical#6637]
Lexical version: 0.17.1

## Steps To Reproduce
```ts
import {LexicalEditor} from 'lexical';
import { createEmptyEditorState } from 'lexical/LexicalEditorState';

function clearEditor(editor: LexicalEditor) {
  editor.update(
    () => {editor.setEditorState(createEmptyEditorState());}
  );
}

export const TestPlugin = () => {
  const [editor] = useLexicalComposerContext();
  clearEditor(editor);
}

```
![image](https://github.com/user-attachments/assets/e450e4bc-a266-4aeb-8f7a-a640156b9d6d)

This gives the `Missing "./LexicalEditorState" specifier in "lexical" package`

Plugin is registered in a lexical editor, using normal RichTextPlugin.

## The current behaviour

The code does not compile.

## The expected behaviour

Code should compile

## Impact of fix

I believe that the problem can impact developers using React.

**Comment by etrepum** [comment]
`createEmptyEditorState` is not a public API and is not exported by the `'lexical'` module
