### ISSUE TITLE
Question/Help: HTMLNode (tldr; don't strip unknown tags, but rather fallback them to readonly HTMLNode if such node would be passed to config)

### ISSUE THREAD

**Issue by Kamyil** [facebook/lexical#6647]
Hi! 
For last 2 weeks I was trying to implement a feature, where you could pass some unknown (for Lexical) HTML tags like iframe or dialog and Lexical would still render them instead of stripping them away on html import/export. 
Such feature would be nice, because it would allow user to add his own HTML if some node/functionality would not be implemented yet and it would still be at least visible
in the editor (while being readonly ofc. because Lexical would not have any way to know how to handle this)

So I tried to do it ...aaand I'm still struggling. I may have some knowledge gaps or didn't maybe read the docs accordingly, and if that's the case ->
I'm truly sorry and I hope maybe this discussion would help other people with this issue as well, because I didn't find any reliable solution yet :/

The solution I tried so far:
I've created the `HTMLNode` that would represent such unknown tags as some kind of fallback
```ts
import {
  DecoratorNode,
  type DOMConversionMap,
  type DOMConversionOutput,
  type EditorConfig,
  type LexicalEditor,
  type LexicalNode,
  type NodeKey,
} from 'lexical';

/** 
 * Fallback node that allows unrecognized HTML tags to at least be visible in the WYSIWYG editor.
 * Any content wrapped in HTMLNode will be readonly ofc., because Lexical would not have any way to know how to handle these tags.
 */
export class HTMLNode<SomeHtmlElement = HTMLElement> extends DecoratorNode<SomeHtmlElement> {
  __html: string;

  static getType(): string {
    return 'html';
  }

  static clone(node: HTMLNode): HTMLNode {
    return new HTMLNode(node.__html, node.__key);
  }

  constructor(html: string, key?: NodeKey) {
    super(key);
    this.__html = html;
  }

  getWritable() {
    return this;
  }

  createDOM(config: EditorConfig): HTMLElement {
    const wrapper = document.createElement('div');
    wrapper.innerHTML = this.__html;
    return wrapper;
  }

  updateDOM(): false {
    return false; // No need to update the DOM after creation
  }

  decorate(editor: LexicalEditor, config: EditorConfig): SomeHtmlElement {
    // not really sure what should I pass here. Lexical requires me to extend this method
    // but I don't really have anything to return here.
    return document.createElement('div') as SomeHtmlElement;
  }

  // Fallback DOM conversion for unrecognized tags
  static importDOM(): DOMConversionMap {
    return {
      '*': (node: Node) => ({
        conversion: (domNode: Node): DOMConversionOutput | null => {
          if (domNode.nodeType === Node.ELEMENT_NODE) {
            const element = domNode as HTMLElement;
            const htmlContent = element.outerHTML;
            return { node: new HTMLNode(htmlContent) };
          }
          return null;
        },
        priority: -1, 
        // ^ I know it might be wrong, but I need some way to tell Lexical
        // that this node is lower in priority than any other Node with priority=0 (like TextNode)
      }),
    };
  }

  exportDOM(): { element: HTMLElement } {
    const parser = new DOMParser();
    const doc = parser.parseFromString(this.__html, 'text/html');
    const element = doc.body.firstElementChild as HTMLElement;
    return { element };
  }

  exportJSON() {
    return {
      type: 'html',
      html: this.__html,
      version: 1,
    };
  }
}

export function $createHTMLNode(html: string): HTMLNode {
  return new HTMLNode(html);
}

export function $isHTMLNode(node: LexicalNode | null | undefined): node is HTMLNode {
  return node instanceof HTMLNode;
}
```

and everything is cool, but then the problem arises when you try to do import&export with `$generateHtmlFromNodes()` and `$generateNodesFromDOM()`,
because I didn't found the way to somehow hook into these functions and tell them to not strip the unknown html tags away.
I know that you can set the priority in the `importDOM` method, but since the lowest priority (at least according to types) is `0` and there are some nodes in lexical packages that
have some tags assigned to that priority, it would require me to override every node to set the priority higher, which would maybe work but it will not be an elegant solution

So I've also tried another approach and I tried to write my own custom import/export html functions that:
- for import: it checked if some tag is recognizable by Lexical and if so 
        -> convert to that node using standard `$generateNodesFromDOM()`, if not then use custom `$generateHtmlNode()`. But the problem also is that `$generateNodesFromDOM`
        does not simply accept the html tag but it rather accepts the selection in second argument, so it requires to do the proper selection of separate dom parts to 
        generate the html out of them and then glue them all together at the end, which... is very problematic, because there are ton of edge-cases where it would not work simply this way
        
- and for export -> it would not ignore the unknown tags but rather exportTheDOM directly 

but yeah, as I mentioned. It is extremely tricky to make this working properly for most of basic cases. Custom functions either moved the text nodes away from paragraphs, 
or close each list items inside their own ul's or appended unnecessary paragraphs on each import/export 

I'm writing this as a Feature request, because I'm not really sure which request type would fit the best for it. 
I thought maybe feature/node like this in `@lexical/html` package would be very nice and convenient, 
since it's a common feature for WYSIWYGs to handle any html, but I will understand if you decide that would not be in Lexical scope.
I'm just asking if there is maybe some obvious way to do this and make it mostly working and if so, how should I tackle this? Which approach should I take?

Thanks for your work!

**Comment by etrepum** [comment]
There's no fallback in importDOM, all html tag names must be known in advance. `'*'` won't work

**Comment by Kamyil** [comment]
Sorry, for a late response, we were testing it and most likely it works :o
So as you mentioned, I needed to explicitly state every single html tag I wanted to convert into that `HTMLNode` inside returned object of `importDOM()` method. 

Thank you so much!
