### ISSUE TITLE
Feature: Support Custom Color for Table Selection Highlight

### ISSUE THREAD

**Issue by dineug** [facebook/lexical#6655]
## Description

I am working on a Lexical Editor for dark themes. It would be great to support custom colors for table selection highlights.

https://github.com/user-attachments/assets/86ef7a54-56cb-4dff-8177-03265b6c11b0

## Impact

This will help achieve a higher-quality dark theme.

**Comment by etrepum** [comment]
@zurfyx is there a reason why this selection color is hard-coded as a style, rather than implemented as a class and/or using css custom properties?
