### ISSUE TITLE
Add test for removing link from a node

### ISSUE THREAD

**Issue by potatowagon** [facebook/lexical#6665]
removing link from a text node works, but not when the node has children (like mark node). This PR fixes it https://github.com/facebook/lexical/pull/6656/files. whats left is to add test

**Comment by vantage-ola** [comment]
@potatowagon still working on the tests?

**Comment by potatowagon** [comment]
@vantage-ola feel free to pick this up!

**Comment by vantage-ola** [comment]
@potatowagon while writing the test, i noticed i couldnt use the MarkNode(for the instance a node has children)  bcos its not in the testenv

`Create node: Attempted to create node MarkNode that was not configured to be used on the editor.`

The approach I took was to use TextNode.format() to simulate marknode...but i guess that approach is slightly off.. 

```
      await editor.update(() => {
        const paragraph = new ParagraphNode();
        const precedingText = new TextNode('some ');
        const linkNode = $createLinkNode('https://x.com', { rel: 'noreferrer' });
        const markNode = new TextNode('text');
        markNode.setFormat(2); // Using format to simulate mark node since we don't have MarkNode in test env

        paragraph.append(precedingText);
        linkNode.append(markNode);
        paragraph.append(linkNode);
        $getRoot().append(paragraph);
      });
```

**Comment by etrepum** [comment]
Yes, adding it to the nodes list in the editor configuration should allow you to create the node, assuming that is the array used for that configuration.
