### ISSUE TITLE
Bug: removeText misbehaves for text nodes in token mode

### ISSUE THREAD

**Issue by adrianmxb** [facebook/lexical#6687]
Lexical version: 0.18.0

## Steps To Reproduce

1. Create a text node in `token` mode
2. Try to partially delete the text
3. It will mutate the node, even though, according to the docs, `token` nodes are immutable and will be deleted all at once.

Link to code example:

You can check it out on the current playground.

## The current behavior

When removing text, text nodes in `token` mode aren't deleted in full, but rather a new non-`token` node is created. This is the expected behaviour for `segmented` nodes, but not for `token` nodes.

## The expected behavior

When I remove text that is part of a `token` text node, the entire `token` text node is deleted.

## Impact of fix

The current version is not complying with the documented behaviour of `token` nodes, which can cause issues for everyone that is using TextNodes in `token` mode. Also, this is a regression introduced in #6456

**Comment by adrianmxb** [comment]
@potatowagon @ivailop7 do you see the possibility to ship this as a patch, as it is breaking behaviour for `token` nodes? We'd otherwise be stuck on 0.17.1 until the next minor release comes out. Would really appreciate to see that! 🙌

**Comment by ivailop7** [comment]
You can use the nightly build to pick the latest changes until we publish a patch.

**Comment by etrepum** [comment]
The next nightly build (0.18.1-nightly.20241003.0) should include #6690, should be published in a few hours
