### ISSUE TITLE
Bug: Codeblock removes text when node is created

### ISSUE THREAD

**Issue by MichalPaszowski** [facebook/lexical#6715]
Lexical version: 0.13 - 0.18

## Steps To Reproduce

1. Type ```test
2. Hit space
3. Codeblock is created, text "test" disappears

Link to code example:

## The current behavior
Codeblock node appears, text inside is lost
## The expected behavior
Codeblock node appears, text inside is appended inside codeblock

## Impact of fix
Everyone who is using Markdown in Lexical will be impacted :)

**Comment by etrepum** [comment]
This is because code blocks using ```` ``` ```` are assumed to be a multi-line code block where the first word is the language used

**Comment by MichalPaszowski** [comment]
Ah, haven't thought about that. 

Thanks
