### ISSUE TITLE
Bug: LexicalTypeaheadMenuPlugin  SSR error: `ReferenceError: document is not defined`

### ISSUE THREAD

**Issue by luisrudge** [facebook/lexical#6716]
It was mentioned [before](https://github.com/facebook/lexical/issues/1177#issuecomment-1022094859)  that you have a util to check if the DOM can be used. I don't think this check is being used in the `LexicalTypeaheadMenuPlugin`, considering I'm getting 
this error:

```
ReferenceError: document is not defined
    at useMenuAnchorRef (....../node_modules/@lexical/react/LexicalTypeaheadMenuPlugin.dev.mjs:337:74)
    at LexicalTypeaheadMenuPlugin (....../node_modules/@lexical/react/LexicalTypeaheadMenuPlugin.dev.mjs:534:28)
```

I'm running a remix project and trying to import the playground. I ran into all sorts of problems, so I used `React.lazy` to import the component only in the frontend. That solved all of the issues, however the above error is logged during server rendering.

**Comment by brooksbp** [comment]
FWIW, I moved my usage of lexical into a component and then imported it with:

```typescript
const ComponentXYZ = dynamic(() => import('./ComponentXYZ'), {ssr: false})
```

and that resolved the issue.

**Comment by bedre7** [comment]
Can I work on this?

**Comment by nilaygit-10721** [comment]
can you assign me this issue?
