### ISSUE TITLE
Feature: TableNode does not retain the cell width when copying and pasting a table from another spreadsheet

### ISSUE THREAD

**Issue by HoosLab** [facebook/lexical#6721]
As stated in the title, there is an issue where the cell width is not retained when copying a table from a Google Drive spreadsheet and pasting it.

Specifically, I want to retain the width defined in the <col /> tags within the <colgroup/> tag, but after extending the TableNode, the TableCellResizerPlugin no longer works properly. The method I used to extend it is as follows.

```
import {TableNode} from '@lexical/table';
import {
  $applyNodeReplacement,
  DOMConversionMap,
  DOMConversionOutput,
} from 'lexical';

export class ExtendedTableNode extends TableNode {
  static getType(): string {
    return 'my-table';
  }

  static clone(node: TableNode): TableNode {
    return new ExtendedTableNode(node.__key);
  }

  static importDOM(): DOMConversionMap | null {
    return {
      table: (_node: Node) => ({
        conversion: $convertTableElement,
        priority: 1,
      }),
    };
  }
}

export function $convertTableElement(
  domNode: HTMLElement,
): DOMConversionOutput {
  const tableNode = $createTableNode();
  if (domNode.hasAttribute('data-lexical-row-striping')) {
    tableNode.setRowStriping(true);
  }
  const colgroup = domNode.querySelector('colgroup');
  const colWidths: number[] = [];

  if (colgroup) {
    const cols = colgroup.querySelectorAll('col');
    cols.forEach((col) => {
      const width = col.style.width || col.width;
      if (width) {
        colWidths.push(parseInt(width, 10));
      }
    });
    tableNode.setColWidths(colWidths);
  }
  return {node: tableNode};
}

export function $createTableNode(): TableNode {
  return $applyNodeReplacement(new ExtendedTableNode());
}
```

I’m wondering if there is an alternative method to achieve this.

**Comment by etrepum** [comment]
You don't show your editor node configuration but I suspect you might not be using the withKlass option which is required for cases where replaced nodes are expected to "inherit" transforms and mutation listeners from their base class.

**Comment by HoosLab** [comment]
It’s working well! I thought there was an infinite loop when I used withKlass before, but I guess I was mistaken. Thank you so much!
