### ISSUE TITLE
Feature: Drag and drop icon will be changed after using

### ISSUE THREAD

**Issue by xushuaiABC** [facebook/lexical#6722]
When I use firefox,it's always normal,like:
![image](https://github.com/user-attachments/assets/bf151bee-4d4e-432a-8bc4-97d4b7965160)
but when I use chrome or edge,the drag and drop icon will be changed like this:
![image](https://github.com/user-attachments/assets/23de7a6a-7e03-4c56-bc81-e2531f78f36f)
![image](https://github.com/user-attachments/assets/3f0118f2-b793-4480-b035-df6880ca654e)
May I inquire if we can establish a mutually consistent agreement?
Looking forward to reply

**Comment by etrepum** [comment]
Fairly certain that this is the browser's UI, not lexical's. If it's customizable it would be through some browser specific CSS

**Comment by xushuaiABC** [comment]
> Fairly certain that this is the browser's UI, not lexical's. If it's customizable it would be through some browser specific CSS

Yes, need to adjust the browser scroll bar style, thanks for answering
