### ISSUE TITLE
Feature: Add Maximum Change Limit and Optimization for Lexical History Plugin

### ISSUE THREAD

**Issue by dineug** [facebook/lexical#6728]
## Description

After reading [this article](https://emergence-engineering.com/blog/lexical-prosemirror-comparison), I traced where memory usage increases and found that it differs depending on whether the Lexical history plugin is enabled in the production build environment.

It would be helpful if the Lexical history plugin had an option to set a maximum limit on change history. Additionally, optimizing how changes are stored could improve performance.

### Use HistoryPlugin
![Lexical-JSHeapUsedSize](https://github.com/user-attachments/assets/bd4a69cd-be48-4fbf-ba1e-96b1e0d9ba6f)

### None HistoryPlugin
![Lexical-JSHeapUsedSize](https://github.com/user-attachments/assets/fb2d836b-51bd-4076-8588-78e2591189ad)

## Impact

This feature would enhance the user experience when editing large documents by providing smoother performance.

**Comment by etrepum** [comment]
It is possible to manage the history size without any additions, since the data structures are public. Something like this (untested):

```ts
function pruneHistoryListener({redoStack, undoStack}: HistoryState, maxHistory: number): UpdateListener {
  return () => {
    redoStack.length = Math.max(0, Math.min(maxHistory, redoStack.length));
    undoStack.length = Math.max(0, Math.min(maxHistory - redoStack.length, undoStack.length));
  };
}

function LimitedHistoryPlugin(props: {
  delay?: number = 1000;
  maxHistory?: number = 50;
  externalHistoryState?: HistoryState;
}) {
  const historyState = useMemo(() => externalHistoryState || createEmptyHistoryState(), [externalHistoryState]);
  const [editor] = useLexicalComposerContext();
  useEffect(() => {
    return mergeRegister(
      registerHistory(editor, historyState, delay),
      editor.registerUpdateListener(pruneHistoryListener(historyState, Math.max(0, maxHistory))),
    );
  }, [editor, historyState, delay, maxHistory]);
  return null;
}
```

**Comment by etrepum** [comment]
Of course if you were looking for something more precise about memory usage you'd probably want to consider the number of nodes in history (weight each history entry by the size of its nodeMap) rather than the number of history entries. Creating a more efficient data structure than simply referencing all EditorStates is an even better option, but with a lot more complexity.

**Comment by dineug** [comment]
I tested it based on maxHistory 100, and it was very effective!
Thank you! @etrepum 

![JSHeapUsedSize-nodeCount](https://github.com/user-attachments/assets/1a619868-5e97-4b22-8b0b-56a4b8925ad4)
