### ISSUE TITLE
Feature: Add keyboard shortcuts so the editor is much more accessible

### ISSUE THREAD

**Issue by BennyAlex** [facebook/lexical#6734]
More many things there are no keyboard shortcuts provided out of the box.
This is very bad escpacially for screenreader / only keyboard users, because it is very annoying and time consuming to go throu each menu just to make someting a headline or insert a list.

I would recommend to use the same keys as word where possible, many users are already familiar with them.

**Comment by etrepum** [comment]
A more helpful feature request would list specific actions and their associated keyboard shortcuts you would like the editor to have. This isn't very actionable as-is

**Comment by BennyAlex** [comment]
Sure https://support.microsoft.com/en-us/office/keyboard-shortcuts-in-word-95ef89dd-7142-4b50-afb2-f762f663ceb2

Sure here is an uncomplete list:

Decrease the font size by 1 point. | Ctrl+Left bracket ([)
Increase the font size by 1 point. | Ctrl+Right bracket (])

Center the text. | Ctrl+E
Justify the text. | Ctrl+J
Align the text to the left. | Ctrl+L
Align the text to the right. | Ctrl+R

Indent the paragraph. | Ctrl+M
Remove a paragraph indent. | Ctrl+Shift+M
Remove paragraph formatting. | Ctrl+Q

Apply the Normal style. | Ctrl+Shift+N
Apply the Heading 1 style. | Ctrl+Alt+1
Apply the Heading 2 style. | Ctrl+Alt+2
Apply the Heading 3 style. | Ctrl+Alt+3

Apply subscript formatting. | Ctrl+Equal sign ( = )
Apply superscript formatting. | Ctrl+Shift+Plus sign (+)

**Comment by etrepum** [comment]
We don't generally use issue assignments but you're welcome to work on this one and submit a PR when you have a solution!

**Comment by etrepum** [comment]
When looking into this, make sure to also consider Mac keyboard shortcuts, which may be different in many cases. For example, most Mac keyboard shortcuts use Cmd instead of Ctrl but Cmd-L is reserved in the browser to select the URL bar, Cmd-M is minimize window, etc.

**Comment by bedre7** [comment]
Ok noted, thanks for the heads-up!

**Comment by agscripter** [comment]
I like this feature. @bedre7 let me know if I can help you.

**Comment by BennyAlex** [comment]
> When looking into this, make sure to also consider Mac keyboard shortcuts, which may be different in many cases. For example, most Mac keyboard shortcuts use Cmd instead of Ctrl but Cmd-L is reserved in the browser to select the URL bar, Cmd-M is minimize window, etc.

Yes you can just check for either cmd or ctrl key.
Also Ctrl + L opens the bar on windows. But you can prevent this and I think I makes sense while the user is in the editor to use common text shortcuts and disable the browser ones.

**Comment by bedre7** [comment]
> > When looking into this, make sure to also consider Mac keyboard shortcuts, which may be different in many cases. For example, most Mac keyboard shortcuts use Cmd instead of Ctrl but Cmd-L is reserved in the browser to select the URL bar, Cmd-M is minimize window, etc.
> 
> Yes you can just check for either cmd or ctrl key. Also Ctrl + L opens the bar on windows. But you can prevent this and I think I makes sense while the user is in the editor to use common text shortcuts and disable the browser ones.

Some browser shortcuts can not be overridden unfortunately, they are reserved for the browser. Look at this: https://stackoverflow.com/questions/38838302/any-way-to-override-ctrln-to-open-a-new-window-in-chrome. Therefore, I'm adopting the Google Docs keyboard shortcuts which are better suited for web apps since Google Docs is a web app, unlike Microsoft Word.

**Comment by etrepum** [comment]
I agree that emulating google docs would be a better strategy here, since it is also very popular but is web native so is subject to the same constraints. I don't think that overriding native shortcuts when a lexical editor happens to be focused is the best option.

**Comment by BennyAlex** [comment]
Sounds good. Maybe there should be an info icons in the toolbar as well that opens a list of all available shortcuts?

**Comment by bedre7** [comment]
> Sounds good. Maybe there should be an info icons in the toolbar as well that opens a list of all available shortcuts?

That's a good point, I have already done that. I'm writing some e2e tests. I will open PR once I'm done with that.

**Comment by BennyAlex** [comment]
I cant use all shortcuts in google docs correctly.
They show ctrl+alt+2 for headline 2 but using that will print ² . I am using a german keyboard maybe thats why but it's something we should check in lexical

**Comment by BennyAlex** [comment]
> > Sounds good. Maybe there should be an info icons in the toolbar as well that opens a list of all available shortcuts?
> 
> That's a good point, I have added the shortcuts next to all toolbar items. I'm writing some e2e tests. I will open PR once I'm done with that.

Can the list then also be extended easily so custom plugins can register a shortcut and let it display it there? Maybe there should be a new mechanism altogether like registerShortCut(MY_COMMAND, [CommandOrControllKey, 'L'] that will globally manage all shortcuts for the editor?
Would help with internalization and different platforms and give warnings if the same keys are used multiple times.

**Comment by etrepum** [comment]
I think at this point it would be best to ship the shortcuts in a playground plug-in that others can copy/paste/modify into their app, with a documentation or FAQ entry about keyboard shortcuts that points to it, rather than force some default behavior at a lower level or come up with some ad-hoc configuration system to support it all right out the gate.

**Comment by bedre7** [comment]
> I think at this point it would be best to ship the shortcuts in a playground plug-in that others can copy/paste/modify into their app, with a documentation or FAQ entry about keyboard shortcuts that points to it, rather than force some default behavior at a lower level or come up with some ad-hoc configuration system to support it all right out the gate.

That makes sense. Thank you for your suggestion, I will move the new shortcut listeners to the playground.

**Comment by BennyAlex** [comment]
> I think at this point it would be best to ship the shortcuts in a playground plug-in that others can copy/paste/modify into their app, with a documentation or FAQ entry about keyboard shortcuts that points to it, rather than force some default behavior at a lower level or come up with some ad-hoc configuration system to support it all right out the gate.

Why is that so many features are not built in but like optional to include? I sure understand its more customziable this way but for stuff that is important for accessibility this should come by default and should focus on providing an editor with as few barriers as possible, even this means we lose some customization or makes it harder.
The web is still so inaccessible today, many developers dont know how to implement it correctly and on the other hand there are many regions (eg EU) that have more and more rules for websites (wich is good) to be accessible. So this is a topic where such a libary should enforce a certain degree of accessiblity by default.

**Comment by etrepum** [comment]
Because it's a framework for building any sort of text editor, there are a lot of different requirements for each use case. It's easier or at least less error-prone to assemble one from minimal components and configuration than to start with something suited for one specific use case and overriding/disabling functionality.

**Comment by bedre7** [comment]
> I think at this point it would be best to ship the shortcuts in a playground plug-in that others can copy/paste/modify into their app, with a documentation or FAQ entry about keyboard shortcuts that points to it, rather than force some default behavior at a lower level or come up with some ad-hoc configuration system to support it all right out the gate.

It's a good idea to create a plug-in for the shortcuts, but there are some shared states and functions with the `ToolbarPlugin`. I was thinking of creating a new Context for the toolbar, something like `useToolbar`, and using it for both the `ToolbarPlugin` and `ShortcutsPlugin` to avoid having to lift the state up to the `Editor` and passing down too many props. What do you think?

**Comment by BennyAlex** [comment]
> > I cant use all shortcuts in google docs correctly. They show ctrl+alt+2 for headline 2 but using that will print ² . I am using a german keyboard maybe thats why but it's something we should check in lexical.
> > They also say ctrl+shift+plus to increase font size but it will zoom in. Not sure if google is a good example here lol
> 
> Yes, some of them might not work for all languages and keyboards as noted here: https://support.google.com/docs/answer/179738?hl=en&co=GENIE.Platform%3DDesktop&oco=1#zippy=%2Cpc-shortcuts. I think it's Ctrl+Shift+. to increase font size.

In word alt + 1,2,3 applies the heading style, which also works for me in the browser. Google docs shift+alt+123, only works with 1 for me.

**Comment by bedre7** [comment]
I think it's Ctrl+Alt+123 for heading styles in Google Docs. I'm adding the shortcuts to the playground with a shortcut plug-in. You will be able to customize the key bindings by tweaking the plug-in in your app.

**Comment by BennyAlex** [comment]
> I think it's Ctrl+Alt+123 for heading styles in Google Docs. I'm adding the shortcuts to the playground with a shortcut plug-in. You will be able to customize the key bindings by tweaking the plug-in in your app.

yes but this shortcut does not work on german keyboard but just using alt+123 does! So why choose this more complicated and less supported shortcut if the other is just better?
