### ISSUE TITLE
Bug: TableSelection no method called hasFormat

### ISSUE THREAD

**Issue by tipsxBase** [facebook/lexical#6753]
v0.18.0 TableSelection no method called hasFormat
![image](https://github.com/user-attachments/assets/17d8f9fa-71c7-43ed-8fb7-c174bb92affc)

**Comment by tipsxBase** [comment]
I compared the code on the main branch with the v0.18.0 tag and the npm version, and found that the TableSelection in the main branch has a hasFormat method, but neither the npm version nor the v0.18.0 tag have this method.

**Comment by etrepum** [comment]
You can wait for the next release or use one of the more recent nightly releases on npm. It's not expected that you should be able to always use unreleased code and have it be compatible with older versions.
