### ISSUE TITLE
Feature: async exportDOM

### ISSUE THREAD

**Issue by JustinVoitel** [facebook/lexical#6757]
## Description
We use a custom file plugin to maintain uploaded "files" which are stored in an external blob storage. When using `$generateHtmlFromNodes` we want to fetch the data for each "file" from our blob storage and render them as a Anchor tag containing the base64 converted data. For example
```ts
export class FileNode extends DecoratorNode<any> {
//...
  exportDOM(): DOMExportOutput {
    const element = document.createElement("a");

    const res = await fetch(`https://my-blob/${this.__id}`);
    const base64Data = await res.text();

    element.setAttribute("href", `data:${this.__mimeType};base64,${base64Data}`);
    element.setAttribute("download", this.__fileName);
    element.textContent = this.__fileName;
    return { element};
  }
//...
```

Therefore we would need the exportDOM function of our DecoratorNode to be async (or the after API) to be able to make fetch requests. 

Is there currently any way to make this possible ?

**Comment by etrepum** [comment]
No, everything that happens in an editor read or update must be synchronous. You'll have to put together your own mechanism for preparing these nodes for export so that the data is cached before you call export.
