### ISSUE TITLE
Bug: When I type : in the editor, it becomes unresponsive.

### ISSUE THREAD

**Issue by Nagendra7509** [facebook/lexical#6768]
I'm trying to enter a date in the editor (ex: `26-10-2024 10:00:00`). However, after typing `26-10-2024 10:00` and pressing `:` the editor freezes and becomes unresponsive to any clicks.

https://github.com/user-attachments/assets/8b1593e4-c07a-4f3f-b270-a08c398bddf3

Lexical version: 0.18.0

I am using Lexical in Chrome browser (`Version 127.0.6533.88 (Official Build) (64-bit)`)

## NOTE: I've identified that this issue is caused by the `MarkdownShortcutPlugin`.

**Comment by vantage-ola** [comment]
yes, i noticed that too..
even on the latest `v0.19.0` build

**Comment by vantage-ola** [comment]
you working on it?

 @Nagendra7509

**Comment by Nagendra7509** [comment]
I’m not actively working on it; I’ve only identified the plugin responsible for the issue. I haven’t explored the specific cause within the plugin.
