### ISSUE TITLE
Bug: getTextContent() get wrong value in RichTextPlugin

### ISSUE THREAD

**Issue by jackple** [facebook/lexical#6783]
Lexical version: 0.19.0

## Steps To Reproduce

1. Input break line text in RichTextPlugin
2. Input break line text in PlainTextPlugin

Link to code example: https://stackblitz.com/edit/facebook-lexical-9rmpdr?file=src%2FApp.tsx

https://github.com/user-attachments/assets/538d47b2-bff9-4be4-a0d8-5716b06c9739

## The current behavior
get 4 \n in RichTextPlugin

## The expected behavior
same like PlainTextPlugin

**Comment by etrepum** [comment]
The extra linebreak between each paragraph tag is expected in rich text mode. Plain text mode has everything in one paragraph tag.

**Comment by jackple** [comment]
@etrepum How can I get the same value?

**Comment by jackple** [comment]
If I use Enter + Shift to line break, it will appear 3 \n, 😄, weird!!!

**Comment by jackple** [comment]
plugin.ts:
```ts
if (useRichTextPlugin && event?.key == 'Enter' && event?.shiftKey) {
  event.preventDefault()
  editor.dispatchCommand(INSERT_PARAGRAPH_COMMAND, undefined)
  return true
}
```

getText.ts:
```ts
function getText() {
  return useRichTextPlugin ? text.replace(/\n\n/g, '\n') : text
}
```

For now, I resolve it in this way.
