### ISSUE TITLE
Bug: Tabs do not show strikethrough

### ISSUE THREAD

**Issue by JoeHart** [facebook/lexical#6808]
👋  Howdy maintainers, first of all big fan of the library! Thanks for all the hard work you put into this great software.

Lexical version: 0.19.0

## Steps To Reproduce

1. Go to lexical playground at https://playground.lexical.dev/
2. Type in `Hello	foo` which is hello press the Tab key then foo.
3. Select all the text
4. Format as strikethrough
5. unselect the text
This then shows only the typed text as struck through, the tab is blank.

<img width="1324" alt="Screenshot 2024-11-07 at 16 44 14" src="https://github.com/user-attachments/assets/e38201b4-d4ec-4268-90e2-6f781cc5d452">

Link to code example:
https://playground.lexical.dev/

## The current behavior

Tabs do not have a strikethrough.

## The expected behavior

Tabs should have strike through.

## Impact of fix
Would keep formatting consistent between lexical and other text editors.

**Comment by etrepum** [comment]
This is basically a CSS issue, TabNode creates a span with only whitespace as content, and CSS won't do a strikethrough in that case since there isn't any "text".

**Comment by rohit-patil18** [comment]
Just as @etrepum said, it is a CSS issue. The strikethrough can be seen when the text is selected as shown in this image.

![image](https://github.com/user-attachments/assets/21355a98-3960-4a3a-9bc0-04063c134887)

**Comment by JoeHart** [comment]
Thanks for suggesting where the issue is arising, its caused by CSS yes but I think its still a bug. Lexical is essentially "pretending" to be a text editor. If you are in a normal text editor, for example this one you would expect strikethrough to display on whitespaces like tabs. ~~Foo				Bar~~ (Though interestingly github shrinks white space 😅 )

**Comment by etrepum** [comment]
The context I'm providing is guidance for whomever wanted to work on it. We currently have a number of new contributors looking for issues to help with and this is a fairly straightforward one.

**Comment by turnerguo** [comment]
Lexical root class has `.ContentEditable__root { white-space: pre-wrap; }` setting which will keep any white space's original style, I guess it was intentionally make any text styles as what user inputs. And for Github they use the css default setting `white-space: normal;` which will shrinks white spaces by default.
Anyway, I think this depends on how Lexical want to deal with strikethrough style, and I think there is no perfect answers, just pick one as Lexical's standard. 😃
