### ISSUE TITLE
Bug: [lexical-link] can't add link successful

### ISSUE THREAD

**Issue by leiyourong** [facebook/lexical#6821]
Lexical version: v0.20.0

## Steps To Reproduce

1. Go to lexical playground
2. Type in any word inside the table
3. Click link toolbar, type in any url and then click confirm   ##button
4. After that, type in any word outside the table
5. Click link toolbar, type in any url and then click confirm button

## The current behavior
the links inside and outside table are reset to 'https://'
https://github.com/user-attachments/assets/8ecf15aa-04eb-48c1-867e-6e0d90a33c4e

## The expected behavior
set correct url to link

**Comment by YabeeKim** [comment]
I also have a similar issue where the URL was not saved while using the collaboration plugin.

**Comment by citruscai** [comment]
i will start working on trying to solve this

**Comment by citruscai** [comment]
it seemsl ike this isnt just a lexical-table issue but an issue within the link?
