### ISSUE TITLE
Bug: calculateZoomLevel missing in Flow?

### ISSUE THREAD

**Issue by Dagur** [facebook/lexical#6823]
Lexical version: 0.20.0

## Steps To Reproduce

1. Try import { calculateZoomLevel } from "@lexical/utils";
2. Get missing-export error from flow

Link to code example:

Just enable flow and try this import

```
import { calculateZoomLevel } from "@lexical/utils";
```

## The current behavior
The function works like it should but a $FlowFixMe is needed to suppress the flow error

## The expected behavior
No Flow error

## Impact of fix

Low severity

**Comment by hadiham** [comment]
Hi @Dagur  and @etrepum 

My partner @RommyT1 and I are students from the University of Michigan working on a Software Engineering course project, where we contribute to open-source software. My partner and I would like to take on this issue as it aligns well with our coursework requirements, and we’re interested in helping improve lexical!

Could you please assign this issue to us? We were able to reproduce this issue locally, and we’d be happy to work on developing and testing a solution. We will make sure to maintain high code quality and follow lexical and facebook's standards.

Thank you for considering our request!

**Comment by hadiham** [comment]
Hi @Dagur and @etrepum 

@RommyT1 and I have implemented a potential fix for this issue. We added the missing calculateZoomLevel declaration in LexicalUtils.js.flow to resolve the Flow error. Additionally, while working on this, we noticed a few other functions that were missing Flow type declarations, so we added the following declarations as well:

`declare export function $getNextRightPreorderNode(
  startingNode: LexicalNode,
): LexicalNode | null;
declare export function calculateZoomLevel(element: Element | null): number;
declare export function $isEditorIsNestedEditor(editor: LexicalEditor): boolean;
declare export function objectKlassEquals<T>(
  object: mixed,
  objectClass: Class<T>,
): boolean;
declare export function $filter<T>(
  nodes: Array<LexicalNode>,
  filterFn: (node: LexicalNode) => null | T,
): Array<T>;
declare export function $insertFirst(parent: ElementNode, node: LexicalNode): void;`

When testing these changes we observed that Flow now correctly recognizes these functions and can be used without $FlowFixMe comments.

Please let us know if there are any questions or further adjustments you’d like us to make. Thank you!

**Comment by etrepum** [comment]
If you submit this as a PR we can review it

**Comment by Dagur** [comment]
Thanks!

Þann mán., 18. nóv. 2024, 06:25 Bob Ippolito skrifaði <
***@***.***>:

**Comment by RommyT1** [comment]
> Thanks!

No problem, this was our first time contributing to an open source, I'm glad we could help!

**Comment by etrepum** [comment]
Thank you for your contribution!
