### ISSUE TITLE
Bug: Table Action Menu - clicking on Merge Cells item only works when you click on the text

### ISSUE THREAD

**Issue by umaranis** [facebook/lexical#6829]
Lexical version: latest (0.20.0)

## Steps To Reproduce

1. Open lexical playground
2. Insert a Table
3. Select two or more cells
4. Click the Action Menu button
5. Hover over the first item i.e. 'Merge Cells'

## The current behavior

Only the text is clickable.
![image](https://github.com/user-attachments/assets/b7ef1231-96e2-4129-a140-cd5ac7b8fa50)

## The expected behavior
Full item is clickable
![image](https://github.com/user-attachments/assets/8e99f7a0-f3c4-446a-bbb3-39ec7d25a59a)

## Impact of fix
It is UI issue that may impact user experience.

**Comment by Kingscliq** [comment]
Can I work on this?

**Comment by etrepum** [comment]
There's already a PR open for this

**Comment by etrepum** [comment]
Closed by https://github.com/facebook/lexical/issues/6829
