### ISSUE TITLE
Chore: Change default skipInitialization to false for registerMutationListener

### ISSUE THREAD

**Issue by etrepum** [facebook/lexical#6846]
After #6357 the `skipInitialization` option to `registerMutationListener` was supposed to change to false. The deprecation period is long past, so it's time to change this default and the associated comments/docs.

Search for `skipInitialization` to find them all. Change only the docs and the default (`DEFAULT_SKIP_INITIALIZATION`), do not change any of the code that uses this option (it's already correct).

This change will prevent bugs like https://github.com/wobsoriano/lexical-vue/issues/66

**Comment by Shopiley** [comment]
Hi, can I take this up?

**Comment by elgh0ul** [comment]
Hey @Shopiley and @etrepum, would you mind if me and @Hammoud183 took this up? 

We're students from the University of Michigan taking a course and we're taking a course revolving around practices of software engineering. We're looking to make our first contribution to a open-source github repo for an assignment and this seems like a good first issue for us.

Thanks, Hadi.

**Comment by etrepum** [comment]
Sure, go ahead

**Comment by Shopiley** [comment]
should I change the comments as well or remove them?

![image](https://github.com/user-attachments/assets/4619f97e-beb5-461c-a66a-80aadea93661)

e.g The default was previously true for backwards compatibility with <= 0.16.1
      but this default is now changed to false in <current version>

**Comment by etrepum** [comment]
Yes, use 0.21.0 as the version that it changed

**Comment by Shopiley** [comment]
[like]  Fadekemi ADEBAYO reacted to your message:
________________________________
