### ISSUE TITLE
Feature: Deprecate $nodesOfType

### ISSUE THREAD

**Issue by etrepum** [facebook/lexical#6847]
## Description

The `$nodesOfType` function is no longer used internally, and does not support node overrides. Generally it was used to work around `registerMutationListener` not having an initialization phase, but that changed in #6357, so it's no longer useful and generally just causes bugs.

This function should be marked `@deprecated` with a comment that tells them to use `registerMutationListener` instead, or to remove their explicit legacy initialization for a mutation listener.

## Impact

Using this function causes bugs in apps that use node overrides, we should discourage its use and eventually remove it.

**Comment by CaioSilvaUT** [comment]
Hello, I'm a student from UTFPR in Brazil, and I'm taking a class where I need to contribute to open source issues. I would like to know if I can take on this issue to work on.

**Comment by etrepum** [comment]
Sure, go ahead

**Comment by dabrpio** [comment]
Hey @etrepum, 
you are saying that it was mainly for internal use (btw I don't know why it was exposed) and used as workaround. But I used `$nodesOfType` to get all the nodes of specific class to be able to update them on some user action like so:
```js
[
    ...$nodesOfType(CustomTableNode),
    ...$nodesOfType(SomeOtherNode),
].forEach((node) => { < some node transformation >})
```
Now, when it's deprecated, I need to replace it with something else. It can't be `registerMutationListener` because from what I understand it is for completely different use case. `registerMutationListener` listens to node updates, whereas I need to update some specific nodes based on user's action.
One idea I came up is leveraging `$dfs` function and filtering the nodes based on their type:
```js
$dfs()
    .map(({node}) => node)
    .filter((node) => $isCustomTableNode(node) || $isSomeOtherNode(node))
    .forEach((node) => { < some node transformation >})
```
What do you think about this solution for `$nodesOfType` replacement?

**Comment by etrepum** [comment]
Yes, your $dfs solution is more correct than $nodesOfType and for that kind of use case the performance is not critical.

**Comment by rolandsaven** [comment]
> Hey @etrepum, you are saying that it was mainly for internal use (btw I don't know why it was exposed) and used as workaround. But I used `$nodesOfType` to get all the nodes of specific class to be able to update them on some user action like so:
> 
> ```js
> [
>     ...$nodesOfType(CustomTableNode),
>     ...$nodesOfType(SomeOtherNode),
> ].forEach((node) => { < some node transformation >})
> ```
> 
> Now, when it's deprecated, I need to replace it with something else. It can't be `registerMutationListener` because from what I understand it is for completely different use case. `registerMutationListener` listens to node updates, whereas I need to update some specific nodes based on user's action. One idea I came up is leveraging `$dfs` function and filtering the nodes based on their type:
> 
> ```js
> $dfs()
>     .map(({node}) => node)
>     .filter((node) => $isCustomTableNode(node) || $isSomeOtherNode(node))
>     .forEach((node) => { < some node transformation >})
> ```
> 
> What do you think about this solution for `$nodesOfType` replacement?

I'm was in the same boot. I didn't know about `$dfs`, so looked at the `getAllTextNodes` on `LexicalElementNode`and created my own. You might be able to do the same

https://github.com/facebook/lexical/blob/main/packages/lexical/src/nodes/LexicalElementNode.ts#L384-L398

```
  getAllTextNodes(): Array<TextNode> {
    const textNodes = [];
    let child: LexicalNode | null = this.getFirstChild();
    while (child !== null) {
      if ($isTextNode(child)) {
        textNodes.push(child);
      }
      if ($isElementNode(child)) {
        const subChildrenNodes = child.getAllTextNodes();
        textNodes.push(...subChildrenNodes);
      }
      child = child.getNextSibling();
    }
    return textNodes;
  }
```
