### ISSUE TITLE
Bug: toJSON() and JSON.stringify(editor) do not preserve HTML Entities

### ISSUE THREAD

**Issue by evanjmg** [facebook/lexical#6853]
Lexical version: 0.20.0

## Steps To Reproduce

1. Type <t and onChange editorState.toJSON()
2. Should export  as "&lt;t" and not "<t", if I bold it it should export as <b> &lt;t </b>

create an editor component
<Editor
with normalising to html from a json. We have to support html and json so we end up rendering html in the editor via below. 
```

export const ContentPlugin: FunctionComponent<ContentPluginProps> = ({ content }) => {
  const [editor] = useLexicalComposerContext();

  useEffect(() => {
    editor.update(() => {
      const parser = new DOMParser();
      const dom = parser.parseFromString(content, 'text/html');

      const nodes = $generateNodesFromDOM(editor, dom);

      const validNodesToInsert = nodes.map((node) =>
        node.getType() === 'image' ? $createParagraphNode().append(node) : node
      );

      const initialSelection = $getSelection()?.clone() ?? null;
      $getRoot().clear().select();
      $getSelection().insertNodes(validNodesToInsert);
      $setSelection(initialSelection);
    });
  }, [editor, content]);

  return null;
};
```

## The current behavior
editorState.toJSON() and JSON.stringify(editorState) does not preserve html entities
## The expected behavior
editorState.toJSON() and JSON.stringify(editorState) should preserve html entities
## Impact of fix
anything that starts with with  < should work. See how we insert in code above.

**Comment by etrepum** [comment]
I think whatever you were trying to write was parsed by GitHub's markdown parser, so this issue doesn't really make any sense.

What exactly is the JSON output that you are seeing, and what do you expect to see? HTML entities are just a way to escape text. As soon as the browser parses the document they are gone. There's no expectation that if you import HTML into lexical that it will export the same HTML at all.
