### ISSUE TITLE
[lexical-playground] Bug: Hidden formatting options in text selection on narrow screens or vertical monitors

### ISSUE THREAD

**Issue by vantage-ola** [facebook/lexical#6858]
Lexical version: 0.20.0

The formatting options are present when the browser window is in the normal aspect ratio
![Screenshot 2024-11-23 002629](https://github.com/user-attachments/assets/b9204a19-e0ab-4f28-81bd-36fcd38e22c6)

The formatting options are hidden when the browser window is in narrow/vertical aspect ratios
![54455](https://github.com/user-attachments/assets/0014a49e-db9e-4eab-935d-fe85dd2e84f8)

Was this the intended behaviour?

**Comment by etrepum** [comment]
Yes, search for `isSmallWidthViewport` in the code to see which plugins are disabled on narrower windows. It might make sense to have different widths for each plugin, but that is currently working as designed.

**Comment by vantage-ola** [comment]
the formatting `<FloatingTextFormatToolbarPlugin/>` and its attached plugins inside the viewport that are restricted to certain views coz the format bar at the top contains the necessary format options already... my bad, silly me .

but the comment option at the side might be needed #6859
