### ISSUE TITLE
 [lexical-playground] Bug: Hidden comment button  on narrow screens or vertical monitors

### ISSUE THREAD

**Issue by vantage-ola** [facebook/lexical#6859]
Lexical version: 0.20.0

The comment button are present when the browser window is in the normal aspect ratio
![Screenshot 2024-11-23 003710](https://github.com/user-attachments/assets/b7bdd7d1-e56d-4b48-baae-97a543ef02eb)

The comment button is hidden when the browser window is in narrow/vertical aspect ratios
![Screenshot 2024-11-23 005659](https://github.com/user-attachments/assets/5303bbd8-a0f9-44ff-b185-6e4c5ac7f1ee)

**Comment by vantage-ola** [comment]
very very similar to issue #6858

**Comment by etrepum** [comment]
This is hidden for the same reason, certain plugins are disabled if the width is narrow. https://github.com/facebook/lexical/issues/6858#issuecomment-2495181543

**Comment by vantage-ola** [comment]
the `FloatingTextFormatToolbarPlugin` has a comment button too. so there will be not need for this. so #6858 should get this issue sorted
