### ISSUE TITLE
Bug: Pressing the left arrow key moves the cursor to the last cell of the table when there is an immutable element(contenteditable=false) immediately following the table.

### ISSUE THREAD

**Issue by 3mukulranjan** [facebook/lexical#6870]
Lexical version:0.20

## Steps To Reproduce

1. Navigate to https://playground.lexical.dev/
2. Select "Insert" and choose a 5 by 5 table.
3. Click just below the table, then select "Insert" again and choose "Equation." After naming the equation, insert it.
4. Notice that the cursor is placed just after the inserted equation. Press the left arrow key or Shift+Left arrow key and observe that the cursor moves to the last cell of the table.

## The current behavior
After pressing the left/Shift left, cursor moved to last cell of the table

## The expected behavior
Pressing Shift+Left key should either select the equation or move the cursor to the beginning of the equation text.

https://github.com/user-attachments/assets/6993748b-3137-4f84-a73b-7e14692d8b22

**Comment by etrepum** [comment]
I replaced your zip file recording with the mp4 itself. It's better to have these things inline, it's just more work for everyone to download a zip when they could've viewed the file directly from the issue.
