### ISSUE TITLE
Docs: /docs/react/ "next" button links to itself

### ISSUE THREAD

**Issue by etrepum** [facebook/lexical#6881]
The "Next" button on the page https://lexical.dev/docs/react/ links to itself

              While at this topic, the page for react documentation at https://lexical.dev/docs/react/ has a next button pointed at it's own url. Anyone working on this, please fix that.

_Originally posted by @knownasnaffy in https://github.com/facebook/lexical/issues/1516#issuecomment-2466301945_

**Comment by vantage-ola** [comment]
The next button should link to `Lexical Plugins` right?

**Comment by knownasnaffy** [comment]
> The next button should link to `Lexical Plugins` right?

The next page is supposed to be lexical plugins. So yes.
