### ISSUE TITLE
Feature: Unify $selectAll implementations from lexical and @lexical/selection

### ISSUE THREAD

**Issue by etrepum** [facebook/lexical#6893]
## Description

`$selectAll` is exported from `@lexical/selection` and `lexical`. These functions do slightly different things (the one from `lexical` can create a new `RangeSelection` directly from root, the one from `@lexical/selection` always expands an existing `RangeSelection` and respects shadow roots), but from a user's perspective there's not usually a meaningful difference.

I think we should:

- Change the signature of `$selectAll` from `lexical` to `$selectAll(selection?: RangeSelection | null): RangeSelection` so it can either expand an existing RangeSelection (the `@lexical/selection` semantics) or create/update-and-set a RangeSelection (the `lexical` semantics). I think we should also return the selection (current behavior is void) because it's often useful to have a reference to the selection and it's annoying to separately call `$getSelection()` and assert-or-cast to ensure that it's the RangeSelection that you know it is.
- Remove the `$selectAll` implementation from `@lexical/selection` and replace it with a re-exported and deprecated reference to the one from the `lexical` package

## Impact

It will make it easier to use `$selectAll` in both cases, shrink the bundle size of `@lexical/selection`, and reduce the API surface area.

Monorepo usage:

- The `@lexical/selection` implementation is not used or tested in the monorepo.
- The `lexical` implementation is only used to implement `SELECT_ALL_COMMAND` and in a few unit tests.

**Comment by elgh0ul** [comment]
Hi @etrepum!

Me and @hammoud183 are students from the University of Michigan and we're taking a course based on Software Engineering. We're looking to make our first open source contribution for an assignment and this looks like a great first issue! Would you be willing to assign this issue to us?

Thanks, Hadi

**Comment by etrepum** [comment]
Sure, go ahead. No need for assignment, just submit a PR when you have something ready

**Comment by Sachin-Mahato** [comment]
Hello @etrepum , could you help me? When I change the function's return type in Packages/lexical/src/LexicalUtils.ts, I see a red line. Is it correct to make this change in this file?
![Screenshot 2024-12-03 205854](https://github.com/user-attachments/assets/db8622de-b5bf-44e5-b758-e8dde942333a)

Is it correct to mark the export as deprecated in packages/lexical-selection/src/index.ts?

![Screenshot 2024-12-03 210217](https://github.com/user-attachments/assets/19b9e2e9-461a-4205-8042-1702c99066c9)

**Comment by etrepum** [comment]
The red lines are telling you something, you should look at what the error message for them are and try to fix the error. There are several.

The deprecated comment shouldn't go there, it won't be associated directly with that function. I think you may have to define it with a variable to give it a separate comment from the imported function. There's probably an example of this elsewhere in the code, search for `@deprecated`.

**Comment by elgh0ul** [comment]
Hey @Sachin-Mahato did you figure out your issue? I was planning on work on this but it seems like you're almost finished.

**Comment by elgh0ul** [comment]
Hey @Sachin-Mahato 
Me and my partner are planning to finalize a PR soon. If you have any insights/advice for this issue please let me know.

**Comment by etrepum** [comment]
Based on having to ask about the errors in that screenshot I don't think they are close, if you two have something nearly ready I wouldn't stop working.

**Comment by elgh0ul** [comment]
Hi @etrepum 
Me and my partner have submitted a pull request and are ready to receive feedback 👍 
Thanks, Hadi
