### ISSUE TITLE
Bug: Infinite loop on insert new line on empty layout item node

### ISSUE THREAD

**Issue by basile-savouret** [facebook/lexical#6907]
This issue is related to this pull request here https://github.com/facebook/lexical/pull/6906 .
If we focus an empty layout item and press "enter" to insert a new line the editor goes into an infinite loop and goes into 100% cpu usage without triggering any error.

The issue i want to point out is the infinite loop which will freeze the page and is critical for an end user in my opinion.
And as well the miss of any error which makes this bug difficult to fix for a third party developper.

The bug seems to be triggered when we have a textNode with no paragraphNode as a parent and we press "enter"

Lexical version: 0.21.0

## Steps To Reproduce

1. Go to the playground
2. Create a column layout
3. Write text on 2 different layout items
4. Copy cut both of the texts 
5. focus the right empty layout item and press "enter" in it

## The current behavior

https://github.com/user-attachments/assets/5f01a8be-1884-4442-a7a9-94d0b5fc3d07

## The expected behavior

It would be better to not go into an infinite loop and to have a proper error for this case.

**Comment by etrepum** [comment]
Fixed by #6906
