### ISSUE TITLE
Feature: support $convertFromMarkdownString in a headless environment

### ISSUE THREAD

**Issue by sgb-io** [facebook/lexical#6918]
## Description

Currently, as far as I can tell, `$convertFromMarkdownString` does not work in a headless (Node.js) environment. I believe this may be because it depends on the DOM.

Using the headless editor and calling `$convertFromMarkdownString` on valid markdown content seems to just result in an empty lexical structure being created. It seems like it (silently) fails to create nodes or get some other response back from DOM APIs.

## Impact

This could help users working with the Ghost blogging platform, for example. If a solution was found, it could allow users to benefit from more extensive integrations where editing blog content can be done programmatically, via APIs etc (in particular, allow users to send markdown to Ghost's content API). Currently, awkward conversion steps are required to programmatically update content, or you're forced to work with a more complex format like html.

**Comment by etrepum** [comment]
I don't think this is the case, but even if it was, you can use jsdom in a headless environment when dom is needed

**Comment by sgb-io** [comment]
@etrepum I have tried jsdom as a workaround, with no luck. I even proxied `document` to spy on DOM calls but didn't see any.

Here is a small repro that seems to result in an empty lexical structure:

```typescript
import { $convertFromMarkdownString, TRANSFORMERS } from "@lexical/markdown";
import { CodeNode } from "@lexical/code";
import { createHeadlessEditor } from "@lexical/headless";
import { HeadingNode, QuoteNode } from "@lexical/rich-text";
import { LinkNode } from "@lexical/link";
import { ListNode, ListItemNode } from "@lexical/list";
import { ParagraphNode, TextNode, EditorState } from "lexical";

function convertMarkdownToLexical(markdown: string): string {
  const editor = createHeadlessEditor({
    nodes: [
      HeadingNode,
      ParagraphNode,
      TextNode,
      LinkNode,
      ListNode,
      ListItemNode,
      CodeNode,
      QuoteNode,
    ],
  });

  editor.update(() => {
    $convertFromMarkdownString(markdown, TRANSFORMERS);
  });

  const editorState: EditorState = editor.getEditorState();

  console.log(editorState.toJSON()); // Produces an empty structure

  return JSON.stringify(editorState.toJSON());
}

convertMarkdownToLexical("# This is a heading\n\nThis is some content");
```

Maybe I am missing something?

**Comment by etrepum** [comment]
If you provide something runnable somewhere like stackblitz or codesandbox I'll take a look. In situations where DOM is needed you will need to set globalThis with window and document for the duration of the call.

**Comment by etrepum** [comment]
Ok looking closer at your example, the reason why you're getting an empty editor is that you're using `editor.update` and expecting the update to be reconciled to the editorState synchronously. You need to use `editor.update(…, {discrete: true});` in this use case.

https://lexical.dev/docs/concepts/editor-state#synchronous-reconciliation-with-discrete-updates

**Comment by sgb-io** [comment]
@etrepum you are right, thanks a lot!

The types led me to believe this option was defaulting to `true`:

```
export type EditorUpdateOptions = {
    onUpdate?: () => void;
    skipTransforms?: true;
    tag?: string | Array<string>;
    discrete?: true;
};
```

**Comment by etrepum** [comment]
That type means the opposite, false can't be explicitly specified.
