### ISSUE TITLE
Bug: NPM Packages Removed?

### ISSUE THREAD

**Issue by mchusma** [facebook/lexical#6921]
I'm seeing errors with NPM installations, and it looks like NPM packages may have been removed on accident.
https://www.npmjs.com/package/lexical

<img width="784" alt="image" src="https://github.com/user-attachments/assets/c3c554a4-4a0f-4140-9844-0ea17f343a14">

## Steps To Reproduce

1. Run npm install --save lexical @lexical/react
2. or Run npm install lexical

**Comment by etrepum** [comment]
Not seeing that from here, must be an npm glitch.

**Comment by etrepum** [comment]
See also https://status.npmjs.org/ - looks like they are currently doing an infrastructure upgrade which must be causing problems.

**Comment by mchusma** [comment]
Thank you! Back alive again.
