### ISSUE TITLE
Bug: Copying an email and then pasting pastes only plain text without copied formatting and styles

### ISSUE THREAD

**Issue by EseCurtis** [facebook/lexical#6924]
Lexical version: 0.14.5

## Steps To Reproduce

1. create a lexical input
2. copy any mail from your email and paste 

## The current behavior

it pastes without the formatting on the copied email

## The expected behavior

it should paste with the formatting and styling like a regular content editable div would

## Impact of fix

It is very high pirority and needed before 2 days

**Comment by etrepum** [comment]
It's really up to you to implement custom classes and importDOM implementations that can preserve precisely what you want for your implementation. The default implementation is conservative and only imports styles that are directly supported by the model. More recent versions of the playground demonstrate how you might do this mostly in configuration, which you could follow as a model for your application. See https://github.com/facebook/lexical/blob/v0.21.0/packages/lexical-playground/src/App.tsx#L143-L187 and the code that uses it for example
