### ISSUE TITLE
Bug: RTE components when resizing or scroll doesn't seem to be contained or collapsed

### ISSUE THREAD

**Issue by ritikaGupta4** [facebook/lexical#6926]
RTE components when resizing or scroll doesn't seem to be contained or collapsed.

Lexical version: 0.18.0

## Steps To Reproduce

1. Go to the lexical playground and add lengthy texts to make it scrollable and table
2. Click on table dropdown and scroll the editor.
3. Now you'll see that dropdown is not being contained and not getting attached with table dropdown.

https://github.com/user-attachments/assets/cd24854e-8966-4cde-bc9f-abe4a399309d

Link to code example: https://playground.lexical.dev/

## The current behavior
Components are not getting contained.

## The expected behavior
Make it contained.

**Comment by Srishtihere** [comment]
can I work on this issue ?
