### ISSUE TITLE
Bug: Image becomes unresizable if embedded inside a table

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#6931]
Lexical 0.21

Trying to resize an image when inside a TableCell does not work:

https://github.com/user-attachments/assets/fc07f84a-fe1d-47f3-b30e-51b98d188be4

**Comment by ivailop7** [comment]
Hopefully this is just a CSS z-index type of issue

**Comment by etrepum** [comment]
Yes that is what is happening. If the table cell is at least as large as the image then it works. It would be more clear with `overflow: scroll` or hidden on the table cell (which we could probably just do, particularly in the playground CSS).
