### ISSUE TITLE
Bug: Insert Multiple Rows not working properly

### ISSUE THREAD

**Issue by ritikaGupta4** [facebook/lexical#6933]
Lexical version: 0.18.0

## Steps To Reproduce

1. Go to the lexical playground and insert a table
2. If you try to add multiple rows, only 1 row is added.
Update your function insertTableRowAtSelection:
` const insertTableRowAtSelection = useCallback(
    (shouldInsertAfter) => {
      editor.update(() => {
        for (let i = 0; i < selectionCounts.rows; i += 1) {
          $insertTableRowExperimental(shouldInsertAfter);
        }
        onClose();
      });
    },
    [editor, onClose, selectionCounts.rows]
  );`
3. After updating multiple rows insertion works, but Insert x rows below does not work properly, it adds rows in-between selected rows

https://github.com/user-attachments/assets/0f2d6d2f-52a9-4d19-b018-8d9d1b772a46

Link to code example:
` const insertTableRowAtSelection = useCallback(
    (shouldInsertAfter) => {
      editor.update(() => {
        for (let i = 0; i < selectionCounts.rows; i += 1) {
          $insertTableRowExperimental(shouldInsertAfter);
        }
        onClose();
      });
    },
    [editor, onClose, selectionCounts.rows]
  );`

**Comment by etrepum** [comment]
Can you reproduce with a current version? A lot has changed in tables since 0.18.0

**Comment by ritikaGupta4** [comment]
In current version, I am not able to add multiple rows which I fixed on my end and shared the snippet above

https://github.com/user-attachments/assets/cf184d55-bd1a-4219-a947-b3aa6f3e5f12
