### ISSUE TITLE
Bug: Table selection disappears when using the custom context menu

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#6941]
Lexical 0.21

After the table refactors, when using the custom context menu, after a table multicell selection, right-clicking dismisses the table selection and cannot apply multicell actions - copy, paste, add N rows, etc.

**Comment by ivailop7** [comment]
@etrepum could you help out here

**Comment by etrepum** [comment]
I don't have a lot of time today but you should look at the mousedown/mouseup handlers in the table code to make sure they can ignore the right click. It's probably just trying to make a new selection based on that click.

**Comment by ivailop7** [comment]
> I don't have a lot of time today but you should look at the mousedown/mouseup handlers in the table code to make sure they can ignore the right click. It's probably just trying to make a new selection based on that click.

ack, will check those

**Comment by ivailop7** [comment]
Not critical, I'm travelling these days, but will try to find the time.
