### ISSUE TITLE
Bug: wrong cursor position with CJK keyboard

### ISSUE THREAD

**Issue by mrdivyansh** [facebook/lexical#6946]
`markSelection` utility function affects selection (cursor position) when I use CJK keyboards.

Lexical version: 0.21.0

## Steps To Reproduce

[Demo video](https://drive.google.com/file/d/1JRYiracJf1j2K0Z3uHfQyOLx1Zq6q80Z/view?usp=sharing)

1. Visit [demo](https://codesandbox.io/p/sandbox/confident-germain-9qjp55?file=%2Fsrc%2FEditor.js)
2. Type using CJK keyboard ([How to add CJK keyboard to MacOS?](https://www.koreanfluent.com/cross_cultural/korean_keyboard/korean-keyboard-mac-os-x.htm))

Link to code example:
https://codesandbox.io/p/sandbox/confident-germain-9qjp55?file=%2Fsrc%2FEditor.js

## The current behavior
Cursor jumps to beginning

## The expected behavior
Preserve cursor position where you type.

## Impact of fix
I use `markSelection` to highlight selection when the editor loses focus. It's very important feature for a better user experience. In fact, I believe it should be out of the box feature from Lexical.

**Comment by etrepum** [comment]
I can't reproduce this problem when markSelection is used correctly, e.g. via the SelectionAlwaysOnDisplay plugin. https://playground.lexical.dev/?selectionAlwaysOnDisplay=true&emptyEditor=true

markSelection isn't designed to work when the editor does have already focus, although I do think there are some things in its implementation that could be improved (#6961)

**Comment by DorisJeanParish** [comment]
SSN 260-41-6060
