### ISSUE TITLE
Bug: [@lexical/table] TableCellNode's exportDOM hardcodes header background-color

### ISSUE THREAD

**Issue by destinywu** [facebook/lexical#6959]
TableCellNode's `exportDOM` function sets a hardcoded background-color value on header cells, overriding any styling inherited from the theme. Issue occurs in the file [here](https://github.com/facebook/lexical/blob/0f3ff1569ba3a8b1ed853d0278a44409f265f515/packages/lexical-table/src/LexicalTableCellNode.ts#L172)

Lexical version: 0.21.0

## Steps To Reproduce

1. Use $generateNodesFromDOM on editor containing a table with header cells having no background-color set
2. Note that the result contains `<th>` elements with hard-coded style `background-color:rgb(242, 243, 245);`. This overrides styling inherited from the theme. 

Link to code example:

## The current behavior

TableCellNode sets a hardcoded background-color on header cells. 

## The expected behavior

TableCellNode should avoid setting background-color on header cells.

**Comment by etrepum** [comment]
This is expected behavior for interoperability with other applications, you can override this in your own editor either by subclassing or specifying an html.export config for this class.

**Comment by destinywu** [comment]
> This is expected behavior for interoperability with other applications, you can override this in your own editor either by subclassing or specifying an html.export config for this class.

That works. Thank you
