### ISSUE TITLE
Question: Is there any way to replace create a paragraph with create a linebreak?

### ISSUE THREAD

**Issue by sometinaintright** [facebook/lexical#6962]
Expectation:
Only one paragraph node in the content as the first child of the root, and the lines will be broken up with line break.

Actual:

- Press Enter: get a new paragraph node
- Press Enter + Shift: get a new line break
- Paste multiple lines text: get multiple paragraph nodes

There may be other behaviors that also create paragraphs that I haven't found....

My implementation:
```js
            editor.registerCommand(
                KEY_ENTER_COMMAND,
                (event) => {
                    const selection = $getSelection();
                    if (!$isRangeSelection(selection)) {
                        return false;
                    }
                    event.preventDefault();
                    editor.dispatchCommand(INSERT_LINE_BREAK_COMMAND, false);
                    return true;
                },
                COMMAND_PRIORITY_CRITICAL,
            )
```

Is this only possible with the override command? This may result in me needing to override multiple commands, I wonder if there's an easier way to do this?

**Comment by etrepum** [comment]
I'd use a node transform for this, there are a lot of ways paragraphs can be created

**Comment by etrepum** [comment]
Since this is a question and not an issue I'm going to close this. The Discord server or a Discussions would be a more appropriate place for questions
