### ISSUE TITLE
Bug: TablePlugin: Delete key commands handling - $deleteCellHandler doen't check is current selection in target table

### ISSUE THREAD

**Issue by Ulop** [facebook/lexical#6972]
Lexical version: 0.21.0

## Steps To Reproduce

1. Open playground
2. Remove all content
3. Append first table
4. Append some text 
5. Append second table
6. Select all cell's of second table
7. Press `Del`

## The current behavior
First table removed

## The expected behavior
Second table removed

Most command handlers in `TableSelectionHelpers.ts` check via `$isSelectionInTable` is current selection(`$getSelection()`) point to target table node passed to `applyTableHandlers`.
This check is missing in the `$deleteCellHandler` method.

This results in the command handler being triggered only for the first table registered for subsequent commands.
```ts
for (const command of DELETE_KEY_COMMANDS) {
    tableObserver.listenersToRemove.add(
      editor.registerCommand<KeyboardEvent>(
        command,
        $deleteCellHandler,
        COMMAND_PRIORITY_CRITICAL,
      ),
    );
  }
```
https://github.com/user-attachments/assets/63e8f39a-fdbd-4bd9-8621-f139cd4ed90c

**Comment by Ulop** [comment]
> Since you've already isolated this to the location of the bug, do you want to submit a PR for it? Should be a straightforward contribution

Yes, I'm want to submit

**Comment by etrepum** [comment]
> hey @etrepum, can I pick this issue up? new to open source and would like to start with the library I used in the past

There are a handful of other issues tagged good first issue that you can look through, I think @Ulop is going to handle this one since they have already done most of the work.
