### ISSUE TITLE
Bug: Cannot assign to read only property 'key' of object 

### ISSUE THREAD

**Issue by nsqnsq** [facebook/lexical#6980]
Lexical version:
"lexical": "0.17.1"
**Describe the bug**
When using your [example](https://github.com/mdx-editor/editor/blob/main/src/examples/html.tsx), an error message appears when selecting two lines of text consecutively：Cannot assign to read only property 'key' of object '#
**Reproduction**
 https://github.com/mdx-editor/editor/blob/main/src/examples/html.tsx

**To Reproduce**
1. Select two lines of text  （ar A paragra）
2. Click the button Make selection orange
![image](https://github.com/user-attachments/assets/8805f914-298f-4775-bb35-9c41b10ebe8b)

**Expected behavior**
This is almost certain to happen. I hope it works normally. Thank you.

**Screenshots**
![image](https://github.com/user-attachments/assets/8805f914-298f-4775-bb35-9c41b10ebe8b)

**Desktop (please complete the following information):**
 - OS: Windows  Must appear
 - Browser Chrome

**Comment by etrepum** [comment]
I think you've reported this bug to the wrong project, I would report this over at https://github.com/mdx-editor/editor
