### ISSUE TITLE
Bug: getDOMCellFromCords incorrect for merged cells

### ISSUE THREAD

**Issue by ivailop7** [facebook/lexical#6999]
Lexical version: 0.22

## Steps To Reproduce

1. Add a table (4x4)
2. Merge four cells in a 2x2 layout
3. Simplest way to demo is by using the arrow key navigation
4. Click on the top cell in the column where the merged cell starts and press 'Down Arrow' key
5. Selection gets moved to right cell

https://github.com/user-attachments/assets/80b6ea49-aa07-4adb-9848-88c4e8bebc12

**Comment by ivailop7** [comment]
I'm trying to add a method that gets all cells in a column (trying to add 'sort by column values feature'), but I never got the correct output, which is how I narrowed it down to 'getDOMCellFromCords'

**Comment by etrepum** [comment]
Oh yeah those cords (sic) functions are all wrong, but I don't think you can fix them without breaking backwards compatibility. The coordinates they use are DOM based, not row/column based.

**Comment by ivailop7** [comment]
Noted, I'll come up with a workaround for my use case.

**Comment by etrepum** [comment]
Not at a computer to look anything up, but I would use the function that builds the table representation where you have a rectangular 2D array of rows x cols and work from that. Avoid anything that needs DOM other than finding the initial cell node. In the best case when you're working with DOM you're using a potentially stale model based on the last reconciliation.

**Comment by ivailop7** [comment]
> Not at a computer to look anything up, but I would use the function that builds the table representation where you have a rectangular 2D array of rows x cols and work from that. Avoid anything that needs DOM other than finding the initial cell node. In the best case when you're working with DOM you're using a potentially stale model based on the last reconciliation.

Thanks for the advice! I'll give it a go.
