### ISSUE TITLE
Bug: Editor depends on white-space: pre-wrap for spacebar to work

### ISSUE THREAD

**Issue by steveluscher** [facebook/lexical#71]
## Repro

1. Remove `whiteSpace: 'pre-wrap'` from the example app
2. `yarn dev`
3. Type ‘Hello world’

Observe that there is no space between ‘Hello’ and ‘world’ and that the text in the view model becomes `"Helloworld "`

**Comment by hwarmington** [comment]
We have a use case to remove end-of-spaces and would like to use `white-space: normal`. Can we reopen this issue or should I create a new one?
