### ISSUE TITLE
Request: Expand event support in E2E test generator

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#716]
Currently, the E2E test generator doesn't support some key events, like inserting lists. We should add these events to make it easier and more useful to use the generator to repro and report issues. It would also be good if the E2E test generator made use of our testing utility functions when pressing certain key combinations (move to start of line, move to end of line, etc).

**Comment by Rbcoder1** [comment]
Can I Try To Solved It I Am Interested In It 
I Review The Codebase Try To Understand it 
so i think i will do it .

**Comment by acywatson** [comment]
I don't see us having time for this in the near future,
