### ISSUE TITLE
Consider a "splitNode" method on BlockNode

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#725]
This method could be analogous to splitText, except it would split BlockNodes at a certain child index.

class MyCoolNode extends BlockNode {

    function splitNode(index): [MyCoolNode, OutlineNode, MyCoolNode] {
        const splitChild = this.getChildAtIndex(index);
        const previousSiblings = splitChild.previousSiblings();
        const nextSiblings = splitChild.nextSiblings();
        const left = createMyCoolNode();
        const right = createMyCoolNode();
        return [left, splitChild, right];
    }

}

Could be useful for things like inserting lists in the middle of blocks, where we need to split the block in two to put the list in the right position.

**Comment by thegreatercurve** [comment]
We have a $splitNode utility.
