### ISSUE TITLE
REPL for Lexical

### ISSUE THREAD

**Issue by acywatson** [facebook/lexical#880]
We need a way for people to easily hack around on Lexical.

There should be some way to easily see and manipulate a tree. Look at ASTExplorer.net for inspiration.

**Comment by thegreatercurve** [comment]
@acywatson I'm just looking through some old tickets. Could we potentially close this Issue? It's had quite low interest, but some of the behaviour could potentially be incorporated into the Dev Tools (like how React DevTools lets you import profiling data).

**Comment by acywatson** [comment]
Yea it's fine to close - I think the idea will live on, but it needs more fleshing out to be actionable. Thanks!
