### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by zurfyx** [facebook/lexical#892]
Color picker on toolbar

- [ ] Text color
- [ ] Highlight color

**Comment by DannyDouglass** [comment]
@zurfyx is this something I could help contribute? I'm new to the project / repo so any additional details would be helpful if so.

**Comment by zurfyx** [comment]
Sure, go for it! Don't have a mock but something that looks moderately pretty on the top bar would do the trick.

Heads up, I just realized the Lexical part is not a trivial good-first issue but happy to assist in the process. Basically you want to replicate formatText (https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalSelection.js#L931) but instead of format you want to apply a style. You can either abstract it or we can help with this later.

Then, there's a couple important bits here:
1. Performance - we want to be able to pull the value quickly and put it into the DOM
2. Size - Reusing the format flag is possible and cheap as we can convert the color to a number but not sure this optimization is worth. Readability wise and performance it's better to pull the color directly from a property. `__color`
3. Reusability - I'd argue it's a good fit for TextNode because it's a common feature and we can optimize it on the reconciler (i.e. when to merge adjacent TextNodes)

Does this make any sense?

cc @trueadm @acywatson WDYT of the proposed approach?

**Comment by acywatson** [comment]
We probably want to use __style for this:

https://github.com/facebook/lexical/blob/main/packages/lexical/src/nodes/LexicalTextNode.js#L229

There are also helpers for it:

https://github.com/facebook/lexical/blob/3f36d8d6234731d89928b1e11c780a9debafc87a/packages/lexical-selection/src/index.js#L294

**Comment by DannyDouglass** [comment]
@zurfyx @acywatson appreciate the additional context. that gives me some direction to get started. i'll dig in this week and follow up with any additional questions.
